fact_internet_sales:
  stage_fact_internet_sales:
    gcs_path: gcs://advworks-dev-ingestion/fact_internet_sales/

dim_customer:
  stage_dim_customer:
    gcs_path: gcs://advworks-dev-ingestion/dim_customer/

dim_product:
  stage_dim_product:
    gcs_path: gcs://advworks-dev-ingestion/dim_product/