{{
  config(
    materialized = "view",
    alias = "entity_descriptions",
    schema='enterprise_MANUAL'
  )
}}

SELECT 

	 ENTITY_CODE
	,CITY
	,TIMEZONE
	,TIME_FORMAT
	,NAME
	,DEFAULTLANGUAGECODE AS DEFAULT_LANGUAGE_CODE
	,LOCATIONSTATECODE AS LOCATION_STATE_CODE
	,LOCATIONSTATENAMEEN AS LOCATION_STATE_NAME_EN
	,LOCATIONSTATENAMEFR AS LOCATION_STATE_NAME_FR
	,LOCATIONCOUNTRYCODE AS LOCATION_COUNTRY_CODE
	,LOCATIONCOUNTRYNAMEEN AS LOCATION_COUNTRY_NAME_EN
	,LOCATIONCOUNTRYNAMEFR  AS LOCATION_COUNTRY_NAME_FR 

from {{ source("landing_enterprise", "ENTITY_DESCRIPTIONS") }}