{{
  config(
    materialized = "view",
    alias = "project_divisions",
    schema='CTM'
  )
}}

SELECT
NULLIF(TRIM(ID::STRING), '') AS ID
,NULLIF(TRIM(PROJECT_ID::STRING), '') AS PROJECT_ID
,NULLIF(TRIM(CODE::STRING), '') AS CODE
,NULLIF(TRIM(DESCRIPTION::STRING), '') AS DESCRIPTION
,TO_TIMESTAMP_NTZ(DUE_DATE::STRING) AS DUE_DATE
,TO_BOOLEAN(SPECIAL_ATTENTION::STRING) AS SPECIAL_ATTENTION
,TO_BOOLEAN(BUILD_MASTER::STRING) AS BUILD_MASTER
,NULLIF(TRIM(COMMENT::STRING), '') AS COMMENT
,SPM_DIVISION_ID::INTEGER AS SPM_DIVISION_ID
,NULLIF(TRIM(DISCRIMINATOR::STRING), '') AS DISCRIMINATOR
,TO_TIMESTAMP_NTZ(DELIVERY_DATE::STRING) AS DELIVERY_DATE
,TO_TIMESTAMP_NTZ(TARGET_RFI_END_DATE::STRING) AS TARGET_RFI_END_DATE
,TO_TIMESTAMP_NTZ(TARGET_TIE_JOIST_OUT::STRING) AS TARGET_TIE_JOIST_OUT
,TO_TIMESTAMP_NTZ(TARGET_DRAWINGS_OUT_DATE::STRING) AS TARGET_DRAWINGS_OUT_DATE
,TO_TIMESTAMP_NTZ(FABRICATION_DUE_DATE::STRING) AS FABRICATION_DUE_DATE
,TO_TIMESTAMP_NTZ(ENGINEERING_DUE_DATE::STRING) AS ENGINEERING_DUE_DATE
,TO_BOOLEAN(FABRICATION_DUE_DATE_CONFIRMED::STRING) AS FABRICATION_DUE_DATE_CONFIRMED
,TO_BOOLEAN(ENGINEERING_DUE_DATE_CONFIRMED::STRING) AS ENGINEERING_DUE_DATE_CONFIRMED
,TO_TIMESTAMP_NTZ(DRAWINGS_RECEIVED_DATE::STRING) AS DRAWINGS_RECEIVED_DATE
,NULLIF(TRIM(QUOTATION_UUID::STRING), '') AS QUOTATION_UUID
,TO_TIMESTAMP_NTZ(ESTIMATION_TARGET_DATE::STRING) AS ESTIMATION_TARGET_DATE
,DROP_DEADTIME_IN_MINUTES::INTEGER AS DROP_DEADTIME_IN_MINUTES
,TO_TIMESTAMP_NTZ(TARGET_RFI2_END_DATE::STRING) AS TARGET_RFI2_END_DATE
,TO_TIMESTAMP_NTZ(CLIENT_APPROVAL_DATE::STRING) AS CLIENT_APPROVAL_DATE
,COPY_CTM_TASKSFROM::INTEGER AS COPY_CTM_TASKSFROM
,TO_BOOLEAN(COPY_CTM_ADVANCEMENT::STRING) AS COPY_CTM_ADVANCEMENT
FROM {{ref('prep_project_divisions')}}
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY ID 
    ORDER BY METADATA_FILE_LAST_MODIFIED DESC
) = 1