{{
  config(
    materialized = "view",
    alias = "projects",
    schema='CTM'
  )
}}

SELECT
 ID::string AS ID
,CODE::string AS CODE
,NAME::string AS NAME
,LEED::string AS LEED
,BUILD_MASTER::string AS BUILD_MASTER
,SPECIAL_ELEMENTS::string AS SPECIAL_ELEMENTS
,COMMENTS::string AS COMMENTS
,CUSTOMER::string AS CUSTOMER
,PROJECT_COORDINATOR_LDAP_ID::string AS PROJECT_COORDINATOR_LDAP_ID
,PROJECT_MANAGER_LDAP_ID::string AS PROJECT_MANAGER_LDAP_ID
,PRIORITY::string AS PRIORITY
,STATUS::string AS STATUS
,STATUS_COMMENTS::string AS STATUS_COMMENTS
,SPM_PROJECT_ID::string AS SPM_PROJECT_ID
,DISCRIMINATOR::string AS DISCRIMINATOR
,WEIGHT_INCREASE_COMMENT::string AS WEIGHT_INCREASE_COMMENT
,DESIGN_COMPLETED::string AS DESIGN_COMPLETED
,PROJECT_TYPE_ID::string AS PROJECT_TYPE_ID
,CREATION_DATE_TIME::string AS CREATION_DATE_TIME
,QUOTATION_UUID::string AS QUOTATION_UUID
,SALES_REPRESENTATIVE_LDAP_ID::string AS SALES_REPRESENTATIVE_LDAP_ID
,DIRECT_DESIGN::string AS DIRECT_DESIGN
,MASTER_JOB_NO::string AS MASTER_JOB_NO
,PROJECT_FILES_SUB_FOLDER::string AS PROJECT_FILES_SUB_FOLDER
,PROJECT_FILES_CONFIGURATION_ID::string AS PROJECT_FILES_CONFIGURATION_ID
,STATUS_UPDATE_DATE_TIME::string AS STATUS_UPDATE_DATE_TIME
,QUOTATION_NUMBER::string AS QUOTATION_NUMBER
,PACKAGE::string AS PACKAGE
,ISSUED_FOR_BUDGET::string AS ISSUED_FOR_BUDGET
FROM {{ref('prep_projects')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY METADATA_FILE_LAST_MODIFIED DESC) = 1


