{{
  config(
    materialized = "view",
    alias = "project_division_products",
    schema='CTM'
  )
}}

SELECT
NULLIF(TRIM(ID::STRING), '') AS ID
,NULLIF(TRIM(PROJECT_DIVISION_ID::STRING), '') AS PROJECT_DIVISION_ID
,NULLIF(TRIM(PROJECT_PRODUCT_ID::STRING), '') AS PROJECT_PRODUCT_ID
,NULLIF(TRIM(PROCESS_TEMPLATE_ID::STRING), '') AS PROCESS_TEMPLATE_ID
,NULLIF(TRIM(SEGMENT_ID::STRING), '') AS SEGMENT_ID
,NULLIF(TRIM(STATUS::STRING), '')::INTEGER AS STATUS
,NULLIF(TRIM(STATUS_COMMENT::STRING), '') AS STATUS_COMMENT
,NULLIF(TRIM(DISCRIMINATOR::STRING), '') AS DISCRIMINATOR
,TO_BOOLEAN(MANUALLY_IGNORED::STRING) AS MANUALLY_IGNORED
,NULLIF(TRIM(STARTING_DATE_OFFSET::STRING), '')::INTEGER AS STARTING_DATE_OFFSET
,TO_TIMESTAMP_NTZ(STARTING_DATE::STRING) AS STARTING_DATE
FROM {{ref('prep_project_division_products')}}
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY ID 
    ORDER BY METADATA_FILE_LAST_MODIFIED DESC, METADATA_FILE_ROW_NUMBER DESC
) = 1