{{
  config(
    materialized = "view",
    alias = "tasks",
    schema='CTM'
  )
}}

SELECT
UNIQUE_ID::string AS UNIQUE_ID
,NULLIF(TRIM(TITLE::string),'') AS TITLE
,STATUS::INTEGER AS STATUS
,DIVISION_DUE_DATE_DELTA::INTEGER AS DIVISION_DUE_DATE_DELTA
,TO_TIMESTAMP_NTZ(STATUS_UPDATE_DATE::string) AS STATUS_UPDATE_DATE
,NULLIF(TRIM(PROJECT_DIVISION_PRODUCT_ID::string),'') AS PROJECT_DIVISION_PRODUCT_ID
,REMAINING_HOURS::NUMBER(18,2) AS REMAINING_HOURS
,ESTIMATED_HOURS::NUMBER(18,2) AS ESTIMATED_HOURS
,PRIORITY::INTEGER AS PRIORITY
,NULLIF(TRIM(STATUS_COMMENTS::string),'') AS STATUS_COMMENTS
,COMPLEXITY::INTEGER AS COMPLEXITY
,"ORDER"::INTEGER AS "ORDER"
,NULLIF(TRIM(ASSIGNED_USERID::string),'') AS ASSIGNED_USERID
,NULLIF(TRIM(RESPONSIBLE_PROJECT_PRODUCT_TEAMID::string),'') AS RESPONSIBLE_PROJECT_PRODUCT_TEAMID
,NULLIF(TRIM(NOTES::string),'') AS NOTES
,TO_TIMESTAMP_NTZ(FIXED_DUE_DATE::string) AS FIXED_DUE_DATE
,NULLIF(TRIM(PROJECT_TYPE_TASK_CODE_ID::string),'') AS PROJECT_TYPE_TASK_CODE_ID
,NULLIF(TRIM(DUE_DATE_LINKED_TYPE_ID::string),'') AS DUE_DATE_LINKED_TYPE_ID
,TO_TIMESTAMP_NTZ(REAL_DUE_DATE::string) AS REAL_DUE_DATE
,REAL_HOURS::NUMBER(18,2) AS REAL_HOURS
,ID::INTEGER AS ID
,TEMPLATE_ESTIMATED_HOURS::NUMBER(18,2) AS TEMPLATE_ESTIMATED_HOURS
,NULLIF(TRIM(PROCESS_TEMPLATE_ID::string),'') AS PROCESS_TEMPLATE_ID
FROM {{ref('prep_tasks')}}
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY UNIQUE_ID 
    ORDER BY METADATA_FILE_LAST_MODIFIED DESC
) = 1