{{
  config(
    materialized = "view",
    alias = "item_whs_d",
    schema='spm_ca'
  )
}}
  SELECT
 UPPER(IN_ENTITY::string) AS IN_ENTITY
,UPPER(ITEM_NO::string) AS ITEM_NO
,UPPER(WHS_CODE::string) AS WHS_CODE
,QTY_ON_HAND::INTEGER AS QTY_ON_HAND
,ON_HAND_DATE::DATE AS ON_HAND_DATE
,QTY_CUST_ORD::INTEGER AS QTY_CUST_ORD
,QTY_ALLOC::INTEGER AS QTY_ALLOC
,QTY_ON_PPS::INTEGER AS QTY_ON_PPS
,QTY_ON_PO::INTEGER AS QTY_ON_PO
,COST::DOUBLE AS COST
,COST_DATE::DATE AS COST_DATE
,LAST_COST::double AS LAST_COST
,LAST_CT_DATE::DATE AS LAST_CT_DATE
,OHU_COUNT::INTEGER AS OHU_COUNT
,COMPUTED_MIN::INTEGER AS COMPUTED_MIN
,OPENING_QTY::INTEGER AS OPENING_QTY
,OPENING_AMT::DOUBLE AS OPENING_AMT
,CLASS::string AS CLASS
,COS_YTD::DOUBLE AS COS_YTD
,QTY_YTD::INTEGER AS QTY_YTD
,COST_DPV::DOUBLE AS COST_DPV
,TOTAL_COST::DOUBLE AS TOTAL_COST
,OLD_QTY_OH::INTEGER AS OLD_QTY_OH
,QTY_ON_MEMO::INTEGER AS QTY_ON_MEMO
,ORDER_LEVEL::INTEGER AS ORDER_LEVEL
,QTY_ON_BUNDLE::INTEGER AS QTY_ON_BUNDLE
,LAST_PC_DATE::DATE AS LAST_PC_DATE
,NULLIF(TRIM(CREATEDBY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(CREATEDDATE::string) AS CREATED_DATE
,TO_TIMESTAMP_NTZ(MODIFIEDDATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIEDBY::string), '') AS MODIFIED_BY
  from {{ref('prep_item_whs_d')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'