{{
  config(
    materialized = "view",
    alias = "projetx_l",
    schema='spm_ca'
  )
}}
  SELECT
UPPER(ENTITY_CODE::string) AS ENTITY_CODE
,UPPER(TRIM(NO_ESTIME::string)) AS NO_ESTIME
,NO_PRODUIT::INTEGER AS NO_PRODUIT
,TO_BOOLEAN(TYPE_PROJET::string) AS TYPE_PROJET
,UPPER(SLSMN_CODE::string) AS SLSMN_CODE
,TO_BOOLEAN(TYPE_FACT::string) AS TYPE_FACT
,QTE_BUDGETE::DOUBLE AS QTE_BUDGETE
,QTE_ESTIME::DOUBLE AS QTE_ESTIME
,SURFACE::DOUBLE AS SURFACE
,NBR_POUTR::INTEGER AS NBR_POUTR
,TMPS_STD_EI_1::string AS TMPS_STD_EI_1
-- always 0
--,TMPS_STD_EI_2::string AS TMPS_STD_EI_2
-- always 0
--,TMPS_STD_EI_3::string AS TMPS_STD_EI_3
-- always 0
--,TMPS_STD_EI_4::string AS TMPS_STD_EI_4
-- always 0
--,TMPS_STD_EI_5::string AS TMPS_STD_EI_5
-- always 0
--,TMPS_STD_EI_6::string AS TMPS_STD_EI_6
,MNT_EST_INFO::DOUBLE AS MNT_EST_INFO
,NET_SALE::DOUBLE AS NET_SALE
,PST_QUOTED::DOUBLE AS PST_QUOTED
,NET_U_PRICE::DOUBLE AS NET_U_PRICE
,TO_BOOLEAN(IND_F_CONN::string) AS IND_F_CONN
,TO_BOOLEAN(WASTE_OUT::string) AS WASTE_OUT
,TO_BOOLEAN(INV_CAT::string) AS INV_CAT
,SEQ_NO::INTEGER AS SEQ_NO
,TMPS_STD_E_1::DOUBLE AS TMPS_STD_E_1
-- always 0
--,TMPS_STD_E_2::DOUBLE AS TMPS_STD_E_2
-- always 0
--,TMPS_STD_E_3::DOUBLE AS TMPS_STD_E_3
-- always 0
--,TMPS_STD_E_4::DOUBLE AS TMPS_STD_E_4
-- always 0
--,TMPS_STD_E_5::DOUBLE AS TMPS_STD_E_5
-- always 0
--,TMPS_STD_E_6::DOUBLE AS TMPS_STD_E_6
-- always 0
--,TMPS_STD_E_7::DOUBLE AS TMPS_STD_E_7
,COMPLEX_CODE::INTEGER AS COMPLEX_CODE
,ESTIM_DET::DOUBLE AS ESTIM_DET
,ESTIM_DES::DOUBLE AS ESTIM_DES
,DSG_COST_1::DOUBLE AS DSG_COST_1
,DSG_COST_2::DOUBLE AS DSG_COST_2
-- always 0
--,DSG_COST_3::DOUBLE AS DSG_COST_3
-- always 0
--,DSG_COST_4::DOUBLE AS DSG_COST_4
-- always 0
--,DSG_COST_5::DOUBLE AS DSG_COST_5
-- always 0
--,DSG_COST_6::DOUBLE AS DSG_COST_6
-- always blank
--,OFFICE_CODE::string AS OFFICE_CODE
-- always blank
--,BRANCH_OFFICE_CODE::string AS BRANCH_OFFICE_CODE
,NBR_ESCORT::INTEGER AS NBR_ESCORT
,COST::DOUBLE AS COST
,VENDOR_ID::INTEGER AS VENDOR_ID
,NULLIF(VENDOR_NAME::string,'') AS VENDOR_NAME
,REVENUE_QUANTITY_TYPE_UUID::string AS REVENUE_QUANTITY_TYPE_UUID
,PROJETX_L_UUID::string AS PROJETX_L_UUID
,ROW_ID::string AS ROW_ID
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
  from {{ref('prep_projetx_l')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'