{{
 config(
 materialized = "view",
 alias = "receipt_line",
 schema='spm_ca'
 )
}}
SELECT
 UPPER(AP_ENTITY::string) AS AP_ENTITY
,UPPER(IN_ENTITY::string) AS IN_ENTITY
,UPPER(ENTITY_CODE::string) AS ENTITY_CODE
,UPPER(WHS_CODE::string) AS WHS_CODE
,NULLIF(TRIM(UPPER(PO_NO::string)),'') AS PO_NO
--Always 0
--,RELEASE_NO::integer AS RELEASE_NO
,NULLIF(TRIM(UPPER(VENDOR_CODE::string)),'') AS VENDOR_CODE
,CURRENCY_COD::string AS CURRENCY_COD
,CONV_MONEY::double AS CONV_MONEY
,NULLIF(TRIM(UPPER(JOB_NO::string)),'') AS JOB_NO
,LINE_NO::integer AS LINE_NO
,REQUEST_DATE::date AS REQUEST_DATE
,PROMISE_DATE::date AS PROMISE_DATE
,NULLIF(TRIM(UPPER(ITEM_NO::string)),'') AS ITEM_NO
,DESCRIPTION::string AS DESCRIPTION
,UOM_CODE::string AS UOM_CODE
,NULLIF(TRIM(UPPER(ITEM_VENDOR::string)),'')  AS ITEM_VENDOR
,NULLIF(TRIM(UPPER(UOM_VENDOR::string)),'')  AS UOM_VENDOR
,CONV_UOM::double AS CONV_UOM
,FOB_VENDOR::double AS FOB_VENDOR
,NULLIF(TRIM(UPPER(RECEIPT_CODE::string)),'') AS RECEIPT_CODE
,LINE_DISC::double AS LINE_DISC
,DUTY_CODE::string AS DUTY_CODE
,DUTY_PCT::double AS DUTY_PCT
,TAX_RATE_1::string AS TAX_RATE_1
,TAX_RATE_2::string AS TAX_RATE_2
,TAX_RATE_3::string AS TAX_RATE_3
,MISC_PCT::double AS MISC_PCT
,NULLIF(TRIM(UPPER(RECEIPT_NO::string)),'') AS RECEIPT_NO
,RCPT_LINE_NO::integer AS RCPT_LINE_NO
,RECEIPT_DATE::date AS RECEIPT_DATE
,PO_DISC::double AS PO_DISC
--100% blank
--,LOT::string AS LOT
,NET_COST::double AS NET_COST
,LANDED_COST::double AS LANDED_COST
,QTY_RECEIVED::integer AS QTY_RECEIVED
,QTY_TO_RCVE::integer AS QTY_TO_RCVE
,RCPT_VALUE::double AS RCPT_VALUE
,CHANGED_QTY::integer AS CHANGED_QTY
,COST_METHOD::string AS COST_METHOD
,TO_BOOLEAN(PO_EXIST::string) AS PO_EXIST
,SEQ_NO::double AS SEQ_NO
,FR_COST::double AS FR_COST
,NET_EXTEND::double AS NET_EXTEND
,QTY_INVOICED::double AS QTY_INVOICED
,JC_QTY::integer AS JC_QTY
,JC_AMT::double AS JC_AMT
,NULLIF(TRIM(UPPER(CANSIS_TRANSF_DATE::string)),'') AS CANSIS_TRANSF_DATE
,INITCAP(NULLIF(TRIM(CMG_COUNTRY::string),'')) AS CMG_COUNTRY
,TO_BOOLEAN(CERTIF::string) AS CERTIF
,NULLIF(TRIM(UPPER(COUNTRY_CODE::string)),'') AS COUNTRY_CODE
,NULLIF(TRIM(CREATED_BY::string),'') AS CREATED_BY
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string),'') AS MODIFIED_BY
,UPPER(NULLIF(TRIM(STEEL_MILL_UUID::string),'')) AS STEEL_MILL_UUID
FROM 
    {{ref('prep_receipt_line')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'