{{
  config(
    materialized = "view",
    alias = "in_control",
    schema='spm_ca'
  )
}}
  SELECT
  UPPER(NULLIF(IN_ENTITY, '')::string) AS IN_ENTITY
,NULLIF(IN_YR, '')::integer AS IN_YR
,NULLIF(IN_PRD, '')::integer AS IN_PRD
--100% 12
--,NUMBER_PRD::integer AS NUMBER_PRD
,NULLIF(WHS_CODE, '')::string AS WHS_CODE
,NULLIF(UOM_CODE, '')::string AS UOM_CODE
,NULLIF(COST_METHOD,'')::string AS COST_METHOD
--100% null
--,BREAK_CODE::string AS BREAK_CODE
--100% null
--,PROD_GROUP::string AS PROD_GROUP
--100% 0
--,PR_GP_LENGTH::integer AS PR_GP_LENGTH
,UPPER(NULLIF(ENTITY_INV, '')::string) AS ENTITY_INV
,NULLIF(ENTITY_WIP, '')::integer AS ENTITY_WIP
--100% L
--,MLI::string AS MLI
--100% 1
--,ALLOW_BO::string AS ALLOW_BO
--100% null
--,MISC_CODE::string AS MISC_CODE
,NULLIF(GL_PHYSICAL, '')::string AS GL_PHYSICAL
,NULLIF(VIEW_LOGIN, '')::string AS VIEW_LOGIN
,NULLIF(UDM_ALT, '')::string AS UDM_ALT
--100% 0
--,FACTEUR::string AS FACTEUR
,NULLIF(COIL_GROUP, '')::string AS COIL_GROUP
--100% 0
--,MESURE::string AS MESURE
,NULLIF(DECK_GROUP, '')::string AS DECK_GROUP
,NULLIF(DESGO_VERSANT, '')::string::boolean AS DESGO_VERSANT
--100% null
--,SLIT_GROUP::string AS SLIT_GROUP
--100% 0
--,DUTY_FREE_RATE::string AS DUTY_FREE_RATE
,NULLIF(IN_CONTROL_UUID, '')::string AS IN_CONTROL_UUID
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
  from {{ref('prep_in_control')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'