{{
  config(
    materialized = "view",
    alias = "item",
    schema='spm_ca'
  )
}}

SELECT
 UPPER(IN_ENTITY::string) AS IN_ENTITY
,UPPER(ITEM_NO::string) AS ITEM_NO
,UPPER(SORT_NAME::string) AS SORT_NAME
,UPPER(UOM_CODE::string) AS UOM_CODE
,STATS_CODE::string AS STATS_CODE
,UPPER(NULLIF(TRIM(BREAK_CODE::string), '')) AS BREAK_CODE
--100 % EMPTY
--,PRICING_GRP::string AS PRICING_GRP
,UPPER(NULLIF(TRIM(VENDOR_CODE::string), '')) AS VENDOR_CODE
-- ALWAYS 0
--,VOLUME::DOUBLE AS VOLUME
,WEIGHT::DOUBLE AS WEIGHT
,UPPER(NULLIF(TRIM(STATUS_CODE::string), '')) AS STATUS_CODE
,TO_BOOLEAN(ACTIVE::string) AS ACTIVE
,NULLIF(TRIM(DUTY_CODE::string), '') AS DUTY_CODE
-- 100% EMPTY
--,LAST_PO_NO::string AS LAST_PO_NO
-- 100% EMPTY
--,LAST_REL_NO::INTEGER AS LAST_REL_NO
,UPPER(UDM_ALT::string) AS UDM_ALT
,FACTEUR::DOUBLE AS FACTEUR
,MESURE::INTEGER AS MESURE
,IFNULL(MILL_COST::DOUBLE,0) AS MILL_COST
,WHS_RATE::INTEGER AS WHS_RATE
,NULLIF(TRIM(REV_COST_DATE::date), '') AS REV_COST_DATE
-- ALWAYS 0
--,EST_COST::DOUBLE AS EST_COST
,EPIX_SEQ::INTEGER AS EPIX_SEQ
,TO_TIMESTAMP_NTZ(CREATED_DATE::string)  AS CREATED_DATE
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,GLOBAL_ITEM_UUID::string AS GLOBAL_ITEM_UUID
,NULLIF(TRIM(ITEM_UUID::string), '') AS ITEM_UUID
,NULLIF(TRIM(STEEL_GRADE_UUID::string), '') AS STEEL_GRADE_UUID
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
FROM {{ref('prep_item')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'