{{
  config(
    materialized = "view",
    alias = "qc_quotation",
    schema='spm_ca',
    meta = {
        'table_key': 'QC_QUOTATION_SK',
        'tests': {
            'null_values':{
                'columns':[
                    'RDM_ACTIVE_STATUS_CODE',
                    'RDM_SALES_OFFICE_DEPARTMENT_CODE',
                    'RDM_PROJECT_STEP'
                ]
            }
        }
    }
  )
}}


WITH raw_qc_quotation AS (
  SELECT * FROM {{ref('prep_qc_quotation')}}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'
)

SELECT
{{ dbt_utils.generate_surrogate_key(["NULLIF(UPPER(TRIM(QQ.OFFICE_CODE::string)),'')","COALESCE(QQ.JOB_NO::string, '')"]) }} as QC_QUOTATION_SK 
,NULLIF(UPPER(TRIM(QQ.OFFICE_CODE::string)),'') AS OFFICE_CODE
,COALESCE(QQ.JOB_NO::string, '') AS JOB_NO -- null removed to simplify the use of the primary key
,QQ.MASTER_JOB_NO::string AS MASTER_JOB_NO
,NULLIF(TRIM(QQ.STATUS1::string), '') AS STATUS1
,NULLIF(TRIM(QQ.STATUS2::string), '') AS STATUS2
,QQ.STATUS1_NO::INTEGER AS STATUS1_NO
,QQ.STATUS2_NO::INTEGER AS STATUS2_NO
,NULLIF(TRIM(QQ.NO_PROJET::string), '') AS NO_PROJET
,INITCAP(NULLIF(TRIM(QQ.PROJ_NAME::string), '')) AS PROJ_NAME
,TO_BOOLEAN(QQ.ACTIVE::string) AS ACTIVE
,QQ.CENTURY::INTEGER AS CENTURY
,INITCAP(NULLIF(TRIM(QQ.CITY::string), '')) AS CITY
,QQ.PROPST_NO::INTEGER AS PROPST_NO
,QQ.DESIGN_CODE::INTEGER AS DESIGN_CODE
,QQ.INSCRP_DATE::DATE AS INSCRP_DATE
,QQ.RECALL_DATE::DATE AS RECALL_DATE
,QQ.BID_DATE::DATE AS BID_DATE
,UPPER(NULLIF(TRIM(QQ.SALESM_INIT_CODE::string),'')) AS SALESM_INIT_CODE
,UPPER(NULLIF(TRIM(QQ.ESTIMT_INIT_CODE::string), '')) AS ESTIMT_INIT_CODE
,QQ.PRICE::DOUBLE AS PRICE
,NULLIF(TRIM(QQ.PROJCT_STEP),'')::INTEGER AS PROJCT_STEP
,QQ.NB_ALT::INTEGER AS NB_ALT
,TO_BOOLEAN(QQ.STATUS_CONTRC::string) AS STATUS_CONTRC
,QQ.ESTIMT_SHIP_DATE::DATE AS ESTIMT_SHIP_DATE
,QQ.ISSUED_FOR::INTEGER AS ISSUED_FOR
,QQ.GC_CLOSE_DATE::DATE AS GC_CLOSE_DATE
,NULLIF(TRIM(QQ.GENERAL_NOTE::string), '') AS GENERAL_NOTE
,UPPER(NULLIF(QQ.SHIP_TERR_CODE::string,'')) AS SHIP_TERR_CODE
-- ALWAYS NULL
--,NULLIF(TRIM(QQ.SALE_TERR_CODE::string),'') AS SALE_TERR_CODE
,QQ.FOLLOW_DATE::DATE AS FOLLOW_DATE
,UPPER(NULLIF(TRIM(QQ.SPM_ENTITY_CODE::string),'')) AS SPM_ENTITY_CODE
,QQ.XTRA_NO::INTEGER AS XTRA_NO
,QQ.SPM_DATE::DATE AS SPM_DATE
,QQ.LONGEST::DOUBLE AS LONGEST
,QQ.CONTRC_COMPT_NO::INTEGER AS CONTRC_COMPT_NO
,QQ.CONTRC_DATE::DATE AS CONTRC_DATE
,NULLIF(TRIM(QQ.CONTRC_NOTE::string), '') AS CONTRC_NOTE
,INITCAP(NULLIF(TRIM(QQ.NOM_CONTACT::string), '')) AS NOM_CONTACT
,QQ.D_LIVRAISON::DATE AS D_LIVRAISON
,QQ.D_ESTIME::DATE AS D_ESTIME
,NULLIF(TRIM(QQ.NO_CONTRAT_V::string), '') AS NO_CONTRAT_V
,NULLIF(TRIM(QQ.NO_BON_ACHAT::string), '') AS NO_BON_ACHAT
,NULLIF(TRIM(QQ.ADRESSE_LIV_1::string), '') AS ADRESSE_LIV_1
,NULLIF(TRIM(QQ.ADRESSE_LIV_2::string), '') AS ADRESSE_LIV_2
,NULLIF(TRIM(QQ.ADRESSE_LIV_3::string), '') AS ADRESSE_LIV_3
,NULLIF(QQ.FOB_CODE::string,'') AS FOB_CODE
,NULLIF(TRIM(QQ.MEMO::string), '') AS MEMO
,NULLIF(TRIM(QQ.DUMMY::string,'"|'),'') AS DUMMY
,NULLIF(QQ.USER_CODE::string,'') AS USER_CODE
,INITCAP(QQ.DSG_ENTITY_CODE::string) AS DSG_ENTITY_CODE
-- always null
--,QQ.MARKUP_WEIGHT_PERCENT::INTEGER AS MARKUP_WEIGHT_PERCENT
-- always null
--,QQ.MARKUP_WEIGHT::INTEGER AS MARKUP_WEIGHT
-- always null
--,QQ.MARKUP_PRICE_PERCENT::INTEGER AS MARKUP_PRICE_PERCENT
-- always null
--,QQ.MARKUP_PRICE_DOLLAR::string AS MARKUP_PRICE_DOLLAR
-- always 0
--,QQ.MARKUP_PRICE::string AS MARKUP_PRICE
-- always False
--,TO_BOOLEAN(QQ.MARKUP_OPENING_FEE::string) AS MARKUP_OPENING_FEE
-- always 0
--,QQ.MARKUP_ROUNDING::string AS MARKUP_ROUNDING
-- always True
--,TO_BOOLEAN(QQ.MESURE::string) AS MESURE
-- always NULL
--,QQ.DESIGN_DATE::DATE AS DESIGN_DATE
-- always NULL
--,NULLIF(TRIM(QQ.DESIGN_DESC::string), '') AS DESIGN_DESC
,TO_BOOLEAN(QQ.ADDEND::string) AS ADDEND
-- always NULL
--,QQ.ADDEND_DATE::DATE AS ADDEND_DATE
,NULLIF(TRIM(QQ.ADDEND_DESC::string), '') AS ADDEND_DESC
-- always NULL
--,TO_BOOLEAN(QQ.SPECFC::string) AS SPECFC
-- always NULL
--,QQ.SPECFC_DATE::DATE AS SPECFC_DATE
,NULLIF(TRIM(QQ.SPECFC_DESC::string), '') AS SPECFC_DESC
,NULLIF(TRIM(QQ.INPUT_BY_INIT_CODE::string), '') AS INPUT_BY_INIT_CODE
,QQ.PO_DATE::DATE AS PO_DATE
,UPPER(NULLIF(TRIM(QQ.COUNTRY::string),'')) AS COUNTRY
,UPPER(NULLIF(TRIM(QQ.COUNTY_CODE::string), '')) AS COUNTY_CODE
,TO_BOOLEAN(QQ.DECK::string) AS DECK
,NULLIF(TRIM(UPPER(REGEXP_REPLACE(QQ.ZIP_CODE::string,'[-\\s.*]',''))), '') AS ZIP_CODE
,INITCAP(NULLIF(TRIM(REGEXP_REPLACE(TRIM(UPPER(QQ.INPUT_BY_NAME::string)), '(ENTER A NEW RESPOSIBLE|PROCESSING){1,}', '')), '')) AS INPUT_BY_NAME
,NULLIF(UPPER(TRIM(QQ.BRANCH_OFFICE_CODE::string)), '') AS BRANCH_OFFICE_CODE
,QQ.PROJCT_SURFACE::INTEGER AS PROJCT_SURFACE
,UPPER(NULLIF(TRIM(QQ.ST::string),'')) AS ST
,TO_BOOLEAN(QQ.APPLY_FEE::string) AS APPLY_FEE
-- always 0
--,QQ.PUBLIC::INTEGER AS PUBLIC
-- always 0
--,QQ.OPENING_FEE::INTEGER AS OPENING_FEE
,NULLIF(TRIM(QQ.CLASS_CATEG::string), '') AS CLASS_CATEG
,NULLIF(TRIM(QQ.CLASS_CODE::string), '') AS CLASS_CODE
,TO_BOOLEAN(QQ.FOLLOW_UP::string) AS FOLLOW_UP
,TIMESTAMPADD(second , QQ.LAST_UPDATE_TIME::INTEGER ,QQ.LAST_UPDATE_DATE::DATE ) AS LAST_UPDATE_DATETIME 
,TO_BOOLEAN(QQ.HOT::string) AS HOT
,QQ.LOST_DATE::DATE AS LOST_DATE
,QQ.MARK_QTY::INTEGER AS MARK_QTY
,QQ.STANDING_ID::INTEGER AS STANDING_ID
,INITCAP(NULLIF(TRIM(QQ.CONTRC_COMPT_OFFICE_CODE::string),'')) AS CONTRC_COMPT_OFFICE_CODE
,QQ.ROUND_TO_FACTOR::INTEGER AS ROUND_TO_FACTOR
,CASE 
    WHEN NULLIF(TRIM(QQ.CURRENCY_COD::string), '') LIKE 'US%' THEN 'USD' 
    WHEN NULLIF(TRIM(QQ.CURRENCY_COD::string), '') LIKE 'CA%' THEN 'CAD'
    ELSE NULLIF(TRIM(QQ.CURRENCY_COD::string), '') 
 END AS CURRENCY_CODE
-- always null
--,QQ.TRANSFER_DATE::DATE AS TRANSFER_DATE
,QQ.DRAWING_DUE_IN::DATE AS DRAWING_DUE_IN
,NULLIF(TRIM(QQ.SPECIAL_ELEMENTS_NOTE::string),'') AS SPECIAL_ELEMENTS_NOTE
,IFF(TRIM(QQ.PROJ_COORD::string) IN ('', '0'), NULL, LOWER(TRIM(QQ.PROJ_COORD::string))) AS PROJ_COORD
,QQ.EXCHGN_RATE::DOUBLE AS EXCHGN_RATE
,QQ.DRAWING_DUE_BACK::DATE AS DRAWING_DUE_BACK
,QQ.APPROVAL_TYPE::INTEGER AS APPROVAL_TYPE
,QQ.DRAWING_DUE_OUT::DATE AS DRAWING_DUE_OUT
,NULLIF(TRIM(QQ.WEIGHT_INCREASE_COMMENT::string), '') AS WEIGHT_INCREASE_COMMENT
,NULLIF(TRIM(QQ.LOST_STATUS_COMMENT::string), '') AS LOST_STATUS_COMMENT
,NULLIF(TRIM(QQ.LAST_LOADED_ESTIMATION_FILE_NAME::string), '') AS LAST_LOADED_ESTIMATION_FILE_NAME
,TO_TIMESTAMP_NTZ(QQ.LAST_LOADED_ESTIMATION_FILE_DATETIME) AS LAST_LOADED_ESTIMATION_FILE_DATETIME
,NULLIF(TRIM(QQ.CONTRC_BUYER_CONTACT_UUID::string),'') AS CONTRC_BUYER_CONTACT_UUID
,NULLIF(TRIM(QQ.CONTRC_PROJ_MANAGER_CONTACT_UUID::string),'') AS CONTRC_PROJ_MANAGER_CONTACT_UUID
,LOWER(NULLIF(TRIM(QQ.VES_ENTRY_COMPLETED_USER_CODE::string),'')) AS VES_ENTRY_COMPLETED_USER_CODE
,TO_BOOLEAN(QQ.ESTIMATION_INCLUDE_DESIGN::string) AS ESTIMATION_INCLUDE_DESIGN
,TO_BOOLEAN(QQ.LEAD::string) AS LEAD
,UPPER(NULLIF(TRIM(QQ.LEAD_PROSPECTOR_INIT_CODE::string::string),'')) AS LEAD_PROSPECTOR_INIT_CODE
,TO_BOOLEAN(QQ.LEED_CERTIFIED::string) AS LEED_CERTIFIED
,TO_BOOLEAN(QQ.EXTRA_CREDIT::string) AS EXTRA_CREDIT
,QQ.SIGNATORY_APPROVAL_STATUS::INTEGER AS SIGNATORY_APPROVAL_STATUS
-- always 0
--,QQ.SIGNATORY_APPROVED_AMOUNT::DOUBLE AS SIGNATORY_APPROVED_AMOUNT
,NULLIF(TRIM(QQ.BID_CUSTOMER_UUID::string),'') AS BID_CUSTOMER_UUID
,NULLIF(TRIM(QQ.CONTRACT_CUSTOMER_UUID::string),'') AS CONTRACT_CUSTOMER_UUID
,TO_BOOLEAN(QQ.SHOW_ADDRESSES_ON_FPS::string) AS SHOW_ADDRESSES_ON_FPS
,NULLIF(TRIM(QQ.QUOTATION_UUID::string),'') AS QUOTATION_UUID
,QQ.DECK_CALC_SOFT::INTEGER AS DECK_CALC_SOFT
,TO_BOOLEAN(QQ.DOMESTIC_STEEL_ONLY::string) AS DOMESTIC_STEEL_ONLY
,TO_BOOLEAN(QQ.MILL_TEST_REQUIRED::string) AS MILL_TEST_REQUIRED
,NULLIF(TRIM(QQ.LAST_LOADED_ESTIMATION_FILE_LOAD_BY::string), '') AS LAST_LOADED_ESTIMATION_FILE_LOAD_BY
,TO_BOOLEAN(QQ.PROJECT_TYPE::string) AS PROJECT_TYPE
,QQ.QUOTATION_TYPE_UUID::string AS QUOTATION_TYPE_UUID
,TO_BOOLEAN(QQ.LAST_LOADED_ESTIMATION_BUDGET_FORMAT::string) AS LAST_LOADED_ESTIMATION_BUDGET_FORMAT
-- always FALSE
--,TO_BOOLEAN(QQ.DRAFTING_CONTRACT::string) AS DRAFTING_CONTRACT
,NULLIF(TRIM(QQ.QUOTATION_MAIN_PRODUCT::string),'') AS QUOTATION_MAIN_PRODUCT
,QQ.QUOTATION_SENT_DATE::DATE AS QUOTATION_SENT_DATE
,TO_BOOLEAN(QQ.ERECTOR_PRIVILEGE_INCLUDED::string) AS ERECTOR_PRIVILEGE_INCLUDED
,INITCAP(NULLIF(TRIM(QQ.DELIVERY_OFFICE_CODE::string), '')) AS DELIVERY_OFFICE_CODE
,INITCAP(NULLIF(TRIM(QQ.DELIVERY_BRANCH_OFFICE_CODE::string), '')) AS DELIVERY_BRANCH_OFFICE_CODE
,TO_TIMESTAMP_NTZ(QQ.ESTIMATION_TARGET_DATETIME::string) AS ESTIMATION_TARGET_DATETIME
,TO_BOOLEAN(QQ.IS_NATIONAL_ACCOUNT::string) AS IS_NATIONAL_ACCOUNT
,QQ.OPPORTUNITY_RATING::INTEGER AS OPPORTUNITY_RATING
,QQ.OPPORTUNITY_STATUS::INTEGER AS OPPORTUNITY_STATUS
,QQ.OPPORTUNITY_STAGE::INTEGER AS OPPORTUNITY_STAGE
,QQ.COMPLX_CODE::INTEGER AS COMPLX_CODE
,QQ.LOST_PRICE_DELTA::INTEGER AS LOST_PRICE_DELTA
,QQ.CONFIDENCE_RATING::INTEGER AS CONFIDENCE_RATING
,QQ.LOST_TO_COMPT_NO::INTEGER AS LOST_TO_COMPT_NO
,QQ.OPPORTUNITY_DELIEVERY_DATE_SPAN::INTEGER AS OPPORTUNITY_DELIVERY_DATE_SPAN
,QQ.OPPORTUNITY_DELIEVERY_DATE_SPAN_MIN::DATE AS OPPORTUNITY_DELIVERY_DATE_SPAN_MIN
,QQ.OPPORTUNITY_DELIEVERY_DATE_SPAN_MAX::DATE AS OPPORTUNITY_DELIVERY_DATE_SPAN_MAX

-- for adding RDM_PROJECT_STEP from RDM
,RDM.STANDARD_APPLICATION_VALUE AS RDM_PROJECT_STEP

,CASE WHEN NULLIF(TRIM(QQ.OFFICE_CODE ::STRING),'') IS NULL 
  THEN NULL 
  ELSE IFNULL(RDM1.STANDARD_APPLICATION_VALUE,'Not Found') 
  END                                                                 AS RDM_SALES_OFFICE_DEPARTMENT_CODE
,CASE WHEN NULLIF(TRIM(QQ.BRANCH_OFFICE_CODE::STRING),'') IS NULL 
  THEN NULL 
  ELSE IFNULL(RDM_SBOD.STANDARD_APPLICATION_VALUE,'Not Found') 
  END                                                                 AS RDM_SALES_BRANCH_OFFICE_DEPARTMENT_CODE
,CASE WHEN QQ.ACTIVE IS NULL 
  THEN NULL 
  ELSE IFNULL(RDM2.STANDARD_APPLICATION_VALUE,'Not Found') 
  END                                                                 AS RDM_ACTIVE_STATUS_CODE
,CASE WHEN NULLIF(TRIM(QQ.COUNTRY::STRING),'') IS NULL 
  THEN NULL 
  ELSE IFNULL(RDM_C.STANDARD_APPLICATION_VALUE,'Not Found') 
  END                                                                 AS RDM_COUNTRY_CODE

,TO_TIMESTAMP_NTZ(QQ.CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(QQ.CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(QQ.MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(QQ.MODIFIED_BY::string), '') AS MODIFIED_BY
,CASE WHEN NULLIF(TRIM(QQ.OFFICE_CODE ::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM1.STANDARD_APPLICATION_VALUE_NAME_FR,'Not Found')
END                                      AS RDM_SALES_OFFICE_DEPARTMENT_NAME_FR
,CASE WHEN NULLIF(TRIM(QQ.OFFICE_CODE ::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM1.STANDARD_APPLICATION_VALUE_NAME_EN ,'Not Found') 
END                                      AS RDM_SALES_OFFICE_DEPARTMENT_NAME_EN
,CASE WHEN NULLIF(TRIM(QQ.BRANCH_OFFICE_CODE::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM_SBOD.STANDARD_APPLICATION_VALUE_NAME_FR,'Not Found') 
END                                      AS RDM_SALES_BRANCH_OFFICE_DEPARTMENT_NAME_FR
,CASE WHEN NULLIF(TRIM(QQ.BRANCH_OFFICE_CODE::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM_SBOD.STANDARD_APPLICATION_VALUE_NAME_EN ,'Not Found') 
END                                      AS RDM_SALES_BRANCH_OFFICE_DEPARTMENT_NAME_EN
,CASE WHEN NULLIF(TRIM(QQ.COUNTRY::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM_C.STANDARD_APPLICATION_VALUE_NAME_FR,'Not Found') 
END                                      AS RDM_COUNTRY_NAME_FR
,CASE WHEN NULLIF(TRIM(QQ.COUNTRY::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM_C.STANDARD_APPLICATION_VALUE_NAME_EN ,'Not Found') 
END                                      AS RDM_COUNTRY_NAME_EN
,CASE WHEN QQ.ACTIVE IS NULL 
THEN NULL ELSE IFNULL(RDM2.STANDARD_APPLICATION_VALUE_NAME_FR,'Not Found') 
END                                      AS RDM_ACTIVE_STATUS_NAME_FR
,CASE WHEN QQ.ACTIVE IS NULL 
THEN NULL ELSE IFNULL(RDM2.STANDARD_APPLICATION_VALUE_NAME_EN ,'Not Found') 
END                                      AS RDM_ACTIVE_STATUS_NAME_EN

FROM raw_qc_quotation QQ
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM
ON UPPER(QQ.PROJCT_STEP) = UPPER(RDM.BUSINESS_APPLICATION_VALUE) 
AND UPPER(RDM.BUSINESS_APPLICATION_DOMAIN_CODE) = 'PROJECTSTEP' 
AND UPPER(RDM.STANDARD_DOMAIN_APPLICATION_CODE) = 'PROJECTSTEP'
AND UPPER(RDM.BUSINESS_APPLICATION_CODE) = 'SPM'
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM1
ON UPPER(TRIM(QQ.OFFICE_CODE)) = UPPER(TRIM(RDM1.BUSINESS_APPLICATION_VALUE))
AND UPPER(RDM1.BUSINESS_APPLICATION_DOMAIN_CODE) = 'SALESOFFICEDEPARTMENT'
AND UPPER(RDM1.STANDARD_DOMAIN_APPLICATION_CODE) = 'SALESOFFICEDEPARTMENT' 
AND UPPER(RDM1.BUSINESS_APPLICATION_CODE) = 'SPM'
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM_SBOD 
ON UPPER(NULLIF(TRIM(QQ.BRANCH_OFFICE_CODE::STRING),'')) = UPPER(RDM_SBOD.BUSINESS_APPLICATION_VALUE)
AND UPPER(RDM_SBOD.BUSINESS_APPLICATION_DOMAIN_CODE) = 'SALESBRANCHOFFICEDEPARTMENT'
AND UPPER(RDM_SBOD.STANDARD_DOMAIN_APPLICATION_CODE) = 'SALESBRANCHOFFICEDEPARTMENT' 
AND UPPER(RDM_SBOD.BUSINESS_APPLICATION_CODE) = 'SPM'
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM2
ON CAST(QQ.ACTIVE AS INT)= CAST(RDM2.BUSINESS_APPLICATION_VALUE AS INT) 
AND UPPER(RDM2.BUSINESS_APPLICATION_DOMAIN_CODE) = 'ACTIVESTATUS'
AND UPPER(RDM2.STANDARD_DOMAIN_APPLICATION_CODE) = 'ACTIVESTATUS' 
AND UPPER(RDM2.BUSINESS_APPLICATION_CODE) = 'SPM'
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM_C 
ON UPPER(NULLIF(TRIM(QQ.COUNTRY::STRING),'')) = UPPER(RDM_C.BUSINESS_APPLICATION_VALUE)
AND UPPER(RDM_C.BUSINESS_APPLICATION_DOMAIN_CODE) = 'COUNTRY'
AND UPPER(RDM_C.STANDARD_DOMAIN_APPLICATION_CODE) = 'COUNTRY' 
AND UPPER(RDM_C.BUSINESS_APPLICATION_CODE) = 'SPM'