
{{
 config(
 materialized = "view",
 alias = "item_tech",
 schema='spm_ca'
 )
}}

SELECT
 UPPER(IN_ENTITY::string) AS IN_ENTITY
,UPPER(NO_ARTICLE::string) AS NO_ARTICLE
,NULLIF(CODE_REF::string, '') AS CODE_REF
,HAUTEUR::double AS HAUTEUR
,LARGEUR::double AS LARGEUR
,EPAISSEUR::double AS EPAISSEUR
,AIRE::double AS AIRE
,LONG_DEPLOYE::double AS LONG_DEPLOYE
,NULLIF(NULLIF(TRIM(UTILISATION::string), ''), ' ') AS UTILISATION
,FABRICATION::integer AS FABRICATION
,NO_ITEM_NUM::integer AS NO_ITEM_NUM
,SURF_PEINT::double AS SURF_PEINT
,EP_OREILLE::integer AS EP_OREILLE
,UPPER(NULLIF(TRIM(ITEM_ALT_NO::string), '')) AS ITEM_ALT_NO
,UPPER(NULLIF(TRIM(MASTER_ITEM::string), '')) AS MASTER_ITEM
,HOLES_QTY::integer AS HOLES_QTY
,GAGE::integer AS GAGE
,WIDTH_TOLERANCE::double AS WIDTH_TOLERANCE
,THICKNESS_TOLERANCE_MIN::double AS THICKNESS_TOLERANCE_MIN
,THICKNESS_TOLERANCE_MAX::double AS THICKNESS_TOLERANCE_MAX
,NULLIF(TRIM(ITEM_FINISHING_UUID::string), '') AS ITEM_FINISHING_UUID
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
FROM {{ref('prep_item_tech')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'