{{
  config(
    materialized = "view",
    alias = "prodct_machn",
    schema='spm_ca'
  )
}}

SELECT
    -- 100 % NULL
    --BRIDGEPREPARATIONDEFAULTPREPQTY,
    -- 100 % NUL
    --DATA:"BridgePreparationGroupOrder" AS BRIDGEPREPARATIONGROUPORDER,
    UPPER(EQUIPMENTID::string) AS EQUIPMENTID,
    TO_BOOLEAN(STATUSDISPLAY::string) as STATUSDISPLAY,
    TO_BOOLEAN(ACTIVE::string) as ACTIVE,
    AUTOMATIC_PRODUCTION_DATA_PURGE::INTEGER AS AUTOMATIC_PRODUCTION_DATA_PURGE,
    AUTOMATIC_PRODUCTION_ENTRY::integer as AUTOMATIC_PRODUCTION_ENTRY,
    CAPACITY::DOUBLE as CAPACITY,
    DATA_WAREHOUSE_TRANSFER::INTEGER AS DATA_WAREHOUSE_TRANSFER,
    -- 100 % NULL
    --DATA:"date_d_entr" AS DATE_D_ENTR,
    -- 100 % NULL
    --DATA:"date_p_entr" AS DATE_P_ENTR,
    DECK_EMBOSSING::integer as DECK_EMBOSSING,
    DELAY_BEFORE_ASSEMBLY::integer as DELAY_BEFORE_ASSEMBLY,
    DELAY_FOR_REALTIME_CORRECTION::integer as DELAY_FOR_REALTIME_CORRECTION,
    DEPT_NO::integer as DEPT_NO,
    DESCRIPTION::string as DESCRIPTION,
    TO_BOOLEAN(DISPLAY_SHOP_DETAIL::String) as DISPLAY_SHOP_DETAIL,
    UPPER(ENTITY_CODE::string) as ENTITY_CODE,
    EQUIPMENT_TYPE_UUID::string as EQUIPMENT_TYPE_UUID,
    HOLE_THICKN::double as HOLE_THICKN,
    HOLE_TIME::double as HOLE_TIME ,
    ITEM_MANAGEMENT_PREPARATION::integer as ITEM_MANAGEMENT_PREPARATION,
    LENGTH_FACTOR::integer as LENGTH_FACTOR,
    LENGTH_METER::integer as LENGTH_METER,
    LENGTH_TIME::double as LENGTH_TIME,
    MACHN_NO::integer as MACHN_NO,
    MAXIMUM_SPEED::integer as MAXIMUM_SPEED,
    PERIMT_FACTOR::double as PERIMT_FACTOR,
    PERIMT_TIME::double as PERIMT_TIME,
    PIECE_TIME::double as PIECE_TIME,
    PREP_SHIFT_NUMBER_TO_DISPLAY::integer as PREP_SHIFT_NUMBER_TO_DISPLAY,
    TO_BOOLEAN(PREPARATION_ALLOW_GROUP::String) as PREPARATION_ALLOW_GROUP,
    TO_BOOLEAN(PREPARATION_PLANNING::String) as PREPARATION_PLANNING,
    PRINTER::string as PRINTER,
    PROD_CUM_CM::String as PROD_CUM_CM,
    PROD_CUM_LBS::string as PROD_CUM_LBS,
    PROD_CUM_MIN::String as PROD_CUM_MIN,
    PROD_DE_CM::double as PROD_DE_CM,
    PROD_DE_LBS::double as PROD_DE_LBS,
    PROD_DE_MIN::double as PROD_DE_MIN,
    PRODCT_MACHN_UUID::string as PRODCT_MACHN_UUID,
    PRODCT_RATE::double as PRODCT_RATE,
    REBUT_TOLERE::integer as REBUT_TOLERE,
    ROBOT::integer as ROBOT,
    SHOP_UUID::string as SHOP_UUID,
    STROKES_COUNTER::integer as STROKES_COUNTER,
    TO_BOOLEAN(STROKES_EMAIL_SENT::string) AS STROKES_EMAIL_SENT,
    STROKES_MAINTENANCE::integer as STROKES_MAINTENANCE,
    STROKES_MANAGERS::String as STROKES_MANAGERS,
    T_EP::double as T_EP,
    T_LOT::double as T_LOT,
    TOMAJ::double as TOMAJ,
    UPPER(TRANSFER_FORMAT::string) as TRANSFER_FORMAT,
    UPPER(UOM_CODE::string) as UOM_CODE,
    TO_BOOLEAN(VALIDATE_COIL_INFORMATION::string) AS VALIDATE_COIL_INFORMATION,
    TO_BOOLEAN(VIRTEK_LASER::string) AS VIRTEK_LASER
    from {{ref('prep_prodct_machn')}}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1