{{
 config(
 materialized = "view",
 alias = "duty",
 schema='spm_ca'
 )
}}

SELECT
    UPPER(DUTY_CODE::STRING) AS DUTY_CODE
    ,DESCRIPTION::STRING AS DESCRIPTION
    ,DUTY_PCT::double AS DUTY_PCT
    ,GL_EXPENSE::integer AS GL_EXPENSE
    -- 100% ""
    --,CREATEDBY::STRING AS CREATEDBY
    -- 100% ""
    --,MODIFIEDBY::STRING AS MODIFIEDBY
    --,TO_TIMESTAMP_NTZ(IPAAS_UPDATED_DATE::STRING) AS IPAAS_UPDATED_DATE
    --,SRC_SYSTEM_OPERATION::STRING AS SRC_SYSTEM_OPERATION
FROM {{ref('prep_duty')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'