{{
  config(
    materialized = "view",
    alias = "qc_people",
    schema='spm_ca'
  )
}}
  SELECT
 INITCAP(NULLIF(TRIM(DSG_ENTITY_CODE::string), '')) AS DSG_ENTITY_CODE
,UPPER(NULLIF(TRIM(INIT_CODE::string), '')) AS INIT_CODE
,TO_BOOLEAN(SALESM::string) AS SALESM
,TO_BOOLEAN(ESTIMT::string) AS ESTIMT
,LOWER(NULLIF(TRIM(USER_CODE::string), '')) AS USER_CODE
,UPPER(NULLIF(TRIM(SPM_SALESM_CODE::string), '')) AS SPM_SALESM_CODE
-- ,DUMMY::string AS DUMMY -- all is null
-- always TRUE
--,TO_BOOLEAN(ACTIVE::string) AS ACTIVE
,TO_BOOLEAN(PROSPECTOR::string) AS PROSPECTOR
,NULLIF(UPPER(TRIM(OFFICE_CODE::string)), '') AS OFFICE_CODE
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
from {{ref('prep_qc_people')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'