{{
  config(
    materialized = "view",
    alias = "vendor",
    schema='spm_ca'
  )
}}

SELECT 
     UPPER(NULLIF(TRIM(VENDOR_CODE::string),'')) AS VENDOR_CODE
    ,INITCAP(NULLIF(TRIM(NAME::string),'')) AS NAME
    ,INITCAP(NULLIF(TRIM(ADDRESS_1::string),'')) AS ADDRESS_1
    ,INITCAP(NULLIF(TRIM(ADDRESS_2::string),'')) AS ADDRESS_2
    ,INITCAP(NULLIF(TRIM(CITY::string),'')) AS CITY
    ,UPPER(NULLIF(TRIM(ST::string),'')) AS ST
    ,UPPER(NULLIF(TRIM(ZIP_CODE::string),'')) AS ZIP_CODE
    ,INITCAP(NULLIF(TRIM(COUNTRY::string),'')) AS COUNTRY
    ,NULLIF(TRIM(TELEPHONE::string),'') AS TELEPHONE
    -- 100% NULL
    --,NULLIF(TRIM(TELEX_TWX::string),'') AS TELEX_TWX
    ,NULLIF(TRIM(VALID_ENTITY::string),'') AS VALID_ENTITY
    ,INITCAP(SORT_NAME::string) AS SORT_NAME
    ,INITCAP(NULLIF(TRIM(CONTACT::string),'')) AS CONTACT
    ,NULLIF(TRIM(MEMO::string),'') AS MEMO
    ,UPPER(NULLIF(TRIM(REMIT_VENDOR::string),'')) AS REMIT_VENDOR
    ,UPPER(NULLIF(TRIM(STATS_VENDOR::string),'')) AS STATS_VENDOR
    ,UPPER(STATUS_CODE::string) AS STATUS_CODE
    ,NULLIF(TRIM(TERM_CODE::string),'') AS TERM_CODE
    ,TO_BOOLEAN(AUTO_DISBURS::string) AS AUTO_DISBURS
    ,NULLIF(TRIM(CLASS::string),'') AS CLASS
    ,NULLIF(TRIM(BANK_CODE::string),'') AS BANK_CODE
    ,NULLIF(TRIM(AP_ACCOUNT::string),'') AS AP_ACCOUNT 
    ,DESCRIPTION::string AS DESCRIPTION
    ,UPPER(CURRENCY_COD::string) AS CURRENCY_COD
    ,TO_BOOLEAN(PAY_DUTY::string) AS PAY_DUTY
    ,VIA_CODE::string AS VIA_CODE
    ,FOB_CODE::string AS FOB_CODE
    ,UPPER(NULLIF(TRIM(BUYER_CODE::string),'')) AS BUYER_CODE
    ,UPPER(NULLIF(TRIM(TYPE_FOURN::string),'')) AS TYPE_FOURN
    ,TO_BOOLEAN(CHECK_ILL::string) AS CHECK_ILL
    ,TO_BOOLEAN(LANGUAGE::string) AS LANGUAGE
    ,NULLIF(TRIM(AP_DISTRIBUT_1::string),'') AS AP_DISTRIBUT_1
    ,NULLIF(TRIM(AP_DISTRIBUT_2::string),'') AS AP_DISTRIBUT_2
    ,NULLIF(TRIM(AP_DISTRIBUT_3::string),'') AS AP_DISTRIBUT_3
    ,NULLIF(TRIM(AP_DISTRIBUT_4::string),'') AS AP_DISTRIBUT_4
    ,NULLIF(TRIM(AP_DISTRIBUT_5::string),'') AS AP_DISTRIBUT_5
    ,NULLIF(TRIM(AP_DISTRIBUT_6::string),'') AS AP_DISTRIBUT_6
    ,NULLIF(TRIM(AP_DISTRIBUT_7::string),'') AS AP_DISTRIBUT_7
    ,NULLIF(TRIM(AP_DISTRIBUT_8::string),'') AS AP_DISTRIBUT_8
    ,NULLIF(TRIM(AP_DISTRIBUT_9::string),'') AS AP_DISTRIBUT_9
    ,NULLIF(TRIM(AP_DISTRIBUT_10::string),'') AS AP_DISTRIBUT_10
    ,NULLIF(TRIM(AP_DISTRIBUT_11::string),'') AS AP_DISTRIBUT_11
    ,NULLIF(TRIM(AP_DISTRIBUT_12::string),'') AS AP_DISTRIBUT_12
    ,NULLIF(TRIM(AP_DISTRIBUT_13::string),'') AS AP_DISTRIBUT_13
    ,NULLIF(TRIM(AP_DISTRIBUT_14::string),'') AS AP_DISTRIBUT_14
    ,NULLIF(TRIM(AP_DISTRIBUT_15::string),'') AS AP_DISTRIBUT_15
    ,NULLIF(TRIM(AP_DISTRIBUT_16::string),'') AS AP_DISTRIBUT_16
    ,NULLIF(TRIM(AP_DISTRIBUT_17::string),'') AS AP_DISTRIBUT_17
    ,NULLIF(TRIM(AP_DISTRIBUT_18::string),'') AS AP_DISTRIBUT_18
    ,NULLIF(TRIM(AP_DISTRIBUT_19::string),'') AS AP_DISTRIBUT_19
    ,NULLIF(TRIM(AP_DISTRIBUT_20::string),'') AS AP_DISTRIBUT_20
    ,NULLIF(TRIM(AP_DISTRIBUT_21::string),'') AS AP_DISTRIBUT_21
    ,NULLIF(TRIM(AP_DISTRIBUT_22::string),'') AS AP_DISTRIBUT_22
    ,NULLIF(TRIM(AP_DISTRIBUT_23::string),'') AS AP_DISTRIBUT_23
    ,NULLIF(TRIM(AP_DISTRIBUT_24::string),'') AS AP_DISTRIBUT_24
    ,NULLIF(TRIM(AP_DISTRIBUT_25::string),'') AS AP_DISTRIBUT_25
    ,NULLIF(TRIM(AP_DISTRIBUT_26::string),'') AS AP_DISTRIBUT_26
    ,NULLIF(TRIM(AP_DISTRIBUT_27::string),'') AS AP_DISTRIBUT_27
    ,NULLIF(TRIM(AP_DISTRIBUT_28::string),'') AS AP_DISTRIBUT_28
    ,NULLIF(TRIM(AP_DISTRIBUT_29::string),'') AS AP_DISTRIBUT_29
    ,NULLIF(TRIM(AP_DISTRIBUT_30::string),'') AS AP_DISTRIBUT_30
    ,NULLIF(TRIM(AP_DISTRIBUT_31::string),'') AS AP_DISTRIBUT_31
    ,NULLIF(TRIM(AP_DISTRIBUT_32::string),'') AS AP_DISTRIBUT_32
    ,NULLIF(TRIM(AP_DISTRIBUT_33::string),'') AS AP_DISTRIBUT_33
    ,NULLIF(TRIM(AP_DISTRIBUT_34::string),'') AS AP_DISTRIBUT_34
    ,NULLIF(TRIM(AP_DISTRIBUT_35::string),'') AS AP_DISTRIBUT_35
    ,NULLIF(TRIM(AP_DISTRIBUT_36::string),'') AS AP_DISTRIBUT_36
    ,NULLIF(TRIM(AP_DISTRIBUT_37::string),'') AS AP_DISTRIBUT_37
    ,NULLIF(TRIM(AP_DISTRIBUT_38::string),'') AS AP_DISTRIBUT_38
    ,NULLIF(TRIM(AP_DISTRIBUT_39::string),'') AS AP_DISTRIBUT_39
    ,NULLIF(TRIM(AP_DISTRIBUT_40::string),'') AS AP_DISTRIBUT_40
    ,TO_BOOLEAN(GST_TAXABLE::string) AS GST_TAXABLE
    ,UPPER(NULLIF(TRIM(GST_NO::string),'')) AS GST_NO
    ,TO_BOOLEAN(PO_S::string) AS PO_S
    ,UPPER(NULLIF(TRIM(TVQ_NO::string),'')) AS TVQ_NO
    ,UPPER(NULLIF(TRIM(MLI_VALID::string),'')) AS MLI_VALID
    ,UPPER(NULLIF(TRIM(CANSIS_VENDOR_NUMBER::string),'')) AS CANSIS_VENDOR_NUMBER
    ,INITCAP(NULLIF(TRIM(CANSIS_VENDOR_SITE_NAME::string),'')) AS CANSIS_VENDOR_SITE_NAME
    ,TO_BOOLEAN(MESURE::string) AS MESURE
    ,TO_BOOLEAN(AFFILIATED::string) AS AFFILIATED
    ,NULLIF(TRIM(RELATIONSHIP_CODE::string),'') AS RELATIONSHIP_CODE
    ,SLITTING_PREFIX_FROM::integer AS SLITTING_PREFIX_FROM
    ,SLITTING_PREFIX_TO::integer AS SLITTING_PREFIX_TO
    -- 100% NULL
    --,INITCAP(NULLIF(TRIM(DISPATCHER_EMAIL_ADDRESS1::string),'')) AS DISPATCHER_EMAIL_ADDRESS1
    -- 100% NULL
    --,INITCAP(NULLIF(TRIM(DISPATCHER_EMAIL_ADDRESS2::string),'')) AS DISPATCHER_EMAIL_ADDRESS2
    ,TO_BOOLEAN(ECOLOGO::string)AS ECOLOGO
    -- 100% NULL
    --,NULLIF(TRIM(CREATED_BY::string),'') AS CREATED_BY
    ,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
    ,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
    -- 100% NULL with the qualify filter bellow, but has some data without
    ,NULLIF(TRIM(MODIFIED_BY::string),'') AS MODIFIED_BY
    -- 100% NULL
    --,UPPER(EXTERNAL_VENDOR_CODE::string) AS EXTERNAL_VENDOR_CODE
FROM {{ref('prep_vendor')}}

QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'