{{
  config(
    materialized = "view",
    alias = "produit_s",
    schema='spm_ca',
    meta = {
        'table_key': 'NOM_PRODUIT',
        'tests': {
            'null_values':{
                'columns':[
                    'RDM_ACTIVE_STATUS_CODE'
                ]
            }
        }    
    }
  )
}}

WITH raw_produit_s AS(
  SELECT * from {{ref('prep_produit_s')}}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'
)

SELECT
UPPER(ENTITY_CODE::string) AS ENTITY_CODE
,NO_PRODUIT::INTEGER AS NO_PRODUIT
,UPPER(NULLIF(TRIM(NOM_PRODUIT::string), '')) AS NOM_PRODUIT
,UPPER(NULLIF(TRIM(NOM_ABREGE::string), '')) AS NOM_ABREGE
,CASE WHEN NO_USINE::string = '' THEN NULL ELSE  CAST(NO_USINE::string AS INTEGER) END AS NO_USINE
,COUT_STD_MIN::DOUBLE AS COUT_STD_MIN
,DRW_STD_COST::DOUBLE AS DRW_STD_COST
,NULLIF(TRIM(NO_GL::VARCHAR(6)), '') AS NO_GL
,POIDS_THEOR::DOUBLE AS POIDS_THEOR
,COUT_ACIER::DOUBLE AS COUT_ACIER
,COUT_FABR::DOUBLE AS COUT_FABR
,BASE_TAXE::DOUBLE AS BASE_TAXE
,TO_BOOLEAN(DISTR_FACT::string) AS DISTR_FACT
,TO_BOOLEAN(TAXABLE_1::string) AS TAXABLE_1
,TO_BOOLEAN(TAXABLE_2::string) AS TAXABLE_2
,TO_BOOLEAN(TAXABLE_3::string) AS TAXABLE_3
,TO_BOOLEAN(TAXABLE_4::string) AS TAXABLE_4
,TO_BOOLEAN(FST_APPLIC::string) AS FST_APPLIC
,TO_BOOLEAN(IMPR_QTES::string) AS IMPR_QTES
,TAUX_FED::INTEGER AS TAUX_FED
,LARGEUR::DOUBLE AS LARGEUR
,COUT_HISTO::DOUBLE AS COUT_HISTO
,FURN_COST::DOUBLE AS FURN_COST
,NULLIF(TRIM(ITEM_NO::string), '') AS ITEM_NO
,TYPE_PROD::INTEGER AS TYPE_PROD
,TO_BOOLEAN(SOUS_CONTRAT::string) AS SOUS_CONTRAT
-- always false
--,TO_BOOLEAN(CREATE_AUTO::string) AS CREATE_AUTO
,TO_BOOLEAN(ROYAUTE::string) AS ROYAUTE
-- always false
--,TO_BOOLEAN(IND_REBUT::string) AS IND_REBUT
,LENGTH_MIN::DOUBLE AS LENGTH_MIN
,TO_BOOLEAN(STATS_DEPTH::string) AS STATS_DEPTH
-- always false
--,SHOE_LENGTH::INTEGER AS SHOE_LENGTH
,TO_BOOLEAN(UTIL_TX::string) AS UTIL_TX
,TO_BOOLEAN(STATS_UNITES::string) AS STATS_UNITES
,TO_BOOLEAN(STATS_POIDS::string) AS STATS_POIDS
,TO_BOOLEAN(STATS_TMPS::string) AS STATS_TMPS
,UPPER(NULLIF(TRIM(NOM_PROD_ANG::string), '')) AS NOM_PROD_ANG
,CASE WHEN CODE_AISI::string = '' THEN NULL ELSE CAST(CODE_AISI::string AS INTEGER) END AS CODE_AISI
,NO_COLON_CARN::INTEGER AS NO_COLON_CARN
,TO_BOOLEAN(MAJ_RES_INV::string) AS MAJ_RES_INV
,TO_BOOLEAN(UPD_UTIL::string) AS UPD_UTIL
,TO_BOOLEAN(GIRTS_PRODC::string) AS GIRTS_PRODC
,TO_BOOLEAN(FOLLOW_MARK::string) AS FOLLOW_MARK
,TO_BOOLEAN(EXT_FAB::string) AS EXT_FAB
,TO_BOOLEAN(FOLLOW_DIV::string) AS FOLLOW_DIV
,TO_BOOLEAN(RAW_MATERIAL::string) AS RAW_MATERIAL
,DEPT_ID::INTEGER AS DEPT_ID
,TO_BOOLEAN(PRODCT_COMPNT::string) AS PRODCT_COMPNT
,TO_BOOLEAN(USE_STD_COST::string) AS USE_STD_COST
,EFFICACITE_1::INTEGER AS EFFICACITE_1
,EFFICACITE_2::INTEGER AS EFFICACITE_2
,EFFICACITE_3::INTEGER AS EFFICACITE_3
,EFFICACITE_4::INTEGER AS EFFICACITE_4
,EFFICACITE_5::INTEGER AS EFFICACITE_5
,EFFICACITE_6::INTEGER AS EFFICACITE_6
,NULLIF(TRIM(CATEGORY_1::VARCHAR(3)), '') AS CATEGORY_1
,NULLIF(TRIM(CATEGORY_2::VARCHAR(3)), '') AS CATEGORY_2
,ID_FACTOR_1::DOUBLE AS ID_FACTOR_1
,ID_FACTOR_2::DOUBLE AS ID_FACTOR_2
,ID_FACTOR_3::DOUBLE AS ID_FACTOR_3
,ID_FACTOR_4::DOUBLE AS ID_FACTOR_4
,ID_FACTOR_5::DOUBLE AS ID_FACTOR_5
,DEPT_NO_1::INTEGER AS DEPT_NO_1
,DEPT_NO_2::INTEGER AS DEPT_NO_2
,DEPT_NO_3::INTEGER AS DEPT_NO_3
,DEPT_NO_4::INTEGER AS DEPT_NO_4
,DEPT_NO_5::INTEGER AS DEPT_NO_5
,DEPT_NO_6::INTEGER AS DEPT_NO_6
,FURN_COST_1::DOUBLE AS FURN_COST_1
,FURN_COST_2::DOUBLE AS FURN_COST_2
,FURN_COST_3::DOUBLE AS FURN_COST_3
,FURN_COST_4::DOUBLE AS FURN_COST_4
,OVERHEAD_COST::DOUBLE AS OVERHEAD_COST
,UPPER(TRIM(TASK_NUMBER::string)) AS TASK_NUMBER
,COUT_FABR_1::DOUBLE AS COUT_FABR_1
,COUT_FABR_2::DOUBLE AS COUT_FABR_2
,COUT_FABR_3::DOUBLE AS COUT_FABR_3
,TO_BOOLEAN(DEPT_TIME_1::string) AS DEPT_TIME_1
,TO_BOOLEAN(DEPT_TIME_2::string) AS DEPT_TIME_2
,TO_BOOLEAN(DEPT_TIME_3::string) AS DEPT_TIME_3
,TO_BOOLEAN(DEPT_TIME_4::string) AS DEPT_TIME_4
,TO_BOOLEAN(DEPT_TIME_5::string) AS DEPT_TIME_5
,TO_BOOLEAN(DEPT_TIME_6::string) AS DEPT_TIME_6
,NULLIF(TRIM(CMG_REVENUE_METHOD::string), '') AS CMG_REVENUE_METHOD
,TO_BOOLEAN(CMG_TRANSF_COST::string) AS CMG_TRANSF_COST
,TO_BOOLEAN(ENG_REQUIRED::string) AS ENG_REQUIRED
-- always False
--,TO_BOOLEAN(BOLT_PRODUCT::string) AS BOLT_PRODUCT
,TO_BOOLEAN(STANDARD_PRODUCT::string) AS STANDARD_PRODUCT
,CASE WHEN DECK_LOGOS::string = '' THEN NULL ELSE TRANSFORM(SPLIT(DECK_LOGOS::string, ','), val -> TRIM(val)) END AS DECK_LOGOS
,TO_BOOLEAN(USE_STD_RATE::string) AS USE_STD_RATE
-- always 0
--,FRINGE_BENEFITS_PCT::INTEGER AS FRINGE_BENEFITS_PCT
,NULLIF(TRIM(VALID_ITEM_NO::string), '') AS VALID_ITEM_NO
,MAX_BUNDL_PIECES::INTEGER AS MAX_BUNDL_PIECES
,BUNDL_PIECES_TOLERANCE::INTEGER AS BUNDL_PIECES_TOLERANCE
,TO_BOOLEAN(IS_ACTIVE::string) AS IS_ACTIVE
,DECK_COOLANT_CODE::INTEGER AS DECK_COOLANT_CODE
,DECK_EDGE_DETECTOR_MAX::DOUBLE AS DECK_EDGE_DETECTOR_MAX
,DECK_EDGE_DETECTOR_HIGH::DOUBLE AS DECK_EDGE_DETECTOR_HIGH
,DECK_EDGE_DETECTOR_IDEAL::DOUBLE AS DECK_EDGE_DETECTOR_IDEAL
,DECK_EDGE_DETECTOR_LOW::DOUBLE AS DECK_EDGE_DETECTOR_LOW
,DECK_EDGE_DETECTOR_MIN::DOUBLE AS DECK_EDGE_DETECTOR_MIN
,WIDTH_TOLERANCE::DOUBLE AS WIDTH_TOLERANCE
,STICKER_COLOR_NO::INTEGER AS STICKER_COLOR_NO
,TO_BOOLEAN(DECK_VENTED::string) AS DECK_VENTED
,TO_BOOLEAN(DECK_HANGER_TAB::string) AS DECK_HANGER_TAB
,TO_BOOLEAN(DECK_REGULAR::string) AS DECK_REGULAR
,TO_BOOLEAN(DECK_ACOUSTIC::string) AS DECK_ACOUSTIC
-- always False
--,TO_BOOLEAN(DECK_FULL_ACOUSTIC::string) AS DECK_FULL_ACOUSTIC
,DECK_DEPTH::DOUBLE AS DECK_DEPTH
,TO_BOOLEAN(DECK_ACCESSORY::string) AS DECK_ACCESSORY
,TO_BOOLEAN(DECK_EMBOSSING::string) AS DECK_EMBOSSING
,UPPER(NULLIF(TRIM(DECK_TYPE_CODE::string), '')) AS DECK_TYPE_CODE
,NULLIF(TRIM(CODE_FIN_C::string), '') AS CODE_FIN_C
,NULLIF(TRIM(PAINT_COLOR::string), '') AS PAINT_COLOR
,TYPE_REQ::INTEGER AS TYPE_REQ
,NULLIF(TRIM(MARK_PREFIX::string), '') AS MARK_PREFIX
,NULLIF(TRIM(CAT_STRUCT::string), '') AS CAT_STRUCT
,NULLIF(TRIM(NO_PEINTURE::string), '') AS NO_PEINTURE
,NULLIF(TRIM(CODE_FIN_T::string), '') AS CODE_FIN_T
,NULLIF(TRIM(DECK_ESTIMATION_CATEGORY::string), '') AS DECK_ESTIMATION_CATEGORY
,ADDITIONAL_PLANNING_DELAY::INTEGER AS ADDITIONAL_PLANNING_DELAY
,MAXIMUM_MARKS_NUMBER::INTEGER AS MAXIMUM_MARKS_NUMBER
,MAXIMUM_MARKS_QTY::INTEGER AS MAXIMUM_MARKS_QTY
,TO_BOOLEAN(AUTOMATIC_SEQUENCING::string) AS AUTOMATIC_SEQUENCING
,TO_BOOLEAN(INVOICING_AMT_CALCULATION::string) AS INVOICING_AMT_CALCULATION
,SOLD_DETAIL_TOLERANCE_AMOUNT::INTEGER AS SOLD_DETAIL_TOLERANCE_AMOUNT
,SOLD_DETAIL_TOLERANCE_WEIGHT_PCT::INTEGER AS SOLD_DETAIL_TOLERANCE_WEIGHT_PCT
,SOLD_DETAIL_TOLERANCE_UNIT::INTEGER AS SOLD_DETAIL_TOLERANCE_UNIT
,NULLIF(TRIM(UOM_BUDGET_ENTRY_TYPE::string), '') AS UOM_BUDGET_ENTRY_TYPE
,SOLD_DETAIL_TOLERANCE_UOM::INTEGER AS SOLD_DETAIL_TOLERANCE_UOM
,TO_BOOLEAN(TRANSFER_INVOICING_AMT::string) AS TRANSFER_INVOICING_AMT
,HOURLY_PRODUCTION::DOUBLE AS HOURLY_PRODUCTION
,NULLIF(TRIM(CAPACITY_UOM_CODE::VARCHAR(2)), '') AS CAPACITY_UOM_CODE
,TO_BOOLEAN(PREPARATION_PLANNING::string) AS PREPARATION_PLANNING
,NULLIF(TRIM(REVENUE_QUANTITY_TYPE_UUID::string), '') AS REVENUE_QUANTITY_TYPE_UUID
,TO_BOOLEAN(ERECTOR_PRIVILEGE::string) AS ERECTOR_PRIVILEGE
,TO_BOOLEAN(ERECTOR_PRIV_WEB_APP_INCLUDED::string) AS ERECTOR_PRIV_WEB_APP_INCLUDED
,TO_BOOLEAN(ERECTOR_PRIV_WEB_APP_MARK_WEIGHT::string) AS ERECTOR_PRIV_WEB_APP_MARK_WEIGHT
,ERECTOR_PRIV_WEB_APP_WEIGHT_PCT::INTEGER AS ERECTOR_PRIV_WEB_APP_WEIGHT_PCT
,ERECTOR_PRIV_SALE_PRODUCT::INTEGER AS ERECTOR_PRIV_SALE_PRODUCT
--always False
--,TO_BOOLEAN(MARK_PIECE_DETAIL_ALLOWED::string) AS MARK_PIECE_DETAIL_ALLOWED
,TO_BOOLEAN(TRANSFER_WASTE_COST::string) AS TRANSFER_WASTE_COST
,TO_BOOLEAN(DISPLAY_MARK_DETAIL_IN_ERECTOR_WEB_APP::string) AS DISPLAY_MARK_DETAIL_IN_ERECTOR_WEB_APP
,TO_BOOLEAN(TRANSFER_RECIPE_WEIGHT_ONLY::string) AS TRANSFER_RECIPE_WEIGHT_ONLY
,TO_BOOLEAN(BUNDLE_ALLOWED::string) AS BUNDLE_ALLOWED
,NULLIF(BUNDLING_MODULE::string,'') AS BUNDLING_MODULE
,TO_BOOLEAN(PARTIAL_PRODUCTION_ALLOWED::string) AS PARTIAL_PRODUCTION_ALLOWED
,TO_BOOLEAN(PARTIAL_BUNDLE_DELIVERY_ALLOWED::string) AS PARTIAL_BUNDLE_DELIVERY_ALLOWED
,TO_BOOLEAN(PREPARATION_WORKFLOW_ENABLED::string) AS PREPARATION_WORKFLOW_ENABLED
,TO_BOOLEAN(PREPARATION_FINISHING::string) AS PREPARATION_FINISHING
,SOLD_SCHEDULED_TOLERANCE_WEIGHT::INTEGER AS SOLD_SCHEDULED_TOLERANCE_WEIGHT
,SOLD_SCHEDULED_TOLERANCE_QTY::INTEGER AS SOLD_SCHEDULED_TOLERANCE_QTY
,SOLD_SCHEDULED_TOLERANCE_TIME::INTEGER AS SOLD_SCHEDULED_TOLERANCE_TIME
,RDM.STANDARD_APPLICATION_VALUE AS RDM_ACTIVE_STATUS_CODE
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
FROM raw_produit_s PS
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM
  ON CAST(PS.IS_ACTIVE AS INT) = CAST(RDM.BUSINESS_APPLICATION_VALUE AS INT)
    AND UPPER(RDM.BUSINESS_APPLICATION_DOMAIN_CODE) = 'ACTIVESTATUS'
    AND UPPER(RDM.STANDARD_DOMAIN_APPLICATION_CODE) = 'ACTIVESTATUS' 
    AND UPPER(RDM.BUSINESS_APPLICATION_CODE) = 'SPM'