{{
  config(
    materialized = "view",
    alias = "warehouse",
    schema='spm_ca'
  )
}}

SELECT
 WHS_CODE::string AS WHS_CODE
,DESCRIPTION::string AS DESCRIPTION
,NULLIF(TRIM(NAME::string),'') AS NAME
,INITCAP(NULLIF(TRIM(ADDRESS_1::string),'')) AS ADDRESS_1
,INITCAP(NULLIF(TRIM(ADDRESS_2::string),'')) AS ADDRESS_2
,INITCAP(NULLIF(TRIM(CITY::string),'')) AS CITY
,UPPER(NULLIF(TRIM(ST::string),'')) AS ST
,UPPER(NULLIF(TRIM(ZIP_CODE::string),''))  AS ZIP_CODE
,NULLIF(TRIM(COUNTRY::string),'') AS COUNTRY
,NULLIF(TRIM(TELEPHONE::string),'') AS TELEPHONE
--100% NULL
--,NULLIF(TRIM(TELEX_TWX::string),'') AS TELEX_TWX
,TAX_CODE::string AS TAX_CODE
,TO_BOOLEAN(S_CONTRC::string) AS S_CONTRC
,TO_BOOLEAN(MULT_INV::string) AS MULT_INV
,TO_BOOLEAN(EXT_WHS::string) AS EXT_WHS
,TO_BOOLEAN(TRACK_HEAT_NO::string) AS TRACK_HEAT_NO
,PCT_PERTE::DOUBLE AS PCT_PERTE
,UPPER(NULLIF(TRIM(ITEM_NO::string),'')) AS ITEM_NO
,TO_BOOLEAN(IND_RESERVE::string) AS IND_RESERVE
,TO_BOOLEAN(CTRL_INV_JOB::string) AS CTRL_INV_JOB
,TO_BOOLEAN(USED::string) AS USED
,UPPER(NULLIF(TRIM(RECEIPT_CODE::string),'')) AS RECEIPT_CODE
,TO_BOOLEAN(EPIX_MAINTN::string) AS EPIX_MAINTN
--100% blank
--,EPIX_USED_WHS::string AS EPIX_USED_WHS
,TO_BOOLEAN(TRACK_B_LOCATION::string) AS TRACK_B_LOCATION
,UPPER(NULLIF(TRIM(MASTER_ENTITY::string),'')) AS MASTER_ENTITY
,UPPER(NULLIF(TRIM(PROJECT_NO::string),'')) AS PROJECT_NO
--100% 0
--,DECK_TYPE::string AS DECK_TYPE
,TO_BOOLEAN(BAR_CODE_FOLLOW::string) AS BAR_CODE_FOLLOW
,CASE VENDOR_ID::integer WHEN 0 THEN NULL ELSE VENDOR_ID::integer END AS VENDOR_ID
,UPPER(NULLIF(TRIM(VENDOR_NAME::string),'')) AS VENDOR_NAME
,UPPER(NULLIF(TRIM(INV_CONCILIATION_USAGES_FORMULA::string),'')) AS INV_CONCILIATION_USAGES_FORMULA
,TO_BOOLEAN(OPTIMIZATION_MANAGE_HEAT_NO::string) AS OPTIMIZATION_MANAGE_HEAT_NO
--100% NULL
--,TO_BOOLEAN(MANAGE_SURFACE_ITEM_MIN_WEIGHT::string) AS MANAGE_SURFACE_ITEM_MIN_WEIGHT
,UPPER(NULLIF(TRIM(LINKED_ABM_PROJECT_NUMBER::string),'')) AS LINKED_ABM_PROJECT_NUMBER
,TO_BOOLEAN(IGNORE_FINANCIAL_RAW_MAT_COST::string) AS IGNORE_FINANCIAL_RAW_MAT_COST
,NULLIF(TRIM(CREATED_BY::string),'') AS CREATED_BY
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string),'') AS MODIFIED_BY

FROM {{ref('prep_warehouse')}}

QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'