{{
  config(
    materialized = "view",
    alias = "cmg_sales_group",
    schema='spm_ca'
  )
}}
  SELECT
 CMG_SALES_GROUP_UUID::string AS CMG_SALES_GROUP_UUID
,SALES_GROUP_CODE::INTEGER AS SALES_GROUP_CODE
,DESCRIPTION_ID::INTEGER AS DESCRIPTION_ID
,UOM_CODE::string AS UOM_CODE
,TO_BOOLEAN(PERFORMANCE_IND_CALCULATION::string) AS PERFORMANCE_IND_CALCULATION
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
from {{ref('prep_cmg_sales_group')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(SRC_SYSTEM_OPERATION) <> 'DELETE'
