{{
  config(
    materialized = "view",
    alias = "qc_competitor",
    schema='spm_ca'
  )
}}
 SELECT
COMPT_NO::INTEGER AS COMPT_NO
,TO_BOOLEAN(ACTIVE::string) AS ACTIVE
,UPPER(NULLIF(TRIM(NAME::string),'')) AS NAME
,NULLIF(TRIM(CONTCT::string),'') AS CONTCT
,NULLIF(TRIM(OFFICE_ADDRSS1::string),'') AS OFFICE_ADDRSS1
,NULLIF(TRIM(OFFICE_ADDRSS2::string),'') AS OFFICE_ADDRSS2
,INITCAP(NULLIF(TRIM(OFFICE_CITY::string),'')) AS OFFICE_CITY
,NULLIF(TRIM(OFFICE_ST::string),'') AS OFFICE_ST
,NULLIF(TRIM(OFFICE_COUNTRY::string),'') AS OFFICE_COUNTRY
,REGEXP_REPLACE(NULLIF(TRIM(OFFICE_ZIP_CODE::string),''),'[-\\s]') AS OFFICE_ZIP_CODE
,NULLIF(REGEXP_REPLACE(OFFICE_PHONE::string,'[^\\d]*(0{9,})?(1{9,})?(2{9,})?(3{9,})?(4{9,})?(5{9,})?(6{9,})?(7{9,})?(8{9,})?(9{9,})?'), '') AS OFFICE_PHONE
,NULLIF(REGEXP_REPLACE(OFFICE_FAX::string,'[^\\d]*(0{9,})?(1{9,})?(2{9,})?(3{9,})?(4{9,})?(5{9,})?(6{9,})?(7{9,})?(8{9,})?(9{9,})?'), '') AS OFFICE_FAX
,NULLIF(TRIM(PREFIX::CHAR(1)),'') AS PREFIX
,NULLIF(TRIM(DUMMY::string),'') AS DUMMY
,NULLIF(TRIM(EMAIL::string),'') AS EMAIL
-- always NULL
--,NULLIF(TRIM(MEMO::string),'') AS MEMO
,NULLIF(TRIM(WEB_ADDRSS::string),'') AS WEB_ADDRSS
,NULLIF(TRIM(SHOP_ADDRSS1::string),'') AS SHOP_ADDRSS1
,NULLIF(TRIM(SHOP_ADDRSS2::string),'') AS SHOP_ADDRSS2
,INITCAP(NULLIF(TRIM(SHOP_CITY::string),'')) AS SHOP_CITY
,NULLIF(TRIM(SHOP_COUNTRY::string),'') AS SHOP_COUNTRY
,NULLIF(REGEXP_REPLACE(SHOP_FAX::string,'[^\\d]*(0{9,})?(1{9,})?(2{9,})?(3{9,})?(4{9,})?(5{9,})?(6{9,})?(7{9,})?(8{9,})?(9{9,})?'), '') AS SHOP_FAX
,TO_BOOLEAN(SHOP_LIKE_OFFICE::string) AS SHOP_LIKE_OFFICE
,NULLIF(REGEXP_REPLACE(SHOP_PHONE::string,'[^\\d]*(0{9,})?(1{9,})?(2{9,})?(3{9,})?(4{9,})?(5{9,})?(6{9,})?(7{9,})?(8{9,})?(9{9,})?'), '') AS SHOP_PHONE
,NULLIF(TRIM(SHOP_ST::CHAR(2)),'') AS SHOP_ST
,REGEXP_REPLACE(NULLIF(TRIM(SHOP_ZIP_CODE::string),''),'[-\\s]') AS SHOP_ZIP_CODE
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY 
from {{ref('prep_qc_competitor')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'