{{
 config(
 materialized = "view",
 alias = "po_line",
 schema='spm_ca'
 )
}}

SELECT
    -- 100% 
    --AP_ENTITY::STRING AS AP_ENTITY
    -- 100% 
    --,IN_ENTITY::STRING AS IN_ENTITY
    UPPER(WHS_CODE::STRING) AS WHS_CODE
    ,UPPER(PO_NO::STRING) AS PO_NO
    -- 100% 
    --,RELEASE_NO::STRING AS RELEASE_NO
    ,UPPER(NULLIF(TRIM(VENDOR_CODE::STRING), '')) AS VENDOR_CODE
    ,UPPER(NULLIF(TRIM(JOB_NO::STRING), '')) AS JOB_NO
    ,LINE_NO::INTEGER AS LINE_NO
    ,REQUEST_DATE::DATE AS REQUEST_DATE
    ,PROMISE_DATE::DATE AS PROMISE_DATE
    ,UPPER(ITEM_NO::STRING) AS ITEM_NO
    ,UPPER(NULLIF(NULLIF(TRIM(DESCRIPTION::STRING), ''),';')) AS DESCRIPTION
    ,UPPER(NULLIF(TRIM(UOM_CODE::STRING), '')) AS UOM_CODE
    ,UPPER(NULLIF(TRIM(ITEM_VENDOR::STRING), '')) AS ITEM_VENDOR
    ,UPPER(NULLIF(TRIM(UOM_VENDOR::STRING), '')) AS UOM_VENDOR
    ,CONV_UOM::double AS CONV_UOM
    ,FOB_VENDOR::double AS FOB_VENDOR
    ,UPPER(RECEIPT_CODE::STRING) AS RECEIPT_CODE
    -- 100% "0.0"
    --,LINE_DISC::STRING AS LINE_DISC
    ,DUTY_CODE::STRING AS DUTY_CODE
    ,TAX_RATE::STRING AS TAX_RATE
    ,MISC_PCT::STRING AS MISC_PCT
    ,UPPER(NULLIF(TRIM(LAST_RCPT_NO::STRING), '')) AS LAST_RCPT_NO
    ,LAST_RC_QTY::INTEGER AS LAST_RC_QTY
    ,QTY_ORIG_ORD::INTEGER AS QTY_ORIG_ORD
    ,QTY_RECEIVED::INTEGER AS QTY_RECEIVED
    ,QTY_TO_RCVE::INTEGER AS QTY_TO_RCVE
    ,UPPER(STATUS_CODE::STRING) AS STATUS_CODE
    ,UPPER(NULLIF(TRIM(CHANG_CANCEL::STRING), '')) AS CHANG_CANCEL
    ,SEQ_NO::STRING AS SEQ_NO
    ,UPPER(QTY_VB_COD::STRING) AS QTY_VB_COD
    -- 100% ""
    --,NO_PROJET::STRING AS NO_PROJET
    -- 100% "0"
    --,JC_LINE_NO::STRING AS JC_LINE_NO
    -- 100% "0"
    --,VENDOR_MEASURE::STRING AS VENDOR_MEASURE
    -- 100% ""
    --,CREATEDBY::STRING AS CREATEDBY
    ,TO_TIMESTAMP_NTZ(CREATED_DATE::STRING) AS CREATED_DATE
    ,TO_TIMESTAMP_NTZ(MODIFIED_DATE::STRING) AS MODIFIED_DATE
    -- 100% ""
    --,MODIFIEDBY::STRING AS MODIFIEDBY
    --,IPAAS_UPDATED_DATE::STRING AS IPAAS_UPDATED_DATE
    --,SRC_SYSTEM_OPERATION::STRING AS SRC_SYSTEM_OPERATION
FROM {{ref('prep_po_line')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'