{{
 config(
 materialized = "view",
 alias = "po",
 schema='spm_ca'
 )
}}

SELECT
    TO_TIMESTAMP_NTZ(CREATED_DATE::STRING) AS CREATED_DATE,
    TO_TIMESTAMP_NTZ(MODIFIED_DATE::STRING) AS MODIFIED_DATE,
    -- 100% "1C"
    --AP_ENTITY::STRING AS AP_ENTITY
    -- 100% "1c"
    --,IN_ENTITY::STRING AS IN_ENTITY
    UPPER(NULLIF(TRIM(ENTITY_CODE::STRING), '')) AS ENTITY_CODE
    ,UPPER(NULLIF(TRIM(WHS_CODE::STRING), '')) AS WHS_CODE
    ,UPPER(PO_NO::STRING) AS PO_NO
    -- 100% "0"
    --,RELEASE_NO::STRING AS RELEASE_NO
    ,UPPER(NULLIF(TRIM(VENDOR_CODE::STRING), '')) AS VENDOR_CODE
    ,UPPER(NULLIF(TRIM(NAME::STRING), '')) AS NAME
    ,UPPER(NULLIF(TRIM(REMIT_VENDOR::STRING), '')) AS REMIT_VENDOR
    -- 100% ""
    --,SHIP_TO::STRING AS SHIP_TO
    ,UPPER(NULLIF(TRIM(SHIP_NAME::STRING), '')) AS SHIP_NAME
    ,UPPER(NULLIF(NULLIF(TRIM(SHIP_ADDRESS::STRING), ''),';')) AS SHIP_ADDRESS
    ,INITCAP(NULLIF(TRIM(SHIP_CITY::STRING), '')) AS SHIP_CITY
    ,UPPER(NULLIF(TRIM(SHIP_ST::STRING), '')) AS SHIP_ST
    ,UPPER(NULLIF(TRIM(SHIP_ZIP::STRING), '')) AS SHIP_ZIP
    ,INITCAP(NULLIF(TRIM(SHIP_COUNTRY::STRING), '')) AS SHIP_COUNTRY
    -- 100% ""
    --,DEPARTMENT::STRING AS DEPARTMENT
    -- 100% ""
    --,VENDOR_REFER::STRING AS VENDOR_REFER
    ,PO_DATE::DATE AS PO_DATE
    ,REQUEST_DATE::DATE AS REQUEST_DATE
    ,PROMISE_DATE::DATE AS PROMISE_DATE
    -- 100% "0.0"
    --,CONTROL_QTY::STRING AS CONTROL_QTY
    ,UPPER(NULLIF(TRIM(RECEIPT_CODE::STRING), '')) AS RECEIPT_CODE
    ,UPPER(NULLIF(NULLIF(TRIM(MEMO::STRING), ''),';')) AS MEMO
    -- 100% "00"
    --,TERM_CODE::STRING AS TERM_CODE
    ,UPPER(NULLIF(TRIM(FOB_DESC::STRING), '')) AS FOB_DESC
    ,UPPER(NULLIF(TRIM(VIA_DESC::STRING), '')) AS VIA_DESC
    ,UPPER(NULLIF(TRIM(BUYER_CODE::STRING), '')) AS BUYER_CODE
    ,UPPER(NULLIF(TRIM(TAX_CODE::STRING), '')) AS TAX_CODE
    ,TO_BOOLEAN(PPD_COLL::STRING) AS PPD_COLL
    -- 100% "0.0"
    --,PO_DISC::STRING AS PO_DISC
    ,UPPER(NULLIF(TRIM(CURRENCY_COD::STRING), '')) AS CURRENCY_COD
    ,UPPER(NULLIF(TRIM(LAST_RCPT_NO::STRING), '')) AS LAST_RCPT_NO
    ,LAST_RC_DATE::DATE AS LAST_RC_DATE
    ,OPEN_VALUE::double AS OPEN_VALUE
    ,UPPER(NULLIF(TRIM(CHANG_CANCEL::STRING), '')) AS CHANG_CANCEL
    ,UPPER(STATUS_CODE::STRING) AS STATUS_CODE
    ,UPPER(NULLIF(TRIM(JOB_NO::STRING), '')) AS JOB_NO
    ,SEQ_NO::STRING AS SEQ_NO
    ,UPPER(NULLIF(TRIM(TERMINAL_NO::STRING), '')) AS TERMINAL_NO
    ,LOWER(NULLIF(TRIM(USER::STRING), '')) AS USER
    ,UPPER(NULLIF(TRIM(CONTACT::STRING), '')) AS CONTACT
    -- 100% "0"
    --,JC_GENERT::STRING AS JC_GENERT
    ,NULLIF(YR::INTEGER, 0) AS YR
    ,PRD::INTEGER AS PRD
    ,TO_BOOLEAN(VENDOR_MEASURE::STRING) AS VENDOR_MEASURE
    ,TO_TIMESTAMP_NTZ(CREATION_DATETIME::STRING) AS CREATION_DATETIME
    -- 100% ""
    --,CREATEDBY::STRING AS CREATEDBY
    -- 100% ""
    --,MODIFIEDBY::STRING AS MODIFIEDBY
    --,IPAAS_UPDATED_DATE::STRING AS IPAAS_UPDATED_DATE
    --,SRC_SYSTEM_OPERATION::STRING AS SRC_SYSTEM_OPERATION
FROM {{ref('prep_po')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'