{{
  config(
    materialized = "view",
    alias = "ess_tranx",
    schema='spm_ca'
  )
}}
SELECT
UPPER(ENTITY_CODE::string) AS ENTITY_CODE
,LINE_NO::INTEGER AS LINE_NO
,MNT_DEPENSE::DOUBLE AS MNT_DEPENSE
,MNT_REVENU::DOUBLE AS MNT_REVENU
,UPPER(NO_PROJET::string) AS NO_PROJET
,CASE PRD::INTEGER WHEN 0 THEN NULL ELSE PRD::INTEGER END AS PRD
,QUANTITY::DOUBLE AS QUANTITY
,TRANS_DATE::DATE AS TRANS_DATE
,CASE YR::INTEGER WHEN 0 THEN NULL ELSE YR::INTEGER END AS YR
,SEQ_NO::INTEGER AS SEQ_NO
--100% BLANK
--,CONTRACT_NO::string AS CONTRACT_NO
--100% BLANK
--,OFFICE_CODE::string AS OFFICE_CODE
--100% BLANK
--,BRANCH_OFFICE_CODE::string AS BRANCH_OFFICE_CODE
,WEIGHT::DOUBLE AS WEIGHT
,AREA::DOUBLE AS AREA
,CASE VENDOR_ID::INTEGER WHEN 0 THEN NULL ELSE VENDOR_ID::INTEGER END AS VENDOR_ID
,NULLIF(TRIM(VENDOR_NAME::string), '') AS VENDOR_NAME
,EXP_MARG::DOUBLE AS EXP_MARG
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
,ESS_TRANX_UUID::string AS ESS_TRANX_UUID
FROM {{ref('prep_ess_tranx')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'