{{
  config(
    materialized = "view",
    alias = "projet_l",
    schema='spm_ca',
    tags=["projet_l"]
  )
}}
  SELECT
    UPPER(NULLIF(ENTITY_CODE, ''))::string AS  ENTITY_CODE --Upper string
    ,NULLIF(NO_PROJET, '')::string AS  NO_PROJET
    ,NULLIF(NO_PRODUIT, '')::string AS  NO_PRODUIT
    ,TO_BOOLEAN(NULLIF(TYPE_FACT, '')::string) AS  TYPE_FACT
    --100% 0
    --,STATS_TMPS_E_3::string AS  STATS_TMPS_E_3
    ,IFNULL(STATS_TMPS_E_1, 0)::DOUBLE AS  STATS_TMPS_E_1
    --100% 0
    --,STATS_TMPS_E_7::string AS  STATS_TMPS_E_7
    --100% 0
    --,STATS_TMPS_E_6::string AS  STATS_TMPS_E_6
    --100% 0
    --,STATS_TMPS_E_5::string AS  STATS_TMPS_E_5
    --100% 0
    --,STATS_TMPS_E_2::string AS  STATS_TMPS_E_2
    --100% 0
    --,STATS_TMPS_E_4::string AS  STATS_TMPS_E_4
    ,IFNULL(STATS_TMPS_IS_1, 0)::DOUBLE AS  STATS_TMPS_IS_1
    ,IFNULL(STATS_TMPS_IS_2, 0)::DOUBLE AS  STATS_TMPS_IS_2
    ,IFNULL(STATS_TMPS_IS_3, 0)::DOUBLE AS  STATS_TMPS_IS_3
    ,IFNULL(STATS_TMPS_IS_4, 0)::DOUBLE AS  STATS_TMPS_IS_4
    ,IFNULL(STATS_TMPS_IS_5, 0)::DOUBLE AS  STATS_TMPS_IS_5
    ,IFNULL(STATS_TMPS_IS_6, 0)::DOUBLE AS  STATS_TMPS_IS_6
    --100% 0
    --,STATS_TMPS_IR_4::DOUBLE AS  STATS_TMPS_IR_4
    --100% 0
    --,STATS_TMPS_IR_3::DOUBLE AS  STATS_TMPS_IR_3
    --100% 0
    --,STATS_TMPS_IR_2::DOUBLE AS  STATS_TMPS_IR_2
    ,IFNULL(STATS_TMPS_IR_1, 0)::DOUBLE AS  STATS_TMPS_IR_1
    --100% 0
    --,STATS_TMPS_IR_6::DOUBLE AS  STATS_TMPS_IR_6
    --100% 0
    --,STATS_TMPS_IR_5::DOUBLE AS  STATS_TMPS_IR_5
    --100% NULL
    --,DESSIN_DEB::string AS  DESSIN_DEB
    --100% NULL
    --,DESSIN_FIN::string AS  DESSIN_FIN
    ,IFNULL(STATS_UNITES_1, 0)::DOUBLE AS  STATS_UNITES_1
    ,IFNULL(STATS_UNITES_2, 0)::DOUBLE AS  STATS_UNITES_2
    ,IFNULL(STATS_UNITES_3, 0)::DOUBLE AS  STATS_UNITES_3
    ,IFNULL(STATS_UNITES_4, 0)::DOUBLE AS  STATS_UNITES_4
    --100% 0
    --,STATS_UNITES_5::string AS  STATS_UNITES_5
    ,IFNULL(STATS_POIDS_1, 0)::DOUBLE AS  STATS_POIDS_1
    ,IFNULL(STATS_POIDS_2, 0)::DOUBLE AS  STATS_POIDS_2
    ,IFNULL(STATS_POIDS_3, 0)::DOUBLE AS  STATS_POIDS_3
    ,IFNULL(STATS_POIDS_4, 0)::DOUBLE AS  STATS_POIDS_4
    --100% 0
    --,STATS_POIDS_5::string AS  STATS_POIDS_5
    ,IFNULL(STATS_POIDS_6, 0)::DOUBLE AS  STATS_POIDS_6
    ,IFNULL(STATS_POIDS_7, 0)::DOUBLE AS  STATS_POIDS_7
    --100% 0
    --,STATS_POIDS_8::string AS  STATS_POIDS_8
    ,IFNULL(STATS_TMPS_EI_1, 0)::DOUBLE AS  STATS_TMPS_EI_1
    --100% 0
    --,STATS_TMPS_EI_2::string AS  STATS_TMPS_EI_2
    --100% 0
    --,STATS_TMPS_EI_3::string AS  STATS_TMPS_EI_3
    --100% 0
    --,STATS_TMPS_EI_4::string AS  STATS_TMPS_EI_4
    --100% 0
    --,STATS_TMPS_EI_5::string AS  STATS_TMPS_EI_5
    --100% 0
    --,STATS_TMPS_EI_6::string AS  STATS_TMPS_EI_6
    ,IFNULL(COMPLEX_CODE, 0)::INTEGER AS  COMPLEX_CODE
    ,TO_BOOLEAN(NULLIF(STATUT, '')::string) AS  STATUT
    ,D_HIST_LIVR_1::DATE AS  D_HIST_LIVR_1
    --100% NULL
    --,D_HIST_LIVR_2::string AS  D_HIST_LIVR_2
    --100% NULL
    --,D_HIST_LIVR_3::string AS  D_HIST_LIVR_3
    --100% NULL
    --,D_HIST_LIVR_4::string AS  D_HIST_LIVR_4
    --100% NULL
    --,D_HIST_LIVR_5::string AS  D_HIST_LIVR_5
    --100% NULL
    --,D_HIST_LIVR_6::string AS  D_HIST_LIVR_6
    ,IFNULL(ESTIM_DET, 0)::DOUBLE AS  ESTIM_DET
    ,TO_BOOLEAN(NULLIF(TYPE_PROJET, '')::string) AS  TYPE_PROJET
    ,UPPER(NULLIF(SLSMN_CODE, ''))::string AS  SLSMN_CODE
    --100% 0
    --,MNT_FACTURE::string AS  MNT_FACTURE
    --100% 0
    --,STATS_ANNUEL_1::string AS  STATS_ANNUEL_1
    --100% 0
    --,STATS_ANNUEL_2::string AS  STATS_ANNUEL_2
    --100% 0
    --,STATS_ANNUEL_3::string AS  STATS_ANNUEL_3
    --100% 0
    --,STATS_ANNUEL_4::string AS  STATS_ANNUEL_4
    ,TO_BOOLEAN(NULLIF(IND_F_CONN, '')::string) AS  IND_F_CONN
    ,IFNULL(NET_SALE, 0)::DOUBLE AS  NET_SALE
    ,IFNULL(PST_QUOTED, 0)::DOUBLE AS  PST_QUOTED
    ,IFNULL(NET_U_PRICE, 0)::DOUBLE AS  NET_U_PRICE
    ,IFNULL(ESTIM_DES, 0)::DOUBLE AS  ESTIM_DES
    ,IFNULL(DESGO_Q, 0)::DOUBLE AS  DESGO_Q
    ,TO_BOOLEAN(NULLIF(WASTE_OUT, '')::string) AS WASTE_OUT
    ,TO_BOOLEAN(NULLIF(INV_CAT, '')::string) AS  INV_CAT
    ,IFNULL(STATS_TMPS_S_1, 0)::DOUBLE AS  STATS_TMPS_S_1
    ,IFNULL(STATS_TMPS_S_2, 0)::DOUBLE AS  STATS_TMPS_S_2
    ,IFNULL(STATS_TMPS_S_3, 0)::DOUBLE AS  STATS_TMPS_S_3
    ,IFNULL(STATS_TMPS_S_4, 0)::DOUBLE AS  STATS_TMPS_S_4
    ,IFNULL(STATS_TMPS_S_5, 0)::DOUBLE AS  STATS_TMPS_S_5
    ,IFNULL(STATS_TMPS_S_6, 0)::DOUBLE AS  STATS_TMPS_S_6
    ,IFNULL(STATS_TMPS_S_7, 0)::DOUBLE AS  STATS_TMPS_S_7
    ,IFNULL(STATS_TMPS_R_1, 0)::DOUBLE AS  STATS_TMPS_R_1
    --100% 0
    --,STATS_TMPS_R_2::string AS  STATS_TMPS_R_2
    --100% 0
    --,STATS_TMPS_R_3::string AS  STATS_TMPS_R_3
    --100% 0
    --,STATS_TMPS_R_4::string AS  STATS_TMPS_R_4
    --100% 0
    --,STATS_TMPS_R_5::string AS  STATS_TMPS_R_5
    --100% 0
    --,STATS_TMPS_R_6::string AS  STATS_TMPS_R_6
    --100% 0
    --,STATS_TMPS_R_7::string AS  STATS_TMPS_R_7
    ,IFNULL(DSG_COST_1, 0)::DOUBLE AS  DSG_COST_1
    ,IFNULL(DSG_COST_2, 0)::DOUBLE AS  DSG_COST_2
    --100% 0
    --,DSG_COST_3::string AS  DSG_COST_3
    --100% 0
    --,DSG_COST_4::string AS  DSG_COST_4
    --100% 0
    --,DSG_COST_5::string AS  DSG_COST_5
    --100% 0
    --,DSG_COST_6::string AS  DSG_COST_6
    --100% 0
    --,MARK_DESIGN_QTY::string AS  MARK_DESIGN_QTY
    --100% 0
    --,TIME_PROCSS_R::string AS  TIME_PROCSS_R
    --100% 0
    --,COST_PROCSS_R::string AS  COST_PROCSS_R
    ,IFNULL(STATS_COST_1, 0)::DOUBLE AS  STATS_COST_1
    ,IFNULL(STATS_COST_2, 0)::DOUBLE AS  STATS_COST_2
    ,IFNULL(STATS_COST_3, 0)::DOUBLE AS  STATS_COST_3
    ,CMG_END_DETAIL::DATE AS  CMG_END_DETAIL
    --100% 0
    --,TIME_PROCSS_I::string AS  TIME_PROCSS_I
    --100% 0
    --,COST_PROCSS_I::string AS  COST_PROCSS_I
    -- ~Vide
    --,OFFICE_CODE::string AS  OFFICE_CODE
    -- ~Vide
    --,BRANCH_OFFICE_CODE::string AS  BRANCH_OFFICE_CODE
    ,IFNULL(SCORE_HRS_TON, 0)::DOUBLE AS  SCORE_HRS_TON
    ,NULLIF(VENDOR_ID, 0)::INTEGER AS  VENDOR_ID
    ,NULLIF(VENDOR_NAME, '')::string AS  VENDOR_NAME
    ,NULLIF(REVENUE_QUANTITY_TYPE_UUID, '')::string AS  REVENUE_QUANTITY_TYPE_UUID
    ,IFNULL(ERECTOR_PRIV_SHIPPED_UOM_TRANSF, 0)::DOUBLE AS  ERECTOR_PRIV_SHIPPED_UOM_TRANSF
    ,NULLIF(PROJET_L_UUID, '')::string AS  PROJET_L_UUID
    ,ROW_ID::string AS  ROW_ID
    ,SRC_SYSTEM_OPERATION::string AS  SRC_SYSTEM_OPERATION
    ,IPAAS_UPDATED_DATE::string AS IPAAS_UPDATED_DATE
    ,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
    ,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
    ,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
    ,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
  from {{ref('prep_projet_l')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'