{{
  config(
    materialized = "view",
    alias = "proj_seq",
    schema='spm_ca'
  )
}}


SELECT 
DRAWING_APPROVAL_TYPE_UUID::STRING AS DRAWING_APPROVAL_TYPE_UUID
,UPPER(BUYER::STRING) AS BUYER
,UPPER(STRUCTURAL_COMMENTS::STRING) AS STRUCTURAL_COMMENTS
,ENGINEERING_COMMENTS::STRING AS ENGINEERING_COMMENTS
,UPPER(DRWG_OFFICE_CODE::STRING) AS DRWG_OFFICE_CODE
,UPPER(CHECKING_OFFICE_CODE::STRING) AS CHECKING_OFFICE_CODE
,UPPER(RFI2INITIALS::STRING) AS RFI2INITIALS
,UPPER(READYTOSTAMPSETBY::STRING) AS READYTOSTAMPSETBY
,UPPER(STAMPINGDONESETBY::STRING) AS STAMPINGDONESETBY
,UPPER(RFI_INITIALS::STRING) AS RFI_INITIALS
,UPPER(MARKING_COLOR_UUID::STRING) AS MARKING_COLOR_UUID
,UPPER(ERECTION_PLANS_RESPONSIBLE::STRING) AS ERECTION_PLANS_RESPONSIBLE
,DIVISION_COMMENTS::STRING AS DIVISION_COMMENTS
,UPPER(SEQ_DIV::STRING) AS SEQ_DIV
,UPPER(DRAWING_APPROVAL_REVISION_CODE::STRING) AS DRAWING_APPROVAL_REVISION_CODE
,EXPEDITION_COMMENTS::STRING AS EXPEDITION_COMMENTS
,LOWER(CREATEDBY::STRING) AS CREATEDBY
,UPPER(FILE_AND_FIELD_REVISION_CODE::STRING) AS FILE_AND_FIELD_REVISION_CODE
,UPPER(LAYOUT_CHECKER_INITIALS::STRING) AS LAYOUT_CHECKER_INITIALS
,UPPER(COMPLEXITY_COMMENTS::STRING) AS COMPLEXITY_COMMENTS
,UPPER(PROJ_HOLD_CODE::STRING) AS PROJ_HOLD_CODE
,UPPER(LAYOUT_INITIALS::STRING) AS LAYOUT_INITIALS
,UPPER(ENG_DATES_1::STRING) AS ENG_DATES_1
,UPPER(ENG_DATES_2::STRING) AS ENG_DATES_2
,UPPER(SEQ_NAME::STRING) AS SEQ_NAME
,ENG_APP_INIT_1::STRING AS ENG_APP_INIT_1
,ENG_APP_INIT_2::STRING AS ENG_APP_INIT_2
,ENG_APP_INIT_3::STRING AS ENG_APP_INIT_3
,ENG_APP_INIT_4::STRING AS ENG_APP_INIT_4
,R_UPDATE::STRING AS R_UPDATE
,UPPER(NO_PROJET::STRING) AS NO_PROJET

/*Always Blank*/
--,UPPER(STRUCT_COMMNT_5::STRING) AS STRUCT_COMMNT_5
--,UPPER(STRUCT_COMMNT_4::STRING) AS STRUCT_COMMNT_4
--,UPPER(STRUCT_COMMNT_3::STRING) AS STRUCT_COMMNT_3
--,UPPER(STRUCT_COMMNT_2::STRING) AS STRUCT_COMMNT_2
--,UPPER(STRUCT_COMMNT_1::STRING) AS STRUCT_COMMNT_1
--,UPPER(COMMENTS_1::STRING) AS COMMENTS_1
--,UPPER(COMMENTS_2::STRING) AS COMMENTS_2
--,UPPER(COMMENTS_3::STRING) AS COMMENTS_3
--,UPPER(COMMENTS_4::STRING) AS COMMENTS_4
--,UPPER(COMMENTS_5::STRING) AS COMMENTS_5
--,MODIFIEDBY::STRING AS MODIFIEDBY
--,BUY_LIST::STRING AS BUY_LIST
--,STRUCT_PLANT::STRING AS STRUCT_PLANT
--,SPECIALATTENTIONUUID::STRING AS SPECIALATTENTIONUUID
--,ENG_REMARKS_1::STRING AS ENG_REMARKS_1
--,ENG_REMARKS_2::STRING AS ENG_REMARKS_2


/*Always Null*/
--,UPPER(MATERIAL_RECEIVED::STRING) AS MATERIAL_RECEIVED


-- Date Fields
,TO_TIMESTAMP_NTZ(DRWG_APPR_DROPDEAD_DATE::STRING) AS DRWG_APPR_DROPDEAD_DATE
,TO_TIMESTAMP_NTZ(LAYOUT_CHECKER_END_DATE::STRING) AS LAYOUT_CHECKER_END_DATE
,TO_TIMESTAMP_NTZ(TIE_JOIST_OUT_TARGET::STRING) AS TIE_JOIST_OUT_TARGET
,TO_TIMESTAMP_NTZ(REQ_COMPL_DROPDEAD_DATE::STRING) AS REQ_COMPL_DROPDEAD_DATE
,TO_TIMESTAMP_NTZ(ENGINEERING_VERIFICATION_DATE::STRING) AS ENGINEERING_VERIFICATION_DATE
,TO_TIMESTAMP_NTZ(RFI2ENDTARGET::STRING) AS RFI2ENDTARGET
,TO_TIMESTAMP_NTZ(RFI2STARTDATE::STRING) AS RFI2STARTDATE
,TO_TIMESTAMP_NTZ(DELI_APPROVED_DATE_PROJ_COORD::STRING) AS DELI_APPROVED_DATE_PROJ_COORD
,TO_TIMESTAMP_NTZ(DRWG_APPROVED_DRAFT_OFFICE_DATE::STRING) AS DRWG_APPROVED_DRAFT_OFFICE_DATE
,TO_TIMESTAMP_NTZ(BINDER_RECEIVED_DATE::STRING) AS BINDER_RECEIVED_DATE
,TO_TIMESTAMP_NTZ(DRWG_RECEIVED_DRAFT_OFFICE_DATE::STRING) AS DRWG_RECEIVED_DRAFT_OFFICE_DATE
,TO_TIMESTAMP_NTZ(ENGINEERING_TARGET::STRING) AS ENGINEERING_TARGET
,TO_TIMESTAMP_NTZ(FABRICATION_START_DATE::STRING) AS FABRICATION_START_DATE
,TO_TIMESTAMP_NTZ(LAYOUT_START_DATE::STRING) AS LAYOUT_START_DATE
,TO_TIMESTAMP_NTZ(LAYOUT_END_DATE::STRING) AS LAYOUT_END_DATE
,TO_TIMESTAMP_NTZ(MAXIMUMPURCHASESTARTDATE::STRING) AS MAXIMUMPURCHASESTARTDATE
,TO_TIMESTAMP_NTZ(DELI_APPROVED_DATE_DELI_COORD::STRING) AS DELI_APPROVED_DATE_DELI_COORD
,TO_TIMESTAMP_NTZ(ENG_START_DATE_1::STRING) AS ENG_START_DATE_1
,TO_TIMESTAMP_NTZ(ENG_START_DATE_2::STRING) AS ENG_START_DATE_2
,TO_TIMESTAMP_NTZ(ENG_START_DATE_3::STRING) AS ENG_START_DATE_3
,TO_TIMESTAMP_NTZ(ENG_START_DATE_4::STRING) AS ENG_START_DATE_4
,TO_TIMESTAMP_NTZ(ENG_END_DATE_1::STRING) AS ENG_END_DATE_1
,TO_TIMESTAMP_NTZ(ENG_END_DATE_2::STRING) AS ENG_END_DATE_2
,TO_TIMESTAMP_NTZ(ENG_END_DATE_3::STRING) AS ENG_END_DATE_3
,TO_TIMESTAMP_NTZ(ENG_END_DATE_4::STRING) AS ENG_END_DATE_4
,TO_TIMESTAMP_NTZ(LAYOUT_BACK_FOR_CHECK_TARGET::STRING) AS LAYOUT_BACK_FOR_CHECK_TARGET
,TO_TIMESTAMP_NTZ(RELEASE_ENG_DROPDEAD_DATE::STRING) AS RELEASE_ENG_DROPDEAD_DATE
,TO_TIMESTAMP_NTZ(FABRICATIONTARGET_1::STRING) AS FABRICATIONTARGET_1
,TO_TIMESTAMP_NTZ(FABRICATIONTARGET_2::STRING) AS FABRICATIONTARGET_2
,TO_TIMESTAMP_NTZ(RFI_END_DATE::STRING) AS RFI_END_DATE
,TO_TIMESTAMP_NTZ(KICKOFFCOMPLETEDATE::STRING) AS KICKOFFCOMPLETEDATE
,TO_TIMESTAMP_NTZ(LAYOUT_CHECKER_START_DATE::STRING) AS LAYOUT_CHECKER_START_DATE
,TO_TIMESTAMP_NTZ(ERECTIONPLANTARGET::STRING) AS ERECTIONPLANTARGET
,TO_TIMESTAMP_NTZ(TIE_JOIST_OUT::STRING) AS TIE_JOIST_OUT
,TO_TIMESTAMP_NTZ(RFI_END_TARGET::STRING) AS RFI_END_TARGET
,TO_TIMESTAMP_NTZ(MODIFIEDDATE::STRING) AS MODIFIEDDATE 
,TO_TIMESTAMP_NTZ(LAYOUT_APPROVAL_TARGET::STRING) AS LAYOUT_APPROVAL_TARGET 
,TO_TIMESTAMP_NTZ(QVIEMAILALERTSENTDATETIME::STRING) AS QVIEMAILALERTSENTDATETIME 
,TO_TIMESTAMP_NTZ(PURCHASESTARTDATE::STRING) AS PURCHASESTARTDATE
,TO_TIMESTAMP_NTZ(FABR_COMPL_DROPDEAD_DATE::STRING) AS FABR_COMPL_DROPDEAD_DATE
,TO_TIMESTAMP_NTZ(PURCHASE_END::STRING) AS PURCHASE_END
,TO_TIMESTAMP_NTZ(DRWG_SENTOUT_DROPDEAD_DATE::STRING) AS DRWG_SENTOUT_DROPDEAD_DATE 
,TO_TIMESTAMP_NTZ(STAMPINGDONEDATETIME::STRING) AS STAMPINGDONEDATETIME
,TO_TIMESTAMP_NTZ(CLASHDETECTIONTARGET::STRING) AS CLASHDETECTIONTARGET
,TO_TIMESTAMP_NTZ(ABM::STRING) AS ABM
,TO_TIMESTAMP_NTZ(RFI_START_DATE::STRING) AS RFI_START_DATE
,TO_TIMESTAMP_NTZ(RFI2ENDDATE::STRING) AS RFI2ENDDATE
,TO_TIMESTAMP_NTZ(CREATEDDATE::STRING) AS CREATEDDATE
,TO_TIMESTAMP_NTZ(READYTOSTAMPDATETIME::STRING) AS READYTOSTAMPDATETIME
,TO_TIMESTAMP_NTZ(WALLPANELSMATERIALS::STRING) AS WALLPANELSMATERIALS
,TO_TIMESTAMP_NTZ(DRWG_RCVD_DROPDEAD_DATE::STRING) AS DRWG_RCVD_DROPDEAD_DATE
,TO_TIMESTAMP_NTZ(D_UPDATE::STRING) AS D_UPDATE
,TO_TIMESTAMP_NTZ(DRW_DATES_1::STRING) AS DRW_DATES_1
,TO_TIMESTAMP_NTZ(DRW_DATES_2::STRING) AS DRW_DATES_2
,TO_TIMESTAMP_NTZ(DRW_DATES_3::STRING) AS DRW_DATES_3
,TO_TIMESTAMP_NTZ(DRW_DATES_4::STRING) AS DRW_DATES_4
,TO_TIMESTAMP_NTZ(DRW_DATES_5::STRING) AS DRW_DATES_5
,TO_TIMESTAMP_NTZ(DRW_DATES_6::STRING) AS DRW_DATES_6
,TO_TIMESTAMP_NTZ(DRW_DATES_7::STRING) AS DRW_DATES_7
,TO_TIMESTAMP_NTZ(D_SHIP::STRING) AS D_SHIP
,TO_TIMESTAMP_NTZ(D_PROD::STRING) AS D_PROD
,TO_TIMESTAMP_NTZ(D_DESIGN::STRING) AS D_DESIGN

/*Always Null*/
--,TO_TIMESTAMP_NTZ(RECENT_DELIVERY::STRING) AS RECENT_DELIVERY
--,TO_TIMESTAMP_NTZ(CLASHDETECTIONEND::STRING) AS CLASHDETECTIONEND

-- Boolean Fields
,TO_BOOLEAN(COPYCTMADVANCEMENT::STRING) AS COPYCTMADVANCEMENT
,TO_BOOLEAN(DELI_APPROVED_BY_DELI_COORD::STRING) AS DELI_APPROVED_BY_DELI_COORD
,TO_BOOLEAN(COMPLETE_DELIVERY::STRING) AS COMPLETE_DELIVERY
,TO_BOOLEAN(INITIAL_CONTRACT::STRING) AS INITIAL_CONTRACT
,TO_BOOLEAN(ERECTOR_PRIVILEGE_INCLUDED::STRING) AS ERECTOR_PRIVILEGE_INCLUDED
,TO_BOOLEAN(DELI_APPROVED_BY_PROJ_COORD::STRING) AS DELI_APPROVED_BY_PROJ_COORD
,TO_BOOLEAN(QUALITY_VERIFICATION_ENGINEER::STRING) AS QUALITY_VERIFICATION_ENGINEER
,TO_BOOLEAN(FAST_TRACK::STRING) AS FAST_TRACK
,TO_BOOLEAN(SITE_PRINTED::STRING) AS SITE_PRINTED
,TO_BOOLEAN(INDC_RESERV::STRING) AS INDC_RESERV
,TO_BOOLEAN(JOB_TYPE::STRING) AS JOB_TYPE
--,TO_BOOLEAN(COMPLETE::STRING) AS COMPLETE /**Always Zero**/


-- Numeric Fields
,FABRICATIONESTIMATEDWEEKSDELAY::INTEGER AS FABRICATIONESTIMATEDWEEKSDELAY
,COMPLEXITY_CODE::INTEGER AS COMPLEXITY_CODE
,DRAWINGESTIMATEDWEEKSDELAY::INTEGER AS DRAWINGESTIMATEDWEEKSDELAY
,DELI_APPROVED_TIME_PROJ_COORD::INTEGER AS DELI_APPROVED_TIME_PROJ_COORD
,APPROVALESTIMATEDWEEKSDELAY::INTEGER AS APPROVALESTIMATEDWEEKSDELAY
,COPYCTMTASKSFROM::INTEGER AS COPYCTMTASKSFROM
,ERECTION_PLANS_RESP_PEOPLE_ID::INTEGER AS ERECTION_PLANS_RESP_PEOPLE_ID
,DELI_APPROVED_TIME_DELI_COORD::INTEGER AS DELI_APPROVED_TIME_DELI_COORD
,W_DESIGN::INTEGER AS W_DESIGN

/*Always Empty*/
--,FABRICATIONMANUALDELAY::INTEGER AS FABRICATIONMANUALDELAY

/*Always Null*/

,W_PROD::INTEGER AS W_PROD
,W_SHIP::INTEGER AS W_SHIP  
,SEQ_NO::INTEGER AS SEQ_NO

/*Always Zero*/
--,DRAFTING_ADVANCEMENT::INTEGER AS DRAFTING_ADVANCEMENT


-- Additional Formatting (if needed)

from {{ref('prep_proj_seq')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'
