{{
  config(
    materialized = "view",
    alias = "qc_quotation_customer",
    schema='spm_ca'
  )
}}
 SELECT
 NULLIF(TRIM(QC_QUOTATION_CUSTOMER_UUID::string), '') AS QC_QUOTATION_CUSTOMER_UUID
,NULLIF(UPPER(TRIM(OFFICE_CODE::string)), '') AS OFFICE_CODE
,NULLIF(TRIM(JOB_NO::string), '') AS JOB_NO
,RANK::INTEGER AS RANK
,SELECT_DATE::DATE AS SELECT_DATE
-- always NULL
--,NULLIF(TRIM(DUMMY::string), '') AS DUMMY
-- always NULL
--,NULLIF(TRIM(MEMO::string),'') AS MEMO
-- always NULL
--,NULLIF(TRIM(WARNING_TEXT::string),'') AS WARNING_TEXT
,DELIVR_DATE::DATE AS DELIVR_DATE
,LAST_UPDATE_DATE::DATE AS LAST_UPDATE_DATE
,TO_BOOLEAN(FOLLOW_UP::string) AS FOLLOW_UP
,NULLIF(TRIM(CUSTOMER_UUID::string),'') AS CUSTOMER_UUID
,ERECTOR_PRIVILEGE_PROPOSED_DATE::DATE AS ERECTOR_PRIVILEGE_PROPOSED_DATE
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
  from {{ref('prep_qc_quotation_customer')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'