{{
  config(
    materialized = "view",
    alias = "projetx_g",
    schema='spm_ca'
  )
}}
SELECT
UPPER(NULLIF(NO_PROJET::string,'')) AS NO_PROJET
,UPPER(TRIM(NULLIF(NO_ESTIME::string,''))) AS NO_ESTIME
,UPPER(NULLIF(ENTITY_CODE::string,'')) AS ENTITY_CODE
,CASE WHEN LENGTH(NO_BON_ACHAT::string) < 2 THEN NULL ELSE UPPER(NO_BON_ACHAT::string) END AS NO_BON_ACHAT
,TIMESTAMPADD(second , T_SAISIE::INTEGER ,D_SAISIE::DATE ) AS DATETIME_SAISIE
,USAGER::string AS USAGER
,D_LIVRAISON::DATE AS D_LIVRAISON
,TO_BOOLEAN(FORM_IMPR::string) AS FORM_IMPR
,TYPE_APPR::INTEGER AS TYPE_APPR
,NULLIF(NO_APPR_CRE::INTEGER,0) AS NO_APPR_CRE
,D_APP_CREDIT::DATE AS D_APP_CREDIT
,SPLIT(NULLIF(LOWER(ORD_PROD::string), 'none'),',') AS ORD_PROD
,TO_BOOLEAN(GENERATION::string) AS GENERATION
,SEQ_NO::INTEGER AS SEQ_NO
,TO_BOOLEAN(GENERE::string) AS GENERE
-- always 0
--,NO_CATG::INTEGER AS NO_CATG
,TO_TIMESTAMP(NULLIF(PROJ_TRANSF::string,'0'),'YYYYMMDDHH24MISS') AS PROJ_TRANSF
--always NULL
--,SOLD_DATE::string AS SOLD_DATE
,UPPER(NULLIF(REVISION_TYPE::string,'')) AS REVISION_TYPE
,NULLIF(APPROVED_BY::string,'') AS APPROVED_BY
,TIMESTAMPADD(second , APPROVED_TIME::INTEGER ,APPROVED_DATE::DATE ) AS APPROVED_DATETIME
,UPPER(APPROVAL_STATUS::string) AS APPROVAL_STATUS
,NULLIF(UPPER(GDM_EXTRA_CODE::string),'') AS GDM_EXTRA_CODE
,PRICE_EXPIRATION_DATE::DATE AS PRICE_EXPIRATION_DATE
,QUOTATION_SENT_DATE::DATE AS QUOTATION_SENT_DATE
,UPPER(NO_AGENT_CT::string) AS NO_AGENT_CT
,NULLIF(ERECTOR_PRIVILEGE_PARENT_PROJ_ID::INTEGER,0) AS ERECTOR_PRIVILEGE_PARENT_PROJ_ID
,NULLIF(FINANCIAL_COMMENTS::string,'') AS FINANCIAL_COMMENTS
,TO_BOOLEAN(OFFICIAL_BUDGET::string) AS OFFICIAL_BUDGET
,ESTIMATED_LAST_SHIPPING_DATE::DATE AS ESTIMATED_LAST_SHIPPING_DATE
,NULLIF(CMIC_POTENTIAL_CHANGE_ITEM_NUMBER::string,'') AS CMIC_POTENTIAL_CHANGE_ITEM_NUMBER
,PROJETX_G_UUID::string AS PROJETX_G_UUID
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
  from {{ref('prep_projetx_g')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'