{{
 config(
 materialized = "view",
 alias = "req_prod",
 schema='spm_ca'
 )
}}

SELECT
 UPPER(ENTITY_CODE::string) AS ENTITY_CODE
,NO_POIDS::integer AS NO_POIDS
,TO_BOOLEAN(IND_CALCUL::string) AS IND_CALCUL
,UPPER(NO_PROJET::string) AS NO_PROJET
,NO_POIDS_LIE::INTEGER AS NO_POIDS_LIE
,NO_PRODUIT::INTEGER AS NO_PRODUIT
,REAL_TIME_1::DOUBLE AS REAL_TIME_1
,REAL_TIME_2::DOUBLE AS REAL_TIME_2
,REAL_TIME_3::DOUBLE AS REAL_TIME_3
,REAL_TIME_4::DOUBLE AS REAL_TIME_4
,REAL_TIME_5::DOUBLE AS REAL_TIME_5
,REAL_TIME_6::DOUBLE AS REAL_TIME_6
,D_CREATION::DATE AS D_CREATION
,MESURE::INTEGER AS MESURE
,DIVISION::string AS DIVISION
,TO_BOOLEAN(COMPLETE::string) AS COMPLETE
,STATS_PROD_1::string AS STATS_PROD_1
,STATS_PROD_2::string AS STATS_PROD_2
,STATS_PROD_3::string AS STATS_PROD_3
,STATS_PROD_4::string AS STATS_PROD_4
,TO_BOOLEAN(MISE_EN_PROD::string) AS MISE_EN_PROD
,D_PROD::DATE AS D_PROD
,UPPER(NULLIF(NO_PEINTURE::string, '')) AS NO_PEINTURE
,UPPER(NULLIF(NO_DETAILER::string, '')) AS NO_DETAILER
,NO_TROU::INTEGER AS NO_TROU
-- 100% NULL
--,DATE_CAL_TPS::DATE AS DATE_CAL_TPS
,TYPE_REQ::INTEGER AS TYPE_REQ
,TO_BOOLEAN(PRINTED::string) AS PRINTED
,UPPER(NULLIF(CODE_FIN_T::string, '')) AS CODE_FIN_T
,UPPER(NULLIF(CODE_FIN_C::string, '')) AS CODE_FIN_C
--ALWAYS 0
--,SHOP_ORDER::INTEGER AS SHOP_ORDER
,D_SHOP::DATE AS D_SHOP
--100% NULL
--,SEQ_PAINT::string AS SEQ_PAINT
,SEQ_NO::INTEGER AS SEQ_NO
--100% NULL
--,SEL_MEP::string AS SEL_MEP
,SEQ_SHOP::INTEGER AS SEQ_SHOP
,SHOP_NO::INTEGER AS SHOP_NO
,NO_JOB_SHOP::INTEGER AS NO_JOB_SHOP
,END_ASS::INTEGER AS END_ASS
,END_WELD::INTEGER AS END_WELD
--100% NULL
--,REM_1::string AS REM_1
--100% NULL
--,REM_2::string AS REM_2
,ENG_REL_DATE::DATE AS ENG_REL_DATE
,TO_BOOLEAN(DET_ENABLE::string) AS DET_ENABLE
,PRODCT_STATUS::INTEGER AS PRODCT_STATUS
,DELIVR_STATUS::INTEGER AS DELIVR_STATUS
,FINISH_STATUS::INTEGER AS FINISH_STATUS
,UPPER(NULLIF(PAINT_INSTR_NO::string, '')) AS PAINT_INSTR_NO
,UPPER(NULLIF(PAINT_COLOR::string, '')) AS PAINT_COLOR
,NULLIF(SEQ_NO_LIST::string, '') AS SEQ_NO_LIST
,NULLIF(REMARK_1::string,'') AS REMARK_1
,NULLIF(REMARK_2::string,'') AS REMARK_2
,NULLIF(REMARK_3::string,'') AS REMARK_3
,NULLIF(REMARK_4::string,'') AS REMARK_4
,NULLIF(REMARK_5::string,'') AS REMARK_5
,NULLIF(REMARK_6::string,'') AS REMARK_6
,NULLIF(REVISN::string,'') AS REVISN
--100% NULL
--,NULLIF(ORIGINAL_ENTITY::string,'') AS ORIGINAL_ENTITY
--100% NULL
--,KRONOS_TRF_DATE::string AS KRONOS_TRF_DATE
--100% NULL
--,DECK_NOTES_ID_LIST::string AS DECK_NOTES_ID_LIST
,TO_BOOLEAN(PRIORITIZED::string) AS PRIORITIZED
--100% NULL
--,DUMMY::string AS DUMMY
,BRIDGING_GROUPED_DATE::DATE AS BRIDGING_GROUPED_DATE
,BRIDGING_GROUPED_TIME::INTEGER AS BRIDGING_GROUPED_TIME
,NULLIF(BRIDGING_GROUPED_BY::string, '') AS BRIDGING_GROUPED_BY
,REQUISITION_RECEIVED_DATE::DATE AS REQUISITION_RECEIVED_DATE
,TO_BOOLEAN(URGENT::string) AS URGENT
,TRANSFER_STATUS::INTEGER AS TRANSFER_STATUS
,MACHN_NO::INTEGER AS MACHN_NO
,FABRICATION_DROPDEAD_DATE::DATE AS FABRICATION_DROPDEAD_DATE
--100% NULL
--,FABRICATION_DROPDEAD_TIME::INTEGER AS FABRICATION_DROPDEAD_TIME
,NULLIF(FOB_CODE::STRING, '')::NUMBER AS FOB_CODE
,NULLIF(DELIVERY_COMMENT::string, '') AS DELIVERY_COMMENT
--100% NULL
--,FABRICATION_SHOP_TIME::INTEGER AS FABRICATION_SHOP_TIME
,DECK_GROUPED_REQUISITION::INTEGER AS DECK_GROUPED_REQUISITION
,NULLIF(BIN_LOCATION::string, '') AS BIN_LOCATION
,NULLIF(BIN_LOCATION_UPD_BY::string, '') AS BIN_LOCATION_UPD_BY
,TO_BOOLEAN(ROLLBAR_USE::string) AS ROLLBAR_USE
,TO_BOOLEAN(PRINT_INFORMATION_ON_ITEM::string) AS PRINT_INFORMATION_ON_ITEM
,NULLIF(STRUCTURAL_BOLT_ASSEMBLY_LOC::string, '') AS STRUCTURAL_BOLT_ASSEMBLY_LOC
,NULLIF(MARKING_COLOR_UUID::string,'') AS MARKING_COLOR_UUID
,TO_BOOLEAN(MULTI_DESTINATION::string) AS MULTI_DESTINATION
,TO_BOOLEAN(PRE_ASSEMBLED::string) AS PRE_ASSEMBLED
,PRE_ASSEMBLED_BOLT_REQUISITION::INTEGER AS PRE_ASSEMBLED_BOLT_REQUISITION
,PANEL_BUNDLE_NUMBER::INTEGER AS PANEL_BUNDLE_NUMBER
,CREATEDBY::string AS CREATED_BY
,TO_TIMESTAMP_NTZ(IMPORTATION_DATETIME::string) AS IMPORTATION_DATETIME
,TO_TIMESTAMP_NTZ(MODIFIEDDATE::string) AS MODIFIED_DATE
,ADDITIONAL_PLANNING_DATE::DATE AS ADDITIONAL_PLANNING_DATE
,NULLIF(PROJECT_PURCHASE_ORDER_UUID::string, '') AS PROJECT_PURCHASE_ORDER_UUID
,NULLIF(APPLICATION_TRANSFER_UUID::string, '') AS APPLICATION_TRANSFER_UUID
--100% NULL
--,PRODUCTION_SHIPPING_DELAY::INTEGER AS PRODUCTION_SHIPPING_DELAY
,TO_BOOLEAN(SEQUENCED_PREPARATION::INTEGER) AS SEQUENCED_PREPARATION
,CRATINGWEIGHT::DOUBLE AS CRATING_WEIGHT
,NULLIF(EXPECTEDASSEMBLYSHOPUUID::string, '') AS EXPECTED_ASSEMBLY_SHOP_UUID
,TO_TIMESTAMP_NTZ(EXPECTEDASSEMBLYDATETIME::string) AS EXPECTED_ASSEMBLY_DATETIME
,TO_BOOLEAN(BUNDLEDREQUISITION::string) AS BUNDLED_REQUISITION
--100% 0
--,EXTERNALID::INTEGER AS EXTERNAL_ID
,UPPER(NULLIF(ERECTIONLABEL::string, '')) AS ERECTION_LABEL
,TO_TIMESTAMP_NTZ(CREATEDDATE::string) AS CREATED_DATE
,NULLIF(MODIFIEDBY::string, '') AS MODIFIED_BY
FROM {{ ref('prep_req_prod') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'