{{
  config(
    materialized = "view",
    alias = "item_whs",
    schema='spm_ca'
  )
}}
  SELECT
 UPPER(IN_ENTITY::string) AS IN_ENTITY
,UPPER(ITEM_NO::string) AS ITEM_NO
,UPPER(WHS_CODE::string) AS WHS_CODE
,NULLIF(BIN_LOCATION::string,'') AS BIN_LOCATION
,UPPER(ENTITY_INV::string) AS ENTITY_INV
,NULLIF(UPPER(ENTITY_WIP::string), '') AS ENTITY_WIP
,LEAD_TIME::INTEGER AS LEAD_TIME
,REORDER_LEV::INTEGER AS REORDER_LEV
,ECON_ORD_QTY::INTEGER AS ECON_ORD_QTY
,PRD_OF_STOCK::INTEGER AS PRD_OF_STOCK
,PRD_RESEARCH::INTEGER AS PRD_RESEARCH
,REORDER_PCT::INTEGER AS REORDER_PCT
,TO_BOOLEAN(ALLOW_BO::string) AS ALLOW_BO
,UPPER(NULLIF(TRIM(MISC_CODE::string), '')) AS MISC_CODE
,PRI_REV_DATE::DATE AS PRI_REV_DATE
,PRICE_1::DOUBLE AS PRICE_1
,PRICE_2::DOUBLE AS PRICE_2
,PRICE_3::DOUBLE AS PRICE_3
,PRICE_4::DOUBLE AS PRICE_4
,PRICE_5::DOUBLE AS PRICE_5
,PRICE_6::DOUBLE AS PRICE_6
-- always 0
-- ,PRICE_7::DOUBLE AS PRICE_7
-- always 0
--,PRICE_8::DOUBLE AS PRICE_8
-- always 0
-- ,PRICE_9::DOUBLE AS PRICE_9
-- always 0
--,PRICE_10::DOUBLE AS PRICE_10
-- always TRUE
--,TO_BOOLEAN(DOLLAR_PCT_1::string) AS DOLLAR_PCT_1
-- always TRUE
--,TO_BOOLEAN(DOLLAR_PCT_2::string) AS DOLLAR_PCT_2
-- always TRUE
--,TO_BOOLEAN(DOLLAR_PCT_3::string) AS DOLLAR_PCT_3
-- always TRUE
--,TO_BOOLEAN(DOLLAR_PCT_4::string) AS DOLLAR_PCT_4
-- always TRUE
--,TO_BOOLEAN(DOLLAR_PCT_5::string) AS DOLLAR_PCT_5
-- always TRUE
--,TO_BOOLEAN(DOLLAR_PCT_6::string) AS DOLLAR_PCT_6
-- always TRUE
--,TO_BOOLEAN(DOLLAR_PCT_7::string) AS DOLLAR_PCT_7
-- always TRUE
--,TO_BOOLEAN(DOLLAR_PCT_8::string) AS DOLLAR_PCT_8
-- always TRUE
--,TO_BOOLEAN(DOLLAR_PCT_9::string) AS DOLLAR_PCT_9
-- always TRUE
--,TO_BOOLEAN(DOLLAR_PCT_10::string) AS DOLLAR_PCT_10
,TO_BOOLEAN(PST_EXEMPT::string) AS PST_EXEMPT
,TO_BOOLEAN(FST_EXEMPT::string) AS FST_EXEMPT
,NULLIF(TRIM(FST_CODE::string), '') AS FST_CODE
,NULLIF(TRIM(TAXABLE::string), '')::INTEGER AS TAXABLE
,NULLIF(TRIM(COST_METHOD::string), '')::INTEGER AS COST_METHOD
,NULLIF(PROD_GROUP::string, '') AS PROD_GROUP
,NULLIF(LAST_VENDOR::string, '') AS LAST_VENDOR
,TO_BOOLEAN(AUTOMT_RELEASE::string) AS AUTOMT_RELEASE
,TO_BOOLEAN(HIST_TRANS::string) AS HIST_TRANS
,STD_TIME::DOUBLE AS STD_TIME
,ORDER_LEVEL::INTEGER AS ORDER_LEVEL
,PRODUCTION_COST::DOUBLE AS PRODUCTION_COST
,TO_BOOLEAN(ACTIVE::string) AS ACTIVE
,TO_TIMESTAMP_NTZ(DEACTIVATION_DATETIME::string) AS DEACTIVATION_DATETIME
,NULLIF(TRIM(DEACTIVATION_BY::string), '') AS DEACTIVATION_BY
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
  from {{ref('prep_item_whs')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'