{{
  config(
    materialized = "view",
    alias = "project_event_sales_group",
    schema='spm_ca'
  )
}}
  SELECT
    PROJECT_EVENT_SALES_GROUP_UUID::string AS PROJECT_EVENT_SALES_GROUP_UUID
    ,PROJECT_EVENT_UUID::string AS PROJECT_EVENT_UUID
    ,NULLIF(SALES_GROUP_CODE, '')::INTEGER AS SALES_GROUP_CODE
    ,NULLIF(BACKCHARGE_PERCENTAGE, '')::DOUBLE AS BACKCHARGE_PERCENTAGE
    --,ROW_ID::string AS ROW_ID
    --,src_system_operation::string AS SRC_SYSTEM_OPERATION
    --,IPAAS_UPDATED_DATE::string AS IPAAS_UPDATED_DATE
    ,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
    ,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
    ,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
    ,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
  from {{ref('prep_project_event_sales_group')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'