{{
  config(
    materialized = "view",
    alias = "qc_quotation_product",
    schema='spm_ca',
    tags=["qc_quotation_product"],
    meta = {
        'table_key': 'NAME_1',
        'tests': {
            'null_values':{
                'columns':[
                    'RDM_CURRENCY_CODE'
                ]
            }
        }    
    }
  )
}}

WITH raw_qc_quotation_product AS (
  SELECT * FROM {{ref('prep_qc_quotation_product')}}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'
)

SELECT

  /*Always Null*/

/*Uncertain column Data*/
--,SPLIT(DUMMY::string, '|') AS DUMMY
--,NULLIF(TRIM(DUMMY::string), '') AS DUMMY

  /*String Fields*/
  NULLIF(UPPER(TRIM(OFFICE_CODE::string)),'') AS OFFICE_CODE
  ,COALESCE(JOB_NO::string, '') AS JOB_NO
  ,UPPER(GROUP_DESCRP_1::string) AS GROUP_DESCRP_1
  ,UPPER(GROUP_DESCRP_2::string) AS GROUP_DESCRP_2
  ,UPPER(GROUP_DESCRP_3::string) AS GROUP_DESCRP_3
  ,UPPER(SPM_ENTITY_CODE::string) AS SPM_ENTITY_CODE
  ,TO_BOOLEAN(QTY_TYPE::string) AS QTY_TYPE
  ,TO_BOOLEAN(APPLY_MARK_UP::string) AS APPLY_MARK_UP
  ,NULLIF(TRIM(SORT_NAME::string), '') AS SORT_NAME
  ,NULLIF(TRIM(ITEM_NO::string), '') AS ITEM_NO
  ,NULLIF(TRIM(UOM_CODE::string), '') AS UOM_CODE
  ,NULLIF(TRIM(UDM_ALT::string), '') AS UDM_ALT
  ,UPPER(NULLIF(TRIM(NAME_1::string), '')) AS NAME_1
  ,UPPER(NULLIF(TRIM(NAME_2::string), '')) AS NAME_2
  ,UPPER(NULLIF(TRIM(NAME_3::string), '')) AS NAME_3
  ,UPPER(NULLIF(TRIM(NAME_4::string), '')) AS NAME_4
  ,TO_BOOLEAN(STD::string) AS STD
  ,UPPER(NULLIF(TRIM(UNIT_QTY_1::string), '')) AS UNIT_QTY_1
  ,UPPER(NULLIF(TRIM(UNIT_QTY_2::string), '')) AS UNIT_QTY_2
  ,CASE 
    WHEN NULLIF(TRIM(CURRENCY_COD::string), '') LIKE 'US%' THEN 'USD' 
    WHEN NULLIF(TRIM(CURRENCY_COD::string), '') LIKE 'CA%' THEN 'CAD'
    ELSE NULLIF(TRIM(CURRENCY_COD::string), '') 
   END AS CURRENCY_CODE
  ,NULLIF(TRIM(QC_QUOT_PRODUCT_HIERARCHY_UUID::string), '') AS QC_QUOT_PRODUCT_HIERARCHY_UUID
  ,NULLIF(TRIM(JOB_COST_LINE_ENTITY_CODE::string), '') AS JOB_COST_LINE_ENTITY_CODE
  ,NULLIF(TRIM(CREATEDBY::string), '') AS CREATED_BY
  ,NULLIF(TRIM(MODIFIEDBY::string), '') AS MODIFIED_BY
  ,UPPER(NULLIF(TRIM(SRC_SYSTEM_OPERATION::string), '')) AS SRC_SYSTEM_OPERATION
  ,RDM.STANDARD_APPLICATION_VALUE AS RDM_CURRENCY_CODE

  /*Numeric Fields*/
  ,PRODCT_NO::INTEGER AS PRODCT_NO
  ,ACC_NO::INTEGER AS ACC_NO
  ,BUD_DELI_COST::DOUBLE AS BUD_DELI_COST
  ,BUD_PROD_COST::DOUBLE AS BUD_PROD_COST
  ,BUD_WEIGHT::DOUBLE AS BUD_WEIGHT
  ,EST_DELI_COST::DOUBLE AS EST_DELI_COST
  ,EST_PROD_COST::DOUBLE AS EST_PROD_COST
  ,EST_WEIGHT::INTEGER AS EST_WEIGHT
  ,FAB_IND_H::DOUBLE AS FAB_IND_H
  ,FAB_SET_H_1::DOUBLE AS FAB_SET_H_1
  ,FAB_SET_H_2::DOUBLE AS FAB_SET_H_2
  ,GROUP_NO::INTEGER AS GROUP_NO
  ,MARK_QTY::INTEGER AS MARK_QTY
  ,QTY_1::INTEGER AS QTY_1
  ,QTY_2::INTEGER AS QTY_2
  ,SURFACE::DOUBLE AS SURFACE
  ,SPM_PRODCT_NO::INTEGER AS SPM_PRODCT_NO
  ,SEQ_NO::INTEGER AS SEQ_NO
  ,MARKUP_WEIGHT_PCT::DOUBLE AS MARKUP_WEIGHT_PCT
  ,MARKUP_WEIGHT::INTEGER AS MARKUP_WEIGHT
  ,MARKUP_PRICE_PCT::DOUBLE AS MARKUP_PRICE_PCT
  ,MARKUP_PRICE_DOLLAR::INTEGER AS MARKUP_PRICE_DOLLAR
  ,GROUP_RPT_MODEL::INTEGER AS GROUP_RPT_MODEL
  ,ESTIM_DET::DOUBLE AS ESTIM_DET
  ,ESTIM_DES::DOUBLE AS ESTIM_DES
  ,DSG_COST_1::DOUBLE AS DSG_COST_1
  ,DSG_COST_2::DOUBLE AS DSG_COST_2
  ,DSG_COST_3::DOUBLE AS DSG_COST_3
  ,DSG_COST_4::DOUBLE AS DSG_COST_4
  ,DSG_COST_5::DOUBLE AS DSG_COST_5
  ,DSG_COST_6::DOUBLE AS DSG_COST_6
  ,COALESCE(COMPLEX_CODE::INTEGER, 0) AS COMPLEX_CODE
  ,MEASURE_QTY::DOUBLE AS MEASURE_QTY
  ,ESTIMT_MODUL::INTEGER AS ESTIMT_MODUL
  ,BREAK_AMT::INTEGER AS BREAK_AMT
  ,COALESCE(CONSTR_LOAD::INTEGER,0) AS CONSTR_LOAD
  ,LINE_NO::INTEGER AS LINE_NO
  ,COALESCE(NUMBER_OF_ESCORTS::DOUBLE,0) AS NUMBER_OF_ESCORTS
  ,DELIVERY_COUNTRY_TAXES_AMOUNT::DOUBLE AS DELIVERY_COUNTRY_TAXES_AMOUNT
  ,PRODUCTION_COUNTRY_TAXES_AMOUNT::DOUBLE AS PRODUCTION_COUNTRY_TAXES_AMOUNT
  ,ADJUSTMENT_GROSS_MARGIN::DOUBLE AS ADJUSTMENT_GROSS_MARGIN

  /*Boolean Fields*/
  ,TO_BOOLEAN(FREIGHT::string) AS FREIGHT
  ,TO_BOOLEAN(DECK::string) AS DECK
  ,TO_BOOLEAN(TYPE_FACT::string) AS TYPE_FACT
  ,TO_BOOLEAN(IMPORTED_FROM_LINKED_ESTIM_MODULE::string) AS IMPORTED_FROM_LINKED_ESTIM_MODULE

  /*Date Fields*/
  ,TO_TIMESTAMP_NTZ(CREATEDDATE::string) AS CREATED_DATE
  ,TO_TIMESTAMP_NTZ(MODIFIEDDATE::string) AS MODIFIED_DATE
  ,TO_TIMESTAMP_NTZ(IPAAS_UPDATED_DATE::string) AS IPAAS_UPDATED_DATE

from raw_qc_quotation_product QQP
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM
  ON UPPER(QQP.CURRENCY_COD) = UPPER(RDM.BUSINESS_APPLICATION_VALUE) 
    AND UPPER(RDM.BUSINESS_APPLICATION_DOMAIN_CODE) = 'CURRENCY' 
    AND UPPER(RDM.STANDARD_DOMAIN_APPLICATION_CODE) = 'CURRENCY' 
    AND UPPER(RDM.BUSINESS_APPLICATION_CODE) = 'SPM'