{{
  config(
    materialized = "view",
    alias = "projet_g",
    schema='spm_ca'
  )
}}

WITH RAW_NORM_PROJET_G AS (
  SELECT * FROM {{ref('prep_projet_g')}}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY PROJET_G_UUID 
  ORDER BY IFNULL(TO_TIMESTAMP_NTZ(MODIFIED_DATE::string),'0000-01-01'::DATE) DESC) = 1 
  AND UPPER(TRIM(SRC_SYSTEM_OPERATION)) <> 'DELETE'
)

SELECT 
NO_PROJET::string AS NO_PROJET
,UPPER(ENTITY_CODE::string) AS ENTITY_CODE
,UPPER(NOM_PROJET_L::string) AS NOM_PROJET_L
,UPPER(NOM_PROJET_C::string) AS NOM_PROJET_C
,UPPER(TRIM(CUST_NO::string)) AS CUST_NO
,UPPER(TRIM(NO_ESTIME::string)) AS NO_ESTIME
,NULLIF(NO_PROJ_CLI::string,'') AS NO_PROJ_CLI
,INITCAP(NULLIF(NOM_CONTACT::string,'')) AS NOM_CONTACT
,NULLIF(NO_BON_ACHAT::string,'') AS NO_BON_ACHAT
,UPPER(NULLIF(NO_CONTRAT_V::string,'')) AS NO_CONTRAT_V
,TO_BOOLEAN(TYPE_PROJET::string) AS TYPE_PROJET
,TO_BOOLEAN(DOUANE_PROJ::string) AS DOUANE_PROJ
,TO_BOOLEAN(STATUT_PROJ::string) AS STATUT_PROJ
,UPPER(TERR_CODE::string) AS TERR_CODE
,NULLIF(PST_LICENSE::string,'') AS PST_LICENSE
-- always empty
--,NULLIF(FST_LICENSE::string,'') AS FST_LICENSE
,NULLIF(ADRESSE_LIV_1::string,'') AS ADRESSE_LIV_1
,NULLIF(ADRESSE_LIV_2::string,'') AS ADRESSE_LIV_2
,NULLIF(ADRESSE_LIV_3::string,'') AS ADRESSE_LIV_3
-- always empty
--,DETAILS_LIV_1::string AS DETAILS_LIV_1
-- always empty
--,DETAILS_LIV_2::string AS DETAILS_LIV_2
-- always empty
--,DETAILS_LIV_3::string AS DETAILS_LIV_3
,FOB_CODE::string AS FOB_CODE
,UPPER(NULLIF(LIEU_FAB::string,'')) AS LIEU_FAB
,UPPER(SLSMN_CODE::string) AS SLSMN_CODE
,NBR_PLANCHER::INTEGER AS NBR_PLANCHER
-- always 0
--,RESP_ORDON::INTEGER AS RESP_ORDON
-- always 0
--,SEQ_FACTURE::INTEGER AS SEQ_FACTURE
,CASE WHEN ARRAY_SIZE(ARRAY_REMOVE(SPLIT(LOWER(ORD_PROD::string),','),'none'::VARIANT)) > 0 
THEN ARRAY_REMOVE(SPLIT(LOWER(ORD_PROD::string),','),'none'::VARIANT) ELSE NULL END AS ORD_PROD
-- always 0
--,HOLD_RATE::DOUBLE AS HOLD_RATE
,WASTE_STR_1::DOUBLE AS WASTE_STR_1
,WASTE_STR_2::DOUBLE AS WASTE_STR_2
-- always 0
--,NBR_DESIGN::INTEGER AS NBR_DESIGN
-- always 0
--,NBR_FAMIL::INTEGER AS NBR_FAMIL
-- always 0
--,NO_CATG::INTEGER AS NO_CATG
,TERM_CODE::string AS TERM_CODE
,INITCAP(CITY_TO::string) AS CITY_TO
,AREA_TO::INTEGER AS AREA_TO
,NULLIF(LOWER(MANAGER::string),'none') AS MANAGER
-- always 1
--,POS_TAG::INTEGER AS POS_TAG
,TO_BOOLEAN(SEQUENCING::string) AS SEQUENCING
,UPPER(NULLIF(JOB_NO::string,'')) AS JOB_NO
,NB_SHIP_1::INTEGER AS NB_SHIP_1
-- always 0
--,NB_SHIP_2::INTEGER AS NB_SHIP_2
,NB_ESCORT::INTEGER AS NB_ESCORT
,LONGEST::DOUBLE AS LONGEST
,NULLIF(JOB_SITE_1::string,'') AS JOB_SITE_1
-- always empty
--,JOB_SITE_2::string AS JOB_SITE_2
,NULLIF(JOB_SITE_3::string,'') AS JOB_SITE_3
,TO_BOOLEAN(FOLLOW_MARK::string) AS FOLLOW_MARK
,TO_BOOLEAN(TRANS_MARK::string) AS TRANS_MARK
-- always empty
--,ENTITY_STE::string AS ENTITY_STE
,NULLIF(NO_ESTIME_ESF::string,'') AS NO_ESTIME_ESF
,MARK_TYPE::INTEGER AS MARK_TYPE
-- always False
--,TO_BOOLEAN(PDM_FILE::string) AS PDM_FILE
,TO_BOOLEAN(FOLLOW_DIV::string) AS FOLLOW_DIV
,LOWER(BOLT_RESP::string) AS BOLT_RESP
,NULLIF(REPLACE(SITE_PHONE::string,'-'),'') AS SITE_PHONE
-- always empty
--,SITE_FAX::string AS SITE_FAX
,UPPER(FORM_ENTITY::string) AS FORM_ENTITY
,PROJ_COORD::string AS PROJ_COORD
-- always empty
--,PAINT_DATE::DATE AS PAINT_DATE
,TO_BOOLEAN(BOLT_INCLUDED::string) AS BOLT_INCLUDED
-- always empty
--,JOIST_PLANT::string AS JOIST_PLANT
,SEQUNC_DATES_1::DATE AS SEQUNC_DATES_1
,SEQUNC_DATES_2::DATE AS SEQUNC_DATES_2
,SEQUNC_DATES_3::DATE AS SEQUNC_DATES_3
,NULLIF(SEQUNC_WEEKS_1::INTEGER, 0) AS SEQUNC_WEEKS_1
,NULLIF(SEQUNC_WEEKS_2::INTEGER, 0) AS SEQUNC_WEEKS_2
,NULLIF(SEQUNC_WEEKS_3::INTEGER, 0) AS SEQUNC_WEEKS_3
,CMG_SOURCE_TEMPLATE::string AS CMG_SOURCE_TEMPLATE
,NULLIF(CMG_ASSOC_PROJ::string,'') AS CMG_ASSOC_PROJ
,TO_BOOLEAN(CMG_TRANSFER::string) AS CMG_TRANSFER
,TIMESTAMPADD(second, CMG_TRANSF_TIME::INTEGER, CMG_TRANSF_DATE::DATE) AS CMG_TRANSF_DATETIME
,CMG_CHECK_AMT::DOUBLE AS CMG_CHECK_AMT
,INITCAP(CMG_CITY::string) AS CMG_CITY
,NULLIF(COUNTY_CODE::string,'') AS COUNTY_CODE
,UPPER(CMG_STATE::string) AS CMG_STATE
,NULLIF(TRIM(UPPER(REGEXP_REPLACE(CMG_ZIP_CODE::string,'[-\\s.*]',''))), '') AS CMG_ZIP_CODE
,UPPER(CMG_COUNTRY::string) AS CMG_COUNTRY
,EXCHGN_RATE::DOUBLE AS EXCHGN_RATE
,TIMESTAMPADD(second, SHIP_TRF_TIME::INTEGER, SHIP_TRF_DATE::DATE) AS SHIP_TRF_DATETIME
,TIMESTAMPADD(second, BUDGET_TRF_TIME::INTEGER, BUDGET_TRF_DATE::DATE) AS BUDGET_TRF_DATETIME
,NULLIF(CMG_CREDIT_COMM::string,'') AS CMG_CREDIT_COMM
-- always blank
--,INVOICE_PRINT_STYLE::string AS INVOICE_PRINT_STYLE
,TO_BOOLEAN(LST_BCKLOG::string) AS LST_BCKLOG
-- always True
--,TO_BOOLEAN(SALES_STAT::string) AS SALES_STAT
-- always False
--,TO_BOOLEAN(QUOTTN_ACCESS::string) AS QUOTTN_ACCESS
,NULLIF(UPPER(TRIM(BRANCH_OFFICE_CODE::string)),'') AS BRANCH_OFFICE_CODE
-- always *
--,MLI::string AS MLI
,TO_BOOLEAN(IS_ABM_PAGE_LINE::string) AS IS_ABM_PAGE_LINE
,TO_BOOLEAN(ABM_FOLLOW_UP::string) AS ABM_FOLLOW_UP
,INITCAP(NULLIF(DRWG_OFFICE_CODE::string,'')) AS DRWG_OFFICE_CODE
,NULLIF(BUYER_CODE::string,'') AS BUYER_CODE
-- always empty
--,KRONOS_TRF_DATE::string AS KRONOS_TRF_DATE
,WASTE_COST_1::DOUBLE AS WASTE_COST_1
,WASTE_COST_2::DOUBLE AS WASTE_COST_2
,NULLIF(UPPER(TRIM(OFFICE_CODE::string)),'') AS OFFICE_CODE
,MAX_DECK_BUNDL_WEIGHT::INTEGER AS MAX_DECK_BUNDL_WEIGHT
,MAX_DECK_BUNDL_PIECES::INTEGER AS MAX_DECK_BUNDL_PIECES
,DECK_BUNDL_PIECES_TOLERANCE::INTEGER AS DECK_BUNDL_PIECES_TOLERANCE
,BUDGET_VALID_DATE::DATE AS BUDGET_VALID_DATE
,CASE WHEN ARRAY_SIZE(ARRAY_REMOVE(SPLIT(LOWER(CHIEFS_ENGINEER::string),','),''::VARIANT)) > 0 
    THEN ARRAY_REMOVE(SPLIT(LOWER(CHIEFS_ENGINEER::string),','),''::VARIANT) ELSE NULL END AS CHIEFS_ENGINEER
,CASE WHEN ARRAY_SIZE(ARRAY_REMOVE(SPLIT(LOWER(CHIEFS_DETAILER::string),','),''::VARIANT)) > 0 
    THEN ARRAY_REMOVE(SPLIT(LOWER(CHIEFS_DETAILER::string),','),''::VARIANT) ELSE NULL END AS CHIEFS_DETAILER
,CASE WHEN ARRAY_SIZE(ARRAY_REMOVE(SPLIT(LOWER(SHIPPING_COORDINATORS::string),','),''::VARIANT)) > 0 
    THEN ARRAY_REMOVE(SPLIT(LOWER(SHIPPING_COORDINATORS::string),','),''::VARIANT) ELSE NULL END AS SHIPPING_COORDINATORS
,GDM_PROJECT_ID::INTEGER AS GDM_PROJECT_ID
-- always NULL
--,QUOTATION_SENT_DATE::DATE AS QUOTATION_SENT_DATE
,PRICE_EXPIRATION_DATE::DATE AS PRICE_EXPIRATION_DATE
-- always FALSE
--,TO_BOOLEAN(NO_SPLICE_TOP_BOT::string) AS NO_SPLICE_TOP_BOT
-- always NULL
--,DRAWING_DUE_IN::DATE AS DRAWING_DUE_IN
,TO_BOOLEAN(SPECIAL_ELEMENTS::string) AS SPECIAL_ELEMENTS
,NULLIF(SPECIAL_ELEMENTS_COMMENTS::string,'') AS SPECIAL_ELEMENTS_COMMENTS
,PRIORITY_CODE::INTEGER AS PRIORITY_CODE
,ROLLBAR_EXPECTED_BACK_DATE::DATE AS ROLLBAR_EXPECTED_BACK_DATE
,ROLLBAR_ACTUAL_BACK_DATE::DATE AS ROLLBAR_ACTUAL_BACK_DATE
,TO_BOOLEAN(IS_LAYOUT_JOB::string) AS IS_LAYOUT_JOB
,ROLLBAR_FOLLOW_UP_DATE::DATE AS ROLLBAR_FOLLOW_UP_DATE
,NULLIF(CONTACT_EMAIL::string,'') AS CONTACT_EMAIL
,TO_BOOLEAN(LIST_ON_HAMBRO_SCHEDULE::string) AS LIST_ON_HAMBRO_SCHEDULE
,NULLIF(SET_OFF_INFORMATION::string,'') AS SET_OFF_INFORMATION
,CMG_INVOICE_STYLE::string AS CMG_INVOICE_STYLE
,TO_BOOLEAN(PO_NO_TRANS_ORACLE::string) AS PO_NO_TRANS_ORACLE
,NULLIF(WEIGHT_INCREASE_COMMENT::string,'') AS WEIGHT_INCREASE_COMMENT
,NULLIF(LAYOUT_PROCESS_CODE::string,'') AS LAYOUT_PROCESS_CODE
-- always empty
--,SHIPPING_COMMENTS::string AS SHIPPING_COMMENTS
,NULLIF(ROLLBAR_COMMENT::string,'') AS ROLLBAR_COMMENT
,TO_BOOLEAN(ESTIMATION_INCLUDE_DESIGN::string) AS ESTIMATION_INCLUDE_DESIGN
,TO_BOOLEAN(LEED_CERTIFIED::string) AS LEED_CERTIFIED
-- always False
--,TO_BOOLEAN(DSMS_TRANSFER::string) AS DSMS_TRANSFER
,DESIGN_COMPLETED_DATE::DATE AS DESIGN_COMPLETED_DATE
,NULLIF(FINANCIAL_COMMENTS::string,'') AS FINANCIAL_COMMENTS
,PROJECT_STATUS_CODE::INTEGER AS PROJECT_STATUS_CODE
,NULLIF(PROJECT_STATUS_COMMENT::string,'') AS PROJECT_STATUS_COMMENT
,NULLIF(LOWER(PROJECT_STATUS_UPDATED_BY::string),'') AS PROJECT_STATUS_UPDATED_BY
,TO_TIMESTAMP_NTZ(PROJECT_STATUS_UPDATED_DATETIME::string) AS PROJECT_STATUS_UPDATED_DATETIME
,BUSINESS_UNIT_ID::INTEGER AS BUSINESS_UNIT_ID
,TO_BOOLEAN(PREPARATION_FOLLOW_UP::string) AS PREPARATION_FOLLOW_UP
,NULLIF(PREP_FOLLOW_UP_MARKS_FILTER::string,'') AS PREP_FOLLOW_UP_MARKS_FILTER
,INITCAP(TAXATION_ADDRESS::string) AS TAXATION_ADDRESS
,PROJET_G_UUID::string AS PROJET_G_UUID

--RDM fields
,CASE WHEN NULLIF(TRIM(OFFICE_CODE ::STRING),'') IS NULL 
  THEN NULL 
  ELSE IFNULL(RDM_SOD.STANDARD_APPLICATION_VALUE,'Not Found') 
  END                                                                       AS RDM_SALES_OFFICE_DEPARTMENT_CODE

,CASE WHEN NULLIF(TRIM(BRANCH_OFFICE_CODE::STRING),'') IS NULL 
  THEN NULL ELSE IFNULL(RDM_SBOD.STANDARD_APPLICATION_VALUE,'Not Found') 
  END                                                                       AS RDM_SALES_BRANCH_OFFICE_DEPARTMENT_CODE

,CASE WHEN NULLIF(TRIM(CMG_COUNTRY::STRING),'') IS NULL 
  THEN NULL ELSE IFNULL(RDM_C.STANDARD_APPLICATION_VALUE,'Not Found') 
  END                                                                       AS RDM_COUNTRY_CODE

,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
,CASE WHEN NULLIF(TRIM(PG.OFFICE_CODE::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM_SOD.STANDARD_APPLICATION_VALUE_NAME_FR,'Not Found') 
END                                                           AS  RDM_SALES_OFFICE_DEPARTMENT_NAME_FR
,CASE WHEN NULLIF(TRIM(PG.OFFICE_CODE::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM_SOD.STANDARD_APPLICATION_VALUE_NAME_EN ,'Not Found') 
END                                                           AS RDM_SALES_OFFICE_DEPARTMENT_NAME_EN
,CASE WHEN NULLIF(TRIM(PG.BRANCH_OFFICE_CODE::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM_SBOD.STANDARD_APPLICATION_VALUE_NAME_FR,'Not Found') 
END                                                           AS RDM_SALES_BRANCH_OFFICE_DEPARTMENT_NAME_FR
,CASE WHEN NULLIF(TRIM(PG.BRANCH_OFFICE_CODE::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM_SBOD.STANDARD_APPLICATION_VALUE_NAME_EN ,'Not Found') 
END                                                           AS RDM_SALES_BRANCH_OFFICE_DEPARTMENT_NAME_EN
,CASE WHEN NULLIF(TRIM(PG.CMG_COUNTRY::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM_C.STANDARD_APPLICATION_VALUE_NAME_FR,'Not Found') 
END                                                           AS RDM_COUNTRY_NAME_FR
,CASE WHEN NULLIF(TRIM(PG.CMG_COUNTRY::STRING),'')
IS NULL THEN NULL ELSE IFNULL(RDM_C.STANDARD_APPLICATION_VALUE_NAME_EN ,'Not Found') 
END                                                           AS RDM_COUNTRY_NAME_EN
FROM RAW_NORM_PROJET_G PG
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM_SOD
ON UPPER(TRIM(PG.OFFICE_CODE)) = UPPER(TRIM(RDM_SOD.BUSINESS_APPLICATION_VALUE))
AND UPPER(RDM_SOD.BUSINESS_APPLICATION_DOMAIN_CODE) = 'SALESOFFICEDEPARTMENT'
AND UPPER(RDM_SOD.STANDARD_DOMAIN_APPLICATION_CODE) = 'SALESOFFICEDEPARTMENT' 
AND UPPER(RDM_SOD.BUSINESS_APPLICATION_CODE) = 'SPM'
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM_SBOD 
ON UPPER(NULLIF(TRIM(PG.BRANCH_OFFICE_CODE::STRING),'')) = UPPER(RDM_SBOD.BUSINESS_APPLICATION_VALUE)
AND UPPER(RDM_SBOD.BUSINESS_APPLICATION_DOMAIN_CODE) = 'SALESBRANCHOFFICEDEPARTMENT'
AND UPPER(RDM_SBOD.STANDARD_DOMAIN_APPLICATION_CODE) = 'SALESBRANCHOFFICEDEPARTMENT' 
AND UPPER(RDM_SBOD.BUSINESS_APPLICATION_CODE) = 'SPM'
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM_C 
ON UPPER(NULLIF(TRIM(PG.CMG_COUNTRY::STRING),'')) = UPPER(RDM_C.BUSINESS_APPLICATION_VALUE)
AND UPPER(RDM_C.BUSINESS_APPLICATION_DOMAIN_CODE) = 'COUNTRY'
AND UPPER(RDM_C.STANDARD_DOMAIN_APPLICATION_CODE) = 'COUNTRY' 
AND UPPER(RDM_C.BUSINESS_APPLICATION_CODE) = 'SPM'
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'