{{
  config(
    materialized = "view",
    alias = "project_event_detail",
    schema='spm_ca'
  )
}}
  SELECT
    PROJECT_EVENT_DETAIL_UUID::string AS PROJECT_EVENT_DETAIL_UUID
    ,PROJECT_EVENT_UUID::string AS PROJECT_EVENT_UUID
    ,EVENT_UUID::string AS EVENT_UUID
    ,COST::DOUBLE AS COST
    ,PROVISION_AMOUNT::DOUBLE AS PROVISION_AMOUNT
    ,CREDIT_PAYMENT_AMOUNT::DOUBLE AS CREDIT_PAYMENT_AMOUNT
    ,UPPER(NULLIF(ENTITY_CODE, ''))::string AS ENTITY_CODE
    ,TO_TIMESTAMP_NTZ(NULLIF(CREATION_DATETIME, '')::string) AS CREATION_DATETIME
    --100% NULL
    --,TO_TIMESTAMP_NTZ(NULLIF(VALIDATED_DATETIME, '')::string) AS VALIDATED_DATETIME
    --100% 0
    --,NULLIF(VALIDATED_BY_PEOPLE_ID, '')::INTEGER AS VALIDATED_BY_PEOPLE_ID
    ,TO_TIMESTAMP_NTZ(NULLIF(CANCELLATION_DATETIME, '')::string) AS CANCELLATION_DATETIME
    ,NULLIF(CANCELLATION_COMMENT, '')::string AS CANCELLATION_COMMENT
    ,NULLIF(CANCELED_BY_PEOPLE_ID, '')::INTEGER AS CANCELED_BY_PEOPLE_ID
    ,NULLIF(LAST_UPDATE_ACTION, '')::string AS LAST_UPDATE_ACTION
    --100% NULL (ou '')
    --,NULLIF(PROJECT_EVENT_QUICK_REMARK_UUID, '')::string AS PROJECT_EVENT_QUICK_REMARK_UUID
    ,NULLIF(PROJECT_EVENT_MANUAL_REMARK, '')::string AS PROJECT_EVENT_MANUAL_REMARK
    --,ROW_ID::string AS ROW_ID
    --,src_system_operation::string AS SRC_SYSTEM_OPERATION
    --,IPAAS_UPDATED_DATE::string AS IPAAS_UPDATED_DATE
    ,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
    ,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
    ,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
  from {{ref('prep_project_event_detail')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'