
{{
 config(
 materialized = "view",
 alias = "item_alt_po",
 schema='spm_ca'
 )
}}

SELECT
 UPPER(IN_ENTITY::string) AS IN_ENTITY
,UPPER(NO_PROJET_FR::string) AS NO_PROJET_FR
,LINE_NO::INTEGER AS LINE_NO
,UPPER(ITEM_NO::string) AS ITEM_NO
,MESURE_ALT::INTEGER AS MESURE_ALT
,UPPER(UDM_ALT::string) AS UDM_ALT
,UPPER(WHS_CODE::string) AS WHS_CODE
,UPPER(NO_PROJET_TO::string) AS NO_PROJET_TO
,TYPE_REF::INTEGER AS TYPE_REF
,UPPER(REFERENCE::string) AS REFERENCE
,FATHR_NO::INTEGER AS FATHR_NO
,DATE(TO_TIMESTAMP_NTZ(REGEXP_REPLACE(UPD_DATE::string,'^(\\d{4})(\\d{2})(\\d{2}) (\\d{2})(\\d{2})(\\d{2}\\.\\d{3})$','\\1-\\2-\\3 \\4:\\5:\\6'))) AS UPD_DATE
,UPD_TIME::INTEGER AS UPD_TIME
,USER::string AS USER
,UPPER(MLI::string) AS MLI
,SEQ_NO_LIST::string AS SEQ_NO_LIST
--ALWAYS 0
--,SEQ_NO::INTEGER AS SEQ_NO
,MESURE1::INTEGER AS MESURE_1
,MESURE2::INTEGER AS MESURE_2
-- ALWAYS NULL
--,DETAIL::string AS DETAIL
--ALWAYS NULL
--,OPER_CODE::string AS OPER_CODE
,ITEM_ALT_ID::INTEGER AS ITEM_ALT_ID
,TO_BOOLEAN(ABM_STATUS::INTEGER) AS ABM_STATUS
,UPPER(HEAT_NO::string) AS HEAT_NO
,UPPER(PLATE_NO::string) AS PLATE_NO
,UPPER(PIECE_ID::string) AS PIECE_ID
,MATERIAL_REFERENCE_LIST::string AS MATERIAL_REFERENCE_LIST
--ALWAYS NULL
--,COMMENTSTATUS::string AS COMMENT_STATUS
--ALWAYS NULL
--,COMMENTSOLUTION::string AS COMMENT_SOLUTION
--ALWAYS NULL
--,COMMENTPURCHASE::string AS COMMENT_PURCHASE
FROM {{ref('prep_item_alt_po')}} 