{{
  config(
    materialized = "view",
    alias = "cmg_outbound_databases",
    schema='spm_ca',
    meta = {
        'table_key': 'DATABASE_NAME',
        'tests': {
            'null_values':{
                'columns':[
                    'RDM_FINANCIAL_COMPANY_CODE',
                    'RDM_CURRENCY_CODE'
                ]
            }
        }    
    }
  )
}}


WITH raw_cmg_outbound_databases as
(
select * from {{ref('prep_cmg_outbound_databases')}}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1
)

SELECT
   NULLIF(TRIM(COD.DATABASE_NAME::string), '') AS DATABASE_NAME
  ,NULLIF(TRIM(COD.DATABASE_DESCRIPTION::string), '') AS DATABASE_DESCRIPTION
  ,NULLIF(TRIM(COD.LOCAL_OUTPUT_PATH::string), '') AS LOCAL_OUTPUT_PATH
  ,NULLIF(TRIM(COD.HOST_NAME::string), '') AS HOST_NAME
  ,NULLIF(TRIM(COD.HOST_DESTINATION_PATH::string), '') AS HOST_DESTINATION_PATH
  ,NULLIF(TRIM(COD.HOST_USER_NAME::string), '') AS HOST_USER_NAME
  ,NULLIF(TRIM(COD.HOST_PASSWORD::string), '') AS HOST_PASSWORD
  ,NULLIF(TRIM(COD.SET_OF_BOOKS::string), '') AS SET_OF_BOOKS
  ,NULLIF(TRIM(COD.PROJECT_PREFIX::string), '') AS PROJECT_PREFIX
  ,NULLIF(TRIM(COD.ADMINISTRATOR_EMAIL::string), '') AS ADMINISTRATOR_EMAIL
  ,NULLIF(TRIM(COD.LOCAL_CURRENCY::string), '') AS LOCAL_CURRENCY
  ,NULLIF(TRIM(COD.DESGO_EMAIL::string), '') AS DESGO_EMAIL
  ,NULLIF(TRIM(COD.AR_ENTITY::string), '') AS AR_ENTITY
  ,NULLIF(TRIM(COD.MANUFACTURING_HELPDESK_EMAIL::string), '') AS MANUFACTURING_HELPDESK_EMAIL
  ,NULLIF(TRIM(COD.FINAPPS_HELPDESK_EMAIL::string), '') AS FINAPPS_HELPDESK_EMAIL
  ,NULLIF(TRIM(COD.CUSTOMER_CREDIT_MANAGEMENT_EMAIL::string), '') AS CUSTOMER_CREDIT_MANAGEMENT_EMAIL

  -- RDM Data for Financial Company
  ,IFNULL(RDM_FIN.STANDARD_APPLICATION_VALUE, 'Not Found') AS RDM_FINANCIAL_COMPANY_CODE
      
  -- RDM Data for Currency
  ,IFNULL(RDM_CUR.STANDARD_APPLICATION_VALUE, 'Not Found') AS RDM_CURRENCY_CODE

  ,NULLIF(TRIM(COD.CREATEDBY::string), '') AS CREATEDBY
  ,TO_TIMESTAMP_NTZ(COD.CREATEDDATE::string) AS CREATED_DATE
  ,TO_TIMESTAMP_NTZ(COD.MODIFIEDDATE::string) AS MODIFIED_DATE
  ,NULLIF(TRIM(COD.MODIFIEDBY::string), '') AS MODIFIEDBY
  ,IFNULL(RDM_FIN.STANDARD_APPLICATION_VALUE_NAME_FR, 'Not Found') AS RDM_FINANCIAL_COMPANY_NAME_FR
  ,IFNULL(RDM_FIN.STANDARD_APPLICATION_VALUE_NAME_EN, 'Not Found') AS RDM_FINANCIAL_COMPANY_NAME_EN

FROM 
    raw_cmg_outbound_databases COD
      
-- Join for RDM_FINANCIAL_COMPANY_CODE
LEFT JOIN 
    {{ref('gov_referencedata_rdm')}} RDM_FIN
    ON UPPER(COD.PROJECT_PREFIX) = UPPER(RDM_FIN.BUSINESS_APPLICATION_VALUE)
    AND UPPER(RDM_FIN.BUSINESS_APPLICATION_DOMAIN_CODE) = 'FINANCIALCOMPANY'
    AND UPPER(RDM_FIN.BUSINESS_APPLICATION_CODE) = 'SPM'

-- Join for RDM_CURRENCY_CODE
LEFT JOIN 
    {{ref('gov_referencedata_rdm')}} RDM_CUR
    ON UPPER(COD.LOCAL_CURRENCY) = UPPER(RDM_CUR.BUSINESS_APPLICATION_VALUE)
    AND UPPER(RDM_CUR.BUSINESS_APPLICATION_DOMAIN_CODE) = 'CURRENCY'
    AND UPPER(RDM_CUR.BUSINESS_APPLICATION_CODE) = 'SPM'