{{
 config(
 materialized = "view",
 alias = "item_alt",
 schema='spm_ca'
 )
}}

SELECT
 UPPER(IN_ENTITY::string) AS IN_ENTITY
,UPPER(WHS_CODE::string) AS WHS_CODE
,UPPER(ITEM_NO::string) AS ITEM_NO
,MESURE_ALT::INTEGER AS MESURE_ALT
,UPPER(UDM_ALT::string) AS UDM_ALT
,NO_RESER::INTEGER AS NO_RESER
--100 % NULL
--,PROD_DATE::DATE AS PROD_DATE
,UPPER(MLI::string) AS MLI
,UPPER(HEAT_NO::string) AS HEAT_NO
,UPPER(BIN_LOCATION::string) AS BIN_LOCATION
,UPPER(TYPE_REF::INTEGER) AS TYPE_REF
,REFERENCE::string AS REFERENCE
,UPPER(NO_PROJET_TO::string) AS NO_PROJET_TO
,LINE_NO::INTEGER AS LINE_NO
,USER::string AS USER
,FATHR_NO::INTEGER AS FATHR_NO
,SEQ_NO_LIST::string AS SEQ_NO_LIST
--ALWAYS 0
--,SEQ_NO::INTEGER AS SEQ_NO
--ALWAYS 0
--,WORK_ORDER::INTEGER AS WORK_ORDER
,MESURE1::INTEGER AS MESURE1
,MESURE2::INTEGER AS MESURE2
,UPPER(DETAIL::string) AS DETAIL
--ALWAYS NULL
--,OPER_CODE::string AS OPER_CODE
,ITEM_ALT_ID::INTEGER AS ITEM_ALT_ID
,TO_BOOLEAN(ABM_STATUS::INTEGER) AS ABM_STATUS
--ALWAYS NULL
--,DROP_PROJECT::string AS DROP_PROJECT
--ALWAYS NULL
--,DROP_DIVISION::string AS DROP_DIVISION
--ALAYS NULL
--,PLATE_NO::string AS PLATE_NO
,UPPER(PO_NO::string) AS PO_NO
,PO_LINE_NO::INTEGER AS PO_LINE_NO
,PARENT_ID::INTEGER AS PARENT_ID
--ALWAYS NULL
--,SKETCH::string AS SKETCH
--ALWAYS NULL
--,PIECE_ID::string AS PIECE_ID
--ALWAYS NULL
--,PROCSS_VENDOR_CODE::string AS PROCSS_VENDOR_CODE
--ALWAYS NULL
--,PROCSS_SEND_DATE::DATE AS PROCSS_SEND_DATE
--ALWAYS NULL
--,PROCSS_BACK_DATE::DATE AS PROCSS_BACK_DATE
--ALWAYS NULL
--,TRANSF_DATE::DATE AS TRANSF_DATE
,TO_BOOLEAN(CHARPY_TEST::string) AS CHARPY_TEST
--ALWAYS NULL
--,MATERIAL_REFERENCE_LIST::string AS MATERIAL_REFERENCE_LIST
--ALWAYS 0
--,COST::DOUBLE AS COST
,TO_TIMESTAMP_NTZ(REGEXP_REPLACE(GANTRYREQUESTEDDATETIME::string,'^(\\d{4})(\\d{2})(\\d{2}) (\\d{2})(\\d{2})(\\d{2}\\.\\d{3})$','\\1-\\2-\\3 \\4:\\5:\\6')) AS GANTRY_REQUESTED_DATETIME
,TO_TIMESTAMP_NTZ(REGEXP_REPLACE(GANTRYCONFIRMEDDATETIME::string,'^(\\d{4})(\\d{2})(\\d{2}) (\\d{2})(\\d{2})(\\d{2}\\.\\d{3})$','\\1-\\2-\\3 \\4:\\5:\\6')) AS GANTRY_CONFIRMED_DATETIME
--ALWAYS NULL
--,COMMENTPURCHASE::string AS COMMENTPURCHASE
--ALWAYS NULL
--,COMMENTSTATUS::string AS COMMENTSTATUS
--ALAYS NULL
--,COMMENTSOLUTION::string AS COMMENTSOLUTION
,UPPER(BACKGROUNDHEXADECIMALCOLOR::string) AS BACKGROUNDHEXADECIMALCOLOR
FROM {{ref('prep_item_alt')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ITEM_ALT_ID ORDER BY IFNULL(TO_TIMESTAMP_NTZ(IPAAS_UPDATED_DATE::string),'0000-01-01'::DATE) DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION)) <> 'DELETE'