{{
  config(
    materialized = "view",
    alias = "ess_trans",
    schema='spm_ca'
  )
}}
SELECT 
  UPPER(ENTITY_CODE::string) AS ENTITY_CODE
,LINE_NO::INTEGER AS LINE_NO
,UPPER(NO_PROJET::string) AS NO_PROJET
,TRANS_CODE::INTEGER AS TRANS_CODE
,REFERENCE::INTEGER AS REFERENCE
,TRANS_DATE::DATE AS TRANS_DATE
,QUANTITY::DOUBLE AS QUANTITY
-- always 0
--,TRANS_AMT::DOUBLE AS TRANS_AMT
,MNT_REVENU::DOUBLE AS MNT_REVENU
,MNT_DEPENSE::DOUBLE AS MNT_DEPENSE
-- always 0
--,POURCENTAGE::DOUBLE AS POURCENTAGE
,NULLIF(REF_CODE::string,'') AS REF_CODE
,PRD::INTEGER AS PRD
-- always 0
--,NO_CATG::INTEGER AS NO_CATG
,YR::INTEGER AS YR
,EXP_MARG::DOUBLE AS EXP_MARG
-- always 0
--,QTY_MARG::DOUBLE AS QTY_MARG
-- always blank
--,STATUS_LINE::string AS STATUS_LINE
-- always A
--,CALCLT_MODE::string AS CALCLT_MODE
-- always blank
--,VENDOR_CODE::string AS VENDOR_CODE
-- always blank
--,PO_NO::string AS PO_NO
-- always blank
--,CONTRACT_NO::string AS CONTRACT_NO
-- always blank
--,OFFICE_CODE::string AS OFFICE_CODE
-- always blank
--,BRANCH_OFFICE_CODE::string AS BRANCH_OFFICE_CODE
,WEIGHT::DOUBLE AS WEIGHT
,AREA::DOUBLE AS AREA
,VENDOR_ID::INTEGER AS VENDOR_ID
,CASE WHEN LENGTH(VENDOR_NAME::string) > 2 THEN UPPER(VENDOR_NAME::string) ELSE NULL END AS VENDOR_NAME
,ESS_TRANS_UUID::string AS ESS_TRANS_UUID
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
  from {{ref('prep_ess_trans')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'
