{{
  config(
    materialized = "view",
    alias = "projet_e",
    schema='spm_ca'
  )
}}

SELECT 
UPPER(NO_PROJET::string) AS NO_PROJET
,D_ESTIME::DATE AS D_ESTIME
,D_OUVERTURE::DATE AS D_OUVERTURE
,D_LIVRAISON::DATE AS D_LIVRAISON
,D_APP_CREDIT::DATE AS D_APP_CREDIT
--100% null
--,D_D_DESIGN::DATE AS D_D_DESIGN
--100% null
--,D_F_DESIGN::DATE AS D_F_DESIGN
--100% null
--,D_D_DETAIL::DATE AS D_D_DETAIL
,D_F_DETAIL::DATE AS D_F_DETAIL
,D_D_PROD::DATE AS D_D_PROD
,D_F_PROD::DATE AS D_F_PROD
,D_D_LIVRE::DATE AS D_D_LIVRE
,D_F_LIVRE::DATE AS D_F_LIVRE
,TO_BOOLEAN(DENONCIATION::string) AS DENONCIATION
--100% FALSE
--,TO_BOOLEAN(IMPR_HISTO::string) AS IMPR_HISTO
--100% null
--,TO_TIMESTAMP_NTZ(D_PLANS::string) AS D_PLANS
--100% null
--,TO_TIMESTAMP_NTZ(D_PLANS_SD::string) AS D_PLANS_SD
--100% null
--,TO_TIMESTAMP_NTZ(APPR_CANAM::string) AS APPR_CANAM
--100% null
--,D_APP_CANAM::DATE AS D_APP_CANAM
,D_SAISIE::DATE AS D_SAISIE
,D_CONTRAT::DATE AS D_CONTRAT
,TYPE_APPR::INTEGER AS TYPE_APPR
,NO_APPR_CRE::INTEGER AS NO_APPR_CRE
,UPPER(NULLIF(TRIM(NO_DETAILER::string), '')) AS NO_DETAILER
,TO_BOOLEAN(MESURE::string) AS MESURE
,NULLIF(TRIM(NO_PEINTURE::string), '') AS NO_PEINTURE
--100% FALSE
--,TO_BOOLEAN(ARC_AIR::string) AS ARC_AIR
--100% TRUE
--,TO_BOOLEAN(DESIGN_BRIDG::string) AS DESIGN_BRIDG
--100% TRUE
--,TO_BOOLEAN(SPLICE_TOP::string) AS SPLICE_TOP
--100% TRUE
--,TO_BOOLEAN(SPLICE_BOT::string) AS SPLICE_BOT
,TO_BOOLEAN(IMPR_INGEN::string) AS IMPR_INGEN
,TO_BOOLEAN(MAN_AUTO_CRED::string) AS MAN_AUTO_CRED
,D_INACTIF::DATE AS D_INACTIF
,T_SAISIE::INTEGER AS T_SAISIE
,LOWER(USAGER::string) AS USAGER
--100% null
--,FINISHING_CODE::string AS FINISHING_CODE
--100% null
--,TO_BOOLEAN(SLOPED_SHOES::string) AS SLOPED_SHOES
--100% null
--,TO_BOOLEAN(DEEP_SHOES::string) AS DEEP_SHOES
--100% null
--,TO_BOOLEAN(SPLICES::string) AS SPLICES
--100% null
--,TO_BOOLEAN(SPEC_LOADS::string) AS SPEC_LOADS
--100% null
--,TO_BOOLEAN(SPEC_DEFLECT::string) AS SPEC_DEFLECT
--100% null
--,TO_BOOLEAN(UPLIFT::string) AS UPLIFT
--100% null
--,TO_BOOLEAN(STAND_SEAM::string) AS STAND_SEAM
--100% null
--,TO_BOOLEAN(ENG_SEAL_REQ::string) AS ENG_SEAL_REQ
--100% null
--,TO_BOOLEAN(SPEC_INSPECT::string) AS SPEC_INSPECT
--100% null
--,TO_BOOLEAN(DWG_AVAIL::string) AS DWG_AVAIL
--100% null
--,TO_BOOLEAN(MOMENTS::string) AS MOMENTS
--100% null
--,TO_BOOLEAN(SPEC_CAMBER::string) AS SPEC_CAMBER
--100% null
--,TO_BOOLEAN(CSQE_BB::string) AS CSQE_BB
--100% null
--,TO_BOOLEAN(SPEC_HOLES::string) AS SPEC_HOLES
--100% null
--,TO_BOOLEAN(SPEC_CONN::string) AS SPEC_CONN
--100% null
--,TO_BOOLEAN(SPEC_BRDG::string) AS SPEC_BRDG
--100% null
--,CKLIST::string AS CKLIST
--100% null
--,D_HISTO::string AS D_HISTO
,TO_BOOLEAN(PRODUCTION_DOC_ARCHIVED::string) AS PRODUCTION_DOC_ARCHIVED
,NULLIF(PRODUCTION_DOC_ARCHIVED_BY::string, '') AS PRODUCTION_DOC_ARCHIVED_BY
,PRODUCTION_DOC_ARCHIVED_DATE::DATE AS PRODUCTION_DOC_ARCHIVED_DATE
,UPPER(NO_AGENT_CT::string) AS NO_AGENT_CT
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(CREATED_BY::string, '') AS CREATED_BY
,NULLIF(MODIFIED_BY::string, '') AS MODIFIED_BY
,PROJET_E_UUID::string AS PROJET_E_UUID
from {{ref('prep_projet_e')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'