{{
  config(
    materialized = "view",
    alias = "proj_seq_lp",
    schema='spm_ca'
  )
}}

SELECT 
 ENTITY_CODE
,NO_PROJET
,SEQ_NO
,NO_PRODUIT
,WEIGHT_1
,WEIGHT_2
,WEIGHT_3
,TMPS_1
,TMPS_2
,PCES_1
,PCES_2
,PCES_3
,REQUISITIONS_RECEIVED_DATE
,PRODUCED_AMOUNT
,SHIPPED_AMOUNT
,ESTIMATED_AMOUNT
,PRODUCED_UOM
,SHIPPED_UOM
,ESTIMATED_UOM
,PRINT_INFORMATION_ON_ITEM
,ESTIMATED_PLANT_FABRICATION_TIME
,CREATED_DATE
,MODIFIED_DATE
,CREATED_BY
,MODIFIED_BY
,PROJ_SEQ_LP_UUID
from {{ref('prep_proj_seq_lp')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'