{{
  config(
    materialized = "view",
    alias = "pe_job",
    schema='spm_ca'
  )
}}


SELECT
     UPPER(NULLIF(TRIM(IN_ENTITY::string), '')) AS IN_ENTITY
    ,UPPER(NULLIF(TRIM(WHS_CODE::string), '')) AS WHS_CODE
    ,UPPER(NULLIF(TRIM(NO_JOB::string), '')) AS NO_JOB
    ,UPPER(NULLIF(TRIM(DESC_JOB::string), '')) AS DESC_JOB
    ,TO_TIMESTAMP_NTZ(DATE_OUV::string) AS DATE_OUV
    ,TO_TIMESTAMP_NTZ(DATE_FERM::string) AS DATE_FERM
    ,COUT_JOB::INTEGER AS COUT_JOB
    ,COUT_ESTIM::INTEGER AS COUT_ESTIM
    ,CUMUL_REG::INTEGER AS CUMUL_REG
    ,CUMUL_SUP::INTEGER AS CUMUL_SUP
    ,CUMUL_DBL::string AS CUMUL_DBL
    ,UPPER(NULLIF(TRIM(TYPE::string), '')) AS TYPE
    ,UPPER(NULLIF(TRIM(NO_GL::string), '')) AS NO_GL
    ,STATUT_PROJ::INTEGER AS STATUT_PROJ
    ,IPAAS_UPDATED_DATE::DATE AS IPAAS_UPDATED_DATE
from {{ref('prep_pe_job')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1