{{
  config(
    full_refresh = true,
    materialized="dynamic_table",
    target_lag="24 hour",
    snowflake_warehouse= var('task_warehouse'),
    alias = "completed_quote_list",
    schema= "dataproducts_bronze",
    post_hook = "ALTER DYNAMIC TABLE {{ this }} SET LOG_LEVEL = ERROR"
  
  )
}}

WITH SS_FACT_SALES_QUOTE AS
(
	SELECT DISTINCT
		SALES_QUOTE_SK,
		SALES_QUOTE_INSCRIPTION_DATE_KEY,
		SALES_QUOTE_CLOSING_DATE_KEY,
		SALES_OFFICE_SK,
		SALES_BRANCH_OFFICE_SK,
		FINANCIAL_COMPANY_SK,
		BUSINESS_UNIT_SK
	FROM {{ref('sche_fact_Sales_Quote')}}
), SS_TASK AS
(
	SELECT
		PDP.ID AS PROJECT_DIVISION_PRODUCT_ID,
		PD.ID AS PROJECT_DIVISION_ID,
		P.ID AS PROJECT_ID,
		P.QUOTATION_UUID AS QUOTATION_UUID,
		PTTC.ID AS PROJECT_TYPE_TASK_CODE_ID,
		P.STATUS AS STATUS,
		MAX(T.STATUS_UPDATE_DATE) AS STATUS_UPDATE_DATE,
		MAX(T.REAL_DUE_DATE) AS REAL_DUE_DATE
	FROM {{ref('norm_tasks')}} T
		LEFT JOIN {{ref('norm_project_division_products')}} PDP ON T.PROJECT_DIVISION_PRODUCT_ID = PDP.ID
		LEFT JOIN {{ref('norm_project_divisions')}} PD ON PDP.PROJECT_DIVISION_ID = PD.ID
		LEFT JOIN {{ref('norm_projects')}} P ON PD.PROJECT_ID = P.ID
		LEFT JOIN {{ref('norm_project_type_task_codes')}} PTTC ON T.PROJECT_TYPE_TASK_CODE_ID = PTTC.ID
	WHERE P.STATUS = 3 AND UPPER(PTTC.CODE) = 'CHECK'
	GROUP BY
		PDP.ID,
		PD.ID,
		P.ID,
		P.QUOTATION_UUID,
		PTTC.ID,
		P.STATUS
), SS_TASK_EST_HOURS AS
(
	SELECT
		PDP.ID AS PROJECT_DIVISION_PRODUCT_ID,
		PD.ID AS PROJECT_DIVISION_ID,
		P.ID AS PROJECT_ID,
		P.QUOTATION_UUID AS QUOTATION_UUID,
		SUM(T.ESTIMATED_HOURS) AS SALES_QUOTE_TASK_ESTIMATED_HOURS
	FROM {{ref('norm_tasks')}} T
		LEFT JOIN {{ref('norm_project_division_products')}} PDP ON T.PROJECT_DIVISION_PRODUCT_ID = PDP.ID
		LEFT JOIN {{ref('norm_project_divisions')}} PD ON PDP.PROJECT_DIVISION_ID = PD.ID
		LEFT JOIN {{ref('norm_projects')}} P ON PD.PROJECT_ID = P.ID
	WHERE P.STATUS = 3 
		-- Exclude "Sales Final Review" & "Estimation Trello" from estimated hours
		AND T.PROJECT_TYPE_TASK_CODE_ID NOT IN ('736033bd-6d3c-4f3d-a144-049b36ab3bcc','1a0fbe99-a371-48d8-aa8e-5347710415c5')
	GROUP BY
		PDP.ID,
		PD.ID,
		P.ID,
		P.QUOTATION_UUID
)
SELECT
	DSO.SALES_OFFICE_DEPARTMENT_CODE 				AS SALES_OFFICE_DEPARTMENT_CODE,
	UPPER(TRIM(DSO.SALES_OFFICE_DEPARTMENT_NAME_EN)) 	AS SALES_OFFICE_DEPARTMENT_NAME,
	DSBO.SALES_BRANCH_OFFICE_DEPARTMENT_NAME_EN 	AS SALES_BRANCH_OFFICE_DEPARTMENT_GROUP_NAME,
	DFC.FINANCIAL_COMPANY_CODE 						AS FINANCIAL_COMPANY_CODE,
	DBU.BUSINESS_UNIT_CODE 							AS BUSINESS_UNIT_CODE,
	DBU.BUSINESS_UNIT_NAME_FR 						AS BUSINESS_UNIT_NAME_FR,
	DBU.BUSINESS_UNIT_NAME_EN 						AS BUSINESS_UNIT_NAME_EN,
	DSQ.SALES_QUOTE_CODE 							AS SALES_QUOTE_CODE,
	DSQ.SALES_QUOTE_ALTERNATIVE_CODE				AS SALES_QUOTE_ALTERNATIVE_QUOTE_CODE,
	DD.FULL_DATE 									AS SALES_QUOTE_INSCRIPTION_DATE,
	CAST(QQ.ESTIMATION_TARGET_DATETIME AS DATE) 	AS SALES_QUOTE_TARGET_DATE, 
	U.USER_NAME 							AS SALES_QUOTE_ESTIMATOR_NAME,
	S.SLSMN_NAME 							AS SALES_QUOTE_SALES_MAN_NAME,
	ST.STATUS_UPDATE_DATE 					AS SALES_QUOTE_TASK_CHECK_DATE,
	ST.REAL_DUE_DATE						AS SALES_QUOTE_TASK_DUE_DATE,
	STH.SALES_QUOTE_TASK_ESTIMATED_HOURS 	AS SALES_QUOTE_TASK_ESTIMATED_HOURS
FROM SS_FACT_SALES_QUOTE SFSQ
	LEFT JOIN {{ref('sche_dim_Sales_Quote')}} DSQ ON SFSQ.SALES_QUOTE_SK = DSQ.SALES_QUOTE_SK
	LEFT JOIN {{ref('sche_dim_Date')}} DD ON SFSQ.SALES_QUOTE_INSCRIPTION_DATE_KEY = DD.DATE_KEY
	LEFT JOIN {{ref('sche_dim_Sales_Office')}} DSO ON SFSQ.SALES_OFFICE_SK = DSO.SALES_OFFICE_SK
	LEFT JOIN {{ref('sche_dim_Sales_Branch_Office')}} DSBO ON SFSQ.SALES_BRANCH_OFFICE_SK = DSBO.SALES_BRANCH_OFFICE_SK
	LEFT JOIN {{ref('sche_dim_Financial_Company')}} DFC ON SFSQ.FINANCIAL_COMPANY_SK = DFC.FINANCIAL_COMPANY_SK
	LEFT JOIN {{ref('sche_dim_Business_Unit')}} DBU ON SFSQ.BUSINESS_UNIT_SK = DBU.BUSINESS_UNIT_SK
	-- JOIN WITH CTM "CHECK" TASK
	LEFT JOIN {{ref('norm_qc_quotation')}} QQ ON DSQ.SALES_QUOTE_CODE = QQ.MASTER_JOB_NO
		AND DSQ.SALES_QUOTE_ALTERNATIVE_CODE = QQ.JOB_NO AND DSQ.SRC_OFFICE_CODE = QQ.OFFICE_CODE AND UPPER(DSQ.ORIGIN_APPLICATION_CODE) = 'SPM'
	LEFT JOIN SS_TASK ST ON QQ.QUOTATION_UUID = ST.QUOTATION_UUID
	LEFT JOIN SS_TASK_EST_HOURS STH ON QQ.QUOTATION_UUID = STH.QUOTATION_UUID
	-- ESTIMATOR DIMENSION
	LEFT JOIN {{ref('norm_qc_people')}} QP_ESTIMATOR ON QQ.ESTIMT_INIT_CODE = QP_ESTIMATOR.INIT_CODE 
		AND QQ.DSG_ENTITY_CODE = QP_ESTIMATOR.DSG_ENTITY_CODE AND QP_ESTIMATOR.ESTIMT = TRUE
	LEFT JOIN {{ref('norm_users')}} U	ON QP_ESTIMATOR.USER_CODE = U.USER_CODE
	-- SALES MAN DIMENSION
	LEFT JOIN {{ref('norm_qc_people')}} QP_SALESREP ON QQ.SALESM_INIT_CODE = QP_SALESREP.INIT_CODE 
		AND QQ.DSG_ENTITY_CODE = QP_SALESREP.DSG_ENTITY_CODE AND QP_SALESREP.SALESM = TRUE
	LEFT JOIN {{ref('norm_salesman')}} S ON QP_SALESREP.SPM_SALESM_CODE = S.SLSMN_CODE
	WHERE ST.STATUS = 3