trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - "*"

variables:
- name: python_version
  value: '3.10'
- name: REGISTRY_URL_TEST
  value: 'northamerica-northeast1-docker.pkg.dev'
- name: IMAGE_PATH_TEST
  value: 'electric-tesla-507710-k2/airflow/custom-airflow'

stages:
- stage: unit_tests
  displayName: 'PR Unit Tests'
  jobs:
  - job: manual_container_test
    displayName: 'Run Tests in Docker'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    # 1. Download the GCP Key for Login
    - task: DownloadSecureFile@1
      name: test_key
      inputs:
        secureFile: 'practice-gcp-service-account.json'

    # 2. Authenticate and Pull the image    
    - script: |
        cat $(test_key.secureFilePath) | docker login -u _json_key --password-stdin https://$(REGISTRY_URL_TEST)
        docker pull $(REGISTRY_URL_TEST)/$(IMAGE_PATH_TEST):latest
      displayName: 'Docker Login and Pull'

    # 3. Run the container with your PR code mounted
    - script: |
        docker run --rm \
          -v $(Build.SourcesDirectory)/airflow-practice:/workspace \
          -w /workspace \
          -e PYTHONPATH=/workspace:/workspace/plugins \
          -e PYTEST_ADDOPTS="-p no:cacheprovider" \
          $(REGISTRY_URL_TEST)/$(IMAGE_PATH_TEST):latest \
          bash -c "pip install -r requirements.txt -q && pytest Tests/ -v"
      displayName: 'Run Pytest inside pulled image'

  # --- TEST STAGE ---
- stage: deploy_test
  displayName: 'Copy Airflow DAGS to Test Environment'
  dependsOn: unit_tests
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: copy_files
    displayName: 'Copy Files to Test Bucket'
    environment: 'TEST - Airflow DAGS'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            fetchDepth: 0

############ 1. Detect changed files ############  for  controlled deployment   ##############################
          - script: |
              echo "Changed files:"
              git diff --name-status HEAD~1 HEAD

              echo ""
              echo "Changed DAGS:"
              git diff --name-only HEAD~1 HEAD | grep '^airflow-practice/DAGS/' || true

              echo ""
              echo "Changed DAG relative paths:"
              git diff --name-only HEAD~1 HEAD \
                | grep '^airflow-practice/DAGS/' \
                | sed 's#^airflow-practice/DAGS/##' || true

              echo ""
              echo "Changed plugins:"
              git diff --name-only HEAD~1 HEAD | grep '^airflow-practice/plugins/' || true

              echo ""
              echo "Other changed files:"
              git diff --name-only HEAD~1 HEAD | grep -vE '^airflow-practice/(DAGS|plugins)/' || true

            displayName: 'Detect and Classify Changed Files'
############################################################################################################

          - task: DownloadSecureFile@1
            name: google_application_credentials
            inputs:
              secureFile: 'practice-gcp-service-account.json'
            displayName: 'Download GCP Json Key'

          - script: |
              chmod 600 $(google_application_credentials.secureFilePath)
              echo "##vso[task.setvariable variable=GOOGLE_APPLICATION_CREDENTIALS]$(google_application_credentials.secureFilePath)"
            displayName: 'Set Secret Variables'

          - script: |
              echo "Installing Google Cloud SDK..."
              curl -sSL https://sdk.cloud.google.com | bash
              gcloud auth activate-service-account --key-file=$(google_application_credentials.secureFilePath)
            displayName: 'Install gcloud SDK and authenticate'

          - script: |
              echo "Processing changed DAG files..."

              git diff --name-status HEAD~1 HEAD \
                | grep '^D\|^A\|^M' \
                | grep 'airflow-practice/DAGS/' \
                | while read -r status file
              do
                relative_path="${file#airflow-practice/DAGS/}"

                echo "Status: $status"
                echo "DAG: $relative_path"

                if [ "$status" = "D" ]; then
                  echo "Deleting from GCS: $relative_path"

                  gcloud storage rm \
                    "gs://advworks-airflow-test/dags/$relative_path"

                elif [ "$status" = "A" ] || [ "$status" = "M" ]; then
                  echo "Copying to GCS: $relative_path"

                  gcloud storage cp \
                    "$(Build.SourcesDirectory)/airflow-practice/DAGS/$relative_path" \
                    "gs://advworks-airflow-test/dags/$relative_path"
                fi
              done
            displayName: 'Deploy Changed DAG Files to Google Cloud Storage'

          - script: |
              echo "Processing changed plugin files..."

              git diff --name-status HEAD~1 HEAD \
                | grep '^D\|^A\|^M' \
                | grep 'airflow-practice/plugins/' \
                | while read -r status file
              do
                relative_path="${file#airflow-practice/plugins/}"

                echo "Status: $status"
                echo "Plugin: $relative_path"

                if [ "$status" = "D" ]; then
                  echo "Deleting from GCS: $relative_path"

                  gcloud storage rm \
                    "gs://advworks-airflow-test/plugins/$relative_path"

                elif [ "$status" = "A" ] || [ "$status" = "M" ]; then
                  echo "Copying to GCS: $relative_path"

                  gcloud storage cp \
                    "$(Build.SourcesDirectory)/airflow-practice/plugins/$relative_path" \
                    "gs://advworks-airflow-test/plugins/$relative_path"
                fi
              done
            displayName: 'Deploy Changed Plugin Files to Google Cloud Storage'

  # --- PRODUCTION STAGE ---
- stage: deploy_prod
  displayName: 'Copy Airflow DAGS to PROD Environment'
  dependsOn: deploy_test
  # Only run if we are on the main branch and the test stage succeeded
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: sync_to_prod
    displayName: 'Full Sync to Prod'
    environment: 'PROD - Airflow DAGS'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            fetchDepth: 0

############ 1. Detect changed files ############  for  controlled deployment   ##############################
          - script: |
              echo "Changed files:"
              git diff --name-status HEAD~1 HEAD

              echo ""
              echo "Changed DAGS:"
              git diff --name-only HEAD~1 HEAD | grep '^airflow-practice/DAGS/' || true

              echo ""
              echo "Changed DAG relative paths:"
              git diff --name-only HEAD~1 HEAD \
                | grep '^airflow-practice/DAGS/' \
                | sed 's#^airflow-practice/DAGS/##' || true

              echo ""
              echo "Changed plugins:"
              git diff --name-only HEAD~1 HEAD | grep '^airflow-practice/plugins/' || true

              echo ""
              echo "Other changed files:"
              git diff --name-only HEAD~1 HEAD | grep -vE '^airflow-practice/(DAGS|plugins)/' || true

            displayName: 'Detect and Classify Changed Files'
############################################################################################################          

          - task: DownloadSecureFile@1
            name: google_application_credentials
            inputs:
              secureFile: 'practice-gcp-service-account.json'
            displayName: 'Download GCP Json Key'

          - script: |
              gcloud auth activate-service-account --key-file=$(google_application_credentials.secureFilePath)
            displayName: 'Authenticate with GCP'

          - script: |
              echo "Processing changed DAG files..."

              git diff --name-status HEAD~1 HEAD \
                | grep '^D\|^A\|^M' \
                | grep 'airflow-practice/DAGS/' \
                | while read -r status file
              do
                relative_path="${file#airflow-practice/DAGS/}"

                echo "Status: $status"
                echo "DAG: $relative_path"

                if [ "$status" = "D" ]; then
                  echo "Deleting from PROD GCS: $relative_path"

                  gcloud storage rm \
                    "gs://advworks-airflow-prod/dags/$relative_path"

                elif [ "$status" = "A" ] || [ "$status" = "M" ]; then
                  echo "Copying to PROD GCS: $relative_path"

                  gcloud storage cp \
                    "$(Build.SourcesDirectory)/airflow-practice/DAGS/$relative_path" \
                    "gs://advworks-airflow-prod/dags/$relative_path"
                fi
              done
            displayName: 'Deploy Changed DAG Files to PROD Google Cloud Storage'

          - script: |
              echo "Processing changed plugin files..."

              git diff --name-status HEAD~1 HEAD \
                | grep '^D\|^A\|^M' \
                | grep 'airflow-practice/plugins/' \
                | while read -r status file
              do
                relative_path="${file#airflow-practice/plugins/}"

                echo "Status: $status"
                echo "Plugin: $relative_path"

                if [ "$status" = "D" ]; then
                  echo "Deleting from PROD GCS: $relative_path"

                  gcloud storage rm \
                    "gs://advworks-airflow-prod/plugins/$relative_path"

                elif [ "$status" = "A" ] || [ "$status" = "M" ]; then
                  echo "Copying to PROD GCS: $relative_path"

                  gcloud storage cp \
                    "$(Build.SourcesDirectory)/airflow-practice/plugins/$relative_path" \
                    "gs://advworks-airflow-prod/plugins/$relative_path"
                fi
              done
            displayName: 'Deploy Changed Plugin Files to PROD Google Cloud Storage'