from pathlib import Path
import shutil


def upload_file(
    source_file: Path,
    destination_folder: Path
):
    """
    Simulates uploading a file to cloud storage.

    source_file:
        Local JSON file generated by the extraction process.

    destination_folder:
        Local directory representing our storage bucket.
    """

    destination_folder.mkdir(
        parents=True,
        exist_ok=True
    )

    destination_file = (
        destination_folder / source_file.name
    )

    shutil.copy2(
        source_file,
        destination_file
    )

    return destination_file