trigger:
  - main

variables:
  - group: snowflake-dev-secrets

pool:
  vmImage: 'ubuntu-latest'

stages:

  - stage: Python
    displayName: '1. Python Validation'

    jobs:
      - job: PythonValidation
        displayName: 'Validate Python Code'

        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11'
            displayName: 'Set Python 3.11'

          - script: |
              python --version
              python -m compileall python-ingestion
            displayName: 'Compile Python Code'


  - stage: DBT
    displayName: '2. dbt Validation'

    dependsOn: Python
    condition: succeeded()

    jobs:
      - job: DBTValidation
        displayName: 'Validate dbt Project'

        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11'
            displayName: 'Set Python 3.11'

          - script: |
              python --version
              python -m pip install --upgrade pip
              pip install dbt-core dbt-snowflake
            displayName: 'Install dbt'

          - script: |
              mkdir -p ~/.dbt
              cat > ~/.dbt/profiles.yml <<'EOF'
              advworks_dbt:
                target: dev
                outputs:
                  dev:
                    type: snowflake
                    account: dummy
                    user: dummy
                    password: dummy
                    role: ACCOUNTADMIN
                    database: ADVWORKS_DEV
                    warehouse: ETL_WH_DEV
                    schema: PREPARE
                    threads: 4
              EOF

              cd DBT/advworks_dbt
              dbt parse
            displayName: 'Run dbt Parse'


  - stage: Terraform
    displayName: '3. Terraform Validation'

    dependsOn: DBT
    condition: succeeded()

    jobs:
      - job: TerraformValidation
        displayName: 'Validate Terraform Code'

        steps:
          - checkout: self

          - script: |
              curl -fsSL https://releases.hashicorp.com/terraform/1.15.8/terraform_1.15.8_linux_amd64.zip -o /tmp/terraform.zip
              rm -rf /tmp/terraform-install
              mkdir -p /tmp/terraform-install
              unzip -o /tmp/terraform.zip -d /tmp/terraform-install
              chmod +x /tmp/terraform-install/terraform
              echo "##vso[task.prependpath]/tmp/terraform-install"
              /tmp/terraform-install/terraform version
            displayName: 'Install Terraform'

          - script: |
              cd terraform
              terraform fmt -check -recursive
            displayName: 'Terraform Format Check'

          - script: |
              cd terraform
              terraform init -backend=false
            displayName: 'Terraform Init'

          - script: |
              cd terraform
              terraform validate
            displayName: 'Terraform Validate'

  - stage: GoogleAuth
    displayName: '4. Test Google Cloud WIF'

    dependsOn: Terraform
    condition: succeeded()

    jobs:
      - job: GoogleAuthentication
        displayName: 'Authenticate to Google Cloud'

        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: 'Get Azure DevOps Federated Token'
            inputs:
              azureSubscription: 'google-cloud-wif'
              addSpnToEnvironment: true
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "$idToken" > "$(Pipeline.Workspace)/.workload_identity.jwt"

                python -c "import os,base64,json; t=os.environ['idToken']; p=t.split('.')[1]; p += '='*((4-len(p)%4)%4); c=json.loads(base64.urlsafe_b64decode(p)); print('SUB=' + str(c.get('sub'))); print('AUD=' + str(c.get('aud')))"

                cat > "$(Pipeline.Workspace)/.workload_identity.wlconfig" <<EOF
                {
                  "type": "external_account",
                  "audience": "//iam.googleapis.com/projects/776178390591/locations/global/workloadIdentityPools/azure-devops-pool/providers/azure-devops-provider",
                  "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
                  "token_url": "https://sts.googleapis.com/v1/token",
                  "credential_source": {
                    "file": "$(Pipeline.Workspace)/.workload_identity.jwt"
                  },
                  "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/terraform-ci@electric-tesla-507710-k2.iam.gserviceaccount.com:generateAccessToken"
                }
                EOF

          - task: Bash@3
            displayName: 'Verify Google Cloud Authentication'
            inputs:
              targetType: 'inline'
              script: |
                export GOOGLE_APPLICATION_CREDENTIALS="$(Pipeline.Workspace)/.workload_identity.wlconfig"

                gcloud auth login --cred-file="$GOOGLE_APPLICATION_CREDENTIALS"

                echo "Authenticated Google account:"
                gcloud auth list

                echo "Google project:"
                gcloud config set project electric-tesla-507710-k2

                echo "Testing access to GCS:"
                gcloud storage buckets describe gs://electric-tesla-507710-k2-tfstate

  - stage: TerraformPlanDev
    displayName: '5. Terraform Plan - DEV'
    dependsOn: GoogleAuth
    condition: succeeded()
    jobs:
      - job: TerraformPlan
        displayName: 'Create Terraform Plan for DEV'
        steps:

          - checkout: self

          # Download Snowflake private key
          - task: DownloadSecureFile@1
            name: snowflakeKey
            inputs:
              secureFile: 'snowflake_tf_key.p8'
            displayName: 'Download Snowflake Private Key'

          - script: |
              echo "Secure file path: $(snowflakeKey.secureFilePath)"
              test -f "$(snowflakeKey.secureFilePath)"
              echo "Secure key file exists."
            displayName: 'Verify Snowflake Key File'

          # Install Terraform
          - script: |
              curl -fsSL https://releases.hashicorp.com/terraform/1.15.8/terraform_1.15.8_linux_amd64.zip -o /tmp/terraform.zip
              rm -rf /tmp/terraform-install
              mkdir -p /tmp/terraform-install
              unzip -o /tmp/terraform.zip -d /tmp/terraform-install
              chmod +x /tmp/terraform-install/terraform
              echo "##vso[task.prependpath]/tmp/terraform-install"
              /tmp/terraform-install/terraform version
            displayName: 'Install Terraform'

          # Authenticate to Google Cloud using Azure DevOps WIF
          - task: AzureCLI@2
            displayName: 'Authenticate to Google Cloud using WIF'
            inputs:
              azureSubscription: 'google-cloud-wif'
              addSpnToEnvironment: true
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "$idToken" > "$(Pipeline.Workspace)/.workload_identity.jwt"

                cat > "$(Pipeline.Workspace)/.workload_identity.wlconfig" <<EOF
                {
                  "type": "external_account",
                  "audience": "//iam.googleapis.com/projects/776178390591/locations/global/workloadIdentityPools/azure-devops-pool/providers/azure-devops-provider",
                  "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
                  "token_url": "https://sts.googleapis.com/v1/token",
                  "credential_source": {
                    "file": "$(Pipeline.Workspace)/.workload_identity.jwt"
                  },
                  "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/terraform-ci@electric-tesla-507710-k2.iam.gserviceaccount.com:generateAccessToken"
                }
                EOF

                export GOOGLE_APPLICATION_CREDENTIALS="$(Pipeline.Workspace)/.workload_identity.wlconfig"

                gcloud auth login --cred-file="$GOOGLE_APPLICATION_CREDENTIALS"

                echo "Google authentication successful."

                gcloud auth list

          # Initialize real GCS backend
          - script: |
              export GOOGLE_APPLICATION_CREDENTIALS="$(Pipeline.Workspace)/.workload_identity.wlconfig"
              cd terraform
              terraform init -reconfigure
            displayName: 'Terraform Init - GCS Backend'

          # Terraform plan against DEV
          - script: |
              export GOOGLE_APPLICATION_CREDENTIALS="$(Pipeline.Workspace)/.workload_identity.wlconfig"
              cd terraform
              terraform plan -var-file=environments/dev.tfvars -var="snowflake_private_key_path=$(snowflakeKey.secureFilePath)" -out=tfplan
            displayName: 'Terraform Plan - DEV'
            env:
              TF_VAR_snowflake_private_key_passphrase: $(SNOWFLAKE_PRIVATE_KEY_PASSPHRASE)

  # - stage: TerraformPlanDev
  #   displayName: '5. Terraform Plan - DEV'

  #   dependsOn: GoogleAuth
  #   condition: succeeded()

  #   jobs:
  #     - job: TerraformPlan
  #       displayName: 'Create Terraform Plan for DEV'

  #       steps:
  #         - checkout: self

  #         - task: DownloadSecureFile@1
  #           name: snowflakeKey
  #           inputs:
  #             secureFile: 'snowflake_tf_key.p8'
  #           displayName: 'Download Snowflake Private Key'

  #         - script: |
  #             echo "Secure file path: $(snowflakeKey.secureFilePath)"
  #             test -f "$(snowflakeKey.secureFilePath)"
  #             echo "Secure key file exists."
  #           displayName: 'Verify Snowflake Key File'

  #         - script: |
  #             curl -fsSL https://releases.hashicorp.com/terraform/1.15.8/terraform_1.15.8_linux_amd64.zip -o /tmp/terraform.zip
  #             rm -rf /tmp/terraform-install
  #             mkdir -p /tmp/terraform-install
  #             unzip -o /tmp/terraform.zip -d /tmp/terraform-install
  #             chmod +x /tmp/terraform-install/terraform
  #             echo "##vso[task.prependpath]/tmp/terraform-install"
  #             /tmp/terraform-install/terraform version
  #           displayName: 'Install Terraform'

  #         - script: |
  #             cd terraform
  #             terraform init -backend=false
  #           displayName: 'Terraform Init'

  #         - script: |
  #             cd terraform
  #             terraform plan -var-file=environments/dev.tfvars -var="snowflake_private_key_path=$(snowflakeKey.secureFilePath)" -out=tfplan
  #           displayName: 'Terraform Plan - DEV'
  #           env:
  #             TF_VAR_snowflake_private_key_passphrase: $(SNOWFLAKE_PRIVATE_KEY_PASSPHRASE)

          # - script: |
          #     cd terraform
          #     terraform plan -var-file=environments/dev.tfvars -out=tfplan
          #   displayName: 'Terraform Plan - DEV'
          #   env:
          #     TF_VAR_snowflake_private_key: $(SNOWFLAKE_PRIVATE_KEY)
          #     TF_VAR_snowflake_private_key_passphrase: $(SNOWFLAKE_PRIVATE_KEY_PASSPHRASE)