{{
  config(
    materialized = "view",
    alias = "projet_g",
    schema='spm_ca'
  )
}}

SELECT
    DATA:"no_projet" AS NO_PROJET,
    DATA:"entity_code" AS ENTITY_CODE,
    DATA:"nom_projet_l" AS NOM_PROJET_L,
    DATA:"nom_projet_c" AS NOM_PROJET_C,
    DATA:"cust_no" AS CUST_NO,
    DATA:"no_estime" AS NO_ESTIME,
    DATA:"no_proj_cli" AS NO_PROJ_CLI,
    DATA:"nom_contact" AS NOM_CONTACT,
    DATA:"no_bon_achat" AS NO_BON_ACHAT,
    DATA:"no_contrat_v" AS NO_CONTRAT_V,
    DATA:"type_projet" AS TYPE_PROJET,
    DATA:"douane_proj" AS DOUANE_PROJ,
    DATA:"statut_proj" AS STATUT_PROJ,
    DATA:"terr_code" AS TERR_CODE,
    DATA:"pst_license" AS PST_LICENSE,
    DATA:"fst_license" AS FST_LICENSE,
    DATA:"adresse_liv_1" AS ADRESSE_LIV_1,
    DATA:"adresse_liv_2" AS ADRESSE_LIV_2,
    DATA:"adresse_liv_3" AS ADRESSE_LIV_3,
    DATA:"details_liv_1" AS DETAILS_LIV_1,
    DATA:"details_liv_2" AS DETAILS_LIV_2,
    DATA:"details_liv_3" AS DETAILS_LIV_3,
    DATA:"fob_code" AS FOB_CODE,
    DATA:"lieu_fab" AS LIEU_FAB,
    DATA:"slsmn_code" AS SLSMN_CODE,
    DATA:"nbr_plancher" AS NBR_PLANCHER,
    DATA:"resp_ordon" AS RESP_ORDON,
    DATA:"seq_facture" AS SEQ_FACTURE,
    DATA:"ord_prod" AS ORD_PROD,
    DATA:"hold_rate" AS HOLD_RATE,
    DATA:"waste_str_1" AS WASTE_STR_1,
    DATA:"waste_str_2" AS WASTE_STR_2,
    DATA:"nbr_design" AS NBR_DESIGN,
    DATA:"nbr_famil" AS NBR_FAMIL,
    DATA:"no_catg" AS NO_CATG,
    DATA:"term_code" AS TERM_CODE,
    DATA:"city_to" AS CITY_TO,
    DATA:"area_to" AS AREA_TO,
    DATA:"manager" AS MANAGER,
    DATA:"pos_tag" AS POS_TAG,
    DATA:"sequencing" AS SEQUENCING,
    DATA:"job_no" AS JOB_NO,
    DATA:"nb_ship_1" AS NB_SHIP_1,
    DATA:"nb_ship_2" AS NB_SHIP_2,
    DATA:"nb_escort" AS NB_ESCORT,
    DATA:"longest" AS LONGEST,
    DATA:"job_site_1" AS JOB_SITE_1,
    DATA:"job_site_2" AS JOB_SITE_2,
    DATA:"job_site_3" AS JOB_SITE_3,
    DATA:"follow_mark" AS FOLLOW_MARK,
    DATA:"trans_mark" AS TRANS_MARK,
    DATA:"entity_ste" AS ENTITY_STE,
    DATA:"no_estime_esf" AS NO_ESTIME_ESF,
    DATA:"mark_type" AS MARK_TYPE,
    DATA:"pdm_file" AS PDM_FILE,
    DATA:"follow_div" AS FOLLOW_DIV,
    DATA:"bolt_resp" AS BOLT_RESP,
    DATA:"site_phone" AS SITE_PHONE,
    DATA:"site_fax" AS SITE_FAX,
    DATA:"form_entity" AS FORM_ENTITY,
    DATA:"proj_coord" AS PROJ_COORD,
    DATA:"paint_date" AS PAINT_DATE,
    DATA:"bolt_included" AS BOLT_INCLUDED,
    DATA:"joist_plant" AS JOIST_PLANT,
    DATA:"sequnc_dates_1" AS SEQUNC_DATES_1,
    DATA:"sequnc_dates_2" AS SEQUNC_DATES_2,
    DATA:"sequnc_dates_3" AS SEQUNC_DATES_3,
    DATA:"sequnc_weeks_1" AS SEQUNC_WEEKS_1,
    DATA:"sequnc_weeks_2" AS SEQUNC_WEEKS_2,
    DATA:"sequnc_weeks_3" AS SEQUNC_WEEKS_3,
    DATA:"cmg_source_template" AS CMG_SOURCE_TEMPLATE,
    DATA:"cmg_assoc_proj" AS CMG_ASSOC_PROJ,
    DATA:"cmg_transf_time" AS CMG_TRANSF_TIME,
    DATA:"cmg_transfer" AS CMG_TRANSFER,
    DATA:"cmg_transf_date" AS CMG_TRANSF_DATE,
    DATA:"cmg_check_amt" AS CMG_CHECK_AMT,
    DATA:"cmg_city" AS CMG_CITY,
    DATA:"county_code" AS COUNTY_CODE,
    DATA:"cmg_state" AS CMG_STATE,
    DATA:"cmg_zip_code" AS CMG_ZIP_CODE,
    DATA:"cmg_country" AS CMG_COUNTRY,
    DATA:"exchgn_rate" AS EXCHGN_RATE,
    DATA:"ship_trf_date" AS SHIP_TRF_DATE,
    DATA:"ship_trf_time" AS SHIP_TRF_TIME,
    DATA:"budget_trf_date" AS BUDGET_TRF_DATE,
    DATA:"budget_trf_time" AS BUDGET_TRF_TIME,
    DATA:"cmg_credit_comm" AS CMG_CREDIT_COMM,
    DATA:"invoice_print_style" AS INVOICE_PRINT_STYLE,
    DATA:"lst_bcklog" AS LST_BCKLOG,
    DATA:"sales_stat" AS SALES_STAT,
    DATA:"quottn_access" AS QUOTTN_ACCESS,
    DATA:"branch_office_code" AS BRANCH_OFFICE_CODE,
    DATA:"mli" AS MLI,
    DATA:"is_abm_page_line" AS IS_ABM_PAGE_LINE,
    DATA:"abm_follow_up" AS ABM_FOLLOW_UP,
    DATA:"drwg_office_code" AS DRWG_OFFICE_CODE,
    DATA:"buyer_code" AS BUYER_CODE,
    DATA:"kronos_trf_date" AS KRONOS_TRF_DATE,
    DATA:"waste_cost_1" AS WASTE_COST_1,
    DATA:"waste_cost_2" AS WASTE_COST_2,
    DATA:"office_code" AS OFFICE_CODE,
    DATA:"max_deck_bundl_weight" AS MAX_DECK_BUNDL_WEIGHT,
    DATA:"max_deck_bundl_pieces" AS MAX_DECK_BUNDL_PIECES,
    DATA:"deck_bundl_pieces_tolerance" AS DECK_BUNDL_PIECES_TOLERANCE,
    DATA:"budget_valid_date" AS BUDGET_VALID_DATE,
    DATA:"chiefs_engineer" AS CHIEFS_ENGINEER,
    DATA:"chiefs_detailer" AS CHIEFS_DETAILER,
    DATA:"shipping_coordinators" AS SHIPPING_COORDINATORS,
    DATA:"gdm_project_id" AS GDM_PROJECT_ID,
    DATA:"quotation_sent_date" AS QUOTATION_SENT_DATE,
    DATA:"price_expiration_date" AS PRICE_EXPIRATION_DATE,
    DATA:"no_splice_top_bot" AS NO_SPLICE_TOP_BOT,
    DATA:"drawing_due_in" AS DRAWING_DUE_IN,
    DATA:"special_elements" AS SPECIAL_ELEMENTS,
    DATA:"special_elements_comments" AS SPECIAL_ELEMENTS_COMMENTS,
    DATA:"priority_code" AS PRIORITY_CODE,
    DATA:"rollbar_expected_back_date" AS ROLLBAR_EXPECTED_BACK_DATE,
    DATA:"rollbar_actual_back_date" AS ROLLBAR_ACTUAL_BACK_DATE,
    DATA:"is_layout_job" AS IS_LAYOUT_JOB,
    DATA:"rollbar_follow_up_date" AS ROLLBAR_FOLLOW_UP_DATE,
    DATA:"contact_email" AS CONTACT_EMAIL,
    DATA:"list_on_hambro_schedule" AS LIST_ON_HAMBRO_SCHEDULE,
    DATA:"set_off_information" AS SET_OFF_INFORMATION,
    DATA:"cmg_invoice_style" AS CMG_INVOICE_STYLE,
    DATA:"po_no_trans_oracle" AS PO_NO_TRANS_ORACLE,
    DATA:"weight_increase_comment" AS WEIGHT_INCREASE_COMMENT,
    DATA:"layout_process_code" AS LAYOUT_PROCESS_CODE,
    DATA:"shipping_comments" AS SHIPPING_COMMENTS,
    DATA:"rollbar_comment" AS ROLLBAR_COMMENT,
    DATA:"estimation_include_design" AS ESTIMATION_INCLUDE_DESIGN,
    DATA:"leed_certified" AS LEED_CERTIFIED,
    DATA:"dsms_transfer" AS DSMS_TRANSFER,
    DATA:"design_completed_date" AS DESIGN_COMPLETED_DATE,
    DATA:"financial_comments" AS FINANCIAL_COMMENTS,
    DATA:"project_status_code" AS PROJECT_STATUS_CODE,
    DATA:"project_status_comment" AS PROJECT_STATUS_COMMENT,
    DATA:"project_status_updated_by" AS PROJECT_STATUS_UPDATED_BY,
    DATA:"project_status_updated_datetime" AS PROJECT_STATUS_UPDATED_DATETIME,
    DATA:"business_unit_id" AS BUSINESS_UNIT_ID,
    DATA:"preparation_follow_up" AS PREPARATION_FOLLOW_UP,
    DATA:"prep_follow_up_marks_filter" AS PREP_FOLLOW_UP_MARKS_FILTER,
    DATA:"taxation_address" AS TAXATION_ADDRESS,
    DATA:"projet_g_uuid" AS PROJET_G_UUID,
    DATA:"_rowid" AS ROW_ID,
    DATA:"CreatedBy" AS CREATED_BY,
    DATA:"CreatedDate" AS CREATED_DATE,
    DATA:"ModifiedDate" AS MODIFIED_DATE,
    DATA:"ModifiedBy" AS MODIFIED_BY,
    DATA:"src_system_operation" AS SRC_SYSTEM_OPERATION,
    DATA:"ipaas_updated_date" AS IPAAS_UPDATED_DATE,
    DATA:"DataEventTimestamp" AS DATA_EVENT_TIMESTAMP,
    FILENAME AS METADATA_FILENAME,
    FILE_ROW_NUMBER AS METADATA_FILE_ROW_NUMBER,
    FILE_LAST_MODIFIED AS METADATA_FILE_LAST_MODIFIED,
    START_SCAN_TIME AS METADATA_START_SCAN_TIME
    ,{{ dbt_utils.generate_surrogate_key(['DATA:"projet_g_uuid"']) }} as TABLE_SK
    ,COALESCE(TO_TIMESTAMP_TZ(DATA:"DataEventTimestamp"),TO_TIMESTAMP_NTZ(DATEADD(microsecond, FILE_ROW_NUMBER,TO_TIMESTAMP_NTZ(DATA:"ipaas_updated_date"::string)))) as QUALIFY_TIMESTAMP

FROM
    {{ source("landing_spm_ca", "PROJET_G") }}
WHERE
    -- Only take the files after the last fullLoad
    SPLIT(FILENAME, '_')[ARRAY_SIZE(SPLIT(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM
            (
                SELECT
                    SPLIT(FILENAME, '_')[ARRAY_SIZE(SPLIT(FILENAME, '_')) - 2] AS min_timestamp,
                    SPLIT(FILENAME, '/')[3] AS type_file
                FROM
                    {{ source("landing_spm_ca", "PROJET_G") }}
                WHERE
                    type_file LIKE 'fullload%'
                QUALIFY ROW_NUMBER() OVER (ORDER BY min_timestamp DESC) = 1
            )
    )