{{
  config(
    materialized = "view",
    alias = "suppliers",
    schema='canam_model'
  )
}}


SELECT
--- For data duplicates in the same file
DISTINCT
COMPANYCODE::NUMBER(38,0) as COMPANYCODE
, NATUREOFSUPPLYCODE::NUMBER(38,0) as NATUREOFSUPPLYCODE
, OURCUSTOMERNUMBER::NUMBER(38,0) as OURCUSTOMERNUMBER
, CASE SOURCESYSTEM::string WHEN 'ORA' THEN 'oracle-ebs' ELSE SOURCESYSTEM::string END as SOURCESYSTEM
, SUPPLIERCODE::NUMBER(38,0) as SUPPLIERCODE
, SUPPLIERTYPECODE::STRING as SUPPLIERTYPECODE
, SupplierName::string AS SUPPLIER_NAME
, SUPPLIERSTATUSCODE::string as SUPPLIERSTATUSCODE
, BUSINESSPARTNERIDENTIFIERS_ARRAY as BUSINESSPARTNERIDENTIFIERS_ARRAY
, BUYFROMPROFILES_ARRAY as BUYFROMPROFILES_ARRAY
, COMMUNICATIONS_ARRAY as COMMUNICATIONS_ARRAY
, INVOICEFROMPROFILE_ARRAY as INVOICEFROMPROFILE_ARRAY
, LOCATIONS_ARRAY as LOCATIONS_ARRAY
, PAYTOPROFILES_ARRAY as PAYTOPROFILES_ARRAY
, SHIPFROMPROFILES_ARRAY as SHIPFROMPROFILES_ARRAY
from {{ref('prep_canammodel_suppliers')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY SUPPLIERCODE ORDER BY TO_TIMESTAMP_NTZ(metadata_file_last_modified) desc, METADATA_FILE_ROW_NUMBER desc) = 1
--qualify metadata_file_last_modified = max(metadata_file_last_modified) OVER (PARTITION BY suppliercode)
