dbt-enterprise-project:
  target: test ##Default target
  outputs:
    local:
      type: snowflake
      threads: 8
      account: "QNFANFA-QI17075"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      
      authenticator: externalbrowser      
      role: "ACCOUNTADMIN"
      database: "ADVWORKS_DEV"
      warehouse: "ETL_WH_DEV"
      schema: "LANDING"
  
    test:
      type: snowflake
      threads: 8
      account: "{{ env_var('TEST_DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('TEST_DBT_SNOWFLAKE_USER') }}"
      role: "{{ env_var('TEST_DBT_SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('TEST_DBT_SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('TEST_DBT_SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('TEST_DBT_SNOWFLAKE_SCHEMA') }}"
      private_key_path: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      private_key_passphrase: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"
      client_session_keep_alive: False

    preprod:
      type: snowflake
      threads: 8
      account: "{{ env_var('PREPROD_DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('PREPROD_DBT_SNOWFLAKE_USER') }}"
      role: "{{ env_var('PREPROD_DBT_SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('PREPROD_DBT_SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('PREPROD_DBT_SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('PREPROD_DBT_SNOWFLAKE_SCHEMA') }}"
      private_key_path: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      private_key_passphrase: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"
      client_session_keep_alive: False

    prod:
      type: snowflake
      threads: 8
      account: "{{ env_var('PROD_DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('PROD_DBT_SNOWFLAKE_USER') }}"
      role: "{{ env_var('PROD_DBT_SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('PROD_DBT_SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('PROD_DBT_SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('PROD_DBT_SNOWFLAKE_SCHEMA') }}"
      private_key_path: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      private_key_passphrase: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"
      client_session_keep_alive: False

