{{
  config(
    full_refresh = true,
    materialized="dynamic_table",
    target_lag="15minutes",
    snowflake_warehouse= var('task_warehouse'),
    alias = "rollformer_substitution_transaction",
    schema= "dataproducts_bronze",
    post_hook = "ALTER DYNAMIC TABLE {{ this }} SET LOG_LEVEL = ERROR"
  )
}}

WITH MAIN_DATA AS(
    SELECT DISTINCT
        PT.USED_SLITTED_COIL_NUMBER AS SLITTEDCOIL_NUMBER,
        PT.SUBSTITUTION_REASON_CODE AS SUBSTITUTION_REASON_CODE,
        PT.REQUISITION_NUMBER AS REQUISITION_NUMBER,
        PT.ENTITY_CODE AS ENTITY_CODE,
        PT.EQUIPMENT_NAME AS EQUIPMENT_NAME,
        PT.PRODUCT_NO AS PRODUCT_NUMBER,
        RP.NO_JOB_SHOP AS JOB_NUMBER,
        PT.MARK AS MARK,
        PT.COMPONENT_TYPE AS COMPONENT_TYPE,
        PT.QUANTITY_DONE AS QUANTITY_DONE,
        ITEM_RW.SORT_NAME AS REQUIRED_ITEM_CODE,
        PT.QUANTITY_DONE * PT.REQUEST_LENGTH / 304.8 AS REQUESTED_ITEM_LENGTH_FOOT,
        PT.USED_SORT_ITEM_CODE AS USED_ITEM_CODE,
        PT.QUANTITY_DONE * PT.USED_LENGTH / 304.8 AS USED_ITEM_LENGTH_FOOT,
        PT.SUBSTITUTION_REASON_DESCRIPTION_ENGLISH AS SUBSTITUTION_REASON_DESC_ENGLISH,
        PT.SUBSTITUTION_REASON_DESCRIPTION_FRENCH AS SUBSTITUTION_REASON_DESC_FRENCH,
        PT.OPERATOR_NAME AS OPERATOR_NAME,
        PT.START_TIME AS SUBSTITUTION_START_TIMESTAMP,
        PT.END_TIME AS SUBSTITUTION_END_TIMESTAMP,
        
        -- Weight and Cost Calculations
        (PT.QUANTITY_DONE * PT.REQUEST_LENGTH * ITEM_RW.WEIGHT) / 304.8 AS REQUIRED_WEIGHT,
        (PT.QUANTITY_DONE * PT.REQUEST_LENGTH * ITEM_USED.WEIGHT) / 304.8 AS USED_WEIGHT,
        IWHS_RC.LAST_COST * REQUIRED_WEIGHT AS REQUIRED_COST,
        IWHS_UC.LAST_COST * USED_WEIGHT AS USED_COST,
        IFNULL(USED_WEIGHT - REQUIRED_WEIGHT, 0) AS SUBSTITUTION_EXTRA_WEIGHT,
        IFNULL(USED_COST - REQUIRED_COST, 0) AS SUBSTITUTION_ADDITIONAL_COST,
        
        CASE 
            WHEN WSC.WORKING_SHIFT_CODE = 'NIGHT' THEN 'NUIT' 
            WHEN WSC.WORKING_SHIFT_CODE = 'DAY' THEN 'JOUR'
            ELSE WSC.WORKING_SHIFT_CODE 
        END AS DAILY_SHIFT_NAME,

        MAX(WSC.WORKING_SHIFT_ACTIVE_FROM_DATE) OVER (
            PARTITION BY
                PT.USED_SLITTED_COIL_NUMBER,
                PT.SUBSTITUTION_REASON_CODE,
                PT.REQUISITION_NUMBER,
                PT.ENTITY_CODE,
                PT.EQUIPMENT_NAME,
                PT.PRODUCT_NO,
                RP.NO_JOB_SHOP,
                PT.MARK,
                PT.COMPONENT_TYPE,
                PT.QUANTITY_DONE,
                ITEM_RW.SORT_NAME,
                PT.REQUEST_LENGTH,
                PT.USED_SORT_ITEM_CODE,
                PT.USED_LENGTH,
                PT.SUBSTITUTION_REASON_DESCRIPTION_ENGLISH,
                PT.SUBSTITUTION_REASON_DESCRIPTION_FRENCH,
                PT.OPERATOR_NAME,
                PT.START_TIME,
                PT.END_TIME,
                REQUIRED_WEIGHT,
                USED_WEIGHT,
                REQUIRED_COST,
                USED_COST,
                SUBSTITUTION_EXTRA_WEIGHT,
                WSC.WORKING_SHIFT_CODE,
                SUBSTITUTION_ADDITIONAL_COST
        ) AS MAX_ACTIVE_FROM_DATE
    FROM {{ ref('norm_production_transactions') }} AS PT
    LEFT JOIN {{ ref('norm_req_prod') }} AS RP 
        ON RP.ENTITY_CODE = PT.ENTITY_CODE 
        AND RP.NO_POIDS = PT.REQUISITION_NUMBER
    LEFT JOIN {{ ref('norm_entity') }} AS E 
        ON E.ENTITY_CODE = PT.ENTITY_CODE
    LEFT JOIN {{ ref('norm_entity_d') }} AS ED 
        ON ED.ENTITY_CODE = PT.ENTITY_CODE
    LEFT JOIN {{ ref('norm_item') }} AS ITEM_USED
        ON ITEM_USED.IN_ENTITY = E.IN_ENTITY 
        AND ITEM_USED.SORT_NAME = PT.USED_SORT_ITEM_CODE
    LEFT JOIN {{ ref('norm_item') }} AS ITEM_RW
        ON ITEM_RW.IN_ENTITY = E.IN_ENTITY 
        AND ITEM_RW.ITEM_NO = PT.REQUIRED_ITEM_CODE
    LEFT JOIN {{ ref('norm_item_whs_d') }} AS IWHS_UC 
        ON IWHS_UC.IN_ENTITY = E.IN_ENTITY 
        AND IWHS_UC.WHS_CODE = ED.WHS_CODE 
        AND IWHS_UC.ITEM_NO = ITEM_USED.ITEM_NO
    LEFT JOIN {{ ref('norm_item_whs_d') }} AS IWHS_RC 
        ON IWHS_RC.IN_ENTITY = E.IN_ENTITY 
        AND IWHS_RC.WHS_CODE = ED.WHS_CODE 
        AND IWHS_RC.ITEM_NO = PT.REQUIRED_ITEM_CODE
    LEFT JOIN {{ ref('sche_working_shift_calendar') }} AS WSC
        ON RP.SHOP_NO = WSC.WORKING_SHIFT_SHOP_NO
        AND PT.ENTITY_CODE = WSC.WORKING_SHIFT_ENTITY_CODE
        AND WSC.WORKING_SHIFT_MACHN_NO IS NULL
        AND PT.START_TIME >= WSC.WORKING_SHIFT_START_DATETIME_NTZ
        AND PT.START_TIME < WSC.WORKING_SHIFT_END_DATETIME_NTZ
    WHERE 
        ITEM_RW.SORT_NAME <> PT.USED_SORT_ITEM_CODE
        AND WSC.WORKING_SHIFT_CODE IS NOT NULL
        AND PT.SUBSTITUTION_REASON_CODE IS NOT NULL
        AND PT.REQUISITION_NUMBER <> 0
        AND PT.QUANTITY_DONE <> 0
)

SELECT
    SLITTEDCOIL_NUMBER,
    SUBSTITUTION_REASON_CODE,
    REQUISITION_NUMBER,
    ENTITY_CODE,
    DAILY_SHIFT_NAME,
    EQUIPMENT_NAME,
    PRODUCT_NUMBER,
    JOB_NUMBER,
    MARK,
    COMPONENT_TYPE,
    QUANTITY_DONE,
    REQUIRED_ITEM_CODE,
    REQUESTED_ITEM_LENGTH_FOOT,
    USED_ITEM_CODE,
    USED_ITEM_LENGTH_FOOT,
    SUBSTITUTION_REASON_DESC_ENGLISH,
    SUBSTITUTION_REASON_DESC_FRENCH,
    SUBSTITUTION_ADDITIONAL_COST,
    SUBSTITUTION_EXTRA_WEIGHT,
    OPERATOR_NAME,
    SUBSTITUTION_START_TIMESTAMP,
    SUBSTITUTION_END_TIMESTAMP
FROM MAIN_DATA
