{{ config(
    materialized='table',
    schema='SCHEMATIZE'
) }}

SELECT
    CUSTOMER_KEY,
    CUSTOMER_ALTERNATE_KEY,
    GEOGRAPHY_KEY,
    TITLE,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    NAME_STYLE,
    BIRTH_DATE,
    MARITAL_STATUS,
    SUFFIX,
    GENDER,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    TOTAL_CHILDREN,
    NUMBER_CHILDREN_AT_HOME,
    ENGLISH_EDUCATION,
    ENGLISH_OCCUPATION,
    HOUSE_OWNER_FLAG,
    NUMBER_CARS_OWNED,
    ADDRESS_LINE_1,
    ADDRESS_LINE_2,
    PHONE,
    DATE_FIRST_PURCHASE,
    COMMUTE_DISTANCE,

    CURRENT_TIMESTAMP() AS CREATED_TIMESTAMP,
    CURRENT_TIMESTAMP() AS UPDATED_TIMESTAMP

FROM {{ ref('dim_customer_normalize') }}