{{ config(
    materialized='table',
    schema='SCHEMATIZE'
) }}

SELECT
    SALES_ORDER_NUMBER,
    SALES_ORDER_LINE_NUMBER,

    PRODUCT_KEY,
    CUSTOMER_KEY,

    ORDER_DATE_KEY,
    DUE_DATE_KEY,
    SHIP_DATE_KEY,

    PROMOTION_KEY,
    CURRENCY_KEY,
    SALES_TERRITORY_KEY,

    REVISION_NUMBER,
    ORDER_QUANTITY,

    UNIT_PRICE,
    EXTENDED_AMOUNT,
    UNIT_PRICE_DISCOUNT_PCT,
    DISCOUNT_AMOUNT,
    PRODUCT_STANDARD_COST,
    TOTAL_PRODUCT_COST,
    SALES_AMOUNT,
    TAX_AMT,
    FREIGHT,

    CARRIER_TRACKING_NUMBER,
    CUSTOMER_PO_NUMBER,

    ORDER_DATE,
    DUE_DATE,
    SHIP_DATE,

    SOURCE_FILE,
    LOAD_TIMESTAMP,

    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP

FROM {{ ref('fact_internet_sales_normalize') }}