{{
  config(
    materialized = "view",
    alias = "cm50_gl_code_combinations",
    schema='EBS'
  )
}}

SELECT
GCC_CODE_COMBINATION_ID::NUMBER AS GCC_CODE_COMBINATION_ID
,TO_TIMESTAMP_NTZ(GCC_LAST_UPDATE_DATE::string) AS GCC_LAST_UPDATE_DATE
,GCC_LAST_UPDATED_BY::NUMBER AS GCC_LAST_UPDATED_BY
,GCC_CHART_OF_ACCOUNTS_ID::NUMBER AS GCC_CHART_OF_ACCOUNTS_ID
,GCC_DETAIL_POSTING_AL_FLAG::string AS GCC_DETAIL_POSTING_AL_FLAG
,GCC_DETAIL_BUDGETING_AL_FLAG::string AS GCC_DETAIL_BUDGETING_AL_FLAG
,GCC_ACCOUNT_TYPE::string AS GCC_ACCOUNT_TYPE
,GCC_ENABLED_FLAG::string AS GCC_ENABLED_FLAG
,GCC_SUMMARY_FLAG::string AS GCC_SUMMARY_FLAG
,UPPER(NULLIF(TRIM(GCC_SEGMENT1::string),'')) AS GCC_SEGMENT1
,UPPER(NULLIF(TRIM(GCC_SEGMENT2::string),'')) AS GCC_SEGMENT2
,UPPER(NULLIF(TRIM(GCC_SEGMENT3::string),'')) AS GCC_SEGMENT3
,UPPER(NULLIF(TRIM(GCC_SEGMENT4::string),'')) AS GCC_SEGMENT4
,UPPER(NULLIF(TRIM(GCC_SEGMENT5::string),'')) AS GCC_SEGMENT5
,UPPER(NULLIF(TRIM(GCC_SEGMENT6::string),'')) AS GCC_SEGMENT6
,GCC_TEMPLATE_ID::NUMBER AS GCC_TEMPLATE_ID
,GCC_ALLOCATION_CREATE_FLAG::string AS GCC_ALLOCATION_CREATE_FLAG
,TO_TIMESTAMP_NTZ(GCC_START_DATE_ACTIVE::string) AS GCC_START_DATE_ACTIVE
--,TO_TIMESTAMP_NTZ(GCC_END_DATE_ACTIVE::string) AS GCC_END_DATE_ACTIVE--entirely null
--,GCC_PRESERVE_FLAG::string AS GCC_PRESERVE_FLAG--entirely null
,GCC_REFRESH_FLAG::string AS GCC_REFRESH_FLAG
  
FROM {{ref('prep_cm50_gl_code_combinations')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY GCC_CODE_COMBINATION_ID ORDER BY TO_TIMESTAMP_NTZ(GCC_LAST_UPDATE_DATE) DESC) = 1