{{
  config(
    materialized = "view",
    alias = "hz_parties",
    schema='ebs'
  )
}}


SELECT PARTY_ID::NUMBER(15,0) AS PARTY_ID
,UPPER(NULLIF(TRIM(PARTY_NUMBER::string), '')) AS PARTY_NUMBER
,UPPER(NULLIF(TRIM(PARTY_NAME::string), '')) AS PARTY_NAME
,UPPER(NULLIF(TRIM(PARTY_TYPE::string), '')) AS PARTY_TYPE
,UPPER(NULLIF(TRIM(VALIDATED_FLAG::string), '')) AS VALIDATED_FLAG
,LAST_UPDATED_BY::NUMBER(15,0) AS LAST_UPDATED_BY
,TO_TIMESTAMP_NTZ(CREATION_DATE::STRING) AS CREATION_DATE
,LAST_UPDATE_LOGIN::NUMBER(15,0) AS LAST_UPDATE_LOGIN
,REQUEST_ID::NUMBER(15,0) AS REQUEST_ID
,PROGRAM_APPLICATION_ID::NUMBER(15,0) AS PROGRAM_APPLICATION_ID
,CREATED_BY::NUMBER(15,0) AS CREATED_BY
,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::STRING) AS LAST_UPDATE_DATE
,PROGRAM_ID::NUMBER(15,0) AS PROGRAM_ID
,TO_TIMESTAMP_NTZ(PROGRAM_UPDATE_DATE::STRING) AS PROGRAM_UPDATE_DATE
--,TO_TIMESTAMP_NTZ(WH_UPDATE_DATE::STRING) AS WH_UPDATE_DATE --Excluded always NULL
--,NULLIF(TRIM(ATTRIBUTE_CATEGORY::string), '') AS ATTRIBUTE_CATEGORY  --Excluded always NULL
,UPPER(NULLIF(TRIM(ATTRIBUTE1::string), '')) AS ATTRIBUTE1
,CASE
        WHEN LENGTH(ATTRIBUTE2::STRING) = 10 AND POSITION('-', ATTRIBUTE2::STRING) = 3
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE2::STRING, 'DD-MM-YYYY')
        WHEN LENGTH(ATTRIBUTE2::STRING) = 10 AND POSITION('-', ATTRIBUTE2::STRING) = 5
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE2::STRING, 'YYYY-MM-DD')
        ELSE NULL
    END AS ATTRIBUTE2
      ,CASE
        WHEN LENGTH(ATTRIBUTE3::STRING) = 10 AND POSITION('-', ATTRIBUTE3::STRING) = 3
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE3::STRING, 'DD-MM-YYYY')
        WHEN LENGTH(ATTRIBUTE3::STRING) = 10 AND POSITION('-', ATTRIBUTE3::STRING) = 5
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE3::STRING, 'YYYY-MM-DD')
        ELSE NULL
    END AS ATTRIBUTE3
      ,CASE
        WHEN LENGTH(ATTRIBUTE4::STRING) = 10 AND POSITION('-', ATTRIBUTE4::STRING) = 3
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE4::STRING, 'DD-MM-YYYY')
        WHEN LENGTH(ATTRIBUTE4::STRING) = 10 AND POSITION('-', ATTRIBUTE4::STRING) = 5
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE4::STRING, 'YYYY-MM-DD')
        ELSE NULL
    END AS ATTRIBUTE4
      ,CASE
        WHEN LENGTH(ATTRIBUTE5::STRING) = 10 AND POSITION('-', ATTRIBUTE5::STRING) = 3
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE5::STRING, 'DD-MM-YYYY')
        WHEN LENGTH(ATTRIBUTE5::STRING) = 10 AND POSITION('-', ATTRIBUTE5::STRING) = 5
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE5::STRING, 'YYYY-MM-DD')
        ELSE NULL
    END AS ATTRIBUTE5
,UPPER(NULLIF(TRIM(ATTRIBUTE6::string), '')) AS ATTRIBUTE6
,UPPER(NULLIF(TRIM(ATTRIBUTE7::string), '')) AS ATTRIBUTE7
,UPPER(NULLIF(TRIM(ATTRIBUTE8::string), '')) AS ATTRIBUTE8
,UPPER(NULLIF(TRIM(ATTRIBUTE9::string), '')) AS ATTRIBUTE9
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE10::string), '')) AS ATTRIBUTE10 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE11::string), '')) AS ATTRIBUTE11 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE12::string), '')) AS ATTRIBUTE12 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE13::string), '')) AS ATTRIBUTE13 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE14::string), '')) AS ATTRIBUTE14 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE15::string), '')) AS ATTRIBUTE15 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE16::string), '')) AS ATTRIBUTE16 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE17::string), '')) AS ATTRIBUTE17 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE18::string), '')) AS ATTRIBUTE18 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE19::string), '')) AS ATTRIBUTE19 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE20::string), '')) AS ATTRIBUTE20 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE21::string), '')) AS ATTRIBUTE21 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE22::string), '')) AS ATTRIBUTE22 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE23::string), '')) AS ATTRIBUTE23 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(ATTRIBUTE24::string), '')) AS ATTRIBUTE24 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE_CATEGORY::string), '')) AS GLOBAL_ATTRIBUTE_CATEGORY --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE1::string), '')) AS GLOBAL_ATTRIBUTE1 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE2::string), '')) AS GLOBAL_ATTRIBUTE2 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE4::string), '')) AS GLOBAL_ATTRIBUTE4 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE3::string), '')) AS GLOBAL_ATTRIBUTE3 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE5::string), '')) AS GLOBAL_ATTRIBUTE5 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE6::string), '')) AS GLOBAL_ATTRIBUTE6 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE7::string), '')) AS GLOBAL_ATTRIBUTE7 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE8::string), '')) AS GLOBAL_ATTRIBUTE8 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE9::string), '')) AS GLOBAL_ATTRIBUTE9 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE10::string), '')) AS GLOBAL_ATTRIBUTE10 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE11::string), '')) AS GLOBAL_ATTRIBUTE11 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE12::string), '')) AS GLOBAL_ATTRIBUTE12 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE13::string), '')) AS GLOBAL_ATTRIBUTE13 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE14::string), '')) AS GLOBAL_ATTRIBUTE14 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE15::string), '')) AS GLOBAL_ATTRIBUTE15 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE16::string), '')) AS GLOBAL_ATTRIBUTE16 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE17::string), '')) AS GLOBAL_ATTRIBUTE17 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE18::string), '')) AS GLOBAL_ATTRIBUTE18 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE19::string), '')) AS GLOBAL_ATTRIBUTE19 --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(GLOBAL_ATTRIBUTE20::string), '')) AS GLOBAL_ATTRIBUTE20 --Excluded always NULL
,UPPER(NULLIF(TRIM(ORIG_SYSTEM_REFERENCE::string), '')) AS ORIG_SYSTEM_REFERENCE
-- ,NULLIF(TRIM(SIC_CODE::string), '') AS SIC_CODE --Excluded always NULL
-- ,NULLIF(TRIM(HQ_BRANCH_IND::string), '') AS HQ_BRANCH_IND --Excluded always NULL
,UPPER(NULLIF(TRIM(CUSTOMER_KEY::string), '')) AS CUSTOMER_KEY
,NULLIF(TRIM(TAX_REFERENCE::string), '') AS TAX_REFERENCE
--,NULLIF(TRIM(JGZZ_FISCAL_CODE::string), '') AS JGZZ_FISCAL_CODE--single value data
--,DUNS_NUMBER::NUMBER AS DUNS_NUMBER --Excluded always NULL
--,NULLIF(TRIM(TAX_NAME::string), '') AS TAX_NAME--Excluded always NULL
--,CASE
   -- WHEN PERSON_PRE_NAME_ADJUNCT::string = 'MR' THEN 'MR.'
    --WHEN PERSON_PRE_NAME_ADJUNCT::string = 'MS' THEN 'MS.'
    --WHEN PERSON_PRE_NAME_ADJUNCT::string = 'MISS' THEN 'MISS'
   -- ELSE NULL
--END AS PERSON_PRE_NAME_ADJUNCT--single value data
,UPPER(NULLIF(TRIM(PERSON_FIRST_NAME::string), '')) AS PERSON_FIRST_NAME
,UPPER(NULLIF(TRIM(PERSON_MIDDLE_NAME::string), '')) AS PERSON_MIDDLE_NAME
,UPPER(NULLIF(TRIM(PERSON_LAST_NAME::string), '')) AS PERSON_LAST_NAME
-- ,UPPER(NULLIF(TRIM(PERSON_NAME_SUFFIX::string), '')) AS PERSON_NAME_SUFFIX --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(PERSON_TITLE::string), '')) AS PERSON_TITLE --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(PERSON_ACADEMIC_TITLE::string), '')) AS PERSON_ACADEMIC_TITLE --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(PERSON_PREVIOUS_LAST_NAME::string), '')) AS PERSON_PREVIOUS_LAST_NAME --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(KNOWN_AS::string), '')) AS KNOWN_AS --Excluded always NULL
-- ,UPPER(NULLIF(TRIM(PERSON_IDEN_TYPE::string), '')) AS PERSON_IDEN_TYPE --Excluded always NULL
,NULLIF(TRIM(PERSON_IDENTIFIER::string), '') AS PERSON_IDENTIFIER
--,NULLIF(TRIM(GROUP_TYPE::string), '') AS GROUP_TYPE--Excluded always NULL
 ,UPPER(NULLIF(TRIM(COUNTRY::string), '')) AS COUNTRY
,INITCAP(NULLIF(TRIM(ADDRESS1::string), '')) AS ADDRESS1
,INITCAP(NULLIF(TRIM(ADDRESS2::string), '')) AS ADDRESS2
,INITCAP(NULLIF(TRIM(ADDRESS3::string), '')) AS ADDRESS3
,UPPER(NULLIF(TRIM(ADDRESS4::string), '')) AS ADDRESS4
,INITCAP(NULLIF(TRIM(CITY::string), '')) AS CITY
,UPPER(NULLIF(TRIM(POSTAL_CODE::string), '')) AS POSTAL_CODE
,UPPER(NULLIF(TRIM(STATE::string), '')) AS STATE
,UPPER(NULLIF(TRIM(PROVINCE::string), '')) AS PROVINCE
,UPPER(NULLIF(TRIM(STATUS::string), '')) AS STATUS
,INITCAP(NULLIF(TRIM(COUNTY::string), '')) AS COUNTY
--,NULLIF(TRIM(SIC_CODE_TYPE::string), '') AS SIC_CODE_TYPE----Excluded always NULL
--,NULLIF(TRIM(TOTAL_NUM_OF_ORDERS::string), '') AS TOTAL_NUM_OF_ORDERS--Excluded always NULL
--,NULLIF(TRIM(TOTAL_ORDERED_AMOUNT::string), '') AS TOTAL_ORDERED_AMOUNT--Excluded always NULL
--,TO_TIMESTAMP_NTZ(LAST_ORDERED_DATE::string) AS LAST_ORDERED_DATE --Excluded always NULL
--,NULLIF(TRIM(URL::string), '') AS URL--Excluded always NULL
,NULLIF(TRIM(EMAIL_ADDRESS::string), '') AS EMAIL_ADDRESS
--,NULLIF(TRIM(DO_NOT_MAIL_FLAG::string), '') AS DO_NOT_MAIL_FLAG--Excluded always NULL
--,NULLIF(TRIM(ANALYSIS_FY::string), '') AS ANALYSIS_FY--Excluded always NULL
--,NULLIF(TRIM(FISCAL_YEAREND_MONTH::string), '') AS FISCAL_YEAREND_MONTH--Excluded always NULL
--,EMPLOYEES_TOTAL::NUMBER AS EMPLOYEES_TOTAL --Excluded always NULL
--,CURR_FY_POTENTIAL_REVENUE::NUMBER AS CURR_FY_POTENTIAL_REVENUE --Excluded always NULL
--,NEXT_FY_POTENTIAL_REVENUE::NUMBER AS NEXT_FY_POTENTIAL_REVENUE --Excluded always NULL
--,YEAR_ESTABLISHED::NUMBER(4,0) AS YEAR_ESTABLISHED --Excluded always NULL
,UPPER(NULLIF(TRIM(GSA_INDICATOR_FLAG::string), '')) AS GSA_INDICATOR_FLAG
--,INITCAP(NULLIF(TRIM(MISSION_STATEMENT::string), '')) AS MISSION_STATEMENT--single value data
--,ORGANIZATION_NAME_PHONETIC::string AS ORGANIZATION_NAME_PHONETIC --Excluded always NULL
--,PERSON_FIRST_NAME_PHONETIC::string AS PERSON_FIRST_NAME_PHONETIC --Excluded always NULL
--,PERSON_LAST_NAME_PHONETIC::string AS PERSON_LAST_NAME_PHONETIC --Excluded always NULL
--,LANGUAGE_NAME::string AS LANGUAGE_NAME --Excluded always NULL
--,UPPER(NULLIF(TRIM(CATEGORY_CODE::string), '')) AS CATEGORY_CODE--single value data
,UPPER(NULLIF(TRIM(REFERENCE_USE_FLAG::string), '')) AS REFERENCE_USE_FLAG
,UPPER(NULLIF(TRIM(THIRD_PARTY_FLAG::string), '')) AS THIRD_PARTY_FLAG
,UPPER(NULLIF(TRIM(COMPETITOR_FLAG::string), '')) AS COMPETITOR_FLAG
--,UPPER(NULLIF(TRIM(SALUTATION::string), '')) AS SALUTATION--Excluded always NULL
--,NULLIF(TRIM(KNOWN_AS2::string), '') AS KNOWN_AS2--Excluded always NULL
--,NULLIF(TRIM(KNOWN_AS3::string), '') AS KNOWN_AS3--Excluded always NULL
--,NULLIF(TRIM(KNOWN_AS4::string), '') AS KNOWN_AS4--Excluded always NULL
--,NULLIF(TRIM(KNOWN_AS5::string), '') AS KNOWN_AS5--Excluded always NULL
--,NULLIF(TRIM(DUNS_NUMBER_C::string), '') AS DUNS_NUMBER_C--Excluded always NULL
,OBJECT_VERSION_NUMBER::NUMBER AS OBJECT_VERSION_NUMBER
,UPPER(NULLIF(TRIM(CREATED_BY_MODULE::string), '')) AS CREATED_BY_MODULE
,APPLICATION_ID::NUMBER AS APPLICATION_ID
,PRIMARY_PHONE_CONTACT_PT_ID::NUMBER(15,0) AS PRIMARY_PHONE_CONTACT_PT_ID
--,UPPER(NULLIF(TRIM(PRIMARY_PHONE_PURPOSE::string), '')) AS PRIMARY_PHONE_PURPOSE--single value data
,UPPER(NULLIF(TRIM(PRIMARY_PHONE_LINE_TYPE::string), '')) AS PRIMARY_PHONE_LINE_TYPE
--,NULLIF(TRIM(PRIMARY_PHONE_COUNTRY_CODE::string), '') AS PRIMARY_PHONE_COUNTRY_CODE--single value data
,NULLIF(TRIM(PRIMARY_PHONE_AREA_CODE::string), '') AS PRIMARY_PHONE_AREA_CODE
,NULLIF(TRIM(PRIMARY_PHONE_NUMBER::string), '') AS PRIMARY_PHONE_NUMBER
,NULLIF(TRIM(PRIMARY_PHONE_EXTENSION::string), '') AS PRIMARY_PHONE_EXTENSION
--,NULLIF(TRIM(CERTIFICATION_LEVEL::string), '') AS CERTIFICATION_LEVEL--Excluded always NULL
--,NULLIF(TRIM(CERT_REASON_CODE::string), '') AS CERT_REASON_CODE--Excluded always NULL
--,NULLIF(TRIM(PREFERRED_CONTACT_METHOD::string), '') AS PREFERRED_CONTACT_METHOD--Excluded always NULL
FROM {{ref('prep_hz_parties')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY PARTY_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) =1