{{
  config(
    materialized = "view",
    alias = "hr_organization_units_v",
    schema='EBS'
  )
}}

SELECT
    --LOC_INFORMATION15::STRING AS LOC_INFORMATION15, -- Excluded: Always NULL
    --LOC_INFORMATION14::STRING AS LOC_INFORMATION14, -- Excluded: Always NULL
    --LOC_INFORMATION13::STRING AS LOC_INFORMATION13, -- Excluded: Always NULL
    INITCAP(NULLIF(TRIM(TOWN_OR_CITY::string), '')) AS TOWN_OR_CITY,
    NULLIF(TRIM(UPPER(REGEXP_REPLACE(POSTAL_CODE::string,'[-\\s.*]',''))), '') AS POSTAL_CODE,
    --TELEPHONE_NUMBER_3::STRING AS TELEPHONE_NUMBER_3, -- Excluded: Always NULL
    NULLIF(REGEXP_REPLACE(TELEPHONE_NUMBER_2::STRING, '[^\\d]*'), '') AS TELEPHONE_NUMBER_2,
    NULLIF(REGEXP_REPLACE(TELEPHONE_NUMBER_1::STRING, '[^\\d]*'), '') AS TELEPHONE_NUMBER_1,
    --REGION_3::STRING AS REGION_3, -- Excluded: Always NULL
    NULLIF(TRIM(REGION_2::STRING), '') AS REGION_2,
    NULLIF(TRIM(REGION_1::STRING), '') AS REGION_1,
    NULLIF(TRIM(ADDRESS_LINE_3::STRING), '') AS ADDRESS_LINE_3,
    NULLIF(TRIM(ADDRESS_LINE_2::STRING), '') AS ADDRESS_LINE_2,
    NULLIF(TRIM(ADDRESS_LINE_1::STRING), '') AS ADDRESS_LINE_1,
    UPPER(NULLIF(TRIM(COUNTRY::string), '')) AS COUNTRY,
    NULLIF(TRIM(STYLE::STRING), '') AS STYLE,
    INITCAP(NULLIF(TRIM(LOCATION_CODE::string), '')) AS LOCATION_CODE,
    NULLIF(TRIM(LOCATION_ID::NUMBER(15,0)), '') AS LOCATION_ID,
    --COST_ALLOCATION_KEYFLEX_ID::NUMBER(9,0) AS COST_ALLOCATION_KEYFLEX_ID, -- Excluded: Always NULL
    --BUSINESS_GROUP_ID::NUMBER(15,0) AS BUSINESS_GROUP_ID, -- Excluded: Always NULL
    --ROW_ID::ROWID AS ROW_ID, -- Excluded: Always NULL
    ORGANIZATION_ID::NUMBER(15,0) AS ORGANIZATION_ID,
    OBJECT_VERSION_NUMBER::NUMBER(9,0) AS OBJECT_VERSION_NUMBER,
    TO_TIMESTAMP_NTZ(CREATION_DATE::STRING) AS CREATION_DATE,
    CREATED_BY::NUMBER(15,0) AS CREATED_BY,
    LAST_UPDATE_LOGIN::NUMBER(15,0) AS LAST_UPDATE_LOGIN,
    LAST_UPDATED_BY::NUMBER(15,0) AS LAST_UPDATED_BY,
    TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::STRING) AS LAST_UPDATE_DATE,
    --ATTRIBUTE20::STRING AS ATTRIBUTE20, -- Excluded: Always NULL
    --ATTRIBUTE19::STRING AS ATTRIBUTE19, -- Excluded: Always NULL
    --ATTRIBUTE18::STRING AS ATTRIBUTE18, -- Excluded: Always NULL
    --ATTRIBUTE17::STRING AS ATTRIBUTE17, -- Excluded: Always NULL
    --ATTRIBUTE16::STRING AS ATTRIBUTE16, -- Excluded: Always NULL
    --ATTRIBUTE15::STRING AS ATTRIBUTE15, -- Excluded: Always NULL
    --ATTRIBUTE14::STRING AS ATTRIBUTE14, -- Excluded: Always NULL
    --ATTRIBUTE13::STRING AS ATTRIBUTE13, -- Excluded: Always NULL
    --ATTRIBUTE12::STRING AS ATTRIBUTE12, -- Excluded: Always NULL
    --ATTRIBUTE11::STRING AS ATTRIBUTE11, -- Excluded: Always NULL
    NULLIF(TRIM(ATTRIBUTE10::STRING), '') AS ATTRIBUTE10,
    NULLIF(TRIM(ATTRIBUTE9::STRING), '') AS ATTRIBUTE9,
    NULLIF(TRIM(ATTRIBUTE8::STRING), '') AS ATTRIBUTE8,
    NULLIF(TRIM(ATTRIBUTE7::STRING), '') AS ATTRIBUTE7,
    NULLIF(TRIM(ATTRIBUTE6::STRING), '') AS ATTRIBUTE6,
    NULLIF(TRIM(ATTRIBUTE5::STRING), '') AS ATTRIBUTE5,
    NULLIF(TRIM(ATTRIBUTE4::STRING), '') AS ATTRIBUTE4,
    NULLIF(TRIM(ATTRIBUTE3::STRING), '') AS ATTRIBUTE3,
    NULLIF(TRIM(ATTRIBUTE2::STRING), '') AS ATTRIBUTE2,
    NULLIF(TRIM(ATTRIBUTE1::STRING), '') AS ATTRIBUTE1,
    NULLIF(TRIM(ATTRIBUTE_CATEGORY::STRING), '') AS ATTRIBUTE_CATEGORY,
    --TO_TIMESTAMP_NTZ(PROGRAM_UPDATE_DATE::DATE) AS PROGRAM_UPDATE_DATE, -- Excluded: Always NULL
    --PROGRAM_ID::NUMBER(15,0) AS PROGRAM_ID, -- Excluded: Always NULL
    --PROGRAM_APPLICATION_ID::NUMBER(15,0) AS PROGRAM_APPLICATION_ID, -- Excluded: Always NULL
    --REQUEST_ID::NUMBER(15,0) AS REQUEST_ID, -- Excluded: Always NULL
    NULLIF(TRIM(ORGANIZATION_TYPE::STRING), '') AS ORGANIZATION_TYPE,
    NULLIF(TRIM(TYPE::STRING), '') AS TYPE,
    --INTERNAL_ADDRESS_LINE::STRING AS INTERNAL_ADDRESS_LINE, -- Excluded: Always NULL
    --NULLIF(TRIM(INTERNAL_EXTERNAL_MEANING::STRING), '') AS INTERNAL_EXTERNAL_MEANING,-- Excluded: Always Internal
    --NULLIF(TRIM(INTERNAL_EXTERNAL_FLAG::STRING), '') AS INTERNAL_EXTERNAL_FLAG,---- Excluded: Always INT
    TO_TIMESTAMP_NTZ(DATE_TO::DATE) AS DATE_TO,
    --COMMENTS::STRING AS COMMENTS, -- Excluded: Always NULL
    UPPER(TRIM(NAME::string)) AS NAME,
    TO_TIMESTAMP_NTZ(DATE_FROM::DATE) AS DATE_FROM
    --SOFT_CODING_KEYFLEX_ID::NUMBER(15,0) AS SOFT_CODING_KEYFLEX_ID, -- Excluded: Always NULL
    --LOC_INFORMATION20::STRING AS LOC_INFORMATION20, -- Excluded: Always NULL
    --LOC_INFORMATION19::STRING AS LOC_INFORMATION19, -- Excluded: Always NULL
    --LOC_INFORMATION18::STRING AS LOC_INFORMATION18, -- Excluded: Always NULL
    --LOC_INFORMATION17::STRING AS LOC_INFORMATION17, -- Excluded: Always NULL
    --LOC_INFORMATION16::STRING AS LOC_INFORMATION16 -- Excluded: Always NULL
FROM {{ref('prep_hr_organization_units_v')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORGANIZATION_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1