{{
  config(
    materialized = "view",
    alias = "cm50_po_supplier",
    schema='EBS',
    meta = {
        'table_key': 'POV_VENDOR_ID',
        'tests': {
            'null_values':{
                'columns':[
                    'RDM_POV_INVOICE_CURRENCY_CODE',
                    'RDM_POV_NATURE_OF_SUPPLIER',
                    'RDM_POV_PAYMENT_CURRENCY_CODE',
                    'RDM_POV_PAYMENT_METHOD_LOOKUP_CODE',
                    'RDM_POV_TERMS_ID'
                ]
            }
        }
    }
    
  )
}}

with raw_data_deduplicated as (

  SELECT *
  FROM {{ref('prep_cm50_po_supplier')}}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY POV_VENDOR_ID ORDER BY TO_TIMESTAMP_NTZ(POV_LAST_UPDATE_DATE) DESC) = 1 

),

raw_data_typed as (
  SELECT 
  POV_ALLOW_AWT_FLAG::string AS POV_ALLOW_AWT_FLAG
  ,POV_ALLOW_SUB_RECEIPTS_FLAG::string AS POV_ALLOW_SUB_RECEIPTS_FLAG
  ,POV_ALLOW_UNORDERED_REC_FLAG::string AS POV_ALLOW_UNORDERED_REC_FLAG
  ,POV_ALWAYS_TAKE_DISC_FLAG::string AS POV_ALWAYS_TAKE_DISC_FLAG
  ,POV_AMOUNT_INCLUDES_TAX_FLAG::string AS POV_AMOUNT_INCLUDES_TAX_FLAG
  ,POV_AP_TAX_ROUNDING_RULE::string AS POV_AP_TAX_ROUNDING_RULE
  ,POV_ATTRIBUTE1::string AS POV_ATTRIBUTE1
  ,POV_AUTO_CALCULATE_INT_FLAG::string AS POV_AUTO_CALCULATE_INT_FLAG
  ,POV_AUTO_TAX_CALC_FLAG::string AS POV_AUTO_TAX_CALC_FLAG
  ,POV_AUTO_TAX_CALC_OVERRIDE::string AS POV_AUTO_TAX_CALC_OVERRIDE
  ,POV_BANK_ACCOUNT_NAME::string AS POV_BANK_ACCOUNT_NAME
  ,POV_BANK_ACCOUNT_NUM::string AS POV_BANK_ACCOUNT_NUM
  ,POV_BANK_ACCOUNT_TYPE::string AS POV_BANK_ACCOUNT_TYPE
  ,POV_BANK_CHARGE_BEARER::string AS POV_BANK_CHARGE_BEARER
  ,POV_BANK_NUM::number(38,0) AS POV_BANK_NUM
  ,POV_BANK_NUMBER::string AS POV_BANK_NUMBER
  ,POV_BILL_TO_LOCATION_ID::number(38,0) AS POV_BILL_TO_LOCATION_ID
  ,POV_CREATED_BY::number(38,0) AS POV_CREATED_BY
  ,POV_CREATE_DEBIT_MEMO_FLAG::string AS POV_CREATE_DEBIT_MEMO_FLAG
  ,TO_TIMESTAMP_NTZ(POV_CREATION_DATE) AS POV_CREATION_DATE
  ,POV_DAYS_EARLY_RECEIPT_ALLOWED::number(38,0) AS POV_DAYS_EARLY_RECEIPT_ALLOWED
  ,POV_DAYS_LATE_RECEIPT_ALLOWED::number(38,0) AS POV_DAYS_LATE_RECEIPT_ALLOWED
  ,POV_EMPLOYEE_ID::number(38,0) AS POV_EMPLOYEE_ID
  ,POV_ENABLED_FLAG::string AS POV_ENABLED_FLAG
  ,TO_TIMESTAMP_NTZ(POV_END_DATE_ACTIVE) AS POV_END_DATE_ACTIVE
  ,POV_ENFORCE_SHIP_TO_LOC_CODE::string AS POV_ENFORCE_SHIP_TO_LOC_CODE
  ,POV_EXCLUSIVE_PAYMENT_FLAG::string AS POV_EXCLUSIVE_PAYMENT_FLAG
  ,POV_EXCLU_FREIGHT_FR_DISCOUNT::string AS POV_EXCLU_FREIGHT_FR_DISCOUNT
  ,POV_FEDERAL_REPORTABLE_FLAG::string AS POV_FEDERAL_REPORTABLE_FLAG
  ,POV_HOLD_ALL_PAYMENTS_FLAG::string AS POV_HOLD_ALL_PAYMENTS_FLAG
  ,POV_HOLD_FLAG::string AS POV_HOLD_FLAG
  ,POV_HOLD_FUTURE_PAYMENTS_FLAG::string AS POV_HOLD_FUTURE_PAYMENTS_FLAG
  ,POV_HOLD_REASON::string AS POV_HOLD_REASON
  ,POV_HOLD_UNMATCHED_INV_FLAG::string AS POV_HOLD_UNMATCHED_INV_FLAG
  ,POV_INDIVIDUAL_1099::string AS POV_INDIVIDUAL_1099
  ,POV_INSPECTION_REQUIRED_FLAG::string AS POV_INSPECTION_REQUIRED_FLAG
  ,POV_INVOICE_CURRENCY_CODE::string AS POV_INVOICE_CURRENCY_CODE
  ,POV_LAST_UPDATED_BY::number(38,0) AS POV_LAST_UPDATED_BY
  ,TO_TIMESTAMP_NTZ(POV_LAST_UPDATE_DATE) AS POV_LAST_UPDATE_DATE
  ,POV_LAST_UPDATE_LOGIN::number(38,0) AS POV_LAST_UPDATE_LOGIN
  ,POV_MATCH_OPTION::string AS POV_MATCH_OPTION
  ,POV_NATURE_OF_SUPPLIER::string AS POV_NATURE_OF_SUPPLIER
  ,POV_NUM_1099::string AS POV_NUM_1099
  ,POV_OFFSET_TAX_FLAG::string AS POV_OFFSET_TAX_FLAG
  ,POV_ONE_TIME_FLAG::string AS POV_ONE_TIME_FLAG
  ,POV_ORG_TYPE_LOOKUP_CODE::string AS POV_ORG_TYPE_LOOKUP_CODE
  ,POV_PARENT_VENDOR_ID::number(38,0) AS POV_PARENT_VENDOR_ID
  ,POV_PAYMENT_CURRENCY_CODE::string AS POV_PAYMENT_CURRENCY_CODE
  ,POV_PAYMENT_METHOD_LOOKUP_CODE::string AS POV_PAYMENT_METHOD_LOOKUP_CODE
  ,POV_PAYMENT_PRIORITY::number(38,0) AS POV_PAYMENT_PRIORITY
  ,POV_PAY_DATE_BASIS_LOOKUP_CODE::string AS POV_PAY_DATE_BASIS_LOOKUP_CODE
  ,POV_PAY_GROUP_LOOKUP_CODE::string AS POV_PAY_GROUP_LOOKUP_CODE
  ,POV_QTY_RCV_EXCEPTION_CODE::string AS POV_QTY_RCV_EXCEPTION_CODE
  ,POV_QTY_RCV_TOLERANCE::number(38,0) AS POV_QTY_RCV_TOLERANCE
  ,POV_RECEIPT_DAYS_EX_CODE::string AS POV_RECEIPT_DAYS_EX_CODE
  ,POV_RECEIPT_REQUIRED_FLAG::string AS POV_RECEIPT_REQUIRED_FLAG
  ,POV_RECEIVING_ROUTING_ID::number(38,0) AS POV_RECEIVING_ROUTING_ID
  ,POV_SET_OF_BOOKS_ID::number(38,0) AS POV_SET_OF_BOOKS_ID
  ,POV_SMALL_BUSINESS_FLAG::string AS POV_SMALL_BUSINESS_FLAG
  ,POV_START_DATE_ACTIVE::date AS POV_START_DATE_ACTIVE
  ,POV_STATE_REPORTABLE_FLAG::string AS POV_STATE_REPORTABLE_FLAG
  ,POV_SUMMARY_FLAG::string AS POV_SUMMARY_FLAG
  ,POV_TAX_REPORTING_NAME::string AS POV_TAX_REPORTING_NAME
  ,POV_TAX_VERIFICATION_DATE::date AS POV_TAX_VERIFICATION_DATE
  ,POV_TERMS_DATE_BASIS::string AS POV_TERMS_DATE_BASIS
  ,POV_TERMS_ID::number(38,0) AS POV_TERMS_ID
  ,POV_TYPE_1099::string AS POV_TYPE_1099
  ,POV_VAT_REGISTRATION_NUM::string AS POV_VAT_REGISTRATION_NUM
  ,POV_VENDOR_ID::number(38,0) AS POV_VENDOR_ID
  ,POV_VENDOR_NAME::string AS POV_VENDOR_NAME
  ,POV_VENDOR_NAME_ALT::string AS POV_VENDOR_NAME_ALT
  ,POV_VENDOR_NUMBER::number(38,0) AS POV_VENDOR_NUMBER
  ,POV_VENDOR_TYPE_LOOKUP_CODE::string AS POV_VENDOR_TYPE_LOOKUP_CODE
  ,POV_WOMEN_OWNED_FLAG::string AS POV_WOMEN_OWNED_FLAG
  ,src_system_operation::string AS src_system_operation
  from raw_data_deduplicated),
rdm_oracle_currency as 
  (SELECT distinct Business_Application_Value, Standard_Application_Value
  from {{ref('gov_referencedata_rdm')}}
  where Business_Application_Code='oracle-ebs'
  and Business_Application_Domain_Code='Currency'),
rdm_oracle_natureofsupply as 
  (SELECT distinct Business_Application_Value, Standard_Application_Value
  from {{ref('gov_referencedata_rdm')}}
  where Business_Application_Code='oracle-ebs'
  and Business_Application_Domain_Code='NatureOfSupply'),
rdm_oracle_paymentmethod as 
  (SELECT distinct Business_Application_Value, Standard_Application_Value
  from {{ref('gov_referencedata_rdm')}}
  where Business_Application_Code='oracle-ebs'
  and Business_Application_Domain_Code='PaymentMethod'),
rdm_oracle_paymentterm as 
  (SELECT distinct Business_Application_Value, Standard_Application_Value
  from {{ref('gov_referencedata_rdm')}}
  where Business_Application_Code='oracle-ebs'
  and Business_Application_Domain_Code='PaymentTerm')
SELECT 
raw_data_typed.POV_ALLOW_AWT_FLAG as POV_ALLOW_AWT_FLAG
, raw_data_typed.POV_ALLOW_SUB_RECEIPTS_FLAG as POV_ALLOW_SUB_RECEIPTS_FLAG
, raw_data_typed.POV_ALLOW_UNORDERED_REC_FLAG as POV_ALLOW_UNORDERED_REC_FLAG
, raw_data_typed.POV_ALWAYS_TAKE_DISC_FLAG as POV_ALWAYS_TAKE_DISC_FLAG
, raw_data_typed.POV_AMOUNT_INCLUDES_TAX_FLAG as POV_AMOUNT_INCLUDES_TAX_FLAG
, raw_data_typed.POV_AP_TAX_ROUNDING_RULE as POV_AP_TAX_ROUNDING_RULE
, raw_data_typed.POV_ATTRIBUTE1 as POV_ATTRIBUTE1
, raw_data_typed.POV_AUTO_CALCULATE_INT_FLAG as POV_AUTO_CALCULATE_INT_FLAG
, raw_data_typed.POV_AUTO_TAX_CALC_FLAG as POV_AUTO_TAX_CALC_FLAG
, raw_data_typed.POV_AUTO_TAX_CALC_OVERRIDE as POV_AUTO_TAX_CALC_OVERRIDE
, raw_data_typed.POV_BANK_ACCOUNT_NAME as POV_BANK_ACCOUNT_NAME
, raw_data_typed.POV_BANK_ACCOUNT_NUM as POV_BANK_ACCOUNT_NUM
, raw_data_typed.POV_BANK_ACCOUNT_TYPE as POV_BANK_ACCOUNT_TYPE
, raw_data_typed.POV_BANK_CHARGE_BEARER as POV_BANK_CHARGE_BEARER
, raw_data_typed.POV_BANK_NUM as POV_BANK_NUM
, raw_data_typed.POV_BANK_NUMBER as POV_BANK_NUMBER
, raw_data_typed.POV_BILL_TO_LOCATION_ID as POV_BILL_TO_LOCATION_ID
, raw_data_typed.POV_CREATED_BY as POV_CREATED_BY
, raw_data_typed.POV_CREATE_DEBIT_MEMO_FLAG as POV_CREATE_DEBIT_MEMO_FLAG
, raw_data_typed.POV_CREATION_DATE as POV_CREATION_DATE
, raw_data_typed.POV_DAYS_EARLY_RECEIPT_ALLOWED as POV_DAYS_EARLY_RECEIPT_ALLOWED
, raw_data_typed.POV_DAYS_LATE_RECEIPT_ALLOWED as POV_DAYS_LATE_RECEIPT_ALLOWED
, raw_data_typed.POV_EMPLOYEE_ID as POV_EMPLOYEE_ID
, raw_data_typed.POV_ENABLED_FLAG as POV_ENABLED_FLAG
, raw_data_typed.POV_END_DATE_ACTIVE as POV_END_DATE_ACTIVE
, raw_data_typed.POV_ENFORCE_SHIP_TO_LOC_CODE as POV_ENFORCE_SHIP_TO_LOC_CODE
, raw_data_typed.POV_EXCLUSIVE_PAYMENT_FLAG as POV_EXCLUSIVE_PAYMENT_FLAG
, raw_data_typed.POV_EXCLU_FREIGHT_FR_DISCOUNT as POV_EXCLU_FREIGHT_FR_DISCOUNT
, raw_data_typed.POV_FEDERAL_REPORTABLE_FLAG as POV_FEDERAL_REPORTABLE_FLAG
, raw_data_typed.POV_HOLD_ALL_PAYMENTS_FLAG as POV_HOLD_ALL_PAYMENTS_FLAG
, raw_data_typed.POV_HOLD_FLAG as POV_HOLD_FLAG
, raw_data_typed.POV_HOLD_FUTURE_PAYMENTS_FLAG as POV_HOLD_FUTURE_PAYMENTS_FLAG
, raw_data_typed.POV_HOLD_REASON as POV_HOLD_REASON
, raw_data_typed.POV_HOLD_UNMATCHED_INV_FLAG as POV_HOLD_UNMATCHED_INV_FLAG
, raw_data_typed.POV_INDIVIDUAL_1099 as POV_INDIVIDUAL_1099
, raw_data_typed.POV_INSPECTION_REQUIRED_FLAG as POV_INSPECTION_REQUIRED_FLAG
, raw_data_typed.POV_INVOICE_CURRENCY_CODE as POV_INVOICE_CURRENCY_CODE
, invoice_currency_code.Standard_Application_Value as RDM_POV_INVOICE_CURRENCY_CODE
, raw_data_typed.POV_LAST_UPDATED_BY as POV_LAST_UPDATED_BY
, raw_data_typed.POV_LAST_UPDATE_DATE as POV_LAST_UPDATE_DATE
, raw_data_typed.POV_LAST_UPDATE_LOGIN as POV_LAST_UPDATE_LOGIN
, raw_data_typed.POV_MATCH_OPTION as POV_MATCH_OPTION
, raw_data_typed.POV_NATURE_OF_SUPPLIER as POV_NATURE_OF_SUPPLIER
, rdm_oracle_natureofsupply.Standard_Application_Value as RDM_POV_NATURE_OF_SUPPLIER
, raw_data_typed.POV_NUM_1099 as POV_NUM_1099
, raw_data_typed.POV_OFFSET_TAX_FLAG as POV_OFFSET_TAX_FLAG
, raw_data_typed.POV_ONE_TIME_FLAG as POV_ONE_TIME_FLAG
, raw_data_typed.POV_ORG_TYPE_LOOKUP_CODE as POV_ORG_TYPE_LOOKUP_CODE
, raw_data_typed.POV_PARENT_VENDOR_ID as POV_PARENT_VENDOR_ID
, raw_data_typed.POV_PAYMENT_CURRENCY_CODE as POV_PAYMENT_CURRENCY_CODE
, payment_currency_code.Standard_Application_Value as RDM_POV_PAYMENT_CURRENCY_CODE
, raw_data_typed.POV_PAYMENT_METHOD_LOOKUP_CODE as POV_PAYMENT_METHOD_LOOKUP_CODE
, rdm_oracle_paymentmethod.Standard_Application_Value as RDM_POV_PAYMENT_METHOD_LOOKUP_CODE
, raw_data_typed.POV_PAYMENT_PRIORITY as POV_PAYMENT_PRIORITY
, raw_data_typed.POV_PAY_DATE_BASIS_LOOKUP_CODE as POV_PAY_DATE_BASIS_LOOKUP_CODE
, raw_data_typed.POV_PAY_GROUP_LOOKUP_CODE as POV_PAY_GROUP_LOOKUP_CODE
, raw_data_typed.POV_QTY_RCV_EXCEPTION_CODE as POV_QTY_RCV_EXCEPTION_CODE
, raw_data_typed.POV_QTY_RCV_TOLERANCE as POV_QTY_RCV_TOLERANCE
, raw_data_typed.POV_RECEIPT_DAYS_EX_CODE as POV_RECEIPT_DAYS_EX_CODE
, raw_data_typed.POV_RECEIPT_REQUIRED_FLAG as POV_RECEIPT_REQUIRED_FLAG
, raw_data_typed.POV_RECEIVING_ROUTING_ID as POV_RECEIVING_ROUTING_ID
, raw_data_typed.POV_SET_OF_BOOKS_ID as POV_SET_OF_BOOKS_ID
, raw_data_typed.POV_SMALL_BUSINESS_FLAG as POV_SMALL_BUSINESS_FLAG
, raw_data_typed.POV_START_DATE_ACTIVE as POV_START_DATE_ACTIVE
, raw_data_typed.POV_STATE_REPORTABLE_FLAG as POV_STATE_REPORTABLE_FLAG
, raw_data_typed.POV_SUMMARY_FLAG as POV_SUMMARY_FLAG
, raw_data_typed.POV_TAX_REPORTING_NAME as POV_TAX_REPORTING_NAME
, raw_data_typed.POV_TAX_VERIFICATION_DATE as POV_TAX_VERIFICATION_DATE
, raw_data_typed.POV_TERMS_DATE_BASIS as POV_TERMS_DATE_BASIS
, raw_data_typed.POV_TERMS_ID as POV_TERMS_ID
, rdm_oracle_paymentterm.Standard_Application_Value as RDM_POV_TERMS_ID
, raw_data_typed.POV_TYPE_1099 as POV_TYPE_1099
, raw_data_typed.POV_VAT_REGISTRATION_NUM as POV_VAT_REGISTRATION_NUM
, raw_data_typed.POV_VENDOR_ID as POV_VENDOR_ID
, raw_data_typed.POV_VENDOR_NAME as POV_VENDOR_NAME
, raw_data_typed.POV_VENDOR_NAME_ALT as POV_VENDOR_NAME_ALT
, raw_data_typed.POV_VENDOR_NUMBER as POV_VENDOR_NUMBER
, raw_data_typed.POV_VENDOR_TYPE_LOOKUP_CODE as POV_VENDOR_TYPE_LOOKUP_CODE
, raw_data_typed.POV_WOMEN_OWNED_FLAG as POV_WOMEN_OWNED_FLAG
, raw_data_typed.SRC_SYSTEM_OPERATION as SRC_SYSTEM_OPERATION
from raw_data_typed
left join rdm_oracle_currency as invoice_currency_code
on raw_data_typed.POV_INVOICE_CURRENCY_CODE=invoice_currency_code.Business_Application_Value
left join rdm_oracle_currency as payment_currency_code
on raw_data_typed.POV_PAYMENT_CURRENCY_CODE=payment_currency_code.Business_Application_Value
left join rdm_oracle_natureofsupply
on raw_data_typed.POV_NATURE_OF_SUPPLIER=rdm_oracle_natureofsupply.Business_Application_Value
left join rdm_oracle_paymentmethod
on raw_data_typed.POV_PAYMENT_METHOD_LOOKUP_CODE=rdm_oracle_paymentmethod.Business_Application_Value
left join rdm_oracle_paymentterm
on raw_data_typed.POV_TERMS_ID::string=rdm_oracle_paymentterm.Business_Application_Value::string
