{{
  config(
    materialized = "view",
    alias = "mtl_object_genealogy",
    schema='EBS'
  )
}}

select
OBJECT_ID::number AS OBJECT_ID
,OBJECT_TYPE::number AS OBJECT_TYPE
,PARENT_OBJECT_TYPE::number AS PARENT_OBJECT_TYPE
,PARENT_OBJECT_ID::number AS PARENT_OBJECT_ID
,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE
,LAST_UPDATED_BY::number AS LAST_UPDATED_BY
,TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE
,CREATED_BY::number AS CREATED_BY
,TO_TIMESTAMP_NTZ(START_DATE_ACTIVE::string) AS START_DATE_ACTIVE
,TO_TIMESTAMP_NTZ(END_DATE_ACTIVE::string) AS END_DATE_ACTIVE
,GENEALOGY_ORIGIN::number AS GENEALOGY_ORIGIN
--,ORIGIN_TXN_ID::number AS ORIGIN_TXN_ID                       --column entirely NULL
,GENEALOGY_TYPE::number AS GENEALOGY_TYPE
,LAST_UPDATE_LOGIN::number AS LAST_UPDATE_LOGIN

/* columns entirely NULL
,ATTRIBUTE_CATEGORY::string AS ATTRIBUTE_CATEGORY             
,ATTRIBUTE1::string AS ATTRIBUTE1
,ATTRIBUTE2::string AS ATTRIBUTE2
,ATTRIBUTE3::string AS ATTRIBUTE3
,ATTRIBUTE4::string AS ATTRIBUTE4
,ATTRIBUTE5::string AS ATTRIBUTE5
,ATTRIBUTE6::string AS ATTRIBUTE6
,ATTRIBUTE7::string AS ATTRIBUTE7
,ATTRIBUTE8::string AS ATTRIBUTE8
,ATTRIBUTE9::string AS ATTRIBUTE9
,ATTRIBUTE10::string AS ATTRIBUTE10
,ATTRIBUTE11::string AS ATTRIBUTE11
,ATTRIBUTE12::string AS ATTRIBUTE12
,ATTRIBUTE13::string AS ATTRIBUTE13
,ATTRIBUTE14::string AS ATTRIBUTE14
,ATTRIBUTE15::string AS ATTRIBUTE15
*/

,REQUEST_ID::number AS REQUEST_ID
,PROGRAM_APPLICATION_ID::number AS PROGRAM_APPLICATION_ID
,PROGRAM_ID::number AS PROGRAM_ID
,TO_TIMESTAMP_NTZ(PROGRAM_UPDATE_DATE)::string AS PROGRAM_UPDATE_DATE
--,UPDATE_TXN_ID::number AS UPDATE_TXN_ID                       --columns entirely NULL
FROM {{ref('prep_mtl_object_genealogy')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY OBJECT_ID,START_DATE_ACTIVE ,END_DATE_ACTIVE ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1