{{
  config(
    materialized = "view",
    alias = "cmg_eam_kpi_activity_target",
    schema='EBS'
  )
}}

SELECT
     TARGET_PERCENT_TO::NUMBER AS TARGET_PERCENT_TO
    ,TARGET_TIME::NUMBER AS TARGET_TIME
    ,TARGET_PERCENT_FROM::NUMBER AS TARGET_PERCENT_FROM
    ,TO_TIMESTAMP_NTZ(END_DATE_ACTIVE::string) AS END_DATE_ACTIVE
    ,TO_TIMESTAMP_NTZ(START_DATE_ACTIVE::string) AS START_DATE_ACTIVE
    ,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE
    ,TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE
    ,ORGANIZATION_ID::NUMBER AS ORGANIZATION_ID
    ,UPPER(NULLIF(TRIM(ACTIVITY_TYPE_CODE::string),'')) AS ACTIVITY_TYPE_CODE
    ,TARGET_ID::NUMBER AS TARGET_ID
FROM {{ref('prep_cmg_eam_kpi_activity_target')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TARGET_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1