{{
  config(
    materialized = "view",
    alias = "pa_segment_value_lookups",
    schema='EBS'
  )
}}

SELECT

  /*String Fields*/
  UPPER(NULLIF(TRIM(SEGMENT_VALUE_LOOKUP::string),'')) AS SEGMENT_VALUE_LOOKUP,
  UPPER(NULLIF(TRIM(SEGMENT_VALUE::string),'')) AS SEGMENT_VALUE,

  /*Numeric Fields*/
  LAST_UPDATE_LOGIN::number(15,0) AS LAST_UPDATE_LOGIN,
  CREATED_BY::number(15,0) AS CREATED_BY,    
  SEGMENT_VALUE_LOOKUP_SET_ID::number(15,0) AS SEGMENT_VALUE_LOOKUP_SET_ID,

  /*Date Fields*/
  TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE,
  TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS  LAST_UPDATE_DATE,  
  TO_TIMESTAMP_NTZ(LAST_UPDATED_BY::string) AS  LAST_UPDATED_BY
  
FROM {{ref('prep_pa_segment_value_lookups')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY SEGMENT_VALUE_LOOKUP_SET_ID,SEGMENT_VALUE_LOOKUP ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1