{{
  config(
    materialized = "view",
    alias = "bom_resource_employees",
    schema='EBS'
  )
}}

SELECT
RESOURCE_ID::number AS RESOURCE_ID,
ORGANIZATION_ID::number AS ORGANIZATION_ID,
PERSON_ID::number AS PERSON_ID,
TO_TIMESTAMP_NTZ(EFFECTIVE_START_DATE::string) AS EFFECTIVE_START_DATE,
TO_TIMESTAMP_NTZ(EFFECTIVE_END_DATE::string) AS EFFECTIVE_END_DATE,
INTERLEAVE::number AS INTERLEAVE,
TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE,
LAST_UPDATED_BY::number AS LAST_UPDATED_BY,
TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE,
CREATED_BY::number AS CREATED_BY,
--LAST_UPDATE_LOGIN::number AS LAST_UPDATE_LOGIN, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE_CATEGORY::string),'')) AS ATTRIBUTE_CATEGORY, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE1::string),'')) AS ATTRIBUTE1, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE2::string),'')) AS ATTRIBUTE2, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE3::string),'')) AS ATTRIBUTE3, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE4::string),'')) AS ATTRIBUTE4, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE5::string),'')) AS ATTRIBUTE5, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE6::string),'')) AS ATTRIBUTE6, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE7::string),'')) AS ATTRIBUTE7, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE8::string),'')) AS ATTRIBUTE8, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE9::string),'')) AS ATTRIBUTE9, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE10::string),'')) AS ATTRIBUTE10, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE11::string),'')) AS ATTRIBUTE11, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE12::string),'')) AS ATTRIBUTE12, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE13::string),'')) AS ATTRIBUTE13, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE14::string),'')) AS ATTRIBUTE14, /* Always Null */
--UPPER(NULLIF(TRIM(ATTRIBUTE15::string),'')) AS ATTRIBUTE15, /* Always Null */
--REQUEST_ID::number AS REQUEST_ID, /* Always Null */
--PROGRAM_APPLICATION_ID::number AS PROGRAM_APPLICATION_ID, /* Always Null */
--PROGRAM_ID::number AS PROGRAM_ID, /* Always Null */
--TO_TIMESTAMP_NTZ(PROGRAM_UPDATE_DATE::string) AS PROGRAM_UPDATE_DATE, /* Always Null */
INSTANCE_ID::number AS INSTANCE_ID
FROM {{ref('prep_bom_resource_employees')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY RESOURCE_ID, ORGANIZATION_ID, PERSON_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1