{{
  config(
    materialized = "view",
    alias = "cm50_pa_projects",
    schema='EBS'
  )
}}

SELECT
TO_TIMESTAMP_NTZ(PPT_START_DATE_ACTIVE::string) AS PPT_START_DATE_ACTIVE
,UPPER(NULLIF(TRIM(PPT_BURDEN_COST_FLAG::string), '')) AS PPT_BURDEN_COST_FLAG
,UPPER(NULLIF(TRIM(PPT_SERVICE_TYPE_CODE::string), '')) AS PPT_SERVICE_TYPE_CODE
,UPPER(NULLIF(TRIM(PPT_DIRECT_FLAG::string), '')) AS PPT_DIRECT_DIRECT_FLAG
,PPT_LAST_UPDATE_LOGIN::NUMBER(15,0) AS PPT_LAST_UPDATE_LOGIN
,PPT_CREATED_BY::NUMBER(15,0) AS PPT_CREATED_BY
,TO_TIMESTAMP_NTZ(PPT_CREATION_DATE::string) AS PPT_CREATION_DATE
,PPT_LAST_UPDATED_BY::NUMBER(15,0) AS PPT_LAST_UPDATED_BY
,TO_TIMESTAMP_NTZ(PPT_LAST_UPDATE_DATE::string) AS PPT_LAST_UPDATE_DATE
,UPPER(NULLIF(TRIM(PPT_PROJECT_TYPE::string), '')) AS PPT_PROJECT_TYPE
,HAO_OBJECT_VERSION_NUMBER::NUMBER(9,0) AS HAO_OBJECT_VERSION_NUMBER
,TO_TIMESTAMP_NTZ(HAO_CREATION_DATE::string) AS HAO_CREATION_DATE
,HAO_CREATED_BY::NUMBER(15,0) AS HAO_CREATED_BY
,HAO_LAST_UPDATE_LOGIN::NUMBER(15,0) AS HAO_LAST_UPDATE_LOGIN
,HAO_LAST_UPDATED_BY::NUMBER(15,0) AS HAO_LAST_UPDATED_BY
,TO_TIMESTAMP_NTZ(HAO_LAST_UPDATE_DATE::string) AS HAO_LAST_UPDATE_DATE
,UPPER(NULLIF(TRIM(HAO_CMG_YES_NO::string), '')) AS HAO_CMG_YES_NO
,UPPER(NULLIF(TRIM(HAO_PA_SRS_EMPLOYEE::string), '')) AS HAO_PA_SRS_EMPLOYEE
-- ,HAO_ATTRIBUTE8::string AS HAO_ATTRIBUTE8 -- excluded as always NULL
-- ,HAO_ATTRIBUTE7::string AS HAO_ATTRIBUTE7 -- excluded as always NULL
-- ,HAO_ATTRIBUTE6::string AS HAO_ATTRIBUTE6 -- excluded as always NULL
-- ,HAO_ATTRIBUTE5::string AS HAO_ATTRIBUTE5 -- excluded as always NULL
,UPPER(NULLIF(TRIM(HAO_CMG_PA_COGS_METHOD::string), '')) AS HAO_CMG_PA_COGS_METHOD
,UPPER(NULLIF(TRIM(HAO_CMG_PO_EMPLOYEE::string), '')) AS HAO_CMG_PO_EMPLOYEE
,UPPER(NULLIF(TRIM(HAO_ATTRIBUTE2::string), '')) AS HAO_ATTRIBUTE2
,UPPER(NULLIF(TRIM(HAO_ATTRIBUTE1::string), '')) AS HAO_ATTRIBUTE1
,UPPER(NULLIF(TRIM(HAO_ATTRIBUTE_CATEGORY::string), '')) AS HAO_ATTRIBUTE_CATEGORY
,UPPER(NULLIF(TRIM(HAO_TYPE::string), '')) AS HAO_TYPE
,UPPER(NULLIF(TRIM(HAO_INTERNAL_EXTERNAL_FLAG::string), '')) AS HAO_INTERNAL_EXTERNAL_FLAG
-- ,TO_TIMESTAMP_NTZ(HAO_DATE_TO::string) AS HAO_DATE_TO -- excluded as always NULL
,UPPER(NULLIF(TRIM(HAO_NAME::string), '')) AS HAO_NAME
,TO_TIMESTAMP_NTZ(HAO_DATE_FROM::string) AS HAO_DATE_FROM
,HAO_LOCATION_ID::NUMBER(15,0) AS HAO_LOCATION_ID
,HAO_BUSINESS_GROUP_ID::NUMBER(15,0) AS HAO_BUSINESS_GROUP_ID
,HAO_ORGANIZATION_ID::NUMBER(15,0) AS HAO_ORGANIZATION_ID
,UPPER(NULLIF(TRIM(CPS_REFERENCE5::string), '')) AS CPS_REFERENCE5
,UPPER(NULLIF(TRIM(CPS_REFERENCE4::string), '')) AS CPS_REFERENCE4
,UPPER(NULLIF(TRIM(CPS_REFERENCE3::string), '')) AS CPS_REFERENCE3
,UPPER(NULLIF(TRIM(CPS_REFERENCE2::string), '')) AS CPS_REFERENCE2
,UPPER(NULLIF(TRIM(CPS_REFERENCE1::string), '')) AS CPS_REFERENCE1
,UPPER(NULLIF(TRIM(CPS_RECEIVABLE_OWNER_CIE::string), '')) AS CPS_RECEIVABLE_OWNER_CIE
,UPPER(NULLIF(TRIM(CPS_PROJECT_OWNER_CIE::string), '')) AS CPS_PROJECT_OWNER_CIE
,UPPER(NULLIF(TRIM(CPS_CMIC_PROJECT::string), '')) AS CPS_CMIC_PROJECT
,UPPER(NULLIF(TRIM(CPS_STRUMIS_PROJECT::string), '')) AS CPS_STRUMIS_PROJECT
,UPPER(NULLIF(TRIM(CPS_REVENUE_ACCRUAL_FLAG::string), '')) AS CPS_REVENUE_ACCRUAL_FLAG
,UPPER(NULLIF(TRIM(CPS_PROJECT_ACCT_MANAGER::string), '')) AS CPS_PROJECT_ACCT_MANAGER
,TO_TIMESTAMP_NTZ(CPS_CO_LAST_COMMENT_DATE::string) AS CPS_CO_LAST_COMMENT_DATE
,UPPER(NULLIF(TRIM(CPS_CO_NOTE::string), '')) AS CPS_CO_NOTE
,TO_TIMESTAMP_NTZ(CPS_CO_LATEST_CHANGED_ORDER::string) AS CPS_CO_LATEST_CHANGED_ORDER
,CPS_CO_NO_CHARGE::NUMBER AS CPS_CO_NO_CHARGE
,CPS_CO_CANCELLED::NUMBER AS CPS_CO_CANCELLED
,CPS_CO_REJECTED::NUMBER AS CPS_CO_REJECTED
,CPS_CO_APPROVED::NUMBER AS CPS_CO_APPROVED
,CPS_CO_SUBMITTED::NUMBER AS CPS_CO_SUBMITTED
,CPS_CO_READY_TO_SUBMIT::NUMBER AS CPS_CO_READY_TO_SUBMIT
,CPS_CO_PROVISION::NUMBER AS CPS_CO_PROVISION
,CPS_CO_STATUS::NUMBER AS CPS_CO_STATUS
,UPPER(NULLIF(TRIM(CPS_KEEP_INVENTORY_FLAG::string), '')) AS CPS_KEEP_INVENTORY_FLAG
,UPPER(NULLIF(TRIM(CPS_PARENT_PROJECT::string), '')) AS CPS_PARENT_PROJECT
,TO_TIMESTAMP_NTZ(CPS_BUDGET_VALID_DATE::string) AS CPS_BUDGET_VALID_DATE
,UPPER(NULLIF(TRIM(CPS_SET_OFF_INFORMATION::string), '')) AS CPS_SET_OFF_INFORMATION
,UPPER(NULLIF(TRIM(CPS_FULLY_PRODUCED::string), '')) AS CPS_FULLY_PRODUCED
,UPPER(NULLIF(TRIM(CPS_SPM_USER::string), '')) AS CPS_SPM_USER
,UPPER(NULLIF(TRIM(CPS_BUSINESS_UNIT::string), '')) AS CPS_BUSINESS_UNIT
,UPPER(NULLIF(TRIM(CPS_CMG_TRANSFER::string), '')) AS CPS_CMG_TRANSFER
,TO_TIMESTAMP_NTZ(CPS_CLOSED_DATE::string) AS CPS_CLOSED_DATE
,UPPER(NULLIF(TRIM(CPS_STATUS::string), '')) AS CPS_STATUS
,UPPER(NULLIF(TRIM(CPS_DATABASE_NAME::string), '')) AS CPS_DATABASE_NAME
,UPPER(NULLIF(TRIM(CPS_PROJECT_DESC::string), '')) AS CPS_PROJECT_DESC
,UPPER(NULLIF(TRIM(CPS_PROJECT_NUM::string), '')) AS CPS_PROJECT_NUM
,CPS_SET_OF_BOOKS_ID::NUMBER(2,0) AS CPS_SET_OF_BOOKS_ID
,UPPER(NULLIF(TRIM(PPA_ALLOW_MULTI_PROGRAM_ROLLUP::string), '')) AS PPA_ALLOW_MULTI_PROGRAM_ROLLUP
,UPPER(NULLIF(TRIM(PPA_PROJFUNC_ATTR_FOR_AR_FLAG::string), '')) AS PPA_PROJFUNC_ATTR_FOR_AR_FLAG
,UPPER(NULLIF(TRIM(PPA_INVOICE_METHOD::string), '')) AS PPA_INVOICE_METHOD
,UPPER(NULLIF(TRIM(PPA_REVENUE_ACCRUAL_METHOD::string), '')) AS PPA_REVENUE_ACCRUAL_METHOD
,UPPER(NULLIF(TRIM(PPA_ENABLE_TOP_MTH_FLAG::string), '')) AS PPA_ENABLE_TOP_MTH_FLAG
,UPPER(NULLIF(TRIM(PPA_ENABLE_TOP_FLAG::string), '')) AS PPA_ENABLE_TOP_FLAG
,UPPER(NULLIF(TRIM(PPA_STRUCTURE_SHARING_CODE::string), '')) AS PPA_STRUCTURE_SHARING_CODE
,UPPER(NULLIF(TRIM(PPA_SYS_PROGRAM_FLAG::string), '')) AS PPA_SYS_PROGRAM_FLAG
,UPPER(NULLIF(TRIM(PPA_CINT_ELIGIBLE_FLAG::string), '')) AS PPA_CINT_ELIGIBLE_FLAG
,UPPER(NULLIF(TRIM(PPA_CAPITAL_EVENT_PROCESSING::string), '')) AS PPA_CAPITAL_EVENT_PROCESSING
,UPPER(NULLIF(TRIM(PPA_ASSET_ALLOCATION_METHOD::string), '')) AS PPA_ASSET_ALLOCATION_METHOD
,UPPER(NULLIF(TRIM(PPA_BTC_COST_BASE_REV_CODE::string), '')) AS PPA_BTC_COST_BASE_REV_CODE
,UPPER(NULLIF(TRIM(PPA_LONG_NAME::string), '')) AS PPA_LONG_NAME
,PPA_BASELINE_DURATION::NUMBER AS PPA_BASELINE_DURATION
,PPA_SCHEDULED_DURATION::NUMBER AS PPA_SCHEDULED_DURATION
,PPA_SECURITY_LEVEL::NUMBER AS PPA_SECURITY_LEVEL
,TO_TIMESTAMP_NTZ(PPA_BASELINE_AS_OF_DATE::string) AS PPA_BASELINE_AS_OF_DATE
,TO_TIMESTAMP_NTZ(PPA_SCHEDULED_AS_OF_DATE::string) AS PPA_SCHEDULED_AS_OF_DATE
,TO_TIMESTAMP_NTZ(PPA_BASELINE_FINISH_DATE::string) AS PPA_BASELINE_FINISH_DATE
,TO_TIMESTAMP_NTZ(PPA_BASELINE_START_DATE::string) AS PPA_BASELINE_START_DATE
,TO_TIMESTAMP_NTZ(PPA_TARGET_FINISH_DATE::string) AS PPA_TARGET_FINISH_DATE
,TO_TIMESTAMP_NTZ(PPA_TARGET_START_DATE::string) AS PPA_TARGET_START_DATE
,UPPER(NULLIF(TRIM(PPA_INCLUDE_GAINS_LOSSES_FLAG::string), '')) AS PPA_INCLUDE_GAINS_LOSSES_FLAG
,UPPER(NULLIF(TRIM(PPA_REVALUATE_FUNDING_FLAG::string), '')) AS PPA_REVALUATE_FUNDING_FLAG
,UPPER(NULLIF(TRIM(PPA_START_ADV_ACTION_SET_FLAG::string), '')) AS PPA_START_ADV_ACTION_SET_FLAG
,PPA_ADV_ACTION_SET_ID::NUMBER(15,0) AS PPA_ADV_ACTION_SET_ID
,UPPER(NULLIF(TRIM(PPA_RETN_ACCOUNTING_FLAG::string), '')) AS PPA_RETN_ACCOUNTING_FLAG
,PPA_RETN_BILLING_INV_FORMAT_ID::NUMBER(15,0) AS PPA_RETN_BILLING_INV_FORMAT_ID
,UPPER(NULLIF(TRIM(PPA_ASSIGN_PRECEDES_TASK::string), '')) AS PPA_ASSIGN_PRECEDES_TASK
,UPPER(NULLIF(TRIM(PPA_SPLIT_COST_FROM_BILL_FLAG::string), '')) AS PPA_SPLIT_COST_FROM_BILL_FLAG
,UPPER(NULLIF(TRIM(PPA_SPLIT_COST_FR_FLAG::string), '')) AS PPA_SPLIT_COST_FR_FLAG
,UPPER(NULLIF(TRIM(PPA_MULTI_CUR_FLAG::string), '')) AS PPA_MULTI_CUR_FLAG
,UPPER(NULLIF(TRIM(PPA_INV_BY_BILL_FLAG::string), '')) AS PPA_INV_BY_BILL_FLAG
,UPPER(NULLIF(TRIM(PPA_PROJFUNC_COST_RATE_TYPE::string), '')) AS PPA_PROJFUNC_COST_RATE_TYPE
,UPPER(NULLIF(TRIM(PPA_BASELINE_FUNDING_FLAG::string), '')) AS PPA_BASELINE_FUNDING_FLAG
,PPA_FUNDING_EXCHANGE_RATE::DOUBLE AS PPA_FUNDING_EXCHANGE_RATE
,UPPER(NULLIF(TRIM(PPA_FUNDING_RATE_TYPE::string), '')) AS PPA_FUNDING_RATE_TYPE
,UPPER(NULLIF(TRIM(PPA_FUNDING_RATE_DATE_CODE::string), '')) AS PPA_FUNDING_RATE_DATE_CODE
,PPA_PROJFUNC_BIL_EXCHANGE_RATE::DOUBLE AS PPA_PROJFUNC_BIL_EXCHANGE_RATE
,UPPER(NULLIF(TRIM(PPA_PROJFUNC_BIL_RATE_TYPE::string), '')) AS PPA_PROJFUNC_BIL_RATE_TYPE
,UPPER(NULLIF(TRIM(PPA_PROJFUNC_BIL_CODE::string), '')) AS PPA_PROJFUNC_BIL_CODE
,UPPER(NULLIF(TRIM(PPA_PROJFUNC_CURRENCY_CODE::string), '')) AS PPA_PROJFUNC_CURRENCY_CODE
,PPA_PROJECT_BIL_EXCHANGE_RATE::DOUBLE AS PPA_PROJECT_BIL_EXCHANGE_RATE
,UPPER(NULLIF(TRIM(PPA_PROJECT_BIL_RATE_TYPE::string), '')) AS PPA_PROJECT_BIL_RATE_TYPE
,UPPER(NULLIF(TRIM(PPA_PROJECT_BIL_RATE_DATE_CODE::string), '')) AS PPA_PROJECT_BIL_RATE_DATE_CODE
,UPPER(NULLIF(TRIM(PPA_REVPROC_CURRENCY_CODE::string), '')) AS PPA_REVPROC_CURRENCY_CODE
,UPPER(NULLIF(TRIM(PPA_INVPROC_CURRENCY_TYPE::string), '')) AS PPA_INVPROC_CURRENCY_TYPE
,PPA_NON_LAB_STD_BILL_RT_SCH_ID::NUMBER AS PPA_NON_LAB_STD_BILL_RT_SCH_ID
,PPA_MIN_CAND_SCORE::NUMBER AS PPA_MIN_CAND_SCORE
,PPA_SEARCH_STARTING_ORG_ID::NUMBER(15,0) AS PPA_SEARCH_STARTING_ORG_ID
,PPA_SEARCH_ORG_HIER_ID::NUMBER(15,0) AS PPA_SEARCH_ORG_HIER_ID
,PPA_SEARCH_MIN_AVAILABILITY::NUMBER AS PPA_SEARCH_MIN_AVAILABILITY
,UPPER(NULLIF(TRIM(PPA_ENABLE_AUTOMATED_SEARCH::string), '')) AS PPA_ENABLE_AUTOMATED_SEARCH
,PPA_JOB_LEVEL_MATCH_WT::NUMBER AS PPA_JOB_LEVEL_MATCH_WT
,PPA_AVAILABILITY_MATCH_WT::NUMBER AS PPA_AVAILABILITY_MATCH_WT
,PPA_COMPETENCE_MATCH_WT::NUMBER AS PPA_COMPETENCE_MATCH_WT
,PPA_EMP_BILL_RATE_SCHEDULE_ID::NUMBER AS PPA_EMP_BILL_RATE_SCHEDULE_ID
,PPA_JOB_BILL_RATE_SCHEDULE_ID::NUMBER AS PPA_JOB_BILL_RATE_SCHEDULE_ID
,PPA_RECORD_VERSION_NUMBER::NUMBER(15,0) AS PPA_RECORD_VERSION_NUMBER
,PPA_LOCATION_ID::NUMBER(15,0) AS PPA_LOCATION_ID
,PPA_COST_JOB_GROUP_ID::NUMBER(15,0) AS PPA_COST_JOB_GROUP_ID
,PPA_BILL_JOB_GROUP_ID::NUMBER(15,0) AS PPA_BILL_JOB_GROUP_ID
,UPPER(NULLIF(TRIM(PPA_CC_PROCESS_NL_FLAG::string), '')) AS PPA_CC_PROCESS_NL_FLAG
,UPPER(NULLIF(TRIM(PPA_CC_PROCESS_LABOR_FLAG::string), '')) AS PPA_CC_PROCESS_LABOR_FLAG
,UPPER(NULLIF(TRIM(PPA_PROJECT_RATE_TYPE::string), '')) AS PPA_PROJECT_RATE_TYPE
,UPPER(NULLIF(TRIM(PPA_ALLOW_CROSS_CHARGE_FLAG::string), '')) AS PPA_ALLOW_CROSS_CHARGE_FLAG
,UPPER(NULLIF(TRIM(PPA_PROJECT_CURRENCY_CODE::string), '')) AS PPA_PROJECT_CURRENCY_CODE
,UPPER(NULLIF(TRIM(PPA_RETENTION_TAX_CODE::string), '')) AS PPA_RETENTION_TAX_CODE
,UPPER(NULLIF(TRIM(PPA_OUTPUT_TAX_CODE::string), '')) AS PPA_OUTPUT_TAX_CODE
,UPPER(NULLIF(TRIM(PPA_ADW_NOTIFY_FLAG::string), '')) AS PPA_ADW_NOTIFY_FLAG
,PPA_BILLING_CYCLE_ID::NUMBER(15,0) AS PPA_BILLING_CYCLE_ID
,TO_TIMESTAMP_NTZ(PPA_SCHEDULED_FINISH_DATE::string) AS PPA_SCHEDULED_FINISH_DATE
,TO_TIMESTAMP_NTZ(PPA_SCHEDULED_START_DATE::string) AS PPA_SCHEDULED_START_DATE
,UPPER(NULLIF(TRIM(PPA_PM_PROJECT_REFERENCE::string), '')) AS PPA_PM_PROJECT_REFERENCE
,UPPER(NULLIF(TRIM(PPA_PM_PRODUCT_CODE::string), '')) AS PPA_PM_PRODUCT_CODE
,PPA_ORG_ID::NUMBER(15,0) AS PPA_ORG_ID
,TO_TIMESTAMP_NTZ(PPA_TEMPLATE_END_DATE_ACTIVE::string) AS PPA_TEMPLATE_END_DATE_ACTIVE
,TO_TIMESTAMP_NTZ(PPA_TEMPLATE_START_DATE_ACTIVE::string) AS PPA_TEMPLATE_START_DATE_ACTIVE
,PPA_CREATED_FROM_PROJECT_ID::NUMBER(15,0) AS PPA_CREATED_FROM_PROJECT_ID
,UPPER(NULLIF(TRIM(PPA_TEMPLATE_FLAG::string), '')) AS PPA_TEMPLATE_FLAG
,UPPER(NULLIF(TRIM(PPA_NON_LABOR_SCH_TYPE::string), '')) AS PPA_NON_LABOR_SCH_TYPE
,UPPER(NULLIF(TRIM(PPA_LABOR_SCH_TYPE::string), '')) AS PPA_LABOR_SCH_TYPE
,UPPER(NULLIF(TRIM(PPA_CREDIT_APPROVER::string), '')) AS PPA_CREDIT_APPROVER
,UPPER(NULLIF(TRIM(PPA_DUTY_PAYABLE_BY::string), '')) AS PPA_DUTY_PAYABLE_BY
,UPPER(NULLIF(TRIM(PPA_US_PROJECT_NO::string), '')) AS PPA_US_PROJECT_NO
,UPPER(NULLIF(TRIM(PPA_NOTICE_OWNER::string), '')) AS PPA_NOTICE_OWNER
,UPPER(NULLIF(TRIM(PPA_GL_BUSINESS_UNITS::string), '')) AS PPA_GL_BUSINESS_UNITS
,UPPER(NULLIF(TRIM(PPA_CMG_PA_US_CONVERSION::string), '')) AS PPA_CMG_PA_US_CONVERSION
,UPPER(NULLIF(TRIM(PPA_PA_COMMISSION_STATUS::string), '')) AS PPA_PA_COMMISSION_STATUS
,UPPER(NULLIF(TRIM(PPA_CUST_PROJECT_NO::string), '')) AS PPA_CUST_PROJECT_NO
,UPPER(NULLIF(TRIM(PPA_Y_NO::string), '')) AS PPA_Y_NO
,UPPER(NULLIF(TRIM(PPA_YES_NO::string), '')) AS PPA_YES_NO
,UPPER(NULLIF(TRIM(PPA_ATTRIBUTE_CATEGORY::string), '')) AS PPA_ATTRIBUTE_CATEGORY
,UPPER(NULLIF(TRIM(PPA_ENABLED_FLAG::string), '')) AS PPA_ENABLED_FLAG
,UPPER(NULLIF(TRIM(PPA_SUMMARY_FLAG::string), '')) AS PPA_SUMMARY_FLAG
,TO_TIMESTAMP_NTZ(PPA_PROGRAM_UPDATE_DATE::string) AS PPA_PROGRAM_UPDATE_DATE
,PPA_PROGRAM_APPLICATION_ID::NUMBER(15,0) AS PPA_PROGRAM_APPLICATION_ID
,PPA_PROGRAM_ID::NUMBER(15,0) AS PPA_PROGRAM_ID
,PPA_REQUEST_ID::NUMBER(15,0) AS PPA_REQUEST_ID
,PPA_UNEARNED_REVENUE_CR::NUMBER(22,5) AS PPA_UNEARNED_REVENUE_CR
,PPA_UNBILLED_RECEIVABLE_DR::NUMBER(22,5) AS PPA_UNBILLED_RECEIVABLE_DR
,UPPER(NULLIF(TRIM(PPA_PROJECT_LEVEL_FUNDING_FLAG::string), '')) AS PPA_PROJECT_LEVEL_FUNDING_FLAG
,UPPER(NULLIF(TRIM(PPA_LIMIT_TO_TXN_CONTROLS_FLAG::string), '')) AS PPA_LIMIT_TO_TXN_CONTROLS_FLAG
,PPA_NON_LABOR_BILL_RATE_ORG_ID::NUMBER(15,0) AS PPA_NON_LABOR_BILL_RATE_ORG_ID
,INITCAP(NULLIF(TRIM(PPA_NON_LABR_STD_BLL_SCHDL::string), '')) AS PPA_NON_LABR_STD_BLL_SCHDL
,PPA_LABOR_BILL_RATE_ORG_ID::NUMBER(15,0) AS PPA_LABOR_BILL_RATE_ORG_ID
,INITCAP(NULLIF(TRIM(PPA_LABOR_STD_BILL_RATE_SCHDL::string), '')) AS PPA_LABOR_STD_BILL_RATE_SCHDL
,PPA_BILLING_OFFSET::NUMBER(15,0) AS PPA_BILLING_OFFSET
,PPA_RETENTION_PERCENTAGE::NUMBER(17,2) AS PPA_RETENTION_PERCENTAGE
,PPA_RETENTION_INVOICE_ID::NUMBER(15,0) AS PPA_RETENTION_INVOICE_ID
,PPA_NON_LABOR_INVOICE_ID::NUMBER(15,0) AS PPA_NON_LABOR_INVOICE_ID
,PPA_LABOR_INVOICE_FORMAT_ID::NUMBER(15,0) AS PPA_LABOR_INVOICE_FORMAT_ID
,UPPER(NULLIF(TRIM(PPA_DISTRIBUTION_RULE::string), '')) AS PPA_DISTRIBUTION_RULE
,TO_TIMESTAMP_NTZ(PPA_CLOSED_DATE::string) AS PPA_CLOSED_DATE
,TO_TIMESTAMP_NTZ(PPA_COMPLETION_DATE::string) AS PPA_COMPLETION_DATE
,TO_TIMESTAMP_NTZ(PPA_START_DATE::string) AS PPA_START_DATE
,INITCAP(NULLIF(TRIM(PPA_DESCRIPTION::string), '')) AS PPA_DESCRIPTION
,UPPER(NULLIF(TRIM(PPA_PROJECT_STATUS_CODE::string), '')) AS PPA_PROJECT_STATUS_CODE
,UPPER(NULLIF(TRIM(PPA_PUBLIC_SECTOR_FLAG::string), '')) AS PPA_PUBLIC_SECTOR_FLAG
,PPA_CARRYING_OUT_ORG_ID::NUMBER(15,0) AS PPA_CARRYING_OUT_ORG_ID
,UPPER(NULLIF(TRIM(PPA_PROJECT_TYPE::string), '')) AS PPA_PROJECT_TYPE
,PPA_LAST_UPDATE_LOGIN::NUMBER(15,0) AS PPA_LAST_UPDATE_LOGIN
,PPA_CREATED_BY::NUMBER(15,0) AS PPA_CREATED_BY
,TO_TIMESTAMP_NTZ(PPA_CREATION_DATE::string) AS PPA_CREATION_DATE
,PPA_LAST_UPDATED_BY::NUMBER(15,0) AS PPA_LAST_UPDATED_BY
,TO_TIMESTAMP_NTZ(PPA_LAST_UPDATE_DATE::string) AS PPA_LAST_UPDATE_DATE
,UPPER(NULLIF(TRIM(PPA_PROJECT_NUMBER::string), '')) AS PPA_PROJECT_NUMBER
,UPPER(NULLIF(TRIM(PPA_PROJECT_NAME::string), '')) AS PPA_PROJECT_NAME
,PPA_PROJECT_ID::NUMBER(15,0) AS PPA_PROJECT_ID
,UPPER(NULLIF(TRIM(PER_CMG_GL_AMOUNT::string), '')) AS PER_CMG_GL_AMOUNT
,UPPER(NULLIF(TRIM(PER_USER_CODE::string), '')) AS PER_USER_CODE
,UPPER(NULLIF(TRIM(PER_SIGNATURE_FILE::string), '')) AS PER_SIGNATURE_FILE
,UPPER(NULLIF(TRIM(PER_CMG_PO_EMPLOYEE::string), '')) AS PER_CMG_PO_EMPLOYEE
-- ,PER_WORK_TELEPHONE::string AS PER_WORK_TELEPHONE -- excluded as always NULL
-- ,PER_SEX::string AS PER_SEX -- excluded as always NULL
-- ,PER_NATIONAL_IDENTIFIER::string AS PER_NATIONAL_IDENTIFIER -- excluded as always NULL
-- ,PER_MIDDLE_NAMES::string AS PER_MIDDLE_NAMES -- excluded as always NULL
,UPPER(NULLIF(TRIM(PER_FULL_NAME::string), '')) AS PER_FULL_NAME
,UPPER(NULLIF(TRIM(PER_FIRST_NAME::string), '')) AS PER_FIRST_NAME
,UPPER(NULLIF(TRIM(PER_EXPENSE_ADDRESS::string), '')) AS PER_EXPENSE_ADDRESS
,UPPER(NULLIF(TRIM(PER_EMPLOYEE_NUMBER::string), '')) AS PER_EMPLOYEE_NUMBER
,UPPER(NULLIF(TRIM(PER_EMAIL_ADDRESS::string), '')) AS PER_EMAIL_ADDRESS
-- ,TO_TIMESTAMP_NTZ(PER_DATE_OF_BIRTH::string) AS PER_DATE_OF_BIRTH -- excluded as always NULL
,UPPER(NULLIF(TRIM(PER_CURRENT_EMPLOYEE_FLAG::string), '')) AS PER_CURRENT_EMPLOYEE_FLAG
,UPPER(NULLIF(TRIM(PER_CURRENT_EMP_OR_APL_FLAG::string), '')) AS PER_CURRENT_EMP_OR_APL_FLAG
-- ,PER_COMMENT_ID::string AS PER_COMMENT_ID -- excluded as always NULL
,TO_TIMESTAMP_NTZ(PER_START_DATE::string) AS PER_START_DATE
,UPPER(NULLIF(TRIM(PER_LAST_NAME::string), '')) AS PER_LAST_NAME
,PER_PERSON_TYPE_ID::NUMBER(15,0) AS PER_PERSON_TYPE_ID
,PER_BUSINESS_GROUP_ID::NUMBER(15,0) AS PER_BUSINESS_GROUP_ID
,TO_TIMESTAMP_NTZ(PER_EFFECTIVE_END_DATE::string) AS PER_EFFECTIVE_END_DATE
,TO_TIMESTAMP_NTZ(PER_EFFECTIVE_START_DATE::string) AS PER_EFFECTIVE_START_DATE
,PER_PERSON_ID::NUMBER(10,0) AS PER_PERSON_ID
,UPPER(NULLIF(TRIM(PPT_CINT_SCH_OVERRIDE_FLAG::string), '')) AS PPT_CINT_SCH_OVERRIDE_FLAG
,UPPER(NULLIF(TRIM(PPT_CAPITAL_EVENT_PROCESSING::string), '')) AS PPT_CAPITAL_EVENT_PROCESSING
,UPPER(NULLIF(TRIM(PPT_ASSET_ALLOCATION_METHOD::string), '')) AS PPT_ASSET_ALLOCATION_METHOD
,UPPER(NULLIF(TRIM(PPT_TOTAL_BURDEN_FLAG::string), '')) AS PPT_TOTAL_BURDEN_FLAG
,UPPER(NULLIF(TRIM(PPT_INCLUDE_GAINS_LOSSES_FLAG::string), '')) AS PPT_INCLUDE_GAINS_LOSSES_FLAG
,UPPER(NULLIF(TRIM(PPT_REVALUATE_FUNDING_FLAG::string), '')) AS PPT_REVALUATE_FUNDING_FLAG
,UPPER(NULLIF(TRIM(PPT_ORG_PROJECT_FLAG::string), '')) AS PPT_ORG_PROJECT_FLAG
,UPPER(NULLIF(TRIM(PPT_PROJECT_TYPE_ID::string), '')) AS PPT_PROJECT_TYPE_ID
,UPPER(NULLIF(TRIM(PPT_BASELINE_FUNDING_FLAG::string), '')) AS PPT_BASELINE_FUNDING_FLAG
,PPT_NON_LAB_STD_BILL_RT_SCH_ID::NUMBER AS PPT_NON_LAB_STD_BILL_RT_SCH_ID
,UPPER(NULLIF(TRIM(PPT_BUDGETARY_OVERRIDE_FLAG::string), '')) AS PPT_BUDGETARY_OVERRIDE_FLAG
,PPT_EMP_BILL_RATE_SCHEDULE_ID::NUMBER AS PPT_EMP_BILL_RATE_SCHEDULE_ID
,PPT_JOB_BILL_RATE_SCHEDULE_ID::NUMBER AS PPT_JOB_BILL_RATE_SCHEDULE_ID
,UPPER(NULLIF(TRIM(PPT_UNASSIGNED_TIME::string), '')) AS PPT_UNASSIGNED_TIME
,UPPER(NULLIF(TRIM(PPT_ADMINISTRATIVE_FLAG::string), '')) AS PPT_ADMINISTRATIVE_FLAG
,PPT_COST_JOB_GROUP_ID::NUMBER(15,0) AS PPT_COST_JOB_GROUP_ID
,PPT_BILL_JOB_GROUP_ID::NUMBER(15,0) AS PPT_BILL_JOB_GROUP_ID
,UPPER(NULLIF(TRIM(PPT_CC_PRVDR_FLAG::string), '')) AS PPT_CC_PRVDR_FLAG
,UPPER(NULLIF(TRIM(PPT_OV_ASSET_ASSIGN_FLAG::string), '')) AS PPT_OV_ASSET_ASSIGN_FLAG
,UPPER(NULLIF(TRIM(PPT_VENDOR_INV_GR_CODE::string), '')) AS PPT_VENDOR_INV_GR_CODE
,UPPER(NULLIF(TRIM(PPT_DEF_START_PROJ_STATUS_CODE::string), '')) AS PPT_DEF_START_PROJ_STATUS_CODE
,UPPER(NULLIF(TRIM(PPT_ADW_NOTIFY_FLAG::string), '')) AS PPT_ADW_NOTIFY_FLAG
,PPT_BILLING_CYCLE_ID::NUMBER(15,0) AS PPT_BILLING_CYCLE_ID
,PPT_BILLING_OFFSET::NUMBER(15,0) AS PPT_BILLING_OFFSET
,UPPER(NULLIF(TRIM(PPT_ENABLE_PROJECT_WF_FLAG::string), '')) AS PPT_ENABLE_PROJECT_WF_FLAG
,UPPER(NULLIF(TRIM(PPT_ENABLE_BUDGET_WF_FLAG::string), '')) AS PPT_ENABLE_BUDGET_WF_FLAG
,UPPER(NULLIF(TRIM(PPT_BURDEN_AMT_DISPLAY_METHOD::string), '')) AS PPT_BURDEN_AMT_DISPLAY_METHOD
,PPT_ORG_ID::NUMBER(15,0) AS PPT_ORG_ID
,UPPER(NULLIF(TRIM(PPT_INTERFACE_ASSET_COST_CODE::string), '')) AS PPT_INTERFACE_ASSET_COST_CODE
,UPPER(NULLIF(TRIM(PPT_CAPITAL_COST_TYPE_CODE::string), '')) AS PPT_CAPITAL_COST_TYPE_CODE
,UPPER(NULLIF(TRIM(PPT_CIP_GROUPING_METHOD_CODE::string), '')) AS PPT_CIP_GROUPING_METHOD_CODE
,UPPER(NULLIF(TRIM(PPT_INTERFACE_FLAG::string), '')) AS PPT_INTERFACE_FLAG
,UPPER(NULLIF(TRIM(PPT_PROJECT_TYPE_CLASS_CODE::string), '')) AS PPT_PROJECT_TYPE_CLASS_CODE
,UPPER(NULLIF(TRIM(PPT_ALLOWABLE_F_CODE::string), '')) AS PPT_ALLOWABLE_F_CODE
,PPT_DEFAULT_RESOURCE_LIST_ID::NUMBER AS PPT_DEFAULT_RESOURCE_LIST_ID
,UPPER(NULLIF(TRIM(PPT_ALLOW_COST_FLAG::string), '')) AS PPT_ALLOW_COST_FLAG
,PPT_COST_BUD_LIST_ID::NUMBER AS PPT_COST_BUD_LIST_ID
,UPPER(NULLIF(TRIM(PPT_COST_BUDGET_CODE::string), '')) AS PPT_COST_BUDGET_CODE
,UPPER(NULLIF(TRIM(PPT_ALLOW_REV_FLAG::string), '')) AS PPT_ALLOW_REV_FLAG
,PPT_REV_BUDGET_LIST_ID::NUMBER AS PPT_REV_BUDGET_LIST_ID
,UPPER(NULLIF(TRIM(PPT_REV_BUDGET_CODE::string), '')) AS PPT_REV_BUDGET_CODE
,UPPER(NULLIF(TRIM(PPT_COST_SCH_OVERRIDE_FLAG::string), '')) AS PPT_COST_SCH_OVERRIDE_FLAG
,UPPER(NULLIF(TRIM(PPT_NON_LABOR_SCH_TYPE::string), '')) AS PPT_NON_LABOR_SCH_TYPE
,UPPER(NULLIF(TRIM(PPT_LABOR_SCH_TYPE::string), '')) AS PPT_LABOR_SCH_TYPE
,UPPER(NULLIF(TRIM(PPT_ATTRIBUTE2::string), '')) AS PPT_ATTRIBUTE2
,UPPER(NULLIF(TRIM(PPT_ATTRIBUTE1::string), '')) AS PPT_ATTRIBUTE1
,INITCAP(NULLIF(TRIM(PPT_DESCRIPTION::string), '')) AS PPT_DESCRIPTION
,TO_TIMESTAMP_NTZ(PPT_END_DATE_ACTIVE::string) AS PPT_END_DATE_ACTIVE
,INITCAP(NULLIF(TRIM(PPT_NON_LABOR_SCHDL::string), '')) AS PPT_NON_LABOR_SCHDL
,PPT_NON_LABOR_BILL_RATE_ORG_ID::NUMBER(15,0) AS PPT_NON_LABOR_BILL_RATE_ORG_ID
,INITCAP(NULLIF(TRIM(PPT_LABOR_STD_BILL_RATE_SCHDL::string), '')) AS PPT_LABOR_STD_BILL_RATE_SCHDL
,PPT_LABOR_BILL_RATE_ORG_ID::NUMBER(15,0) AS PPT_LABOR_BILL_RATE_ORG_ID
,PPT_NON_LABOR_INV_FOR_ID::NUMBER(15,0) AS PPT_NON_LABOR_INV_FOR_ID
,PPT_LABOR_INVOICE_FORMAT_ID::NUMBER(15,0) AS PPT_LABOR_INVOICE_FORMAT_ID
,PER_PARTY_ID::NUMBER(15,0) AS PER_PARTY_ID
,PER_OBJECT_VERSION_NUMBER::NUMBER(9,0) AS PER_OBJECT_VERSION_NUMBER
,TO_TIMESTAMP_NTZ(PER_CREATION_DATE::string) AS PER_CREATION_DATE
,PER_CREATED_BY::NUMBER(15,0) AS PER_CREATED_BY
,PER_LAST_UPDATE_LOGIN::NUMBER(15,0) AS PER_LAST_UPDATE_LOGIN
,PER_LAST_UPDATED_BY::NUMBER(15,0) AS PER_LAST_UPDATED_BY
,TO_TIMESTAMP_NTZ(PER_LAST_UPDATE_DATE::string) AS PER_LAST_UPDATE_DATE
FROM {{ref('prep_cm50_pa_projects')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY PPA_PROJECT_ID ORDER BY TO_TIMESTAMP_NTZ(PPA_LAST_UPDATE_DATE) DESC) = 1