{{
  config(
    materialized = "view",
    alias = "wip_accounting_classes",
    schema='EBS'
  )
}}

SELECT
  ORGANIZATION_ID::integer AS ORGANIZATION_ID
,CLASS_CODE::string AS CLASS_CODE
--  GLOBAL_ATTRIBUTE19::string AS GLOBAL_ATTRIBUTE19
-- ,GLOBAL_ATTRIBUTE18::string AS GLOBAL_ATTRIBUTE18
-- ,GLOBAL_ATTRIBUTE16::string AS GLOBAL_ATTRIBUTE16
-- ,GLOBAL_ATTRIBUTE15::string AS GLOBAL_ATTRIBUTE15
-- ,GLOBAL_ATTRIBUTE14::string AS GLOBAL_ATTRIBUTE14
-- ,GLOBAL_ATTRIBUTE13::string AS GLOBAL_ATTRIBUTE13
-- ,GLOBAL_ATTRIBUTE12::string AS GLOBAL_ATTRIBUTE12
-- ,GLOBAL_ATTRIBUTE11::string AS GLOBAL_ATTRIBUTE11
-- ,GLOBAL_ATTRIBUTE10::string AS GLOBAL_ATTRIBUTE10
-- ,GLOBAL_ATTRIBUTE8::string AS GLOBAL_ATTRIBUTE8
-- ,GLOBAL_ATTRIBUTE7::string AS GLOBAL_ATTRIBUTE7
-- ,GLOBAL_ATTRIBUTE6::string AS GLOBAL_ATTRIBUTE6
-- ,GLOBAL_ATTRIBUTE5::string AS GLOBAL_ATTRIBUTE5
-- ,GLOBAL_ATTRIBUTE4::string AS GLOBAL_ATTRIBUTE4
-- ,GLOBAL_ATTRIBUTE3::string AS GLOBAL_ATTRIBUTE3
-- ,GLOBAL_ATTRIBUTE2::string AS GLOBAL_ATTRIBUTE2
-- ,GLOBAL_ATTRIBUTE_CATEGORY::string AS GLOBAL_ATTRIBUTE_CATEGORY
-- ,ATTRIBUTE15::string AS ATTRIBUTE15
-- ,ATTRIBUTE14::string AS ATTRIBUTE14
-- ,ATTRIBUTE13::string AS ATTRIBUTE13
-- ,ATTRIBUTE11::string AS ATTRIBUTE11
-- ,ATTRIBUTE10::string AS ATTRIBUTE10
-- ,ATTRIBUTE9::string AS ATTRIBUTE9
-- ,ATTRIBUTE8::string AS ATTRIBUTE8
-- ,ATTRIBUTE7::string AS ATTRIBUTE7
-- ,ATTRIBUTE6::string AS ATTRIBUTE6
-- ,ATTRIBUTE5::string AS ATTRIBUTE5
-- ,ATTRIBUTE4::string AS ATTRIBUTE4
-- ,ATTRIBUTE2::string AS ATTRIBUTE2
-- ,ATTRIBUTE1::string AS ATTRIBUTE1
-- ,ATTRIBUTE_CATEGORY::string AS ATTRIBUTE_CATEGORY
-- ,STD_COST_ADJUSTMENT_ACCOUNT::string AS STD_COST_ADJUSTMENT_ACCOUNT
,OVERHEAD_VARIANCE_ACCOUNT::integer AS OVERHEAD_VARIANCE_ACCOUNT
,OVERHEAD_ACCOUNT::integer AS OVERHEAD_ACCOUNT
,OUTSIDE_PROC_VARIANCE_ACCOUNT::integer AS OUTSIDE_PROC_VARIANCE_ACCOUNT
,OUTSIDE_PROCESSING_ACCOUNT::integer AS OUTSIDE_PROCESSING_ACCOUNT
,RESOURCE_VARIANCE_ACCOUNT::integer AS RESOURCE_VARIANCE_ACCOUNT
,RESOURCE_ACCOUNT::integer AS RESOURCE_ACCOUNT
,MATERIAL_OVERHEAD_ACCOUNT::integer AS MATERIAL_OVERHEAD_ACCOUNT
,MATERIAL_VARIANCE_ACCOUNT::integer AS MATERIAL_VARIANCE_ACCOUNT
,MATERIAL_ACCOUNT::integer AS MATERIAL_ACCOUNT
,TO_TIMESTAMP_NTZ(DISABLE_DATE::string) AS DISABLE_DATE
,DESCRIPTION::string AS DESCRIPTION
,CLASS_TYPE::integer AS CLASS_TYPE
--,LAST_UPDATE_LOGIN::string AS LAST_UPDATE_LOGIN
,CREATED_BY::integer AS CREATED_BY
,TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE
,LAST_UPDATED_BY::integer AS LAST_UPDATED_BY
,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE
--,COST_TYPE_ID::string AS COST_TYPE_ID
-- ,COMPLETION_COST_SOURCE::integer AS COMPLETION_COST_SOURCE
-- ,GLOBAL_ATTRIBUTE20::string AS GLOBAL_ATTRIBUTE20
-- ,GLOBAL_ATTRIBUTE17::string AS GLOBAL_ATTRIBUTE17
-- ,GLOBAL_ATTRIBUTE1::string AS GLOBAL_ATTRIBUTE1
-- ,ATTRIBUTE3::string AS ATTRIBUTE3
-- ,GLOBAL_ATTRIBUTE9::string AS GLOBAL_ATTRIBUTE9
-- ,ATTRIBUTE12::string AS ATTRIBUTE12
-- ,EXPENSE_ACCOUNT::string AS EXPENSE_ACCOUNT
,SYSTEM_OPTION_ID::integer AS SYSTEM_OPTION_ID
-- ,BRIDGING_ACCOUNT::string AS BRIDGING_ACCOUNT
-- ,EST_SCRAP_VAR_ACCOUNT::string AS EST_SCRAP_VAR_ACCOUNT
-- ,EST_SCRAP_ACCOUNT::string AS EST_SCRAP_ACCOUNT
-- ,METADATA_FILENAME ::string AS METADATA_FILENAME 
-- ,METADATA_FILE_ROW_NUMBER::string AS METADATA_FILE_ROW_NUMBER
-- ,TO_TIMESTAMP_NTZ(METADATA_FILE_LAST_MODIFIED::string) AS METADATA_FILE_LAST_MODIFIED
-- ,TO_TIMESTAMP_NTZ(METADATA_START_SCAN_TIME  ::string) AS METADATA_START_SCAN_TIME

FROM {{ref('prep_wip_accounting_classes')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORGANIZATION_ID,CLASS_CODE ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1