 {{
  config(
    materialized = "view",
    alias = "pa_periods_all",
    schema='EBS'
  )
}}

SELECT
 PERIOD_NAME::string AS  PERIOD_NAME
, TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS  LAST_UPDATE_DATE
, LAST_UPDATED_BY::number(15,0) AS  LAST_UPDATED_BY
, TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS  CREATION_DATE
, CREATED_BY::number(15,0) AS  CREATED_BY
, LAST_UPDATE_LOGIN::number(15,0) AS  LAST_UPDATE_LOGIN
, TO_TIMESTAMP_NTZ(START_DATE::string) AS  START_DATE
, TO_TIMESTAMP_NTZ(END_DATE::string) AS  END_DATE
, STATUS::string AS  STATUS
, GL_PERIOD_NAME::string AS  GL_PERIOD_NAME
, CURRENT_PA_PERIOD_FLAG::string AS  CURRENT_PA_PERIOD_FLAG
, ORG_ID::number(15,0) AS  ORG_ID
FROM {{ref('prep_pa_periods_all')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY PERIOD_NAME,ORG_ID,CURRENT_PA_PERIOD_FLAG ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1