{{
  config(
    materialized = "view",
    alias = "mtl_serial_numbers",
    schema='EBS'
  )
}}

select
INVENTORY_ITEM_ID::NUMBER AS INVENTORY_ITEM_ID
,UPPER(TRIM(SERIAL_NUMBER::string)) AS SERIAL_NUMBER
,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE
,LAST_UPDATED_BY::NUMBER AS LAST_UPDATED_BY
,TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE
,CREATED_BY::NUMBER AS CREATED_BY
,LAST_UPDATE_LOGIN::NUMBER AS LAST_UPDATE_LOGIN
,REQUEST_ID::NUMBER AS REQUEST_ID
--,PROGRAM_APPLICATION_ID::NUMBER AS PROGRAM_APPLICATION_ID
--,PROGRAM_ID::NUMBER AS PROGRAM_ID
--,TO_TIMESTAMP_NTZ(PROGRAM_UPDATE_DATE::string) AS PROGRAM_UPDATE_DATE
,TO_TIMESTAMP_NTZ(INITIALIZATION_DATE::string) AS INITIALIZATION_DATE
,TO_TIMESTAMP_NTZ(COMPLETION_DATE::string) AS COMPLETION_DATE
--,TO_TIMESTAMP_NTZ(SHIP_DATE::string) AS SHIP_DATE
,CURRENT_STATUS::NUMBER AS CURRENT_STATUS
--,REVISION::string AS REVISION
--,LOT_NUMBER::string AS LOT_NUMBER
--,FIXED_ASSET_TAG::string AS FIXED_ASSET_TAG
--,RESERVED_ORDER_ID::NUMBER AS RESERVED_ORDER_ID
,PARENT_ITEM_ID::NUMBER AS PARENT_ITEM_ID
--,PARENT_SERIAL_NUMBER::string AS PARENT_SERIAL_NUMBER
--,ORIGINAL_WIP_ENTITY_ID::NUMBER AS ORIGINAL_WIP_ENTITY_ID
,ORIGINAL_UNIT_VENDOR_ID::NUMBER AS ORIGINAL_UNIT_VENDOR_ID
--,VENDOR_SERIAL_NUMBER::string AS VENDOR_SERIAL_NUMBER
--,VENDOR_LOT_NUMBER::string AS VENDOR_LOT_NUMBER
,LAST_TXN_SOURCE_TYPE_ID::NUMBER AS LAST_TXN_SOURCE_TYPE_ID
,LAST_TRANSACTION_ID::NUMBER AS LAST_TRANSACTION_ID
,LAST_RECEIPT_ISSUE_TYPE::NUMBER AS LAST_RECEIPT_ISSUE_TYPE
,UPPER(TRIM(LAST_TXN_SOURCE_NAME::string)) AS LAST_TXN_SOURCE_NAME
,LAST_TXN_SOURCE_ID::NUMBER AS LAST_TXN_SOURCE_ID
,UPPER(TRIM(DESCRIPTIVE_TEXT::string)) AS DESCRIPTIVE_TEXT
,CURRENT_SUBINVENTORY_CODE::string AS CURRENT_SUBINVENTORY_CODE
,CURRENT_LOCATOR_ID::NUMBER AS CURRENT_LOCATOR_ID
,CURRENT_ORGANIZATION_ID::NUMBER AS CURRENT_ORGANIZATION_ID
--,ATTRIBUTE_CATEGORY::string AS ATTRIBUTE_CATEGORY
,UPPER(TRIM(ATTRIBUTE1::string)) AS ATTRIBUTE1
,UPPER(TRIM(ATTRIBUTE2::string)) AS ATTRIBUTE2
,ATTRIBUTE3::string AS ATTRIBUTE3
,ATTRIBUTE4::string AS ATTRIBUTE4
--,ATTRIBUTE5::string AS ATTRIBUTE5
--,ATTRIBUTE6::string AS ATTRIBUTE6
--,ATTRIBUTE7::string AS ATTRIBUTE7
--,ATTRIBUTE8::string AS ATTRIBUTE8
--,ATTRIBUTE9::string AS ATTRIBUTE9
--,ATTRIBUTE10::string AS ATTRIBUTE10
--,ATTRIBUTE11::string AS ATTRIBUTE11
--,ATTRIBUTE12::string AS ATTRIBUTE12
--,ATTRIBUTE13::string AS ATTRIBUTE13
--,ATTRIBUTE14::string AS ATTRIBUTE14
--,ATTRIBUTE15::string AS ATTRIBUTE15
,GROUP_MARK_ID::NUMBER AS GROUP_MARK_ID
--,LINE_MARK_ID::NUMBER AS LINE_MARK_ID
--,LOT_LINE_MARK_ID::NUMBER AS LOT_LINE_MARK_ID
--,END_ITEM_UNIT_NUMBER::string AS END_ITEM_UNIT_NUMBER
,GEN_OBJECT_ID::NUMBER AS GEN_OBJECT_ID
--,SERIAL_ATTRIBUTE_CATEGORY::string AS SERIAL_ATTRIBUTE_CATEGORY
--,TERRITORY_CODE::string AS TERRITORY_CODE
--,TO_TIMESTAMP_NTZ(ORIGINATION_DATE::string) AS ORIGINATION_DATE
--,C_ATTRIBUTE1::string AS C_ATTRIBUTE1
-- ,C_ATTRIBUTE2::string AS C_ATTRIBUTE2
-- ,C_ATTRIBUTE3::string AS C_ATTRIBUTE3
-- ,C_ATTRIBUTE4::string AS C_ATTRIBUTE4
-- ,C_ATTRIBUTE5::string AS C_ATTRIBUTE5
-- ,C_ATTRIBUTE6::string AS C_ATTRIBUTE6
-- ,C_ATTRIBUTE7::string AS C_ATTRIBUTE7
-- ,C_ATTRIBUTE8::string AS C_ATTRIBUTE8
-- ,C_ATTRIBUTE9::string AS C_ATTRIBUTE9
-- ,C_ATTRIBUTE10::string AS C_ATTRIBUTE10
-- ,C_ATTRIBUTE11::string AS C_ATTRIBUTE11
-- ,C_ATTRIBUTE12::string AS C_ATTRIBUTE12
-- ,C_ATTRIBUTE13::string AS C_ATTRIBUTE13
-- ,C_ATTRIBUTE14::string AS C_ATTRIBUTE14
-- ,C_ATTRIBUTE15::string AS C_ATTRIBUTE15
-- ,C_ATTRIBUTE16::string AS C_ATTRIBUTE16
-- ,C_ATTRIBUTE17::string AS C_ATTRIBUTE17
-- ,C_ATTRIBUTE18::string AS C_ATTRIBUTE18
-- ,C_ATTRIBUTE19::string AS C_ATTRIBUTE19
-- ,C_ATTRIBUTE20::string AS C_ATTRIBUTE20
-- ,TO_TIMESTAMP_NTZ(D_ATTRIBUTE1::string) AS D_ATTRIBUTE1
-- ,TO_TIMESTAMP_NTZ(D_ATTRIBUTE2::string) AS D_ATTRIBUTE2
-- ,TO_TIMESTAMP_NTZ(D_ATTRIBUTE3::string) AS D_ATTRIBUTE3
-- ,TO_TIMESTAMP_NTZ(D_ATTRIBUTE4::string) AS D_ATTRIBUTE4
-- ,TO_TIMESTAMP_NTZ(D_ATTRIBUTE5::string) AS D_ATTRIBUTE5
-- ,TO_TIMESTAMP_NTZ(D_ATTRIBUTE6::string) AS D_ATTRIBUTE6
-- ,TO_TIMESTAMP_NTZ(D_ATTRIBUTE7::string) AS D_ATTRIBUTE7
-- ,TO_TIMESTAMP_NTZ(D_ATTRIBUTE8::string) AS D_ATTRIBUTE8
-- ,TO_TIMESTAMP_NTZ(D_ATTRIBUTE9::string) AS D_ATTRIBUTE9
-- ,TO_TIMESTAMP_NTZ(D_ATTRIBUTE10::string) AS D_ATTRIBUTE10
-- ,N_ATTRIBUTE1::NUMBER AS N_ATTRIBUTE1
-- ,N_ATTRIBUTE2::NUMBER AS N_ATTRIBUTE2
-- ,N_ATTRIBUTE3::NUMBER AS N_ATTRIBUTE3
-- ,N_ATTRIBUTE4::NUMBER AS N_ATTRIBUTE4
-- ,N_ATTRIBUTE5::NUMBER AS N_ATTRIBUTE5
-- ,N_ATTRIBUTE6::NUMBER AS N_ATTRIBUTE6
-- ,N_ATTRIBUTE7::NUMBER AS N_ATTRIBUTE7
-- ,N_ATTRIBUTE8::NUMBER AS N_ATTRIBUTE8
-- ,N_ATTRIBUTE9::NUMBER AS N_ATTRIBUTE9
-- ,N_ATTRIBUTE10::NUMBER AS N_ATTRIBUTE10
,STATUS_ID::NUMBER AS STATUS_ID
,COST_GROUP_ID::NUMBER AS COST_GROUP_ID
--,TIME_SINCE_NEW::NUMBER AS TIME_SINCE_NEW
--,CYCLES_SINCE_NEW::NUMBER AS CYCLES_SINCE_NEW
--,TIME_SINCE_OVERHAUL::NUMBER AS TIME_SINCE_OVERHAUL
--,CYCLES_SINCE_OVERHAUL::NUMBER AS CYCLES_SINCE_OVERHAUL
--,TIME_SINCE_REPAIR::NUMBER AS TIME_SINCE_REPAIR
--,CYCLES_SINCE_REPAIR::NUMBER AS CYCLES_SINCE_REPAIR
--,TIME_SINCE_VISIT::NUMBER AS TIME_SINCE_VISIT
-- ,CYCLES_SINCE_VISIT::NUMBER AS CYCLES_SINCE_VISIT
-- ,TIME_SINCE_MARK::NUMBER AS TIME_SINCE_MARK
-- ,CYCLES_SINCE_MARK::NUMBER AS CYCLES_SINCE_MARK
-- ,NUMBER_OF_REPAIRS::NUMBER AS NUMBER_OF_REPAIRS
-- ,LPN_ID::NUMBER AS LPN_ID
-- ,INSPECTION_STATUS::NUMBER AS INSPECTION_STATUS
,PREVIOUS_STATUS::string AS PREVIOUS_STATUS
--,LPN_TXN_ERROR_FLAG::string AS LPN_TXN_ERROR_FLAG
,UPPER(TRIM(WIP_ACCOUNTING_CLASS_CODE::string)) AS WIP_ACCOUNTING_CLASS_CODE
,MAINTAINABLE_FLAG::string AS MAINTAINABLE_FLAG
,OWNING_DEPARTMENT_ID::NUMBER AS OWNING_DEPARTMENT_ID
,NETWORK_ASSET_FLAG::string AS NETWORK_ASSET_FLAG
,FA_ASSET_ID::NUMBER AS FA_ASSET_ID
--,PN_LOCATION_ID::NUMBER AS PN_LOCATION_ID
,EAM_LOCATION_ID::NUMBER AS EAM_LOCATION_ID
,ASSET_CRITICALITY_CODE::string AS ASSET_CRITICALITY_CODE
--,CATEGORY_ID::NUMBER AS CATEGORY_ID
--,PROD_ORGANIZATION_ID::NUMBER AS PROD_ORGANIZATION_ID
--,EQUIPMENT_ITEM_ID::NUMBER AS EQUIPMENT_ITEM_ID
--,EQP_SERIAL_NUMBER::string AS EQP_SERIAL_NUMBER
,ORGANIZATION_TYPE::NUMBER AS ORGANIZATION_TYPE
,OWNING_ORGANIZATION_ID::NUMBER AS OWNING_ORGANIZATION_ID
,OWNING_TP_TYPE::NUMBER AS OWNING_TP_TYPE
,PLANNING_ORGANIZATION_ID::NUMBER AS PLANNING_ORGANIZATION_ID
,PLANNING_TP_TYPE::NUMBER AS PLANNING_TP_TYPE
--,ONHAND_QUANTITIES_ID::NUMBER AS ONHAND_QUANTITIES_ID
--,WIP_ENTITY_ID::NUMBER AS WIP_ENTITY_ID
--,OPERATION_SEQ_NUM::NUMBER AS OPERATION_SEQ_NUM
--,INTRAOPERATION_STEP_TYPE::NUMBER AS INTRAOPERATION_STEP_TYPE
,EAM_INSTANTIATION_FLAG::string AS EAM_INSTANTIATION_FLAG
--,EAM_LINEAR_LOCATION_ID::NUMBER AS EAM_LINEAR_LOCATION_ID
FROM {{ref('prep_mtl_serial_numbers')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY INVENTORY_ITEM_ID,SERIAL_NUMBER ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1