{{
  config(
    materialized = "view",
    alias = "hz_cust_accounts",
    schema='EBS'
  )
}}



SELECT CUST_ACCOUNT_ID::NUMBER(15,0) AS CUST_ACCOUNT_ID
      ,PARTY_ID::NUMBER(15,0) AS PARTY_ID
      ,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::STRING) AS LAST_UPDATE_DATE
      ,NULLIF(TRIM(ACCOUNT_NUMBER::string), '') AS ACCOUNT_NUMBER
      ,LAST_UPDATED_BY::NUMBER(15,0) AS LAST_UPDATED_BY
      ,TO_TIMESTAMP_NTZ(CREATION_DATE::STRING) AS CREATION_DATE
      ,CREATED_BY::NUMBER(15,0) AS CREATED_BY
      ,LAST_UPDATE_LOGIN::NUMBER(15,0) AS LAST_UPDATE_LOGIN
      ,REQUEST_ID::NUMBER(15,0) AS REQUEST_ID
      ,PROGRAM_APPLICATION_ID::NUMBER(15,0) AS PROGRAM_APPLICATION_ID
      ,PROGRAM_ID::NUMBER(15,0) AS PROGRAM_ID
      ,TO_TIMESTAMP_NTZ(PROGRAM_UPDATE_DATE::STRING) AS PROGRAM_UPDATE_DATE
      --,TO_TIMESTAMP_NTZ(WH_UPDATE_DATE::STRING) AS WH_UPDATE_DATE --Excluded always NULL
      --,NULLIF(TRIM(ATTRIBUTE_CATEGORY::string), '') AS ATTRIBUTE_CATEGORY  --Excluded always NULL
      ,NULLIF(TRIM(ATTRIBUTE1::string), '') AS ATTRIBUTE1
      ,CASE
        WHEN LENGTH(ATTRIBUTE2::STRING) = 10 AND POSITION('-', ATTRIBUTE2::STRING) = 3
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE2::STRING, 'DD-MM-YYYY')
        WHEN LENGTH(ATTRIBUTE2::STRING) = 10 AND POSITION('-', ATTRIBUTE2::STRING) = 5
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE2::STRING, 'YYYY-MM-DD')
        ELSE NULL
    END AS ATTRIBUTE2
      ,CASE
        WHEN LENGTH(ATTRIBUTE3::STRING) = 10 AND POSITION('-', ATTRIBUTE3::STRING) = 3
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE3::STRING, 'DD-MM-YYYY')
        WHEN LENGTH(ATTRIBUTE3::STRING) = 10 AND POSITION('-', ATTRIBUTE3::STRING) = 5
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE3::STRING, 'YYYY-MM-DD')
        ELSE NULL
    END AS ATTRIBUTE3
      ,CASE
        WHEN LENGTH(ATTRIBUTE4::STRING) = 10 AND POSITION('-', ATTRIBUTE4::STRING) = 3
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE4::STRING, 'DD-MM-YYYY')
        WHEN LENGTH(ATTRIBUTE4::STRING) = 10 AND POSITION('-', ATTRIBUTE4::STRING) = 5
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE4::STRING, 'YYYY-MM-DD')
        ELSE NULL
    END AS ATTRIBUTE4
      ,CASE
        WHEN LENGTH(ATTRIBUTE5::STRING) = 10 AND POSITION('-', ATTRIBUTE5::STRING) = 3
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE5::STRING, 'DD-MM-YYYY')
        WHEN LENGTH(ATTRIBUTE5::STRING) = 10 AND POSITION('-', ATTRIBUTE5::STRING) = 5
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE5::STRING, 'YYYY-MM-DD')
        ELSE NULL
    END AS ATTRIBUTE5
      ,UPPER(NULLIF(TRIM(ATTRIBUTE6::string), '')) AS ATTRIBUTE6
      ,NULLIF(TRIM(ATTRIBUTE7::string), '') AS ATTRIBUTE7
      ,NULLIF(TRIM(ATTRIBUTE8::string), '') AS ATTRIBUTE8
      ,INITCAP(NULLIF(TRIM(ATTRIBUTE9::string), '')) AS ATTRIBUTE9
      --,NULLIF(TRIM(ATTRIBUTE10::string), '') AS ATTRIBUTE10 --Excluded always NULL
      --,NULLIF(TRIM(ATTRIBUTE11::string), '') AS ATTRIBUTE11 --Excluded always NULL
      --,NULLIF(TRIM(ATTRIBUTE12::string), '') AS ATTRIBUTE12 --Excluded always NULL
      --,NULLIF(TRIM(ATTRIBUTE13::string), '') AS ATTRIBUTE13 --Excluded always NULL
      --,NULLIF(TRIM(ATTRIBUTE14::string), '') AS ATTRIBUTE14 --Excluded always NULL
      --,NULLIF(TRIM(ATTRIBUTE15::string), '') AS ATTRIBUTE15 --Excluded always NULL
      --,NULLIF(TRIM(ATTRIBUTE16::string), '') AS ATTRIBUTE16 --Excluded always NULL
      --,NULLIF(TRIM(ATTRIBUTE17::string), '') AS ATTRIBUTE17--Excluded always NULL
      --,NULLIF(TRIM(ATTRIBUTE18::string), '') AS ATTRIBUTE18--Excluded always NULL
      --,NULLIF(TRIM(ATTRIBUTE19::string), '') AS ATTRIBUTE19--Excluded always NULL
      --,NULLIF(TRIM(ATTRIBUTE20::string), '') AS ATTRIBUTE20--Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE_CATEGORY::string), '') AS GLOBAL_ATTRIBUTE_CATEGORY --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE1::string), '') AS GLOBAL_ATTRIBUTE1 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE2::string), '') AS GLOBAL_ATTRIBUTE2 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE3::string), '') AS GLOBAL_ATTRIBUTE3 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE4::string), '') AS GLOBAL_ATTRIBUTE4 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE5::string), '') AS GLOBAL_ATTRIBUTE5 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE6::string), '') AS GLOBAL_ATTRIBUTE6 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE7::string), '') AS GLOBAL_ATTRIBUTE7 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE8::string), '') AS GLOBAL_ATTRIBUTE8 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE9::string), '') AS GLOBAL_ATTRIBUTE9 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE10::string), '') AS GLOBAL_ATTRIBUTE10 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE11::string), '') AS GLOBAL_ATTRIBUTE11 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE12::string), '') AS GLOBAL_ATTRIBUTE12 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE13::string), '') AS GLOBAL_ATTRIBUTE13 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE14::string), '') AS GLOBAL_ATTRIBUTE14 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE15::string), '') AS GLOBAL_ATTRIBUTE15 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE16::string), '') AS GLOBAL_ATTRIBUTE16 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE17::string), '') AS GLOBAL_ATTRIBUTE17 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE18::string), '') AS GLOBAL_ATTRIBUTE18 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE19::string), '') AS GLOBAL_ATTRIBUTE19 --Excluded always NULL
      --,NULLIF(TRIM(GLOBAL_ATTRIBUTE20::string), '') AS GLOBAL_ATTRIBUTE20 --Excluded always NULL
      ,UPPER(NULLIF(TRIM(ORIG_SYSTEM_REFERENCE::string), '')) AS ORIG_SYSTEM_REFERENCE
      ,NULLIF(TRIM(STATUS::string), '') AS STATUS
      --,NULLIF(TRIM(CUSTOMER_TYPE::string), '') AS CUSTOMER_TYPE --Single Value Excluded
      ,NULLIF(TRIM(CUSTOMER_CLASS_CODE::string), '') AS CUSTOMER_CLASS_CODE
      --,PRIMARY_SALESREP_ID::NUMBER(15,0) AS PRIMARY_SALESREP_ID --Excluded always NULL
      --,NULLIF(TRIM(SALES_CHANNEL_CODE::string), '') AS SALES_CHANNEL_CODE --Excluded always NULL
      --,ORDER_TYPE_ID::NUMBER(15,0) AS ORDER_TYPE_ID --Excluded always NULL
      --,PRICE_LIST_ID::NUMBER(15,0) AS PRICE_LIST_ID --Excluded always NULL
      --,NULLIF(TRIM(SUBCATEGORY_CODE::string), '') AS SUBCATEGORY_CODE --Excluded always NULL
      --,NULLIF(TRIM(TAX_CODE::string), '') AS TAX_CODE --Excluded always NULL
      --,NULLIF(TRIM(FOB_POINT::string), '') AS FOB_POINT --Excluded always NULL
      --,NULLIF(TRIM(FREIGHT_TERM::string), '') AS FREIGHT_TERM --Excluded always NULL
      --,NULLIF(TRIM(SHIP_PARTIAL::string), '') AS SHIP_PARTIAL --Excluded always NULL
      --,NULLIF(TRIM(SHIP_VIA::string), '') AS SHIP_VIA --Excluded always NULL
      --,WAREHOUSE_ID::NUMBER(15,0) AS WAREHOUSE_ID --Excluded always NULL
      ,PAYMENT_TERM_ID::NUMBER(15,0) AS PAYMENT_TERM_ID
      --,NULLIF(TRIM(TAX_HEADER_LEVEL_FLAG::string), '') AS TAX_HEADER_LEVEL_FLAG --Excluded always NULL
      --,NULLIF(TRIM(TAX_ROUNDING_RULE::string), '') AS TAX_ROUNDING_RULE --Excluded always NULL
      --,NULLIF(TRIM(COTERMINATE_DAY_MONTH::string), '') AS COTERMINATE_DAY_MONTH --Excluded always NULL
      --,PRIMARY_SPECIALIST_ID::NUMBER(15,0) AS PRICE_LIST_ID --Excluded always NULL
      --,SECONDARY_SPECIALIST_ID::NUMBER(15,0) AS SECONDARY_SPECIALIST_ID --Excluded always NULL
      --,NULLIF(TRIM(ACCOUNT_LIABLE_FLAG::string), '') AS ACCOUNT_LIABLE_FLAG --Excluded always NULL
      --,RESTRICTION_LIMIT_AMOUNT::INTEGER AS RESTRICTION_LIMIT_AMOUNT --Excluded always NULL
      --,CURRENT_BALANCE::INTEGER AS CURRENT_BALANCE --Excluded always NULL
      --,NULLIF(TRIM(PASSWORD_TEXT::string), '') AS PASSWORD_TEXT --Excluded always NULL
      --,NULLIF(TRIM(HIGH_PRIORITY_INDICATOR::string), '') AS HIGH_PRIORITY_INDICATOR --Excluded always NULL
      --,TO_TIMESTAMP_NTZ(ACCOUNT_ESTABLISHED_DATE::STRING) AS ACCOUNT_ESTABLISHED_DATE --Excluded always NULL
      --,TO_TIMESTAMP_NTZ(ACCOUNT_TERMINATION_DATE::STRING) AS ACCOUNT_TERMINATION_DATE --Excluded always NULL
      --,TO_TIMESTAMP_NTZ(ACCOUNT_ACTIVATION_DATE::STRING) AS ACCOUNT_ACTIVATION_DATE --Excluded always NULL
      --,NULLIF(TRIM(CREDIT_CLASSIFICATION_CODE::string), '') AS CREDIT_CLASSIFICATION_CODE --Excluded always NULL
      --,NULLIF(TRIM(DEPARTMENT::string), '') AS DEPARTMENT --Excluded always NULL
      --,NULLIF(TRIM(MAJOR_ACCOUNT_NUMBER::string), '') AS MAJOR_ACCOUNT_NUMBER --Excluded always NULL
      --,NULLIF(TRIM(HOTWATCH_SERVICE_FLAG::string), '') AS HOTWATCH_SERVICE_FLAG --Excluded always NULL
      --,NULLIF(TRIM(HOTWATCH_SVC_BAL_IND::string), '') AS HOTWATCH_SVC_BAL_IND --Excluded always NULL
      --,TO_TIMESTAMP_NTZ(HELD_BILL_EXPIRATION_DATE::STRING) AS HELD_BILL_EXPIRATION_DATE --Excluded always NULL
      --,NULLIF(TRIM(HOLD_BILL_FLAG::string), '') AS HOLD_BILL_FLAG --Excluded always NULL
      --,NULLIF(TRIM(HIGH_PRIORITY_REMARKS::string), '') AS HIGH_PRIORITY_REMARKS --Excluded always NULL
      --,TO_TIMESTAMP_NTZ(PO_EFFECTIVE_DATE::STRING) AS PO_EFFECTIVE_DATE --Excluded always NULL
      --,TO_TIMESTAMP_NTZ(PO_EXPIRATION_DATE::STRING) AS PO_EXPIRATION_DATE --Excluded always NULL
      --,NULLIF(TRIM(REALTIME_RATE_FLAG::string), '') AS REALTIME_RATE_FLAG --Excluded always NULL
      --,NULLIF(TRIM(SINGLE_USER_FLAG::string), '') AS SINGLE_USER_FLAG --Excluded always NULL
      --,NULLIF(TRIM(WATCH_ACCOUNT_FLAG::string), '') AS WATCH_ACCOUNT_FLAG --Excluded always NULL
      --,NULLIF(TRIM(WATCH_BALANCE_INDICATOR::string), '') AS WATCH_BALANCE_INDICATOR --Excluded always NULL
      --,NULLIF(TRIM(GEO_CODE::string), '') AS GEO_CODE --Excluded always NULL
      --,NULLIF(TRIM(ACCT_LIFE_CYCLE_STATUS::string), '') AS ACCT_LIFE_CYCLE_STATUS --Excluded always NULL
      --,NULLIF(TRIM(ACCOUNT_NAME::string), '') AS ACCOUNT_NAME --Excluded always NULL
      --,NULLIF(TRIM(DEPOSIT_REFUND_METHOD::string), '') AS DEPOSIT_REFUND_METHOD --Excluded always NULL
      --,NULLIF(TRIM(DORMANT_ACCOUNT_FLAG::string), '') AS DORMANT_ACCOUNT_FLAG --Excluded always NULL
      --,NULLIF(TRIM(NPA_NUMBER::string), '') AS NPA_NUMBER --Excluded always NULL
      --,PIN_NUMBER::NUMBER(15,0) AS PIN_NUMBER --Excluded always NULL
      --,TO_TIMESTAMP_NTZ(SUSPENSION_DATE::STRING) AS SUSPENSION_DATE --Excluded always NULL
      --,WRITE_OFF_ADJUSTMENT_AMOUNT::INTEGER AS WRITE_OFF_ADJUSTMENT_AMOUNT --Excluded always NULL
      --,WRITE_OFF_PAYMENT_AMOUNT::INTEGER AS WRITE_OFF_PAYMENT_AMOUNT --Excluded always NULL
      --,WRITE_OFF_AMOUNT::INTEGER AS WRITE_OFF_AMOUNT --Excluded always NULL
      --,NULLIF(TRIM(SOURCE_CODE::string), '') AS SOURCE_CODE --Excluded always NULL
      --,NULLIF(TRIM(COMPETITOR_TYPE::string), '') AS COMPETITOR_TYPE --Excluded always NULL
      --,NULLIF(TRIM(COMMENTS::string), '') AS COMMENTS --Excluded always NULL
      --,DATES_NEGATIVE_TOLERANCE::INTEGER AS DATES_NEGATIVE_TOLERANCE --Excluded always NULL
      --,DATES_POSITIVE_TOLERANCE::INTEGER AS DATES_POSITIVE_TOLERANCE --Excluded always NULL
      --,NULLIF(TRIM(DATE_TYPE_PREFERENCE::string), '') AS DATE_TYPE_PREFERENCE --Excluded always NULL
      --,OVER_SHIPMENT_TOLERANCE::INTEGER AS OVER_SHIPMENT_TOLERANCE --Excluded always NULL
      --,UNDER_SHIPMENT_TOLERANCE::INTEGER AS UNDER_SHIPMENT_TOLERANCE --Excluded always NULL
      --,OVER_RETURN_TOLERANCE::INTEGER AS OVER_RETURN_TOLERANCE --Excluded always NULL
      --,UNDER_RETURN_TOLERANCE::INTEGER AS UNDER_RETURN_TOLERANCE --Excluded always NULL
      --,NULLIF(TRIM(ITEM_CROSS_REF_PREF::string), '') AS ITEM_CROSS_REF_PREF --Excluded always NULL
      ,NULLIF(TRIM(SHIP_SETS_INCLUDE_LINES_FLAG::string), '') AS SHIP_SETS_INCLUDE_LINES_FLAG
      --,NULLIF(TRIM(ARRIVALSETS_INCLUDE_LINES_FLAG::string), '') AS ARRIVALSETS_INCLUDE_LINES_FLAG --Excluded always NULL
      --,NULLIF(TRIM(SCHED_DATE_PUSH_FLAG::string), '') AS SCHED_DATE_PUSH_FLAG --Excluded always NULL
      --,NULLIF(TRIM(INVOICE_QUANTITY_RULE::string), '') AS INVOICE_QUANTITY_RULE --Excluded always NULL
      --,NULLIF(TRIM(PRICING_EVENT::string), '') AS PRICING_EVENT --Excluded always NULL
      ,ACCOUNT_REPLICATION_KEY::NUMBER(15,0) AS ACCOUNT_REPLICATION_KEY --Excluded always NULL      
      --,TO_TIMESTAMP_NTZ(STATUS_UPDATE_DATE::STRING) AS STATUS_UPDATE_DATE --Excluded always NULL
      --,NULLIF(TRIM(AUTOPAY_FLAG::string), '') AS AUTOPAY_FLAG --Excluded always NULL
      --,NULLIF(TRIM(NOTIFY_FLAG::string), '') AS NOTIFY_FLAG --Excluded always NULL
      --,LAST_BATCH_ID::INTEGER AS LAST_BATCH_ID --Excluded always NULL
      ,OBJECT_VERSION_NUMBER::INTEGER AS OBJECT_VERSION_NUMBER
      ,NULLIF(TRIM(CREATED_BY_MODULE::string), '') AS CREATED_BY_MODULE
      ,APPLICATION_ID::INTEGER AS APPLICATION_ID --Excluded always NULL
      --,SELLING_PARTY_ID::NUMBER(15,0) AS SELLING_PARTY_ID --Excluded always NULL
      --,ORG_ID::NUMBER(15,0) AS ORG_ID --Excluded always NULL
FROM {{ref('prep_hz_cust_accounts')}}
 QUALIFY ROW_NUMBER() OVER (PARTITION BY CUST_ACCOUNT_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1