{{
  config(
    materialized = "view",
    alias = "pa_expenditure_types",
    schema='EBS'
  )
}}

SELECT
 UPPER(NULLIF(TRIM(EXPENDITURE_TYPE::string), '')) AS EXPENDITURE_TYPE
,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE
,LAST_UPDATED_BY::NUMBER(15,0) AS LAST_UPDATED_BY
,TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE
,CREATED_BY::NUMBER(15,0) AS CREATED_BY
,LAST_UPDATE_LOGIN::NUMBER(15,0) AS LAST_UPDATE_LOGIN
,UPPER(NULLIF(TRIM(EXPENDITURE_CATEGORY::string), '')) AS EXPENDITURE_CATEGORY
,UPPER(NULLIF(TRIM(REVENUE_CATEGORY_CODE::string), '')) AS REVENUE_CATEGORY_CODE
,UPPER(NULLIF(TRIM(SYSTEM_LINKAGE_FUNCTION::string), '')) AS SYSTEM_LINKAGE_FUNCTION
,UPPER(NULLIF(TRIM(UNIT_OF_MEASURE::string), '')) AS UNIT_OF_MEASURE
,TO_TIMESTAMP_NTZ(START_DATE_ACTIVE::string) AS START_DATE_ACTIVE
,UPPER(NULLIF(TRIM(COST_RATE_FLAG::string), '')) AS COST_RATE_FLAG
,TO_TIMESTAMP_NTZ(END_DATE_ACTIVE::string) AS END_DATE_ACTIVE
,INITCAP(NULLIF(TRIM(DESCRIPTION::string), '')) AS DESCRIPTION
--,NULLIF(TRIM(ATTRIBUTE_CATEGORY::string), '') AS ATTRIBUTE_CATEGORY
,UPPER(NULLIF(TRIM(ATTRIBUTE1::string), '')) AS ATTRIBUTE1
--,NULLIF(TRIM(ATTRIBUTE2::string), '') AS ATTRIBUTE2
,UPPER(NULLIF(TRIM(ATTRIBUTE3::string), '')) AS ATTRIBUTE3
,UPPER(NULLIF(TRIM(ATTRIBUTE4::string), '')) AS ATTRIBUTE4
,UPPER(NULLIF(TRIM(ATTRIBUTE5::string), '')) AS ATTRIBUTE5
,UPPER(NULLIF(TRIM(ATTRIBUTE6::string), '')) AS ATTRIBUTE6
--,UPPER(NULLIF(TRIM(ATTRIBUTE7::string), '')) AS ATTRIBUTE7
--,UPPER(NULLIF(TRIM(ATTRIBUTE8::string), '')) AS ATTRIBUTE8
--,UPPER(NULLIF(TRIM(ATTRIBUTE9::string), '')) AS ATTRIBUTE9
--,UPPER(NULLIF(TRIM(ATTRIBUTE10::string), '')) AS ATTRIBUTE10
--,UPPER(NULLIF(TRIM(ATTRIBUTE11::string), '')) AS ATTRIBUTE11
--,UPPER(NULLIF(TRIM(ATTRIBUTE12::string), '')) AS ATTRIBUTE12
--,UPPER(NULLIF(TRIM(ATTRIBUTE13::string), '')) AS ATTRIBUTE13
--,UPPER(NULLIF(TRIM(ATTRIBUTE14::string), '')) AS ATTRIBUTE14
--,UPPER(NULLIF(TRIM(ATTRIBUTE15::string), '')) AS ATTRIBUTE15
,UPPER(NULLIF(TRIM(ADW_NOTIFY_FLAG::string), '')) AS ADW_NOTIFY_FLAG
,EXPENDITURE_TYPE_ID::NUMBER(15,0) AS EXPENDITURE_TYPE_ID
FROM {{ref('prep_pa_expenditure_types')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY EXPENDITURE_TYPE_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1