{{
  config(
    materialized = "view",
    alias = "bom_departments",
    schema='EBS'
  )
}}

SELECT

DEPARTMENT_ID::number AS DEPARTMENT_ID,
UPPER(NULLIF(TRIM(DEPARTMENT_CODE::string),'')) AS DEPARTMENT_CODE,
ORGANIZATION_ID::number AS ORGANIZATION_ID,

TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE,
LAST_UPDATED_BY::number AS LAST_UPDATED_BY,

TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE,
CREATED_BY::number AS CREATED_BY,
LAST_UPDATE_LOGIN::number AS LAST_UPDATE_LOGIN,
INITCAP(NULLIF(TRIM(DESCRIPTION::string),'')) AS DESCRIPTION,

TO_TIMESTAMP_NTZ(DISABLE_DATE::string) AS DISABLE_DATE,

/* Always Null */
--DEPARTMENT_CLASS_CODE::string AS DEPARTMENT_CLASS_CODE,
--ATTRIBUTE_CATEGORY::string AS ATTRIBUTE_CATEGORY,
-- ATTRIBUTE1::string AS ATTRIBUTE1,
-- ATTRIBUTE2::string AS ATTRIBUTE2,
-- ATTRIBUTE3::string AS ATTRIBUTE3,
-- ATTRIBUTE4::string AS ATTRIBUTE4,
-- ATTRIBUTE5::string AS ATTRIBUTE5,
-- ATTRIBUTE6::string AS ATTRIBUTE6,
-- ATTRIBUTE7::string AS ATTRIBUTE7,
-- ATTRIBUTE8::string AS ATTRIBUTE8,
-- ATTRIBUTE9::string AS ATTRIBUTE9,
-- ATTRIBUTE10::string AS ATTRIBUTE10,
-- ATTRIBUTE11::string AS ATTRIBUTE11,
-- ATTRIBUTE12::string AS ATTRIBUTE12,
-- ATTRIBUTE13::string AS ATTRIBUTE13,
-- ATTRIBUTE14::string AS ATTRIBUTE14,
-- ATTRIBUTE15::string AS ATTRIBUTE15,
-- REQUEST_ID::number AS REQUEST_ID,
-- PROGRAM_APPLICATION_ID::number AS PROGRAM_APPLICATION_ID,
-- PROGRAM_ID::number AS PROGRAM_ID,
-- TO_TIMESTAMP_NTZ(PROGRAM_UPDATE_DATE::string) AS PROGRAM_UPDATE_DATE,
LOCATION_ID::number AS LOCATION_ID,
PA_EXPENDITURE_ORG_ID::number AS PA_EXPENDITURE_ORG_ID,
--SCRAP_ACCOUNT::number AS SCRAP_ACCOUNT, /* Always Null */
--EST_ABSORPTION_ACCOUNT::number AS EST_ABSORPTION_ACCOUNT,  /* Always Null */
UPPER(NULLIF(TRIM(MAINT_COST_CATEGORY::string),'')) AS MAINT_COST_CATEGORY

FROM {{ref('prep_bom_departments')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY DEPARTMENT_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1