{{
  config(
    materialized = "view",
    alias = "pa_tasks",
    schema='EBS'
  )
}}


SELECT
-- CINT_STOP_DATE::string AS CINT_STOP_DATE
 CINT_ELIGIBLE_FLAG::string AS CINT_ELIGIBLE_FLAG
,RETIREMENT_COST_FLAG::string AS RETIREMENT_COST_FLAG
,LONG_TASK_NAME::string AS LONG_TASK_NAME
--,NON_LABOR_DISC_REASON_CODE::string AS NON_LABOR_DISC_REASON_CODE
--,LABOR_DISC_REASON_CODE::string AS LABOR_DISC_REASON_CODE
,NON_LAB_STD_BILL_RT_SCH_ID::string AS NON_LAB_STD_BILL_RT_SCH_ID
--,TASKFUNC_COST_RATE_DATE::string AS TASKFUNC_COST_RATE_DATE
--,TASKFUNC_COST_RATE_TYPE::string AS TASKFUNC_COST_RATE_TYPE
--,EMP_BILL_RATE_SCHEDULE_ID::string AS EMP_BILL_RATE_SCHEDULE_ID
,JOB_BILL_RATE_SCHEDULE_ID::string AS JOB_BILL_RATE_SCHEDULE_ID
,RECORD_VERSION_NUMBER::string AS RECORD_VERSION_NUMBER
--,WORK_TYPE_ID::string AS WORK_TYPE_ID
--,OVR_REV_IND_RATE_SCH_ID::string AS OVR_REV_IND_RATE_SCH_ID
--,OVR_INV_IND_RATE_SCH_ID::string AS OVR_INV_IND_RATE_SCH_ID
--,OVR_COST_IND_RATE_SCH_ID::string AS OVR_COST_IND_RATE_SCH_ID
--,NON_LABOR_SCH_TYPE::string AS NON_LABOR_SCH_TYPE --single value 'B' 
--,LABOR_SCH_TYPE::string AS LABOR_SCH_TYPE --single value 'B' 
--,INV_IND_SCH_FIXED_DATE::string AS INV_IND_SCH_FIXED_DATE
--,COST_IND_SCH_FIXED_DATE::string AS COST_IND_SCH_FIXED_DATE
--,INV_IND_RATE_SCH_ID::string AS INV_IND_RATE_SCH_ID
--,REV_IND_RATE_SCH_ID::string AS REV_IND_RATE_SCH_ID
--,COST_IND_RATE_SCH_ID::string AS COST_IND_RATE_SCH_ID
,ATTRIBUTE10::string AS ATTRIBUTE10
,ATTRIBUTE9::string AS ATTRIBUTE9
,ATTRIBUTE8::string AS ATTRIBUTE8
,ATTRIBUTE7::string AS ATTRIBUTE7
,ATTRIBUTE6::string AS ATTRIBUTE6
,ATTRIBUTE5::string AS ATTRIBUTE5
,ATTRIBUTE4::string AS ATTRIBUTE4
,ATTRIBUTE2::string AS ATTRIBUTE2
,ATTRIBUTE_CATEGORY::string AS ATTRIBUTE_CATEGORY
--,PROGRAM_UPDATE_DATE::string AS PROGRAM_UPDATE_DATE
--,PROGRAM_ID::string AS PROGRAM_ID
--,REQUEST_ID::string AS REQUEST_ID
--,LABOR_COST_MULTIPLIER_NAME::string AS LABOR_COST_MULTIPLIER_NAME
--,NON_LABOR_SCHEDULE_DISCOUNT::string AS NON_LABOR_SCHEDULE_DISCOUNT
--,NON_LABOR_SCHEDULE_FIXED_DATE::string AS NON_LABOR_SCHEDULE_FIXED_DATE
--,NON_LABOR_STD_BILL_RATE_SCHDL::string AS NON_LABOR_STD_BILL_RATE_SCHDL--single value 'Standard Non Labor'
,NON_LABOR_BILL_RATE_ORG_ID::string AS NON_LABOR_BILL_RATE_ORG_ID
--,LABOR_SCHEDULE_DISCOUNT::string AS LABOR_SCHEDULE_DISCOUNT
--,LABOR_SCHEDULE_FIXED_DATE::string AS LABOR_SCHEDULE_FIXED_DATE
,LABOR_BILL_RATE_ORG_ID::string AS LABOR_BILL_RATE_ORG_ID
--,ADDRESS_ID::string AS ADDRESS_ID
,TO_TIMESTAMP_NTZ(COMPLETION_DATE::string) AS COMPLETION_DATE
,TO_TIMESTAMP_NTZ(START_DATE::string) AS START_DATE
--,LIMIT_TO_TXN_CONTROLS_FLAG::string AS LIMIT_TO_TXN_CONTROLS_FLAG --single value of N
,BILLABLE_FLAG::string AS BILLABLE_FLAG
,CHARGEABLE_FLAG::string AS CHARGEABLE_FLAG
--,TASK_MANAGER_PERSON_ID::string AS TASK_MANAGER_PERSON_ID
,SERVICE_TYPE_CODE::string AS SERVICE_TYPE_CODE
,CARRYING_OUT_ORGANIZATION_ID::string AS CARRYING_OUT_ORGANIZATION_ID
,DESCRIPTION::string AS DESCRIPTION
,PARENT_TASK_ID::string AS PARENT_TASK_ID
,READY_TO_DISTRIBUTE_FLAG::string AS READY_TO_DISTRIBUTE_FLAG
,WBS_LEVEL::string AS WBS_LEVEL
,TOP_TASK_ID::string AS TOP_TASK_ID
,TASK_NAME::string AS TASK_NAME
,LAST_UPDATE_LOGIN::string AS LAST_UPDATE_LOGIN
,LAST_UPDATED_BY::string AS LAST_UPDATED_BY
,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE
,CREATED_BY::string AS CREATED_BY
,TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE
,UPPER(TRIM(TASK_NUMBER::string)) AS TASK_NUMBER
,PROJECT_ID::string AS PROJECT_ID
,TASK_ID::string AS TASK_ID
--,ADW_NOTIFY_FLAG::string AS ADW_NOTIFY_FLAG--single value of 'Y'
--,ALLOW_CROSS_CHARGE_FLAG::string AS ALLOW_CROSS_CHARGE_FLAG--single value of 'Y'
--,GEN_ETC_SOURCE_CODE::string AS GEN_ETC_SOURCE_CODE--single value of 'FINANCIAL_PLAN'
--,EARLY_FINISH_DATE::string AS EARLY_FINISH_DATE
--,EARLY_START_DATE::string AS EARLY_START_DATE
--,ACTUAL_FINISH_DATE::string AS ACTUAL_FINISH_DATE
--,ACTUAL_START_DATE::string AS ACTUAL_START_DATE
,UPPER(TRIM(PM_TASK_REFERENCE::string)) AS PM_TASK_REFERENCE
--,PM_PRODUCT_CODE::string AS PM_PRODUCT_CODE---single value 'SPM'
,CUSTOMER_ID::string AS CUSTOMER_ID --Has been kept in case if needed in future to combine with other tables but has 100% nulls
--,PROGRAM_APPLICATION_ID::string AS PROGRAM_APPLICATION_ID
--,BILL_SCHE_OVRD_FLAG::string AS BILL_SCHE_OVRD_FLAG
--,INVOICE_METHOD::string AS INVOICE_METHOD--single value 'EVENT'
--,REVENUE_ACCRUAL_METHOD::string AS REVENUE_ACCRUAL_METHOD 'EVENT'
,RECEIVE_PROJECT_INVOICE_FLAG::string AS RECEIVE_PROJECT_INVOICE_FLAG
--,NL_TP_FIXED_DATE::string AS NL_TP_FIXED_DATE
--,NL_TP_SCHEDULE_ID::string AS NL_TP_SCHEDULE_ID
--,CC_PROCESS_NL_FLAG::string AS CC_PROCESS_NL_FLAG--single value 'N'
--,LABOR_TP_FIXED_DATE::string AS LABOR_TP_FIXED_DATE
--,LABOR_TP_SCHEDULE_ID::string AS LABOR_TP_SCHEDULE_ID
--,CC_PROCESS_LABOR_FLAG::string AS CC_PROCESS_LABOR_FLAG single value 'N'
--,PROJECT_RATE_TYPE::string AS PROJECT_RATE_TYPE
--,PROJECT_RATE_DATE::string AS PROJECT_RATE_DATE
--,SCHEDULED_FINISH_DATE::string AS SCHEDULED_FINISH_DATE
--,SCHEDULED_START_DATE::string AS SCHEDULED_START_DATE
--,LATE_FINISH_DATE::string AS LATE_FINISH_DATE
--,LATE_START_DATE::string AS LATE_START_DATE
,ATTRIBUTE1::string AS ATTRIBUTE1
--,REV_IND_SCH_FIXED_DATE::string AS REV_IND_SCH_FIXED_DATE
,ATTRIBUTE3::string AS ATTRIBUTE3
--,LABOR_STD_BILL_RATE_SCHDL::string AS LABOR_STD_BILL_RATE_SCHDL--single value 'Standard Job'
,READY_TO_BILL_FLAG::string AS READY_TO_BILL_FLAG
,METADATA_FILENAME ::string AS METADATA_FILENAME 
,METADATA_FILE_ROW_NUMBER::string AS METADATA_FILE_ROW_NUMBER
,TO_TIMESTAMP_NTZ(METADATA_FILE_LAST_MODIFIED::string) AS METADATA_FILE_LAST_MODIFIED
,TO_TIMESTAMP_NTZ(METADATA_START_SCAN_TIME::string) AS METADATA_START_SCAN_TIME
FROM {{ref('prep_pa_tasks')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TASK_ID,PROJECT_ID,TASK_NAME ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1
