{{
  config(
    materialized = "view",
    alias = "hz_customer_profiles",
    schema='EBS'
  )
}}



SELECT PARTY_ID::NUMBER(15,0) AS PARTY_ID
    --,TO_TIMESTAMP_NTZ(LAST_CREDIT_REVIEW_DATE::STRING) AS LAST_CREDIT_REVIEW_DATE,--Excluded always NULL
    ,NULLIF(TRIM(REVIEW_CYCLE::string), '') AS REVIEW_CYCLE
    --,NULLIF(TRIM(CREDIT_CLASSIFICATION::string), '') AS CREDIT_CLASSIFICATION--Excluded always NULL
    --,NULLIF(TRIM(GLOBAL_ATTRIBUTE11::string), '') AS GLOBAL_ATTRIBUTE11--Excluded always NULL
    --,NULLIF(TRIM(GLOBAL_ATTRIBUTE10::string), '') AS GLOBAL_ATTRIBUTE10--Excluded always NULL
    --,NULLIF(TRIM(GLOBAL_ATTRIBUTE9::string), '') AS GLOBAL_ATTRIBUTE9--Excluded always NULL
    --,NULLIF(TRIM(GLOBAL_ATTRIBUTE8::string), '') AS GLOBAL_ATTRIBUTE8--Excluded always NULL
    --,NULLIF(TRIM(GLOBAL_ATTRIBUTE7::string), '') AS GLOBAL_ATTRIBUTE7--Excluded always NULL
    --,NULLIF(TRIM(GLOBAL_ATTRIBUTE6::string), '') AS GLOBAL_ATTRIBUTE6--Excluded always NULL
    --,NULLIF(TRIM(GLOBAL_ATTRIBUTE5::string), '') AS GLOBAL_ATTRIBUTE5--Excluded always NULL
    --,NULLIF(TRIM(GLOBAL_ATTRIBUTE4::string), '') AS GLOBAL_ATTRIBUTE4--Excluded always NULL
    --,NULLIF(TRIM(GLOBAL_ATTRIBUTE3::string), '') AS GLOBAL_ATTRIBUTE3--Excluded always NULL
    --,NULLIF(TRIM(GLOBAL_ATTRIBUTE2::string), '') AS GLOBAL_ATTRIBUTE2--Excluded always NULL
    --,NULLIF(TRIM(GLOBAL_ATTRIBUTE1::string), '') AS GLOBAL_ATTRIBUTE1--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE15::string), '') AS JGZZ_ATTRIBUTE15--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE14::string), '') AS JGZZ_ATTRIBUTE14--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE13::string), '') AS JGZZ_ATTRIBUTE13--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE12::string), '') AS JGZZ_ATTRIBUTE12--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE11::string), '') AS JGZZ_ATTRIBUTE11--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE10::string), '') AS JGZZ_ATTRIBUTE10--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE9::string), '') AS JGZZ_ATTRIBUTE9--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE8::string), '') AS JGZZ_ATTRIBUTE8--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE7::string), '') AS JGZZ_ATTRIBUTE7--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE6::string), '') AS JGZZ_ATTRIBUTE6--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE5::string), '') AS JGZZ_ATTRIBUTE5--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE4::string), '') AS JGZZ_ATTRIBUTE4--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE3::string), '') AS JGZZ_ATTRIBUTE3--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE2::string), '') AS JGZZ_ATTRIBUTE2--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE1::string), '') AS JGZZ_ATTRIBUTE1--Excluded always NULL
    --,NULLIF(TRIM(JGZZ_ATTRIBUTE_CATEGORY::string), '') AS JGZZ_ATTRIBUTE_CATEGORY--Excluded always NULL
    --,CLEARING_DAYS::NUMBER(15,0) AS CLEARING_DAYS--Excluded always null
    ,GROUPING_RULE_ID::NUMBER(15,0) AS GROUPING_RULE_ID
    ,NULLIF(TRIM(CHARGE_ON_FINANCE_CHARGE_FLAG::string), '') AS CHARGE_ON_FINANCE_CHARGE_FLAG
    ,NULLIF(TRIM(TAX_PRINTING_OPTION::string), '') AS TAX_PRINTING_OPTION
    ,NULLIF(TRIM(AUTO_REC_INCL_DISPUTED_FLAG::string), '') AS AUTO_REC_INCL_DISPUTED_FLAG
    ,NULLIF(TRIM(ATTRIBUTE15::string), '') AS ATTRIBUTE15
    --,NULLIF(TRIM(ATTRIBUTE14::string), '') AS ATTRIBUTE14--Excluded always null
    --,NULLIF(TRIM(ATTRIBUTE13::string), '') AS ATTRIBUTE13--Excluded always null
    --,NULLIF(TRIM(ATTRIBUTE12::string), '') AS ATTRIBUTE12--Excluded always null
    --,NULLIF(TRIM(ATTRIBUTE11::string), '') AS ATTRIBUTE11--Excluded always null
    --,NULLIF(TRIM(WH_UPDATE_DATE::string), '') AS WH_UPDATE_DATE--Excluded always null
    ,REQUEST_ID::NUMBER(15,0) AS REQUEST_ID
    ,TO_TIMESTAMP_NTZ(PROGRAM_UPDATE_DATE::STRING) AS PROGRAM_UPDATE_DATE
    ,PROGRAM_ID::NUMBER(15,0) AS PROGRAM_ID
    ,PROGRAM_APPLICATION_ID::NUMBER(15,0) AS PROGRAM_APPLICATION_ID
    --,NULLIF(TRIM(ATTRIBUTE10::string), '') AS ATTRIBUTE10--Excluded always NULL
    --,NULLIF(TRIM(ATTRIBUTE9::string), '') AS ATTRIBUTE9--Excluded always NULL
    --,NULLIF(TRIM(ATTRIBUTE8::string), '') AS ATTRIBUTE8--Excluded always NULL
    --,NULLIF(TRIM(ATTRIBUTE7::string), '') AS ATTRIBUTE7--Excluded always NULL
    --,NULLIF(TRIM(ATTRIBUTE6::string), '') AS ATTRIBUTE6--Excluded always NULL
    --,NULLIF(TRIM(ATTRIBUTE5::string), '') AS ATTRIBUTE5--Excluded always NULL
    --,NULLIF(TRIM(ATTRIBUTE4::string), '') AS ATTRIBUTE4--Excluded always NULL
    --,NULLIF(TRIM(ATTRIBUTE3::string), '') AS ATTRIBUTE3--Excluded always NULL
    --,NULLIF(TRIM(ATTRIBUTE2::string), '') AS ATTRIBUTE2--Excluded always NULL
    --,NULLIF(TRIM(ATTRIBUTE1::string), '') AS ATTRIBUTE1--Excluded always NULL
    --,NULLIF(TRIM(ATTRIBUTE_CATEGORY::string), '') AS ATTRIBUTE_CATEGORY--Excluded always NULL
    ,AUTOCASH_HIERARCHY_ID::NUMBER(15,0) AS AUTOCASH_HIERARCHY_ID
    --,PERCENT_COLLECTABLE::NUMBER(15,0) AS PERCENT_COLLECTABLE--Excluded always null
    ,NULLIF(TRIM(ACCOUNT_STATUS::string), '') AS ACCOUNT_STATUS
    --,STATEMENT_CYCLE_ID::NUMBER(15,0) AS STATEMENT_CYCLE_ID--Excluded always null
    ,DISCOUNT_GRACE_DAYS::NUMBER AS DISCOUNT_GRACE_DAYS
    ,PAYMENT_GRACE_DAYS::NUMBER AS PAYMENT_GRACE_DAYS
    ,INTEREST_PERIOD_DAYS::NUMBER AS INTEREST_PERIOD_DAYS
    --,DUNNING_LETTER_SET_ID::NUMBER(15,0) AS DUNNING_LETTER_SET_ID--Excluded always NULL
    ,NULLIF(TRIM(OVERRIDE_TERMS::string), '') AS OVERRIDE_TERMS
    ,STANDARD_TERMS::NUMBER(15,0) AS STANDARD_TERMS
    --,NULLIF(TRIM(RISK_CODE::string), '') AS RISK_CODE--Excluded always NULL
    ,NULLIF(TRIM(CREDIT_RATING::string), '') AS CREDIT_RATING
    ,SITE_USE_ID::NUMBER(15,0) AS SITE_USE_ID
    ,PROFILE_CLASS_ID::NUMBER(15,0) AS PROFILE_CLASS_ID
    ,NULLIF(TRIM(CREDIT_HOLD::string), '') AS CREDIT_HOLD
    --,NULLIF(TRIM(CREDIT_BALANCE_STATEMENTS::string), '') AS CREDIT_BALANCE_STATEMENTS--Excluded always NULL
    --,NULLIF(TRIM(SEND_STATEMENTS::string), '') AS SEND_STATEMENTS--Excluded always NULL
    --,NULLIF(TRIM(PREF_FUNCTIONAL_CURRENCY::string), '') AS PREF_FUNCTIONAL_CURRENCY--Excluded always NULL
    ,NULLIF(TRIM(INTEREST_CHARGES::string), '') AS INTEREST_CHARGES
    --,NULLIF(TRIM(DUNNING_LETTERS::string), '') AS DUNNING_LETTERS--Excluded always NULL
    ,NULLIF(TRIM(DISCOUNT_TERMS::string), '') AS DISCOUNT_TERMS
    --,TOLERANCE::NUMBER AS TOLERANCE--Excluded always 0
    --,TO_TIMESTAMP_NTZ(NEXT_CREDIT_REVIEW_DATE::STRING) AS NEXT_CREDIT_REVIEW_DATE--Excluded always NULL
    ,NULLIF(TRIM(CREDIT_CHECKING::string), '') AS CREDIT_CHECKING
    --,CREDIT_ANALYST_ID::NUMBER(15,0) AS CREDIT_ANALYST_ID--Excluded always NULL
    ,COLLECTOR_ID::NUMBER(15,0) AS COLLECTOR_ID
    ,NULLIF(TRIM(STATUS::string), '') AS STATUS
    ,CUST_ACCOUNT_ID::NUMBER(15,0) AS CUST_ACCOUNT_ID
    ,TO_TIMESTAMP_NTZ(CREATION_DATE::STRING) AS CREATION_DATE
    ,CREATED_BY::NUMBER(15,0) AS CREATED_BY
    ,LAST_UPDATE_LOGIN::NUMBER(15,0) AS LAST_UPDATE_LOGIN
    ,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::STRING) AS LAST_UPDATE_DATE
    ,LAST_UPDATED_BY::NUMBER(15,0) AS LAST_UPDATED_BY
    ,CUST_ACCOUNT_PROFILE_ID::NUMBER(15,0) AS CUST_ACCOUNT_PROFILE_ID
    --,LOCKBOX_MATCHING_OPTION::string AS LOCKBOX_MATCHING_OPTION --Excluded always NULL
--,AUTOCASH_HIERARCHY_ID_FOR_ADR::NUMBER(15,0) AS AUTOCASH_HIERARCHY_ID_FOR_ADR--Excluded always NULL
--,CONS_INV_TYPE::string AS CONS_INV_TYPE--Excluded always NULL
,NULLIF(TRIM(CONS_INV_FLAG::string), '') AS CONS_INV_FLAG,
--,GLOBAL_ATTRIBUTE_CATEGORY::string AS GLOBAL_ATTRIBUTE_CATEGORY--Excluded always NULL
--,GLOBAL_ATTRIBUTE20::string AS GLOBAL_ATTRIBUTE20--Excluded always NULL
--,GLOBAL_ATTRIBUTE19::string AS GLOBAL_ATTRIBUTE19--Excluded always NULL
--,GLOBAL_ATTRIBUTE18::string AS GLOBAL_ATTRIBUTE18--Excluded always NULL
--,GLOBAL_ATTRIBUTE17::string AS GLOBAL_ATTRIBUTE17--Excluded always NULL
--,GLOBAL_ATTRIBUTE16::string AS GLOBAL_ATTRIBUTE16--Excluded always NULL
--,GLOBAL_ATTRIBUTE15::string AS GLOBAL_ATTRIBUTE15--Excluded always NULL
--,GLOBAL_ATTRIBUTE14::string AS GLOBAL_ATTRIBUTE14--Excluded always NULL
--,GLOBAL_ATTRIBUTE13::string AS GLOBAL_ATTRIBUTE13--Excluded always NULL
--,GLOBAL_ATTRIBUTE12::string AS GLOBAL_ATTRIBUTE12--Excluded always NULL
APPLICATION_ID::NUMBER AS APPLICATION_ID,
NULLIF(TRIM(CREATED_BY_MODULE::string), '') AS CREATED_BY_MODULE
    ,OBJECT_VERSION_NUMBER::NUMBER AS OBJECT_VERSION_NUMBER
FROM {{ref('prep_hz_customer_profiles')}}
 QUALIFY ROW_NUMBER() OVER (PARTITION BY CUST_ACCOUNT_PROFILE_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1