{{
  config(
    materialized = "view",
    alias = "mtl_eam_asset_attr_values",
    schema='EBS'
  )
}}

SELECT
N_ATTRIBUTE8::number AS N_ATTRIBUTE8
,N_ATTRIBUTE7::number AS N_ATTRIBUTE7
,N_ATTRIBUTE6::number AS N_ATTRIBUTE6
,N_ATTRIBUTE5::number AS N_ATTRIBUTE5
,N_ATTRIBUTE4::number AS N_ATTRIBUTE4
--,N_ATTRIBUTE3::number AS N_ATTRIBUTE3--excluded as always NULL
,N_ATTRIBUTE2::number AS N_ATTRIBUTE2
--,N_ATTRIBUTE1::number AS N_ATTRIBUTE1--excluded as always NULL
,TO_TIMESTAMP_NTZ(D_ATTRIBUTE10::string) AS D_ATTRIBUTE10
,TO_TIMESTAMP_NTZ(D_ATTRIBUTE9::string) AS D_ATTRIBUTE9
,TO_TIMESTAMP_NTZ(D_ATTRIBUTE8::string) AS D_ATTRIBUTE8
,TO_TIMESTAMP_NTZ(D_ATTRIBUTE7::string) AS D_ATTRIBUTE7
--,TO_TIMESTAMP_NTZ(D_ATTRIBUTE6::string) AS D_ATTRIBUTE6--excluded as always NULL
--,TO_TIMESTAMP_NTZ(D_ATTRIBUTE5::string) AS D_ATTRIBUTE5--excluded as always NULL
--,TO_TIMESTAMP_NTZ(D_ATTRIBUTE4::string) AS D_ATTRIBUTE4--excluded as always NULL
--,TO_TIMESTAMP_NTZ(D_ATTRIBUTE3::string) AS D_ATTRIBUTE3--excluded as always NULL
,TO_TIMESTAMP_NTZ(D_ATTRIBUTE2::string) AS D_ATTRIBUTE2
,TO_TIMESTAMP_NTZ(D_ATTRIBUTE1::string) AS D_ATTRIBUTE1
,UPPER(NULLIF(TRIM(C_ATTRIBUTE20::string),'')) AS C_ATTRIBUTE20
,NULLIF(TRIM(C_ATTRIBUTE19::string),'') AS C_ATTRIBUTE19
,NULLIF(TRIM(C_ATTRIBUTE18::string),'') AS C_ATTRIBUTE18
,INITCAP(NULLIF(TRIM(C_ATTRIBUTE17::string),'')) AS C_ATTRIBUTE17
,UPPER(NULLIF(TRIM(C_ATTRIBUTE16::string),'')) AS C_ATTRIBUTE16
,NULLIF(TRIM(C_ATTRIBUTE15::string),'') AS C_ATTRIBUTE15
,NULLIF(TRIM(C_ATTRIBUTE14::string),'') AS C_ATTRIBUTE14
,NULLIF(TRIM(C_ATTRIBUTE13::string),'') AS C_ATTRIBUTE13
,NULLIF(TRIM(C_ATTRIBUTE12::string),'') AS C_ATTRIBUTE12
,NULLIF(TRIM(C_ATTRIBUTE11::string),'') AS C_ATTRIBUTE11
,NULLIF(TRIM(C_ATTRIBUTE10::string),'') AS C_ATTRIBUTE10
,NULLIF(TRIM(C_ATTRIBUTE9::string),'') AS C_ATTRIBUTE9
,NULLIF(TRIM(C_ATTRIBUTE8::string),'') AS C_ATTRIBUTE8
,NULLIF(TRIM(C_ATTRIBUTE7::string),'') AS C_ATTRIBUTE7
,NULLIF(TRIM(C_ATTRIBUTE6::string),'') AS C_ATTRIBUTE6
,NULLIF(TRIM(C_ATTRIBUTE5::string),'') AS C_ATTRIBUTE5
,NULLIF(TRIM(C_ATTRIBUTE4::string),'') AS C_ATTRIBUTE4
,NULLIF(TRIM(C_ATTRIBUTE3::string),'') AS C_ATTRIBUTE3
,NULLIF(TRIM(C_ATTRIBUTE2::string),'') AS C_ATTRIBUTE2
,NULLIF(TRIM(C_ATTRIBUTE1::string),'') AS C_ATTRIBUTE1
,ORGANIZATION_ID::number AS ORGANIZATION_ID
,NULLIF(TRIM(SERIAL_NUMBER::string),'') AS SERIAL_NUMBER
,INVENTORY_ITEM_ID::number AS INVENTORY_ITEM_ID
--,UPPER(NULLIF(TRIM(DESCRIPTIVE_FLEXFIELD_NAME::string),'')) AS DESCRIPTIVE_FLEXFIELD_NAME--excluded as always same value
,APPLICATION_ID::number AS APPLICATION_ID
,INITCAP(NULLIF(TRIM(ATTRIBUTE_GROUP::string),'')) AS ATTRIBUTE_GROUP
,UPPER(NULLIF(TRIM(ATTRIBUTE_CATEGORY::string),'')) AS ATTRIBUTE_CATEGORY
,ASSOCIATION_ID::number AS ASSOCIATION_ID
,NULLIF(TRIM(ROW_ID::string),'') AS ROW_ID
--,TO_TIMESTAMP_NTZ(PROGRAM_UPDATE_DATE::string) AS PROGRAM_UPDATE_DATE--excluded as always NULL
--,PROGRAM_ID::number AS PROGRAM_ID--excluded as always NULL
--,PROGRAM_APPLICATION_ID::number AS PROGRAM_APPLICATION_ID--excluded as always NULL
--,REQUEST_ID::number AS REQUEST_ID--excluded as always NULL
,LAST_UPDATE_LOGIN::number AS LAST_UPDATE_LOGIN
,CREATED_BY::number AS CREATED_BY
,TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE
,LAST_UPDATED_BY::number AS LAST_UPDATED_BY
,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE
,N_ATTRIBUTE10::number AS N_ATTRIBUTE10
,N_ATTRIBUTE9::number AS N_ATTRIBUTE9
FROM {{ref('prep_mtl_eam_asset_attr_values')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY SERIAL_NUMBER, ASSOCIATION_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1