{{
  config(
    materialized = "view",
    alias = "cmg_dw_projects_etl",
    schema='EBS'
  )
}}

 SELECT 
 PROJECT_CODE::string AS PROJECT_CODE
,PROJECT_NAME::string AS PROJECT_NAME
,NULLIF(TRIM(PROJECT_SALESREP::string),'') AS PROJECT_SALESREP
,NULLIF(TRIM(PROJECT_MANAGER::string),'') AS PROJECT_MANAGER
,NULLIF(TRIM(COORDINATOR_NAME::string),'') AS COORDINATOR_NAME
,NULLIF(TRIM(PROJECT_MANAGER_EMAIL::string),'') AS PROJECT_MANAGER_EMAIL
,NULLIF(TRIM(PROJECT_SALESREP_GLCIE::string),'') AS PROJECT_SALESREP_GLCIE
,NULLIF(TRIM(PROJECT_SALESREP_REGION::string),'') AS PROJECT_SALESREP_REGION
,NULLIF(TRIM(PROJECT_SALESREP_SUBREGION::string),'') AS PROJECT_SALESREP_SUBREGION
,NULLIF(TRIM(PROJECT_CURRENCY::string),'')  AS PROJECT_CURRENCY
,NULLIF(TRIM(PROJECT_STATUS_CODE::string),'')  AS PROJECT_STATUS_CODE
,NULLIF(TRIM(PROJECT_TYPE::string),'')  AS PROJECT_TYPE
,TO_TIMESTAMP_NTZ(PROJECT_START_DATE::string) AS PROJECT_START_DATE
,TO_TIMESTAMP_NTZ(PROJECT_CLOSE_DATE::string) AS PROJECT_CLOSE_DATE
,TO_TIMESTAMP_NTZ(PROJECT_COMPLETION_DATE::string) AS PROJECT_COMPLETION_DATE
,TO_TIMESTAMP_NTZ(PROJECT_CREATION_DATE::string) AS PROJECT_CREATION_DATE
,NULLIF(TRIM(CLASS_CATEGORY::string),'') AS CLASS_CATEGORY
,NULLIF(TRIM(CLASS_CODE::string),'') AS CLASS_CODE
,NULLIF(TRIM(CLASS_DESCRIPTION::string),'') AS CLASS_DESCRIPTION
,NULLIF(TRIM(BILL_TO_NUMBER::string),'') AS BILL_TO_NUMBER
,BILL_TO_ORG_ID::NUMBER AS BILL_TO_ORG_ID
,NULLIF(TRIM(SHIP_ADDRESS1::string),'') AS SHIP_ADDRESS1
,NULLIF(TRIM(SHIP_ADDRESS2::string),'') AS SHIP_ADDRESS2
,NULLIF(TRIM(SHIP_ADDRESS3::string),'') AS SHIP_ADDRESS3
,NULLIF(TRIM(SHIP_POSTAL_CODE::string),'') AS SHIP_POSTAL_CODE
,NULLIF(TRIM(SHIP_CITY::string),'') AS SHIP_CITY
,NULLIF(TRIM(SHIP_STATE_PROV::string),'') AS SHIP_STATE_PROV
,NULLIF(TRIM(SHIP_COUNTY::string),'') AS SHIP_COUNTY
,NULLIF(TRIM(SHIP_COUNTRY::string),'') AS SHIP_COUNTRY
,NULLIF(TRIM(RELATED_PROJECT_CODE::string),'') AS RELATED_PROJECT_CODE
,CARRYING_OUT_ORGANIZATION_ID::NUMBER AS CARRYING_OUT_ORGANIZATION_ID
,NULLIF(TRIM(BUSINESS_UNITS_CODE::string),'') AS BUSINESS_UNITS_CODE
,NULLIF(TRIM(PROJECT_CURRENCY_RATE::string),'') AS PROJECT_CURRENCY_RATE
,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE
FROM {{ref('prep_cmg_dw_projects_etl')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY PROJECT_CODE ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1