{{
  config(
    materialized = "view",
    alias = "pa_segment_value_lookup_sets",
    schema='EBS'
  )
}}

SELECT
 UPPER(NULLIF(TRIM(DESCRIPTION::string),'')) AS  DESCRIPTION
, LAST_UPDATE_LOGIN::number(15,0) AS  LAST_UPDATE_LOGIN
, CREATED_BY::number(15,0) AS  CREATED_BY
, TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS  CREATION_DATE
, LAST_UPDATED_BY::number(15,0) AS  LAST_UPDATED_BY
, TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS  LAST_UPDATE_DATE
, UPPER(NULLIF(TRIM(SEGMENT_VALUE_LOOKUP_SET_NAME::string),'')) AS  SEGMENT_VALUE_LOOKUP_SET_NAME
, SEGMENT_VALUE_LOOKUP_SET_ID::number(15,0) AS  SEGMENT_VALUE_LOOKUP_SET_ID
--, SRC_SYSTEM_OPERATION::string AS  SRC_SYSTEM_OPERATION
FROM {{ref('prep_pa_segment_value_lookup_sets')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY SEGMENT_VALUE_LOOKUP_SET_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1