{{
  config(
    materialized = "view",
    alias = "ar_collectors",
    schema='EBS'
  )
}}


SELECT
COLLECTOR_ID::number(15,0) AS COLLECTOR_ID
,LAST_UPDATED_BY::number(15,0) AS LAST_UPDATED_BY
,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE
,LAST_UPDATE_LOGIN::number(15,0) AS LAST_UPDATE_LOGIN
,TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE
,CREATED_BY::number(15,0) AS CREATED_BY
,UPPER(TRIM(NAME::string)) AS NAME
,UPPER(TRIM(DESCRIPTION::string)) AS DESCRIPTION
,STATUS::string AS STATUS
,TO_TIMESTAMP_NTZ(INACTIVE_DATE::string) AS INACTIVE_DATE
,UPPER(TRIM(ALIAS::string)) AS ALIAS
,NULLIF(REGEXP_REPLACE(TELEPHONE_NUMBER::string, '[^\\d]', ''), '') AS TELEPHONE_NUMBER
,ATTRIBUTE1::number AS ATTRIBUTE1
,UPPER(TRIM(ATTRIBUTE2::string)) AS ATTRIBUTE2
,UPPER(TRIM(ATTRIBUTE3::string)) AS ATTRIBUTE3
---Null Values for these columns---
-- ,ATTRIBUTE4::string AS ATTRIBUTE4
-- ,ATTRIBUTE5::string AS ATTRIBUTE5
-- ,ATTRIBUTE6::string AS ATTRIBUTE6
-- ,ATTRIBUTE7::string AS ATTRIBUTE7
-- ,ATTRIBUTE8::string AS ATTRIBUTE8
-- ,ATTRIBUTE9::string AS ATTRIBUTE9
-- ,ATTRIBUTE10::string AS ATTRIBUTE10
-- ,ATTRIBUTE11::string AS ATTRIBUTE11
-- ,ATTRIBUTE12::string AS ATTRIBUTE12
-- ,ATTRIBUTE13::string AS ATTRIBUTE13
-- ,ATTRIBUTE14::string AS ATTRIBUTE14
-- ,ATTRIBUTE15::string AS ATTRIBUTE15
-- ,RESOURCE_ID::string AS RESOURCE_ID
-- ,RESOURCE_TYPE::string AS RESOURCE_TYPE
-- ,ATTRIBUTE_CATEGORY::string AS ATTRIBUTE_CATEGORY
-- ,EMPLOYEE_ID::string AS EMPLOYEE_ID
FROM {{ref('prep_ar_collectors')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY COLLECTOR_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1