{{
  config(
    materialized = "view",
    alias = "wip_discrete_jobs",
    schema='EBS'
  )
}}

SELECT
  WIP_ENTITY_ID::NUMBER AS WIP_ENTITY_ID,/*PK*/
  ORGANIZATION_ID::NUMBER AS ORGANIZATION_ID,
  TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE,
  LAST_UPDATED_BY::NUMBER AS LAST_UPDATED_BY,
  TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE,
  CREATED_BY::NUMBER AS CREATED_BY,
  LAST_UPDATE_LOGIN::NUMBER AS LAST_UPDATE_LOGIN,
  REQUEST_ID::NUMBER AS REQUEST_ID,
  --PROGRAM_APPLICATION_ID::NUMBER AS PROGRAM_APPLICATION_ID,/*Always Null*/
  --PROGRAM_ID::NUMBER AS PROGRAM_ID,/*Always Null*/
  TO_TIMESTAMP_NTZ(PROGRAM_UPDATE_DATE::string) AS PROGRAM_UPDATE_DATE,
  --SOURCE_LINE_ID::NUMBER AS SOURCE_LINE_ID,/*Always Null*/
  --UPPER(NULLIF(TRIM(SOURCE_CODE::string),'')) AS SOURCE_CODE,/*Always Null*/
  INITCAP(NULLIF(TRIM(DESCRIPTION::string),'')) AS DESCRIPTION,
  STATUS_TYPE::NUMBER AS STATUS_TYPE,
  PRIMARY_ITEM_ID::NUMBER AS PRIMARY_ITEM_ID,
  FIRM_PLANNED_FLAG::NUMBER AS FIRM_PLANNED_FLAG,
  JOB_TYPE::NUMBER AS JOB_TYPE,
  WIP_SUPPLY_TYPE::NUMBER AS WIP_SUPPLY_TYPE,
  UPPER(NULLIF(TRIM(CLASS_CODE::string),'')) AS CLASS_CODE,
  MATERIAL_ACCOUNT::NUMBER AS MATERIAL_ACCOUNT,
  MATERIAL_OVERHEAD_ACCOUNT::NUMBER AS MATERIAL_OVERHEAD_ACCOUNT,
  RESOURCE_ACCOUNT::NUMBER AS RESOURCE_ACCOUNT,
  OUTSIDE_PROCESSING_ACCOUNT::NUMBER AS OUTSIDE_PROCESSING_ACCOUNT,
  MATERIAL_VARIANCE_ACCOUNT::NUMBER AS MATERIAL_VARIANCE_ACCOUNT,
  RESOURCE_VARIANCE_ACCOUNT::NUMBER AS RESOURCE_VARIANCE_ACCOUNT,
  OUTSIDE_PROC_VARIANCE_ACCOUNT::NUMBER AS OUTSIDE_PROC_VARIANCE_ACCOUNT,
  --STD_COST_ADJUSTMENT_ACCOUNT::NUMBER AS STD_COST_ADJUSTMENT_ACCOUNT,/*Always Null*/
  OVERHEAD_ACCOUNT::NUMBER AS OVERHEAD_ACCOUNT,
  OVERHEAD_VARIANCE_ACCOUNT::NUMBER AS OVERHEAD_VARIANCE_ACCOUNT,
  TO_TIMESTAMP_NTZ(SCHEDULED_START_DATE::string) AS SCHEDULED_START_DATE,
  TO_TIMESTAMP_NTZ(DATE_RELEASED::string) AS DATE_RELEASED,
  TO_TIMESTAMP_NTZ(SCHEDULED_COMPLETION_DATE::string) AS SCHEDULED_COMPLETION_DATE,
  TO_TIMESTAMP_NTZ(DATE_COMPLETED::string) AS DATE_COMPLETED,
  TO_TIMESTAMP_NTZ(DATE_CLOSED::string) AS DATE_CLOSED,
  START_QUANTITY::NUMBER AS START_QUANTITY,
  QUANTITY_COMPLETED::NUMBER AS QUANTITY_COMPLETED,
  QUANTITY_SCRAPPED::NUMBER AS QUANTITY_SCRAPPED,
  NET_QUANTITY::NUMBER AS NET_QUANTITY,
  --BOM_REFERENCE_ID::NUMBER AS BOM_REFERENCE_ID,/*Always Null*/
  --ROUTING_REFERENCE_ID::NUMBER AS ROUTING_REFERENCE_ID,/*Always Null*/
  --COMMON_BOM_SEQUENCE_ID::NUMBER AS COMMON_BOM_SEQUENCE_ID,/*Always Null*/
  --COMMON_ROUTING_SEQUENCE_ID::NUMBER AS COMMON_ROUTING_SEQUENCE_ID,/*Always Null*/
  --UPPER(NULLIF(TRIM(BOM_REVISION::string),'')) AS BOM_REVISION,/*Always Null*/
  --UPPER(NULLIF(TRIM(ROUTING_REVISION::string),'')) AS ROUTING_REVISION,/*Always Null*/
  --TO_TIMESTAMP_NTZ(BOM_REVISION_DATE::string) AS BOM_REVISION_DATE,/*Always Null*/
  --TO_TIMESTAMP_NTZ(ROUTING_REVISION_DATE::string) AS ROUTING_REVISION_DATE,/*Always Null*/
  --UPPER(NULLIF(TRIM(LOT_NUMBER::string),'')) AS LOT_NUMBER,/*Always Null*/
  --UPPER(NULLIF(TRIM(ALTERNATE_BOM_DESIGNATOR::string),'')) AS ALTERNATE_BOM_DESIGNATOR,/*Always Null*/
  --UPPER(NULLIF(TRIM(ALTERNATE_ROUTING_DESIGNATOR::string),'')) AS ALTERNATE_ROUTING_DESIGNATOR,/*Always Null*/
  --UPPER(NULLIF(TRIM(COMPLETION_SUBINVENTORY::string),'')) AS COMPLETION_SUBINVENTORY,/*Always Null*/
  --COMPLETION_LOCATOR_ID::NUMBER AS COMPLETION_LOCATOR_ID,/*Always Null*/
  --TO_TIMESTAMP_NTZ(MPS_SCHEDULED_COMPLETION_DATE::string) AS MPS_SCHEDULED_COMPLETION_DATE,/*Always Null*/
  --MPS_NET_QUANTITY::NUMBER AS MPS_NET_QUANTITY,/*Always Null*/
  --UPPER(NULLIF(TRIM(DEMAND_CLASS::string),'')) AS DEMAND_CLASS,/*Always Null*/
  --SCHEDULE_GROUP_ID::NUMBER AS SCHEDULE_GROUP_ID,/*Always Null*/
  --BUILD_SEQUENCE::NUMBER AS BUILD_SEQUENCE,/*Always Null*/
  --LINE_ID::NUMBER AS LINE_ID,/*Always Null*/
  PROJECT_ID::NUMBER AS PROJECT_ID,
  TASK_ID::NUMBER AS TASK_ID,
  --UPPER(NULLIF(TRIM(ATTRIBUTE_CATEGORY::string),'')) AS ATTRIBUTE_CATEGORY,/*Always Null*/
  UPPER(NULLIF(TRIM(ATTRIBUTE1::string),'')) AS ATTRIBUTE1,
  UPPER(NULLIF(TRIM(ATTRIBUTE2::string),'')) AS ATTRIBUTE2,
  --UPPER(NULLIF(TRIM(ATTRIBUTE3::string),'')) AS ATTRIBUTE3,/*Always Null*/
  --UPPER(NULLIF(TRIM(ATTRIBUTE4::string),'')) AS ATTRIBUTE4,/*Always Null*/
  --UPPER(NULLIF(TRIM(ATTRIBUTE5::string),'')) AS ATTRIBUTE5,/*Always Null*/
  --UPPER(NULLIF(TRIM(ATTRIBUTE6::string),'')) AS ATTRIBUTE6,/*Always Null*/
  --UPPER(NULLIF(TRIM(ATTRIBUTE7::string),'')) AS ATTRIBUTE7,/*Always Null*/
  --UPPER(NULLIF(TRIM(ATTRIBUTE8::string),'')) AS ATTRIBUTE8,/*Always Null*/
  --UPPER(NULLIF(TRIM(ATTRIBUTE9::string),'')) AS ATTRIBUTE9,/*Always Null*/
  --UPPER(NULLIF(TRIM(ATTRIBUTE10::string),'')) AS ATTRIBUTE10,/*Always Null*/
  --UPPER(NULLIF(TRIM(ATTRIBUTE11::string),'')) AS ATTRIBUTE11,/*Always Null*/
  --UPPER(NULLIF(TRIM(ATTRIBUTE12::string),'')) AS ATTRIBUTE12,/*Always Null*/
  --UPPER(NULLIF(TRIM(ATTRIBUTE13::string),'')) AS ATTRIBUTE13,/*Always Null*/
  --UPPER(NULLIF(TRIM(ATTRIBUTE14::string),'')) AS ATTRIBUTE14,/*Always Null*/
  --UPPER(NULLIF(TRIM(ATTRIBUTE15::string),'')) AS ATTRIBUTE15,/*Always Null*/
  --KANBAN_CARD_ID::NUMBER AS KANBAN_CARD_ID,/*Always Null*/
  --OVERCOMPLETION_TOLERANCE_TYPE::NUMBER AS OVERCOMPLETION_TOLERANCE_TYPE,/*Always Null*/
  --OVERCOMPLETION_TOLERANCE_VALUE::NUMBER AS OVERCOMPLETION_TOLERANCE_VALUE,/*Always Null*/
  --UPPER(NULLIF(TRIM(END_ITEM_UNIT_NUMBER::string),'')) AS END_ITEM_UNIT_NUMBER,/*Always Null*/
  PO_CREATION_TIME::NUMBER AS PO_CREATION_TIME,
  PRIORITY::NUMBER AS PRIORITY,
  TO_TIMESTAMP_NTZ(DUE_DATE::string) AS DUE_DATE,
  UPPER(NULLIF(TRIM(ISSUE_ZERO_COST_FLAG::string),'')) AS ISSUE_ZERO_COST_FLAG,
  --EST_SCRAP_ACCOUNT::NUMBER AS EST_SCRAP_ACCOUNT,/*Always Null*/
  --EST_SCRAP_VAR_ACCOUNT::NUMBER AS EST_SCRAP_VAR_ACCOUNT,/*Always Null*/
  --EST_SCRAP_PRIOR_QTY::NUMBER AS EST_SCRAP_PRIOR_QTY,/*Always Null*/
  --DUE_DATE_PENALTY::NUMBER AS DUE_DATE_PENALTY,/*Always Null*/
  --DUE_DATE_TOLERANCE::NUMBER AS DUE_DATE_TOLERANCE,/*Always Null*/
  --COPRODUCTS_SUPPLY::NUMBER AS COPRODUCTS_SUPPLY,/*Always Null*/
  --PARENT_WIP_ENTITY_ID::NUMBER AS PARENT_WIP_ENTITY_ID,/*Always Null*/
  UPPER(NULLIF(TRIM(ASSET_NUMBER::string),'')) AS ASSET_NUMBER,
  ASSET_GROUP_ID::NUMBER AS ASSET_GROUP_ID,
  --REBUILD_ITEM_ID::NUMBER AS REBUILD_ITEM_ID,/*Always Null*/
  --UPPER(NULLIF(TRIM(REBUILD_SERIAL_NUMBER::string),'')) AS REBUILD_SERIAL_NUMBER,/*Always Null*/
  --UPPER(NULLIF(TRIM(MANUAL_REBUILD_FLAG::string),'')) AS MANUAL_REBUILD_FLAG,/*Always Null*/
  UPPER(NULLIF(TRIM(SHUTDOWN_TYPE::string),'')) AS SHUTDOWN_TYPE,
  ESTIMATION_STATUS::NUMBER AS ESTIMATION_STATUS,
  TO_TIMESTAMP_NTZ(REQUESTED_START_DATE::string) AS REQUESTED_START_DATE,
  UPPER(NULLIF(TRIM(NOTIFICATION_REQUIRED::string),'')) AS NOTIFICATION_REQUIRED,
  --UPPER(NULLIF(TRIM(WORK_ORDER_TYPE::string),'')) AS WORK_ORDER_TYPE,/*Always Null*/
  OWNING_DEPARTMENT::NUMBER AS OWNING_DEPARTMENT,
  UPPER(NULLIF(TRIM(ACTIVITY_TYPE::string),'')) AS ACTIVITY_TYPE,
  --UPPER(NULLIF(TRIM(ACTIVITY_CAUSE::string),'')) AS ACTIVITY_CAUSE,/*Always Null*/
  UPPER(NULLIF(TRIM(ACTIVITY_SOURCE::string),'')) AS ACTIVITY_SOURCE,
  UPPER(NULLIF(TRIM(TAGOUT_REQUIRED::string),'')) AS TAGOUT_REQUIRED,
  UPPER(NULLIF(TRIM(PLAN_MAINTENANCE::string),'')) AS PLAN_MAINTENANCE,
  PM_SCHEDULE_ID::NUMBER AS PM_SCHEDULE_ID,
  TO_TIMESTAMP_NTZ(LAST_ESTIMATION_DATE::string) AS LAST_ESTIMATION_DATE,
  LAST_ESTIMATION_REQ_ID::NUMBER AS LAST_ESTIMATION_REQ_ID,
  --SERIALIZATION_START_OP::NUMBER AS SERIALIZATION_START_OP,/*Always Null*/
  MAINTENANCE_OBJECT_ID::NUMBER AS MAINTENANCE_OBJECT_ID,
  MAINTENANCE_OBJECT_TYPE::NUMBER AS MAINTENANCE_OBJECT_TYPE,
  MAINTENANCE_OBJECT_SOURCE::NUMBER AS MAINTENANCE_OBJECT_SOURCE,
  UPPER(NULLIF(TRIM(MATERIAL_ISSUE_BY_MO::string),'')) AS MATERIAL_ISSUE_BY_MO,
  --SCHEDULING_REQUEST_ID::NUMBER AS SCHEDULING_REQUEST_ID,/*Always Null*/
  --EAM_LINEAR_LOCATION_ID::NUMBER AS EAM_LINEAR_LOCATION_ID/*Always Null*/

FROM {{ref('prep_wip_discrete_jobs')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY WIP_ENTITY_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1