{{
  config(
    materialized = "view",
    alias = "fnd_flex_value_sets",
    schema='EBS'
  )
}}

SELECT

  /*String Fields*/
  UPPER(NULLIF(TRIM(LONGLIST_FLAG::string),'')) AS LONGLIST_FLAG,
  UPPER(NULLIF(TRIM(SECURITY_ENABLED_FLAG::string),'')) AS SECURITY_ENABLED_FLAG,
  UPPER(NULLIF(TRIM(PROTECTED_FLAG::string),'')) AS PROTECTED_FLAG,
  UPPER(NULLIF(TRIM(FORMAT_TYPE::string),'')) AS FORMAT_TYPE,
  UPPER(NULLIF(TRIM(VALIDATION_TYPE::string),'')) AS VALIDATION_TYPE,
  NULLIF(TRIM(MAXIMUM_VALUE::string),'') AS MAXIMUM_VALUE,
  NULLIF(TRIM(MINIMUM_VALUE::string),'') AS MINIMUM_VALUE,
  UPPER(NULLIF(TRIM(FLEX_VALUE_SET_NAME::string),'')) AS FLEX_VALUE_SET_NAME,
  INITCAP(NULLIF(TRIM(DEPENDANT_DEFAULT_MEANING::string),'')) AS DEPENDANT_DEFAULT_MEANING,
  INITCAP(NULLIF(TRIM(DEPENDANT_DEFAULT_VALUE::string),'')) AS DEPENDANT_DEFAULT_VALUE,
  INITCAP(NULLIF(TRIM(DESCRIPTION::string),'')) AS DESCRIPTION,
  UPPER(NULLIF(TRIM(NUMERIC_MODE_ENABLED_FLAG::string),'')) AS NUMERIC_MODE_ENABLED_FLAG,
  UPPER(NULLIF(TRIM(UPPERCASE_ONLY_FLAG::string),'')) AS UPPERCASE_ONLY_FLAG,
  UPPER(NULLIF(TRIM(ALPHANUMERIC_ALLOWED_FLAG::string),'')) AS ALPHANUMERIC_ALLOWED_FLAG,  

  /*Single Value*/
  --NULLIF(TRIM(LAST_UPDATE_LOGIN::string),'') AS LAST_UPDATE_LOGIN,

  /*Numeric Fields*/  
  CREATED_BY::number AS CREATED_BY,
  LAST_UPDATED_BY::number AS LAST_UPDATED_BY,
  NULLIF(TRIM(NUMBER_PRECISION::number),'') AS NUMBER_PRECISION,
  NULLIF(TRIM(PARENT_FLEX_VALUE_SET_ID::number),'') AS PARENT_FLEX_VALUE_SET_ID,
  TRIM(MAXIMUM_SIZE::number) AS MAXIMUM_SIZE,
  FLEX_VALUE_SET_ID::number AS FLEX_VALUE_SET_ID,

   /*Date Fields*/  
  TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE,
  TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE,
   
FROM {{ref('prep_fnd_flex_value_sets')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY FLEX_VALUE_SET_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1