{{
  config(
    materialized = "view",
    alias = "cmg_eam_kpi_product_lines",
    schema='EBS'
  )
}}

SELECT
PRODUCT_LINE_ID::number AS PRODUCT_LINE_ID
,UPPER(NULLIF(TRIM(PRODUCT_LINE_NAME::string),'')) AS PRODUCT_LINE_NAME
,SHOP_ID::number AS SHOP_ID
,TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE
,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE
,ORGANIZATION_ID::number AS ORGANIZATION_ID
,ENABLED_FLAG::string AS ENABLED_FLAG
FROM {{ref('prep_cmg_eam_kpi_product_lines')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY PRODUCT_LINE_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1