{{
  config(
    materialized = "view",
    alias = "hr_all_organization_units",
    schema='EBS'
  )
}}

SELECT TO_TIMESTAMP_NTZ(CREATION_DATE::DATE) AS CREATION_DATE,
LAST_UPDATE_LOGIN::NUMBER(15,0) AS LAST_UPDATE_LOGIN,
LAST_UPDATED_BY::NUMBER(15,0) AS LAST_UPDATED_BY,
TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::DATE) AS LAST_UPDATE_DATE,
--ATTRIBUTE20::string AS ATTRIBUTE20,--excluded as always NULL
--ATTRIBUTE19::string AS ATTRIBUTE19,--excluded as always NULL
--ATTRIBUTE18::string AS ATTRIBUTE18,--excluded as always NULL
--ATTRIBUTE17::string AS ATTRIBUTE17,--excluded as always NULL
--ATTRIBUTE16::string AS ATTRIBUTE16,--excluded as always NULL
--ATTRIBUTE15::string AS ATTRIBUTE15,--excluded as always NULL
--ATTRIBUTE14::string AS ATTRIBUTE14,--excluded as always NULL
--ATTRIBUTE13::string AS ATTRIBUTE13,--excluded as always NULL
--ATTRIBUTE11::string AS ATTRIBUTE11,--excluded as always NULL
NULLIF(TRIM(ATTRIBUTE9::string), '') AS ATTRIBUTE9,
NULLIF(TRIM(ATTRIBUTE8::string), '') AS ATTRIBUTE8,
NULLIF(TRIM(ATTRIBUTE7::string), '') AS ATTRIBUTE7,
NULLIF(TRIM(ATTRIBUTE6::string), '') AS ATTRIBUTE6,
NULLIF(TRIM(ATTRIBUTE5::string), '') AS ATTRIBUTE5,
NULLIF(TRIM(ATTRIBUTE4::string), '') AS ATTRIBUTE4,
NULLIF(TRIM(ATTRIBUTE3::string), '') AS ATTRIBUTE3,
UPPER(NULLIF(TRIM(ATTRIBUTE2::string), '')) AS ATTRIBUTE2,
UPPER(NULLIF(TRIM(ATTRIBUTE1::string), '')) AS ATTRIBUTE1,
UPPER(NULLIF(TRIM(ATTRIBUTE_CATEGORY::string), '')) AS ATTRIBUTE_CATEGORY,
--TO_TIMESTAMP_NTZ(PROGRAM_UPDATE_DATE::DATE) AS PROGRAM_UPDATE_DATE,--excluded as always NULL
--PROGRAM_ID::NUMBER(15,0) AS PROGRAM_ID,--excluded as always NULL
--PROGRAM_APPLICATION_ID::NUMBER(15,0) AS PROGRAM_APPLICATION_ID,--excluded as always NULL
--REQUEST_ID::NUMBER(15,0) AS REQUEST_ID,--excluded as always NULL
--NULLIF(TRIM(INTERNAL_ADDRESS_LINE::string), '') AS INTERNAL_ADDRESS_LINE,--excluded as always NULL
--NULLIF(TRIM(INTERNAL_EXTERNAL_FLAG::string), '') AS INTERNAL_EXTERNAL_FLAG,--excluded as always same "INT"
UPPER(NULLIF(TRIM(NAME::string), '')) AS NAME,
TO_TIMESTAMP_NTZ(DATE_FROM::DATE) AS DATE_FROM,
--SOFT_CODING_KEYFLEX_ID::NUMBER(15,0) AS SOFT_CODING_KEYFLEX_ID,--excluded as always NULL
LOCATION_ID::NUMBER(15,0) AS LOCATION_ID,
--COST_ALLOCATION_KEYFLEX_ID::NUMBER(9,0) AS COST_ALLOCATION_KEYFLEX_ID,--excluded as always NULL
BUSINESS_GROUP_ID::NUMBER(15,0) AS BUSINESS_GROUP_ID,
ORGANIZATION_ID::NUMBER(9,0) AS ORGANIZATION_ID,
CREATED_BY::NUMBER(15,0) AS CREATED_BY,
--NULLIF(TRIM(ATTRIBUTE12::string), '') AS ATTRIBUTE12,--excluded as always NULL
NULLIF(TRIM(ATTRIBUTE10::string), '') AS ATTRIBUTE10,
UPPER(NULLIF(TRIM(TYPE::string), '')) AS TYPE,
--NULLIF(TRIM(COMMENTS::string), '') AS COMMENTS,--excluded as always NULL
TO_TIMESTAMP_NTZ(DATE_TO::DATE) AS DATE_TO,
--NULLIF(TRIM(PARTY_ID::string), '') AS PARTY_ID,--excluded as always NULL
OBJECT_VERSION_NUMBER::NUMBER(9,0) AS OBJECT_VERSION_NUMBER
FROM {{ref('prep_hr_all_organization_units')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORGANIZATION_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1