{{
  config(
    materialized = "view",
    alias = "wip_entities",
    schema='EBS'
  )
}}

SELECT
  WIP_ENTITY_ID::NUMBER AS WIP_ENTITY_ID,/*PK*/
  ORGANIZATION_ID::NUMBER AS ORGANIZATION_ID,
  TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE,
  LAST_UPDATED_BY::NUMBER AS LAST_UPDATED_BY,
  TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE,
  CREATED_BY::NUMBER AS CREATED_BY,
  LAST_UPDATE_LOGIN::NUMBER AS LAST_UPDATE_LOGIN,
  --REQUEST_ID::NUMBER AS REQUEST_ID,/*Always Null*/
  --PROGRAM_APPLICATION_ID::NUMBER AS PROGRAM_APPLICATION_ID,/*Always Null*/
  --PROGRAM_ID::NUMBER AS PROGRAM_ID,/*Always Null*/
  TO_TIMESTAMP_NTZ(PROGRAM_UPDATE_DATE::string) AS PROGRAM_UPDATE_DATE,
  UPPER(NULLIF(TRIM(WIP_ENTITY_NAME::string),'')) AS WIP_ENTITY_NAME,
  ENTITY_TYPE::NUMBER AS ENTITY_TYPE,
  INITCAP(NULLIF(TRIM(DESCRIPTION::string),'')) AS DESCRIPTION,
  PRIMARY_ITEM_ID::NUMBER AS PRIMARY_ITEM_ID,
  GEN_OBJECT_ID::NUMBER AS GEN_OBJECT_ID   
FROM {{ref('prep_wip_entities')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY WIP_ENTITY_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1