{{
  config(
    materialized = "view",
    alias = "hz_locations",
    schema='EBS'
  )
}}


SELECT LOCATION_ID::NUMBER(15,0) AS LOCATION_ID
       ,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::STRING) AS LAST_UPDATE_DATE
       ,LAST_UPDATED_BY::NUMBER(15,0) AS LAST_UPDATED_BY
       ,TO_TIMESTAMP_NTZ(CREATION_DATE::STRING) AS CREATION_DATE
       ,CREATED_BY::NUMBER(15,0) AS CREATED_BY
       ,LAST_UPDATE_LOGIN::NUMBER(15,0) AS LAST_UPDATE_LOGIN
       ,REQUEST_ID::NUMBER(15,0) AS REQUEST_ID
       ,PROGRAM_APPLICATION_ID::NUMBER(15,0) AS PROGRAM_APPLICATION_ID
       ,PROGRAM_ID::NUMBER(15,0) AS PROGRAM_ID
       ,TO_TIMESTAMP_NTZ(PROGRAM_UPDATE_DATE::STRING) AS PROGRAM_UPDATE_DATE
       --,TO_TIMESTAMP_NTZ(WH_UPDATE_DATE::STRING) AS WH_UPDATE_DATE --Excluded always NULL
       --,NULLIF(TRIM(ATTRIBUTE_CATEGORY::string), '') AS ATTRIBUTE_CATEGORY  --Excluded always NULL
       --,NULLIF(TRIM(ATTRIBUTE1::string), '') AS ATTRIBUTE1  --Excluded always NULL
       ,NULLIF(TRIM(ATTRIBUTE2::string), '') AS ATTRIBUTE2
       --,NULLIF(TRIM(ATTRIBUTE3::string), '') AS ATTRIBUTE3  --Excluded always NULL
       --,NULLIF(TRIM(ATTRIBUTE4::string), '') AS ATTRIBUTE4  --Excluded always NULL
       ,UPPER(NULLIF(TRIM(ATTRIBUTE6::string), '')) AS ATTRIBUTE6
       ,CASE
        WHEN LENGTH(ATTRIBUTE7::STRING) = 10 AND POSITION('/', ATTRIBUTE7::STRING) = 3
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE7::STRING, 'DD/MM/YYYY')
        WHEN LENGTH(ATTRIBUTE7::STRING) = 10 AND POSITION('/', ATTRIBUTE7::STRING) = 5
             THEN TRY_TO_TIMESTAMP(ATTRIBUTE7::STRING, 'YYYY/MM/DD')
        ELSE NULL
       END AS ATTRIBUTE7
       ,UPPER(NULLIF(TRIM(ATTRIBUTE8::string), '')) AS ATTRIBUTE8
       ,UPPER(NULLIF(TRIM(ATTRIBUTE9::string), '')) AS ATTRIBUTE9
       --,UPPER(NULLIF(TRIM(ATTRIBUTE10::string), '')) AS ATTRIBUTE10
       --,UPPER(NULLIF(TRIM(ATTRIBUTE11::string), '')) AS ATTRIBUTE11
       --,NULLIF(TRIM(ATTRIBUTE12::string), '') AS ATTRIBUTE12 --Excluded always NULL
       --,NULLIF(TRIM(ATTRIBUTE13::string), '') AS ATTRIBUTE13 --Excluded always NULL
       --,NULLIF(TRIM(ATTRIBUTE14::string), '') AS ATTRIBUTE14 --Excluded always NULL
       --,NULLIF(TRIM(ATTRIBUTE15::string), '') AS ATTRIBUTE15 --Excluded always NULL
       --,NULLIF(TRIM(ATTRIBUTE16::string), '') AS ATTRIBUTE16 --Excluded always NULL
       --,NULLIF(TRIM(ATTRIBUTE17::string), '') AS ATTRIBUTE17 --Excluded always NULL
       --,NULLIF(TRIM(ATTRIBUTE18::string), '') AS ATTRIBUTE18 --Excluded always NULL
       --,NULLIF(TRIM(ATTRIBUTE19::string), '') AS ATTRIBUTE19 --Excluded always NULL
       --,NULLIF(TRIM(ATTRIBUTE20::string), '') AS ATTRIBUTE20 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE_CATEGORY::string), '') AS GLOBAL_ATTRIBUTE_CATEGORY --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE1::string), '') AS GLOBAL_ATTRIBUTE1 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE2::string), '') AS GLOBAL_ATTRIBUTE2 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE3::string), '') AS GLOBAL_ATTRIBUTE3 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE4::string), '') AS GLOBAL_ATTRIBUTE4 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE5::string), '') AS GLOBAL_ATTRIBUTE5 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE6::string), '') AS GLOBAL_ATTRIBUTE6 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE7::string), '') AS GLOBAL_ATTRIBUTE7 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE8::string), '') AS GLOBAL_ATTRIBUTE8 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE9::string), '') AS GLOBAL_ATTRIBUTE9 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE10::string), '') AS GLOBAL_ATTRIBUTE10 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE11::string), '') AS GLOBAL_ATTRIBUTE11 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE12::string), '') AS GLOBAL_ATTRIBUTE12 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE13::string), '') AS GLOBAL_ATTRIBUTE13 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE14::string), '') AS GLOBAL_ATTRIBUTE14 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE15::string), '') AS GLOBAL_ATTRIBUTE15 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE16::string), '') AS GLOBAL_ATTRIBUTE16 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE17::string), '') AS GLOBAL_ATTRIBUTE17 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE18::string), '') AS GLOBAL_ATTRIBUTE18 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE19::string), '') AS GLOBAL_ATTRIBUTE19 --Excluded always NULL
       --,NULLIF(TRIM(GLOBAL_ATTRIBUTE20::string), '') AS GLOBAL_ATTRIBUTE20 --Excluded always NULL
       ,UPPER(NULLIF(TRIM(ORIG_SYSTEM_REFERENCE::string), '')) AS ORIG_SYSTEM_REFERENCE
       ,UPPER(NULLIF(TRIM(COUNTRY::string), '')) AS COUNTRY
       ,INITCAP(NULLIF(TRIM(ADDRESS1::string), '')) AS ADDRESS1
       ,INITCAP(NULLIF(TRIM(ADDRESS2::string), '')) AS ADDRESS2
       ,INITCAP(NULLIF(TRIM(ADDRESS3::string), '')) AS ADDRESS3
       ,UPPER(NULLIF(TRIM(ADDRESS4::string), '')) AS ADDRESS4
       ,INITCAP(NULLIF(TRIM(CITY::string), '')) AS CITY
       ,UPPER(NULLIF(TRIM(POSTAL_CODE::string), '')) AS POSTAL_CODE
       ,UPPER(NULLIF(TRIM(STATE::string), '')) AS STATE
       ,UPPER(NULLIF(TRIM(PROVINCE::string), '')) AS PROVINCE
       ,INITCAP(NULLIF(TRIM(COUNTY::string), '')) AS COUNTY
       ,UPPER(NULLIF(TRIM(ADDRESS_KEY::string), '')) AS ADDRESS_KEY
       --,NULLIF(TRIM(ADDRESS_STYLE::string), '') AS ADDRESS_STYLE --Excluded always NULL
       ,UPPER(NULLIF(TRIM(VALIDATED_FLAG::string), '')) AS VALIDATED_FLAG
       --,UPPER(NULLIF(TRIM(ADDRESS_LINES_PHONETIC::string), '')) AS ADDRESS_LINES_PHONETIC --Excluded always NULL
       --,UPPER(NULLIF(TRIM(APARTMENT_FLAG::string), '')) AS APARTMENT_FLAG --Excluded always NULL
       --,UPPER(NULLIF(TRIM(PO_BOX_NUMBER::string), '')) AS PO_BOX_NUMBER --Excluded always NULL
       --,UPPER(NULLIF(TRIM(HOUSE_NUMBER::string), '')) AS HOUSE_NUMBER --Excluded always NULL
       --,UPPER(NULLIF(TRIM(STREET_SUFFIX::string), '')) AS STREET_SUFFIX --Excluded always NULL
       --,UPPER(NULLIF(TRIM(APARTMENT_NUMBER::string), '')) AS APARTMENT_NUMBER --Excluded always NULL
       --,UPPER(NULLIF(TRIM(SECONDARY_SUFFIX_ELEMENT::string), '')) AS SECONDARY_SUFFIX_ELEMENT --Excluded always NULL
       --,UPPER(NULLIF(TRIM(STREET::string), '')) AS STREET --Excluded always NULL
       --,UPPER(NULLIF(TRIM(RURAL_ROUTE_TYPE::string), '')) AS RURAL_ROUTE_TYPE --Excluded always NULL
       --,UPPER(NULLIF(TRIM(RURAL_ROUTE_NUMBER::string), '')) AS RURAL_ROUTE_NUMBER --Excluded always NULL
       --,UPPER(NULLIF(TRIM(STREET_NUMBER::string), '')) AS STREET_NUMBER --Excluded always NULL
       --,UPPER(NULLIF(TRIM(BUILDING::string), '')) AS BUILDING --Excluded always NULL
       --,UPPER(NULLIF(TRIM(FLOOR::string), '')) AS FLOOR --Excluded always NULL
       --,UPPER(NULLIF(TRIM(SUITE::string), '')) AS SUITE --Excluded always NULL
       --,UPPER(NULLIF(TRIM(ROOM::string), '')) AS ROOM --Excluded always NULL
       --,UPPER(NULLIF(TRIM(POSTAL_PLUS4_CODE::string), '')) AS POSTAL_PLUS4_CODE --Excluded always NULL
       --,UPPER(NULLIF(TRIM(TIME_ZONE::string), '')) AS TIME_ZONE --Excluded always NULL
       --,UPPER(NULLIF(TRIM(OVERSEAS_ADDRESS_FLAG::string), '')) AS OVERSEAS_ADDRESS_FLAG --Excluded always NULL
       --,UPPER(NULLIF(TRIM(POST_OFFICE::string), '')) AS POST_OFFICE --Excluded always NULL
       --,UPPER(NULLIF(TRIM(POSITION::string), '')) AS POSITION --Excluded always NULL
       --,UPPER(NULLIF(TRIM(DELIVERY_POINT_CODE::string), '')) AS DELIVERY_POINT_CODE --Excluded always NULL
       --,UPPER(NULLIF(TRIM(LOCATION_DIRECTIONS::string), '')) AS LOCATION_DIRECTIONS --Excluded always NULL
       --,TO_TIMESTAMP_NTZ(ADDRESS_EFFECTIVE_DATE::STRING) AS ADDRESS_EFFECTIVE_DATE --Excluded always NULL
       --,TO_TIMESTAMP_NTZ(ADDRESS_EXPIRATION_DATE::STRING) AS ADDRESS_EXPIRATION_DATE --Excluded always NULL
       --,UPPER(NULLIF(TRIM(ADDRESS_ERROR_CODE::string), '')) AS ADDRESS_ERROR_CODE --Excluded always NULL
       --,UPPER(NULLIF(TRIM(CLLI_CODE::string), '')) AS CLLI_CODE --Excluded always NULL
       --,UPPER(NULLIF(TRIM(DODAAC::string), '')) AS DODAAC --Excluded always NULL
       --,UPPER(NULLIF(TRIM(TRAILING_DIRECTORY_CODE::string), '')) AS TRAILING_DIRECTORY_CODE --Excluded always NULL
       ,UPPER(NULLIF(TRIM(LANGUAGE::string), '')) AS LANGUAGE
       --,UPPER(NULLIF(TRIM(LIFE_CYCLE_STATUS::string), '')) AS LIFE_CYCLE_STATUS --Excluded always NULL
       --,UPPER(NULLIF(TRIM(SHORT_DESCRIPTION::string), '')) AS SHORT_DESCRIPTION --Excluded always NULL
       --,UPPER(NULLIF(TRIM(DESCRIPTION::string), '')) AS DESCRIPTION --Excluded always NULL
       ,UPPER(NULLIF(TRIM(CONTENT_SOURCE_TYPE::string), '')) AS CONTENT_SOURCE_TYPE
       --,LOC_HIERARCHY_ID::NUMBER(15,0) AS LOC_HIERARCHY_ID --Excluded always NULL
       --,UPPER(NULLIF(TRIM(SALES_TAX_GEOCODE::string), '')) AS SALES_TAX_GEOCODE --Excluded always NULL
       ,UPPER(NULLIF(TRIM(SALES_TAX_INSIDE_CITY_LIMITS::string), '')) AS SALES_TAX_INSIDE_CITY_LIMITS
       --,FA_LOCATION_ID::NUMBER(15,0) AS FA_LOCATION_ID --Excluded always NULL
       ,OBJECT_VERSION_NUMBER::NUMBER AS OBJECT_VERSION_NUMBER
       ,UPPER(NULLIF(TRIM(CREATED_BY_MODULE::string), '')) AS CREATED_BY_MODULE
       ,APPLICATION_ID::NUMBER AS APPLICATION_ID
       ,TIMEZONE_ID::NUMBER AS TIMEZONE_ID
       ,UPPER(NULLIF(TRIM(GEOMETRY_STATUS_CODE::string), '')) AS GEOMETRY_STATUS_CODE /*Contains 1 Value*/
       ,UPPER(NULLIF(TRIM(ACTUAL_CONTENT_SOURCE::string), '')) AS ACTUAL_CONTENT_SOURCE
       ,UPPER(NULLIF(TRIM(VALIDATION_STATUS_CODE::string), '')) AS VALIDATION_STATUS_CODE
       --,TO_TIMESTAMP_NTZ(DATE_VALIDATED::STRING) AS DATE_VALIDATED --Excluded always NULL
       --,UPPER(NULLIF(TRIM(DO_NOT_VALIDATE_FLAG::string), '')) AS DO_NOT_VALIDATE_FLAG --Excluded always NULL
       --,UPPER(NULLIF(TRIM(GEOMETRY::GEOGRAPHY), '')) AS GEOMETRY --Excluded always NULL
FROM {{ref('prep_hz_locations')}}
 QUALIFY ROW_NUMBER() OVER (PARTITION BY LOCATION_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1