{{
  config(
    materialized = "view",
    alias = "cmg_eam_kpi_areas",
    schema='EBS'
  )
}}

SELECT
    AREA_ID::NUMBER AS AREA_ID,
    UPPER(NULLIF(TRIM(AREA_NAME::string),'')) AS AREA_NAME,
    PRODUCT_LINE_ID::NUMBER AS PRODUCT_LINE_ID,
    SHOP_ID::NUMBER AS SHOP_ID,
    TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE,
    TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE,
    ORGANIZATION_ID::NUMBER AS ORGANIZATION_ID,
    UPPER(NULLIF(TRIM(ENABLED_FLAG::string),'')) AS ENABLED_FLAG
FROM {{ref('prep_cmg_eam_kpi_areas')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY AREA_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1