{{
  config(
    materialized = "view",
    alias = "fnd_flex_values_tl",
    schema='EBS'
  )
}}

SELECT

  /*String Fields*/
   NULLIF(TRIM(DESCRIPTION::string),'') AS DESCRIPTION
  ,UPPER(NULLIF(TRIM(LANGUAGE::string),'')) AS LANGUAGE
  ,UPPER(NULLIF(TRIM(SOURCE_LANG::string),'')) AS SOURCE_LANG
  ,UPPER(NULLIF(TRIM(FLEX_VALUE_MEANING::string),'')) AS FLEX_VALUE_MEANING

  /*Numeric Fields*/
  ,LAST_UPDATE_LOGIN::INTEGER AS LAST_UPDATE_LOGIN
  ,CREATED_BY::INTEGER AS CREATED_BY
  ,LAST_UPDATED_BY::INTEGER AS LAST_UPDATED_BY
  ,FLEX_VALUE_ID::INTEGER AS FLEX_VALUE_ID

   /*Date Fields*/
   ,TO_TIMESTAMP_NTZ(CREATION_DATE::STRING) AS CREATION_DATE
   ,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::STRING) AS LAST_UPDATE_DATE

FROM {{ref('prep_fnd_flex_values_tl')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY FLEX_VALUE_ID,LANGUAGE,DESCRIPTION ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1