{{
  config(
    materialized = "view",
    alias = "hz_cust_acct_sites_all",
    schema='EBS'
  )
}}

SELECT

/*Always Null*/
  -- ADDRESS_TEXT::string AS ADDRESS_TEXT,
  -- ATTRIBUTE_CATEGORY::string AS ATTRIBUTE_CATEGORY,
  -- ATTRIBUTE1::string AS ATTRIBUTE1,
  -- ATTRIBUTE10::string AS ATTRIBUTE10,
  -- ATTRIBUTE11::string AS ATTRIBUTE11,
  -- ATTRIBUTE12::string AS ATTRIBUTE12,
  -- ATTRIBUTE13::string AS ATTRIBUTE13,
  -- ATTRIBUTE14::string AS ATTRIBUTE14,
  -- ATTRIBUTE15::string AS ATTRIBUTE15,
  -- ATTRIBUTE16::string AS ATTRIBUTE16,
  -- ATTRIBUTE17::string AS ATTRIBUTE17,
  -- ATTRIBUTE18::string AS ATTRIBUTE18,
  -- ATTRIBUTE19::string AS ATTRIBUTE19,
  -- ATTRIBUTE20::string AS ATTRIBUTE20,
  -- ATTRIBUTE3::string AS ATTRIBUTE3,
  -- ATTRIBUTE4::string AS ATTRIBUTE4,
  -- ATTRIBUTE5::string AS ATTRIBUTE5,
  -- ATTRIBUTE6::string AS ATTRIBUTE6,
  -- ATTRIBUTE7::string AS ATTRIBUTE7,
  -- ATTRIBUTE8::string AS ATTRIBUTE8,
  -- ATTRIBUTE9::string AS ATTRIBUTE9,
  -- ECE_TP_LOCATION_CODE::string AS ECE_TP_LOCATION_CODE,
  -- GLOBAL_ATTRIBUTE_CATEGORY::string AS GLOBAL_ATTRIBUTE_CATEGORY,
  -- GLOBAL_ATTRIBUTE1::string AS GLOBAL_ATTRIBUTE1,
  -- GLOBAL_ATTRIBUTE10::string AS GLOBAL_ATTRIBUTE10,
  -- GLOBAL_ATTRIBUTE11::string AS GLOBAL_ATTRIBUTE11,
  -- GLOBAL_ATTRIBUTE12::string AS GLOBAL_ATTRIBUTE12,
  -- GLOBAL_ATTRIBUTE13::string AS GLOBAL_ATTRIBUTE13,
  -- GLOBAL_ATTRIBUTE14::string AS GLOBAL_ATTRIBUTE14,
  -- GLOBAL_ATTRIBUTE15::string AS GLOBAL_ATTRIBUTE15,
  -- GLOBAL_ATTRIBUTE16::string AS GLOBAL_ATTRIBUTE16,
  -- GLOBAL_ATTRIBUTE17::string AS GLOBAL_ATTRIBUTE17,
  -- GLOBAL_ATTRIBUTE18::string AS GLOBAL_ATTRIBUTE18,
  -- GLOBAL_ATTRIBUTE19::string AS GLOBAL_ATTRIBUTE19,
  -- GLOBAL_ATTRIBUTE2::string AS GLOBAL_ATTRIBUTE2,
  -- GLOBAL_ATTRIBUTE20::string AS GLOBAL_ATTRIBUTE20,
  -- GLOBAL_ATTRIBUTE3::string AS GLOBAL_ATTRIBUTE3,
  -- GLOBAL_ATTRIBUTE4::string AS GLOBAL_ATTRIBUTE4,
  -- GLOBAL_ATTRIBUTE5::string AS GLOBAL_ATTRIBUTE5,
  -- GLOBAL_ATTRIBUTE6::string AS GLOBAL_ATTRIBUTE6,
  -- GLOBAL_ATTRIBUTE7::string AS GLOBAL_ATTRIBUTE7,
  -- GLOBAL_ATTRIBUTE8::string AS GLOBAL_ATTRIBUTE8,
  -- GLOBAL_ATTRIBUTE9::string AS GLOBAL_ATTRIBUTE9,
  -- MARKET_FLAG::string AS MARKET_FLAG, 
  -- PRIMARY_SPECIALIST_ID::string AS PRIMARY_SPECIALIST_ID,
  -- SECONDARY_SPECIALIST_ID::string AS SECONDARY_SPECIALIST_ID,
  -- SERVICE_TERRITORY_ID::string AS SERVICE_TERRITORY_ID,
  -- TERRITORY::string AS TERRITORY,
  -- TERRITORY_ID::string AS TERRITORY_ID,
  -- TP_HEADER_ID::string AS TP_HEADER_ID,
  -- TRANSLATED_CUSTOMER_NAME::string AS TRANSLATED_CUSTOMER_NAME,
  -- WH_UPDATE_DATE::string AS WH_UPDATE_DATE


  /*Numeric Fields*/
  APPLICATION_ID::number AS APPLICATION_ID,
  CREATED_BY::number AS CREATED_BY,
  CUST_ACCOUNT_ID::number AS CUST_ACCOUNT_ID,
  CUST_ACCT_SITE_ID::number AS CUST_ACCT_SITE_ID,
  LAST_UPDATE_LOGIN::number AS LAST_UPDATE_LOGIN,
  LAST_UPDATED_BY::number AS LAST_UPDATED_BY,
  OBJECT_VERSION_NUMBER::number AS OBJECT_VERSION_NUMBER,
  ORG_ID::number AS ORG_ID,
  PARTY_SITE_ID::number AS PARTY_SITE_ID,
  PROGRAM_APPLICATION_ID::number AS PROGRAM_APPLICATION_ID,
  PROGRAM_ID::number AS PROGRAM_ID,  
  REQUEST_ID::number AS REQUEST_ID,
  

  /*String Field*/
  NULLIF(TRIM(ATTRIBUTE2::string), '') AS ATTRIBUTE2,
  UPPER(NULLIF(TRIM(BILL_TO_FLAG::string), '')) AS BILL_TO_FLAG,
  UPPER(NULLIF(TRIM(CREATED_BY_MODULE::string), '')) AS CREATED_BY_MODULE,
  UPPER(NULLIF(TRIM(CUSTOMER_CATEGORY_CODE::string), '')) AS CUSTOMER_CATEGORY_CODE,
  UPPER(NULLIF(TRIM(KEY_ACCOUNT_FLAG::string), '')) AS KEY_ACCOUNT_FLAG,
  UPPER(NULLIF(TRIM(LANGUAGE::string), '')) AS LANGUAGE,
  NULLIF(TRIM(ORIG_SYSTEM_REFERENCE::string), '') AS ORIG_SYSTEM_REFERENCE,
  UPPER(NULLIF(TRIM(SHIP_TO_FLAG::string), '')) AS SHIP_TO_FLAG,
  UPPER(NULLIF(TRIM(STATUS::string), '')) AS STATUS,

  /*Date Fields*/
  TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE,
  TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE,
  TO_TIMESTAMP_NTZ(PROGRAM_UPDATE_DATE::string) AS PROGRAM_UPDATE_DATE
  
FROM 
{{ref('prep_hz_cust_acct_sites_all')}}
 QUALIFY ROW_NUMBER() OVER (PARTITION BY CUST_ACCOUNT_ID,CUST_ACCT_SITE_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1