{{
  config(
    materialized = "view",
    alias = "cmg_pa_analysis",
    schema='EBS'
  )
}}

SELECT
SHIPPED_UOM::NUMBER(30,5) AS SHIPPED_UOM,
SHIPPED_LBS::NUMBER(30,5) AS SHIPPED_LBS,
COGS_AMOUNT::NUMBER(30,5) AS COGS_AMOUNT,
REVENUE_AMOUNT::NUMBER(30,5) AS REVENUE_AMOUNT,
NULLIF(TRIM(PERIOD_NAME::string),'') AS PERIOD_NAME,
ORGANIZATION_ID::NUMBER(15,0) AS ORGANIZATION_ID,
BILL_TO_ADDRESS_ID::NUMBER(15,0) AS BILL_TO_ADDRESS_ID,
TASK_ID::NUMBER(15,0) AS TASK_ID,
PROJECT_ID::NUMBER(15,0) AS PROJECT_ID,
ORG_ID::NUMBER(15,0) AS ORG_ID,
TO_TIMESTAMP_NTZ(MONTH_ENDING_DATE::string) AS MONTH_ENDING_DATE,
NULLIF(TRIM(MEMBER_FLAG::string),'') AS MEMBER_FLAG,
SHIPPED_UNITS::NUMBER(30,5) AS SHIPPED_UNITS,
ADJUST_AMOUNT::NUMBER(30,5) AS ADJUST_AMOUNT,
NULLIF(TRIM(PRINT_FLAG::string),'') AS PRINT_FLAG,
BACKCHARGE_AMOUNT::NUMBER(30,5) AS BACKCHARGE_AMOUNT,
TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE
FROM {{ref('prep_cmg_pa_analysis')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORG_ID,PROJECT_ID,TASK_ID,PERIOD_NAME,ORGANIZATION_ID,PRINT_FLAG,MONTH_ENDING_DATE,MEMBER_FLAG ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1