{{
  config(
    materialized = "view",
    alias = "cmg_pa_shipped_quantities",
    schema='EBS'
  )
}}

SELECT
CREATED_BY::number AS CREATED_BY
,TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE
,LAST_UPDATED_BY::number AS LAST_UPDATED_BY
,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE
,LAST_UPDATE_LOGIN::number AS LAST_UPDATE_LOGIN
,PROJECT_ID::number AS PROJECT_ID
,TASK_ID::number AS TASK_ID
,ORG_ID::number AS ORG_ID
,ORGANIZATION_ID::number AS ORGANIZATION_ID
,UPPER(NULLIF(TRIM(TASK_FAMILY::string),'')) AS TASK_FAMILY
,TO_TIMESTAMP_NTZ(TRANSACTION_DATE::string) AS TRANSACTION_DATE
,SHIPPED_QUANTITY::number AS SHIPPED_QUANTITY
,SHIPPED_UNITS::number AS SHIPPED_UNITS
,SHIPPED_UOM::number AS SHIPPED_UOM
,BILL_OF_LADING_NUMBER::number AS BILL_OF_LADING_NUMBER
,TO_TIMESTAMP_NTZ(BILL_OF_LADING_DATE::string) AS BILL_OF_LADING_DATE
,UPPER(NULLIF(TRIM(FOB::string),'')) AS FOB
,UPPER(NULLIF(TRIM(FOB_DESCRIPTION::string),'')) AS FOB_DESCRIPTION
,UPPER(NULLIF(TRIM(SHIP_VIA::string),'')) AS SHIP_VIA
,SHIP_VIA_DESCRIPTION::string AS SHIP_VIA_DESCRIPTION
,SHIPPED_QUANTITY_NOT_NAFTA::number AS SHIPPED_QUANTITY_NOT_NAFTA
,UPPER(NULLIF(TRIM(EVENT_FLAG::string),'')) AS EVENT_FLAG
,UPPER(NULLIF(TRIM(NON_NAFTA_ORIGIN::string),'')) AS NON_NAFTA_ORIGIN
,UPPER(NULLIF(TRIM(DESCRIPTION::string),'')) AS DESCRIPTION
,BACKORDER_QUANTITY::number AS BACKORDER_QUANTITY
,ORDERED_QUANTITY::number AS ORDERED_QUANTITY
,UPPER(NULLIF(TRIM(COMMENTS::string),'')) AS COMMENTS
,UPPER(NULLIF(TRIM(COMMENT_BOTTOM::string),'')) AS COMMENT_BOTTOM
,NULLIF(TRIM(ADDRESS1::string),'') AS ADDRESS1
,NULLIF(TRIM(ADDRESS2::string),'') AS ADDRESS2
,INITCAP(NULLIF(TRIM(CITY::string),'')) AS CITY
,UPPER(NULLIF(TRIM(STATE_PROVINCE::string),'')) AS STATE_PROVINCE
,NULLIF(TRIM(POSTAL_CODE::string),'') AS POSTAL_CODE
,INVOICE_AMOUNT::number AS INVOICE_AMOUNT
,UPPER(NULLIF(TRIM(QUANTITY_TYPE::string),'')) AS QUANTITY_TYPE
,SHOP_BOLT_SHIP_QTY::number AS SHOP_BOLT_SHIP_QTY
,SHOP_BOLT_SHIP_UNITS::number AS SHOP_BOLT_SHIP_UNITS
,SHOP_BOLT_SHIP_QTY_NOT_NAFTA::number AS SHOP_BOLT_SHIP_QTY_NOT_NAFTA
,UPPER(NULLIF(TRIM(STRUMIS_DELIVERY_NOTE::string),'')) AS STRUMIS_DELIVERY_NOTE
,UPPER(TRIM(ORIGINAL_TASK_NUMBER::string)) AS ORIGINAL_TASK_NUMBER
,UPPER(NULLIF(TRIM(CUSTOMS_DESCRIPTION::string),'')) AS CUSTOMS_DESCRIPTION
FROM {{ref('prep_cmg_pa_shipped_quantities')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY EVENT_FLAG::STRING, PROJECT_ID::NUMBER, BILL_OF_LADING_NUMBER::NUMBER, TASK_ID::NUMBER ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1