{{
  config(
    materialized = "view",
    alias = "cm50_ap_invoice_distribution",
    schema='EBS'
  )
}}

with raw_data_deduplicated as (

  SELECT *
  FROM {{ref('prep_cm50_ap_invoice_distribution')}}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY AID_INVOICE_DISTRIBUTION_ID ORDER BY TO_TIMESTAMP_NTZ(AID_LAST_UPDATE_DATE) DESC) = 1 

)

SELECT 
AID_ACCOUNTING_DATE::date as AID_ACCOUNTING_DATE
, AID_ACCOUNTING_EVENT_ID::number(38,0) as AID_ACCOUNTING_EVENT_ID
, AID_ACCRUAL_POSTED_FLAG::string as AID_ACCRUAL_POSTED_FLAG
, AID_AMOUNT::number(38,2) as AID_AMOUNT
, AID_AMOUNT_INCLUDES_TAX_FLAG::string as AID_AMOUNT_INCLUDES_TAX_FLAG
, COALESCE(
        TRY_TO_TIMESTAMP_NTZ(AID_AP_INTERFACED::STRING, 'YYYYMMDDHH24MISS'),
        TRY_TO_TIMESTAMP_NTZ(AID_AP_INTERFACED::STRING, 'YYYY/MM/DD HH24:MI:SS'),
        TRY_TO_TIMESTAMP_NTZ(AID_AP_INTERFACED::STRING, 'YYYY-MM-DD HH24:MI:SS') -- Safe addition for hyphenated dates
    ) AS AID_AP_INTERFACED
, AID_AP_MODEL_NO::string as AID_AP_MODEL_NO
, AID_ASSETS_ADDITION_FLAG::string as AID_ASSETS_ADDITION_FLAG
, AID_ASSETS_TRACKING_FLAG::string as AID_ASSETS_TRACKING_FLAG
, AID_ATTRIBUTE8::string as AID_ATTRIBUTE8
, AID_ATTRIBUTE9::string as AID_ATTRIBUTE9
, AID_ATTRIBUTE_CATEGORY::string as AID_ATTRIBUTE_CATEGORY
, AID_BASE_AMOUNT::number(38,2) as AID_BASE_AMOUNT
, AID_BASE_INVE_PRCE_VARIANCE::number(38,2) as AID_BASE_INVE_PRCE_VARIANCE
, AID_BASE_QUANTITY_VARIANCE::number(38,2) as AID_BASE_QUANTITY_VARIANCE
, AID_BATCH_ID::number(38,0) as AID_BATCH_ID
, AID_CANCELLATION_FLAG::string as AID_CANCELLATION_FLAG
, AID_CASH_POSTED_FLAG::string as AID_CASH_POSTED_FLAG
, AID_CM_PA_CC_AR_INV_ID::number(38,0) as AID_CM_PA_CC_AR_INV_ID
, AID_CREATED_BY::number(38,0) as AID_CREATED_BY
, TO_TIMESTAMP_NTZ(AID_CREATION_DATE) as AID_CREATION_DATE
, AID_DESCRIPTION::string as AID_DESCRIPTION
, AID_DISTRIBUTION_LINE_NUMBER::number(38,0) as AID_DISTRIBUTION_LINE_NUMBER
, AID_DIST_CODE_COMBINATION_ID::number(38,0) as AID_DIST_CODE_COMBINATION_ID
, AID_DIST_MATCH_TYPE::string as AID_DIST_MATCH_TYPE
, AID_ENCUMBERED_FLAG::string as AID_ENCUMBERED_FLAG
, AID_EXCHANGE_DATE::date as AID_EXCHANGE_DATE
, AID_EXCHANGE_RATE::number(38,8) as AID_EXCHANGE_RATE
, AID_EXCHANGE_RATE_TYPE::string as AID_EXCHANGE_RATE_TYPE
, AID_EXCHANGE_RATE_VARIANCE::number(38,2) as AID_EXCHANGE_RATE_VARIANCE
, TO_TIMESTAMP_NTZ(AID_EXPENDITURE_ITEM_DATE) as AID_EXPENDITURE_ITEM_DATE
, AID_EXPENDITURE_ORG_ID::number(38,0) as AID_EXPENDITURE_ORG_ID
, AID_EXPENDITURE_TYPE::string as AID_EXPENDITURE_TYPE
, AID_FINAL_MATCH_FLAG::string as AID_FINAL_MATCH_FLAG
, AID_GL_DETAIL_ACTIVITY::string as AID_GL_DETAIL_ACTIVITY
, AID_GL_LOCATION::string as AID_GL_LOCATION
, AID_INCOME_TAX_REGION::string as AID_INCOME_TAX_REGION
, AID_INVENTORY_TRANSFER_STATUS::string as AID_INVENTORY_TRANSFER_STATUS
, AID_INVOICE_DISTRIBUTION_ID::number(38,0) as AID_INVOICE_DISTRIBUTION_ID
, AID_INVOICE_ID::number(38,0) as AID_INVOICE_ID
, AID_INVOICE_INCL_PRPAY_FLAG::string as AID_INVOICE_INCL_PRPAY_FLAG
, AID_INVOICE_PRICE_VARIANCE::number(38,2) as AID_INVOICE_PRICE_VARIANCE
, AID_LAST_UPDATED_BY::number(38,0) as AID_LAST_UPDATED_BY
, TO_TIMESTAMP_NTZ(AID_LAST_UPDATE_DATE) as AID_LAST_UPDATE_DATE
, AID_LAST_UPDATE_LOGIN::number(38,0) as AID_LAST_UPDATE_LOGIN
, AID_LINE_TYPE_LOOKUP_CODE::string as AID_LINE_TYPE_LOOKUP_CODE
, AID_MATCHED_UOM_LOOKUP_CODE::string as AID_MATCHED_UOM_LOOKUP_CODE
, AID_MATCH_STATUS_FLAG::string as AID_MATCH_STATUS_FLAG
, AID_ORG_ID::number(38,0) as AID_ORG_ID
, AID_PARENT_INVOICE_ID::number(38,0) as AID_PARENT_INVOICE_ID
, AID_PARENT_REVERSAL_ID::number(38,0) as AID_PARENT_REVERSAL_ID
, AID_PA_ADDITION_FLAG::string as AID_PA_ADDITION_FLAG
, AID_PA_CC_AR_INVOICE_ID::number(38,0) as AID_PA_CC_AR_INVOICE_ID
, AID_PA_CC_AR_INVOICE_LINE_NUM::number(38,0) as AID_PA_CC_AR_INVOICE_LINE_NUM
, AID_PA_QUANTITY::number(38,5) as AID_PA_QUANTITY
, AID_PERIOD_NAME::string as AID_PERIOD_NAME
, AID_POSTED_FLAG::string as AID_POSTED_FLAG
, AID_PO_DISTRIBUTION_ID::number(38,0) as AID_PO_DISTRIBUTION_ID
, AID_PO_FLEET_WORK_ORDER::string as AID_PO_FLEET_WORK_ORDER
, AID_PO_TAG_NUMBER::string as AID_PO_TAG_NUMBER
, AID_PREPAY_AMOUNT_REMAINING::number(38,2) as AID_PREPAY_AMOUNT_REMAINING
, AID_PREPAY_DISTRIBUTION_ID::number(38,0) as AID_PREPAY_DISTRIBUTION_ID
, AID_PREPAY_TAX_PARENT_ID::number(38,0) as AID_PREPAY_TAX_PARENT_ID
, AID_PRICE_ADJUSTMENT_FLAG::string as AID_PRICE_ADJUSTMENT_FLAG
, AID_PRICE_CORRECT_INV_ID::number(38,0) as AID_PRICE_CORRECT_INV_ID
, AID_PRICE_CORRECT_QTY::number(38,15) as AID_PRICE_CORRECT_QTY
, AID_PRICE_VAR_CODE_COM_ID::number(38,0) as AID_PRICE_VAR_CODE_COM_ID
, AID_PROGRAM_APPLICATION_ID::number(38,0) as AID_PROGRAM_APPLICATION_ID
, AID_PROGRAM_ID::number(38,0) as AID_PROGRAM_ID
, TO_TIMESTAMP_NTZ(AID_PROGRAM_UPDATE_DATE) as AID_PROGRAM_UPDATE_DATE
, AID_PROJECT_ACCOUNTING_CONTEXT::string as AID_PROJECT_ACCOUNTING_CONTEXT
, AID_PROJECT_ID::number(38,0) as AID_PROJECT_ID
, AID_QUANTITY_INVOICED::number(38,15) as AID_QUANTITY_INVOICED
, AID_QUANTITY_VARIANCE::number(38,2) as AID_QUANTITY_VARIANCE
, AID_RATE_VAR_CDE_COMB_ID::number(38,0) as AID_RATE_VAR_CDE_COMB_ID
, AID_REQUEST_ID::number(38,0) as AID_REQUEST_ID
, AID_REVERSAL_FLAG::string as AID_REVERSAL_FLAG
, AID_SET_OF_BOOKS_ID::number(38,0) as AID_SET_OF_BOOKS_ID
, AID_TASK_ID::number(38,0) as AID_TASK_ID
, AID_TAX_CALCULATED_FLAG::string as AID_TAX_CALCULATED_FLAG
, AID_TAX_CODE_ID::number(38,0) as AID_TAX_CODE_ID
, AID_TAX_CODE_OVERRIDE_FLAG::string as AID_TAX_CODE_OVERRIDE_FLAG
, AID_TAX_RECOVERABLE_FLAG::string as AID_TAX_RECOVERABLE_FLAG
, AID_TAX_RECOVERY_OVERRIDE_FLAG::string as AID_TAX_RECOVERY_OVERRIDE_FLAG
, AID_TAX_RECOVERY_RATE::number(38,4) as AID_TAX_RECOVERY_RATE
, AID_TYPE_1099::string as AID_TYPE_1099
, AID_UNIT_PRICE::number(38,19) as AID_UNIT_PRICE
from raw_data_deduplicated