{{
  config(
    materialized = "view",
    alias = "gl_periods",
    schema='EBS'
  )
}}

SELECT


  /*String Fields*/
  UPPER(NULLIF(TRIM(ADJUSTMENT_PERIOD_FLAG::string),'')) AS ADJUSTMENT_PERIOD_FLAG,
  UPPER(NULLIF(TRIM(ENTERED_PERIOD_NAME::string),'')) AS ENTERED_PERIOD_NAME,
  UPPER(NULLIF(TRIM(PERIOD_SET_NAME::string),'')) AS PERIOD_SET_NAME,
  UPPER(NULLIF(TRIM(PERIOD_NAME::string),'')) AS PERIOD_NAME,
  INITCAP(NULLIF(TRIM(PERIOD_TYPE::string),'')) AS PERIOD_TYPE,

  
  /*Always Null*/
  -- ATTRIBUTE1::string AS ATTRIBUTE1,
  -- ATTRIBUTE2::string AS ATTRIBUTE2,
  -- ATTRIBUTE3::string AS ATTRIBUTE3,
  -- ATTRIBUTE4::string AS ATTRIBUTE4,
  -- ATTRIBUTE5::string AS ATTRIBUTE5,
  -- ATTRIBUTE6::string AS ATTRIBUTE6,
  -- ATTRIBUTE7::string AS ATTRIBUTE7,
  -- ATTRIBUTE8::string AS ATTRIBUTE8,
  -- CONTEXT::string AS CONTEXT,
  -- DESCRIPTION::string AS DESCRIPTION,

  
 /*Numeric Fields*/
  CREATED_BY::number AS CREATED_BY,
  LAST_UPDATE_LOGIN::number AS LAST_UPDATE_LOGIN,
  LAST_UPDATED_BY::number AS LAST_UPDATED_BY,
  PERIOD_NUM::number AS PERIOD_NUM, 
  PERIOD_YEAR::number AS PERIOD_YEAR,
  QUARTER_NUM::number AS QUARTER_NUM,

  
  /*Date Fields*/
  TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE,
  TO_TIMESTAMP_NTZ(END_DATE::string) AS END_DATE,
  TO_TIMESTAMP_NTZ(QUARTER_START_DATE::string) AS QUARTER_START_DATE,
  TO_TIMESTAMP_NTZ(START_DATE::string) AS START_DATE,
  TO_TIMESTAMP_NTZ(YEAR_START_DATE::string) AS YEAR_START_DATE,
  TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE 

FROM {{ref('prep_gl_periods')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY PERIOD_NAME ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1