{{
  config(
    materialized = "view",
    alias = "fnd_flex_values",
    schema='EBS',
    tags=["fnd_flex_values"]
  )
}}

SELECT
 FLEX_VALUE_SET_ID::number AS FLEX_VALUE_SET_ID
 ,NULLIF(TRIM(FLEX_VALUE_ID::number),'') AS FLEX_VALUE_ID
 ,UPPER(NULLIF(TRIM(FLEX_VALUE::string),'')) AS FLEX_VALUE
 ,TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE
 ,LAST_UPDATED_BY::number AS LAST_UPDATED_BY
 ,TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE
 ,CREATED_BY::number AS CREATED_BY
 ,LAST_UPDATE_LOGIN::number AS LAST_UPDATE_LOGIN
 ,UPPER(NULLIF(TRIM(ENABLED_FLAG::string),'')) AS ENABLED_FLAG
 ,UPPER(NULLIF(TRIM(SUMMARY_FLAG::string),'')) AS SUMMARY_FLAG
 ,TO_TIMESTAMP_NTZ(START_DATE_ACTIVE::string) AS START_DATE_ACTIVE
 ,TO_TIMESTAMP_NTZ(END_DATE_ACTIVE::string) AS END_DATE_ACTIVE
 ,UPPER(NULLIF(TRIM(PARENT_FLEX_VALUE_LOW::string),'')) AS PARENT_FLEX_VALUE_LOW
 --,UPPER(NULLIF(TRIM(PARENT_FLEX_VALUE_HIGH::string),'')) AS PARENT_FLEX_VALUE_HIGH  -- all null
 --,STRUCTURED_HIERARCHY_LEVEL::number AS STRUCTURED_HIERARCHY_LEVEL --all null
 ,UPPER(NULLIF(TRIM(HIERARCHY_LEVEL::string),'')) AS HIERARCHY_LEVEL
 ,UPPER(NULLIF(TRIM(COMPILED_VALUE_ATTRIBUTES::string),'')) AS COMPILED_VALUE_ATTRIBUTES
 ,UPPER(NULLIF(TRIM(VALUE_CATEGORY::string),'')) AS VALUE_CATEGORY
 ,UPPER(NULLIF(TRIM(ATTRIBUTE1::string),'')) AS ATTRIBUTE1
 ,UPPER(NULLIF(TRIM(ATTRIBUTE2::string),'')) AS ATTRIBUTE2
 ,UPPER(NULLIF(TRIM(ATTRIBUTE3::string),'')) AS ATTRIBUTE3
 ,UPPER(NULLIF(TRIM(ATTRIBUTE4::string),'')) AS ATTRIBUTE4
 ,UPPER(NULLIF(TRIM(ATTRIBUTE5::string),'')) AS ATTRIBUTE5
 ,UPPER(NULLIF(TRIM(ATTRIBUTE6::string),'')) AS ATTRIBUTE6
 ,UPPER(NULLIF(TRIM(ATTRIBUTE7::string),'')) AS ATTRIBUTE7
 ,UPPER(NULLIF(TRIM(ATTRIBUTE8::string),'')) AS ATTRIBUTE8
 ,UPPER(NULLIF(TRIM(ATTRIBUTE9::string),'')) AS ATTRIBUTE9
 ,UPPER(NULLIF(TRIM(ATTRIBUTE10::string),'')) AS ATTRIBUTE10
 ,UPPER(NULLIF(TRIM(ATTRIBUTE11::string),'')) AS ATTRIBUTE11
 ,UPPER(NULLIF(TRIM(ATTRIBUTE12::string),'')) AS ATTRIBUTE12
 ,UPPER(NULLIF(TRIM(ATTRIBUTE13::string),'')) AS ATTRIBUTE13
 ,UPPER(NULLIF(TRIM(ATTRIBUTE14::string),'')) AS ATTRIBUTE14
 ,UPPER(NULLIF(TRIM(ATTRIBUTE15::string),'')) AS ATTRIBUTE15
 ,UPPER(NULLIF(TRIM(ATTRIBUTE16::string),'')) AS ATTRIBUTE16
 /*all null*/
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE17::string),'')) AS ATTRIBUTE17
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE18::string),'')) AS ATTRIBUTE18
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE19::string),'')) AS ATTRIBUTE19
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE20::string),'')) AS ATTRIBUTE20
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE21::string),'')) AS ATTRIBUTE21
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE22::string),'')) AS ATTRIBUTE22
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE23::string),'')) AS ATTRIBUTE23
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE24::string),'')) AS ATTRIBUTE24
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE25::string),'')) AS ATTRIBUTE25
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE26::string),'')) AS ATTRIBUTE26
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE27::string),'')) AS ATTRIBUTE27
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE28::string),'')) AS ATTRIBUTE28
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE29::string),'')) AS ATTRIBUTE29
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE30::string),'')) AS ATTRIBUTE30
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE31::string),'')) AS ATTRIBUTE31
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE32::string),'')) AS ATTRIBUTE32
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE33::string),'')) AS ATTRIBUTE33
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE34::string),'')) AS ATTRIBUTE34
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE35::string),'')) AS ATTRIBUTE35
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE36::string),'')) AS ATTRIBUTE36
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE37::string),'')) AS ATTRIBUTE37
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE38::string),'')) AS ATTRIBUTE38
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE39::string),'')) AS ATTRIBUTE39
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE40::string),'')) AS ATTRIBUTE40
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE41::string),'')) AS ATTRIBUTE41
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE42::string),'')) AS ATTRIBUTE42
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE43::string),'')) AS ATTRIBUTE43
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE44::string),'')) AS ATTRIBUTE44
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE45::string),'')) AS ATTRIBUTE45
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE46::string),'')) AS ATTRIBUTE46
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE47::string),'')) AS ATTRIBUTE47
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE48::string),'')) AS ATTRIBUTE48
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE49::string),'')) AS ATTRIBUTE49
 -- ,UPPER(NULLIF(TRIM(ATTRIBUTE50::string),'')) AS ATTRIBUTE50
 -- ,ATTRIBUTE_SORT_ORDER::number AS ATTRIBUTE_SORT_ORDER
   
FROM {{ref('prep_fnd_flex_values')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY FLEX_VALUE_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1