{{
  config(
    materialized = "view",
    alias = "po_vendors",
    schema='EBS'
  )
}}



SELECT
TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE
,VENDOR_ID::integer AS VENDOR_ID
-- ,GLOBAL_ATTRIBUTE5::string AS GLOBAL_ATTRIBUTE5
-- ,GLOBAL_ATTRIBUTE4::string AS GLOBAL_ATTRIBUTE4
-- ,GLOBAL_ATTRIBUTE3::string AS GLOBAL_ATTRIBUTE3
-- ,GLOBAL_ATTRIBUTE2::string AS GLOBAL_ATTRIBUTE2
-- ,GLOBAL_ATTRIBUTE1::string AS GLOBAL_ATTRIBUTE1
-- ,AWT_GROUP_ID::string AS AWT_GROUP_ID
,ALLOW_AWT_FLAG::string AS ALLOW_AWT_FLAG
--,CHECK_DIGITS::string AS CHECK_DIGITS
,TAX_REPORTING_NAME::string AS TAX_REPORTING_NAME
,EXCLUDE_FREIGHT_FROM_DISCOUNT::string AS EXCLUDE_FREIGHT_FROM_DISCOUNT
,AUTO_CALCULATE_INTEREST_FLAG::string AS AUTO_CALCULATE_INTEREST_FLAG
--,OFFSET_VAT_CODE::string AS OFFSET_VAT_CODE
--,PROGRAM_UPDATE_DATE::string AS PROGRAM_UPDATE_DATE
-- ,PROGRAM_ID::string AS PROGRAM_ID
-- ,PROGRAM_APPLICATION_ID::string AS PROGRAM_APPLICATION_ID
-- ,REQUEST_ID::string AS REQUEST_ID
-- ,ATTRIBUTE15::string AS ATTRIBUTE15
-- ,ATTRIBUTE14::string AS ATTRIBUTE14
-- ,ATTRIBUTE13::string AS ATTRIBUTE13
-- ,ATTRIBUTE12::string AS ATTRIBUTE12
-- ,ATTRIBUTE11::string AS ATTRIBUTE11
-- ,ATTRIBUTE10::string AS ATTRIBUTE10
-- ,ATTRIBUTE9::string AS ATTRIBUTE9
-- ,ATTRIBUTE8::string AS ATTRIBUTE8
-- ,ATTRIBUTE7::string AS ATTRIBUTE7
-- ,ATTRIBUTE6::string AS ATTRIBUTE6
-- ,ATTRIBUTE5::string AS ATTRIBUTE5
-- ,ATTRIBUTE3::string AS ATTRIBUTE3
,ATTRIBUTE2::string AS ATTRIBUTE2
,ATTRIBUTE1::string AS ATTRIBUTE1
-- ,ATTRIBUTE_CATEGORY::string AS ATTRIBUTE_CATEGORY
,FEDERAL_REPORTABLE_FLAG::string AS FEDERAL_REPORTABLE_FLAG
,STATE_REPORTABLE_FLAG::string AS STATE_REPORTABLE_FLAG
-- ,NAME_CONTROL::string AS NAME_CONTROL
,TO_TIMESTAMP_NTZ(TAX_VERIFICATION_DATE::string) AS TAX_VERIFICATION_DATE
,AMOUNT_INCLUDES_TAX_FLAG::string AS AMOUNT_INCLUDES_TAX_FLAG
,AUTO_TAX_CALC_OVERRIDE::string AS AUTO_TAX_CALC_OVERRIDE
,AUTO_TAX_CALC_FLAG::string AS AUTO_TAX_CALC_FLAG
,AP_TAX_ROUNDING_RULE::string AS AP_TAX_ROUNDING_RULE
,EXCLUSIVE_PAYMENT_FLAG::string AS EXCLUSIVE_PAYMENT_FLAG
,HOLD_UNMATCHED_INVOICES_FLAG::string AS HOLD_UNMATCHED_INVOICES_FLAG
,ALLOW_UNORDERED_RECEIPTS_FLAG::string AS ALLOW_UNORDERED_RECEIPTS_FLAG
,ALLOW_SUBSTITUTE_RECEIPTS_FLAG::string AS ALLOW_SUBSTITUTE_RECEIPTS_FLAG
,RECEIVING_ROUTING_ID::string AS RECEIVING_ROUTING_ID
,RECEIPT_DAYS_EXCEPTION_CODE::string AS RECEIPT_DAYS_EXCEPTION_CODE
,DAYS_LATE_RECEIPT_ALLOWED::string AS DAYS_LATE_RECEIPT_ALLOWED
,DAYS_EARLY_RECEIPT_ALLOWED::string AS DAYS_EARLY_RECEIPT_ALLOWED
,ENFORCE_SHIP_TO_LOCATION_CODE::string AS ENFORCE_SHIP_TO_LOCATION_CODE
,QTY_RCV_EXCEPTION_CODE::string AS QTY_RCV_EXCEPTION_CODE
,QTY_RCV_TOLERANCE::string AS QTY_RCV_TOLERANCE
,RECEIPT_REQUIRED_FLAG::string AS RECEIPT_REQUIRED_FLAG
-- ,PRICE_TOLERANCE::string AS PRICE_TOLERANCE
,TERMS_DATE_BASIS::string AS TERMS_DATE_BASIS
-- ,HOLD_DATE::string AS HOLD_DATE
-- ,HOLD_BY::string AS HOLD_BY
-- ,PURCHASING_HOLD_REASON::string AS PURCHASING_HOLD_REASON
,HOLD_FLAG::string AS HOLD_FLAG
-- ,STANDARD_INDUSTRY_CLASS::string AS STANDARD_INDUSTRY_CLASS
,SMALL_BUSINESS_FLAG::string AS SMALL_BUSINESS_FLAG
,WOMEN_OWNED_FLAG::string AS WOMEN_OWNED_FLAG
-- ,BANK_ACCOUNT_TYPE::string AS BANK_ACCOUNT_TYPE
,BANK_NUM::string AS BANK_NUM
,BANK_ACCOUNT_NUM::string AS BANK_ACCOUNT_NUM
-- ,BANK_ACCOUNT_NAME::string AS BANK_ACCOUNT_NAME
,PAYMENT_METHOD_LOOKUP_CODE::string AS PAYMENT_METHOD_LOOKUP_CODE
-- ,MINORITY_GROUP_LOOKUP_CODE::string AS MINORITY_GROUP_LOOKUP_CODE
,TO_TIMESTAMP_NTZ(END_DATE_ACTIVE::string) AS END_DATE_ACTIVE
,TO_TIMESTAMP_NTZ(START_DATE_ACTIVE::string) AS START_DATE_ACTIVE
-- ,VAT_CODE::string AS VAT_CODE
,ORGANIZATION_TYPE_LOOKUP_CODE::string AS ORGANIZATION_TYPE_LOOKUP_CODE
-- ,WITHHOLDING_START_DATE::string AS WITHHOLDING_START_DATE
-- ,WITHHOLDING_STATUS_LOOKUP_CODE::string AS WITHHOLDING_STATUS_LOOKUP_CODE
,TYPE_1099::string AS TYPE_1099
,NUM_1099::string AS NUM_1099
-- ,PREPAY_CODE_COMBINATION_ID::string AS PREPAY_CODE_COMBINATION_ID
-- ,EXPENSE_CODE_COMBINATION_ID::string AS EXPENSE_CODE_COMBINATION_ID
-- ,DISC_TAKEN_CODE_COMBINATION_ID::string AS DISC_TAKEN_CODE_COMBINATION_ID
-- ,DISC_LOST_CODE_COMBINATION_ID::string AS DISC_LOST_CODE_COMBINATION_ID
-- ,ACCTS_PAY_CODE_COMBINATION_ID::string AS ACCTS_PAY_CODE_COMBINATION_ID
-- ,DISTRIBUTION_SET_ID::string AS DISTRIBUTION_SET_ID
,HOLD_REASON::string AS HOLD_REASON
,HOLD_FUTURE_PAYMENTS_FLAG::string AS HOLD_FUTURE_PAYMENTS_FLAG
-- ,EXCHANGE_DATE_LOOKUP_CODE::string AS EXCHANGE_DATE_LOOKUP_CODE
-- ,INVOICE_AMOUNT_LIMIT::string AS INVOICE_AMOUNT_LIMIT
,PAYMENT_CURRENCY_CODE::string AS PAYMENT_CURRENCY_CODE
,INVOICE_CURRENCY_CODE::string AS INVOICE_CURRENCY_CODE
,PAYMENT_PRIORITY::string AS PAYMENT_PRIORITY
,PAY_GROUP_LOOKUP_CODE::string AS PAY_GROUP_LOOKUP_CODE
,PAY_DATE_BASIS_LOOKUP_CODE::string AS PAY_DATE_BASIS_LOOKUP_CODE
,ALWAYS_TAKE_DISC_FLAG::string AS ALWAYS_TAKE_DISC_FLAG
-- ,CREDIT_STATUS_LOOKUP_CODE::string AS CREDIT_STATUS_LOOKUP_CODE
,SET_OF_BOOKS_ID::string AS SET_OF_BOOKS_ID
,TERMS_ID::string AS TERMS_ID
-- ,FOB_LOOKUP_CODE::string AS FOB_LOOKUP_CODE
-- ,FREIGHT_TERMS_LOOKUP_CODE::string AS FREIGHT_TERMS_LOOKUP_CODE
-- ,SHIP_VIA_LOOKUP_CODE::string AS SHIP_VIA_LOOKUP_CODE
,BILL_TO_LOCATION_ID::string AS BILL_TO_LOCATION_ID
-- ,SHIP_TO_LOCATION_ID::string AS SHIP_TO_LOCATION_ID
-- ,MIN_ORDER_AMOUNT::string AS MIN_ORDER_AMOUNT
-- ,PARENT_VENDOR_ID::string AS PARENT_VENDOR_ID
,ONE_TIME_FLAG::string AS ONE_TIME_FLAG
-- ,CUSTOMER_NUM::string AS CUSTOMER_NUM
,VENDOR_TYPE_LOOKUP_CODE::string AS VENDOR_TYPE_LOOKUP_CODE
,EMPLOYEE_ID::integer AS EMPLOYEE_ID
,CREATED_BY::integer AS CREATED_BY
,TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE
,LAST_UPDATE_LOGIN::integer AS LAST_UPDATE_LOGIN
-- ,SEGMENT5::string AS SEGMENT5
-- ,SEGMENT4::string AS SEGMENT4
-- ,SEGMENT2::string AS SEGMENT2
,ENABLED_FLAG::string AS ENABLED_FLAG
,SUMMARY_FLAG::string AS SUMMARY_FLAG
,SEGMENT1::string AS SEGMENT1
,VENDOR_NAME_ALT::string AS VENDOR_NAME_ALT
,VENDOR_NAME::string AS VENDOR_NAME
,LAST_UPDATED_BY::integer AS LAST_UPDATED_BY
-- ,BANK_BRANCH_TYPE::string AS BANK_BRANCH_TYPE
-- ,BANK_CHARGE_BEARER::string AS BANK_CHARGE_BEARER
-- ,EDI_REMITTANCE_INSTRUCTION::string AS EDI_REMITTANCE_INSTRUCTION
-- ,EDI_REMITTANCE_METHOD::string AS EDI_REMITTANCE_METHOD
-- ,EDI_PAYMENT_FORMAT::string AS EDI_PAYMENT_FORMAT
-- ,EDI_PAYMENT_METHOD::string AS EDI_PAYMENT_METHOD
-- ,EDI_TRANSACTION_HANDLING::string AS EDI_TRANSACTION_HANDLING
-- ,GLOBAL_ATTRIBUTE_CATEGORY::string AS GLOBAL_ATTRIBUTE_CATEGORY
-- ,GLOBAL_ATTRIBUTE20::string AS GLOBAL_ATTRIBUTE20
-- ,GLOBAL_ATTRIBUTE18::string AS GLOBAL_ATTRIBUTE18
-- ,GLOBAL_ATTRIBUTE17::string AS GLOBAL_ATTRIBUTE17
-- ,GLOBAL_ATTRIBUTE16::string AS GLOBAL_ATTRIBUTE16
-- ,GLOBAL_ATTRIBUTE15::string AS GLOBAL_ATTRIBUTE15
-- ,GLOBAL_ATTRIBUTE14::string AS GLOBAL_ATTRIBUTE14
-- ,GLOBAL_ATTRIBUTE13::string AS GLOBAL_ATTRIBUTE13
-- ,GLOBAL_ATTRIBUTE12::string AS GLOBAL_ATTRIBUTE12
-- ,GLOBAL_ATTRIBUTE11::string AS GLOBAL_ATTRIBUTE11
-- ,GLOBAL_ATTRIBUTE10::string AS GLOBAL_ATTRIBUTE10
-- ,GLOBAL_ATTRIBUTE9::string AS GLOBAL_ATTRIBUTE9
-- ,GLOBAL_ATTRIBUTE8::string AS GLOBAL_ATTRIBUTE8
-- ,GLOBAL_ATTRIBUTE7::string AS GLOBAL_ATTRIBUTE7
-- ,GLOBAL_ATTRIBUTE6::string AS GLOBAL_ATTRIBUTE6
-- ,GLOBAL_ATTRIBUTE19::string AS GLOBAL_ATTRIBUTE19
,VAT_REGISTRATION_NUM::string AS VAT_REGISTRATION_NUM
-- ,ATTRIBUTE4::string AS ATTRIBUTE4
,INSPECTION_REQUIRED_FLAG::string AS INSPECTION_REQUIRED_FLAG
,HOLD_ALL_PAYMENTS_FLAG::string AS HOLD_ALL_PAYMENTS_FLAG
-- ,SEGMENT3::string AS SEGMENT3
,BANK_NUMBER::string AS BANK_NUMBER
,OFFSET_TAX_FLAG::string AS OFFSET_TAX_FLAG
,CREATE_DEBIT_MEMO_FLAG::string AS CREATE_DEBIT_MEMO_FLAG
,FUTURE_DATED_PAYMENT_CCID::string AS FUTURE_DATED_PAYMENT_CCID
,MATCH_OPTION::string AS MATCH_OPTION
-- ,BUS_CLASS_LAST_CERTIFIED_BY::string AS BUS_CLASS_LAST_CERTIFIED_BY
-- ,BUS_CLASS_LAST_CERTIFIED_DATE::string AS BUS_CLASS_LAST_CERTIFIED_DATE
-- ,CIS_PARENT_VENDOR_ID::string AS CIS_PARENT_VENDOR_ID
-- ,VALIDATION_NUMBER::string AS VALIDATION_NUMBER
-- ,CREDIT_LIMIT::string AS CREDIT_LIMIT
,INDIVIDUAL_1099::string AS INDIVIDUAL_1099
-- ,CIS_VERIFICATION_DATE::string AS CIS_VERIFICATION_DATE
-- ,MATCH_STATUS_FLAG::string AS MATCH_STATUS_FLAG
-- ,VERIFICATION_REQUEST_ID::string AS VERIFICATION_REQUEST_ID
-- ,VERIFICATION_NUMBER::string AS VERIFICATION_NUMBER
-- ,NATIONAL_INSURANCE_NUMBER::string AS NATIONAL_INSURANCE_NUMBER
-- ,COMPANY_REGISTRATION_NUMBER::string AS COMPANY_REGISTRATION_NUMBER
-- ,WORK_REFERENCE::string AS WORK_REFERENCE
-- ,TRADING_NAME::string AS TRADING_NAME
-- ,SALUTATION::string AS SALUTATION
-- ,LAST_NAME::string AS LAST_NAME
-- ,SECOND_NAME::string AS SECOND_NAME
-- ,FIRST_NAME::string AS FIRST_NAME
-- ,CIS_ENABLED_FLAG::string AS CIS_ENABLED_FLAG
-- ,PARTNERSHIP_NAME::string AS PARTNERSHIP_NAME
-- ,PARTNERSHIP_UTR::string AS PARTNERSHIP_UTR
-- ,UNIQUE_TAX_REFERENCE_NUM::string AS UNIQUE_TAX_REFERENCE_NUM
,METADATA_FILENAME::string AS METADATA_FILENAME
,METADATA_FILE_ROW_NUMBER::string AS METADATA_FILE_ROW_NUMBER
,TO_TIMESTAMP_NTZ(METADATA_FILE_LAST_MODIFIED::string) AS METADATA_FILE_LAST_MODIFIED
,TO_TIMESTAMP_NTZ(METADATA_START_SCAN_TIME::string) AS METADATA_START_SCAN_TIME 
FROM {{ref('prep_po_vendors')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY VENDOR_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) =1