{{
  config(
    materialized = "view",
    alias = "eam_work_orders",
    schema='EBS'
  )
}}

SELECT

    -- ATTRIBUTE7::string AS ATTRIBUTE7,  /* Always Null */
    -- ATTRIBUTE6::string AS ATTRIBUTE6,  /* Always Null */
    -- ATTRIBUTE5::string AS ATTRIBUTE5,  /* Always Null */
    -- ATTRIBUTE4::string AS ATTRIBUTE4,  /* Always Null */
    -- ATTRIBUTE3::string AS ATTRIBUTE3,  /* Always Null */
    UPPER(NULLIF(TRIM(ATTRIBUTE2::string),'')) AS ATTRIBUTE_2,
    UPPER(NULLIF(TRIM(ATTRIBUTE1::string),'')) AS ATTRIBUTE_1,
    --ATTRIBUTE_CATEGORY::string AS ATTRIBUTE_CATEGORY,  /* Always Null */
    -- DEMAND_CLASS::string AS DEMAND_CLASS,             /* Always Null */   
    -- LOT_NUMBER::string AS LOT_NUMBER,                 /* Always Null */ 
    -- COMPLETION_LOCATOR_ID::string AS COMPLETION_LOCATOR_ID,      /* Always Null */
    -- COMPLETION_SUBINVENTORY::string AS COMPLETION_SUBINVENTORY,  /* Always Null */
    -- ROUTING_REVISION_DATE::string AS ROUTING_REVISION_DATE,      /* Always Null */
    -- ROUTING_REVISION::string AS ROUTING_REVISION,                /* Always Null */
    --ALTERNATE_ROUTING_DESIGNATOR::string AS ALTERNATE_ROUTING_DESIGNATOR,  /* Always Null */
    -- BOM_REVISION_DATE::string AS BOM_REVISION_DATE,  /* Always Null */
    -- BOM_REVISION::string AS BOM_REVISION,  /* Always Null */
    --ALTERNATE_BOM_DESIGNATOR::string AS ALTERNATE_BOM_DESIGNATOR,  /* Always Null */
    -- COMMON_ROUTING_SEQUENCE_ID::string AS COMMON_ROUTING_SEQUENCE_ID, /* Always Null */
    -- COMMON_BOM_SEQUENCE_ID::string AS COMMON_BOM_SEQUENCE_ID,  /* Always Null */
    -- ROUTING_REFERENCE_ID::string AS ROUTING_REFERENCE_ID,    /* Always Null */
    -- BOM_REFERENCE_ID::string AS BOM_REFERENCE_ID,            /* Always Null */
    -- REBUILD_SERIAL_NUMBER::string AS REBUILD_SERIAL_NUMBER,  /* Always Null */
    -- REBUILD_ITEM_ID::string AS REBUILD_ITEM_ID,              /* Always Null */
    -- PARENT_WIP_ENTITY_NAME::string AS PARENT_WIP_ENTITY_NAME,  /* Always Null */
    -- PARENT_WIP_ENTITY_ID::string AS PARENT_WIP_ENTITY_ID,      /* Always Null */
    TASK_ID::NUMBER AS TASK_ID,
    UPPER(NULLIF(TRIM(TASK_NAME::string),'')) AS TASK_NAME,
    UPPER(TRIM(TASK_NUMBER::string)) AS TASK_NUMBER,
    PROJECT_ID::NUMBER AS PROJECT_ID,
    UPPER(NULLIF(TRIM(PROJECT_NAME::string),'')) AS PROJECT_NAME,
    UPPER(NULLIF(TRIM(PROJECT_NUMBER::string),'')) AS PROJECT_NUMBER,
    -- SCHEDULE_GROUP_NAME::string AS SCHEDULE_GROUP_NAME,  /* Always Null */
    -- SCHEDULE_GROUP_ID::string AS SCHEDULE_GROUP_ID,      /* Always Null */
    FIRM_PLANNED_FLAG::NUMBER AS FIRM_PLANNED_FLAG,
    UPPER(NULLIF(TRIM(PLAN_MAINTENANCE::string),'')) AS PLAN_MAINTENANCE,
    UPPER(NULLIF(TRIM(TAGOUT_REQUIRED::string),'')) AS TAGOUT_REQUIRED,
    UPPER(NULLIF(TRIM(SHUTDOWN_TYPE_DISP::string),''))  AS SHUTDOWN_TYPE_DISP,
    UPPER(NULLIF(TRIM(SHUTDOWN_TYPE::string),''))  AS SHUTDOWN_TYPE,
    UPPER(NULLIF(TRIM(NOTIFICATION_REQUIRED::string),'')) AS NOTIFICATION_REQUIRED,
    ESTIMATION_STATUS::NUMBER AS ESTIMATION_STATUS,
    TO_TIMESTAMP_NTZ(REQUESTED_DUE_DATE::string) AS REQUESTED_DUE_DATE,
    TO_TIMESTAMP_NTZ(REQUESTED_START_DATE::string) AS REQUESTED_START_DATE,
    UPPER(NULLIF(TRIM(PRIORITY_DISP::string),'')) AS PRIORITY_DISP,
    PRIORITY::NUMBER AS PRIORITY,
    --ACTIVITY_CAUSE_DISP::string AS ACTIVITY_CAUSE_DISP, /* Always Null */
    --ACTIVITY_CAUSE::string AS ACTIVITY_CAUSE,      /* Always Null */
    UPPER(NULLIF(TRIM(ACTIVITY_TYPE_DISP::string),''))  AS ACTIVITY_TYPE_DISP,
    UPPER(NULLIF(TRIM(ACTIVITY_TYPE::string),''))  AS ACTIVITY_TYPE,
    UPPER(NULLIF(TRIM(OWNING_DEPARTMENT_CODE::string),''))  AS OWNING_DEPARTMENT_CODE,
    OWNING_DEPARTMENT::NUMBER AS OWNING_DEPARTMENT,
    TO_TIMESTAMP_NTZ(DATE_CLOSED::string) AS DATE_CLOSED,
    TO_TIMESTAMP_NTZ(DATE_COMPLETED::string) AS DATE_COMPLETED,
    TO_TIMESTAMP_NTZ(DATE_RELEASED::string) AS DATE_RELEASED,
    TO_TIMESTAMP_NTZ(SCHEDULED_COMPLETION_DATE::string) AS SCHEDULED_COMPLETION_DATE,
    TO_TIMESTAMP_NTZ(SCHEDULED_START_DATE::string) AS SCHEDULED_START_DATE,
    OVERHEAD_VARIANCE_ACCOUNT::NUMBER AS OVERHEAD_VARIANCE_ACCOUNT,
    OVERHEAD_ACCOUNT::NUMBER AS OVERHEAD_ACCOUNT,
    -- STD_COST_ADJUSTMENT_ACCOUNT::string AS STD_COST_ADJUSTMENT_ACCOUNT,  /* Always Null */
    OUTSIDE_PROC_VARIANCE_ACCOUNT::NUMBER AS OUTSIDE_PROC_VARIANCE_ACCOUNT,
    RESOURCE_VARIANCE_ACCOUNT::NUMBER AS RESOURCE_VARIANCE_ACCOUNT,
    MATERIAL_VARIANCE_ACCOUNT::NUMBER AS MATERIAL_VARIANCE_ACCOUNT,
    OUTSIDE_PROCESSING_ACCOUNT::NUMBER AS OUTSIDE_PROCESSING_ACCOUNT,
    RESOURCE_ACCOUNT::NUMBER AS RESOURCE_ACCOUNT,
    MATERIAL_OVERHEAD_ACCOUNT::NUMBER AS MATERIAL_OVERHEAD_ACCOUNT,
    MATERIAL_ACCOUNT::NUMBER AS MATERIAL_ACCOUNT,
    -- WORK_ORDER_TYPE_DISP::string AS WORK_ORDER_TYPE_DISP, /* Always Null */
    -- WORK_ORDER_TYPE::string AS WORK_ORDER_TYPE,          /* Always Null */
   -- MANUAL_REBUILD_FLAG::string AS MANUAL_REBUILD_FLAG,  /* Always Null */
    PM_SCHEDULE_ID::NUMBER AS PM_SCHEDULE_ID,
    UPPER(NULLIF(TRIM(STATUS_TYPE_DISP::string),''))  AS STATUS_TYPE_DISP,
    STATUS_TYPE::NUMBER AS STATUS_TYPE,
    UPPER(NULLIF(TRIM(CLASS_CODE::string),''))  AS CLASS_CODE,
    UPPER(NULLIF(TRIM(ASSET_DESCRIPTION::string),''))  AS ASSET_DESCRIPTION,
    UPPER(NULLIF(TRIM(ASSET_NUMBER::string),''))  AS ASSET_NUMBER,
    ASSET_GROUP_ID::NUMBER AS ASSET_GROUP_ID,
    PRIMARY_ITEM_ID::NUMBER AS PRIMARY_ITEM_ID,
    UPPER(NULLIF(TRIM(DESCRIPTION::string),''))  AS DESCRIPTION,
    LAST_UPDATE_LOGIN::NUMBER AS LAST_UPDATE_LOGIN,
    CREATED_BY::NUMBER AS CREATED_BY,
    TO_TIMESTAMP_NTZ(CREATION_DATE::string) AS CREATION_DATE,
    LAST_UPDATED_BY::NUMBER AS LAST_UPDATED_BY,
    TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE::string) AS LAST_UPDATE_DATE,
    ORGANIZATION_ID::NUMBER AS ORGANIZATION_ID,
    ENTITY_TYPE::NUMBER AS ENTITY_TYPE,
    WE_ROW_ID::string AS WE_ROW_ID,
    UPPER(NULLIF(TRIM(WIP_ENTITY_NAME::string),'')) AS WIP_ENTITY_NAME,
    WIP_ENTITY_ID::NUMBER AS WIP_ENTITY_ID,
    TO_TIMESTAMP_NTZ(ACTUAL_START_DATE::string) AS ACTUAL_START_DATE,
    UPPER(NULLIF(TRIM(SCHED_PARENT_WIP_ENTITY_NAME::string),'')) AS SCHED_PARENT_WIP_ENTITY_NAME,
    ROW_ID::string AS ROW_ID,
    UPPER(NULLIF(TRIM(RESOLUTION_CODE::string),'')) AS RESOLUTION_CODE,
    UPPER(NULLIF(TRIM(CAUSE_CODE::string),''))  AS CAUSE_CODE,
    UPPER(NULLIF(TRIM(FAILURE_CODE::string),'')) AS FAILURE_CODE,
    FAILURE_ENTRY_ID::NUMBER AS FAILURE_ENTRY_ID,
    FAILURE_ID::NUMBER AS FAILURE_ID,
    -- EAM_LINEAR_LOCATION_ID::string AS EAM_LINEAR_LOCATION_ID,  EAM_LINEAR_LOCATION_ID
    UPPER(NULLIF(TRIM(ACTIVITY_SOURCE_MEANING::string),''))  AS ACTIVITY_SOURCE_MEANING,
    UPPER(NULLIF(TRIM(ACTIVITY_SOURCE::string),''))  AS ACTIVITY_SOURCE,
    UPPER(NULLIF(TRIM(MATERIAL_ISSUE_BY_MO::string),''))  AS MATERIAL_ISSUE_BY_MO,
    -- SERVICE_REQUEST::string AS SERVICE_REQUEST,        /* Always Null */
    -- SERVICE_REQUEST_ID::string AS SERVICE_REQUEST_ID,  /* Always Null */
    MAINTENANCE_OBJECT_ID::NUMBER AS MAINTENANCE_OBJECT_ID,
    UPPER(NULLIF(TRIM(SOURCE::string),''))  AS SOURCE,
    MAINTENANCE_OBJECT_TYPE::NUMBER AS MAINTENANCE_OBJECT_TYPE,
    MAINTENANCE_OBJECT_SOURCE::NUMBER AS MAINTENANCE_OBJECT_SOURCE,
    -- INSTANCE_NUMBER::string AS INSTANCE_NUMBER, /* Always Null */
    INSTANCE_ID::NUMBER AS INSTANCE_ID,
    -- ATTRIBUTE15::string AS ATTRIBUTE15, /* Always Null */
    -- ATTRIBUTE14::string AS ATTRIBUTE14, /* Always Null */
    -- ATTRIBUTE13::string AS ATTRIBUTE13, /* Always Null */
    -- ATTRIBUTE12::string AS ATTRIBUTE12, /* Always Null */
    -- ATTRIBUTE11::string AS ATTRIBUTE11, /* Always Null */
    -- ATTRIBUTE10::string AS ATTRIBUTE10, /* Always Null */
    -- ATTRIBUTE9::string AS ATTRIBUTE9, /* Always Null */
    -- ATTRIBUTE8::string AS ATTRIBUTE8, /* Always Null */
    UPPER(NULLIF(TRIM(COMMENTS::string),''))  AS COMMENTS,
    TO_TIMESTAMP_NTZ(FAILURE_DATE::string) AS FAILURE_DATE,
    UPPER(NULLIF(TRIM(FAILURE_CODE_REQUIRED::string),'')) AS FAILURE_CODE_REQUIRED

FROM {{ref('prep_eam_work_orders')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY WIP_ENTITY_ID ORDER BY TO_TIMESTAMP_NTZ(LAST_UPDATE_DATE) DESC) = 1