{{
  config(
    materialized = "view",
    alias = "branch_office_business_unit_map",
    schema='enterprise_MANUAL'
  )
}}

SELECT 
    UPPER(TRIM(OFFICE_CODE::string))                          AS OFFICE_CODE
    ,UPPER(TRIM(BRANCH_OFFICE_CODE::string))                  AS BRANCH_OFFICE_CODE
    ,BUSINESS_UNIT_CODE::string                               AS BUSINESS_UNIT_CODE 
    ,IFNULL(RDM_LOB.STANDARD_APPLICATION_VALUE,'Not Found')   AS RDM_LINE_OF_BUSINESS_CODE
    ,IFNULL(RDM_LOB.STANDARD_APPLICATION_VALUE_NAME_FR,'Not Found') AS RDM_LINE_OF_BUSINESS_NAME_FR
    ,IFNULL(RDM_LOB.STANDARD_APPLICATION_VALUE_NAME_EN ,'Not Found') AS RDM_LINE_OF_BUSINESS_NAME_EN
FROM {{ ref ('prep_manual_branch_office_business_unit_map') }} BOBUM
 LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM_LOB 
    ON UPPER(TRIM(BOBUM.BUSINESS_UNIT_CODE)) = UPPER(RDM_LOB.BUSINESS_APPLICATION_VALUE)
    AND UPPER(RDM_LOB.BUSINESS_APPLICATION_DOMAIN_CODE) = 'LINESOFBUSINESS'
    AND UPPER(RDM_LOB.STANDARD_DOMAIN_APPLICATION_CODE) = 'LINESOFBUSINESS' 
    AND UPPER(RDM_LOB.BUSINESS_APPLICATION_CODE) = 'SPM'