{{
  config(
    materialized = "view",
    alias = "PROJECT_IMPACT",
    schema='INFOR'
  )
}}

SELECT
    UPPER(T.DATA:ACTIVITY::string) as ACTIVITY,
    NULLIF(T.DATA:ACTIVITY_DESC::string, '') as ACTIVITY_DESC,
    NULLIF(T.DATA:ACTIVITY_TYPE::string, '') as ACTIVITY_TYPE,
    T.DATA:AMT_DUE::NUMBER(38, 15) as AMT_DUE,
    NULLIF(T.DATA:BP_FIN_GROUP::string, '') as BP_FIN_GROUP,
    NULLIF(T.DATA:BP_FIN_GROUP_DESC::string, '') as BP_FIN_GROUP_DESC,
    T.DATA:BUDGET_PROFIT_LOSS::NUMBER(38, 15) as BUDGET_PROFIT_LOSS,
    T.DATA:BUDGET_REVENUE::NUMBER(38, 15) as BUDGET_REVENUE,
    T.DATA:BUDGET_TOT_COST::NUMBER(38, 15) as BUDGET_TOT_COST,
    NULLIF(UPPER(T.DATA:CATEGORY::string), '') as CATEGORY,
    NULLIF(T.DATA:CATEGORY_DESC::string, '') as CATEGORY_DESC,
    NULLIF(UPPER(T.DATA:CLIN::string), '') as CLIN,
    T.DATA:CLIN_AMT::NUMBER(38, 15) as CLIN_AMT,
    NULLIF(UPPER(T.DATA:CLIN_CURRENCY::string), '') as CLIN_CURRENCY,
    T.DATA:CLIN_RATE::integer as CLIN_RATE,
    T.DATA:FINANCIAL_CPY::integer as FINANCIAL_CPY,
    NULLIF(T.DATA:FINANCIAL_CPY_DESC::string, '') as FINANCIAL_CPY_DESC,
    T.DATA:FORECAST_TOT_COST::NUMBER(38, 15) as FORECAST_TOT_COST,
    NULLIF(UPPER(T.DATA:GEO_AREA::string), '') as GEO_AREA,
    NULLIF(T.DATA:GEO_AREA_DESC::string, '') as GEO_AREA_DESC,
    NULLIF(UPPER(T.DATA:"GROUP"::string), '') as "GROUP",
    NULLIF(T.DATA:GROUP_DESC::string, '') as GROUP_DESC,
    T.DATA:IMPACT_PERIOD::integer as IMPACT_PERIOD,
    T.DATA:IMPACT_YEAR::integer as IMPACT_YEAR,
    NULLIF(UPPER(T.DATA:INVOICE_TO_BP::string), '') as INVOICE_TO_BP,
    NULLIF(T.DATA:INVOICE_TO_BP_NAME::string, '') as INVOICE_TO_BP_NAME,
    NULLIF(UPPER(T.DATA:LINE_OF_BUSINESS::string), '') as LINE_OF_BUSINESS,
    NULLIF(T.DATA:LINE_OF_BUSINESS_DESC::string, '') as LINE_OF_BUSINESS_DESC,
    T.DATA:PERIOD_BILLING::NUMBER(38, 15) as PERIOD_BILLING,
    T.DATA:PERIOD_COST_HC::NUMBER(38, 15) as PERIOD_COST_HC,
    T.DATA:PERIOD_PROFIT_LOSS_HC::NUMBER(38, 15) as PERIOD_PROFIT_LOSS_HC,
    T.DATA:PERIOD_REVENUE_HC::NUMBER(38, 15) as PERIOD_REVENUE_HC,
    UPPER(T.DATA:PLAN::string) as PLAN,
    NULLIF(UPPER(T.DATA:PROJECT::string), '') as PROJECT,
    NULLIF(T.DATA:PROJECT_ACCOUNTANT::string, '') as PROJECT_ACCOUNTANT,
    NULLIF(UPPER(T.DATA:PROJECT_CURRENCY::string), '') as PROJECT_CURRENCY,
    NULLIF(T.DATA:PROJECT_DESC::string, '') as PROJECT_DESC,
    NULLIF(UPPER(T.DATA:PROJECT_MANAGER::string), '') as PROJECT_MANAGER,
    NULLIF(T.DATA:PROJECT_MANAGER_NAME::string, '') as PROJECT_MANAGER_NAME,
    NULLIF(UPPER(T.DATA:PROJECT_OFFICE::string), '') as PROJECT_OFFICE,
    NULLIF(T.DATA:PROJECT_OFFICE_DESC::string, '') as PROJECT_OFFICE_DESC,
    NULLIF(UPPER(T.DATA:PROJECT_STATUS::string), '') as PROJECT_STATUS,
    T.DATA:PTD_BILLING::NUMBER(38, 15) as PTD_BILLING,
    T.DATA:PTD_COST_HC::NUMBER(38, 15) as PTD_COST_HC,
    T.DATA:PTD_PROFIT_LOSS_HC::NUMBER(38, 15) as PTD_PROFIT_LOSS_HC,
    T.DATA:PTD_REVENUE_HC::NUMBER(38, 15) as PTD_REVENUE_HC,
    T.DATA:PTP_PTD_COST_RECOG::NUMBER(38, 15) as PTP_PTD_COST_RECOG,
    T.DATA:PTP_PTD_COST_RECOG_HC::NUMBER(38, 15) as PTP_PTD_COST_RECOG_HC,
    T.DATA:PTP_PTD_COST_TOAL_HC::NUMBER(38, 15) as PTP_PTD_COST_TOAL_HC,
    T.DATA:PTP_PTD_COST_TOTAL::NUMBER(38, 15) as PTP_PTD_COST_TOTAL,
    T.DATA:PTP_PTD_PROFIT_LOSS::NUMBER(38, 15) as PTP_PTD_PROFIT_LOSS,
    T.DATA:PTP_PTD_PROFIT_LOSS_HC::NUMBER(38, 15) as PTP_PTD_PROFIT_LOSS_HC,
    T.DATA:PTP_PTD_REVENUE::NUMBER(38, 15) as PTP_PTD_REVENUE,
    T.DATA:PTP_PTD_REVENUE_HC::NUMBER(38, 15) as PTP_PTD_REVENUE_HC,
    T.DATA:REMAIN_BILLING::NUMBER(38, 15) as REMAIN_BILLING,
    T.DATA:REMAIN_BILLING_PCT::string as REMAIN_BILLING_PCT,
    NULLIF(UPPER(T.DATA:STATUS::string), '') as STATUS,
    NULLIF(UPPER(T.DATA:TOTAL_TYPE::string), '') as TOTAL_TYPE,
    T.DATA:TOTAL_TYPE_CODE::integer as TOTAL_TYPE_CODE,
    TO_TIMESTAMP(T.DATA:TIMESTAMP::string) as TIMESTAMP,
    FILENAME as metadata_filename,
    FILE_ROW_NUMBER as metadata_file_row_number,
    FILE_LAST_MODIFIED as metadata_file_last_modified,
    START_SCAN_TIME as metatada_start_scan_time
FROM 
    {{ source("landing_infor", "PROJECT_IMPACT") }} T
WHERE 
  split(FILENAME, '_')[array_size(split(FILENAME, '_')) - 2] >=
  (SELECT min_timestamp
  FROM
      (SELECT split(FILENAME, '_')[array_size(split(FILENAME, '_')) - 2] AS min_timestamp, split(FILENAME, '/')[3] AS type_file
      FROM {{ source("landing_infor", "PROJECT_IMPACT") }} T
      WHERE type_file LIKE 'fullload%'
      QUALIFY ROW_NUMBER() OVER (ORDER BY min_timestamp DESC) = 1)
  )