{{ config(
    materialized='incremental',
    schema='NORMALIZE',
    unique_key='CUSTOMER_KEY',
    incremental_strategy='merge'
) }}

{% if is_incremental() %}

WITH watermark AS (

    SELECT
        COALESCE(
            MAX(LOAD_TIMESTAMP),
            TO_TIMESTAMP_NTZ('1900-01-01')
        ) AS MAX_LOAD_TIMESTAMP

    FROM {{ this }}

),

ranked AS (

    SELECT
        CUSTOMER_KEY,
        GEOGRAPHY_KEY,
        CUSTOMER_ALTERNATE_KEY,
        TITLE,
        FIRST_NAME,
        MIDDLE_NAME,
        LAST_NAME,
        NAME_STYLE,
        BIRTH_DATE,
        MARITAL_STATUS,
        SUFFIX,
        GENDER,
        EMAIL_ADDRESS,
        YEARLY_INCOME,
        TOTAL_CHILDREN,
        NUMBER_CHILDREN_AT_HOME,
        ENGLISH_EDUCATION,
        SPANISH_EDUCATION,
        FRENCH_EDUCATION,
        ENGLISH_OCCUPATION,
        SPANISH_OCCUPATION,
        FRENCH_OCCUPATION,
        HOUSE_OWNER_FLAG,
        NUMBER_CARS_OWNED,
        ADDRESS_LINE_1,
        ADDRESS_LINE_2,
        PHONE,
        DATE_FIRST_PURCHASE,
        COMMUTE_DISTANCE,
        SOURCE_FILE,
        LOAD_TIMESTAMP,

        ROW_NUMBER() OVER (
            PARTITION BY CUSTOMER_KEY
            ORDER BY LOAD_TIMESTAMP DESC
        ) AS RN

    FROM {{ ref('dim_customer_prepare') }}

    WHERE LOAD_TIMESTAMP > (
        SELECT MAX_LOAD_TIMESTAMP
        FROM watermark
    )
)

{% else %}

WITH ranked AS (

    SELECT
        CUSTOMER_KEY,
        GEOGRAPHY_KEY,
        CUSTOMER_ALTERNATE_KEY,
        TITLE,
        FIRST_NAME,
        MIDDLE_NAME,
        LAST_NAME,
        NAME_STYLE,
        BIRTH_DATE,
        MARITAL_STATUS,
        SUFFIX,
        GENDER,
        EMAIL_ADDRESS,
        YEARLY_INCOME,
        TOTAL_CHILDREN,
        NUMBER_CHILDREN_AT_HOME,
        ENGLISH_EDUCATION,
        SPANISH_EDUCATION,
        FRENCH_EDUCATION,
        ENGLISH_OCCUPATION,
        SPANISH_OCCUPATION,
        FRENCH_OCCUPATION,
        HOUSE_OWNER_FLAG,
        NUMBER_CARS_OWNED,
        ADDRESS_LINE_1,
        ADDRESS_LINE_2,
        PHONE,
        DATE_FIRST_PURCHASE,
        COMMUTE_DISTANCE,
        SOURCE_FILE,
        LOAD_TIMESTAMP,

        ROW_NUMBER() OVER (
            PARTITION BY CUSTOMER_KEY
            ORDER BY LOAD_TIMESTAMP DESC
        ) AS RN

    FROM {{ ref('dim_customer_prepare') }}
)

{% endif %}

SELECT

    CUSTOMER_KEY,
    GEOGRAPHY_KEY,
    UPPER(TRIM(CUSTOMER_ALTERNATE_KEY)) AS CUSTOMER_ALTERNATE_KEY,
    NULLIF(UPPER(TRIM(TITLE)), '') AS TITLE,

    INITCAP(TRIM(FIRST_NAME)) AS FIRST_NAME,
    INITCAP(TRIM(MIDDLE_NAME)) AS MIDDLE_NAME,
    INITCAP(TRIM(LAST_NAME)) AS LAST_NAME,

    NAME_STYLE,
    BIRTH_DATE,

    UPPER(TRIM(MARITAL_STATUS)) AS MARITAL_STATUS,

    NULLIF(UPPER(TRIM(SUFFIX)), '') AS SUFFIX,
    UPPER(TRIM(GENDER)) AS GENDER,

    LOWER(TRIM(EMAIL_ADDRESS)) AS EMAIL_ADDRESS,

    CAST(YEARLY_INCOME AS NUMBER(18,2)) AS YEARLY_INCOME,

    CAST(TOTAL_CHILDREN AS NUMBER(38,0)) AS TOTAL_CHILDREN,
    CAST(NUMBER_CHILDREN_AT_HOME AS NUMBER(38,0)) AS NUMBER_CHILDREN_AT_HOME,

    INITCAP(TRIM(ENGLISH_EDUCATION)) AS ENGLISH_EDUCATION,
    INITCAP(TRIM(SPANISH_EDUCATION)) AS SPANISH_EDUCATION,
    INITCAP(TRIM(FRENCH_EDUCATION)) AS FRENCH_EDUCATION,

    INITCAP(TRIM(ENGLISH_OCCUPATION)) AS ENGLISH_OCCUPATION,
    INITCAP(TRIM(SPANISH_OCCUPATION)) AS SPANISH_OCCUPATION,
    INITCAP(TRIM(FRENCH_OCCUPATION)) AS FRENCH_OCCUPATION,

    HOUSE_OWNER_FLAG,

    CAST(NUMBER_CARS_OWNED AS NUMBER(38,0)) AS NUMBER_CARS_OWNED,

    NULLIF(TRIM(ADDRESS_LINE_1), '') AS ADDRESS_LINE_1,
    NULLIF(TRIM(ADDRESS_LINE_2), '') AS ADDRESS_LINE_2,
    NULLIF(TRIM(PHONE), '') AS PHONE,

    DATE_FIRST_PURCHASE,

    TRIM(COMMUTE_DISTANCE) AS COMMUTE_DISTANCE,

    SOURCE_FILE,
    LOAD_TIMESTAMP

FROM ranked

WHERE RN = 1