{{ config(
    materialized='table',
    schema='NORMALIZE'
) }}

WITH ranked AS (

    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY PRODUCT_KEY
            ORDER BY LOAD_TIMESTAMP DESC
        ) AS RN

    FROM {{ ref('dim_product_prepare') }}

)

SELECT

    PRODUCT_KEY,

    UPPER(TRIM(PRODUCT_ALTERNATE_KEY)) AS PRODUCT_ALTERNATE_KEY,

    INITCAP(TRIM(ENGLISH_PRODUCT_NAME)) AS ENGLISH_PRODUCT_NAME,

    NULLIF(INITCAP(TRIM(COLOR)), '') AS COLOR,

    NULLIF(TRIM(SIZE), '') AS SIZE,

    CAST(STANDARD_COST AS NUMBER(19,4)) AS STANDARD_COST,
    CAST(LIST_PRICE AS NUMBER(19,4)) AS LIST_PRICE,

    CAST(PRODUCT_SUBCATEGORY_KEY AS NUMBER(38,0))
        AS PRODUCT_SUBCATEGORY_KEY,

    START_DATE,
    END_DATE,

    UPPER(TRIM(STATUS)) AS STATUS,

    --SOURCE_FILE,
    LOAD_TIMESTAMP,

    CURRENT_TIMESTAMP() AS CREATED_TIMESTAMP,
    CURRENT_TIMESTAMP() AS UPDATED_TIMESTAMP

FROM ranked
WHERE RN = 1