{{ config(
    materialized='table',
    schema='NORMALIZE'
) }}

SELECT
    PRODUCT_KEY,
    ORDER_DATE_KEY,
    DUE_DATE_KEY,
    SHIP_DATE_KEY,
    CUSTOMER_KEY,
    PROMOTION_KEY,
    CURRENCY_KEY,
    SALES_TERRITORY_KEY,

    TRIM(SALES_ORDER_NUMBER) AS SALES_ORDER_NUMBER,

    SALES_ORDER_LINE_NUMBER,
    REVISION_NUMBER,
    ORDER_QUANTITY,

    UNIT_PRICE,
    EXTENDED_AMOUNT,
    UNIT_PRICE_DISCOUNT_PCT,
    DISCOUNT_AMOUNT,
    PRODUCT_STANDARD_COST,
    TOTAL_PRODUCT_COST,
    SALES_AMOUNT,
    TAX_AMT,
    FREIGHT,

    NULLIF(TRIM(CARRIER_TRACKING_NUMBER), '') AS CARRIER_TRACKING_NUMBER,
    NULLIF(TRIM(CUSTOMER_PO_NUMBER), '') AS CUSTOMER_PO_NUMBER,

    ORDER_DATE,
    DUE_DATE,
    SHIP_DATE,

    SOURCE_FILE,
    LOAD_TIMESTAMP,

    CURRENT_TIMESTAMP() AS CREATED_TIMESTAMP,
    CURRENT_TIMESTAMP() AS UPDATED_TIMESTAMP

FROM {{ ref('fact_internet_sales_prepare') }}