{{ config(
    materialized='table',
    schema='NORMALIZE'
) }}

WITH source_data AS (

    SELECT
        PRODUCT_KEY,
        ORDER_DATE_KEY,
        DUE_DATE_KEY,
        SHIP_DATE_KEY,
        CUSTOMER_KEY,
        PROMOTION_KEY,
        CURRENCY_KEY,
        SALES_TERRITORY_KEY,

        UPPER(TRIM(SALES_ORDER_NUMBER)) AS SALES_ORDER_NUMBER,

        SALES_ORDER_LINE_NUMBER,
        REVISION_NUMBER,
        ORDER_QUANTITY,

        CAST(UNIT_PRICE AS NUMBER(19,4)) AS UNIT_PRICE,
        CAST(EXTENDED_AMOUNT AS NUMBER(19,4)) AS EXTENDED_AMOUNT,
        CAST(UNIT_PRICE_DISCOUNT_PCT AS NUMBER(19,4))
            AS UNIT_PRICE_DISCOUNT_PCT,
        CAST(DISCOUNT_AMOUNT AS NUMBER(19,4)) AS DISCOUNT_AMOUNT,
        CAST(PRODUCT_STANDARD_COST AS NUMBER(19,4))
            AS PRODUCT_STANDARD_COST,
        CAST(TOTAL_PRODUCT_COST AS NUMBER(19,4))
            AS TOTAL_PRODUCT_COST,
        CAST(SALES_AMOUNT AS NUMBER(19,4)) AS SALES_AMOUNT,
        CAST(TAX_AMT AS NUMBER(19,4)) AS TAX_AMT,
        CAST(FREIGHT AS NUMBER(19,4)) AS FREIGHT,

        NULLIF(UPPER(TRIM(CARRIER_TRACKING_NUMBER)), '')
            AS CARRIER_TRACKING_NUMBER,

        NULLIF(UPPER(TRIM(CUSTOMER_PO_NUMBER)), '')
            AS CUSTOMER_PO_NUMBER,

        TO_TIMESTAMP_NTZ(ORDER_DATE) AS ORDER_DATE,
        TO_TIMESTAMP_NTZ(DUE_DATE) AS DUE_DATE,
        TO_TIMESTAMP_NTZ(SHIP_DATE) AS SHIP_DATE

    FROM {{ ref('fact_internet_sales_prepare') }}

),

deduplicated AS (

    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY
                SALES_ORDER_NUMBER,
                SALES_ORDER_LINE_NUMBER
            ORDER BY
                REVISION_NUMBER DESC
        ) AS RN

    FROM source_data

)

SELECT
    PRODUCT_KEY,
    ORDER_DATE_KEY,
    DUE_DATE_KEY,
    SHIP_DATE_KEY,
    CUSTOMER_KEY,
    PROMOTION_KEY,
    CURRENCY_KEY,
    SALES_TERRITORY_KEY,

    SALES_ORDER_NUMBER,
    SALES_ORDER_LINE_NUMBER,
    REVISION_NUMBER,
    ORDER_QUANTITY,

    UNIT_PRICE,
    EXTENDED_AMOUNT,
    UNIT_PRICE_DISCOUNT_PCT,
    DISCOUNT_AMOUNT,
    PRODUCT_STANDARD_COST,
    TOTAL_PRODUCT_COST,
    SALES_AMOUNT,
    TAX_AMT,
    FREIGHT,

    CARRIER_TRACKING_NUMBER,
    CUSTOMER_PO_NUMBER,

    ORDER_DATE,
    DUE_DATE,
    SHIP_DATE,

    CURRENT_TIMESTAMP() AS CREATED_TIMESTAMP,
    CURRENT_TIMESTAMP() AS UPDATED_TIMESTAMP

FROM deduplicated

WHERE RN = 1