{{
  config(
    full_refresh = true,
    materialized="dynamic_table",
    target_lag="24 hour",
    snowflake_warehouse= var('task_warehouse'),
    alias = "project_booking",
    schema= "dataproducts_gold",
    post_hook = "ALTER DYNAMIC TABLE {{ this }} SET LOG_LEVEL = ERROR"
  
  )
}}

-- DATA PRODUCT : PROJECT_BOOKING

SELECT 
	DD.FULL_DATE :: DATE																			AS SALES_DATE,
	DD.CANAM_WEEK_START_DATE :: DATE																AS SALES_CANAM_WEEK_START_DATE,
	DD.CANAM_WEEK_NUMBER :: INTEGER																    AS SALES_CANAM_WEEK_NUMBER,
	DD.CALENDAR_MONTH_NUMBER :: INTEGER																AS SALES_CALENDAR_MONTH_NUMBER,
	DD.CALENDAR_MONTH_NAME_EN :: STRING																AS SALES_CALENDAR_MONTH_NAME_EN,
	DD.CALENDAR_YEAR :: INTEGER																		AS SALES_CALENDAR_YEAR,
	DD.FISCAL_PERIOD_NUMBER :: INTEGER																AS SALES_FISCAL_PERIOD_NUMBER,
	DD.FISCAL_PERIOD_NAME :: STRING																	AS SALES_FISCAL_PERIOD_NAME,
	DD.FISCAL_YEAR :: INTEGER																		AS SALES_FISCAL_YEAR,
	DBU.BUSINESS_UNIT_CODE :: STRING																AS BUSINESS_UNIT_CODE,
	DBU.BUSINESS_UNIT_NAME_FR :: STRING																AS BUSINESS_UNIT_NAME_FR,
	DBU.BUSINESS_UNIT_NAME_EN :: STRING																AS BUSINESS_UNIT_NAME_EN,
	UPPER(TRIM(DSO.SALES_OFFICE_DEPARTMENT_CODE)) :: STRING											AS SALES_OFFICE_DEPARTMENT_CODE,
	UPPER(TRIM(DSO.SALES_OFFICE_DEPARTMENT_NAME_EN)) :: STRING										AS SALES_OFFICE_DEPARTMENT_NAME,
	UPPER(TRIM(DSBO.SALES_BRANCH_OFFICE_DEPARTMENT_NAME_EN)) :: STRING                              AS SALES_BRANCH_OFFICE_DEPARTMENT_GROUP_NAME,
	DSO.SALES_OFFICE_DEPARTMENT_COUNTRY_CODE :: STRING												AS SALES_OFFICE_DEPARTMENT_COUNTRY_CODE,
	UPPER(TRIM(DSBO.SALES_BRANCH_OFFICE_DEPARTMENT_CODE)) :: STRING									AS SALES_BRANCH_OFFICE_DEPARTMENT_CODE,
	UPPER(TRIM(DSBO.SALES_BRANCH_OFFICE_DEPARTMENT_NAME_EN)) :: STRING								AS SALES_BRANCH_OFFICE_DEPARTMENT_NAME,
	DCU_FROM.CURRENCY_CODE :: STRING																AS ORIGINAL_CURRENCY_CODE,
	'NO BUDGET VARIATION' :: STRING																	AS BUDGET_VARIATION_TYPE_NAME,
	DP.PROJECT_CODE :: STRING																		AS PROJECT_CODE,
	DP.PROJECT_NAME_EN :: STRING																	AS PROJECT_NAME,
	DP.PROJECT_START_DATE :: DATE																	AS PROJECT_START_DATE,
	DP.PROJECT_CLOSE_DATE :: DATE																	AS PROJECT_CLOSE_DATE,
	DP.PROJECT_STATUS_CODE :: STRING																AS PROJECT_STATUS_CODE,
	DP.PROJECT_TYPE_CODE :: STRING																	AS PROJECT_TYPE_CODE,
	DP.PROJECT_CLASS_CATEGORY_NAME :: STRING														AS PROJECT_CLASS_CATEGORY_NAME,
	DP.PROJECT_CLASS_NAME :: STRING																	AS PROJECT_CLASS_NAME,
	DP.PROJECT_PACKAGE_STATUS_CODE :: STRING														AS PROJECT_PACKAGE_STATUS_CODE,
	DP.PROJECT_BUILD_MASTER_STATUS_CODE :: STRING 													AS PROJECT_BUILD_MASTER_STATUS_CODE,
	DP.PROJECT_MANAGER_FULL_NAME :: STRING 															AS PROJECT_MANAGER_FULL_NAME,
	DP.PROJECT_SALESREP_FULL_NAME :: STRING 														AS PROJECT_SALESREP_FULL_NAME,
	DP.PROJECT_SHIPPING_CITY_CODE :: STRING 														AS PROJECT_CITY_CODE,
	DP.PROJECT_SHIPPING_STATE_CODE :: STRING														AS PROJECT_STATE_CODE,
	DP.PROJECT_SHIPPING_COUNTRY_CODE :: STRING														AS PROJECT_COUNTRY_CODE,
	DP.PROJECT_CURRENCY_RATE :: STRING																AS PROJECT_CURRENCY_RATE,
	DC.CUSTOMER_CODE :: STRING																		AS CUSTOMER_CODE,
	DC.CUSTOMER_NAME :: STRING																		AS CUSTOMER_NAME,
	DC.CUSTOMER_CODE :: STRING																		AS CUSTOMER_CLASS_CODE,
	DC.BUSINESS_PARTNER_CODE :: STRING                                                              AS BUSINESS_PARTNER_CUSTOMER_CODE,
	DC.BUSINESS_PARTNER_NAME :: STRING																AS BUSINESS_PARTNER_CUSTOMER_NAME,
	DI.ITEM_SALES_GROUP_CODE :: STRING																AS ITEM_SALES_GROUP_CODE,
	CASE WHEN DI.ITEM_CODE LIKE '160.%' 
		THEN DI.ITEM_NAME_EN
    	ELSE DI.ITEM_SALES_GROUP_CODE
	END :: STRING  																							AS ITEM_NAME_GROUP,
	IFNULL(SUM(FPA.DIRECT_TIME_ORIGINAL_BUDGET/60),0) :: NUMBER(38,2)                               		AS DIRECT_TIME_HR,
	IFNULL(SUM(FPA.INDIRECT_TIME_ORIGINAL_BUDGET/60),0) :: NUMBER(38,2)                                		AS INDIRECT_TIME_HR,
	IFNULL(SUM(FPA.WEIGHT_ORIGINAL_BUDGET),0) :: NUMBER(38,2)												AS SALES_WEIGHT_LB,
	IFNULL(SUM(FPA.WEIGHT_ORIGINAL_BUDGET/2000),0) :: NUMBER(38,2) 											AS SALES_WEIGHT_T,
	IFNULL(SUM(FPA.AREA_ORIGINAL_BUDGET),0) :: NUMBER(38,2) 												AS SALES_AREA_SF,
	IFNULL(SUM(FPA.SOLD_PRICE_ORIGINAL_BUDGET*FER_CAD.EXCHANGE_RATE),0) :: NUMBER(38,2)						AS SALES_AMOUNT_CAD,
	IFNULL(SUM(FPA.MATERIAL_COST_ORIGINAL_BUDGET_AMOUNT*FER_CAD.EXCHANGE_RATE),0) :: NUMBER(38,2)			AS MATERIAL_COST_AMOUNT_CAD,
	IFNULL(SUM(FPA.FABRICATION_COST_ORIGINAL_BUDGET_AMOUNT*FER_CAD.EXCHANGE_RATE),0) :: NUMBER(38,2)		AS FABRICATION_COST_AMOUNT_CAD,
	IFNULL(SUM(FPA.LABOR_COST_ORIGINAL_BUDGET_AMOUNT*FER_CAD.EXCHANGE_RATE),0) :: NUMBER(38,2)				AS LABOR_COST_AMOUNT_CAD,
	IFNULL(SUM(FPA.SOLD_PRICE_ORIGINAL_BUDGET),0) - 
	SUM((IFNULL(FPA.MATERIAL_COST_ORIGINAL_BUDGET_AMOUNT,0) + 
		IFNULL(FPA.FABRICATION_COST_ORIGINAL_BUDGET_AMOUNT,0) + 
		IFNULL(FPA.LABOR_COST_ORIGINAL_BUDGET_AMOUNT,0))*IFNULL(FER_CAD.EXCHANGE_RATE,0)) :: NUMBER(38,2)	AS SALES_PROFIT_ESTIMATE_AMOUNT_CAD,
	IFNULL(SUM(FPA.SOLD_PRICE_ORIGINAL_BUDGET*FER_USD.EXCHANGE_RATE),0) :: NUMBER(38,2)						AS SALES_AMOUNT_USD,
	IFNULL(SUM(FPA.MATERIAL_COST_ORIGINAL_BUDGET_AMOUNT*FER_USD.EXCHANGE_RATE),0) :: NUMBER(38,2)			AS MATERIAL_COST_AMOUNT_USD,
	IFNULL(SUM(FPA.FABRICATION_COST_ORIGINAL_BUDGET_AMOUNT*FER_USD.EXCHANGE_RATE),0) :: NUMBER(38,2)		AS FABRICATION_COST_AMOUNT_USD,
	IFNULL(SUM(FPA.LABOR_COST_ORIGINAL_BUDGET_AMOUNT*FER_USD.EXCHANGE_RATE),0) :: NUMBER(38,2)				AS LABOR_COST_AMOUNT_USD,
	IFNULL(SUM(FPA.SOLD_PRICE_ORIGINAL_BUDGET),0) - 
	SUM((IFNULL(FPA.MATERIAL_COST_ORIGINAL_BUDGET_AMOUNT,0) + 
		IFNULL(FPA.FABRICATION_COST_ORIGINAL_BUDGET_AMOUNT,0) + 
		IFNULL(FPA.LABOR_COST_ORIGINAL_BUDGET_AMOUNT,0))*IFNULL(FER_USD.EXCHANGE_RATE,0)) :: NUMBER(38,2)	AS SALES_PROFIT_ESTIMATE_AMOUNT_USD
FROM {{ref('sche_fact_Project_Activity')}} FPA
	LEFT JOIN {{ref('sche_dim_Date')}} DD ON FPA.PROJECT_START_DATE_KEY = DD.DATE_KEY
	LEFT JOIN {{ref('sche_dim_Project')}} DP ON FPA.PROJECT_SK = DP.PROJECT_SK
	LEFT JOIN {{ref('sche_dim_Business_Unit')}} DBU ON FPA.BUSINESS_UNIT_SK = DBU.BUSINESS_UNIT_SK
	LEFT JOIN {{ref('sche_dim_Sales_Office')}} DSO ON FPA.SALES_OFFICE_SK = DSO.SALES_OFFICE_SK
	LEFT JOIN {{ref('sche_dim_Sales_Branch_Office')}} DSBO ON FPA.SALES_BRANCH_OFFICE_SK = DSBO.SALES_BRANCH_OFFICE_SK
	LEFT JOIN {{ref('sche_dim_Item')}} DI ON FPA.ITEM_SK = DI.ITEM_SK
	LEFT JOIN {{ref('sche_dim_Customer')}} DC ON FPA.SOLD_TO_CUSTOMER_SK = DC.CUSTOMER_SK
	LEFT JOIN {{ref('sche_dim_Currency')}} DCU_FROM ON FPA.PRICE_AND_COST_ORIGINAL_BUDGET_CURRENCY_SK = DCU_FROM.CURRENCY_SK
	LEFT JOIN {{ref('sche_dim_Currency')}} DCU_FROM_CAD ON DCU_FROM_CAD.CURRENCY_CODE = 'CAD'
    LEFT JOIN {{ref('sche_dim_Currency')}} DCU_TO_CAD ON FPA.TO_CURRENCY_CAD_SK = DCU_TO_CAD.CURRENCY_SK
    LEFT JOIN {{ref('sche_dim_Currency')}} DCU_TO_USD ON FPA.TO_CURRENCY_USD_SK = DCU_TO_USD.CURRENCY_SK
-- Equivalent to TRUNC(fact_sales_orders.sales_orders_date,'MONTH')= dw_currency_rate.currency_date
    LEFT JOIN {{ref('sche_dim_Exchange_Rate_Type')}} DERT ON FPA.FISCAL_PERIOD_END_AVG_EXCHANGE_RATE_TYPE_SK = DERT.EXCHANGE_RATE_TYPE_SK
    LEFT JOIN {{ref('sche_fact_Exchange_Rate')}} FER_CAD ON DCU_FROM.CURRENCY_SK = FER_CAD.FROM_CURRENCY_SK AND DCU_TO_CAD.CURRENCY_SK = FER_CAD.TO_CURRENCY_SK
    AND DD.DATE_KEY = FER_CAD.EXCHANGE_RATE_DATE_KEY AND DERT.EXCHANGE_RATE_TYPE_SK=FER_CAD.EXCHANGE_RATE_TYPE_SK
    LEFT JOIN {{ref('sche_fact_Exchange_Rate')}} FER_USD ON DCU_FROM.CURRENCY_SK = FER_USD.FROM_CURRENCY_SK AND DCU_TO_USD.CURRENCY_SK = FER_USD.TO_CURRENCY_SK
    AND DD.DATE_KEY = FER_USD.EXCHANGE_RATE_DATE_KEY AND DERT.EXCHANGE_RATE_TYPE_SK=FER_USD.EXCHANGE_RATE_TYPE_SK
LEFT JOIN {{ref('sche_fact_Exchange_Rate')}} FER_USD_COST ON DCU_FROM_CAD.CURRENCY_SK = FER_USD_COST.FROM_CURRENCY_SK AND DCU_TO_USD.CURRENCY_SK = FER_USD_COST.TO_CURRENCY_SK
            AND DD.DATE_KEY = FER_USD_COST.EXCHANGE_RATE_DATE_KEY AND DERT.EXCHANGE_RATE_TYPE_SK = FER_USD_COST.EXCHANGE_RATE_TYPE_SK
WHERE DI.ITEM_CODE <> 'N/A' -- Equivalent to NVL(dsa_salestrx.REJECTED_CODE,100) <> '8'
	AND DD.FISCAL_YEAR BETWEEN YEAR(CURRENT_DATE()) - 5 AND YEAR(CURRENT_DATE())
GROUP BY 
	SALES_DATE,
	SALES_CANAM_WEEK_START_DATE,  
	SALES_CANAM_WEEK_NUMBER,
	SALES_CALENDAR_MONTH_NUMBER,
	SALES_CALENDAR_MONTH_NAME_EN,
	SALES_CALENDAR_YEAR,
	SALES_FISCAL_PERIOD_NUMBER,
	SALES_FISCAL_PERIOD_NAME,
	SALES_FISCAL_YEAR,
	DBU.BUSINESS_UNIT_CODE,
	BUSINESS_UNIT_NAME_FR,
	BUSINESS_UNIT_NAME_EN,
	DSO.SALES_OFFICE_DEPARTMENT_CODE,
	SALES_OFFICE_DEPARTMENT_NAME,
	SALES_BRANCH_OFFICE_DEPARTMENT_GROUP_NAME,
	SALES_OFFICE_DEPARTMENT_COUNTRY_CODE,
	SALES_BRANCH_OFFICE_DEPARTMENT_CODE,
	SALES_BRANCH_OFFICE_DEPARTMENT_NAME,
	ORIGINAL_CURRENCY_CODE,
	BUDGET_VARIATION_TYPE_NAME,
	PROJECT_CODE,
	PROJECT_NAME,
	PROJECT_START_DATE,
	PROJECT_CLOSE_DATE,
	PROJECT_STATUS_CODE,
	PROJECT_TYPE_CODE,
	PROJECT_CLASS_CATEGORY_NAME,
	PROJECT_CLASS_NAME,
	PROJECT_PACKAGE_STATUS_CODE,
	PROJECT_BUILD_MASTER_STATUS_CODE,
	PROJECT_MANAGER_FULL_NAME,
	PROJECT_SALESREP_FULL_NAME,
	PROJECT_CITY_CODE,
	PROJECT_STATE_CODE,
	PROJECT_COUNTRY_CODE,
	PROJECT_CURRENCY_RATE,
	CUSTOMER_CODE,
	CUSTOMER_NAME,
	CUSTOMER_CLASS_CODE,
	BUSINESS_PARTNER_CODE,
	BUSINESS_PARTNER_NAME,
	ITEM_SALES_GROUP_CODE,
	ITEM_NAME_GROUP
UNION ALL
SELECT 
	DD.FULL_DATE																				AS SALES_DATE,
	DD.CANAM_WEEK_START_DATE																	AS SALES_CANAM_WEEK_START_DATE,
	DD.CANAM_WEEK_NUMBER																	    AS SALES_CANAM_WEEK_NUMBER,
	DD.CALENDAR_MONTH_NUMBER																	AS SALES_CALENDAR_MONTH_NUMBER,
	DD.CALENDAR_MONTH_NAME_EN																	AS SALES_CALENDAR_MONTH_NAME_EN,
	DD.CALENDAR_YEAR																			AS SALES_CALENDAR_YEAR,
	DD.FISCAL_PERIOD_NUMBER																	    AS SALES_FISCAL_PERIOD_NUMBER,
	DD.FISCAL_PERIOD_NAME																		AS SALES_FISCAL_PERIOD_NAME,
	DD.FISCAL_YEAR																				AS SALES_FISCAL_YEAR,
	DBU.BUSINESS_UNIT_CODE																		AS BUSINESS_UNIT_CODE,
	DBU.BUSINESS_UNIT_NAME_FR																	AS BUSINESS_UNIT_NAME_FR,
	DBU.BUSINESS_UNIT_NAME_EN																	AS BUSINESS_UNIT_NAME_EN,
	UPPER(TRIM(DSO.SALES_OFFICE_DEPARTMENT_CODE))												AS SALES_OFFICE_DEPARTMENT_CODE,
	UPPER(TRIM(DSO.SALES_OFFICE_DEPARTMENT_NAME_EN))												AS SALES_OFFICE_DEPARTMENT_NAME,
	UPPER(TRIM(DSBO.SALES_BRANCH_OFFICE_DEPARTMENT_NAME_EN))                                 AS SALES_BRANCH_OFFICE_DEPARTMENT_GROUP_NAME,
	DSO.SALES_OFFICE_DEPARTMENT_COUNTRY_CODE													AS SALES_OFFICE_DEPARTMENT_COUNTRY_CODE,
	UPPER(TRIM(DSBO.SALES_BRANCH_OFFICE_DEPARTMENT_CODE))										AS SALES_BRANCH_OFFICE_DEPARTMENT_CODE,
	UPPER(TRIM(DSBO.SALES_BRANCH_OFFICE_DEPARTMENT_NAME_EN))										AS SALES_BRANCH_OFFICE_DEPARTMENT_NAME,
	DCU_FROM.CURRENCY_CODE 																			AS ORIGINAL_CURRENCY_CODE,
	CASE FPABV.BUDGET_VARIATION_TYPE_CODE
	    WHEN 'E' THEN 'EXTRA/CREDIT'
	    WHEN 'P' THEN 'PERMUTATION'
	    WHEN 'A' THEN 'MANUAL ADJUSTMENT'
	    WHEN 'C' THEN 'CANCELLATION'
	    WHEN 'T' THEN 'PROJECT TRANSFER'
	    ELSE 'NOT FOUND' 
	END																							AS BUDGET_VARIATION_TYPE_NAME,
	DP.PROJECT_CODE																				AS PROJECT_CODE,
	DP.PROJECT_NAME_EN																			AS PROJECT_NAME,
	DP.PROJECT_START_DATE																		AS PROJECT_START_DATE,
	DP.PROJECT_CLOSE_DATE																		AS PROJECT_CLOSE_DATE,
	DP.PROJECT_STATUS_CODE																		AS PROJECT_STATUS_CODE,
	DP.PROJECT_TYPE_CODE																		AS PROJECT_TYPE_CODE,
	DP.PROJECT_CLASS_CATEGORY_NAME																AS PROJECT_CLASS_CATEGORY_NAME,
	DP.PROJECT_CLASS_NAME																		AS PROJECT_CLASS_NAME,
	DP.PROJECT_PACKAGE_STATUS_CODE																AS PROJECT_PACKAGE_STATUS_CODE,
	DP.PROJECT_BUILD_MASTER_STATUS_CODE 														AS PROJECT_BUILD_MASTER_STATUS_CODE,
	DP.PROJECT_MANAGER_FULL_NAME 																AS PROJECT_MANAGER_FULL_NAME,
	DP.PROJECT_SALESREP_FULL_NAME 																AS PROJECT_SALESREP_FULL_NAME,
	DP.PROJECT_SHIPPING_CITY_CODE 																AS PROJECT_CITY_CODE,
	DP.PROJECT_SHIPPING_STATE_CODE																AS PROJECT_STATE_CODE,
	DP.PROJECT_SHIPPING_COUNTRY_CODE															AS PROJECT_COUNTRY_CODE,
	DP.PROJECT_CURRENCY_RATE																	AS PROJECT_CURRENCY_RATE,
	DC.CUSTOMER_CODE																			AS CUSTOMER_CODE,
	DC.CUSTOMER_NAME																			AS CUSTOMER_NAME,
	DC.CUSTOMER_CODE																		AS CUSTOMER_CLASS_CODE,
	DC.BUSINESS_PARTNER_CODE                                                                    AS BUSINESS_PARTNER_CUSTOMER_CODE,
	DC.BUSINESS_PARTNER_NAME																	AS BUSINESS_PARTNER_CUSTOMER_NAME,
	DI.ITEM_SALES_GROUP_CODE																	AS ITEM_SALES_GROUP_CODE,
	CASE WHEN DI.ITEM_CODE LIKE '160.%' 
		THEN DI.ITEM_NAME_EN
    	ELSE DI.ITEM_SALES_GROUP_CODE
	END																							AS ITEM_NAME_GROUP,
	IFNULL(SUM(FPABV.DIRECT_TIME_BUDGET_VARIATION/60),0)                            			AS DIRECT_TIME_HR,
	IFNULL(SUM(FPABV.INDIRECT_TIME_BUDGET_VARIATION/60),0)                          			AS INDIRECT_TIME_HR,
	IFNULL(SUM(FPABV.WEIGHT_BUDGET_VARIATION),0)												AS SALES_WEIGHT_LB,
	IFNULL(SUM(FPABV.WEIGHT_BUDGET_VARIATION/2000),0) 											AS SALES_WEIGHT_T,
	IFNULL(SUM(FPABV.AREA_BUDGET_VARIATION),0) 													AS SALES_AREA_SF,
	IFNULL(SUM(FPABV.SOLD_PRICE_BUDGET_VARIATION*FER_CAD.EXCHANGE_RATE),0)						AS SALES_AMOUNT_CAD,
	IFNULL(SUM(FPABV.MATERIAL_COST_BUDGET_VARIATION_AMOUNT),0)									AS MATERIAL_COST_AMOUNT_CAD,
	IFNULL(SUM(FPABV.FABRICATION_COST_BUDGET_VARIATION_AMOUNT),0)                               AS FABRICATION_COST_AMOUNT_CAD,
	IFNULL(SUM(FPABV.LABOR_COST_BUDGET_VARIATION_AMOUNT),0)										AS LABOR_COST_AMOUNT_CAD,
	IFNULL(SUM(FPABV.SOLD_PRICE_BUDGET_VARIATION*FER_CAD.EXCHANGE_RATE),0) - 
		SUM(IFNULL(FPABV.MATERIAL_COST_BUDGET_VARIATION_AMOUNT,0) + 
			IFNULL(FPABV.FABRICATION_COST_BUDGET_VARIATION_AMOUNT,0) + 
			IFNULL(FPABV.LABOR_COST_BUDGET_VARIATION_AMOUNT,0))									AS SALES_PROFIT_ESTIMATE_AMOUNT_CAD,
	IFNULL(SUM(FPABV.SOLD_PRICE_BUDGET_VARIATION*FER_USD.EXCHANGE_RATE),0)						AS SALES_AMOUNT_USD,
	IFNULL(SUM(FPABV.MATERIAL_COST_BUDGET_VARIATION_AMOUNT*FER_USD_COST.EXCHANGE_RATE),0)		AS MATERIAL_COST_AMOUNT_USD,
	IFNULL(SUM(FPABV.FABRICATION_COST_BUDGET_VARIATION_AMOUNT*FER_USD_COST.EXCHANGE_RATE),0)	AS FABRICATION_COST_AMOUNT_USD,
	IFNULL(SUM(FPABV.LABOR_COST_BUDGET_VARIATION_AMOUNT*FER_USD_COST.EXCHANGE_RATE),0)			AS LABOR_COST_AMOUNT_USD,
	IFNULL(SUM(FPABV.SOLD_PRICE_BUDGET_VARIATION*FER_USD.EXCHANGE_RATE),0) - 
		SUM((IFNULL(FPABV.MATERIAL_COST_BUDGET_VARIATION_AMOUNT,0) + 
			IFNULL(FPABV.FABRICATION_COST_BUDGET_VARIATION_AMOUNT,0) + 
			IFNULL(FPABV.LABOR_COST_BUDGET_VARIATION_AMOUNT,0))*IFNULL(FER_USD_COST.EXCHANGE_RATE,0))	AS SALES_PROFIT_ESTIMATE_AMOUNT_USD
FROM {{ref('sche_fact_Project_Activity_Budget_Variation')}} FPABV
	LEFT JOIN {{ref('sche_dim_Date')}} DD ON FPABV.BUDGET_VARIATION_DATE_KEY = DD.DATE_KEY
	LEFT JOIN {{ref('sche_dim_Project')}} DP ON FPABV.PROJECT_SK = DP.PROJECT_SK
	LEFT JOIN {{ref('sche_dim_Business_Unit')}} DBU ON FPABV.BUSINESS_UNIT_SK = DBU.BUSINESS_UNIT_SK
	LEFT JOIN {{ref('sche_dim_Sales_Office')}} DSO ON FPABV.SALES_OFFICE_SK = DSO.SALES_OFFICE_SK
	LEFT JOIN {{ref('sche_dim_Sales_Branch_Office')}} DSBO ON FPABV.SALES_BRANCH_OFFICE_SK = DSBO.SALES_BRANCH_OFFICE_SK
	LEFT JOIN {{ref('sche_dim_Item')}} DI ON FPABV.ITEM_SK = DI.ITEM_SK
	LEFT JOIN {{ref('sche_dim_Customer')}} DC ON FPABV.SOLD_TO_CUSTOMER_SK = DC.CUSTOMER_SK
	LEFT JOIN {{ref('sche_dim_Currency')}} DCU_FROM_CAD ON DCU_FROM_CAD.CURRENCY_CODE = 'CAD'
	LEFT JOIN {{ref('sche_dim_Currency')}} DCU_FROM ON FPABV.PRICE_AND_COST_BUDGET_VARIATION_CURRENCY_SK = DCU_FROM.CURRENCY_SK
    LEFT JOIN {{ref('sche_dim_Currency')}} DCU_TO_CAD ON FPABV.TO_CURRENCY_CAD_SK = DCU_TO_CAD.CURRENCY_SK
	LEFT JOIN {{ref('sche_dim_Currency')}} DCU_TO_USD ON FPABV.TO_CURRENCY_USD_SK = DCU_TO_USD.CURRENCY_SK
	-- Equivalent to TRUNC(fact_sales_orders.sales_orders_date,'MONTH')= dw_currency_rate.currency_date
	LEFT JOIN {{ref('sche_dim_Exchange_Rate_Type')}} DERT ON FPABV.FISCAL_PERIOD_END_AVG_EXCHANGE_RATE_TYPE_SK = DERT.EXCHANGE_RATE_TYPE_SK
	LEFT JOIN {{ref('sche_fact_Exchange_Rate')}} FER_CAD ON DCU_FROM.CURRENCY_SK = FER_CAD.FROM_CURRENCY_SK AND DCU_TO_CAD.CURRENCY_SK = FER_CAD.TO_CURRENCY_SK 
    AND DD.DATE_KEY = FER_CAD.EXCHANGE_RATE_DATE_KEY AND DERT.EXCHANGE_RATE_TYPE_SK=FER_CAD.EXCHANGE_RATE_TYPE_SK
	LEFT JOIN {{ref('sche_fact_Exchange_Rate')}} FER_USD ON DCU_FROM.CURRENCY_SK = FER_USD.FROM_CURRENCY_SK AND DCU_TO_USD.CURRENCY_SK = FER_USD.TO_CURRENCY_SK 
    AND DD.DATE_KEY = FER_USD.EXCHANGE_RATE_DATE_KEY AND DERT.EXCHANGE_RATE_TYPE_SK=FER_USD.EXCHANGE_RATE_TYPE_SK
	LEFT JOIN {{ref('sche_fact_Exchange_Rate')}} FER_USD_COST ON DCU_FROM_CAD.CURRENCY_SK = FER_USD_COST.FROM_CURRENCY_SK AND DCU_TO_USD.CURRENCY_SK = FER_USD_COST.TO_CURRENCY_SK
            AND DD.DATE_KEY = FER_USD_COST.EXCHANGE_RATE_DATE_KEY AND DERT.EXCHANGE_RATE_TYPE_SK = FER_USD_COST.EXCHANGE_RATE_TYPE_SK
WHERE DI.ITEM_CODE <> 'N/A' -- Equivalent to NVL(dsa_salestrx.REJECTED_CODE,100) <> '8'
	AND DD.FISCAL_YEAR BETWEEN YEAR(CURRENT_DATE()) - 5 AND YEAR(CURRENT_DATE())
GROUP BY 
	SALES_DATE,
	SALES_CANAM_WEEK_START_DATE,  
	SALES_CANAM_WEEK_NUMBER,
	SALES_CALENDAR_MONTH_NUMBER,
	SALES_CALENDAR_MONTH_NAME_EN,
	SALES_CALENDAR_YEAR,
	SALES_FISCAL_PERIOD_NUMBER,
	SALES_FISCAL_PERIOD_NAME,
	SALES_FISCAL_YEAR,
	DBU.BUSINESS_UNIT_CODE,
	BUSINESS_UNIT_NAME_FR,
	BUSINESS_UNIT_NAME_EN,
	DSO.SALES_OFFICE_DEPARTMENT_CODE,
	SALES_OFFICE_DEPARTMENT_NAME,
	SALES_BRANCH_OFFICE_DEPARTMENT_GROUP_NAME,
	SALES_OFFICE_DEPARTMENT_COUNTRY_CODE,
	SALES_BRANCH_OFFICE_DEPARTMENT_CODE,
	SALES_BRANCH_OFFICE_DEPARTMENT_NAME,
	ORIGINAL_CURRENCY_CODE,
	BUDGET_VARIATION_TYPE_NAME,
	PROJECT_CODE,
	PROJECT_NAME,
	PROJECT_START_DATE,
	PROJECT_CLOSE_DATE,
	PROJECT_STATUS_CODE,
	PROJECT_TYPE_CODE,
	PROJECT_CLASS_CATEGORY_NAME,
	PROJECT_CLASS_NAME,
	PROJECT_PACKAGE_STATUS_CODE,
	PROJECT_BUILD_MASTER_STATUS_CODE,
	PROJECT_MANAGER_FULL_NAME,
	PROJECT_SALESREP_FULL_NAME,
	PROJECT_CITY_CODE,
	PROJECT_STATE_CODE,
	PROJECT_COUNTRY_CODE,
	PROJECT_CURRENCY_RATE,
	CUSTOMER_CODE,
	CUSTOMER_NAME,
	CUSTOMER_CLASS_CODE,
	BUSINESS_PARTNER_CODE,
	BUSINESS_PARTNER_NAME,
	ITEM_SALES_GROUP_CODE,
	ITEM_NAME_GROUP