snowflake_organization_name = "QNFANFA"
snowflake_account_name      = "QI17075"
snowflake_user              = "CHETANCHANDRA81"
snowflake_role              = "ACCOUNTADMIN"
snowflake_warehouse         = "ETL_WH_DEV"
snowflake_database          = "ADVWORKS_DEV"
environment                 = "dev"