snowflake_organization_name = "QNFANFA"
snowflake_account_name      = "QI17075"
snowflake_user              = "CHETANCHANDRA81"
snowflake_role              = "ACCOUNTADMIN"
snowflake_warehouse         = "ETL_WH_DEV"
snowflake_database          = "ADVWORKS_DEV"
environment                 = "dev"

gcp_project_id      = "electric-tesla-507710-k2"
gcp_project_number  = "776178390591"
gcp_region           = "northamerica-northeast1"
gcp_bucket_name      = "advworks-dev-ingestion"