{{
  config(
    materialized="table",
    snowflake_warehouse= var('task_warehouse'),
    alias = "etl_event_detail",
    schema= "data_quality"
  )
}}

/************** 
THIS IS AN HISTORIC TABLE THAT HAS BEEN DEPLOYED IN SNOWFLAKE DIRECTLY, CODE FOR REFERENCE ONLY. 
                                REDEPLOYING THIS CODE WILL DESTROY THE HISTORY                  
**************/
/*
CREATE OR REPLACE TABLE ENV_GOVERNANCE.DATA_QUALITY.ETL_EVENT_DETAIL (
    ETL_EVENT_DETAIL_SK STRING,
    ETL_EVENT_KEY STRING,
    EVENT_DATE_KEY STRING,
    ETL_EVENT_DESCRIPTION_CODE INTEGER,
    EVENT_TIMESTAMP TIMESTAMP_NTZ,
    TABLE_KEY STRING,
    FIELD_KEY STRING,
    RECORD_SK_KEY STRING,
    RECORD_SK STRING,
    RECORD_CONTENT VARIANT,
    ETL_EVENT_STATUS STRING,
    EFFECTIVE_START_TIMESTAMP TIMESTAMP_NTZ,
    EFFECTIVE_END_TIMESTAMP TIMESTAMP_NTZ
)
*/