CREATE DATABASE IF NOT EXISTS ADVWORKS_DEV;

CREATE SCHEMA IF NOT EXISTS ADVWORKS_DEV.LANDING;
CREATE SCHEMA IF NOT EXISTS ADVWORKS_DEV.PREPARE;
CREATE SCHEMA IF NOT EXISTS ADVWORKS_DEV.NORMALIZE;
CREATE SCHEMA IF NOT EXISTS ADVWORKS_DEV.SCHEMATIZE;
CREATE SCHEMA IF NOT EXISTS ADVWORKS_DEV.MARKETPLACE;

SHOW DATABASES;

SHOW SCHEMAS IN DATABASE ADVWORKS_DEV;

USE WAREHOUSE ETL_WH_DEV;

SELECT CURRENT_WAREHOUSE();

SELECT
    CURRENT_ACCOUNT(),
    CURRENT_USER(),
    CURRENT_ROLE(),
    CURRENT_REGION();

SELECT CURRENT_WAREHOUSE();

SHOW WAREHOUSES;

USE DATABASE ADVWORKS_DEV;

USE SCHEMA LANDING;

CREATE OR REPLACE STAGE DIMCUSTOMER_STAGE
    FILE_FORMAT = (
        TYPE = JSON
    );

SHOW STAGES;
DESC STAGE DIMCUSTOMER_STAGE;
LIST @DIMCUSTOMER_STAGE;
LIST @ADVWORKS_DEV.LANDING.DIMCUSTOMER_STAGE;
