SELECT SYSTEM$PIPE_STATUS(
    'ADVWORKS_DEV.LANDING.PIPE_DIM_CUSTOMER'
);
/*
"SYSTEM$PIPE_STATUS(
    'ADVWORKS_DEV.LANDING.PIPE_DIM_CUSTOMER'
)"
{"executionState":"RUNNING","pendingFileCount":0,"lastIngestedTimestamp":"2026-09-12T17:24:37.67Z","lastIngestedFilePath":"DimCustomer_batch_incremental_20260912_225153_001.jsonl","notificationChannelName":"projects/electric-tesla-507710-k2/subscriptions/dev-gcs-events-sub","numOutstandingMessagesOnChannel":0,"lastReceivedMessageTimestamp":"2026-09-12T17:24:37.291Z","lastForwardedMessageTimestamp":"2026-09-12T17:24:37.678Z","lastPulledFromChannelTimestamp":"2026-09-12T17:29:39.431Z","lastForwardedFilePath":"advworks-dev-ingestion/dim_customer/DimCustomer_batch_incremental_20260912_225153_001.jsonl","pendingHistoryRefreshJobsCount":0}
*/

-- — Check whether Snowpipe loaded the incremental file
SELECT
    RAW_DATA:CustomerKey::INT AS CUSTOMER_KEY,
    RAW_DATA:CustomerAlternateKey::STRING AS CUSTOMER_ALTERNATE_KEY,
    SOURCE_FILE,
    LOAD_TIMESTAMP
FROM ADVWORKS_DEV.LANDING.DIM_CUSTOMER
WHERE SOURCE_FILE LIKE '%DimCustomer_batch_incremental_20260912_225153_001.jsonl%';
/*
CUSTOMER_KEY	CUSTOMER_ALTERNATE_KEY	SOURCE_FILE	                                                                LOAD_TIMESTAMP
29487	          INCR_TEST_004	        dim_customer/DimCustomer_batch_incremental_20260912_225153_001.jsonl	2026-09-12 10:24:37.718
*/

--— Verify the overall LANDING count
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(RAW_DATA:CustomerKey::INT = 29487) AS NEW_CUSTOMER_ROWS
FROM ADVWORKS_DEV.LANDING.DIM_CUSTOMER;
/*
TOTAL_ROWS	NEW_CUSTOMER_ROWS
24488	          1
*/

CREATE OR REPLACE TABLE ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL
LIKE ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER;
/*
status
Table DIM_CUSTOMER_INCREMENTAL successfully created.
*/

DESC TABLE ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL;
/*
name	type	kind	null?	default	primary key	unique key	check	expression	comment	policy name	privacy domain	write default
CUSTOMER_KEY	NUMBER(38,0)	COLUMN	Y		N	N						
CUSTOMER_ALTERNATE_KEY	VARCHAR(16777216)	COLUMN	Y		N	N						
GEOGRAPHY_KEY	NUMBER(38,0)	COLUMN	Y		N	N						
TITLE	VARCHAR(16777216)	COLUMN	Y		N	N						
FIRST_NAME	VARCHAR(16777216)	COLUMN	Y		N	N						
MIDDLE_NAME	VARCHAR(16777216)	COLUMN	Y		N	N						
LAST_NAME	VARCHAR(16777216)	COLUMN	Y		N	N						
NAME_STYLE	BOOLEAN	COLUMN	Y		N	N						
BIRTH_DATE	DATE	COLUMN	Y		N	N						
MARITAL_STATUS	VARCHAR(16777216)	COLUMN	Y		N	N						
SUFFIX	VARCHAR(16777216)	COLUMN	Y		N	N						
GENDER	VARCHAR(16777216)	COLUMN	Y		N	N						
EMAIL_ADDRESS	VARCHAR(16777216)	COLUMN	Y		N	N						
YEARLY_INCOME	NUMBER(18,2)	COLUMN	Y		N	N						
TOTAL_CHILDREN	NUMBER(38,0)	COLUMN	Y		N	N						
NUMBER_CHILDREN_AT_HOME	NUMBER(38,0)	COLUMN	Y		N	N						
ENGLISH_EDUCATION	VARCHAR(16777216)	COLUMN	Y		N	N						
ENGLISH_OCCUPATION	VARCHAR(16777216)	COLUMN	Y		N	N						
HOUSE_OWNER_FLAG	BOOLEAN	COLUMN	Y		N	N						
NUMBER_CARS_OWNED	NUMBER(38,0)	COLUMN	Y		N	N						
ADDRESS_LINE_1	VARCHAR(16777216)	COLUMN	Y		N	N						
ADDRESS_LINE_2	VARCHAR(16777216)	COLUMN	Y		N	N						
PHONE	VARCHAR(16777216)	COLUMN	Y		N	N						
DATE_FIRST_PURCHASE	DATE	COLUMN	Y		N	N						
COMMUTE_DISTANCE	VARCHAR(16777216)	COLUMN	Y		N	N						
CREATED_TIMESTAMP	TIMESTAMP_LTZ(9)	COLUMN	Y		N	N						
UPDATED_TIMESTAMP	TIMESTAMP_LTZ(9)	COLUMN	Y		N	N						
*/


SELECT COUNT(*) AS TARGET_ROWS
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL;
/*
TARGET_ROWS
0
*/

SELECT *
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL
WHERE CUSTOMER_KEY = 29487; -- Query produced no results
/*

*/

MERGE INTO ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL AS TARGET
USING (
    SELECT
        RAW_DATA:CustomerKey::NUMBER AS CUSTOMER_KEY,
        RAW_DATA:CustomerAlternateKey::VARCHAR AS CUSTOMER_ALTERNATE_KEY,
        RAW_DATA:GeographyKey::NUMBER AS GEOGRAPHY_KEY,
        RAW_DATA:Title::VARCHAR AS TITLE,
        RAW_DATA:FirstName::VARCHAR AS FIRST_NAME,
        RAW_DATA:MiddleName::VARCHAR AS MIDDLE_NAME,
        RAW_DATA:LastName::VARCHAR AS LAST_NAME,
        RAW_DATA:NameStyle::BOOLEAN AS NAME_STYLE,
        RAW_DATA:BirthDate::DATE AS BIRTH_DATE,
        RAW_DATA:MaritalStatus::VARCHAR AS MARITAL_STATUS,
        RAW_DATA:Suffix::VARCHAR AS SUFFIX,
        RAW_DATA:Gender::VARCHAR AS GENDER,
        RAW_DATA:EmailAddress::VARCHAR AS EMAIL_ADDRESS,
        RAW_DATA:YearlyIncome::NUMBER(18,2) AS YEARLY_INCOME,
        RAW_DATA:TotalChildren::NUMBER AS TOTAL_CHILDREN,
        RAW_DATA:NumberChildrenAtHome::NUMBER AS NUMBER_CHILDREN_AT_HOME,
        RAW_DATA:EnglishEducation::VARCHAR AS ENGLISH_EDUCATION,
        RAW_DATA:EnglishOccupation::VARCHAR AS ENGLISH_OCCUPATION,
        CASE
            WHEN RAW_DATA:HouseOwnerFlag::VARCHAR = 'Y' THEN TRUE
            WHEN RAW_DATA:HouseOwnerFlag::VARCHAR = 'N' THEN FALSE
            ELSE NULL
        END AS HOUSE_OWNER_FLAG,
        RAW_DATA:NumberCarsOwned::NUMBER AS NUMBER_CARS_OWNED,
        RAW_DATA:AddressLine1::VARCHAR AS ADDRESS_LINE_1,
        RAW_DATA:AddressLine2::VARCHAR AS ADDRESS_LINE_2,
        RAW_DATA:Phone::VARCHAR AS PHONE,
        RAW_DATA:DateFirstPurchase::DATE AS DATE_FIRST_PURCHASE,
        RAW_DATA:CommuteDistance::VARCHAR AS COMMUTE_DISTANCE
    FROM ADVWORKS_DEV.LANDING.DIM_CUSTOMER
    WHERE RAW_DATA:CustomerKey::NUMBER = 29487
) AS SOURCE
ON TARGET.CUSTOMER_KEY = SOURCE.CUSTOMER_KEY

WHEN MATCHED THEN UPDATE SET
    CUSTOMER_ALTERNATE_KEY = SOURCE.CUSTOMER_ALTERNATE_KEY,
    GEOGRAPHY_KEY = SOURCE.GEOGRAPHY_KEY,
    TITLE = SOURCE.TITLE,
    FIRST_NAME = SOURCE.FIRST_NAME,
    MIDDLE_NAME = SOURCE.MIDDLE_NAME,
    LAST_NAME = SOURCE.LAST_NAME,
    NAME_STYLE = SOURCE.NAME_STYLE,
    BIRTH_DATE = SOURCE.BIRTH_DATE,
    MARITAL_STATUS = SOURCE.MARITAL_STATUS,
    SUFFIX = SOURCE.SUFFIX,
    GENDER = SOURCE.GENDER,
    EMAIL_ADDRESS = SOURCE.EMAIL_ADDRESS,
    YEARLY_INCOME = SOURCE.YEARLY_INCOME,
    TOTAL_CHILDREN = SOURCE.TOTAL_CHILDREN,
    NUMBER_CHILDREN_AT_HOME = SOURCE.NUMBER_CHILDREN_AT_HOME,
    ENGLISH_EDUCATION = SOURCE.ENGLISH_EDUCATION,
    ENGLISH_OCCUPATION = SOURCE.ENGLISH_OCCUPATION,
    HOUSE_OWNER_FLAG = SOURCE.HOUSE_OWNER_FLAG,
    NUMBER_CARS_OWNED = SOURCE.NUMBER_CARS_OWNED,
    ADDRESS_LINE_1 = SOURCE.ADDRESS_LINE_1,
    ADDRESS_LINE_2 = SOURCE.ADDRESS_LINE_2,
    PHONE = SOURCE.PHONE,
    DATE_FIRST_PURCHASE = SOURCE.DATE_FIRST_PURCHASE,
    COMMUTE_DISTANCE = SOURCE.COMMUTE_DISTANCE,
    UPDATED_TIMESTAMP = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    CUSTOMER_KEY,
    CUSTOMER_ALTERNATE_KEY,
    GEOGRAPHY_KEY,
    TITLE,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    NAME_STYLE,
    BIRTH_DATE,
    MARITAL_STATUS,
    SUFFIX,
    GENDER,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    TOTAL_CHILDREN,
    NUMBER_CHILDREN_AT_HOME,
    ENGLISH_EDUCATION,
    ENGLISH_OCCUPATION,
    HOUSE_OWNER_FLAG,
    NUMBER_CARS_OWNED,
    ADDRESS_LINE_1,
    ADDRESS_LINE_2,
    PHONE,
    DATE_FIRST_PURCHASE,
    COMMUTE_DISTANCE,
    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP
)
VALUES (
    SOURCE.CUSTOMER_KEY,
    SOURCE.CUSTOMER_ALTERNATE_KEY,
    SOURCE.GEOGRAPHY_KEY,
    SOURCE.TITLE,
    SOURCE.FIRST_NAME,
    SOURCE.MIDDLE_NAME,
    SOURCE.LAST_NAME,
    SOURCE.NAME_STYLE,
    SOURCE.BIRTH_DATE,
    SOURCE.MARITAL_STATUS,
    SOURCE.SUFFIX,
    SOURCE.GENDER,
    SOURCE.EMAIL_ADDRESS,
    SOURCE.YEARLY_INCOME,
    SOURCE.TOTAL_CHILDREN,
    SOURCE.NUMBER_CHILDREN_AT_HOME,
    SOURCE.ENGLISH_EDUCATION,
    SOURCE.ENGLISH_OCCUPATION,
    SOURCE.HOUSE_OWNER_FLAG,
    SOURCE.NUMBER_CARS_OWNED,
    SOURCE.ADDRESS_LINE_1,
    SOURCE.ADDRESS_LINE_2,
    SOURCE.PHONE,
    SOURCE.DATE_FIRST_PURCHASE,
    SOURCE.COMMUTE_DISTANCE,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
);
/*
number of rows inserted	number of rows updated
1	                              0
*/

SELECT
    CUSTOMER_KEY,
    CUSTOMER_ALTERNATE_KEY,
    FIRST_NAME,
    LAST_NAME,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL
WHERE CUSTOMER_KEY = 29487;
/*
CUSTOMER_KEY   CUSTOMER_ALTERNATE_KEY	FIRST_NAME	   LAST_NAME	EMAIL_ADDRESS	            YEARLY_INCOME	CREATED_TIMESTAMP	        UPDATED_TIMESTAMP
29487	          INCR_TEST_004	        Incremental	   Test004	incremental.test004@example.com	80000.00	2026-09-12 11:03:04.804 -0700	2026-09-12 11:03:04.804 -0700
*/


SELECT
    RAW_DATA:CustomerKey::INT AS CUSTOMER_KEY,
    RAW_DATA:EmailAddress::STRING AS EMAIL_ADDRESS,
    RAW_DATA:YearlyIncome::NUMBER(18,2) AS YEARLY_INCOME,
    SOURCE_FILE,
    LOAD_TIMESTAMP
FROM ADVWORKS_DEV.LANDING.DIM_CUSTOMER
WHERE SOURCE_FILE LIKE '%DimCustomer_update_29487.jsonl%';
/*
CUSTOMER_KEY	EMAIL_ADDRESS	                    YEARLY_INCOME	SOURCE_FILE	                                   LOAD_TIMESTAMP
29487	      incremental.updated004@example.com	90000.00	    dim_customer/DimCustomer_update_29487.jsonl	 2026-09-12 11:17:40.829
*/

SELECT SYSTEM$PIPE_STATUS(
    'ADVWORKS_DEV.LANDING.PIPE_DIM_CUSTOMER'
);
/*
"SYSTEM$PIPE_STATUS(
    'ADVWORKS_DEV.LANDING.PIPE_DIM_CUSTOMER'
)"
{"executionState":"RUNNING","pendingFileCount":0,"lastIngestedTimestamp":"2026-09-12T18:17:38.169Z","lastIngestedFilePath":"DimCustomer_update_29487.jsonl","notificationChannelName":"projects/electric-tesla-507710-k2/subscriptions/dev-gcs-events-sub","numOutstandingMessagesOnChannel":0,"lastReceivedMessageTimestamp":"2026-09-12T18:17:37.931Z","lastForwardedMessageTimestamp":"2026-09-12T18:17:40.789Z","lastPulledFromChannelTimestamp":"2026-09-12T18:22:54.436Z","lastForwardedFilePath":"advworks-dev-ingestion/dim_customer/DimCustomer_update_29487.jsonl","pendingHistoryRefreshJobsCount":0}
*/

--  MERGE the latest customer version. First, let's see both versions:
SELECT
    RAW_DATA:CustomerKey::INT AS CUSTOMER_KEY,
    RAW_DATA:EmailAddress::STRING AS EMAIL_ADDRESS,
    RAW_DATA:YearlyIncome::NUMBER(18,2) AS YEARLY_INCOME,
    SOURCE_FILE,
    LOAD_TIMESTAMP
FROM ADVWORKS_DEV.LANDING.DIM_CUSTOMER
WHERE RAW_DATA:CustomerKey::INT = 29487
ORDER BY LOAD_TIMESTAMP;
/*
CUSTOMER_KEY	EMAIL_ADDRESS	                   YEARLY_INCOME	SOURCE_FILE	                                                            LOAD_TIMESTAMP
29487	      incremental.test004@example.com	    80000.00	dim_customer/DimCustomer_batch_incremental_20260912_225153_001.jsonl	2026-09-12 10:24:37.718
29487	      incremental.updated004@example.com	90000.00	dim_customer/DimCustomer_update_29487.jsonl	                            2026-09-12 11:17:40.829
*/

--Now run the SCD Type 1 MERGE:
MERGE INTO ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL AS TARGET
USING (
    SELECT
        RAW_DATA:CustomerKey::NUMBER AS CUSTOMER_KEY,
        RAW_DATA:CustomerAlternateKey::VARCHAR AS CUSTOMER_ALTERNATE_KEY,
        RAW_DATA:GeographyKey::NUMBER AS GEOGRAPHY_KEY,
        RAW_DATA:Title::VARCHAR AS TITLE,
        RAW_DATA:FirstName::VARCHAR AS FIRST_NAME,
        RAW_DATA:MiddleName::VARCHAR AS MIDDLE_NAME,
        RAW_DATA:LastName::VARCHAR AS LAST_NAME,
        RAW_DATA:NameStyle::BOOLEAN AS NAME_STYLE,
        RAW_DATA:BirthDate::DATE AS BIRTH_DATE,
        RAW_DATA:MaritalStatus::VARCHAR AS MARITAL_STATUS,
        RAW_DATA:Suffix::VARCHAR AS SUFFIX,
        RAW_DATA:Gender::VARCHAR AS GENDER,
        RAW_DATA:EmailAddress::VARCHAR AS EMAIL_ADDRESS,
        RAW_DATA:YearlyIncome::NUMBER(18,2) AS YEARLY_INCOME,
        RAW_DATA:TotalChildren::NUMBER AS TOTAL_CHILDREN,
        RAW_DATA:NumberChildrenAtHome::NUMBER AS NUMBER_CHILDREN_AT_HOME,
        RAW_DATA:EnglishEducation::VARCHAR AS ENGLISH_EDUCATION,
        RAW_DATA:EnglishOccupation::VARCHAR AS ENGLISH_OCCUPATION,
        CASE
            WHEN RAW_DATA:HouseOwnerFlag::VARCHAR = 'Y' THEN TRUE
            WHEN RAW_DATA:HouseOwnerFlag::VARCHAR = 'N' THEN FALSE
            ELSE NULL
        END AS HOUSE_OWNER_FLAG,
        RAW_DATA:NumberCarsOwned::NUMBER AS NUMBER_CARS_OWNED,
        RAW_DATA:AddressLine1::VARCHAR AS ADDRESS_LINE_1,
        RAW_DATA:AddressLine2::VARCHAR AS ADDRESS_LINE_2,
        RAW_DATA:Phone::VARCHAR AS PHONE,
        RAW_DATA:DateFirstPurchase::DATE AS DATE_FIRST_PURCHASE,
        RAW_DATA:CommuteDistance::VARCHAR AS COMMUTE_DISTANCE
    FROM ADVWORKS_DEV.LANDING.DIM_CUSTOMER
    WHERE RAW_DATA:CustomerKey::NUMBER = 29487
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY RAW_DATA:CustomerKey::NUMBER
        ORDER BY LOAD_TIMESTAMP DESC
    ) = 1
) AS SOURCE
ON TARGET.CUSTOMER_KEY = SOURCE.CUSTOMER_KEY

WHEN MATCHED THEN UPDATE SET
    CUSTOMER_ALTERNATE_KEY = SOURCE.CUSTOMER_ALTERNATE_KEY,
    GEOGRAPHY_KEY = SOURCE.GEOGRAPHY_KEY,
    TITLE = SOURCE.TITLE,
    FIRST_NAME = SOURCE.FIRST_NAME,
    MIDDLE_NAME = SOURCE.MIDDLE_NAME,
    LAST_NAME = SOURCE.LAST_NAME,
    NAME_STYLE = SOURCE.NAME_STYLE,
    BIRTH_DATE = SOURCE.BIRTH_DATE,
    MARITAL_STATUS = SOURCE.MARITAL_STATUS,
    SUFFIX = SOURCE.SUFFIX,
    GENDER = SOURCE.GENDER,
    EMAIL_ADDRESS = SOURCE.EMAIL_ADDRESS,
    YEARLY_INCOME = SOURCE.YEARLY_INCOME,
    TOTAL_CHILDREN = SOURCE.TOTAL_CHILDREN,
    NUMBER_CHILDREN_AT_HOME = SOURCE.NUMBER_CHILDREN_AT_HOME,
    ENGLISH_EDUCATION = SOURCE.ENGLISH_EDUCATION,
    ENGLISH_OCCUPATION = SOURCE.ENGLISH_OCCUPATION,
    HOUSE_OWNER_FLAG = SOURCE.HOUSE_OWNER_FLAG,
    NUMBER_CARS_OWNED = SOURCE.NUMBER_CARS_OWNED,
    ADDRESS_LINE_1 = SOURCE.ADDRESS_LINE_1,
    ADDRESS_LINE_2 = SOURCE.ADDRESS_LINE_2,
    PHONE = SOURCE.PHONE,
    DATE_FIRST_PURCHASE = SOURCE.DATE_FIRST_PURCHASE,
    COMMUTE_DISTANCE = SOURCE.COMMUTE_DISTANCE,
    UPDATED_TIMESTAMP = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    CUSTOMER_KEY,
    CUSTOMER_ALTERNATE_KEY,
    GEOGRAPHY_KEY,
    TITLE,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    NAME_STYLE,
    BIRTH_DATE,
    MARITAL_STATUS,
    SUFFIX,
    GENDER,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    TOTAL_CHILDREN,
    NUMBER_CHILDREN_AT_HOME,
    ENGLISH_EDUCATION,
    ENGLISH_OCCUPATION,
    HOUSE_OWNER_FLAG,
    NUMBER_CARS_OWNED,
    ADDRESS_LINE_1,
    ADDRESS_LINE_2,
    PHONE,
    DATE_FIRST_PURCHASE,
    COMMUTE_DISTANCE,
    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP
)
VALUES (
    SOURCE.CUSTOMER_KEY,
    SOURCE.CUSTOMER_ALTERNATE_KEY,
    SOURCE.GEOGRAPHY_KEY,
    SOURCE.TITLE,
    SOURCE.FIRST_NAME,
    SOURCE.MIDDLE_NAME,
    SOURCE.LAST_NAME,
    SOURCE.NAME_STYLE,
    SOURCE.BIRTH_DATE,
    SOURCE.MARITAL_STATUS,
    SOURCE.SUFFIX,
    SOURCE.GENDER,
    SOURCE.EMAIL_ADDRESS,
    SOURCE.YEARLY_INCOME,
    SOURCE.TOTAL_CHILDREN,
    SOURCE.NUMBER_CHILDREN_AT_HOME,
    SOURCE.ENGLISH_EDUCATION,
    SOURCE.ENGLISH_OCCUPATION,
    SOURCE.HOUSE_OWNER_FLAG,
    SOURCE.NUMBER_CARS_OWNED,
    SOURCE.ADDRESS_LINE_1,
    SOURCE.ADDRESS_LINE_2,
    SOURCE.PHONE,
    SOURCE.DATE_FIRST_PURCHASE,
    SOURCE.COMMUTE_DISTANCE,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
);
/*
number of rows inserted	number of rows updated
0	                              1
*/

-- Prove SCD Type 1 worked  
SELECT
    CUSTOMER_KEY,
    CUSTOMER_ALTERNATE_KEY,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL
WHERE CUSTOMER_KEY = 29487;
/*
CUSTOMER_KEY	CUSTOMER_ALTERNATE_KEY	EMAIL_ADDRESS	                  YEARLY_INCOME	CREATED_TIMESTAMP	            UPDATED_TIMESTAMP
29487	          INCR_TEST_004	      incremental.updated004@example.com	90000.00	2026-09-12 11:03:04.804 -0700	2026-09-12 11:27:22.757 -0700
*/

SELECT COUNT(*) AS CUSTOMER_ROWS
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL
WHERE CUSTOMER_KEY = 29487;
/*
CUSTOMER_ROWS
1
*/

/*
#############################################################################################################################################################
That's above is SCD Type 1:

The latest value replaces the previous value, while the historical version is retained only in the raw/landing layer—not in the current-state dimension.
#############################################################################################################################################################
*/

--Create an SCD Type 2 target table
CREATE OR REPLACE TABLE ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_SCD2
LIKE ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER;

-- Now add the SCD2 tracking columns:
ALTER TABLE ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_SCD2
ADD COLUMN VALID_FROM TIMESTAMP_NTZ;

ALTER TABLE ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_SCD2
ADD COLUMN VALID_TO TIMESTAMP_NTZ;

ALTER TABLE ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_SCD2
ADD COLUMN IS_CURRENT BOOLEAN;

DESC TABLE ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_SCD2;
/*
name	type	kind	null?	default	primary key	unique key	check	expression	comment	policy name	privacy domain	write default
CUSTOMER_KEY	NUMBER(38,0)	COLUMN	Y		N	N						
CUSTOMER_ALTERNATE_KEY	VARCHAR(16777216)	COLUMN	Y		N	N						
GEOGRAPHY_KEY	NUMBER(38,0)	COLUMN	Y		N	N						
TITLE	VARCHAR(16777216)	COLUMN	Y		N	N						
FIRST_NAME	VARCHAR(16777216)	COLUMN	Y		N	N						
MIDDLE_NAME	VARCHAR(16777216)	COLUMN	Y		N	N						
LAST_NAME	VARCHAR(16777216)	COLUMN	Y		N	N						
NAME_STYLE	BOOLEAN	COLUMN	Y		N	N						
BIRTH_DATE	DATE	COLUMN	Y		N	N						
MARITAL_STATUS	VARCHAR(16777216)	COLUMN	Y		N	N						
SUFFIX	VARCHAR(16777216)	COLUMN	Y		N	N						
GENDER	VARCHAR(16777216)	COLUMN	Y		N	N						
EMAIL_ADDRESS	VARCHAR(16777216)	COLUMN	Y		N	N						
YEARLY_INCOME	NUMBER(18,2)	COLUMN	Y		N	N						
TOTAL_CHILDREN	NUMBER(38,0)	COLUMN	Y		N	N						
NUMBER_CHILDREN_AT_HOME	NUMBER(38,0)	COLUMN	Y		N	N						
ENGLISH_EDUCATION	VARCHAR(16777216)	COLUMN	Y		N	N						
ENGLISH_OCCUPATION	VARCHAR(16777216)	COLUMN	Y		N	N						
HOUSE_OWNER_FLAG	BOOLEAN	COLUMN	Y		N	N						
NUMBER_CARS_OWNED	NUMBER(38,0)	COLUMN	Y		N	N						
ADDRESS_LINE_1	VARCHAR(16777216)	COLUMN	Y		N	N						
ADDRESS_LINE_2	VARCHAR(16777216)	COLUMN	Y		N	N						
PHONE	VARCHAR(16777216)	COLUMN	Y		N	N						
DATE_FIRST_PURCHASE	DATE	COLUMN	Y		N	N						
COMMUTE_DISTANCE	VARCHAR(16777216)	COLUMN	Y		N	N						
CREATED_TIMESTAMP	TIMESTAMP_LTZ(9)	COLUMN	Y		N	N						
UPDATED_TIMESTAMP	TIMESTAMP_LTZ(9)	COLUMN	Y		N	N						
VALID_FROM	TIMESTAMP_NTZ(9)	COLUMN	Y		N	N						
VALID_TO	TIMESTAMP_NTZ(9)	COLUMN	Y		N	N						
IS_CURRENT	BOOLEAN	COLUMN	Y		N	N						
*/

-- Seed the original customer version
INSERT INTO ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_SCD2
(
    CUSTOMER_KEY,
    CUSTOMER_ALTERNATE_KEY,
    GEOGRAPHY_KEY,
    TITLE,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    NAME_STYLE,
    BIRTH_DATE,
    MARITAL_STATUS,
    SUFFIX,
    GENDER,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    TOTAL_CHILDREN,
    NUMBER_CHILDREN_AT_HOME,
    ENGLISH_EDUCATION,
    ENGLISH_OCCUPATION,
    HOUSE_OWNER_FLAG,
    NUMBER_CARS_OWNED,
    ADDRESS_LINE_1,
    ADDRESS_LINE_2,
    PHONE,
    DATE_FIRST_PURCHASE,
    COMMUTE_DISTANCE,
    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP,
    VALID_FROM,
    VALID_TO,
    IS_CURRENT
)
SELECT
    RAW_DATA:CustomerKey::NUMBER,
    RAW_DATA:CustomerAlternateKey::VARCHAR,
    RAW_DATA:GeographyKey::NUMBER,
    RAW_DATA:Title::VARCHAR,
    RAW_DATA:FirstName::VARCHAR,
    RAW_DATA:MiddleName::VARCHAR,
    RAW_DATA:LastName::VARCHAR,
    RAW_DATA:NameStyle::BOOLEAN,
    RAW_DATA:BirthDate::DATE,
    RAW_DATA:MaritalStatus::VARCHAR,
    RAW_DATA:Suffix::VARCHAR,
    RAW_DATA:Gender::VARCHAR,
    RAW_DATA:EmailAddress::VARCHAR,
    RAW_DATA:YearlyIncome::NUMBER(18,2),
    RAW_DATA:TotalChildren::NUMBER,
    RAW_DATA:NumberChildrenAtHome::NUMBER,
    RAW_DATA:EnglishEducation::VARCHAR,
    RAW_DATA:EnglishOccupation::VARCHAR,
    CASE
        WHEN RAW_DATA:HouseOwnerFlag::VARCHAR = 'Y' THEN TRUE
        WHEN RAW_DATA:HouseOwnerFlag::VARCHAR = 'N' THEN FALSE
        ELSE NULL
    END,
    RAW_DATA:NumberCarsOwned::NUMBER,
    RAW_DATA:AddressLine1::VARCHAR,
    RAW_DATA:AddressLine2::VARCHAR,
    RAW_DATA:Phone::VARCHAR,
    RAW_DATA:DateFirstPurchase::DATE,
    RAW_DATA:CommuteDistance::VARCHAR,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    NULL,
    TRUE
FROM ADVWORKS_DEV.LANDING.DIM_CUSTOMER
WHERE SOURCE_FILE LIKE '%DimCustomer_batch_incremental_20260912_225153_001.jsonl%';

-- Validate:
SELECT
    CUSTOMER_KEY,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    VALID_FROM,
    VALID_TO,
    IS_CURRENT
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_SCD2
WHERE CUSTOMER_KEY = 29487;
/*
CUSTOMER_KEY	EMAIL_ADDRESS	                 YEARLY_INCOME	VALID_FROM	   VALID_TO	       IS_CURRENT
29487	      incremental.test004@example.com	80000.00	   2026-09-12 1    1:47:08.853		TRUE
*/

-- First expire the old record:
UPDATE ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_SCD2 AS TARGET
SET
    VALID_TO = CURRENT_TIMESTAMP(),
    IS_CURRENT = FALSE,
    UPDATED_TIMESTAMP = CURRENT_TIMESTAMP()
WHERE TARGET.CUSTOMER_KEY = 29487
  AND TARGET.IS_CURRENT = TRUE
  AND EXISTS (
      SELECT 1
      FROM ADVWORKS_DEV.LANDING.DIM_CUSTOMER AS SOURCE
      WHERE SOURCE.SOURCE_FILE LIKE '%DimCustomer_update_29487.jsonl%'
        AND SOURCE.RAW_DATA:CustomerKey::NUMBER = TARGET.CUSTOMER_KEY
  );

-- Now insert the new version:
INSERT INTO ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_SCD2
(
    CUSTOMER_KEY,
    CUSTOMER_ALTERNATE_KEY,
    GEOGRAPHY_KEY,
    TITLE,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    NAME_STYLE,
    BIRTH_DATE,
    MARITAL_STATUS,
    SUFFIX,
    GENDER,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    TOTAL_CHILDREN,
    NUMBER_CHILDREN_AT_HOME,
    ENGLISH_EDUCATION,
    ENGLISH_OCCUPATION,
    HOUSE_OWNER_FLAG,
    NUMBER_CARS_OWNED,
    ADDRESS_LINE_1,
    ADDRESS_LINE_2,
    PHONE,
    DATE_FIRST_PURCHASE,
    COMMUTE_DISTANCE,
    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP,
    VALID_FROM,
    VALID_TO,
    IS_CURRENT
)
SELECT
    RAW_DATA:CustomerKey::NUMBER,
    RAW_DATA:CustomerAlternateKey::VARCHAR,
    RAW_DATA:GeographyKey::NUMBER,
    RAW_DATA:Title::VARCHAR,
    RAW_DATA:FirstName::VARCHAR,
    RAW_DATA:MiddleName::VARCHAR,
    RAW_DATA:LastName::VARCHAR,
    RAW_DATA:NameStyle::BOOLEAN,
    RAW_DATA:BirthDate::DATE,
    RAW_DATA:MaritalStatus::VARCHAR,
    RAW_DATA:Suffix::VARCHAR,
    RAW_DATA:Gender::VARCHAR,
    RAW_DATA:EmailAddress::VARCHAR,
    RAW_DATA:YearlyIncome::NUMBER(18,2),
    RAW_DATA:TotalChildren::NUMBER,
    RAW_DATA:NumberChildrenAtHome::NUMBER,
    RAW_DATA:EnglishEducation::VARCHAR,
    RAW_DATA:EnglishOccupation::VARCHAR,
    CASE
        WHEN RAW_DATA:HouseOwnerFlag::VARCHAR = 'Y' THEN TRUE
        WHEN RAW_DATA:HouseOwnerFlag::VARCHAR = 'N' THEN FALSE
        ELSE NULL
    END,
    RAW_DATA:NumberCarsOwned::NUMBER,
    RAW_DATA:AddressLine1::VARCHAR,
    RAW_DATA:AddressLine2::VARCHAR,
    RAW_DATA:Phone::VARCHAR,
    RAW_DATA:DateFirstPurchase::DATE,
    RAW_DATA:CommuteDistance::VARCHAR,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    NULL,
    TRUE
FROM ADVWORKS_DEV.LANDING.DIM_CUSTOMER
WHERE SOURCE_FILE LIKE '%DimCustomer_update_29487.jsonl%';

-- Prove SCD Type 2 worked
SELECT
    CUSTOMER_KEY,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    VALID_FROM,
    VALID_TO,
    IS_CURRENT
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_SCD2
WHERE CUSTOMER_KEY = 29487
ORDER BY VALID_FROM;
/*
CUSTOMER_KEY	EMAIL_ADDRESS	                   YEARLY_INCOME	VALID_FROM	                 VALID_TO	           IS_CURRENT
29487	      incremental.test004@example.com	    80000.00	    2026-09-12 11:47:08.853	   2026-09-12 11:50:06.948	FALSE
29487	      incremental.updated004@example.com	90000.00	    2026-09-12 11:50:50.293		   null                  RUE
*/

-- And run this final validation:
SELECT
    COUNT(*) AS TOTAL_VERSIONS,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_VERSIONS,
    COUNT_IF(IS_CURRENT = FALSE) AS HISTORICAL_VERSIONS
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_SCD2
WHERE CUSTOMER_KEY = 29487;
/*
TOTAL_VERSIONS	CURRENT_VERSIONS	HISTORICAL_VERSIONS
2	                  1	                     1
*/

