SELECT
    CUSTOMER_KEY,
    COUNT(*) AS ROW_COUNT
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL
WHERE CUSTOMER_KEY = 29487
GROUP BY CUSTOMER_KEY;

MERGE INTO ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL AS TARGET
USING
(
    SELECT
        RAW_DATA:CustomerKey::INT AS CUSTOMER_KEY,
        RAW_DATA:CustomerAlternateKey::STRING AS CUSTOMER_ALTERNATE_KEY,
        RAW_DATA:GeographyKey::INT AS GEOGRAPHY_KEY,
        RAW_DATA:FirstName::STRING AS FIRST_NAME,
        RAW_DATA:LastName::STRING AS LAST_NAME,
        RAW_DATA:EmailAddress::STRING AS EMAIL_ADDRESS,
        RAW_DATA:YearlyIncome::NUMBER(18,2) AS YEARLY_INCOME,
        LOAD_TIMESTAMP
    FROM ADVWORKS_DEV.LANDING.DIM_CUSTOMER
    QUALIFY ROW_NUMBER() OVER
    (
        PARTITION BY RAW_DATA:CustomerKey
        ORDER BY LOAD_TIMESTAMP DESC
    ) = 1
) AS SOURCE

ON TARGET.CUSTOMER_KEY = SOURCE.CUSTOMER_KEY

WHEN MATCHED THEN UPDATE SET
    TARGET.EMAIL_ADDRESS = SOURCE.EMAIL_ADDRESS,
    TARGET.YEARLY_INCOME = SOURCE.YEARLY_INCOME,
    TARGET.UPDATED_TIMESTAMP = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
    CUSTOMER_KEY,
    CUSTOMER_ALTERNATE_KEY,
    GEOGRAPHY_KEY,
    FIRST_NAME,
    LAST_NAME,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP
)
VALUES
(
    SOURCE.CUSTOMER_KEY,
    SOURCE.CUSTOMER_ALTERNATE_KEY,
    SOURCE.GEOGRAPHY_KEY,
    SOURCE.FIRST_NAME,
    SOURCE.LAST_NAME,
    SOURCE.EMAIL_ADDRESS,
    SOURCE.YEARLY_INCOME,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
);
/*
Run 1:
number of rows inserted	number of rows updated
18487	                          1

Run 2:
number of rows inserted	number of rows updated
0	                              18488
*/

SELECT
    CUSTOMER_KEY,
    COUNT(*) AS ROW_COUNT
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL
WHERE CUSTOMER_KEY = 29487
GROUP BY CUSTOMER_KEY;
/*
CUSTOMER_KEY	ROW_COUNT
29487	          1
*/

INSERT INTO ADVWORKS_DEV.AUDIT.PIPELINE_AUDIT
(
    RUN_ID,
    PIPELINE_NAME,
    ENVIRONMENT,
    SOURCE_SYSTEM,
    SOURCE_OBJECT,
    TARGET_OBJECT,
    STATUS,
    START_TIME,
    END_TIME,
    ROWS_READ,
    ROWS_WRITTEN,
    ERROR_COUNT,
    ERROR_MESSAGE
)
VALUES
(
    'MODULE11_FAILURE_TEST_001',
    'DIM_CUSTOMER_SCD1',
    'DEV',
    'SQL_SERVER',
    'dbo.DimCustomer',
    'NORMALIZE.DIM_CUSTOMER_INCREMENTAL',
    'FAILED',
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    0,
    0,
    1,
    'Controlled failure test - transformation object does not exist'
);

SELECT *
FROM ADVWORKS_DEV.AUDIT.PIPELINE_AUDIT
WHERE RUN_ID = 'MODULE11_FAILURE_TEST_001';

MERGE INTO ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL AS TARGET
USING
(
    SELECT
        RAW_DATA:CustomerKey::NUMBER AS CUSTOMER_KEY,
        RAW_DATA:CustomerAlternateKey::STRING AS CUSTOMER_ALTERNATE_KEY,
        RAW_DATA:GeographyKey::NUMBER AS GEOGRAPHY_KEY,
        RAW_DATA:FirstName::STRING AS FIRST_NAME,
        RAW_DATA:LastName::STRING AS LAST_NAME,
        RAW_DATA:EmailAddress::STRING AS EMAIL_ADDRESS,
        RAW_DATA:YearlyIncome::NUMBER(18,2) AS YEARLY_INCOME,
        LOAD_TIMESTAMP
    FROM ADVWORKS_DEV.LANDING.DIM_CUSTOMER
    WHERE RAW_DATA:CustomerKey::NUMBER = 29487
    QUALIFY ROW_NUMBER() OVER
    (
        PARTITION BY RAW_DATA:CustomerKey
        ORDER BY LOAD_TIMESTAMP DESC
    ) = 1
) AS SOURCE
ON TARGET.CUSTOMER_KEY = SOURCE.CUSTOMER_KEY

WHEN MATCHED THEN UPDATE SET
    TARGET.EMAIL_ADDRESS = SOURCE.EMAIL_ADDRESS,
    TARGET.YEARLY_INCOME = SOURCE.YEARLY_INCOME,
    TARGET.UPDATED_TIMESTAMP = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
    CUSTOMER_KEY,
    CUSTOMER_ALTERNATE_KEY,
    GEOGRAPHY_KEY,
    FIRST_NAME,
    LAST_NAME,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP
)
VALUES
(
    SOURCE.CUSTOMER_KEY,
    SOURCE.CUSTOMER_ALTERNATE_KEY,
    SOURCE.GEOGRAPHY_KEY,
    SOURCE.FIRST_NAME,
    SOURCE.LAST_NAME,
    SOURCE.EMAIL_ADDRESS,
    SOURCE.YEARLY_INCOME,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
);
-- number of rows inserted	number of rows updated
-- 0	                          1

INSERT INTO ADVWORKS_DEV.AUDIT.PIPELINE_AUDIT
(
    RUN_ID,
    PIPELINE_NAME,
    ENVIRONMENT,
    SOURCE_SYSTEM,
    SOURCE_OBJECT,
    TARGET_OBJECT,
    STATUS,
    START_TIME,
    END_TIME,
    ROWS_READ,
    ROWS_WRITTEN,
    ERROR_COUNT,
    ERROR_MESSAGE
)
VALUES
(
    'MODULE11_RECOVERY_001',
    'DIM_CUSTOMER_SCD1',
    'DEV',
    'SQL_SERVER',
    'dbo.DimCustomer',
    'NORMALIZE.DIM_CUSTOMER_INCREMENTAL',
    'SUCCESS',
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    1,
    1,
    0,
    NULL
);

SELECT
    CUSTOMER_KEY,
    CUSTOMER_ALTERNATE_KEY,
    EMAIL_ADDRESS,
    YEARLY_INCOME
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL
WHERE CUSTOMER_KEY = 29487;

-- CUSTOMER_KEY	CUSTOMER_ALTERNATE_KEY	EMAIL_ADDRESS	YEARLY_INCOME
-- 29487	INCR_TEST_004	incremental.updated004@example.com	90000.00

SELECT
    CUSTOMER_KEY,
    COUNT(*) AS RECORD_COUNT
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_INCREMENTAL
WHERE CUSTOMER_KEY = 29487
GROUP BY CUSTOMER_KEY;

-- CUSTOMER_KEY	RECORD_COUNT
-- 29487	          1

SELECT
    RUN_ID,
    PIPELINE_NAME,
    STATUS,
    ROWS_READ,
    ROWS_WRITTEN,
    ERROR_COUNT,
    ERROR_MESSAGE,
    CREATED_AT
FROM ADVWORKS_DEV.AUDIT.PIPELINE_AUDIT
WHERE PIPELINE_NAME = 'DIM_CUSTOMER_SCD1'
ORDER BY CREATED_AT;

-- RUN_ID	                         PIPELINE_NAME	STATUS	ROWS_READ	ROWS_WRITTEN	ERROR_COUNT	ERROR_MESSAGE	                                                  CREATED_AT
-- MODULE11_FAILURE_TEST_001	  DIM_CUSTOMER_SCD1	FAILED	0	             0	              1	    Controlled failure test - transformation object does not exist	2026-09-13 07:03:28.414
-- MODULE11_RECOVERY_001	      DIM_CUSTOMER_SCD1	SUCCESS	1	             1	              0		null                                                            2026-09-13 07:05:30.997