/*
NORMALIZE

Now we're moving from technical preparation to data standardization/model preparation.

For DIMCUSTOMER, we'll create:

ADVWORKS_DEV
│
├── LANDING
│   └── DIMCUSTOMER_RAW
│
├── PREPARE
│   └── DIMCUSTOMER_PREPARED
│
├── NORMALIZE
│   └── DIMCUSTOMER_NORMALIZED   ← NEXT
│
├── SCHEMATIZE
│
└── MARKETPLACE

The important distinction is:

PREPARE
    ↓
"What did the source send, converted into usable types?"

NORMALIZE
    ↓
"How should we standardize and clean this data for our warehouse?"

SCHEMATIZE
    ↓
"How should the analytical warehouse model be structured?"

MARKETPLACE
    ↓
"How should business users consume it?"

*/

-- ######################################  Stage 5 — Create NORMALIZE table  ####################################################

USE DATABASE ADVWORKS_DEV;

CREATE OR REPLACE TABLE NORMALIZE.DIMCUSTOMER_NORMALIZED
(
    CUSTOMER_KEY              INTEGER,
    GEOGRAPHY_KEY             INTEGER,
    CUSTOMER_ALTERNATE_KEY    VARCHAR(20),

    TITLE                     VARCHAR(10),
    FIRST_NAME                VARCHAR(100),
    MIDDLE_NAME               VARCHAR(100),
    LAST_NAME                 VARCHAR(100),
    NAME_STYLE                BOOLEAN,
    BIRTH_DATE                DATE,

    MARITAL_STATUS            VARCHAR(1),
    SUFFIX                    VARCHAR(10),
    GENDER                    VARCHAR(1),

    EMAIL_ADDRESS             VARCHAR(255),
    YEARLY_INCOME             NUMBER(18,2),

    TOTAL_CHILDREN            INTEGER,
    NUMBER_CHILDREN_AT_HOME   INTEGER,

    ENGLISH_EDUCATION         VARCHAR(100),
    SPANISH_EDUCATION         VARCHAR(100),
    FRENCH_EDUCATION          VARCHAR(100),

    ENGLISH_OCCUPATION        VARCHAR(100),
    SPANISH_OCCUPATION        VARCHAR(100),
    FRENCH_OCCUPATION         VARCHAR(100),

    HOUSE_OWNER_FLAG          BOOLEAN,
    NUMBER_CARS_OWNED         INTEGER,

    ADDRESS_LINE1             VARCHAR(255),
    ADDRESS_LINE2             VARCHAR(255),
    PHONE                     VARCHAR(50),

    DATE_FIRST_PURCHASE       DATE,
    COMMUTE_DISTANCE          VARCHAR(50),

    SOURCE_FILE               VARCHAR(500),
    LOAD_TIMESTAMP            TIMESTAMP_NTZ,

    NORMALIZED_TIMESTAMP      TIMESTAMP_NTZ
);

/*

Why are we adding NORMALIZED_TIMESTAMP?  
This is pipeline metadata. It tells us when the normalization step processed the record, which is useful for:

troubleshooting
auditing
pipeline monitoring
identifying when transformations occurred

*/

-- ###########################    Normalize the data. Now we'll deliberately perform some basic standardization.  ###########################

INSERT INTO ADVWORKS_DEV.NORMALIZE.DIMCUSTOMER_NORMALIZED
(
    CUSTOMER_KEY,
    GEOGRAPHY_KEY,
    CUSTOMER_ALTERNATE_KEY,

    TITLE,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    NAME_STYLE,
    BIRTH_DATE,

    MARITAL_STATUS,
    SUFFIX,
    GENDER,

    EMAIL_ADDRESS,
    YEARLY_INCOME,

    TOTAL_CHILDREN,
    NUMBER_CHILDREN_AT_HOME,

    ENGLISH_EDUCATION,
    SPANISH_EDUCATION,
    FRENCH_EDUCATION,

    ENGLISH_OCCUPATION,
    SPANISH_OCCUPATION,
    FRENCH_OCCUPATION,

    HOUSE_OWNER_FLAG,
    NUMBER_CARS_OWNED,

    ADDRESS_LINE1,
    ADDRESS_LINE2,
    PHONE,

    DATE_FIRST_PURCHASE,
    COMMUTE_DISTANCE,

    SOURCE_FILE,
    LOAD_TIMESTAMP,

    NORMALIZED_TIMESTAMP
)

SELECT

    CUSTOMER_KEY,

    GEOGRAPHY_KEY,

    TRIM(CUSTOMER_ALTERNATE_KEY),

    NULLIF(TRIM(TITLE), ''),

    INITCAP(TRIM(FIRST_NAME)),

    NULLIF(TRIM(MIDDLE_NAME), ''),

    INITCAP(TRIM(LAST_NAME)),

    NAME_STYLE,

    BIRTH_DATE,

    UPPER(TRIM(MARITAL_STATUS)),

    NULLIF(TRIM(SUFFIX), ''),

    UPPER(TRIM(GENDER)),

    LOWER(TRIM(EMAIL_ADDRESS)),

    YEARLY_INCOME,

    TOTAL_CHILDREN,

    NUMBER_CHILDREN_AT_HOME,

    TRIM(ENGLISH_EDUCATION),

    TRIM(SPANISH_EDUCATION),

    TRIM(FRENCH_EDUCATION),

    TRIM(ENGLISH_OCCUPATION),

    TRIM(SPANISH_OCCUPATION),

    TRIM(FRENCH_OCCUPATION),

    HOUSE_OWNER_FLAG,

    NUMBER_CARS_OWNED,

    TRIM(ADDRESS_LINE1),

    NULLIF(TRIM(ADDRESS_LINE2), ''),

    TRIM(PHONE),

    DATE_FIRST_PURCHASE,

    TRIM(COMMUTE_DISTANCE),

    SOURCE_FILE,

    LOAD_TIMESTAMP,

    CURRENT_TIMESTAMP()

FROM ADVWORKS_DEV.PREPARE.DIMCUSTOMER_PREPARED;

-- ###########################   Validate NORMALIZE   ###################################################

SELECT COUNT(*) AS NORMALIZE_COUNT
FROM ADVWORKS_DEV.NORMALIZE.DIMCUSTOMER_NORMALIZED; --18484

SELECT
    (SELECT COUNT(*)
     FROM ADVWORKS_DEV.PREPARE.DIMCUSTOMER_PREPARED)
        AS PREPARE_COUNT,

    (SELECT COUNT(*)
     FROM ADVWORKS_DEV.NORMALIZE.DIMCUSTOMER_NORMALIZED)
        AS NORMALIZE_COUNT;
/*
PREPARE_COUNT	NORMALIZE_COUNT
18484	18484
*/

-- Primary key
SELECT COUNT(*) AS NULL_CUSTOMER_KEYS
FROM ADVWORKS_DEV.NORMALIZE.DIMCUSTOMER_NORMALIZED
WHERE CUSTOMER_KEY IS NULL; -- 0

--Duplicate customers
SELECT
    CUSTOMER_KEY,
    COUNT(*) AS CNT
FROM ADVWORKS_DEV.NORMALIZE.DIMCUSTOMER_NORMALIZED
GROUP BY CUSTOMER_KEY
HAVING COUNT(*) > 1; -- Query produced no results

-- Email standardization
SELECT
    CUSTOMER_KEY,
    EMAIL_ADDRESS
FROM ADVWORKS_DEV.NORMALIZE.DIMCUSTOMER_NORMALIZED
ORDER BY CUSTOMER_KEY
LIMIT 10;
/*
CUSTOMER_KEY	EMAIL_ADDRESS
11000	jon24@adventure-works.com
11001	eugene10@adventure-works.com
11002	ruben35@adventure-works.com
11003	christy12@adventure-works.com
11004	elizabeth5@adventure-works.com
11005	julio1@adventure-works.com
11006	janet9@adventure-works.com
11007	marco14@adventure-works.com
11008	rob4@adventure-works.com
11009	shannon38@adventure-works.com
*/


/*

So we now have a clean, validated pipeline through NORMALIZE:

AdventureWorksDW2022
        ↓
Python / pyodbc
        ↓
JSONL
        ↓
Storage
        ↓
Snowflake Stage
        ↓
LANDING
  DIMCUSTOMER_RAW
        ↓
PREPARE
  DIMCUSTOMER_PREPARED
        ↓
NORMALIZE
  DIMCUSTOMER_NORMALIZED
        ↓
     NEXT
  SCHEMATIZE
        ↓
  MARKETPLACE

*/

-- Create the DIM_PRODUCT NORMALIZE table

USE DATABASE ADVWORKS_DEV;
USE SCHEMA NORMALIZE;

CREATE OR REPLACE TABLE DIMPRODUCT_NORMALIZED
(
    PRODUCT_KEY              INTEGER,
    PRODUCT_ALTERNATE_KEY    VARCHAR(50),
    ENGLISH_PRODUCT_NAME     VARCHAR(255),
    COLOR                    VARCHAR(50),
    SIZE                     VARCHAR(50),
    STANDARD_COST            NUMBER(18,2),
    LIST_PRICE               NUMBER(18,2),
    PRODUCT_SUBCATEGORY_KEY  INTEGER,
    START_DATE               DATE,
    END_DATE                 DATE,
    STATUS                   VARCHAR(50),
    SOURCE_FILE              VARCHAR(500),
    CREATED_TIMESTAMP        TIMESTAMP_NTZ,
    UPDATED_TIMESTAMP        TIMESTAMP_NTZ
);

-- LOAD DATA

INSERT INTO DIMPRODUCT_NORMALIZED
(
    PRODUCT_KEY,
    PRODUCT_ALTERNATE_KEY,
    ENGLISH_PRODUCT_NAME,
    COLOR,
    SIZE,
    STANDARD_COST,
    LIST_PRICE,
    PRODUCT_SUBCATEGORY_KEY,
    START_DATE,
    END_DATE,
    STATUS,
    SOURCE_FILE,
    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP
)
SELECT
    PRODUCT_KEY,

    NULLIF(
        TRIM(PRODUCT_ALTERNATE_KEY),
        ''
    ) AS PRODUCT_ALTERNATE_KEY,

    NULLIF(
        TRIM(ENGLISH_PRODUCT_NAME),
        ''
    ) AS ENGLISH_PRODUCT_NAME,

    NULLIF(
        TRIM(COLOR),
        ''
    ) AS COLOR,

    NULLIF(
        TRIM(SIZE),
        ''
    ) AS SIZE,

    STANDARD_COST,

    LIST_PRICE,

    PRODUCT_SUBCATEGORY_KEY,

    START_DATE,

    END_DATE,

    CASE
        WHEN END_DATE IS NULL THEN 'ACTIVE'
        ELSE 'INACTIVE'
    END AS STATUS,

    SOURCE_FILE,

    CURRENT_TIMESTAMP() AS CREATED_TIMESTAMP,

    CURRENT_TIMESTAMP() AS UPDATED_TIMESTAMP

FROM ADVWORKS_DEV.PREPARE.DIMPRODUCT_PREPARE; -- 606

-- VALIDATE
SELECT *
FROM ADVWORKS_DEV.NORMALIZE.DIMPRODUCT_NORMALIZED
ORDER BY PRODUCT_KEY
LIMIT 10;
/*
PRODUCT_KEY	PRODUCT_ALTERNATE_KEY	ENGLISH_PRODUCT_NAME	COLOR	SIZE	STANDARD_COST	LIST_PRICE	PRODUCT_SUBCATEGORY_KEY	START_DATE	END_DATE	STATUS	SOURCE_FILE	CREATED_TIMESTAMP	UPDATED_TIMESTAMP
1	AR-5381	Adjustable Race	NA					2003-07-01		ACTIVE	DimProduct_batch_001.json	2026-09-03 09:13:21.992	2026-09-03 09:13:21.992
2	BA-8327	Bearing Ball	NA					2003-07-01		ACTIVE	DimProduct_batch_001.json	2026-09-03 09:13:21.992	2026-09-03 09:13:21.992
3	BE-2349	BB Ball Bearing	NA					2003-07-01		ACTIVE	DimProduct_batch_001.json	2026-09-03 09:13:21.992	2026-09-03 09:13:21.992
4	BE-2908	Headset Ball Bearings	NA					2003-07-01		ACTIVE	DimProduct_batch_001.json	2026-09-03 09:13:21.992	2026-09-03 09:13:21.992
5	BL-2036	Blade	NA					2003-07-01		ACTIVE	DimProduct_batch_001.json	2026-09-03 09:13:21.992	2026-09-03 09:13:21.992
6	CA-5965	LL Crankarm	Black					2003-07-01		ACTIVE	DimProduct_batch_001.json	2026-09-03 09:13:21.992	2026-09-03 09:13:21.992
7	CA-6738	ML Crankarm	Black					2003-07-01		ACTIVE	DimProduct_batch_001.json	2026-09-03 09:13:21.992	2026-09-03 09:13:21.992
8	CA-7457	HL Crankarm	Black					2003-07-01		ACTIVE	DimProduct_batch_001.json	2026-09-03 09:13:21.992	2026-09-03 09:13:21.992
9	CB-2903	Chainring Bolts	Silver					2003-07-01		ACTIVE	DimProduct_batch_001.json	2026-09-03 09:13:21.992	2026-09-03 09:13:21.992
10	CN-6137	Chainring Nut	Silver					2003-07-01		ACTIVE	DimProduct_batch_001.json	2026-09-03 09:13:21.992	2026-09-03 09:13:21.992
*/

-- COUNT CHECK
SELECT
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT PRODUCT_KEY) AS DISTINCT_PRODUCTS,
    MIN(PRODUCT_KEY) AS MIN_PRODUCT_KEY,
    MAX(PRODUCT_KEY) AS MAX_PRODUCT_KEY
FROM ADVWORKS_DEV.NORMALIZE.DIMPRODUCT_NORMALIZED;
/*
ROW_COUNT	DISTINCT_PRODUCTS	MIN_PRODUCT_KEY	MAX_PRODUCT_KEY
606	606	1	606
*/

-- DERIVED STATUS
SELECT
    STATUS,
    COUNT(*) AS PRODUCT_COUNT
FROM ADVWORKS_DEV.NORMALIZE.DIMPRODUCT_NORMALIZED
GROUP BY STATUS
ORDER BY STATUS;
/*
STATUS	PRODUCT_COUNT
ACTIVE	406
INACTIVE	200
*/


--###################################################################################################################################

USE DATABASE ADVWORKS_DEV;
USE SCHEMA NORMALIZE;

CREATE OR REPLACE TABLE FACTINTERNETSALES_NORMALIZED
(
    PRODUCT_KEY                 INTEGER,
    ORDER_DATE_KEY              INTEGER,
    DUE_DATE_KEY                INTEGER,
    SHIP_DATE_KEY               INTEGER,
    CUSTOMER_KEY                INTEGER,
    PROMOTION_KEY               INTEGER,
    CURRENCY_KEY                INTEGER,
    SALES_TERRITORY_KEY         INTEGER,

    SALES_ORDER_NUMBER          VARCHAR(20),
    SALES_ORDER_LINE_NUMBER     INTEGER,
    REVISION_NUMBER             INTEGER,

    ORDER_QUANTITY               INTEGER,

    UNIT_PRICE                   NUMBER(19,4),
    EXTENDED_AMOUNT              NUMBER(19,4),
    UNIT_PRICE_DISCOUNT_PCT      FLOAT,
    DISCOUNT_AMOUNT              NUMBER(19,4),

    PRODUCT_STANDARD_COST        NUMBER(19,4),
    TOTAL_PRODUCT_COST           NUMBER(19,4),
    SALES_AMOUNT                 NUMBER(19,4),
    TAX_AMT                      NUMBER(19,4),
    FREIGHT                      NUMBER(19,4),

    CARRIER_TRACKING_NUMBER      VARCHAR(25),
    CUSTOMER_PO_NUMBER           VARCHAR(25),

    ORDER_DATE                   TIMESTAMP_NTZ,
    DUE_DATE                     TIMESTAMP_NTZ,
    SHIP_DATE                    TIMESTAMP_NTZ,

    SOURCE_FILE                  VARCHAR(500),
    LOAD_TIMESTAMP               TIMESTAMP_NTZ,
    NORMALIZED_TIMESTAMP         TIMESTAMP_NTZ
);

-- LOAD DATA
INSERT INTO ADVWORKS_DEV.NORMALIZE.FACTINTERNETSALES_NORMALIZED
(
    PRODUCT_KEY,
    ORDER_DATE_KEY,
    DUE_DATE_KEY,
    SHIP_DATE_KEY,
    CUSTOMER_KEY,
    PROMOTION_KEY,
    CURRENCY_KEY,
    SALES_TERRITORY_KEY,

    SALES_ORDER_NUMBER,
    SALES_ORDER_LINE_NUMBER,
    REVISION_NUMBER,

    ORDER_QUANTITY,

    UNIT_PRICE,
    EXTENDED_AMOUNT,
    UNIT_PRICE_DISCOUNT_PCT,
    DISCOUNT_AMOUNT,

    PRODUCT_STANDARD_COST,
    TOTAL_PRODUCT_COST,
    SALES_AMOUNT,
    TAX_AMT,
    FREIGHT,

    CARRIER_TRACKING_NUMBER,
    CUSTOMER_PO_NUMBER,

    ORDER_DATE,
    DUE_DATE,
    SHIP_DATE,

    SOURCE_FILE,
    LOAD_TIMESTAMP,
    NORMALIZED_TIMESTAMP
)
SELECT
    PRODUCT_KEY,
    ORDER_DATE_KEY,
    DUE_DATE_KEY,
    SHIP_DATE_KEY,
    CUSTOMER_KEY,
    PROMOTION_KEY,
    CURRENCY_KEY,
    SALES_TERRITORY_KEY,

    TRIM(SALES_ORDER_NUMBER),
    SALES_ORDER_LINE_NUMBER,
    REVISION_NUMBER,

    ORDER_QUANTITY,

    UNIT_PRICE,
    EXTENDED_AMOUNT,
    UNIT_PRICE_DISCOUNT_PCT,
    DISCOUNT_AMOUNT,

    PRODUCT_STANDARD_COST,
    TOTAL_PRODUCT_COST,
    SALES_AMOUNT,
    TAX_AMT,
    FREIGHT,

    NULLIF(TRIM(CARRIER_TRACKING_NUMBER), ''),
    NULLIF(TRIM(CUSTOMER_PO_NUMBER), ''),

    ORDER_DATE,
    DUE_DATE,
    SHIP_DATE,

    SOURCE_FILE,
    LOAD_TIMESTAMP,
    CURRENT_TIMESTAMP()

FROM ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED; --60398

-- VALIDATE COUNT
SELECT
    (SELECT COUNT(*)
     FROM ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED)
        AS PREPARE_COUNT,

    (SELECT COUNT(*)
     FROM ADVWORKS_DEV.NORMALIZE.FACTINTERNETSALES_NORMALIZED)
        AS NORMALIZE_COUNT;
/*
PREPARE_COUNT	NORMALIZE_COUNT
60398	60398
*/

-- VALIDATE NULLS IN KEYS
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PRODUCT_KEY IS NULL) AS NULL_PRODUCT_KEY,
    COUNT_IF(CUSTOMER_KEY IS NULL) AS NULL_CUSTOMER_KEY,
    COUNT_IF(ORDER_DATE_KEY IS NULL) AS NULL_ORDER_DATE_KEY,
    COUNT_IF(SALES_ORDER_NUMBER IS NULL) AS NULL_ORDER_NUMBER,
    COUNT_IF(SALES_ORDER_LINE_NUMBER IS NULL) AS NULL_ORDER_LINE_NUMBER,
    COUNT_IF(SALES_AMOUNT IS NULL) AS NULL_SALES_AMOUNT
FROM ADVWORKS_DEV.NORMALIZE.FACTINTERNETSALES_NORMALIZED;
/*
TOTAL_ROWS	NULL_PRODUCT_KEY	NULL_CUSTOMER_KEY	NULL_ORDER_DATE_KEY	NULL_ORDER_NUMBER	NULL_ORDER_LINE_NUMBER	NULL_SALES_AMOUNT
60398	0	0	0	0	0	0
*/

-- DUPLICATE CHECK
SELECT
    SALES_ORDER_NUMBER,
    SALES_ORDER_LINE_NUMBER,
    COUNT(*) AS ROW_COUNT
FROM ADVWORKS_DEV.NORMALIZE.FACTINTERNETSALES_NORMALIZED
GROUP BY
    SALES_ORDER_NUMBER,
    SALES_ORDER_LINE_NUMBER
HAVING COUNT(*) > 1
ORDER BY SALES_ORDER_NUMBER; -- 1989 ROWS RETURNED 
/*
SALES_ORDER_NUMBER	SALES_ORDER_LINE_NUMBER	ROW_COUNT
SO51386	3	2
SO51431	4	2
SO51467	3	2
SO51468	2	2
SO51473	3	2
SO51475	3	2
SO51478	2	2
SO51479	3	2
SO51487	3	2
SO51488	3	2
SO51493	3	2
SO51500	2	2
SO51502	4	2
SO51509	2	2
SO51512	3	2
SO51517	3	2
SO51518	2	2
SO51523	3	2
SO51524	3	2
SO51529	4	2
*/

TRUNCATE TABLE ADVWORKS_DEV.NORMALIZE.FACTINTERNETSALES_NORMALIZED;

SELECT COUNT(*) AS NORMALIZE_COUNT
FROM ADVWORKS_DEV.NORMALIZE.FACTINTERNETSALES_NORMALIZED;

INSERT INTO ADVWORKS_DEV.NORMALIZE.FACTINTERNETSALES_NORMALIZED
(
    PRODUCT_KEY,
    ORDER_DATE_KEY,
    DUE_DATE_KEY,
    SHIP_DATE_KEY,
    CUSTOMER_KEY,
    PROMOTION_KEY,
    CURRENCY_KEY,
    SALES_TERRITORY_KEY,
    SALES_ORDER_NUMBER,
    SALES_ORDER_LINE_NUMBER,
    REVISION_NUMBER,
    ORDER_QUANTITY,
    UNIT_PRICE,
    EXTENDED_AMOUNT,
    UNIT_PRICE_DISCOUNT_PCT,
    DISCOUNT_AMOUNT,
    PRODUCT_STANDARD_COST,
    TOTAL_PRODUCT_COST,
    SALES_AMOUNT,
    TAX_AMT,
    FREIGHT,
    CARRIER_TRACKING_NUMBER,
    CUSTOMER_PO_NUMBER,
    ORDER_DATE,
    DUE_DATE,
    SHIP_DATE,
    SOURCE_FILE,
    LOAD_TIMESTAMP,
    NORMALIZED_TIMESTAMP
)
SELECT
    PRODUCT_KEY,
    ORDER_DATE_KEY,
    DUE_DATE_KEY,
    SHIP_DATE_KEY,
    CUSTOMER_KEY,
    PROMOTION_KEY,
    CURRENCY_KEY,
    SALES_TERRITORY_KEY,
    TRIM(SALES_ORDER_NUMBER),
    SALES_ORDER_LINE_NUMBER,
    REVISION_NUMBER,
    ORDER_QUANTITY,
    UNIT_PRICE,
    EXTENDED_AMOUNT,
    UNIT_PRICE_DISCOUNT_PCT,
    DISCOUNT_AMOUNT,
    PRODUCT_STANDARD_COST,
    TOTAL_PRODUCT_COST,
    SALES_AMOUNT,
    TAX_AMT,
    FREIGHT,
    NULLIF(TRIM(CARRIER_TRACKING_NUMBER), ''),
    NULLIF(TRIM(CUSTOMER_PO_NUMBER), ''),
    ORDER_DATE,
    DUE_DATE,
    SHIP_DATE,
    SOURCE_FILE,
    LOAD_TIMESTAMP,
    CURRENT_TIMESTAMP()
FROM ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED; -- 60398

SELECT COUNT(*) AS NORMALIZE_COUNT
FROM ADVWORKS_DEV.NORMALIZE.FACTINTERNETSALES_NORMALIZED; -- 60398

-- null check
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PRODUCT_KEY IS NULL) AS NULL_PRODUCT_KEY,
    COUNT_IF(CUSTOMER_KEY IS NULL) AS NULL_CUSTOMER_KEY,
    COUNT_IF(ORDER_DATE_KEY IS NULL) AS NULL_ORDER_DATE_KEY,
    COUNT_IF(SALES_ORDER_NUMBER IS NULL) AS NULL_ORDER_NUMBER,
    COUNT_IF(SALES_ORDER_LINE_NUMBER IS NULL) AS NULL_ORDER_LINE_NUMBER,
    COUNT_IF(SALES_AMOUNT IS NULL) AS NULL_SALES_AMOUNT
FROM ADVWORKS_DEV.NORMALIZE.FACTINTERNETSALES_NORMALIZED;
/*
TOTAL_ROWS	NULL_PRODUCT_KEY	NULL_CUSTOMER_KEY	NULL_ORDER_DATE_KEY	NULL_ORDER_NUMBER	NULL_ORDER_LINE_NUMBER	NULL_SALES_AMOUNT
60398	0	0	0	0	0	0
*/

-- Grain / duplicate validation
SELECT
    SALES_ORDER_NUMBER,
    SALES_ORDER_LINE_NUMBER,
    COUNT(*) AS ROW_COUNT
FROM ADVWORKS_DEV.NORMALIZE.FACTINTERNETSALES_NORMALIZED
GROUP BY
    SALES_ORDER_NUMBER,
    SALES_ORDER_LINE_NUMBER
HAVING COUNT(*) > 1
ORDER BY SALES_ORDER_NUMBER; -- Query produced no results

-- Financial reconciliation
SELECT
    COUNT(*) AS ROW_COUNT,
    SUM(SALES_AMOUNT) AS TOTAL_SALES,
    SUM(TOTAL_PRODUCT_COST) AS TOTAL_PRODUCT_COST,
    SUM(TAX_AMT) AS TOTAL_TAX,
    SUM(FREIGHT) AS TOTAL_FREIGHT,
    MIN(SALES_AMOUNT) AS MIN_SALES_AMOUNT,
    MAX(SALES_AMOUNT) AS MAX_SALES_AMOUNT
FROM ADVWORKS_DEV.NORMALIZE.FACTINTERNETSALES_NORMALIZED;
/*
ROW_COUNT	TOTAL_SALES	TOTAL_PRODUCT_COST	TOTAL_TAX	TOTAL_FREIGHT	MIN_SALES_AMOUNT	MAX_SALES_AMOUNT
60398	29358677.2207	17277793.5757	2348694.2301	733969.6091	2.2900	3578.2700
*/
