--##################  validations ##########################################

SELECT
    RECORD:CustomerKey::INTEGER AS CUSTOMER_KEY,
    RECORD:GeographyKey::INTEGER AS GEOGRAPHY_KEY,
    RECORD:CustomerAlternateKey::VARCHAR AS CUSTOMER_ALTERNATE_KEY,
    RECORD:FirstName::VARCHAR AS FIRST_NAME,
    RECORD:LastName::VARCHAR AS LAST_NAME,
    RECORD:BirthDate::VARCHAR AS BIRTH_DATE_RAW,
    RECORD:YearlyIncome::NUMBER(18,2) AS YEARLY_INCOME,
    RECORD:TotalChildren::INTEGER AS TOTAL_CHILDREN,
    RECORD:NumberChildrenAtHome::INTEGER AS NUMBER_CHILDREN_AT_HOME,
    RECORD:HouseOwnerFlag::VARCHAR AS HOUSE_OWNER_FLAG_RAW,
    RECORD:NumberCarsOwned::INTEGER AS NUMBER_CARS_OWNED,
    RECORD:DateFirstPurchase::VARCHAR AS DATE_FIRST_PURCHASE_RAW
FROM ADVWORKS_DEV.LANDING.DIMCUSTOMER_RAW
LIMIT 10;

/*
CUSTOMER_KEY	GEOGRAPHY_KEY	CUSTOMER_ALTERNATE_KEY	FIRST_NAME	LAST_NAME	BIRTH_DATE_RAW	YEARLY_INCOME	TOTAL_CHILDREN	NUMBER_CHILDREN_AT_HOME
26000	369	AW00026000	Connor	Lopez	1971-10-02	40000.00	0	0
26001	539	AW00026001	Nicholas	Lee	1972-09-21	50000.00	0	0
26002	548	AW00026002	Samuel	Walker	1973-04-01	50000.00	0	0
26003	307	AW00026003	Denise	Subram	1973-05-24	60000.00	0	0
26004	348	AW00026004	Arthur	Washington	1966-05-08	60000.00	1	0
26005	547	AW00026005	Elizabeth	Clark	1966-05-18	60000.00	1	0
26006	607	AW00026006	Garrett	Peterson	1965-04-22	60000.00	4	3
26007	347	AW00026007	Jesse	Morgan	1970-04-04	60000.00	4	3
26008	315	AW00026008	Jennifer	Gonzales	1970-06-19	70000.00	5	5
26009	315	AW00026009	Luis	Foster	1965-03-12	70000.00	5	5

*/

SELECT
    COUNT(*) AS TOTAL_RECORDS,

    COUNT_IF(RECORD:CustomerKey IS NULL) AS NULL_CUSTOMER_KEY,
    COUNT_IF(RECORD:GeographyKey IS NULL) AS NULL_GEOGRAPHY_KEY,
    COUNT_IF(RECORD:FirstName IS NULL) AS NULL_FIRST_NAME,
    COUNT_IF(RECORD:LastName IS NULL) AS NULL_LAST_NAME,
    COUNT_IF(RECORD:BirthDate IS NULL) AS NULL_BIRTH_DATE,
    COUNT_IF(RECORD:YearlyIncome IS NULL) AS NULL_YEARLY_INCOME,
    COUNT_IF(RECORD:DateFirstPurchase IS NULL) AS NULL_DATE_FIRST_PURCHASE
FROM ADVWORKS_DEV.LANDING.DIMCUSTOMER_RAW;
/*
TOTAL_RECORDS	NULL_CUSTOMER_KEY	NULL_GEOGRAPHY_KEY	NULL_FIRST_NAME	NULL_LAST_NAME	NULL_BIRTH_DATE	NULL_YEARLY_INCOME	NULL_DATE_FIRST_PURCHASE
18484	0	0	0	0	0	0	0

*/

--Marital status
SELECT
    RECORD:MaritalStatus::VARCHAR AS MARITAL_STATUS,
    COUNT(*) AS RECORD_COUNT
FROM ADVWORKS_DEV.LANDING.DIMCUSTOMER_RAW
GROUP BY RECORD:MaritalStatus::VARCHAR
ORDER BY RECORD_COUNT DESC;
/*
MARITAL_STATUS	RECORD_COUNT
M	10011
S	8473
*/


--Gender
SELECT
    RECORD:Gender::VARCHAR AS GENDER,
    COUNT(*) AS RECORD_COUNT
FROM ADVWORKS_DEV.LANDING.DIMCUSTOMER_RAW
GROUP BY RECORD:Gender::VARCHAR
ORDER BY RECORD_COUNT DESC;
/*
GENDER	RECORD_COUNT
M	9351
F	9133

*/


--House owner flag
SELECT
    RECORD:HouseOwnerFlag::VARCHAR AS HOUSE_OWNER_FLAG,
    COUNT(*) AS RECORD_COUNT
FROM ADVWORKS_DEV.LANDING.DIMCUSTOMER_RAW
GROUP BY RECORD:HouseOwnerFlag::VARCHAR
ORDER BY RECORD_COUNT DESC;
/*
HOUSE_OWNER_FLAG	RECORD_COUNT
1	12502
0	5982

*/


--Commute distance
SELECT
    RECORD:CommuteDistance::VARCHAR AS COMMUTE_DISTANCE,
    COUNT(*) AS RECORD_COUNT
FROM ADVWORKS_DEV.LANDING.DIMCUSTOMER_RAW
GROUP BY RECORD:CommuteDistance::VARCHAR
ORDER BY RECORD_COUNT DESC;
/*
COMMUTE_DISTANCE	RECORD_COUNT
0-1 Miles	6310
2-5 Miles	3234
1-2 Miles	3232
5-10 Miles	3214
10+ Miles	2494

*/

--#############################################  Create the PREPARE table #######################################################

USE DATABASE ADVWORKS_DEV;

CREATE OR REPLACE TABLE PREPARE.DIMCUSTOMER_PREPARED
(
    CUSTOMER_KEY              INTEGER,
    GEOGRAPHY_KEY             INTEGER,
    CUSTOMER_ALTERNATE_KEY    VARCHAR(20),

    TITLE                     VARCHAR(10),
    FIRST_NAME                VARCHAR(100),
    MIDDLE_NAME               VARCHAR(100),
    LAST_NAME                 VARCHAR(100),
    NAME_STYLE                BOOLEAN,
    BIRTH_DATE                DATE,

    MARITAL_STATUS            VARCHAR(1),
    SUFFIX                    VARCHAR(10),
    GENDER                    VARCHAR(1),

    EMAIL_ADDRESS             VARCHAR(255),
    YEARLY_INCOME             NUMBER(18,2),

    TOTAL_CHILDREN            INTEGER,
    NUMBER_CHILDREN_AT_HOME   INTEGER,

    ENGLISH_EDUCATION         VARCHAR(100),
    SPANISH_EDUCATION         VARCHAR(100),
    FRENCH_EDUCATION          VARCHAR(100),

    ENGLISH_OCCUPATION        VARCHAR(100),
    SPANISH_OCCUPATION        VARCHAR(100),
    FRENCH_OCCUPATION         VARCHAR(100),

    HOUSE_OWNER_FLAG          BOOLEAN,
    NUMBER_CARS_OWNED         INTEGER,

    ADDRESS_LINE1             VARCHAR(255),
    ADDRESS_LINE2             VARCHAR(255),
    PHONE                     VARCHAR(50),

    DATE_FIRST_PURCHASE       DATE,
    COMMUTE_DISTANCE          VARCHAR(50),

    SOURCE_FILE               VARCHAR(500),
    LOAD_TIMESTAMP            TIMESTAMP_NTZ
);

--############################################## Load LANDING → PREPARE   ##############################################

with raw_dim_customer as (
select * from ADVWORKS_DEV.LANDING.DIMCUSTOMER_RAW
)
SELECT
RECORD:CustomerKey::INTEGER,

    RECORD:GeographyKey::INTEGER,

    RECORD:CustomerAlternateKey::VARCHAR,

    RECORD:Title::VARCHAR,

    RECORD:FirstName::VARCHAR,

    RECORD:MiddleName::VARCHAR,

    RECORD:LastName::VARCHAR,

    RECORD:NameStyle::BOOLEAN,

    TRY_TO_DATE(
        RECORD:BirthDate::VARCHAR
    ),

    RECORD:MaritalStatus::VARCHAR,

    RECORD:Suffix::VARCHAR,

    RECORD:Gender::VARCHAR,

    RECORD:EmailAddress::VARCHAR,

    RECORD:YearlyIncome::NUMBER(18,2),

    RECORD:TotalChildren::INTEGER,

    RECORD:NumberChildrenAtHome::INTEGER,

    RECORD:EnglishEducation::VARCHAR,

    RECORD:SpanishEducation::VARCHAR,

    RECORD:FrenchEducation::VARCHAR,

    RECORD:EnglishOccupation::VARCHAR,

    RECORD:SpanishOccupation::VARCHAR,

    RECORD:FrenchOccupation::VARCHAR,

    CASE
        WHEN RECORD:HouseOwnerFlag::VARCHAR = '1'
            THEN TRUE

        WHEN RECORD:HouseOwnerFlag::VARCHAR = '0'
            THEN FALSE

        ELSE NULL
    END,

    RECORD:NumberCarsOwned::INTEGER,

    RECORD:AddressLine1::VARCHAR,

    RECORD:AddressLine2::VARCHAR,

    RECORD:Phone::VARCHAR,

    TRY_TO_DATE(
        RECORD:DateFirstPurchase::VARCHAR
    ),

    RECORD:CommuteDistance::VARCHAR,

    SOURCE_FILE,

    LOAD_TIMESTAMP
    
    FROM raw_dim_customer;

    -- ##################################################################################################################

INSERT INTO ADVWORKS_DEV.PREPARE.DIMCUSTOMER_PREPARED
(
    CUSTOMER_KEY,
    GEOGRAPHY_KEY,
    CUSTOMER_ALTERNATE_KEY,

    TITLE,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    NAME_STYLE,
    BIRTH_DATE,

    MARITAL_STATUS,
    SUFFIX,
    GENDER,

    EMAIL_ADDRESS,
    YEARLY_INCOME,

    TOTAL_CHILDREN,
    NUMBER_CHILDREN_AT_HOME,

    ENGLISH_EDUCATION,
    SPANISH_EDUCATION,
    FRENCH_EDUCATION,

    ENGLISH_OCCUPATION,
    SPANISH_OCCUPATION,
    FRENCH_OCCUPATION,

    HOUSE_OWNER_FLAG,
    NUMBER_CARS_OWNED,

    ADDRESS_LINE1,
    ADDRESS_LINE2,
    PHONE,

    DATE_FIRST_PURCHASE,
    COMMUTE_DISTANCE,

    SOURCE_FILE,
    LOAD_TIMESTAMP
)

SELECT

    RECORD:CustomerKey::INTEGER,

    RECORD:GeographyKey::INTEGER,

    RECORD:CustomerAlternateKey::VARCHAR,

    RECORD:Title::VARCHAR,

    RECORD:FirstName::VARCHAR,

    RECORD:MiddleName::VARCHAR,

    RECORD:LastName::VARCHAR,

    RECORD:NameStyle::BOOLEAN,

    TRY_TO_DATE(
        RECORD:BirthDate::VARCHAR
    ),

    RECORD:MaritalStatus::VARCHAR,

    RECORD:Suffix::VARCHAR,

    RECORD:Gender::VARCHAR,

    RECORD:EmailAddress::VARCHAR,

    RECORD:YearlyIncome::NUMBER(18,2),

    RECORD:TotalChildren::INTEGER,

    RECORD:NumberChildrenAtHome::INTEGER,

    RECORD:EnglishEducation::VARCHAR,

    RECORD:SpanishEducation::VARCHAR,

    RECORD:FrenchEducation::VARCHAR,

    RECORD:EnglishOccupation::VARCHAR,

    RECORD:SpanishOccupation::VARCHAR,

    RECORD:FrenchOccupation::VARCHAR,

    CASE
        WHEN RECORD:HouseOwnerFlag::VARCHAR = '1'
            THEN TRUE

        WHEN RECORD:HouseOwnerFlag::VARCHAR = '0'
            THEN FALSE

        ELSE NULL
    END,

    RECORD:NumberCarsOwned::INTEGER,

    RECORD:AddressLine1::VARCHAR,

    RECORD:AddressLine2::VARCHAR,

    RECORD:Phone::VARCHAR,

    TRY_TO_DATE(
        RECORD:DateFirstPurchase::VARCHAR
    ),

    RECORD:CommuteDistance::VARCHAR,

    SOURCE_FILE,

    LOAD_TIMESTAMP

FROM ADVWORKS_DEV.LANDING.DIMCUSTOMER_RAW;


-- Verify record count

SELECT COUNT(*) AS PREPARE_COUNT
FROM ADVWORKS_DEV.PREPARE.DIMCUSTOMER_PREPARED; -- 18484

SELECT
    (SELECT COUNT(*)
     FROM ADVWORKS_DEV.LANDING.DIMCUSTOMER_RAW)
        AS LANDING_COUNT,

    (SELECT COUNT(*)
     FROM ADVWORKS_DEV.PREPARE.DIMCUSTOMER_PREPARED)
        AS PREPARE_COUNT;
/*
LANDING_COUNT	PREPARE_COUNT
18484	18484
*/

SELECT
    CUSTOMER_KEY,
    GEOGRAPHY_KEY,
    CUSTOMER_ALTERNATE_KEY,
    FIRST_NAME,
    LAST_NAME,
    BIRTH_DATE,
    YEARLY_INCOME,
    TOTAL_CHILDREN,
    NUMBER_CHILDREN_AT_HOME,
    HOUSE_OWNER_FLAG,
    NUMBER_CARS_OWNED,
    DATE_FIRST_PURCHASE,
    COMMUTE_DISTANCE,
    SOURCE_FILE,
    LOAD_TIMESTAMP
FROM ADVWORKS_DEV.PREPARE.DIMCUSTOMER_PREPARED
ORDER BY CUSTOMER_KEY
LIMIT 10;

--Verify the actual Snowflake data types. This is a useful exercise.


DESC TABLE ADVWORKS_DEV.PREPARE.DIMCUSTOMER_PREPARED;

-- Check NULL primary key
SELECT COUNT(*) AS NULL_CUSTOMER_KEYS
FROM ADVWORKS_DEV.PREPARE.DIMCUSTOMER_PREPARED
WHERE CUSTOMER_KEY IS NULL; -- 0

-- Check duplicate keys
SELECT
    CUSTOMER_KEY,
    COUNT(*) AS CNT
FROM ADVWORKS_DEV.PREPARE.DIMCUSTOMER_PREPARED
GROUP BY CUSTOMER_KEY
HAVING COUNT(*) > 1; -- Query produced no results

-- Check house-owner conversion
SELECT
    HOUSE_OWNER_FLAG,
    COUNT(*) AS RECORD_COUNT
FROM ADVWORKS_DEV.PREPARE.DIMCUSTOMER_PREPARED
GROUP BY HOUSE_OWNER_FLAG
ORDER BY HOUSE_OWNER_FLAG;

-- Check date conversion
SELECT
    COUNT(*) AS INVALID_BIRTH_DATES
FROM ADVWORKS_DEV.PREPARE.DIMCUSTOMER_PREPARED
WHERE BIRTH_DATE IS NULL; -- 0

SELECT
    COUNT(*) AS INVALID_PURCHASE_DATES
FROM ADVWORKS_DEV.PREPARE.DIMCUSTOMER_PREPARED
WHERE DATE_FIRST_PURCHASE IS NULL; -- 0

/*

We now have a genuine two-layer warehouse:

                 LANDING
                    │
                    │ raw
                    ▼
        ┌────────────────────────┐
        │ DIMCUSTOMER_RAW        │
        │                        │
        │ RECORD VARIANT         │
        │ SOURCE_FILE            │
        │ LOAD_TIMESTAMP         │
        └────────────┬───────────┘
                     │
                     │ transformation
                     ▼
                 PREPARE
                     │
                     ▼
        ┌────────────────────────┐
        │ DIMCUSTOMER_PREPARED   │
        │                        │
        │ Typed columns          │
        │ DATE                   │
        │ INTEGER                │
        │ NUMBER                 │
        │ BOOLEAN                │
        │ VARCHAR                │
        └────────────────────────┘


AdventureWorksDW2022
        │
        ▼
Python / pyodbc
        │
        ▼
JSONL batches
        │
        ▼
Local Storage Bucket
        │
        ▼
Snowflake Internal Stage
        │
        ▼
LANDING.DIMCUSTOMER_RAW
        │
        │  JSON → typed columns
        ▼
PREPARE.DIMCUSTOMER_PREPARED
        │
        ▼
      NEXT
        │
        ▼
NORMALIZE
*/

-- Create PREPARE.DIMPRODUCT_PREPARE

USE DATABASE ADVWORKS_DEV;
USE SCHEMA PREPARE;

CREATE OR REPLACE TABLE DIMPRODUCT_PREPARE
(
    PRODUCT_KEY              INTEGER,
    PRODUCT_ALTERNATE_KEY    VARCHAR(50),

    ENGLISH_PRODUCT_NAME     VARCHAR(255),

    COLOR                    VARCHAR(50),
    SIZE                     VARCHAR(50),

    STANDARD_COST            NUMBER(18,2),
    LIST_PRICE               NUMBER(18,2),

    PRODUCT_SUBCATEGORY_KEY  INTEGER,

    START_DATE               DATE,
    END_DATE                 DATE,

    STATUS                   VARCHAR(50),

    SOURCE_FILE              VARCHAR(500),
    LOAD_TIMESTAMP           TIMESTAMP_NTZ
);

-- load data

INSERT INTO ADVWORKS_DEV.PREPARE.DIMPRODUCT_PREPARE
(
    PRODUCT_KEY,
    PRODUCT_ALTERNATE_KEY,

    ENGLISH_PRODUCT_NAME,

    COLOR,
    SIZE,

    STANDARD_COST,
    LIST_PRICE,

    PRODUCT_SUBCATEGORY_KEY,

    START_DATE,
    END_DATE,

    STATUS,

    SOURCE_FILE,
    LOAD_TIMESTAMP
)
SELECT
    RECORD:ProductKey::INTEGER
        AS PRODUCT_KEY,

    RECORD:ProductAlternateKey::VARCHAR(50)
        AS PRODUCT_ALTERNATE_KEY,

    RECORD:EnglishProductName::VARCHAR(255)
        AS ENGLISH_PRODUCT_NAME,

    NULLIF(RECORD:Color::VARCHAR(50), '')
        AS COLOR,

    NULLIF(RECORD:Size::VARCHAR(50), '')
        AS SIZE,

    RECORD:StandardCost::NUMBER(18,2)
        AS STANDARD_COST,

    RECORD:ListPrice::NUMBER(18,2)
        AS LIST_PRICE,

    RECORD:ProductSubcategoryKey::INTEGER
        AS PRODUCT_SUBCATEGORY_KEY,

    RECORD:StartDate::DATE
        AS START_DATE,

    RECORD:EndDate::DATE
        AS END_DATE,

    RECORD:Status::VARCHAR(50)
        AS STATUS,

    SOURCE_FILE,

    LOAD_TIMESTAMP

FROM ADVWORKS_DEV.LANDING.DIMPRODUCT_RAW;

-- validate
SELECT *
FROM ADVWORKS_DEV.PREPARE.DIMPRODUCT_PREPARE
LIMIT 20;
/*
PRODUCT_KEY	PRODUCT_ALTERNATE_KEY	ENGLISH_PRODUCT_NAME	COLOR	SIZE	STANDARD_COST	LIST_PRICE	PRODUCT_SUBCATEGORY_KEY	START_DATE	END_DATE	STATUS	SOURCE_FILE	LOAD_TIMESTAMP
											DimProduct_batch_001.json	2026-09-03 07:15:19.385
*/

--check the number of records:
SELECT COUNT(*) AS RECORD_COUNT
FROM ADVWORKS_DEV.PREPARE.DIMPRODUCT_PREPARE; --RECORD_COUNT is 1

--check for duplicate products:
SELECT
    PRODUCT_KEY,
    COUNT(*) AS CNT
FROM ADVWORKS_DEV.PREPARE.DIMPRODUCT_PREPARE
GROUP BY PRODUCT_KEY
HAVING COUNT(*) > 1; -- Query produced no results

SELECT
    TYPEOF(RECORD) AS RECORD_TYPE,
    ARRAY_SIZE(RECORD) AS PRODUCT_COUNT
FROM ADVWORKS_DEV.LANDING.DIMPRODUCT_RAW
LIMIT 1;
/*
RECORD_TYPE	PRODUCT_COUNT
ARRAY	606
*/

SELECT
    F.INDEX AS ARRAY_POSITION,
    F.VALUE:ProductKey::INTEGER AS PRODUCT_KEY,
    F.VALUE:ProductAlternateKey::VARCHAR AS PRODUCT_ALTERNATE_KEY,
    F.VALUE:EnglishProductName::VARCHAR AS PRODUCT_NAME,
    F.VALUE:Color::VARCHAR AS COLOR,
    F.VALUE:StartDate::DATE AS START_DATE,
    F.VALUE:Status::VARCHAR AS STATUS
FROM ADVWORKS_DEV.LANDING.DIMPRODUCT_RAW,
     LATERAL FLATTEN(INPUT => RECORD) F
ORDER BY F.INDEX
LIMIT 10;
/*
ARRAY_POSITION	PRODUCT_KEY	PRODUCT_ALTERNATE_KEY	PRODUCT_NAME	COLOR	START_DATE	STATUS
0	1	AR-5381	Adjustable Race	NA	2003-07-01	Current
1	2	BA-8327	Bearing Ball	NA	2003-07-01	Current
2	3	BE-2349	BB Ball Bearing	NA	2003-07-01	Current
3	4	BE-2908	Headset Ball Bearings	NA	2003-07-01	Current
4	5	BL-2036	Blade	NA	2003-07-01	Current
5	6	CA-5965	LL Crankarm	Black	2003-07-01	Current
6	7	CA-6738	ML Crankarm	Black	2003-07-01	Current
7	8	CA-7457	HL Crankarm	Black	2003-07-01	Current
8	9	CB-2903	Chainring Bolts	Silver	2003-07-01	Current
9	10	CN-6137	Chainring Nut	Silver	2003-07-01	Current
*/

USE DATABASE ADVWORKS_DEV;
USE SCHEMA PREPARE;

CREATE OR REPLACE TABLE DIMPRODUCT_PREPARE
(
    PRODUCT_KEY              INTEGER,
    PRODUCT_ALTERNATE_KEY    VARCHAR(50),
    ENGLISH_PRODUCT_NAME     VARCHAR(255),
    COLOR                    VARCHAR(50),
    SIZE                     VARCHAR(50),
    STANDARD_COST            NUMBER(18,2),
    LIST_PRICE               NUMBER(18,2),
    PRODUCT_SUBCATEGORY_KEY  INTEGER,
    START_DATE               DATE,
    END_DATE                 DATE,
    STATUS                   VARCHAR(50),
    SOURCE_FILE              VARCHAR(500),
    LOAD_TIMESTAMP            TIMESTAMP_NTZ
);

INSERT INTO DIMPRODUCT_PREPARE
(
    PRODUCT_KEY,
    PRODUCT_ALTERNATE_KEY,
    ENGLISH_PRODUCT_NAME,
    COLOR,
    SIZE,
    STANDARD_COST,
    LIST_PRICE,
    PRODUCT_SUBCATEGORY_KEY,
    START_DATE,
    END_DATE,
    STATUS,
    SOURCE_FILE,
    LOAD_TIMESTAMP
)
SELECT
    F.VALUE:ProductKey::INTEGER
        AS PRODUCT_KEY,

    F.VALUE:ProductAlternateKey::VARCHAR(50)
        AS PRODUCT_ALTERNATE_KEY,

    NULLIF(
        TRIM(F.VALUE:EnglishProductName::VARCHAR(255)),
        ''
    ) AS ENGLISH_PRODUCT_NAME,

    NULLIF(
        TRIM(F.VALUE:Color::VARCHAR(50)),
        ''
    ) AS COLOR,

    NULLIF(
        TRIM(F.VALUE:Size::VARCHAR(50)),
        ''
    ) AS SIZE,

    F.VALUE:StandardCost::NUMBER(18,2)
        AS STANDARD_COST,

    F.VALUE:ListPrice::NUMBER(18,2)
        AS LIST_PRICE,

    F.VALUE:ProductSubcategoryKey::INTEGER
        AS PRODUCT_SUBCATEGORY_KEY,

    F.VALUE:StartDate::TIMESTAMP_NTZ::DATE
        AS START_DATE,

    F.VALUE:EndDate::TIMESTAMP_NTZ::DATE
        AS END_DATE,

    F.VALUE:Status::VARCHAR(50)
        AS STATUS,

    SOURCE_FILE,

    LOAD_TIMESTAMP

FROM ADVWORKS_DEV.LANDING.DIMPRODUCT_RAW,
     LATERAL FLATTEN(INPUT => RECORD) F;
/*
number of rows inserted
606
*/

-- — Validate the load
SELECT *
FROM ADVWORKS_DEV.PREPARE.DIMPRODUCT_PREPARE
ORDER BY PRODUCT_KEY
LIMIT 10;
/*
PRODUCT_KEY	PRODUCT_ALTERNATE_KEY	ENGLISH_PRODUCT_NAME	COLOR	SIZE	STANDARD_COST	LIST_PRICE	PRODUCT_SUBCATEGORY_KEY	START_DATE	END_DATE	STATUS	SOURCE_FILE	LOAD_TIMESTAMP
1	AR-5381	Adjustable Race	NA					2003-07-01		Current	DimProduct_batch_001.json	2026-09-03 07:15:19.385
2	BA-8327	Bearing Ball	NA					2003-07-01		Current	DimProduct_batch_001.json	2026-09-03 07:15:19.385
3	BE-2349	BB Ball Bearing	NA					2003-07-01		Current	DimProduct_batch_001.json	2026-09-03 07:15:19.385
4	BE-2908	Headset Ball Bearings	NA					2003-07-01		Current	DimProduct_batch_001.json	2026-09-03 07:15:19.385
5	BL-2036	Blade	NA					2003-07-01		Current	DimProduct_batch_001.json	2026-09-03 07:15:19.385
6	CA-5965	LL Crankarm	Black					2003-07-01		Current	DimProduct_batch_001.json	2026-09-03 07:15:19.385
7	CA-6738	ML Crankarm	Black					2003-07-01		Current	DimProduct_batch_001.json	2026-09-03 07:15:19.385
8	CA-7457	HL Crankarm	Black					2003-07-01		Current	DimProduct_batch_001.json	2026-09-03 07:15:19.385
9	CB-2903	Chainring Bolts	Silver					2003-07-01		Current	DimProduct_batch_001.json	2026-09-03 07:15:19.385
10	CN-6137	Chainring Nut	Silver					2003-07-01		Current	DimProduct_batch_001.json	2026-09-03 07:15:19.385
*/

-- count check
SELECT
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT PRODUCT_KEY) AS DISTINCT_PRODUCTS,
    MIN(PRODUCT_KEY) AS MIN_PRODUCT_KEY,
    MAX(PRODUCT_KEY) AS MAX_PRODUCT_KEY
FROM ADVWORKS_DEV.PREPARE.DIMPRODUCT_PREPARE;
/*
ROW_COUNT	DISTINCT_PRODUCTS	MIN_PRODUCT_KEY	MAX_PRODUCT_KEY
606	606	1	606
*/

--###################################################################################################################################

USE DATABASE ADVWORKS_DEV;
USE SCHEMA PREPARE;

CREATE OR REPLACE TABLE FACTINTERNETSALES_PREPARED
(
    PRODUCT_KEY                 INTEGER,
    ORDER_DATE_KEY              INTEGER,
    DUE_DATE_KEY                INTEGER,
    SHIP_DATE_KEY               INTEGER,
    CUSTOMER_KEY                INTEGER,
    PROMOTION_KEY               INTEGER,
    CURRENCY_KEY                INTEGER,
    SALES_TERRITORY_KEY         INTEGER,

    SALES_ORDER_NUMBER          VARCHAR(20),
    SALES_ORDER_LINE_NUMBER     INTEGER,
    REVISION_NUMBER             INTEGER,

    ORDER_QUANTITY               INTEGER,

    UNIT_PRICE                   NUMBER(19,4),
    EXTENDED_AMOUNT              NUMBER(19,4),
    UNIT_PRICE_DISCOUNT_PCT      FLOAT,
    DISCOUNT_AMOUNT              NUMBER(19,4),

    PRODUCT_STANDARD_COST        NUMBER(19,4),
    TOTAL_PRODUCT_COST           NUMBER(19,4),
    SALES_AMOUNT                 NUMBER(19,4),
    TAX_AMT                      NUMBER(19,4),
    FREIGHT                      NUMBER(19,4),

    CARRIER_TRACKING_NUMBER      VARCHAR(25),
    CUSTOMER_PO_NUMBER           VARCHAR(25),

    ORDER_DATE                   TIMESTAMP_NTZ,
    DUE_DATE                     TIMESTAMP_NTZ,
    SHIP_DATE                    TIMESTAMP_NTZ,

    SOURCE_FILE                  VARCHAR(500),
    LOAD_TIMESTAMP               TIMESTAMP_NTZ
);

/*
We're deliberately converting SQL Server types into appropriate Snowflake warehouse types:

SQL Server                 Snowflake
---------------------------------------------
int                    →   INTEGER
tinyint                →   INTEGER
smallint               →   INTEGER
money                  →   NUMBER(19,4)
float                  →   FLOAT
nvarchar(20)           →   VARCHAR(20)
datetime               →   TIMESTAMP_NTZ

For financial values such as:

UnitPrice
SalesAmount
TaxAmt
Freight

we use NUMBER, rather than floating point, because these are monetary values.

That's an important data-engineering design decision.
*/

-- Load PREPARE from LANDING
INSERT INTO ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED
(
    PRODUCT_KEY,
    ORDER_DATE_KEY,
    DUE_DATE_KEY,
    SHIP_DATE_KEY,
    CUSTOMER_KEY,
    PROMOTION_KEY,
    CURRENCY_KEY,
    SALES_TERRITORY_KEY,

    SALES_ORDER_NUMBER,
    SALES_ORDER_LINE_NUMBER,
    REVISION_NUMBER,

    ORDER_QUANTITY,

    UNIT_PRICE,
    EXTENDED_AMOUNT,
    UNIT_PRICE_DISCOUNT_PCT,
    DISCOUNT_AMOUNT,

    PRODUCT_STANDARD_COST,
    TOTAL_PRODUCT_COST,
    SALES_AMOUNT,
    TAX_AMT,
    FREIGHT,

    CARRIER_TRACKING_NUMBER,
    CUSTOMER_PO_NUMBER,

    ORDER_DATE,
    DUE_DATE,
    SHIP_DATE,

    SOURCE_FILE,
    LOAD_TIMESTAMP
)
SELECT
    RECORD:ProductKey::INTEGER,
    RECORD:OrderDateKey::INTEGER,
    RECORD:DueDateKey::INTEGER,
    RECORD:ShipDateKey::INTEGER,
    RECORD:CustomerKey::INTEGER,
    RECORD:PromotionKey::INTEGER,
    RECORD:CurrencyKey::INTEGER,
    RECORD:SalesTerritoryKey::INTEGER,

    RECORD:SalesOrderNumber::VARCHAR(20),
    RECORD:SalesOrderLineNumber::INTEGER,
    RECORD:RevisionNumber::INTEGER,

    RECORD:OrderQuantity::INTEGER,

    RECORD:UnitPrice::NUMBER(19,4),
    RECORD:ExtendedAmount::NUMBER(19,4),
    RECORD:UnitPriceDiscountPct::FLOAT,
    RECORD:DiscountAmount::NUMBER(19,4),

    RECORD:ProductStandardCost::NUMBER(19,4),
    RECORD:TotalProductCost::NUMBER(19,4),
    RECORD:SalesAmount::NUMBER(19,4),
    RECORD:TaxAmt::NUMBER(19,4),
    RECORD:Freight::NUMBER(19,4),

    RECORD:CarrierTrackingNumber::VARCHAR(25),
    RECORD:CustomerPONumber::VARCHAR(25),

    RECORD:OrderDate::TIMESTAMP_NTZ,
    RECORD:DueDate::TIMESTAMP_NTZ,
    RECORD:ShipDate::TIMESTAMP_NTZ,

    SOURCE_FILE,
    LOAD_TIMESTAMP
FROM ADVWORKS_DEV.LANDING.FACTINTERNETSALES_RAW; -- 60398

-- validate
SELECT
    (SELECT COUNT(*)
     FROM ADVWORKS_DEV.LANDING.FACTINTERNETSALES_RAW)
        AS LANDING_COUNT,

    (SELECT COUNT(*)
     FROM ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED)
        AS PREPARE_COUNT;
/*
LANDING_COUNT	PREPARE_COUNT
60398	60398
*/

-- null check
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PRODUCT_KEY IS NULL) AS NULL_PRODUCT_KEY,
    COUNT_IF(CUSTOMER_KEY IS NULL) AS NULL_CUSTOMER_KEY,
    COUNT_IF(ORDER_DATE_KEY IS NULL) AS NULL_ORDER_DATE_KEY,
    COUNT_IF(SALES_ORDER_NUMBER IS NULL) AS NULL_ORDER_NUMBER,
    COUNT_IF(SALES_ORDER_LINE_NUMBER IS NULL) AS NULL_ORDER_LINE_NUMBER,

    COUNT_IF(SALES_AMOUNT IS NULL) AS NULL_SALES_AMOUNT
FROM ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED;
/*
TOTAL_ROWS	NULL_PRODUCT_KEY	NULL_CUSTOMER_KEY	NULL_ORDER_DATE_KEY	NULL_ORDER_NUMBER	NULL_ORDER_LINE_NUMBER	NULL_SALES_AMOUNT
60398	0	0	0	0	0	0
*/

-- Validate the financial measures
SELECT
    COUNT(*) AS ROW_COUNT,
    SUM(SALES_AMOUNT) AS TOTAL_SALES,
    SUM(TOTAL_PRODUCT_COST) AS TOTAL_PRODUCT_COST,
    SUM(TAX_AMT) AS TOTAL_TAX,
    SUM(FREIGHT) AS TOTAL_FREIGHT,
    MIN(SALES_AMOUNT) AS MIN_SALES_AMOUNT,
    MAX(SALES_AMOUNT) AS MAX_SALES_AMOUNT
FROM ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED;
/*
ROW_COUNT	TOTAL_SALES	TOTAL_PRODUCT_COST	TOTAL_TAX	TOTAL_FREIGHT	MIN_SALES_AMOUNT	MAX_SALES_AMOUNT
60398	29358677.2207	17277793.5757	2348694.2301	733969.6091	2.2900	3578.2700
*/

-- Inspect the prepared data
SELECT
    PRODUCT_KEY,
    CUSTOMER_KEY,
    ORDER_DATE_KEY,
    SALES_ORDER_NUMBER,
    SALES_ORDER_LINE_NUMBER,
    ORDER_QUANTITY,
    UNIT_PRICE,
    SALES_AMOUNT,
    TAX_AMT,
    FREIGHT,
    ORDER_DATE,
    SOURCE_FILE
FROM ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED
ORDER BY SALES_ORDER_NUMBER
LIMIT 20;
/*
PRODUCT_KEY	CUSTOMER_KEY	ORDER_DATE_KEY	SALES_ORDER_NUMBER	SALES_ORDER_LINE_NUMBER	ORDER_QUANTITY	UNIT_PRICE	SALES_AMOUNT	TAX_AMT	FREIGHT	ORDER_DATE	SOURCE_FILE
310	21768	20101229	SO43697	1	1	3578.2700	3578.2700	286.2616	89.4568	2010-12-29 00:00:00.000	FactInternetSales_batch_003.jsonl
346	28389	20101229	SO43698	1	1	3399.9900	3399.9900	271.9992	84.9998	2010-12-29 00:00:00.000	FactInternetSales_batch_003.jsonl
346	25863	20101229	SO43699	1	1	3399.9900	3399.9900	271.9992	84.9998	2010-12-29 00:00:00.000	FactInternetSales_batch_003.jsonl
336	14501	20101229	SO43700	1	1	699.0982	699.0982	55.9279	17.4775	2010-12-29 00:00:00.000	FactInternetSales_batch_003.jsonl
346	11003	20101229	SO43701	1	1	3399.9900	3399.9900	271.9992	84.9998	2010-12-29 00:00:00.000	FactInternetSales_batch_003.jsonl
311	27645	20101230	SO43702	1	1	3578.2700	3578.2700	286.2616	89.4568	2010-12-30 00:00:00.000	FactInternetSales_batch_003.jsonl
310	16624	20101230	SO43703	1	1	3578.2700	3578.2700	286.2616	89.4568	2010-12-30 00:00:00.000	FactInternetSales_batch_003.jsonl
351	11005	20101230	SO43704	1	1	3374.9900	3374.9900	269.9992	84.3748	2010-12-30 00:00:00.000	FactInternetSales_batch_003.jsonl
344	11011	20101230	SO43705	1	1	3399.9900	3399.9900	271.9992	84.9998	2010-12-30 00:00:00.000	FactInternetSales_batch_003.jsonl
312	27621	20101231	SO43706	1	1	3578.2700	3578.2700	286.2616	89.4568	2010-12-31 00:00:00.000	FactInternetSales_batch_003.jsonl
312	27616	20101231	SO43707	1	1	3578.2700	3578.2700	286.2616	89.4568	2010-12-31 00:00:00.000	FactInternetSales_batch_003.jsonl
330	20042	20101231	SO43708	1	1	699.0982	699.0982	55.9279	17.4775	2010-12-31 00:00:00.000	FactInternetSales_batch_003.jsonl
313	16351	20101231	SO43709	1	1	3578.2700	3578.2700	286.2616	89.4568	2010-12-31 00:00:00.000	FactInternetSales_batch_003.jsonl
314	16517	20101231	SO43710	1	1	3578.2700	3578.2700	286.2616	89.4568	2010-12-31 00:00:00.000	FactInternetSales_batch_003.jsonl
314	27606	20110101	SO43711	1	1	3578.2700	3578.2700	286.2616	89.4568	2011-01-01 00:00:00.000	FactInternetSales_batch_003.jsonl
311	13513	20110101	SO43712	1	1	3578.2700	3578.2700	286.2616	89.4568	2011-01-01 00:00:00.000	FactInternetSales_batch_003.jsonl
310	27601	20110102	SO43713	1	1	3578.2700	3578.2700	286.2616	89.4568	2011-01-02 00:00:00.000	FactInternetSales_batch_003.jsonl
311	13591	20110102	SO43714	1	1	3578.2700	3578.2700	286.2616	89.4568	2011-01-02 00:00:00.000	FactInternetSales_batch_003.jsonl
314	16483	20110102	SO43715	1	1	3578.2700	3578.2700	286.2616	89.4568	2011-01-02 00:00:00.000	FactInternetSales_batch_003.jsonl
311	16529	20110102	SO43716	1	1	3578.2700	3578.2700	286.2616	89.4568	2011-01-02 00:00:00.000	FactInternetSales_batch_003.jsonl
*/

TRUNCATE TABLE ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED;
SELECT COUNT(*) AS PREPARE_COUNT
FROM ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED;

INSERT INTO ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED
(
    PRODUCT_KEY,
    ORDER_DATE_KEY,
    DUE_DATE_KEY,
    SHIP_DATE_KEY,
    CUSTOMER_KEY,
    PROMOTION_KEY,
    CURRENCY_KEY,
    SALES_TERRITORY_KEY,

    SALES_ORDER_NUMBER,
    SALES_ORDER_LINE_NUMBER,
    REVISION_NUMBER,

    ORDER_QUANTITY,

    UNIT_PRICE,
    EXTENDED_AMOUNT,
    UNIT_PRICE_DISCOUNT_PCT,
    DISCOUNT_AMOUNT,

    PRODUCT_STANDARD_COST,
    TOTAL_PRODUCT_COST,
    SALES_AMOUNT,
    TAX_AMT,
    FREIGHT,

    CARRIER_TRACKING_NUMBER,
    CUSTOMER_PO_NUMBER,

    ORDER_DATE,
    DUE_DATE,
    SHIP_DATE,

    SOURCE_FILE,
    LOAD_TIMESTAMP
)
SELECT
    RECORD:ProductKey::INTEGER,
    RECORD:OrderDateKey::INTEGER,
    RECORD:DueDateKey::INTEGER,
    RECORD:ShipDateKey::INTEGER,
    RECORD:CustomerKey::INTEGER,
    RECORD:PromotionKey::INTEGER,
    RECORD:CurrencyKey::INTEGER,
    RECORD:SalesTerritoryKey::INTEGER,

    RECORD:SalesOrderNumber::VARCHAR,
    RECORD:SalesOrderLineNumber::INTEGER,
    RECORD:RevisionNumber::INTEGER,

    RECORD:OrderQuantity::INTEGER,

    RECORD:UnitPrice::NUMBER(19,4),
    RECORD:ExtendedAmount::NUMBER(19,4),
    RECORD:UnitPriceDiscountPct::FLOAT,
    RECORD:DiscountAmount::NUMBER(19,4),

    RECORD:ProductStandardCost::NUMBER(19,4),
    RECORD:TotalProductCost::NUMBER(19,4),
    RECORD:SalesAmount::NUMBER(19,4),
    RECORD:TaxAmt::NUMBER(19,4),
    RECORD:Freight::NUMBER(19,4),

    RECORD:CarrierTrackingNumber::VARCHAR,
    RECORD:CustomerPONumber::VARCHAR,

    RECORD:OrderDate::TIMESTAMP_NTZ,
    RECORD:DueDate::TIMESTAMP_NTZ,
    RECORD:ShipDate::TIMESTAMP_NTZ,

    SOURCE_FILE,
    LOAD_TIMESTAMP

FROM ADVWORKS_DEV.LANDING.FACTINTERNETSALES_RAW; --60398

SELECT COUNT(*) AS PREPARE_COUNT
FROM ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED; --60398

-- null check
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PRODUCT_KEY IS NULL) AS NULL_PRODUCT_KEY,
    COUNT_IF(CUSTOMER_KEY IS NULL) AS NULL_CUSTOMER_KEY,
    COUNT_IF(ORDER_DATE_KEY IS NULL) AS NULL_ORDER_DATE_KEY,
    COUNT_IF(SALES_ORDER_NUMBER IS NULL) AS NULL_ORDER_NUMBER,
    COUNT_IF(SALES_ORDER_LINE_NUMBER IS NULL) AS NULL_ORDER_LINE_NUMBER,
    COUNT_IF(SALES_AMOUNT IS NULL) AS NULL_SALES_AMOUNT
FROM ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED;
/*
TOTAL_ROWS	NULL_PRODUCT_KEY	NULL_CUSTOMER_KEY	NULL_ORDER_DATE_KEY	NULL_ORDER_NUMBER	NULL_ORDER_LINE_NUMBER	NULL_SALES_AMOUNT
60398	0	0	0	0	0	0
*/

-- grain validation
SELECT
    SALES_ORDER_NUMBER,
    SALES_ORDER_LINE_NUMBER,
    COUNT(*) AS ROW_COUNT
FROM ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED
GROUP BY
    SALES_ORDER_NUMBER,
    SALES_ORDER_LINE_NUMBER
HAVING COUNT(*) > 1
ORDER BY SALES_ORDER_NUMBER; -- Query produced no results

SELECT
    COUNT(*) AS ROW_COUNT,
    SUM(SALES_AMOUNT) AS TOTAL_SALES,
    SUM(TOTAL_PRODUCT_COST) AS TOTAL_PRODUCT_COST,
    SUM(TAX_AMT) AS TOTAL_TAX,
    SUM(FREIGHT) AS TOTAL_FREIGHT,
    MIN(SALES_AMOUNT) AS MIN_SALES_AMOUNT,
    MAX(SALES_AMOUNT) AS MAX_SALES_AMOUNT
FROM ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED;
/*
ROW_COUNT	TOTAL_SALES	TOTAL_PRODUCT_COST	TOTAL_TAX	TOTAL_FREIGHT	MIN_SALES_AMOUNT	MAX_SALES_AMOUNT
60398	29358677.2207	17277793.5757	2348694.2301	733969.6091	2.2900	3578.2700
*/

ALTER TABLE ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARED 
RENAME TO ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARE ;

SELECT
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT CONCAT(
        SALES_ORDER_NUMBER,
        '|',
        SALES_ORDER_LINE_NUMBER
    )) AS DISTINCT_ORDER_LINES
FROM ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARE;
/*
ROW_COUNT	DISTINCT_ORDER_LINES
60398	60398
*/

SELECT
    MIN(ORDER_DATE) AS MIN_ORDER_DATE,
    MAX(ORDER_DATE) AS MAX_ORDER_DATE,
    MIN(SALES_AMOUNT) AS MIN_SALES_AMOUNT,
    MAX(SALES_AMOUNT) AS MAX_SALES_AMOUNT
FROM ADVWORKS_DEV.PREPARE.FACTINTERNETSALES_PREPARE;
/*
MIN_ORDER_DATE	MAX_ORDER_DATE	MIN_SALES_AMOUNT	MAX_SALES_AMOUNT
2010-12-29 00:00:00.000	2014-01-28 00:00:00.000	2.2900	3578.2700
*/

