SELECT
    CUSTOMER_KEY,
    FIRST_NAME,
    LAST_NAME,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    LOAD_TIMESTAMP,
    DBT_VALID_FROM,
    DBT_VALID_TO,
    DBT_SCD_ID
FROM ADVWORKS_DEV.SNAPSHOTS.DIM_CUSTOMER_SNAPSHOT
ORDER BY CUSTOMER_KEY
LIMIT 20;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	EMAIL_ADDRESS	YEARLY_INCOME	LOAD_TIMESTAMP	DBT_VALID_FROM	DBT_VALID_TO	DBT_SCD_ID
11000	Jon	Yang	jon24@adventure-works.com	90000.0000	2026-09-12 04:44:29.831	2026-09-12 04:44:29.831		bd842c6fc01f513293ddcdc6b4f6e42f
11000	Jon	Yang	jon24@adventure-works.com	90000.0000	2026-09-12 04:44:29.831	2026-09-12 04:44:29.831		bd842c6fc01f513293ddcdc6b4f6e42f
11000	Jon	Yang	jon24@adventure-works.com	90000.0000	2026-09-12 03:15:47.433	2026-09-12 03:15:47.433		fb8b3e5bcb12d9cedad7add86c16ff95
11001	Eugene	Huang	eugene10@adventure-works.com	60000.0000	2026-09-12 03:15:47.433	2026-09-12 03:15:47.433		08f3eb5e882fbadf725b8a6c4cb53aa8
11001	Eugene	Huang	eugene10@adventure-works.com	60000.0000	2026-09-12 04:44:29.831	2026-09-12 04:44:29.831		eeb275a48508590c92ec355803861609
11001	Eugene	Huang	eugene10@adventure-works.com	60000.0000	2026-09-12 04:44:29.831	2026-09-12 04:44:29.831		eeb275a48508590c92ec355803861609
11002	Ruben	Torres	ruben35@adventure-works.com	60000.0000	2026-09-12 04:44:29.831	2026-09-12 04:44:29.831		a6d844dbc3e2b474b8e078a963e12c6b
11002	Ruben	Torres	ruben35@adventure-works.com	60000.0000	2026-09-12 03:15:47.433	2026-09-12 03:15:47.433		15e5452e368c3f45716cf8ffba02813a
11002	Ruben	Torres	ruben35@adventure-works.com	60000.0000	2026-09-12 04:44:29.831	2026-09-12 04:44:29.831		a6d844dbc3e2b474b8e078a963e12c6b
11003	Christy	Zhu	christy12@adventure-works.com	70000.0000	2026-09-12 04:44:29.831	2026-09-12 04:44:29.831		9ed8c82089a2a2b5b646561aab0e05fd
11003	Christy	Zhu	christy12@adventure-works.com	70000.0000	2026-09-12 04:44:29.831	2026-09-12 04:44:29.831		9ed8c82089a2a2b5b646561aab0e05fd
11003	Christy	Zhu	christy12@adventure-works.com	70000.0000	2026-09-12 03:15:47.433	2026-09-12 03:15:47.433		f2476adff2c4555be16e430df7797a0c
11004	Elizabeth	Johnson	elizabeth5@adventure-works.com	80000.0000	2026-09-12 04:44:29.831	2026-09-12 04:44:29.831		4263c014b740c8a78b5b007beab9b03b
11004	Elizabeth	Johnson	elizabeth5@adventure-works.com	80000.0000	2026-09-12 03:15:47.433	2026-09-12 03:15:47.433		4ee07f26005329c41adba2d3ad250287
11004	Elizabeth	Johnson	elizabeth5@adventure-works.com	80000.0000	2026-09-12 04:44:29.831	2026-09-12 04:44:29.831		4263c014b740c8a78b5b007beab9b03b
11005	Julio	Ruiz	julio1@adventure-works.com	70000.0000	2026-09-12 03:15:47.433	2026-09-12 03:15:47.433		0bb048165f6032c578e7b2308e959b21
11005	Julio	Ruiz	julio1@adventure-works.com	70000.0000	2026-09-12 04:44:29.831	2026-09-12 04:44:29.831		e44e701957240e5342cfe215a5f67b6f
11005	Julio	Ruiz	julio1@adventure-works.com	70000.0000	2026-09-12 04:44:29.831	2026-09-12 04:44:29.831		e44e701957240e5342cfe215a5f67b6f
11006	Janet	Alvarez	janet9@adventure-works.com	70000.0000	2026-09-12 04:44:29.831	2026-09-12 04:44:29.831		304132fbb455e081edb25b1058025000
11006	Janet	Alvarez	janet9@adventure-works.com	70000.0000	2026-09-12 04:44:29.831	2026-09-12 04:44:29.831		304132fbb455e081edb25b1058025000
*/


SELECT
    CUSTOMER_KEY,
    FIRST_NAME,
    LAST_NAME,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    LOAD_TIMESTAMP
FROM ADVWORKS_DEV.PREPARE.DIM_CUSTOMER_PREPARE
ORDER BY CUSTOMER_KEY
LIMIT 1;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	EMAIL_ADDRESS	YEARLY_INCOME	LOAD_TIMESTAMP
11000	Jon	Yang	jon24@adventure-works.com	90000.0000	2026-09-12 03:15:47.433
*/


SELECT
    CUSTOMER_KEY,
    COUNT(*) AS ROW_COUNT
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE
GROUP BY CUSTOMER_KEY
HAVING COUNT(*) > 1
ORDER BY CUSTOMER_KEY; -- Query produced no results
/*

*/



SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT CUSTOMER_KEY) AS DISTINCT_CUSTOMERS
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE;
/*
TOTAL_ROWS	DISTINCT_CUSTOMERS
18484	      18484
*/



SELECT
    CUSTOMER_KEY,
    LOAD_TIMESTAMP,
    COUNT(*) AS ROW_COUNT
FROM ADVWORKS_DEV.PREPARE.DIM_CUSTOMER_PREPARE
WHERE CUSTOMER_KEY = 11000
GROUP BY CUSTOMER_KEY, LOAD_TIMESTAMP
ORDER BY LOAD_TIMESTAMP;
/*
CUSTOMER_KEY	LOAD_TIMESTAMP	            ROW_COUNT
11000	        2026-09-12 03:15:47.433	      1
11000	        2026-09-12 04:44:29.831	      2
*/


DROP TABLE IF EXISTS ADVWORKS_DEV.SNAPSHOTS.DIM_CUSTOMER_SNAPSHOT;

SELECT
    COUNT(*) AS SNAPSHOT_ROWS,
    COUNT(DISTINCT CUSTOMER_KEY) AS DISTINCT_CUSTOMERS
FROM ADVWORKS_DEV.SNAPSHOTS.DIM_CUSTOMER_SNAPSHOT;
/*
SNAPSHOT_ROWS	DISTINCT_CUSTOMERS
18484	          18484
*/


SELECT
    CUSTOMER_KEY,
    FIRST_NAME,
    LAST_NAME,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    LOAD_TIMESTAMP,
    DBT_VALID_FROM,
    DBT_VALID_TO,
    DBT_SCD_ID
FROM ADVWORKS_DEV.SNAPSHOTS.DIM_CUSTOMER_SNAPSHOT
WHERE CUSTOMER_KEY = 11000;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	EMAIL_ADDRESS	            YEARLY_INCOME	LOAD_TIMESTAMP	       DBT_VALID_FROM	         DBT_VALID_TO	DBT_SCD_ID
11000	          Jon	        Yang	jon24@adventure-works.com	90000.00	  2026-09-09 10:25:03.281	2026-09-09 10:25:03.281	 null	      2af0a1d1744326a6fe792985c89ef07d
*/


SELECT
    CUSTOMER_KEY,
    FIRST_NAME,
    LAST_NAME,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    LOAD_TIMESTAMP
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE
WHERE CUSTOMER_KEY = 11000;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	EMAIL_ADDRESS	            YEARLY_INCOME	LOAD_TIMESTAMP
11000	          Jon	        Yang	jon24@adventure-works.com	90000.00	    2026-09-09 10:25:03.281
*/

SELECT RAW_DATA, SOURCE_FILE, LOAD_TIMESTAMP FROM ADVWORKS_DEV.LANDING.DIM_CUSTOMER WHERE RAW_DATA:"CustomerKey"::NUMBER = 11000 ORDER BY LOAD_TIMESTAMP;
/*
RAW_DATA	SOURCE_FILE	LOAD_TIMESTAMP
{
  "AddressLine1": "3761 N. 14th St",
  "AddressLine2": null,
  "BirthDate": "1971-10-06",
  "CommuteDistance": "1-2 Miles",
  "CustomerAlternateKey": "AW00011000",
  "CustomerKey": 11000,
  "DateFirstPurchase": "2011-01-19",
  "EmailAddress": "jon24@adventure-works.com",
  "EnglishEducation": "Bachelors",
  "EnglishOccupation": "Professional",
  "FirstName": "Jon",
  "FrenchEducation": "Bac + 4",
  "FrenchOccupation": "Cadre",
  "Gender": "M",
  "GeographyKey": 26,
  "HouseOwnerFlag": "1",
  "LastName": "Yang",
  "MaritalStatus": "M",
  "MiddleName": "V",
  "NameStyle": false,
  "NumberCarsOwned": 0,
  "NumberChildrenAtHome": 0,
  "Phone": "1 (11) 500 555-0162",
  "SpanishEducation": "Licenciatura",
  "SpanishOccupation": "Profesional",
  "Suffix": null,
  "Title": null,
  "TotalChildren": 2,
  "YearlyIncome": 90000
}	dim_customer/DEV_TEST_DimCustomer_001.jsonl	2026-09-12 03:15:47.433
{
  "AddressLine1": "3761 N. 14th St",
  "AddressLine2": null,
  "BirthDate": "1971-10-06",
  "CommuteDistance": "1-2 Miles",
  "CustomerAlternateKey": "AW00011000",
  "CustomerKey": 11000,
  "DateFirstPurchase": "2011-01-19",
  "EmailAddress": "jon24@adventure-works.com",
  "EnglishEducation": "Bachelors",
  "EnglishOccupation": "Professional",
  "FirstName": "Jon",
  "FrenchEducation": "Bac + 4",
  "FrenchOccupation": "Cadre",
  "Gender": "M",
  "GeographyKey": 26,
  "HouseOwnerFlag": "1",
  "LastName": "Yang",
  "MaritalStatus": "M",
  "MiddleName": "V",
  "NameStyle": false,
  "NumberCarsOwned": 0,
  "NumberChildrenAtHome": 0,
  "Phone": "1 (11) 500 555-0162",
  "SpanishEducation": "Licenciatura",
  "SpanishOccupation": "Profesional",
  "Suffix": null,
  "Title": null,
  "TotalChildren": 2,
  "YearlyIncome": 90000
}	dim_customer/DimCustomer_batch_001.jsonl	2026-09-12 04:44:29.831
{
  "AddressLine1": "3761 N. 14th St",
  "AddressLine2": null,
  "BirthDate": "1971-10-06",
  "CommuteDistance": "1-2 Miles",
  "CustomerAlternateKey": "AW00011000",
  "CustomerKey": 11000,
  "DateFirstPurchase": "2011-01-19",
  "EmailAddress": "jon24@adventure-works.com",
  "EnglishEducation": "Bachelors",
  "EnglishOccupation": "Professional",
  "FirstName": "Jon",
  "FrenchEducation": "Bac + 4",
  "FrenchOccupation": "Cadre",
  "Gender": "M",
  "GeographyKey": 26,
  "HouseOwnerFlag": "1",
  "LastName": "Yang",
  "MaritalStatus": "M",
  "MiddleName": "V",
  "NameStyle": false,
  "NumberCarsOwned": 0,
  "NumberChildrenAtHome": 0,
  "Phone": "1 (11) 500 555-0162",
  "SpanishEducation": "Licenciatura",
  "SpanishOccupation": "Profesional",
  "Suffix": null,
  "Title": null,
  "TotalChildren": 2,
  "YearlyIncome": 90000
}	dim_customer/terraform_test_customer_001.jsonl	2026-09-12 04:44:29.831
*/

INSERT INTO ADVWORKS_DEV.LANDING.DIM_CUSTOMER
(
    RAW_DATA,
    SOURCE_FILE,
    LOAD_TIMESTAMP
)
SELECT
    PARSE_JSON('{
        "AddressLine1": "3761 N. 14th St",
        "AddressLine2": null,
        "BirthDate": "1971-10-06",
        "CommuteDistance": "1-2 Miles",
        "CustomerAlternateKey": "AW00011000",
        "CustomerKey": 11000,
        "DateFirstPurchase": "2011-01-19",
        "EmailAddress": "jon24@adventure-works.com",
        "EnglishEducation": "Bachelors",
        "EnglishOccupation": "Professional",
        "FirstName": "Jon",
        "FrenchEducation": "Bac + 4",
        "FrenchOccupation": "Cadre",
        "Gender": "M",
        "GeographyKey": 26,
        "HouseOwnerFlag": "1",
        "LastName": "Yang",
        "MaritalStatus": "M",
        "MiddleName": "V",
        "NameStyle": false,
        "NumberCarsOwned": 0,
        "NumberChildrenAtHome": 0,
        "Phone": "1 (11) 500 555-0162",
        "SpanishEducation": "Licenciatura",
        "SpanishOccupation": "Profesional",
        "Suffix": null,
        "Title": null,
        "TotalChildren": 2,
        "YearlyIncome": 95000
    }'),
    'dim_customer/CDC_DimCustomer_11000.jsonl',
    CURRENT_TIMESTAMP()
;
/*
number of rows inserted
1
*/


SELECT
    RAW_DATA:"CustomerKey"::NUMBER AS CUSTOMER_KEY,
    RAW_DATA:"FirstName"::VARCHAR AS FIRST_NAME,
    RAW_DATA:"LastName"::VARCHAR AS LAST_NAME,
    RAW_DATA:"YearlyIncome"::NUMBER AS YEARLY_INCOME,
    SOURCE_FILE,
    LOAD_TIMESTAMP
FROM ADVWORKS_DEV.LANDING.DIM_CUSTOMER
WHERE RAW_DATA:"CustomerKey"::NUMBER = 11000
ORDER BY LOAD_TIMESTAMP DESC;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	YEARLY_INCOME	SOURCE_FILE	LOAD_TIMESTAMP
11000	Jon	Yang	95000	dim_customer/CDC_DimCustomer_11000.jsonl	2026-09-26 01:21:12.308
11000	Jon	Yang	90000	dim_customer/DimCustomer_batch_001.jsonl	2026-09-12 04:44:29.831
11000	Jon	Yang	90000	dim_customer/terraform_test_customer_001.jsonl	2026-09-12 04:44:29.831
11000	Jon	Yang	90000	dim_customer/DEV_TEST_DimCustomer_001.jsonl	2026-09-12 03:15:47.433
*/



SELECT
    CUSTOMER_KEY,
    FIRST_NAME,
    LAST_NAME,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    LOAD_TIMESTAMP
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE
WHERE CUSTOMER_KEY = 11000;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	EMAIL_ADDRESS	            YEARLY_INCOME	LOAD_TIMESTAMP
11000	          Jon	        Yang	jon24@adventure-works.com	95000.00	    2026-09-26 01:21:12.308
*/



SELECT
    CUSTOMER_KEY,
    FIRST_NAME,
    LAST_NAME,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    LOAD_TIMESTAMP,
    DBT_VALID_FROM,
    DBT_VALID_TO,
    DBT_SCD_ID
FROM ADVWORKS_DEV.SNAPSHOTS.DIM_CUSTOMER_SNAPSHOT
WHERE CUSTOMER_KEY = 11000
ORDER BY DBT_VALID_FROM;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	EMAIL_ADDRESS	        YEARLY_INCOME	LOAD_TIMESTAMP	       DBT_VALID_FROM	             DBT_VALID_TO	               DBT_SCD_ID
11000	          Jon	    Yang	jon24@adventure-works.com	90000.00	2026-09-09 10:25:03.281	    2026-09-09 10:25:03.281	    2026-09-26 01:21:12.308	    2af0a1d1744326a6fe792985c89ef07d
11000	          Jon	    Yang	jon24@adventure-works.com	95000.00	2026-09-26 01:21:12.308	    2026-09-26 01:21:12.308		null                        5537c816a2d22ac9f55c4c42b2b9897a
*/


SELECT
    CUSTOMER_KEY,
    COUNT(*) AS VERSION_COUNT,
    COUNT_IF(DBT_VALID_TO IS NULL) AS CURRENT_VERSION_COUNT
FROM ADVWORKS_DEV.SNAPSHOTS.DIM_CUSTOMER_SNAPSHOT
WHERE CUSTOMER_KEY = 11000
GROUP BY CUSTOMER_KEY;
/*
CUSTOMER_KEY	VERSION_COUNT	CURRENT_VERSION_COUNT
11000	          2	                  1
*/


CREATE OR REPLACE TABLE ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC
LIKE ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE; -- Table DIM_CUSTOMER_CDC successfully created.

SELECT COUNT(*) FROM ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC; -- 0

CREATE OR REPLACE STREAM ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM
ON TABLE ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE; -- Stream DIM_CUSTOMER_CDC_STREAM successfully created.

SHOW STREAMS LIKE 'DIM_CUSTOMER_CDC_STREAM' IN SCHEMA ADVWORKS_DEV.SCHEMATIZE;
/*
created_on	name	database_name	schema_name	owner	comment	table_name	source_type	base_tables	type	stale	mode	stale_after	invalid_reason	owner_role_type
2026-09-26 02:31:20.486 -0700	DIM_CUSTOMER_CDC_STREAM	ADVWORKS_DEV	SCHEMATIZE	ACCOUNTADMIN		ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE	Table	ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE	DELTA	false	DEFAULT	2026-10-10 02:26:20.635 -0700	N/A	ROLE
*/

SELECT CUSTOMER_KEY, FIRST_NAME, LAST_NAME, YEARLY_INCOME, LOAD_TIMESTAMP
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE
WHERE CUSTOMER_KEY = 11000;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	YEARLY_INCOME	LOAD_TIMESTAMP
11000	Jon	Yang	95000.00	2026-09-26 01:21:12.308
*/


UPDATE ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE
SET YEARLY_INCOME = 100000,
    UPDATED_TIMESTAMP = CURRENT_TIMESTAMP()
WHERE CUSTOMER_KEY = 11000;
/*
number of rows updated	number of multi-joined rows updated
1	0
*/


SELECT
    CUSTOMER_KEY,
    FIRST_NAME,
    LAST_NAME,
    YEARLY_INCOME,
    LOAD_TIMESTAMP,
    UPDATED_TIMESTAMP,
    METADATA$ACTION,
    METADATA$ISUPDATE,
    METADATA$ROW_ID
FROM ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM
WHERE CUSTOMER_KEY = 11000;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	YEARLY_INCOME	LOAD_TIMESTAMP	UPDATED_TIMESTAMP	METADATA$ACTION	METADATA$ISUPDATE	METADATA$ROW_ID
11000	Jon	Yang	100000.00	2026-09-26 01:21:12.308	2026-09-26 02:33:55.036 -0700	INSERT	TRUE	d7f9abda0334e92e80d932e03e80d021c5f0c5a8
11000	Jon	Yang	95000.00	2026-09-26 01:21:12.308	2026-09-26 01:23:51.401 -0700	DELETE	TRUE	d7f9abda0334e92e80d932e03e80d021c5f0c5a8
*/


INSERT INTO ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC
SELECT *
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE
WHERE CUSTOMER_KEY = 11000;
/*
number of rows inserted
1
*/


SELECT CUSTOMER_KEY, FIRST_NAME, LAST_NAME, YEARLY_INCOME, UPDATED_TIMESTAMP
FROM ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC
WHERE CUSTOMER_KEY = 11000;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	YEARLY_INCOME	UPDATED_TIMESTAMP
11000	          jon	    Yang	       100000.00	2026-09-26 02:33:55.036 -0700
*/



CREATE OR REPLACE TASK ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_TASK
WAREHOUSE = ETL_WH_DEV
SCHEDULE = 'USING CRON * * * * * UTC'
WHEN SYSTEM$STREAM_HAS_DATA('ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM')
AS
MERGE INTO ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC AS TARGET
USING (
    SELECT *
    FROM ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM
    WHERE METADATA$ACTION = 'INSERT'
) AS SOURCE
ON TARGET.CUSTOMER_KEY = SOURCE.CUSTOMER_KEY

WHEN MATCHED THEN UPDATE SET
    TARGET.GEOGRAPHY_KEY = SOURCE.GEOGRAPHY_KEY,
    TARGET.CUSTOMER_ALTERNATE_KEY = SOURCE.CUSTOMER_ALTERNATE_KEY,
    TARGET.TITLE = SOURCE.TITLE,
    TARGET.FIRST_NAME = SOURCE.FIRST_NAME,
    TARGET.MIDDLE_NAME = SOURCE.MIDDLE_NAME,
    TARGET.LAST_NAME = SOURCE.LAST_NAME,
    TARGET.NAME_STYLE = SOURCE.NAME_STYLE,
    TARGET.BIRTH_DATE = SOURCE.BIRTH_DATE,
    TARGET.MARITAL_STATUS = SOURCE.MARITAL_STATUS,
    TARGET.SUFFIX = SOURCE.SUFFIX,
    TARGET.GENDER = SOURCE.GENDER,
    TARGET.EMAIL_ADDRESS = SOURCE.EMAIL_ADDRESS,
    TARGET.YEARLY_INCOME = SOURCE.YEARLY_INCOME,
    TARGET.TOTAL_CHILDREN = SOURCE.TOTAL_CHILDREN,
    TARGET.NUMBER_CHILDREN_AT_HOME = SOURCE.NUMBER_CHILDREN_AT_HOME,
    TARGET.ENGLISH_EDUCATION = SOURCE.ENGLISH_EDUCATION,
    TARGET.SPANISH_EDUCATION = SOURCE.SPANISH_EDUCATION,
    TARGET.FRENCH_EDUCATION = SOURCE.FRENCH_EDUCATION,
    TARGET.ENGLISH_OCCUPATION = SOURCE.ENGLISH_OCCUPATION,
    TARGET.SPANISH_OCCUPATION = SOURCE.SPANISH_OCCUPATION,
    TARGET.FRENCH_OCCUPATION = SOURCE.FRENCH_OCCUPATION,
    TARGET.HOUSE_OWNER_FLAG = SOURCE.HOUSE_OWNER_FLAG,
    TARGET.NUMBER_CARS_OWNED = SOURCE.NUMBER_CARS_OWNED,
    TARGET.ADDRESS_LINE_1 = SOURCE.ADDRESS_LINE_1,
    TARGET.ADDRESS_LINE_2 = SOURCE.ADDRESS_LINE_2,
    TARGET.PHONE = SOURCE.PHONE,
    TARGET.DATE_FIRST_PURCHASE = SOURCE.DATE_FIRST_PURCHASE,
    TARGET.COMMUTE_DISTANCE = SOURCE.COMMUTE_DISTANCE,
    TARGET.LOAD_TIMESTAMP = SOURCE.LOAD_TIMESTAMP,
    TARGET.CREATED_TIMESTAMP = SOURCE.CREATED_TIMESTAMP,
    TARGET.UPDATED_TIMESTAMP = SOURCE.UPDATED_TIMESTAMP

WHEN NOT MATCHED THEN INSERT (
    CUSTOMER_KEY,
    GEOGRAPHY_KEY,
    CUSTOMER_ALTERNATE_KEY,
    TITLE,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    NAME_STYLE,
    BIRTH_DATE,
    MARITAL_STATUS,
    SUFFIX,
    GENDER,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    TOTAL_CHILDREN,
    NUMBER_CHILDREN_AT_HOME,
    ENGLISH_EDUCATION,
    SPANISH_EDUCATION,
    FRENCH_EDUCATION,
    ENGLISH_OCCUPATION,
    SPANISH_OCCUPATION,
    FRENCH_OCCUPATION,
    HOUSE_OWNER_FLAG,
    NUMBER_CARS_OWNED,
    ADDRESS_LINE_1,
    ADDRESS_LINE_2,
    PHONE,
    DATE_FIRST_PURCHASE,
    COMMUTE_DISTANCE,
    LOAD_TIMESTAMP,
    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP
)
VALUES (
    SOURCE.CUSTOMER_KEY,
    SOURCE.GEOGRAPHY_KEY,
    SOURCE.CUSTOMER_ALTERNATE_KEY,
    SOURCE.TITLE,
    SOURCE.FIRST_NAME,
    SOURCE.MIDDLE_NAME,
    SOURCE.LAST_NAME,
    SOURCE.NAME_STYLE,
    SOURCE.BIRTH_DATE,
    SOURCE.MARITAL_STATUS,
    SOURCE.SUFFIX,
    SOURCE.GENDER,
    SOURCE.EMAIL_ADDRESS,
    SOURCE.YEARLY_INCOME,
    SOURCE.TOTAL_CHILDREN,
    SOURCE.NUMBER_CHILDREN_AT_HOME,
    SOURCE.ENGLISH_EDUCATION,
    SOURCE.SPANISH_EDUCATION,
    SOURCE.FRENCH_EDUCATION,
    SOURCE.ENGLISH_OCCUPATION,
    SOURCE.SPANISH_OCCUPATION,
    SOURCE.FRENCH_OCCUPATION,
    SOURCE.HOUSE_OWNER_FLAG,
    SOURCE.NUMBER_CARS_OWNED,
    SOURCE.ADDRESS_LINE_1,
    SOURCE.ADDRESS_LINE_2,
    SOURCE.PHONE,
    SOURCE.DATE_FIRST_PURCHASE,
    SOURCE.COMMUTE_DISTANCE,
    SOURCE.LOAD_TIMESTAMP,
    SOURCE.CREATED_TIMESTAMP,
    SOURCE.UPDATED_TIMESTAMP
);-- Task DIM_CUSTOMER_CDC_TASK successfully created.

SHOW TASKS LIKE 'DIM_CUSTOMER_CDC_TASK' IN SCHEMA ADVWORKS_DEV.SCHEMATIZE;
/*
created_on	name	id	database_name	schema_name	owner	comment	warehouse	schedule	predecessors	state	definition	condition	allow_overlapping_execution	error_integration	last_committed_on	last_suspended_on	owner_role_type	config	task_relations	last_suspended_reason	success_integration	scheduling_mode	target_completion_interval	execute_as_user	overlap_policy	created_by_user
2026-09-26 02:40:00.596 -0700	DIM_CUSTOMER_CDC_TASK	01c75384-b873-ab37-0000-0000000002c1	ADVWORKS_DEV	SCHEMATIZE	ACCOUNTADMIN		ETL_WH_DEV	USING CRON * * * * * UTC	[]	suspended	MERGE INTO ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC AS TARGET
USING (
    SELECT *
    FROM ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM
    WHERE METADATA$ACTION = 'INSERT'
) AS SOURCE
ON TARGET.CUSTOMER_KEY = SOURCE.CUSTOMER_KEY

WHEN MATCHED THEN UPDATE SET
    TARGET.GEOGRAPHY_KEY = SOURCE.GEOGRAPHY_KEY,
    TARGET.CUSTOMER_ALTERNATE_KEY = SOURCE.CUSTOMER_ALTERNATE_KEY,
    TARGET.TITLE = SOURCE.TITLE,
    TARGET.FIRST_NAME = SOURCE.FIRST_NAME,
    TARGET.MIDDLE_NAME = SOURCE.MIDDLE_NAME,
    TARGET.LAST_NAME = SOURCE.LAST_NAME,
    TARGET.NAME_STYLE = SOURCE.NAME_STYLE,
    TARGET.BIRTH_DATE = SOURCE.BIRTH_DATE,
    TARGET.MARITAL_STATUS = SOURCE.MARITAL_STATUS,
    TARGET.SUFFIX = SOURCE.SUFFIX,
    TARGET.GENDER = SOURCE.GENDER,
    TARGET.EMAIL_ADDRESS = SOURCE.EMAIL_ADDRESS,
    TARGET.YEARLY_INCOME = SOURCE.YEARLY_INCOME,
    TARGET.TOTAL_CHILDREN = SOURCE.TOTAL_CHILDREN,
    TARGET.NUMBER_CHILDREN_AT_HOME = SOURCE.NUMBER_CHILDREN_AT_HOME,
    TARGET.ENGLISH_EDUCATION = SOURCE.ENGLISH_EDUCATION,
    TARGET.SPANISH_EDUCATION = SOURCE.SPANISH_EDUCATION,
    TARGET.FRENCH_EDUCATION = SOURCE.FRENCH_EDUCATION,
    TARGET.ENGLISH_OCCUPATION = SOURCE.ENGLISH_OCCUPATION,
    TARGET.SPANISH_OCCUPATION = SOURCE.SPANISH_OCCUPATION,
    TARGET.FRENCH_OCCUPATION = SOURCE.FRENCH_OCCUPATION,
    TARGET.HOUSE_OWNER_FLAG = SOURCE.HOUSE_OWNER_FLAG,
    TARGET.NUMBER_CARS_OWNED = SOURCE.NUMBER_CARS_OWNED,
    TARGET.ADDRESS_LINE_1 = SOURCE.ADDRESS_LINE_1,
    TARGET.ADDRESS_LINE_2 = SOURCE.ADDRESS_LINE_2,
    TARGET.PHONE = SOURCE.PHONE,
    TARGET.DATE_FIRST_PURCHASE = SOURCE.DATE_FIRST_PURCHASE,
    TARGET.COMMUTE_DISTANCE = SOURCE.COMMUTE_DISTANCE,
    TARGET.LOAD_TIMESTAMP = SOURCE.LOAD_TIMESTAMP,
    TARGET.CREATED_TIMESTAMP = SOURCE.CREATED_TIMESTAMP,
    TARGET.UPDATED_TIMESTAMP = SOURCE.UPDATED_TIMESTAMP

WHEN NOT MATCHED THEN INSERT (
    CUSTOMER_KEY,
    GEOGRAPHY_KEY,
    CUSTOMER_ALTERNATE_KEY,
    TITLE,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    NAME_STYLE,
    BIRTH_DATE,
    MARITAL_STATUS,
    SUFFIX,
    GENDER,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    TOTAL_CHILDREN,
    NUMBER_CHILDREN_AT_HOME,
    ENGLISH_EDUCATION,
    SPANISH_EDUCATION,
    FRENCH_EDUCATION,
    ENGLISH_OCCUPATION,
    SPANISH_OCCUPATION,
    FRENCH_OCCUPATION,
    HOUSE_OWNER_FLAG,
    NUMBER_CARS_OWNED,
    ADDRESS_LINE_1,
    ADDRESS_LINE_2,
    PHONE,
    DATE_FIRST_PURCHASE,
    COMMUTE_DISTANCE,
    LOAD_TIMESTAMP,
    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP
)
VALUES (
    SOURCE.CUSTOMER_KEY,
    SOURCE.GEOGRAPHY_KEY,
    SOURCE.CUSTOMER_ALTERNATE_KEY,
    SOURCE.TITLE,
    SOURCE.FIRST_NAME,
    SOURCE.MIDDLE_NAME,
    SOURCE.LAST_NAME,
    SOURCE.NAME_STYLE,
    SOURCE.BIRTH_DATE,
    SOURCE.MARITAL_STATUS,
    SOURCE.SUFFIX,
    SOURCE.GENDER,
    SOURCE.EMAIL_ADDRESS,
    SOURCE.YEARLY_INCOME,
    SOURCE.TOTAL_CHILDREN,
    SOURCE.NUMBER_CHILDREN_AT_HOME,
    SOURCE.ENGLISH_EDUCATION,
    SOURCE.SPANISH_EDUCATION,
    SOURCE.FRENCH_EDUCATION,
    SOURCE.ENGLISH_OCCUPATION,
    SOURCE.SPANISH_OCCUPATION,
    SOURCE.FRENCH_OCCUPATION,
    SOURCE.HOUSE_OWNER_FLAG,
    SOURCE.NUMBER_CARS_OWNED,
    SOURCE.ADDRESS_LINE_1,
    SOURCE.ADDRESS_LINE_2,
    SOURCE.PHONE,
    SOURCE.DATE_FIRST_PURCHASE,
    SOURCE.COMMUTE_DISTANCE,
    SOURCE.LOAD_TIMESTAMP,
    SOURCE.CREATED_TIMESTAMP,
    SOURCE.UPDATED_TIMESTAMP
)	SYSTEM$STREAM_HAS_DATA('ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM')	false	null			ROLE		{"Predecessors":[]}		null				NO_OVERLAP	CHETANCHANDRA81
*/



EXECUTE TASK ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_TASK; -- Task DIM_CUSTOMER_CDC_TASK is scheduled to run immediately.

SELECT
    CUSTOMER_KEY,
    FIRST_NAME,
    LAST_NAME,
    YEARLY_INCOME,
    UPDATED_TIMESTAMP
FROM ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC
WHERE CUSTOMER_KEY = 11000;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	YEARLY_INCOME	UPDATED_TIMESTAMP
11000	          Jon	        Yang	100000.00	     2026-09-26 02:33:55.036 -0700
*/

SELECT
    NAME,
    STATE,
    SCHEDULED_TIME,
    QUERY_START_TIME,
    COMPLETED_TIME,
    ERROR_CODE,
    ERROR_MESSAGE
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'DIM_CUSTOMER_CDC_TASK',
    SCHEDULED_TIME_RANGE_START => DATEADD('minute', -10, CURRENT_TIMESTAMP())
))
ORDER BY SCHEDULED_TIME DESC;

/*
NAME	STATE	SCHEDULED_TIME	QUERY_START_TIME	COMPLETED_TIME	ERROR_CODE	ERROR_MESSAGE
DIM_CUSTOMER_CDC_TASK	SUCCEEDED	2026-09-26 02:42:22.134 -0700	2026-09-26 02:42:22.504 -0700	2026-09-26 02:42:24.844 -0700		
*/


SELECT SYSTEM$STREAM_HAS_DATA('ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM');
/*
SYSTEM$STREAM_HAS_DATA('ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM')
FALSE
*/

--------_________________________________________________________________________________________________________________________________________________________

SELECT CUSTOMER_KEY, FIRST_NAME, LAST_NAME, YEARLY_INCOME FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE WHERE CUSTOMER_KEY = 11001;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	YEARLY_INCOME
11001	Eugene	Huang	60000.00
*/


INSERT INTO ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC SELECT * FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE WHERE CUSTOMER_KEY = 11001;

SELECT CUSTOMER_KEY, FIRST_NAME, LAST_NAME, YEARLY_INCOME FROM ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC WHERE CUSTOMER_KEY = 11001;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	YEARLY_INCOME
11001	Eugene	Huang	60000.00
*/

DELETE FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE WHERE CUSTOMER_KEY = 11001;
SELECT CUSTOMER_KEY, FIRST_NAME, LAST_NAME FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE WHERE CUSTOMER_KEY = 11001; -- 0

SELECT
    CUSTOMER_KEY,
    FIRST_NAME,
    LAST_NAME,
    YEARLY_INCOME,
    METADATA$ACTION,
    METADATA$ISUPDATE,
    METADATA$ROW_ID
FROM ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM
WHERE CUSTOMER_KEY = 11001;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	YEARLY_INCOME	METADATA$ACTION	    METADATA$ISUPDATE	METADATA$ROW_ID
11001	          Eugene	Huang	       60000.00	           DELETE	         FALSE	      7c33f844c020f201ca5810d373d45e5248257014
*/


ALTER TASK ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_TASK SUSPEND;

CREATE OR REPLACE TASK ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_TASK
WAREHOUSE = ETL_WH_DEV
SCHEDULE = 'USING CRON * * * * * UTC'
WHEN SYSTEM$STREAM_HAS_DATA('ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM')
AS
MERGE INTO ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC AS TARGET
USING (
    SELECT *
    FROM ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM
    WHERE METADATA$ACTION = 'INSERT'
       OR (
            METADATA$ACTION = 'DELETE'
            AND METADATA$ISUPDATE = FALSE
          )
) AS SOURCE
ON TARGET.CUSTOMER_KEY = SOURCE.CUSTOMER_KEY

WHEN MATCHED
     AND SOURCE.METADATA$ACTION = 'DELETE'
     AND SOURCE.METADATA$ISUPDATE = FALSE
THEN DELETE

WHEN MATCHED
     AND SOURCE.METADATA$ACTION = 'INSERT'
THEN UPDATE SET
    TARGET.GEOGRAPHY_KEY = SOURCE.GEOGRAPHY_KEY,
    TARGET.CUSTOMER_ALTERNATE_KEY = SOURCE.CUSTOMER_ALTERNATE_KEY,
    TARGET.TITLE = SOURCE.TITLE,
    TARGET.FIRST_NAME = SOURCE.FIRST_NAME,
    TARGET.MIDDLE_NAME = SOURCE.MIDDLE_NAME,
    TARGET.LAST_NAME = SOURCE.LAST_NAME,
    TARGET.NAME_STYLE = SOURCE.NAME_STYLE,
    TARGET.BIRTH_DATE = SOURCE.BIRTH_DATE,
    TARGET.MARITAL_STATUS = SOURCE.MARITAL_STATUS,
    TARGET.SUFFIX = SOURCE.SUFFIX,
    TARGET.GENDER = SOURCE.GENDER,
    TARGET.EMAIL_ADDRESS = SOURCE.EMAIL_ADDRESS,
    TARGET.YEARLY_INCOME = SOURCE.YEARLY_INCOME,
    TARGET.TOTAL_CHILDREN = SOURCE.TOTAL_CHILDREN,
    TARGET.NUMBER_CHILDREN_AT_HOME = SOURCE.NUMBER_CHILDREN_AT_HOME,
    TARGET.ENGLISH_EDUCATION = SOURCE.ENGLISH_EDUCATION,
    TARGET.SPANISH_EDUCATION = SOURCE.SPANISH_EDUCATION,
    TARGET.FRENCH_EDUCATION = SOURCE.FRENCH_EDUCATION,
    TARGET.ENGLISH_OCCUPATION = SOURCE.ENGLISH_OCCUPATION,
    TARGET.SPANISH_OCCUPATION = SOURCE.SPANISH_OCCUPATION,
    TARGET.FRENCH_OCCUPATION = SOURCE.FRENCH_OCCUPATION,
    TARGET.HOUSE_OWNER_FLAG = SOURCE.HOUSE_OWNER_FLAG,
    TARGET.NUMBER_CARS_OWNED = SOURCE.NUMBER_CARS_OWNED,
    TARGET.ADDRESS_LINE_1 = SOURCE.ADDRESS_LINE_1,
    TARGET.ADDRESS_LINE_2 = SOURCE.ADDRESS_LINE_2,
    TARGET.PHONE = SOURCE.PHONE,
    TARGET.DATE_FIRST_PURCHASE = SOURCE.DATE_FIRST_PURCHASE,
    TARGET.COMMUTE_DISTANCE = SOURCE.COMMUTE_DISTANCE,
    TARGET.LOAD_TIMESTAMP = SOURCE.LOAD_TIMESTAMP,
    TARGET.CREATED_TIMESTAMP = SOURCE.CREATED_TIMESTAMP,
    TARGET.UPDATED_TIMESTAMP = SOURCE.UPDATED_TIMESTAMP

WHEN NOT MATCHED
     AND SOURCE.METADATA$ACTION = 'INSERT'
THEN INSERT (
    CUSTOMER_KEY,
    GEOGRAPHY_KEY,
    CUSTOMER_ALTERNATE_KEY,
    TITLE,
    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    NAME_STYLE,
    BIRTH_DATE,
    MARITAL_STATUS,
    SUFFIX,
    GENDER,
    EMAIL_ADDRESS,
    YEARLY_INCOME,
    TOTAL_CHILDREN,
    NUMBER_CHILDREN_AT_HOME,
    ENGLISH_EDUCATION,
    SPANISH_EDUCATION,
    FRENCH_EDUCATION,
    ENGLISH_OCCUPATION,
    SPANISH_OCCUPATION,
    FRENCH_OCCUPATION,
    HOUSE_OWNER_FLAG,
    NUMBER_CARS_OWNED,
    ADDRESS_LINE_1,
    ADDRESS_LINE_2,
    PHONE,
    DATE_FIRST_PURCHASE,
    COMMUTE_DISTANCE,
    LOAD_TIMESTAMP,
    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP
)
VALUES (
    SOURCE.CUSTOMER_KEY,
    SOURCE.GEOGRAPHY_KEY,
    SOURCE.CUSTOMER_ALTERNATE_KEY,
    SOURCE.TITLE,
    SOURCE.FIRST_NAME,
    SOURCE.MIDDLE_NAME,
    SOURCE.LAST_NAME,
    SOURCE.NAME_STYLE,
    SOURCE.BIRTH_DATE,
    SOURCE.MARITAL_STATUS,
    SOURCE.SUFFIX,
    SOURCE.GENDER,
    SOURCE.EMAIL_ADDRESS,
    SOURCE.YEARLY_INCOME,
    SOURCE.TOTAL_CHILDREN,
    SOURCE.NUMBER_CHILDREN_AT_HOME,
    SOURCE.ENGLISH_EDUCATION,
    SOURCE.SPANISH_EDUCATION,
    SOURCE.FRENCH_EDUCATION,
    SOURCE.ENGLISH_OCCUPATION,
    SOURCE.SPANISH_OCCUPATION,
    SOURCE.FRENCH_OCCUPATION,
    SOURCE.HOUSE_OWNER_FLAG,
    SOURCE.NUMBER_CARS_OWNED,
    SOURCE.ADDRESS_LINE_1,
    SOURCE.ADDRESS_LINE_2,
    SOURCE.PHONE,
    SOURCE.DATE_FIRST_PURCHASE,
    SOURCE.COMMUTE_DISTANCE,
    SOURCE.LOAD_TIMESTAMP,
    SOURCE.CREATED_TIMESTAMP,
    SOURCE.UPDATED_TIMESTAMP
); -- Task DIM_CUSTOMER_CDC_TASK successfully created.

EXECUTE TASK ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_TASK;

SELECT
    NAME,
    STATE,
    ERROR_CODE,
    ERROR_MESSAGE
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'DIM_CUSTOMER_CDC_TASK',
    SCHEDULED_TIME_RANGE_START => DATEADD('minute', -10, CURRENT_TIMESTAMP())
))
ORDER BY SCHEDULED_TIME DESC;
/*
NAME	                   STATE	ERROR_CODE	ERROR_MESSAGE
DIM_CUSTOMER_CDC_TASK	SUCCEEDED		NULL       NULL
*/

SELECT
    CUSTOMER_KEY,
    FIRST_NAME,
    LAST_NAME,
    YEARLY_INCOME
FROM ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC
WHERE CUSTOMER_KEY = 11001; -- Query produced no results

SELECT SYSTEM$STREAM_HAS_DATA(
    'ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM'
);
/*
"SYSTEM$STREAM_HAS_DATA(
    'ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM'
)"
FALSE
*/

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

SELECT CUSTOMER_KEY, FIRST_NAME, LAST_NAME, YEARLY_INCOME
FROM ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE
WHERE CUSTOMER_KEY = 11000;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	YEARLY_INCOME
11000	Jon	Yang	100000.00
*/


UPDATE ADVWORKS_DEV.NORMALIZE.DIM_CUSTOMER_NORMALIZE
SET YEARLY_INCOME = 105000,
    UPDATED_TIMESTAMP = CURRENT_TIMESTAMP()
WHERE CUSTOMER_KEY = 11000;
/*
number of rows updated	number of multi-joined rows updated
1	0
*/


SELECT
    CUSTOMER_KEY,
    YEARLY_INCOME,
    METADATA$ACTION,
    METADATA$ISUPDATE,
    METADATA$ROW_ID
FROM ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM
WHERE CUSTOMER_KEY = 11000
ORDER BY METADATA$ACTION;
/*
CUSTOMER_KEY	YEARLY_INCOME	METADATA$ACTION	METADATA$ISUPDATE	METADATA$ROW_ID
11000	          100000.00	      DELETE	         TRUE	       d7f9abda0334e92e80d932e03e80d021c5f0c5a8
11000	          105000.00	      INSERT	         TRUE	       d7f9abda0334e92e80d932e03e80d021c5f0c5a8
*/

EXECUTE TASK ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_TASK;

SELECT
    CUSTOMER_KEY,
    FIRST_NAME,
    LAST_NAME,
    YEARLY_INCOME,
    UPDATED_TIMESTAMP
FROM ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC
WHERE CUSTOMER_KEY = 11000;
/*
CUSTOMER_KEY	FIRST_NAME	LAST_NAME	YEARLY_INCOME	UPDATED_TIMESTAMP
11000	          Jon	        Yang	105000.00	 2026-09-26 03:00:20.102 -0700
*/

SELECT SYSTEM$STREAM_HAS_DATA(
    'ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM'
);

/*
"SYSTEM$STREAM_HAS_DATA(
    'ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER_CDC_STREAM'
)"
FALSE
*/
