/*
DIM_CUSTOMER
DIM_PRODUCT
DIM_DATE
FACT_SALES
        ↓
DATA_PRODUCT / MARKETPLACE
*/
-- ###########################################    DIM_CUSTOMER    ########################################### 
USE DATABASE ADVWORKS_DEV;
USE SCHEMA SCHEMATIZE;

CREATE OR REPLACE SEQUENCE CUSTOMER_SK_SEQ
START = 1
INCREMENT = 1;

CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_SK              INTEGER,
    CUSTOMER_KEY             INTEGER,
    CUSTOMER_ALTERNATE_KEY   VARCHAR(20),

    FIRST_NAME               VARCHAR(100),
    MIDDLE_NAME              VARCHAR(100),
    LAST_NAME                VARCHAR(100),

    FULL_NAME                VARCHAR(300),

    BIRTH_DATE               DATE,
    GENDER                   VARCHAR(1),
    MARITAL_STATUS           VARCHAR(1),

    EMAIL_ADDRESS            VARCHAR(255),
    YEARLY_INCOME            NUMBER(18,2),

    TOTAL_CHILDREN           INTEGER,
    HOUSE_OWNER_FLAG         BOOLEAN,
    NUMBER_CARS_OWNED        INTEGER,

    COMMUTE_DISTANCE         VARCHAR(50),

    SOURCE_FILE              VARCHAR(500),
    CREATED_TIMESTAMP        TIMESTAMP_NTZ,
    UPDATED_TIMESTAMP        TIMESTAMP_NTZ
);

--load it

INSERT INTO SCHEMATIZE.DIM_CUSTOMER
SELECT
    CUSTOMER_SK_SEQ.NEXTVAL,

    CUSTOMER_KEY,
    CUSTOMER_ALTERNATE_KEY,

    FIRST_NAME,
    MIDDLE_NAME,
    LAST_NAME,

    CONCAT_WS(
        ' ',
        FIRST_NAME,
        MIDDLE_NAME,
        LAST_NAME
    ) AS FULL_NAME,

    BIRTH_DATE,
    GENDER,
    MARITAL_STATUS,

    EMAIL_ADDRESS,
    YEARLY_INCOME,

    TOTAL_CHILDREN,
    HOUSE_OWNER_FLAG,
    NUMBER_CARS_OWNED,

    COMMUTE_DISTANCE,

    SOURCE_FILE,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()

FROM NORMALIZE.DIMCUSTOMER_NORMALIZED;

-- validate
SELECT COUNT(*)
FROM SCHEMATIZE.DIM_CUSTOMER; -- 18484

SELECT
    CUSTOMER_SK,
    CUSTOMER_KEY,
    FULL_NAME,
    EMAIL_ADDRESS
FROM SCHEMATIZE.DIM_CUSTOMER
ORDER BY CUSTOMER_SK
LIMIT 10;
/*
CUSTOMER_SK	CUSTOMER_KEY	FULL_NAME	EMAIL_ADDRESS
1	26000		connor40@adventure-works.com
2	26001	Nicholas G Lee	nicholas2@adventure-works.com
3	26002	Samuel J Walker	samuel72@adventure-works.com
4	26003		denise14@adventure-works.com
5	26004		arthur45@adventure-works.com
6	26005	Elizabeth J Clark	elizabeth23@adventure-works.com
7	26006		garrett10@adventure-works.com
8	26007		jesse13@adventure-works.com
9	26008		jennifer90@adventure-works.com
10	26009	Luis R Foster	luis15@adventure-works.com
*/

-- SCHEMATIZE.DIM_PRODUCT

USE DATABASE ADVWORKS_DEV;
USE SCHEMA SCHEMATIZE;

CREATE OR REPLACE TABLE DIM_PRODUCT
(
    PRODUCT_SK               INTEGER AUTOINCREMENT,
    PRODUCT_KEY              INTEGER,
    PRODUCT_ALTERNATE_KEY    VARCHAR(50),
    PRODUCT_NAME             VARCHAR(255),
    COLOR                    VARCHAR(50),
    SIZE                     VARCHAR(50),
    STANDARD_COST            NUMBER(18,2),
    LIST_PRICE               NUMBER(18,2),
    PRODUCT_SUBCATEGORY_KEY  INTEGER,
    START_DATE               DATE,
    END_DATE                 DATE,
    STATUS                   VARCHAR(50),
    CREATED_TIMESTAMP        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- LOAD DATA
INSERT INTO ADVWORKS_DEV.SCHEMATIZE.DIM_PRODUCT
(
    PRODUCT_KEY,
    PRODUCT_ALTERNATE_KEY,
    PRODUCT_NAME,
    COLOR,
    SIZE,
    STANDARD_COST,
    LIST_PRICE,
    PRODUCT_SUBCATEGORY_KEY,
    START_DATE,
    END_DATE,
    STATUS
)
SELECT
    PRODUCT_KEY,
    PRODUCT_ALTERNATE_KEY,
    ENGLISH_PRODUCT_NAME,
    COLOR,
    SIZE,
    STANDARD_COST,
    LIST_PRICE,
    PRODUCT_SUBCATEGORY_KEY,
    START_DATE,
    END_DATE,
    STATUS
FROM ADVWORKS_DEV.NORMALIZE.DIMPRODUCT_NORMALIZED; -- 606

-- VALIDATE
SELECT *
FROM ADVWORKS_DEV.SCHEMATIZE.DIM_PRODUCT
ORDER BY PRODUCT_KEY
LIMIT 10;
/*
PRODUCT_SK	PRODUCT_KEY	PRODUCT_ALTERNATE_KEY	PRODUCT_NAME	COLOR	SIZE	STANDARD_COST	LIST_PRICE	PRODUCT_SUBCATEGORY_KEY	START_DATE	END_DATE	STATUS	CREATED_TIMESTAMP
1	1	AR-5381	Adjustable Race	NA					2003-07-01		ACTIVE	2026-09-03 09:16:35.759
2	2	BA-8327	Bearing Ball	NA					2003-07-01		ACTIVE	2026-09-03 09:16:35.759
3	3	BE-2349	BB Ball Bearing	NA					2003-07-01		ACTIVE	2026-09-03 09:16:35.759
4	4	BE-2908	Headset Ball Bearings	NA					2003-07-01		ACTIVE	2026-09-03 09:16:35.759
5	5	BL-2036	Blade	NA					2003-07-01		ACTIVE	2026-09-03 09:16:35.759
6	6	CA-5965	LL Crankarm	Black					2003-07-01		ACTIVE	2026-09-03 09:16:35.759
7	7	CA-6738	ML Crankarm	Black					2003-07-01		ACTIVE	2026-09-03 09:16:35.759
8	8	CA-7457	HL Crankarm	Black					2003-07-01		ACTIVE	2026-09-03 09:16:35.759
9	9	CB-2903	Chainring Bolts	Silver					2003-07-01		ACTIVE	2026-09-03 09:16:35.759
10	10	CN-6137	Chainring Nut	Silver					2003-07-01		ACTIVE	2026-09-03 09:16:35.759
*/

-- COUNT AND DISTINCT CHECK
SELECT
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT PRODUCT_SK) AS DISTINCT_SURROGATE_KEYS,
    COUNT(DISTINCT PRODUCT_KEY) AS DISTINCT_PRODUCT_KEYS,
    MIN(PRODUCT_SK) AS MIN_PRODUCT_SK,
    MAX(PRODUCT_SK) AS MAX_PRODUCT_SK
FROM ADVWORKS_DEV.SCHEMATIZE.DIM_PRODUCT;
/*
ROW_COUNT	DISTINCT_SURROGATE_KEYS	DISTINCT_PRODUCT_KEYS	MIN_PRODUCT_SK	MAX_PRODUCT_SK
606	606	606	1	650
*/

-- DUPLICATE CHECK
SELECT
    PRODUCT_KEY,
    COUNT(*) AS CNT
FROM ADVWORKS_DEV.SCHEMATIZE.DIM_PRODUCT
GROUP BY PRODUCT_KEY
HAVING COUNT(*) > 1; --Query produced no results

-- SURROGATE KEY CHECK
SELECT
    COUNT(*) AS ROW_COUNT,
    COUNT(PRODUCT_SK) AS NON_NULL_SURROGATE_KEYS,
    COUNT(DISTINCT PRODUCT_SK) AS DISTINCT_SURROGATE_KEYS,
    COUNT(PRODUCT_KEY) AS NON_NULL_PRODUCT_KEYS,
    COUNT(DISTINCT PRODUCT_KEY) AS DISTINCT_PRODUCT_KEYS
FROM ADVWORKS_DEV.SCHEMATIZE.DIM_PRODUCT;
/*
ROW_COUNT	NON_NULL_SURROGATE_KEYS	DISTINCT_SURROGATE_KEYS	NON_NULL_PRODUCT_KEYS	DISTINCT_PRODUCT_KEYS
606	606	606	606	606
*/

-- MORE CHECK
SELECT
    PRODUCT_SK,
    PRODUCT_KEY,
    PRODUCT_ALTERNATE_KEY,
    PRODUCT_NAME,
    LIST_PRICE,
    STATUS
FROM ADVWORKS_DEV.SCHEMATIZE.DIM_PRODUCT
ORDER BY PRODUCT_SK
LIMIT 20;
/*
PRODUCT_SK	PRODUCT_KEY	PRODUCT_ALTERNATE_KEY	PRODUCT_NAME	LIST_PRICE	STATUS
1	1	AR-5381	Adjustable Race		ACTIVE
2	2	BA-8327	Bearing Ball		ACTIVE
3	3	BE-2349	BB Ball Bearing		ACTIVE
4	4	BE-2908	Headset Ball Bearings		ACTIVE
5	5	BL-2036	Blade		ACTIVE
6	6	CA-5965	LL Crankarm		ACTIVE
7	7	CA-6738	ML Crankarm		ACTIVE
8	8	CA-7457	HL Crankarm		ACTIVE
9	9	CB-2903	Chainring Bolts		ACTIVE
10	10	CN-6137	Chainring Nut		ACTIVE
11	11	CR-7833	Chainring		ACTIVE
12	12	CR-9981	Crown Race		ACTIVE
13	13	CS-2812	Chain Stays		ACTIVE
14	14	DC-8732	Decal 1		ACTIVE
15	15	DC-9824	Decal 2		ACTIVE
16	16	DT-2377	Down Tube		ACTIVE
17	17	EC-M092	Mountain End Caps		ACTIVE
18	18	EC-R098	Road End Caps		ACTIVE
19	19	EC-T209	Touring End Caps		ACTIVE
20	20	FE-3760	Fork End		ACTIVE
*/

--  #############################################################################################################################################
/*
Next step: SCHEMATIZE

This is where we turn the normalized transactional data into a proper dimensional/star schema.

Our target architecture:

                    ┌────────────────────┐
                    │   DIM_CUSTOMER   │
                    │   CUSTOMER_SK    │
                    └──────────┬─────────┘
                             │
                             │
┌────────────────────┐         │         ┌────────────────────┐
│    DIM_DATE      │         │         │    DIM_PRODUCT   │
│     DATE_SK      │──────────┼──────────│    PRODUCT_SK    │
└────────────────────┘         │         └──────────┬─────────┘
                             │                  │
                             ▼                  ▼
                    ┌──────────────────────────────────┐
                    │          FACT_SALES          │
                    │                              │
                    │ CUSTOMER_SK                  │
                    │ PRODUCT_SK                   │
                    │ ORDER_DATE_SK                │
                    │ SALES_ORDER_NUMBER           │
                    │ SALES_ORDER_LINE_NUMBER      │
                    │ QUANTITY                     │
                    │ SALES_AMOUNT                 │
                    │ TAX_AMOUNT                   │
                    │ FREIGHT                      │
                    └──────────────────────────────────┘

*/

--Validate DIM_PRODUCT
SELECT
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT PRODUCT_SK) AS DISTINCT_PRODUCT_SK,
    COUNT(DISTINCT PRODUCT_KEY) AS DISTINCT_PRODUCT_KEY,
    COUNT_IF(PRODUCT_SK IS NULL) AS NULL_PRODUCT_SK,
    COUNT_IF(PRODUCT_KEY IS NULL) AS NULL_PRODUCT_KEY
FROM ADVWORKS_DEV.SCHEMATIZE.DIM_PRODUCT;
/*
ROW_COUNT	DISTINCT_PRODUCT_SK	DISTINCT_PRODUCT_KEY	NULL_PRODUCT_SK	NULL_PRODUCT_KEY
606	606	606	0	0
*/

-- check whether every product referenced by the fact exists in the dimension:
SELECT
    COUNT(DISTINCT N.PRODUCT_KEY) AS NORMALIZE_PRODUCTS,
    COUNT(DISTINCT P.PRODUCT_KEY) AS DIM_PRODUCTS
FROM ADVWORKS_DEV.NORMALIZE.FACTINTERNETSALES_NORMALIZED N
LEFT JOIN ADVWORKS_DEV.SCHEMATIZE.DIM_PRODUCT P
    ON N.PRODUCT_KEY = P.PRODUCT_KEY;
/*
NORMALIZE_PRODUCTS	DIM_PRODUCTS
158	158
*/

-- check specifically for orphan product keys:
SELECT DISTINCT
    N.PRODUCT_KEY
FROM ADVWORKS_DEV.NORMALIZE.FACTINTERNETSALES_NORMALIZED N
LEFT JOIN ADVWORKS_DEV.SCHEMATIZE.DIM_PRODUCT P
    ON N.PRODUCT_KEY = P.PRODUCT_KEY
WHERE P.PRODUCT_KEY IS NULL
ORDER BY N.PRODUCT_KEY; -- Query produced no results

-- Validate DIM_CUSTOMER
SELECT
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT CUSTOMER_SK) AS DISTINCT_CUSTOMER_SK,
    COUNT(DISTINCT CUSTOMER_KEY) AS DISTINCT_CUSTOMER_KEY,
    COUNT_IF(CUSTOMER_SK IS NULL) AS NULL_CUSTOMER_SK,
    COUNT_IF(CUSTOMER_KEY IS NULL) AS NULL_CUSTOMER_KEY
FROM ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER;
/*
ROW_COUNT	DISTINCT_CUSTOMER_SK	DISTINCT_CUSTOMER_KEY	NULL_CUSTOMER_SK	NULL_CUSTOMER_KEY
18484	18484	18484	0	0
*/

-- check for orphan customers:
SELECT DISTINCT
    N.CUSTOMER_KEY
FROM ADVWORKS_DEV.NORMALIZE.FACTINTERNETSALES_NORMALIZED N
LEFT JOIN ADVWORKS_DEV.SCHEMATIZE.DIM_CUSTOMER C
    ON N.CUSTOMER_KEY = C.CUSTOMER_KEY
WHERE C.CUSTOMER_KEY IS NULL
ORDER BY N.CUSTOMER_KEY; -- Query produced no results   

