{{
  config(
    full_refresh = true,
    materialized="dynamic_table",
    target_lag="downstream",
    snowflake_warehouse= var('task_warehouse'),
    alias = "fact_Sales_Quote",
    schema= "facts",
    post_hook = "ALTER DYNAMIC TABLE {{ this }} SET LOG_LEVEL = ERROR"
  )
}}

SELECT
	DSQ.SALES_QUOTE_SK 					AS SALES_QUOTE_SK,			-- PRIMARY FOREIGN KEY
	QTP.QUOTED_TO_PROFILE_SK				AS QUOTED_TO_PROFILE_SK,		-- PRIMARY FOREIGN KEY
	DSC.SALES_CONTRACT_SK 					AS SALES_CONTRACT_SK,			-- FOREIGN KEY
	DD.DATE_KEY						AS SALES_QUOTE_INSCRIPTION_DATE_KEY,	-- FOREIGN KEY
	DD1.DATE_KEY						AS SALES_QUOTE_CLOSING_DATE_KEY,	-- FOREIGN KEY
	DSF.SALES_OFFICE_SK					AS SALES_OFFICE_SK,			-- FOREIGN KEY
	DSBF.SALES_BRANCH_OFFICE_SK				AS SALES_BRANCH_OFFICE_SK,		-- FOREIGN KEY
	DFC.FINANCIAL_COMPANY_SK				AS FINANCIAL_COMPANY_SK,		-- FOREIGN KEY
	DBU.BUSINESS_UNIT_SK					AS BUSINESS_UNIT_SK			-- FOREIGN KEY
FROM {{ref('norm_qc_quotation')}} QQ
	LEFT JOIN {{ref('norm_qc_quotation_customer')}} QQC ON QQ.OFFICE_CODE = QQC.OFFICE_CODE AND QQ.JOB_NO = QQC.JOB_NO
	LEFT JOIN {{ref('norm_customer')}} C ON QQC.CUSTOMER_UUID = C.CUSTOMER_UUID 
	LEFT JOIN {{ref('norm_branch_office_business_unit_map')}} BOBUM ON QQ.OFFICE_CODE = BOBUM.OFFICE_CODE AND QQ.BRANCH_OFFICE_CODE = BOBUM.BRANCH_OFFICE_CODE
	CROSS JOIN {{ref('norm_cmg_outbound_databases')}} COD
	LEFT JOIN {{ref('sche_dim_Sales_Quote')}} DSQ ON QQ.MASTER_JOB_NO = DSQ.SALES_QUOTE_CODE AND QQ.JOB_NO = DSQ.SALES_QUOTE_ALTERNATIVE_CODE 
		AND QQ.OFFICE_CODE = DSQ.SRC_OFFICE_CODE AND UPPER(DSQ.ORIGIN_APPLICATION_CODE) = 'SPM'
	LEFT JOIN {{ref('sche_dim_Quoted_To_Profile')}} QTP ON QQC.CUSTOMER_UUID = QTP.QUOTED_TO_PROFILE_CODE
	LEFT JOIN {{ref('sche_dim_Sales_Contract')}} DSC ON QQ.JOB_NO = DSC.SALES_CONTRACT_CODE 
		AND QQ.OFFICE_CODE = DSC.SRC_OFFICE_CODE AND UPPER(DSC.ORIGIN_APPLICATION_CODE) = 'SPM'
	LEFT JOIN {{ref('sche_dim_Date')}} DD ON QQ.INSCRP_DATE = DD.FULL_DATE 
	LEFT JOIN {{ref('sche_dim_Date')}} DD1 ON QQ.BID_DATE = DD1.FULL_DATE
	LEFT JOIN {{ref('sche_dim_Sales_Office')}} DSF ON QQ.OFFICE_CODE = DSF.ORIGIN_OFFICE_CODE
	LEFT JOIN {{ref('sche_dim_Sales_Branch_Office')}} DSBF ON QQ.OFFICE_CODE = DSBF.ORIGIN_OFFICE_CODE AND QQ.BRANCH_OFFICE_CODE = DSBF.ORIGIN_BRANCH_OFFICE_CODE
	LEFT JOIN {{ref('sche_dim_Financial_Company')}} DFC ON COD.RDM_FINANCIAL_COMPANY_CODE = DFC.FINANCIAL_COMPANY_CODE
	LEFT JOIN {{ref('sche_dim_Business_Unit')}} DBU ON BOBUM.BUSINESS_UNIT_CODE = DBU.BUSINESS_UNIT_CODE
    WHERE QQ.PROJCT_STEP IS NOT NULL