{{
  config(
    full_refresh = true,
    materialized="dynamic_table",
    target_lag="downstream",
    snowflake_warehouse= var('task_warehouse'),
    alias = "fact_Sales_Contract",
    schema= "facts",
    post_hook = "ALTER DYNAMIC TABLE {{ this }} SET LOG_LEVEL = ERROR"
  )
}}

SELECT
	 DSC.SALES_CONTRACT_SK			        AS SALES_CONTRACT_SK,			-- PRIMARY FOREIGN KEY
	 DP.PROJECT_SK 					AS PROJECT_SK,				-- FOREIGN KEY
	 DC.CUSTOMER_SK					AS SOLD_TO_CUSTOMER_SK,			-- FOREIGN KEY
	 DSQ.SALES_QUOTE_SK				AS SALES_QUOTE_SK,			-- FOREIGN KEY
	 DD.DATE_KEY					AS SALES_CONTRACT_DATE_KEY,		-- FOREIGN KEY
	 DSF.SALES_OFFICE_SK			        AS SALES_OFFICE_SK,			-- FOREIGN KEY
	 DSBF.SALES_BRANCH_OFFICE_SK	                AS SALES_BRANCH_OFFICE_SK,	        -- FOREIGN KEY
	 DFC.FINANCIAL_COMPANY_SK		        AS FINANCIAL_COMPANY_SK,		-- FOREIGN KEY
	 DBU.BUSINESS_UNIT_SK			        AS BUSINESS_UNIT_SK			-- FOREIGN KEY
FROM {{ref('norm_qc_quotation')}} QQ
	INNER JOIN {{ref('norm_projet_g')}} PG ON QQ.JOB_NO = PG.JOB_NO
	LEFT JOIN {{ref('norm_projet_e')}} PE ON QQ.NO_PROJET = PE.NO_PROJET
	LEFT JOIN {{ref('norm_customer')}} C ON QQ.CONTRACT_CUSTOMER_UUID = C.CUSTOMER_UUID
	LEFT JOIN {{ref('norm_branch_office_business_unit_map')}} BOBUM ON QQ.OFFICE_CODE = BOBUM.OFFICE_CODE AND QQ.BRANCH_OFFICE_CODE = BOBUM.BRANCH_OFFICE_CODE
	CROSS JOIN {{ref('norm_cmg_outbound_databases')}} COD
	LEFT JOIN {{ref('sche_dim_Sales_Contract')}} DSC ON QQ.JOB_NO = DSC.SALES_CONTRACT_CODE AND QQ.OFFICE_CODE = DSC.SRC_OFFICE_CODE AND UPPER(DSC.ORIGIN_APPLICATION_CODE) = 'SPM'
	LEFT JOIN {{ref('sche_dim_Project')}} DP ON QQ.NO_PROJET = DP.PROJECT_CODE AND COD.RDM_FINANCIAL_COMPANY_CODE = DP.FINANCIAL_COMPANY_CODE
	LEFT JOIN {{ref('sche_dim_Customer')}} DC ON C.CUST_NO = DC.CUSTOMER_CODE
	LEFT JOIN {{ref('sche_dim_Sales_Quote')}} DSQ ON QQ.MASTER_JOB_NO = DSQ.SALES_QUOTE_CODE AND QQ.JOB_NO = DSQ.SALES_QUOTE_ALTERNATIVE_CODE 
		AND QQ.OFFICE_CODE = DSQ.SRC_OFFICE_CODE AND UPPER(DSQ.ORIGIN_APPLICATION_CODE) = 'SPM'	
	LEFT JOIN {{ref('sche_dim_Date')}} DD ON PE.D_OUVERTURE = DD.FULL_DATE 
	LEFT JOIN {{ref('sche_dim_Sales_Office')}} DSF ON QQ.OFFICE_CODE = DSF.SRC_OFFICE_CODE
	LEFT JOIN {{ref('sche_dim_Sales_Branch_Office')}} DSBF ON QQ.OFFICE_CODE = DSBF.SRC_OFFICE_CODE AND QQ.BRANCH_OFFICE_CODE = DSBF.SRC_BRANCH_OFFICE_CODE
	LEFT JOIN {{ref('sche_dim_Financial_Company')}} DFC ON COD.RDM_FINANCIAL_COMPANY_CODE = DFC.FINANCIAL_COMPANY_CODE
	LEFT JOIN {{ref('sche_dim_Business_Unit')}} DBU ON BOBUM.BUSINESS_UNIT_CODE = DBU.BUSINESS_UNIT_CODE
WHERE QQ.PROJCT_STEP BETWEEN 15 AND 95