{{
  config(
    full_refresh = true,
    materialized="dynamic_table",
    target_lag="downstream",
    snowflake_warehouse= var('task_warehouse'),
    alias = "fact_Sales_Contract_Line",
    schema= "facts",
    post_hook = "ALTER DYNAMIC TABLE {{ this }} SET LOG_LEVEL = ERROR"
  )
}}



WITH SS_QC_QUOTATION_PRODUCT AS
(
	SELECT 
		COD.RDM_FINANCIAL_COMPANY_CODE AS FINANCIAL_COMPANY_CODE,
		QQ.NO_PROJET,
		QQ.OFFICE_CODE,
		QQ.BRANCH_OFFICE_CODE,
		QQ.MASTER_JOB_NO,
		QQ.JOB_NO,
		PE.D_OUVERTURE,
		BOBUM.BUSINESS_UNIT_CODE,
		C.CUST_NO,
		QQP.ACC_NO,
		QQP.ESTIMT_MODUL,
		QQP.SEQ_NO,
		QQP.GROUP_NO,
		QQP.PRODCT_NO,
		QQP.STD,
		QQP.DECK,
		QQP.BUD_WEIGHT,
		QQP.MEASURE_QTY,
		QQP.QTY_1,
		QQP.EST_DELI_COST,
		QQP.DSG_COST_4,
		CASE 
	        WHEN QQP.SPM_PRODCT_NO = 121 THEN T.TASK_NUMBER
	        ELSE PS.TASK_NUMBER 
	    END AS TASK_NUMBER,
		UOM.TYPE AS UOM_TYPE,
		CASE WHEN QQP.BUD_WEIGHT IS NOT NULL
			THEN 
				CASE WHEN QQP.ESTIMT_MODUL = 2
				THEN 'KG' ELSE 'LB' END
			ELSE 'N/A' END 												AS WEIGHT_UOM_CODE,
		CASE WHEN QQP.ESTIMT_MODUL = 2 
				AND QQP.STD = 1
				AND UOM.TYPE = 3 
				AND QQP.DECK = 0
			THEN 'M'
			ELSE 'N/A' END 												AS LENGTH_UOM_CODE,
		CASE WHEN QQP.DECK = 1 THEN 'SF' ELSE 'N/A' END 				AS AREA_UOM_CODE,
		CASE WHEN QQP.QTY_1 IS NOT NULL THEN 'UN' ELSE 'N/A' END		AS QUANTITY_UOM_CODE,
		QQP.RDM_CURRENCY_CODE 											AS PRICE_CURRENCY_CODE
	FROM {{ref('norm_qc_quotation')}} QQ
		INNER JOIN {{ref('norm_projet_g')}} PG ON QQ.JOB_NO = PG.JOB_NO
		LEFT JOIN {{ref('norm_projet_e')}} PE ON QQ.NO_PROJET = PE.NO_PROJET
		LEFT JOIN {{ref('norm_branch_office_business_unit_map')}} BOBUM ON QQ.OFFICE_CODE = BOBUM.OFFICE_CODE AND QQ.BRANCH_OFFICE_CODE = BOBUM.BRANCH_OFFICE_CODE
		LEFT JOIN {{ref('norm_customer')}} C ON QQ.CONTRACT_CUSTOMER_UUID = C.CUSTOMER_UUID
		LEFT JOIN {{ref('norm_qc_quotation_product')}} QQP ON QQ.OFFICE_CODE = QQP.OFFICE_CODE AND QQ.JOB_NO = QQP.JOB_NO
		INNER JOIN {{ref('norm_produit_s')}} PS ON QQP.SPM_PRODCT_NO = PS.NO_PRODUIT AND QQP.SPM_ENTITY_CODE = PS.ENTITY_CODE 
		-- special Case with 121 spm_prodct_no (Subcontracted sellable Item) N/A item...  use group_no and get the first task number
		LEFT JOIN (
		    SELECT 
		        SALES_GROUP_CODE, 
		        TASK_NUMBER,
		        ROW_NUMBER() OVER (PARTITION BY SALES_GROUP_CODE ORDER BY TASK_NUMBER) AS RN
		    FROM {{ref('norm_cmg_task')}}
			) T ON T.SALES_GROUP_CODE = QQP.GROUP_NO AND T.RN = 1
		LEFT JOIN {{ref('norm_uom')}} UOM ON QQP.UDM_ALT = UOM.UOM_CODE
		CROSS JOIN {{ref('norm_cmg_outbound_databases')}} COD
	WHERE QQ.PROJCT_STEP BETWEEN 15 AND 95
	AND (QQP.ACC_NO <> 0 OR QQP.PRODCT_NO <> 0)
	AND QQP.PRODCT_NO <> 999
	AND UPPER(QQP.SPM_ENTITY_CODE) <> 'BREAK'
	AND (QQP.ESTIMT_MODUL <> 4 OR (QQP.ESTIMT_MODUL = 4 AND QQP.QC_QUOT_PRODUCT_HIERARCHY_UUID IS NOT NULL))
), SS_QC_QUOTATION_PRODUCT_FEE_AND_BREAK AS 
(
	SELECT
		OFFICE_CODE AS OFFICE_CODE,
		JOB_NO,
		GROUP_NO,
		SUM(CASE 
        WHEN ESTIMT_MODUL = 2 AND BREAK_AMT = 1 THEN 0
        WHEN ESTIMT_MODUL = 1 THEN DSG_COST_5 
        ELSE EST_PROD_COST 
    END) AS FEE_AND_BREAK_AMOUNT
	FROM {{ref('norm_qc_quotation_product')}}
	WHERE BREAK_AMT <> 0
	GROUP BY OFFICE_CODE, JOB_NO, GROUP_NO
) 

SELECT
	DSC.SALES_CONTRACT_SK :: VARCHAR(32)											AS SALES_CONTRACT_SK,					-- PRIMARY FOREIGN KEY
	DSCL.SALES_CONTRACT_LINE_SK :: VARCHAR(32) 									AS SALES_CONTRACT_LINE_SK,	 			-- PRIMARY FOREIGN KEY
 	DP.PROJECT_SK :: VARCHAR(32) 													AS PROJECT_SK, 							-- FOREIGN KEY
	--DPA.PROJECT_ACTIVITY_SK 										AS PROJECT_ACTIVITY_SK,					-- FOREIGN KEY
	DC.CUSTOMER_SK :: VARCHAR(32)													AS SOLD_TO_CUSTOMER_SK,					-- FOREIGN KEY	
	DSQ.SALES_QUOTE_SK :: VARCHAR(32) 												AS SALES_QUOTE_SK,						-- FOREIGN KEY
	DSQL.SALES_QUOTE_LINE_SK :: VARCHAR(32) 										AS SALES_QUOTE_LINE_SK,					-- FOREIGN KEY
	DD.DATE_KEY :: STRING													AS SALES_CONTRACT_DATE_KEY,				-- FOREIGN KEY
	DI.ITEM_SK :: VARCHAR(32) 														AS ITEM_SK,								-- FOREIGN KEY
	DSF.SALES_OFFICE_SK :: VARCHAR(32)												AS SALES_OFFICE_SK,						-- FOREIGN KEY
	DSBF.SALES_BRANCH_OFFICE_SK :: VARCHAR(32)										AS SALES_BRANCH_OFFICE_SK,				-- FOREIGN KEY
	DFC.FINANCIAL_COMPANY_SK :: VARCHAR(32)										AS FINANCIAL_COMPANY_SK,				-- FOREIGN KEY
	DBU.BUSINESS_UNIT_SK :: VARCHAR(32)											AS BUSINESS_UNIT_SK,					-- FOREIGN KEY
	DUOM.UOM_SK :: VARCHAR(32)	 												AS WEIGHT_UOM_SK,						-- FOREIGN KEY
	DUOM1.UOM_SK :: VARCHAR(32)													AS LENGTH_UOM_SK,						-- FOREIGN KEY
	DUOM2.UOM_SK :: VARCHAR(32) 													AS AREA_UOM_SK,							-- FOREIGN KEY
	DUOM3.UOM_SK :: VARCHAR(32)													AS QUANTITY_UOM_SK,						-- FOREIGN KEY
	DCU.CURRENCY_SK :: VARCHAR(32)							 						AS PRICE_CURRENCY_SK,					-- FOREIGN KEY
	DCU1.CURRENCY_SK :: VARCHAR(32)												AS TO_CURRENCY_CAD_SK,					-- FOREIGN KEY
	DCU2.CURRENCY_SK :: VARCHAR(32)												AS TO_CURRENCY_USD_SK,					-- FOREIGN KEY
	DERT.EXCHANGE_RATE_TYPE_SK :: VARCHAR(32) 										AS FISCAL_PERIOD_END_AVG_EXCHANGE_RATE_TYPE_SK,
	IFNULL(SQQP.BUD_WEIGHT,0) :: NUMBER(38,4)	 									AS WEIGHT,
	CASE WHEN SQQP.ESTIMT_MODUL = 2 
			AND SQQP.STD = 1
			AND SQQP.UOM_TYPE = 3
			AND SQQP.DECK = 0
		THEN SQQP.MEASURE_QTY
		ELSE 0 END :: NUMBER(38,4)													AS LENGTH,
	CASE WHEN SQQP.DECK = 1 THEN SQQP.QTY_1 ELSE 0 END :: INTEGER 				AS AREA,
	IFNULL(SQQP.QTY_1,0) :: INTEGER											AS QUANTITY,
	IFNULL(SQQP.EST_DELI_COST,0) - 
		IFNULL(CASE WHEN SQQP.ACC_NO = 0 AND SQQP.PRODCT_NO <> 0 
		THEN (SQQPFB.FEE_AND_BREAK_AMOUNT + SQQP.DSG_COST_4)
		ELSE 0 END,0) :: NUMBER(38,4)												AS GROSS_PRICE_LINE_AMOUNT
FROM SS_QC_QUOTATION_PRODUCT SQQP
	LEFT JOIN SS_QC_QUOTATION_PRODUCT_FEE_AND_BREAK SQQPFB ON SQQP.OFFICE_CODE = SQQPFB.OFFICE_CODE
		AND SQQP.JOB_NO = SQQPFB.JOB_NO
		AND SQQP.GROUP_NO = SQQPFB.GROUP_NO
	LEFT JOIN {{ref('sche_dim_Sales_Contract')}} DSC ON SQQP.JOB_NO = DSC.SALES_CONTRACT_CODE 
		AND SQQP.OFFICE_CODE = DSC.SRC_OFFICE_CODE AND UPPER(DSC.ORIGIN_APPLICATION_CODE) = 'SPM'
	LEFT JOIN {{ref('sche_dim_Sales_Contract_Line')}} DSCL ON SQQP.JOB_NO = DSCL.SALES_CONTRACT_CODE
		AND SQQP.OFFICE_CODE = DSCL.SRC_OFFICE_CODE AND CONCAT(SQQP.ESTIMT_MODUL,'-',SQQP.SEQ_NO) = DSCL.SALES_CONTRACT_LINE_CODE AND UPPER(DSCL.ORIGIN_APPLICATION_CODE) = 'SPM'
	LEFT JOIN {{ref('sche_dim_Project')}} DP ON SQQP.NO_PROJET = DP.PROJECT_CODE AND SQQP.FINANCIAL_COMPANY_CODE = DP.FINANCIAL_COMPANY_CODE
	--LEFT JOIN {{ref('sche_dim_Project_Activity')}} DPA ON SQQP.PROJECT_ACTIVITY_CODE = DPA.PROJECT_ACTIVITY_CODE AND SQQP.PROJECT_ACTIVITY_TYPE_CODE = DPA.PROJECT_ACTIVITY_TYPE_CODE
	LEFT JOIN {{ref('sche_dim_Customer')}} DC ON SQQP.CUST_NO = DC.CUSTOMER_CODE
	LEFT JOIN {{ref('sche_dim_Sales_Quote')}} DSQ ON SQQP.MASTER_JOB_NO = DSQ.SALES_QUOTE_CODE AND SQQP.JOB_NO = DSQ.SALES_QUOTE_ALTERNATIVE_CODE 
		AND SQQP.OFFICE_CODE = DSQ.SRC_OFFICE_CODE AND UPPER(DSQ.ORIGIN_APPLICATION_CODE) = 'SPM'
	LEFT JOIN {{ref('sche_dim_Sales_Quote_Line')}} DSQL ON SQQP.MASTER_JOB_NO = DSQL.SALES_QUOTE_CODE AND SQQP.JOB_NO = DSQL.SALES_QUOTE_ALTERNATIVE_CODE
		AND SQQP.OFFICE_CODE = DSQL.SRC_OFFICE_CODE AND CONCAT(SQQP.ESTIMT_MODUL,'-',SQQP.SEQ_NO) = DSQL.SALES_QUOTE_LINE_CODE AND UPPER(DSQL.ORIGIN_APPLICATION_CODE) = 'SPM'
	LEFT JOIN {{ref('sche_dim_Date')}} DD ON SQQP.D_OUVERTURE = DD.FULL_DATE
	LEFT JOIN {{ref('sche_dim_Item')}} DI ON SQQP.TASK_NUMBER = DI.ITEM_CODE
	LEFT JOIN {{ref('sche_dim_Sales_Office')}} DSF ON SQQP.OFFICE_CODE = DSF.ORIGIN_OFFICE_CODE
	LEFT JOIN {{ref('sche_dim_Sales_Branch_Office')}} DSBF ON SQQP.OFFICE_CODE = DSBF.ORIGIN_OFFICE_CODE AND SQQP.BRANCH_OFFICE_CODE = DSBF.ORIGIN_BRANCH_OFFICE_CODE
	LEFT JOIN {{ref('sche_dim_Financial_Company')}} DFC ON SQQP.FINANCIAL_COMPANY_CODE = DFC.FINANCIAL_COMPANY_CODE
	LEFT JOIN {{ref('sche_dim_Business_Unit')}} DBU ON SQQP.BUSINESS_UNIT_CODE = DBU.BUSINESS_UNIT_CODE
	LEFT JOIN {{ref('sche_dim_Unit_Of_Measure')}} DUOM ON SQQP.WEIGHT_UOM_CODE = DUOM.SRC_UOM_CODE
	LEFT JOIN {{ref('sche_dim_Unit_Of_Measure')}} DUOM1 ON SQQP.LENGTH_UOM_CODE = DUOM1.SRC_UOM_CODE
	LEFT JOIN {{ref('sche_dim_Unit_Of_Measure')}} DUOM2 ON SQQP.AREA_UOM_CODE = DUOM2.SRC_UOM_CODE
	LEFT JOIN {{ref('sche_dim_Unit_Of_Measure')}} DUOM3 ON SQQP.QUANTITY_UOM_CODE = DUOM3.SRC_UOM_CODE
	LEFT JOIN {{ref('sche_dim_Currency')}} DCU ON SQQP.PRICE_CURRENCY_CODE = DCU.CURRENCY_CODE
	LEFT JOIN {{ref('sche_dim_Currency')}} DCU1 ON DCU1.CURRENCY_CODE = 'CAD'
	LEFT JOIN {{ref('sche_dim_Currency')}} DCU2 ON DCU2.CURRENCY_CODE = 'USD'
	LEFT JOIN {{ref('sche_dim_Exchange_Rate_Type')}} DERT ON DERT.EXCHANGE_RATE_TYPE_CODE = 'FiscalPeriodEndAvg'