{{
  config(
    full_refresh = true,
    materialized="dynamic_table",
    target_lag="downstream",
    snowflake_warehouse= var('task_warehouse'),
    alias = "fact_Project_Activity_Budget_Variation",
    schema= "facts",
    post_hook = "ALTER DYNAMIC TABLE {{ this }} SET LOG_LEVEL = ERROR"
  )
}}

WITH SS_PROJECT_ACTIVITY_BUDGET_VARIATION AS 
(
	SELECT 
		-- Original project activity : Fabrication, material and transport "New Project" from extra-credit table
		COD.RDM_FINANCIAL_COMPANY_CODE												AS FINANCIAL_COMPANY_CODE,
		PG.NO_PROJET,
		PG.OFFICE_CODE,
		PG.BRANCH_OFFICE_CODE,
		CAST(PXG.DATETIME_SAISIE AS DATE) 											AS DATE_SAISIE,
		PXG.REVISION_TYPE,
		PXG.APPROVAL_STATUS,
		BU.BUSINESS_UNIT_CODE,
		PXL.TYPE_PROJET,
		PXL.PST_QUOTED,
		CONCAT(PXL.ENTITY_CODE,'-',PXL.NO_PRODUIT)							AS PROJECT_ACTIVITY_CODE,
		'Production'																AS PROJECT_ACTIVITY_TYPE_CODE,
		QQ.JOB_NO,
		QQ.CONTRACT_CUSTOMER_UUID,
		C.CUST_NO,
		--QQP.ESTIMT_MODUL,
		--QQP.SEQ_NO,
		PS.TASK_NUMBER,
		CASE WHEN PXL.TMPS_STD_E_1 IS NULL THEN 'N/A' ELSE 'MIN' END				AS DIRECT_TIME_BUDGET_VARIATION_UOM_CODE,
		CASE WHEN PXL.TMPS_STD_EI_1 IS NULL THEN 'N/A' ELSE 'MIN' END				AS INDIRECT_TIME_BUDGET_VARIATION_UOM_CODE,
		CASE 
			WHEN PS.NO_PRODUIT IN (7000,7010) 
				OR PA.ATTRIBUTE_CODE = 'FREIGHT' 
				THEN 'N/A' 
			WHEN (PS.TYPE_PROD = 7 AND PS.GIRTS_PRODC = FALSE) 
				OR (UPPER(TRIM(PS.UOM_BUDGET_ENTRY_TYPE))='SURFACE')
				THEN CASE WHEN PXL.SURFACE IS NULL THEN 'N/A' ELSE 'SF' END
			ELSE 'N/A'
		END																			AS AREA_BUDGET_VARIATION_UOM_CODE,
		CASE WHEN PS.STATS_UNITES = TRUE THEN 
			CASE WHEN PXL.NBR_POUTR IS NULL THEN 'N/A' ELSE 'UN' END
		ELSE 'N/A' END																AS QUANTITY_BUDGET_VARIATION_UOM_CODE,
		CASE 
			WHEN PS.NO_PRODUIT IN (7000,7010) OR PA.ATTRIBUTE_CODE = 'FREIGHT' 
				THEN 'N/A' 
			ELSE CASE WHEN PXL.QTE_BUDGETE IS NULL THEN 'N/A' ELSE 'LB' END														
		END																			AS WEIGHT_BUDGET_VARIATION_UOM_CODE,
		CASE WHEN PG.EXCHGN_RATE IN (0,1) THEN 'CAD' ELSE 'USD' END		 			AS PRICE_AND_COST_BUDGET_VARIATION_CURRENCY_CODE,
		IFNULL(PXL.TMPS_STD_E_1*60,0)												AS DIRECT_TIME_BUDGET_VARIATION,
		IFNULL(PXL.TMPS_STD_EI_1*60,0)												AS INDIRECT_TIME_BUDGET_VARIATION,
		CASE 
			WHEN PS.NO_PRODUIT IN (7000,7010) 
				OR PA.ATTRIBUTE_CODE = 'FREIGHT' 
				THEN 0 
			WHEN (PS.TYPE_PROD = 7 AND PS.GIRTS_PRODC = FALSE) 
				OR (UPPER(TRIM(PS.UOM_BUDGET_ENTRY_TYPE))='SURFACE')
				THEN IFNULL(PXL.SURFACE,0)
			ELSE 0
		END																			AS AREA_BUDGET_VARIATION,
		CASE WHEN PS.STATS_UNITES = TRUE THEN IFNULL(PXL.NBR_POUTR,0) ELSE 0 END	AS QUANTITY_BUDGET_VARIATION,
		CASE 
			WHEN PS.NO_PRODUIT IN (7000,7010) OR PA.ATTRIBUTE_CODE = 'FREIGHT' 
				THEN 0 
			ELSE IFNULL(PXL.QTE_BUDGETE,0)														
		END																			AS WEIGHT_BUDGET_VARIATION,
		IFNULL(PXL.DSG_COST_1,0)													AS MATERIAL_COST_BUDGET_VARIATION_AMOUNT,
		IFNULL(PXL.DSG_COST_2,0)													AS FABRICATION_COST_BUDGET_VARIATION_AMOUNT,
		0																			AS LABOR_COST_BUDGET_VARIATION_AMOUNT,
		IFNULL(PXL.NET_SALE,0)														AS SOLD_PRICE_BUDGET_VARIATION
	FROM {{ref('norm_projetx_l')}} PXL
		LEFT JOIN {{ref('norm_projetx_g')}} PXG ON PXL.NO_ESTIME = PXG.NO_ESTIME AND PXL.SEQ_NO = PXG.SEQ_NO
		LEFT JOIN {{ref('norm_projet_g')}} PG ON PXG.NO_PROJET = PG.NO_PROJET
		LEFT JOIN {{ref('norm_projet_e')}} PE ON PXG.NO_PROJET = PE.NO_PROJET
		LEFT JOIN {{ref('norm_project')}} P ON PG.GDM_PROJECT_ID = P.PROJECT_ID
		LEFT JOIN {{ref('norm_business_unit')}} BU ON P.BUSINESS_UNIT_ID = BU.BUSINESS_UNIT_ID
		INNER JOIN {{ref('norm_produit_s')}} PS ON PXL.ENTITY_CODE = PS.ENTITY_CODE AND PXL.NO_PRODUIT = PS.NO_PRODUIT
		LEFT JOIN {{ref('norm_product_attribute')}} PA ON PXL.ENTITY_CODE = PA.ENTITY_CODE AND PXL.NO_PRODUIT = PA.NO_PRODUIT AND PA.ATTRIBUTE_CODE = 'FREIGHT'
		LEFT JOIN {{ref('norm_qc_quotation')}} QQ ON PG.JOB_NO = QQ.JOB_NO
		--LEFT JOIN {{ref('norm_qc_quotation_product')}} QQP ON QQ.JOB_NO = QQP.JOB_NO AND PXL.ENTITY_CODE = TRIM(QQP.SPM_ENTITY_CODE) AND PXL.NO_PRODUIT = CAST(QQP.SPM_PRODCT_NO AS NVARCHAR(20))
		LEFT JOIN {{ref('norm_customer')}} C ON PG.CUST_NO = C.CUST_NO
		CROSS JOIN {{ref('norm_cmg_outbound_databases')}} COD
	WHERE PXG.SEQ_NO <> 0
		AND PXG.GENERATION = TRUE
		AND YEAR(PE.D_OUVERTURE) >= 2008
		AND PG.CMG_TRANSFER =  TRUE 
		AND PG.CUST_NO <> '*N'
	UNION ALL
	
	SELECT 
		COD.RDM_FINANCIAL_COMPANY_CODE											AS FINANCIAL_COMPANY_CODE,
		PG.NO_PROJET,
		PG.OFFICE_CODE,
		PG.BRANCH_OFFICE_CODE,
		CAST(PXG.DATETIME_SAISIE AS DATE) 										AS DATE_SAISIE,
		PXG.REVISION_TYPE,
		PXG.APPROVAL_STATUS,
		BU.BUSINESS_UNIT_CODE,
		NULL AS TYPE_PROJET,
		NULL AS PST_QUOTED,	
		CONCAT(ETX.ENTITY_CODE,'-',ETX.LINE_NO)							AS PROJECT_ACTIVITY_CODE,
		'Services'																AS PROJECT_ACTIVITY_TYPE_CODE,
		QQ.JOB_NO,
		QQ.CONTRACT_CUSTOMER_UUID,
		C.CUST_NO,
		--NULL 																	AS ESTIMT_MODUL,
		--NULL 																	AS SEQ_NO,
		EL.DW_TASK 																AS TASK_NUMBER,
		'N/A'																	AS DIRECT_TIME_BUDGET_VARIATION_UOM_CODE,
		'N/A'																	AS INDIRECT_TIME_BUDGET_VARIATION_UOM_CODE,
		CASE WHEN ETX.AREA IS NULL THEN 'N/A' ELSE 'SF' END						AS AREA_BUDGET_VARIATION_UOM_CODE,
		CASE WHEN ETX.QUANTITY IS NULL THEN 'N/A' ELSE 'HR' END					AS QUANTITY_BUDGET_VARIATION_UOM_CODE,
		CASE WHEN ETX.WEIGHT IS NULL THEN 'N/A' ELSE 'LB' END					AS WEIGHT_BUDGET_VARIATION_UOM_CODE,
		CASE WHEN PG.EXCHGN_RATE IN (0,1) THEN 'CAD' ELSE 'USD' END		 		AS PRICE_AND_COST_BUDGET_VARIATION_CURRENCY_CODE,
		0																		AS DIRECT_TIME_BUDGET_VARIATION,
		0																		AS INDIRECT_TIME_BUDGET_VARIATION,
		IFNULL(ETX.AREA,0)														AS AREA_BUDGET_VARIATION,
		IFNULL(ETX.QUANTITY,0)													AS QUANTITY_BUDGET_VARIATION,
		IFNULL(ETX.WEIGHT,0)													AS WEIGHT_BUDGET_VARIATION,
		0																		AS MATERIAL_COST_BUDGET_VARIATION_AMOUNT,
		0																		AS FABRICATION_COST_BUDGET_VARIATION_AMOUNT,
		IFNULL(ETX.MNT_DEPENSE,0)												AS LABOR_COST_BUDGET_VARIATION_AMOUNT,
		IFNULL(ETX.MNT_REVENU,0)												AS SOLD_PRICE_BUDGET_VARIATION
	FROM {{ref('norm_ess_tranx')}} ETX
		LEFT JOIN {{ref('norm_projet_e')}} PE ON ETX.NO_PROJET = PE.NO_PROJET
		LEFT JOIN {{ref('norm_projet_g')}} PG ON ETX.NO_PROJET = PG.NO_PROJET
		LEFT JOIN {{ref('norm_projetx_g')}} PXG ON ETX.NO_PROJET = PXG.NO_PROJET AND ETX.SEQ_NO = PXG.SEQ_NO
		LEFT JOIN {{ref('norm_project')}} P ON PG.GDM_PROJECT_ID = P.PROJECT_ID
		LEFT JOIN {{ref('norm_business_unit')}} BU ON P.BUSINESS_UNIT_ID = BU.BUSINESS_UNIT_ID
		LEFT JOIN {{ref('norm_qc_quotation')}} QQ ON PG.JOB_NO = QQ.JOB_NO
		LEFT JOIN {{ref('norm_ess_line')}} EL ON ETX.ENTITY_CODE = EL.ENTITY_CODE AND ETX.LINE_NO = EL.LINE_NO
		LEFT JOIN {{ref('norm_customer')}} C ON PG.CUST_NO = C.CUST_NO
		CROSS JOIN {{ref('norm_cmg_outbound_databases')}} COD
	WHERE PXG.SEQ_NO <> 0
		AND PXG.GENERATION = TRUE
		AND YEAR(PE.D_OUVERTURE) >= 2008
		AND PG.CMG_TRANSFER =  TRUE
		AND PG.CUST_NO <> '*N'
)

SELECT 
	DPA.PROJECT_ACTIVITY_SK					 		AS PROJECT_ACTIVITY_SK,								-- PRIMARY FOREIGN KEY
	DP.PROJECT_SK									AS PROJECT_SK,										-- PRIMARY FOREIGN KEY
	DD.DATE_KEY										AS BUDGET_VARIATION_DATE_KEY,						-- FOREIGN KEY
	DSC.SALES_CONTRACT_SK							AS SALES_CONTRACT_SK,								-- FOREIGN KEY
	--DSCL.SALES_CONTRACT_LINE_SK 					AS SALES_CONTRACT_LINE_SK,							-- FOREIGN KEY
	DC.CUSTOMER_SK 									AS SOLD_TO_CUSTOMER_SK,								-- FOREIGN KEY
	DI.ITEM_SK										AS ITEM_SK,											-- FOREIGN KEY
	DSF.SALES_OFFICE_SK								AS SALES_OFFICE_SK,									-- FOREIGN KEY
	DSBF.SALES_BRANCH_OFFICE_SK						AS SALES_BRANCH_OFFICE_SK,							-- FOREIGN KEY
	DFC.FINANCIAL_COMPANY_SK						AS FINANCIAL_COMPANY_SK,							-- FOREIGN KEY
	DBU.BUSINESS_UNIT_SK							AS BUSINESS_UNIT_SK,								-- FOREIGN KEY
	DUOM1.UOM_SK									AS DIRECT_TIME_BUDGET_VARIATION_UOM_SK,				-- FOREIGN KEY
	DUOM2.UOM_SK									AS INDIRECT_TIME_BUDGET_VARIATION_UOM_SK,			-- FOREIGN KEY
	DUOM3.UOM_SK									AS AREA_BUDGET_VARIATION_UOM_SK,					-- FOREIGN KEY
	DUOM4.UOM_SK									AS QUANTITY_BUDGET_VARIATION_UOM_SK,				-- FOREIGN KEY
	DUOM5.UOM_SK									AS WEIGHT_BUDGET_VARIATION_UOM_SK,					-- FOREIGN KEY
	DCU.CURRENCY_SK						 			AS PRICE_AND_COST_BUDGET_VARIATION_CURRENCY_SK,		-- FOREIGN KEY
	DCU1.CURRENCY_SK								AS TO_CURRENCY_CAD_SK,								-- FOREIGN KEY
	DCU2.CURRENCY_SK								AS TO_CURRENCY_USD_SK,								-- FOREIGN KEY
	DERT.EXCHANGE_RATE_TYPE_SK 						AS FISCAL_PERIOD_END_AVG_EXCHANGE_RATE_TYPE_SK,
	SPABV.REVISION_TYPE								AS BUDGET_VARIATION_TYPE_CODE,
	SPABV.APPROVAL_STATUS							AS BUDGET_VARIATION_STATUS_CODE,
	SPABV.DIRECT_TIME_BUDGET_VARIATION				AS DIRECT_TIME_BUDGET_VARIATION,
	SPABV.INDIRECT_TIME_BUDGET_VARIATION			AS INDIRECT_TIME_BUDGET_VARIATION,
	SPABV.AREA_BUDGET_VARIATION						AS AREA_BUDGET_VARIATION,
	SPABV.QUANTITY_BUDGET_VARIATION					AS QUANTITY_BUDGET_VARIATION,
	SPABV.WEIGHT_BUDGET_VARIATION					AS WEIGHT_BUDGET_VARIATION,
	SPABV.MATERIAL_COST_BUDGET_VARIATION_AMOUNT		AS MATERIAL_COST_BUDGET_VARIATION_AMOUNT,
	SPABV.FABRICATION_COST_BUDGET_VARIATION_AMOUNT	AS FABRICATION_COST_BUDGET_VARIATION_AMOUNT,
	SPABV.LABOR_COST_BUDGET_VARIATION_AMOUNT		AS LABOR_COST_BUDGET_VARIATION_AMOUNT,
	SPABV.SOLD_PRICE_BUDGET_VARIATION				AS SOLD_PRICE_BUDGET_VARIATION
FROM SS_PROJECT_ACTIVITY_BUDGET_VARIATION SPABV
	LEFT JOIN {{ref('sche_dim_Project_Activity')}} DPA ON SPABV.PROJECT_ACTIVITY_CODE = DPA.PROJECT_ACTIVITY_CODE AND SPABV.PROJECT_ACTIVITY_TYPE_CODE = DPA.PROJECT_ACTIVITY_TYPE_CODE
	LEFT JOIN {{ref('sche_dim_Project')}} DP ON SPABV.NO_PROJET = DP.PROJECT_CODE AND SPABV.FINANCIAL_COMPANY_CODE = DP.FINANCIAL_COMPANY_CODE
	LEFT JOIN {{ref('sche_dim_Date')}} DD ON SPABV.DATE_SAISIE = DD.FULL_DATE
	LEFT JOIN {{ref('sche_dim_Sales_Contract')}} DSC ON SPABV.JOB_NO = DSC.SALES_CONTRACT_CODE 
		AND SPABV.OFFICE_CODE = DSC.SRC_OFFICE_CODE AND UPPER(DSC.ORIGIN_APPLICATION_CODE) = 'SPM'
	--LEFT JOIN {{ref('sche_dim_Sales_Contract_Line')}} DSCL ON SPABV.JOB_NO = DSCL.SALES_CONTRACT_CODE
		--AND SPABV.OFFICE_CODE = DSCL.SRC_OFFICE_CODE AND CONCAT(SPABV.ESTIMT_MODUL,SPABV.SEQ_NO) = DSCL.SALES_CONTRACT_LINE_CODE AND UPPER(DSCL.ORIGIN_APPLICATION_CODE) = 'SPM'
	LEFT JOIN {{ref('sche_dim_Customer')}} DC ON SPABV.CUST_NO = DC.CUSTOMER_CODE
	LEFT JOIN {{ref('sche_dim_Item')}} DI ON SPABV.TASK_NUMBER = DI.ITEM_CODE
	LEFT JOIN {{ref('sche_dim_Sales_Office')}} DSF ON SPABV.OFFICE_CODE = DSF.ORIGIN_OFFICE_CODE
	LEFT JOIN {{ref('sche_dim_Sales_Branch_Office')}} DSBF ON SPABV.OFFICE_CODE = DSBF.ORIGIN_OFFICE_CODE AND SPABV.BRANCH_OFFICE_CODE = DSBF.SALES_BRANCH_OFFICE_DEPARTMENT_CODE
	LEFT JOIN {{ref('sche_dim_Financial_Company')}} DFC ON SPABV.FINANCIAL_COMPANY_CODE = DFC.FINANCIAL_COMPANY_CODE
	LEFT JOIN {{ref('sche_dim_Business_Unit')}} DBU ON SPABV.BUSINESS_UNIT_CODE = DBU.BUSINESS_UNIT_CODE
	LEFT JOIN {{ref('sche_dim_Unit_Of_Measure')}} DUOM1 ON SPABV.DIRECT_TIME_BUDGET_VARIATION_UOM_CODE = DUOM1.ORIGIN_UOM_CODE
	LEFT JOIN {{ref('sche_dim_Unit_Of_Measure')}} DUOM2 ON SPABV.INDIRECT_TIME_BUDGET_VARIATION_UOM_CODE = DUOM2.ORIGIN_UOM_CODE
	LEFT JOIN {{ref('sche_dim_Unit_Of_Measure')}} DUOM3 ON SPABV.AREA_BUDGET_VARIATION_UOM_CODE = DUOM3.ORIGIN_UOM_CODE
	LEFT JOIN {{ref('sche_dim_Unit_Of_Measure')}} DUOM4 ON SPABV.QUANTITY_BUDGET_VARIATION_UOM_CODE = DUOM4.ORIGIN_UOM_CODE
	LEFT JOIN {{ref('sche_dim_Unit_Of_Measure')}} DUOM5 ON SPABV.WEIGHT_BUDGET_VARIATION_UOM_CODE = DUOM5.ORIGIN_UOM_CODE
	LEFT JOIN {{ref('sche_dim_Currency')}} DCU ON SPABV.PRICE_AND_COST_BUDGET_VARIATION_CURRENCY_CODE = DCU.CURRENCY_CODE
	LEFT JOIN {{ref('sche_dim_Currency')}}  DCU1 ON DCU1.CURRENCY_CODE = 'CAD'
	LEFT JOIN {{ref('sche_dim_Currency')}}  DCU2 ON DCU2.CURRENCY_CODE = 'USD'
	LEFT JOIN {{ref('sche_dim_Exchange_Rate_Type')}} DERT ON DERT.EXCHANGE_RATE_TYPE_CODE = 'FiscalPeriodEndAvg'
UNION ALL
-- Modification for Erection Taxes Sales amount (Source : EIS.OracleETL "PKG_TRANSFORM")
SELECT 
	DPA.PROJECT_ACTIVITY_SK					 		AS PROJECT_ACTIVITY_SK,								-- PRIMARY FOREIGN KEY
	DP.PROJECT_SK									AS PROJECT_SK,										-- PRIMARY FOREIGN KEY
	DD.DATE_KEY										AS BUDGET_VARIATION_DATE_KEY,						-- FOREIGN KEY
	DSC.SALES_CONTRACT_SK							AS SALES_CONTRACT_SK,								-- FOREIGN KEY
	--DSCL.SALES_CONTRACT_LINE_SK 					AS SALES_CONTRACT_LINE_SK,							-- FOREIGN KEY
	DC.CUSTOMER_SK 									AS SOLD_TO_CUSTOMER_SK,								-- FOREIGN KEY
	DI.ITEM_SK										AS ITEM_SK,											-- FOREIGN KEY
	DSF.SALES_OFFICE_SK								AS SALES_OFFICE_SK,									-- FOREIGN KEY
	DSBF.SALES_BRANCH_OFFICE_SK						AS SALES_BRANCH_OFFICE_SK,							-- FOREIGN KEY
	DFC.FINANCIAL_COMPANY_SK						AS FINANCIAL_COMPANY_SK,							-- FOREIGN KEY
	DBU.BUSINESS_UNIT_SK							AS BUSINESS_UNIT_SK,								-- FOREIGN KEY
	'N/A'											AS DIRECT_TIME_BUDGET_VARIATION_UOM_SK,				-- FOREIGN KEY
	'N/A'											AS INDIRECT_TIME_BUDGET_VARIATION_UOM_SK,			-- FOREIGN KEY
	'N/A'											AS AREA_BUDGET_VARIATION_UOM_SK,					-- FOREIGN KEY
	'N/A'											AS QUANTITY_BUDGET_VARIATION_UOM_SK,				-- FOREIGN KEY
	'N/A'											AS WEIGHT_BUDGET_VARIATION_UOM_SK,					-- FOREIGN KEY
	DCU.CURRENCY_SK						 			AS PRICE_AND_COST_BUDGET_VARIATION_CURRENCY_SK,		-- FOREIGN KEY
	DCU1.CURRENCY_SK								AS TO_CURRENCY_CAD_SK,								-- FOREIGN KEY
	DCU2.CURRENCY_SK								AS TO_CURRENCY_USD_SK,								-- FOREIGN KEY
	DERT.EXCHANGE_RATE_TYPE_SK 						AS FISCAL_PERIOD_END_AVG_EXCHANGE_RATE_TYPE_SK,
	SPABV.REVISION_TYPE								AS BUDGET_VARIATION_TYPE_CODE,
	SPABV.APPROVAL_STATUS							AS BUDGET_VARIATION_STATUS_CODE,
	0												AS DIRECT_TIME_BUDGET_VARIATION,
	0												AS INDIRECT_TIME_BUDGET_VARIATION,
	0												AS AREA_BUDGET_VARIATION,
	0												AS QUANTITY_BUDGET_VARIATION,
	0												AS WEIGHT_BUDGET_VARIATION,
	0												AS MATERIAL_COST_BUDGET_VARIATION_AMOUNT,
	0												AS FABRICATION_COST_BUDGET_VARIATION_AMOUNT,
	0												AS LABOR_COST_BUDGET_VARIATION_AMOUNT,
	SPABV.PST_QUOTED								AS SOLD_PRICE_BUDGET_VARIATION
FROM SS_PROJECT_ACTIVITY_BUDGET_VARIATION SPABV
	LEFT JOIN {{ref('sche_dim_Project_Activity')}} DPA ON SPABV.PROJECT_ACTIVITY_CODE = DPA.PROJECT_ACTIVITY_CODE AND SPABV.PROJECT_ACTIVITY_TYPE_CODE = DPA.PROJECT_ACTIVITY_TYPE_CODE
	LEFT JOIN {{ref('sche_dim_Project')}} DP ON SPABV.NO_PROJET = DP.PROJECT_CODE AND SPABV.FINANCIAL_COMPANY_CODE = DP.FINANCIAL_COMPANY_CODE
	LEFT JOIN {{ref('sche_dim_Date')}} DD ON SPABV.DATE_SAISIE = DD.FULL_DATE 
	LEFT JOIN {{ref('sche_dim_Sales_Contract')}} DSC ON SPABV.JOB_NO = DSC.SALES_CONTRACT_CODE 
		AND SPABV.OFFICE_CODE = DSC.SRC_OFFICE_CODE AND UPPER(DSC.ORIGIN_APPLICATION_CODE) = 'SPM'
	--LEFT JOIN {{ref('sche_dim_Sales_Contract_Line')}} DSCL ON SPABV.JOB_NO = DSCL.SALES_CONTRACT_CODE
	--	AND SPABV.OFFICE_CODE = DSCL.SRC_OFFICE_CODE AND CONCAT(SPABV.ESTIMT_MODUL,SPABV.SEQ_NO) = DSCL.SALES_CONTRACT_LINE_CODE AND UPPER(DSCL.ORIGIN_APPLICATION_CODE) = 'SPM'
	LEFT JOIN {{ref('sche_dim_Customer')}} DC ON SPABV.CUST_NO = DC.CUSTOMER_CODE
	LEFT JOIN {{ref('sche_dim_Item')}} DI ON '400' = DI.ITEM_CODE -- TAX ON ERECTED PROJ.
	LEFT JOIN {{ref('sche_dim_Sales_Office')}} DSF ON SPABV.OFFICE_CODE = DSF.ORIGIN_OFFICE_CODE
	LEFT JOIN {{ref('sche_dim_Sales_Branch_Office')}} DSBF ON SPABV.OFFICE_CODE = DSBF.ORIGIN_OFFICE_CODE AND SPABV.BRANCH_OFFICE_CODE = DSBF.SALES_BRANCH_OFFICE_DEPARTMENT_CODE
	LEFT JOIN {{ref('sche_dim_Financial_Company')}} DFC ON SPABV.FINANCIAL_COMPANY_CODE = DFC.FINANCIAL_COMPANY_CODE
	LEFT JOIN {{ref('sche_dim_Business_Unit')}} DBU ON SPABV.BUSINESS_UNIT_CODE = DBU.BUSINESS_UNIT_CODE
	LEFT JOIN {{ref('sche_dim_Currency')}} DCU ON SPABV.PRICE_AND_COST_BUDGET_VARIATION_CURRENCY_CODE = DCU.CURRENCY_CODE
	LEFT JOIN {{ref('sche_dim_Currency')}} DCU1 ON DCU1.CURRENCY_CODE = 'CAD'
	LEFT JOIN {{ref('sche_dim_Currency')}} DCU2 ON DCU2.CURRENCY_CODE = 'USD'
	LEFT JOIN {{ref('sche_dim_Exchange_Rate_Type')}} DERT ON DERT.EXCHANGE_RATE_TYPE_CODE = 'FiscalPeriodEndAvg'
WHERE SPABV.TYPE_PROJET = FALSE-- Same as dsa_salestrx.type_projet = 'Erected'
	AND SPABV.PST_QUOTED <> 0 -- Same as dsa_salestrx.erection_taxes <> 0