{{
  config(
    full_refresh = true,
    materialized="dynamic_table",
    target_lag="downstream",
    snowflake_warehouse= var('task_warehouse'),
    alias = "fact_exchange_rate",
    schema= "facts"
  )
}}

WITH SS_GL_TRANSLATION_RATES AS (
	SELECT
		GTR.RDM_TO_CURRENCY_CODE AS TO_CURRENCY_CODE, -- RDM - CURRENCY
		GTR.EOP_RATE,
		GTR.AVG_RATE,
		GP.START_DATE AS FISCAL_PERIOD_VALID_FROM_DATETIME,
		IFNULL(DATEADD(SECOND,-1,
			LEAD(GP.START_DATE) OVER(PARTITION BY GTR.TO_CURRENCY_CODE ORDER BY GP.START_DATE)), '9999-12-31 23:59:59') AS FISCAL_PERIOD_VALID_TO_DATETIME_EXTENDED,
		CASE
			WHEN DAY(GP.START_DATE) >= 16
	        	THEN DATEADD(MONTH, 1, DATE_TRUNC(MONTH, GP.START_DATE))
	        ELSE DATE_TRUNC(MONTH, GP.START_DATE)
	    END	AS CALENDAR_MONTH_VALID_FROM_DATETIME,
		IFNULL(DATEADD(SECOND,-1,
			LEAD(CALENDAR_MONTH_VALID_FROM_DATETIME) OVER(
				PARTITION BY GTR.TO_CURRENCY_CODE
				ORDER BY CALENDAR_MONTH_VALID_FROM_DATETIME)),'9999-12-31 23:59:59') AS CALENDAR_MONTH_VALID_TO_DATETIME_EXTENDED
	FROM {{ref('norm_gl_translation_rates')}} GTR
		LEFT JOIN {{ref('norm_gl_periods')}} GP ON GTR.PERIOD_NAME = GP.PERIOD_NAME
	WHERE GTR.SET_OF_BOOKS_ID = 1

	UNION ALL

	SELECT DISTINCT
		'CAD',	-- BASED ON RDM - CURRENCY
		1,
		1,
		GP.START_DATE AS FISCAL_PERIOD_VALID_FROM_DATETIME,
		IFNULL(DATEADD(SECOND,-1,
			LEAD(GP.START_DATE) OVER(
				PARTITION BY GTR.TO_CURRENCY_CODE
				ORDER BY GP.START_DATE)),'9999-12-31 23:59:59') AS FISCAL_PERIOD_VALID_TO_DATETIME_EXTENDED,
		CASE
			WHEN DAY(GP.START_DATE) >= 16 
	        	THEN DATEADD(MONTH, 1, DATE_TRUNC(MONTH, GP.START_DATE))
	        ELSE DATE_TRUNC(MONTH, GP.START_DATE)
	    END AS CALENDAR_MONTH_VALID_FROM_DATETIME,
		IFNULL(DATEADD(SECOND,-1,
			LEAD(CALENDAR_MONTH_VALID_FROM_DATETIME) OVER(
				PARTITION BY GTR.TO_CURRENCY_CODE 
				ORDER BY CALENDAR_MONTH_VALID_FROM_DATETIME)),'9999-12-31 23:59:59') AS CALENDAR_MONTH_VALID_TO_DATETIME_EXTENDED
	FROM {{ref('norm_gl_translation_rates')}} GTR
		LEFT JOIN {{ref('norm_gl_periods')}} GP ON GTR.PERIOD_NAME = GP.PERIOD_NAME
	WHERE GTR.SET_OF_BOOKS_ID = 1 AND GTR.TO_CURRENCY_CODE = 'USD'
), 

SS_PROJECT AS (
	SELECT
		PG.NO_PROJET,
		COD.RDM_FINANCIAL_COMPANY_CODE AS FINANCIAL_COMPANY_CODE, -- RDM - FINANCIAL COMPANY
		P.PROJECT_CURRENCY_CODE AS TO_CURRENCY_CODE, -- RDM - CURRENCY
		P.EXCHGN_RATE AS EXCHANGE_RATE
	FROM {{ref('norm_project')}} P
		INNER JOIN {{ref('norm_projet_g')}} PG ON P.PROJECT_ID = PG.GDM_PROJECT_ID
		CROSS JOIN {{ref('norm_cmg_outbound_databases')}} COD
	WHERE P.PROJECT_CURRENCY_CODE <> 'Not Found'
	UNION
	SELECT 
		PG.NO_PROJET,
		COD.RDM_FINANCIAL_COMPANY_CODE AS FINANCIAL_COMPANY_CODE, -- RDM - FINANCIAL COMPANY
		CASE WHEN P.EXCHGN_RATE = 1 THEN P.PROJECT_CURRENCY_CODE
			WHEN P.PROJECT_CURRENCY_CODE = 'CAD' THEN 'USD'
			WHEN P.PROJECT_CURRENCY_CODE = 'USD' THEN 'CAD'
			ELSE 'N/A' END AS TO_CURRENCY_CODE,	-- BASED ON RDM - CURRENCY
		CASE
			WHEN P.EXCHGN_RATE = 0 THEN 0 
			ELSE 1/P.EXCHGN_RATE 
		END AS EXCHANGE_RATE
	FROM {{ref('norm_project')}} P
		INNER JOIN {{ref('norm_projet_g')}} PG ON P.PROJECT_ID = PG.GDM_PROJECT_ID
		CROSS JOIN {{ref('norm_cmg_outbound_databases')}} COD
	WHERE P.PROJECT_CURRENCY_CODE <> 'Not Found'
)

-- First section : Refers to the average month end rate
SELECT 
	DD.DATE_KEY AS EXCHANGE_RATE_DATE_KEY, -- FOREIGN KEY
	NULL AS PROJECT_SK, -- FOREIGN KEY
	DC_FROM.CURRENCY_SK AS FROM_CURRENCY_SK, -- FOREIGN KEY
	DC_TO.CURRENCY_SK AS TO_CURRENCY_SK, -- FOREIGN KEY
	DERT.EXCHANGE_RATE_TYPE_SK	AS EXCHANGE_RATE_TYPE_SK, -- BASED ON RDM - EXCHANGE RATE TYPE
	CAST(SGTR1.AVG_RATE/SGTR.AVG_RATE AS NUMBER(15,6)) AS EXCHANGE_RATE
FROM {{ref('sche_dim_Date')}} DD
	LEFT JOIN SS_GL_TRANSLATION_RATES SGTR ON DD.FULL_DATE BETWEEN SGTR.CALENDAR_MONTH_VALID_FROM_DATETIME AND SGTR.CALENDAR_MONTH_VALID_TO_DATETIME_EXTENDED
	LEFT JOIN SS_GL_TRANSLATION_RATES SGTR1 ON SGTR.CALENDAR_MONTH_VALID_FROM_DATETIME = SGTR1.CALENDAR_MONTH_VALID_FROM_DATETIME
	LEFT JOIN {{ref('sche_dim_Currency')}} DC_FROM ON SGTR.TO_CURRENCY_CODE = DC_FROM.CURRENCY_CODE
	LEFT JOIN {{ref('sche_dim_Currency')}} DC_TO ON SGTR1.TO_CURRENCY_CODE = DC_TO.CURRENCY_CODE
	LEFT JOIN {{ref('sche_dim_Exchange_Rate_Type')}} DERT ON DERT.EXCHANGE_RATE_TYPE_CODE = 'FiscalPeriodEndAvg'
-- Apply last exchange rate to current and next year
WHERE DD.FULL_DATE <= DATEADD(DAY,-1,DATE_TRUNC(YEAR,DATEADD(YEAR, 2, CURRENT_DATE())))
UNION ALL
-- Second section : Refers to the average fiscal period end rate
SELECT 
	DD.DATE_KEY AS EXCHANGE_RATE_DATE_KEY, -- FOREIGN KEY
	NULL AS PROJECT_SK, -- FOREIGN KEY
	DC_FROM.CURRENCY_SK AS FROM_CURRENCY_SK, -- FOREIGN KEY
	DC_TO.CURRENCY_SK AS TO_CURRENCY_SK, -- FOREIGN KEY
	DERT.EXCHANGE_RATE_TYPE_SK AS EXCHANGE_RATE_TYPE_SK, -- BASED ON RDM - EXCHANGE RATE TYPE
	CAST(SGTR1.EOP_RATE/SGTR.EOP_RATE AS NUMBER(15,6)) AS EXCHANGE_RATE
FROM {{ref('sche_dim_Date')}} DD
	LEFT JOIN SS_GL_TRANSLATION_RATES SGTR ON DD.FULL_DATE BETWEEN SGTR.CALENDAR_MONTH_VALID_FROM_DATETIME AND SGTR.CALENDAR_MONTH_VALID_TO_DATETIME_EXTENDED
	LEFT JOIN SS_GL_TRANSLATION_RATES SGTR1 ON SGTR.CALENDAR_MONTH_VALID_FROM_DATETIME = SGTR1.CALENDAR_MONTH_VALID_FROM_DATETIME
	LEFT JOIN {{ref('sche_dim_Currency')}} DC_FROM ON SGTR.TO_CURRENCY_CODE = DC_FROM.CURRENCY_CODE
	LEFT JOIN {{ref('sche_dim_Currency')}} DC_TO ON SGTR1.TO_CURRENCY_CODE = DC_TO.CURRENCY_CODE
	LEFT JOIN {{ref('sche_dim_Exchange_Rate_Type')}} DERT ON DERT.EXCHANGE_RATE_TYPE_CODE = 'FiscalPeriodEnd'
-- Apply last exchange rate to current and next year
WHERE DD.FULL_DATE <= DATEADD(DAY,-1,DATE_TRUNC(YEAR,DATEADD(YEAR, 2, CURRENT_DATE())))
UNION ALL
-- Third section : Refers to the projet rate
SELECT 
	NULL AS EXCHANGE_RATE_DATE_KEY, -- FOREIGN KEY
	DP.PROJECT_SK AS PROJECT_SK, -- FOREIGN KEY
	DC_FROM.CURRENCY_SK AS FROM_CURRENCY_SK, -- FOREIGN KEY
	DC_TO.CURRENCY_SK AS TO_CURRENCY_SK, -- FOREIGN KEY
	DERT.EXCHANGE_RATE_TYPE_SK AS EXCHANGE_RATE_TYPE_SK, -- BASED ON RDM - EXCHANGE RATE TYPE
	CAST(CASE 
		WHEN SP.EXCHANGE_RATE = 0 THEN 0
		ELSE SP1.EXCHANGE_RATE/SP.EXCHANGE_RATE
	END AS NUMBER(15,6)) AS EXCHANGE_RATE
FROM SS_PROJECT SP
	LEFT JOIN SS_PROJECT SP1 ON SP.NO_PROJET = SP1.NO_PROJET
	LEFT JOIN {{ref('sche_dim_Project')}} DP ON SP.NO_PROJET = DP.PROJECT_CODE AND SP.FINANCIAL_COMPANY_CODE = DP.FINANCIAL_COMPANY_CODE
	LEFT JOIN {{ref('sche_dim_Currency')}} DC_FROM ON SP.TO_CURRENCY_CODE = DC_FROM.CURRENCY_CODE
	LEFT JOIN {{ref('sche_dim_Currency')}} DC_TO ON SP1.TO_CURRENCY_CODE = DC_TO.CURRENCY_CODE
	LEFT JOIN {{ref('sche_dim_Exchange_Rate_Type')}} DERT ON DERT.EXCHANGE_RATE_TYPE_CODE = 'Project'