{{
  config(
    materialized = "view",
    alias = "entity_d",
    schema='spm_gen'
  )
}}
SELECT 
  NULLIF(UPPER(TRIM(ENTITY_CODE::string)),'') AS ENTITY_CODE
, NULLIF(UPPER(TRIM(NOM_ABREGE::string)),'') AS NOM_ABREGE
-- 100% null
--, MESSAGE_GEN_1::string AS MESSAGE_GEN_1
--, MESSAGE_GEN_2::string AS MESSAGE_GEN_2
--, MESSAGE_GEN_3::string AS MESSAGE_GEN_3
--, MESSAGE_GEN_4::string AS MESSAGE_GEN_4
--, MESSAGE_GEN_5::string AS MESSAGE_GEN_5
--, MESSAGE_GEN_6::string AS MESSAGE_GEN_6
--, MESSAGE_GEN_7::string AS MESSAGE_GEN_7
--, MESSAGE_GEN_8::string AS MESSAGE_GEN_8
--, MESSAGE_GEN_9::string AS MESSAGE_GEN_9
--, MESSAGE_GEN_10::string AS MESSAGE_GEN_10
--, MESSAGE_GEN_11::string AS MESSAGE_GEN_11
--, MESSAGE_GEN_12::string AS MESSAGE_GEN_12
--, MESSAGE_GEN_13::string AS MESSAGE_GEN_13
-- 100% '0'
--, NO_BANQUE::string AS NO_BANQUE
, NULLIF(UPPER(TRIM(NO_ENR_NP::string)),'') AS NO_ENR_NP
, NULLIF(UPPER(TRIM(NO_ENR_P::string)),'') AS NO_ENR_P
, NULLIF(UPPER(TRIM(NO_ENR_PROV::string)),'') AS NO_ENR_PROV
, TO_BOOLEAN(FLAG_ASS_1::string) AS FLAG_ASS_1
, TO_BOOLEAN(FLAG_ASS_2::string) AS FLAG_ASS_2
, TO_BOOLEAN(FLAG_ASS_3::string) AS FLAG_ASS_3
, TO_BOOLEAN(FLAG_ASS_4::string) AS FLAG_ASS_4
, TO_BOOLEAN(FLAG_ASS_5::string) AS FLAG_ASS_5
, TO_BOOLEAN(FLAG_ASS_6::string) AS FLAG_ASS_6
, TO_BOOLEAN(FLAG_ASS_7::string) AS FLAG_ASS_7
, TO_BOOLEAN(FLAG_ASS_8::string) AS FLAG_ASS_8
, TO_BOOLEAN(FLAG_ASS_9::string) AS FLAG_ASS_9
, TO_BOOLEAN(FLAG_ASS_10::string) AS FLAG_ASS_10
, TO_BOOLEAN(FLAG_ASS_11::string) AS FLAG_ASS_11
, TO_BOOLEAN(FLAG_ASS_12::string) AS FLAG_ASS_12
, TO_BOOLEAN(FLAG_ASS_13::string) AS FLAG_ASS_13
, TO_BOOLEAN(FLAG_ASS_14::string) AS FLAG_ASS_14
, TO_BOOLEAN(FLAG_ASS_15::string) AS FLAG_ASS_15
, TO_BOOLEAN(FLAG_ASS_16::string) AS FLAG_ASS_16
, TO_BOOLEAN(FLAG_ASS_17::string) AS FLAG_ASS_17
, TO_BOOLEAN(FLAG_ASS_18::string) AS FLAG_ASS_18
, TO_BOOLEAN(FLAG_ASS_19::string) AS FLAG_ASS_19
, TO_BOOLEAN(FLAG_ASS_20::string) AS FLAG_ASS_20
, TO_BOOLEAN(FLAG_ASS_21::string) AS FLAG_ASS_21
, TO_BOOLEAN(FLAG_ASS_22::string) AS FLAG_ASS_22
, TO_BOOLEAN(FLAG_ASS_23::string) AS FLAG_ASS_23
, TO_BOOLEAN(FLAG_ASS_24::string) AS FLAG_ASS_24
, NULLIF(TRIM(ENTITY_ASS::STRING),'')::INTEGER AS ENTITY_ASS
, RRQ_SHARE::double AS RRQ_SHARE
, ASGR_SHARE::double AS ASGR_SHARE
, CNT_SHARE::double AS CNT_SHARE
, TO_BOOLEAN(CANSIS_SYST::string) AS CANSIS_SYST
, RAMQ_SHARE::double AS RAMQ_SHARE
, OHIP_SHARE::double AS OHIP_SHARE
, CSST_SHARED_1::double AS CSST_SHARED_1
, CSST_SHARED_2::double AS CSST_SHARED_2
, CSST_SHARED_3::double AS CSST_SHARED_3
, CSST_SHARED_4::double AS CSST_SHARED_4
, CSST_SHARED_5::double AS CSST_SHARED_5
, CSST_SHARED_6::double AS CSST_SHARED_6
, CSST_SHARED_7::double AS CSST_SHARED_7
, CSST_SHARED_8::double AS CSST_SHARED_8
, TAUX_VAC_H::double AS TAUX_VAC_H
, TAUX_VAC_S::double AS TAUX_VAC_S
, AHC_SHARE::double AS AHC_SHARE
, ASS_GR_SHARE::double AS ASS_GR_SHARE
, TO_BOOLEAN(MESURE::string) AS MESURE
, WCB_SHARE_ON_1::double AS WCB_SHARE_ON_1
, WCB_SHARE_ON_2::double AS WCB_SHARE_ON_2
, WCB_SHARE_ON_3::double AS WCB_SHARE_ON_3
, WCB_SHARE_AB_1::double AS WCB_SHARE_AB_1
, WCB_SHARE_AB_2::double AS WCB_SHARE_AB_2
, WCB_SHARE_AB_3::double AS WCB_SHARE_AB_3
, WCB_SHARE_CB_1::double AS WCB_SHARE_CB_1
, WCB_SHARE_CB_2::double AS WCB_SHARE_CB_2
, WCB_SHARE_CB_3::double AS WCB_SHARE_CB_3
, WCB_SHARE_NB_1::double AS WCB_SHARE_NB_1
, WCB_SHARE_NB_2::double AS WCB_SHARE_NB_2
, WCB_SHARE_NB_3::double AS WCB_SHARE_NB_3
, TO_BOOLEAN(POUR_VAC::string) AS POUR_VAC
, TAUX_VAC_H1::double AS TAUX_VAC_H1
, TAUX_VAC_S1::double AS TAUX_VAC_S1
, NULLIF(UPPER(TRIM(GSP_ENTITY::string)),'') AS GSP_ENTITY
, NULLIF(UPPER(TRIM(WHS_CODE::string)),'') AS WHS_CODE
, RQAP_YEUR::double AS RQAP_YEUR
, NULLIF(UPPER(TRIM(BOLT_WHS_CODE::string)),'') AS BOLT_WHS_CODE
, NULLIF(TRIM(LANGUE::STRING),'')::INTEGER AS LANGUE
-- 100% '0'
--, HOLE_NUMBER_MAN::string AS HOLE_NUMBER_MAN
, NULLIF(TRIM(SLOGAN_NAME_ID::STRING),'')::INTEGER AS SLOGAN_NAME_ID
, NULLIF(UPPER(TRIM(STRUCTURAL_WAREHOUSE_CODE::string)),'') AS STRUCTURAL_WAREHOUSE_CODE
, NULLIF(UPPER(TRIM(ROLLBAR_WHS_CODE::string)),'') AS ROLLBAR_WHS_CODE
, TO_BOOLEAN(TVQ_TAXABLE::string) AS TVQ_TAXABLE
, NULLIF(UPPER(TRIM(DECK_WHS_CODE::string)),'') AS DECK_WHS_CODE
, NULLIF(TRIM(CANSIS_COMPANY::STRING),'')::INTEGER AS CANSIS_COMPANY
, NULLIF(TRIM(CANSIS_LOCATION::STRING),'')::INTEGER AS CANSIS_LOCATION
, NULLIF(UPPER(TRIM(CANSIS_ORGANIZATION::string)),'') AS CANSIS_ORGANIZATION
, NULLIF(UPPER(TRIM(CANSIS_PO_PREPARER::string)),'') AS CANSIS_PO_PREPARER
, NULLIF(UPPER(TRIM(SHORT_CODE::string)),'') AS SHORT_CODE
, NULLIF(TRIM(NATURL_LANGG::STRING),'')::INTEGER AS NATURL_LANGG
-- 100% '0'
--, CMG_CONV_PHASE::string AS CMG_CONV_PHASE
, TO_BOOLEAN(CMG_TRF_INVC::string) AS CMG_TRF_INVC
, TO_BOOLEAN(DESGO_VERSANT::string) AS DESGO_VERSANT
, NULLIF(UPPER(TRIM(OFFICE_CODE::string)),'') AS OFFICE_CODE
, TO_BOOLEAN(MEASURE_USED::string) AS MEASURE_USED
, TO_BOOLEAN(GIRTS_VERTICAL_MAN::string) AS GIRTS_VERTICAL_MAN
, NULLIF(UPPER(TRIM(SUB_ASSEMBLY_WHS_CODE::string)),'') AS SUB_ASSEMBLY_WHS_CODE
, TO_BOOLEAN(REQUISITION_DRAW_DECK_ACCESSORY::string) AS REQUISITION_DRAW_DECK_ACCESSORY
, TO_BOOLEAN(SHOP_DOCUMENTS_MEASURE::string) AS SHOP_DOCUMENTS_MEASURE
, TO_TIMESTAMP_NTZ(IPAAS_UPDATED_DATE) AS IPAAS_UPDATED_DATE
, SRC_SYSTEM_OPERATION AS SRC_SYSTEM_OPERATION
  from {{ref('prep_entity_d')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'