{{
  config(
    materialized = "view",
    alias = "users",
    schema='spm_gen'
  )
}}
SELECT 
USER_CODE::string AS USER_CODE -- I keep the blank as it is the key
,NULLIF(USER_NAME::string,'') AS USER_NAME
,INITCAP(NULLIF(SITE_ID::string,'')) AS SITE_ID
,NULLIF(TRIM(MEMO::string),'') AS MEMO
,TIMESTAMP_NTZ_FROM_PARTS(LAST_IN_DATE::DATE, NULLIF(LAST_IN_HRS::string, '')::TIME) AS LAST_IN_DATETIME
,TIMESTAMP_NTZ_FROM_PARTS(LAST_OUT_DATE::string, NULLIF(LAST_OUT_HRS::string, '')::TIME) AS LAST_OUT_DATETIME
,UPPER(LANG_CODE::string) AS LANG_CODE
,DIR_OUT_FILE::string AS DIR_OUT_FILE
,TO_BOOLEAN(INACTIVE::string) AS INACTIVE
,NULLIF(INACTIVE_USER_CODE::string,'') AS INACTIVE_USER_CODE
,INACTIVE_DATE::DATE AS INACTIVE_DATE
,TO_BOOLEAN(MOD_OUT_FILE::string) AS MOD_OUT_FILE
,WIN_MODE::INTEGER AS WIN_MODE
-- always false
--,TO_BOOLEAN(PWD_DELAY::string) AS PWD_DELAY
,PWD_LAST_CHANGE::DATE AS PWD_LAST_CHANGE
,PWD_EXPIRATION_DATE::DATE AS PWD_EXPIRATION_DATE
--,PWD_FROM_LOGIN_HRS::string AS PWD_FROM_LOGIN_HRS -- constant column
--,PWD_TO_LOGIN_HRS::string AS PWD_TO_LOGIN_HRS -- constant column
,TO_BOOLEAN(PWD_LOGIN_DAYS_1::string) AS PWD_LOGIN_DAYS_1
,TO_BOOLEAN(PWD_LOGIN_DAYS_2::string) AS PWD_LOGIN_DAYS_2
,TO_BOOLEAN(PWD_LOGIN_DAYS_3::string) AS PWD_LOGIN_DAYS_3
,TO_BOOLEAN(PWD_LOGIN_DAYS_4::string) AS PWD_LOGIN_DAYS_4
,TO_BOOLEAN(PWD_LOGIN_DAYS_5::string) AS PWD_LOGIN_DAYS_5
,TO_BOOLEAN(PWD_LOGIN_DAYS_6::string) AS PWD_LOGIN_DAYS_6
,TO_BOOLEAN(PWD_LOGIN_DAYS_7::string) AS PWD_LOGIN_DAYS_7
,PWD_INVALID::INTEGER AS PWD_INVALID
,ARRAY_REMOVE(SPLIT(NULLIF(TRIM(TTY_HISTORY_LIST::string),''),','),''::VARIANT)::ARRAY(INTEGER) AS TTY_HISTORY_LIST
,NULLIF(TRIM(PWD_HISTORY::string),'') AS PWD_HISTORY
,TO_BOOLEAN(PWD_BYPASS_MASK::string) AS PWD_BYPASS_MASK
,TO_BOOLEAN(PWD_BYPASS_INVALID::string) AS PWD_BYPASS_INVALID
,TO_BOOLEAN(PWD_BYPASS_HISTORY::string) AS PWD_BYPASS_HISTORY
,TO_BOOLEAN(PWD_CAN_CHANGE::string) AS PWD_CAN_CHANGE
,TO_BOOLEAN(USE_SYS_OUT_FILE::string) AS USE_SYS_OUT_FILE
,TO_BOOLEAN(USE_SYS_OUT_FILE_UNIX::string) AS USE_SYS_OUT_FILE_UNIX
--,WEB_MODULE_ID::string AS WEB_MODULE_ID -- empty column
,NULLIF(WIN_ENV_ID::string,'') AS WIN_ENV_ID
,WIN_GROUP::INTEGER AS WIN_GROUP
,NULLIF(WIN_GROUP_SUB::string,'') AS WIN_GROUP_SUB
,WIN_SPLIT::INTEGER AS WIN_SPLIT
,WIN_STATE::INTEGER AS WIN_STATE
,WIN_X::INTEGER AS WIN_X
,WIN_Y::INTEGER AS WIN_Y
,WIN_WIDTH::INTEGER AS WIN_WIDTH
,WIN_HEIGHT::INTEGER AS WIN_HEIGHT
,WIN_HISTORY::INTEGER AS WIN_HISTORY
,SPLIT(NULLIF(WIN_HISTORY_LIST::string,''),',')::ARRAY(INTEGER) AS WIN_HISTORY_LIST
,NULLIF(EMAIL::string, '') AS EMAIL
,NULLIF(TTY_ENV_ID::string,'') AS TTY_ENV_ID
,TTY_HISTORY::INTEGER AS TTY_HISTORY
,DIR_OUT_FILE_UNIX::string AS DIR_OUT_FILE_UNIX
,TO_BOOLEAN(MOD_OUT_FILE_UNIX::string) AS MOD_OUT_FILE_UNIX
,NULLIF(UPPER(TTY_PRINTER_ID::string),'') AS TTY_PRINTER_ID
,TTY_GROUP::INTEGER AS TTY_GROUP
,NULLIF(TTY_GROUP_SUB::string,'') AS TTY_GROUP_SUB
,WIN_SCHEDULED_REPORTS_FILTER::INTEGER AS WIN_SCHEDULED_REPORTS_FILTER
  from {{ref('prep_users')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'