{{
  config(
    materialized = "view",
    alias = "entity",
    schema='spm_gen'
  )
}}
SELECT 
  NULLIF(UPPER(TRIM(ENTITY_CODE::STRING)),'') AS ENTITY_CODE
, NULLIF(INITCAP(TRIM(NAME::STRING)),'') AS NAME
, NULLIF(INITCAP(TRIM(NAME_ADDRESS_1::STRING)),'') AS NAME_ADDRESS_1
, NULLIF(INITCAP(TRIM(NAME_ADDRESS_2::STRING)),'') AS NAME_ADDRESS_2
, NULLIF(INITCAP(TRIM(NAME_ADDRESS_3::STRING)),'') AS NAME_ADDRESS_3
, NULLIF(INITCAP(TRIM(NAME_ADDRESS_4::STRING)),'') AS NAME_ADDRESS_4
, NULLIF(INITCAP(TRIM(NAME_ADDRESS_5::STRING)),'') AS NAME_ADDRESS_5
, NULLIF(UPPER(TRIM(AR_ENTITY::STRING)),'') AS AR_ENTITY
, NULLIF(UPPER(TRIM(AP_ENTITY::STRING)),'') AS AP_ENTITY
, NULLIF(UPPER(TRIM(GL_ENTITY::STRING)),'') AS GL_ENTITY
, NULLIF(UPPER(TRIM(PY_ENTITY::STRING)),'') AS PY_ENTITY
, NULLIF(UPPER(TRIM(IN_ENTITY::STRING)),'') AS IN_ENTITY
, NULLIF(UPPER(TRIM(FA_ENTITY::STRING)),'') AS FA_ENTITY
, NULLIF(UPPER(TRIM(APPLICATION_1::STRING)),'') AS APPLICATION_1
, NULLIF(UPPER(TRIM(APPLICATION_2::STRING)),'') AS APPLICATION_2
, NULLIF(UPPER(TRIM(APPLICATION_3::STRING)),'') AS APPLICATION_3
, NULLIF(UPPER(TRIM(APPLICATION_4::STRING)),'') AS APPLICATION_4
, NULLIF(UPPER(TRIM(APPLICATION_5::STRING)),'') AS APPLICATION_5
, NULLIF(UPPER(TRIM(CONTROL_ENT_1::STRING)),'') AS CONTROL_ENT_1
, NULLIF(UPPER(TRIM(CONTROL_ENT_2::STRING)),'') AS CONTROL_ENT_2
, NULLIF(UPPER(TRIM(CONTROL_ENT_3::STRING)),'') AS CONTROL_ENT_3
, NULLIF(UPPER(TRIM(CONTROL_ENT_4::STRING)),'') AS CONTROL_ENT_4
, NULLIF(UPPER(TRIM(CONTROL_ENT_5::STRING)),'') AS CONTROL_ENT_5
, NULLIF(UPPER(TRIM(CP_ENTITY::STRING)),'') AS CP_ENTITY
, TO_TIMESTAMP_NTZ(IPAAS_UPDATED_DATE) AS IPAAS_UPDATED_DATE
, SRC_SYSTEM_OPERATION AS SRC_SYSTEM_OPERATION
  from {{ref('prep_entity')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'