{{ config(
    materialized='view',
    schema='PREPARE'
) }}

SELECT
    RAW_DATA:"CustomerKey"::NUMBER AS CUSTOMER_KEY,
    RAW_DATA:"GeographyKey"::NUMBER AS GEOGRAPHY_KEY,
    RAW_DATA:"CustomerAlternateKey"::VARCHAR AS CUSTOMER_ALTERNATE_KEY,
    RAW_DATA:"Title"::VARCHAR AS TITLE,
    RAW_DATA:"FirstName"::VARCHAR AS FIRST_NAME,
    RAW_DATA:"MiddleName"::VARCHAR AS MIDDLE_NAME,
    RAW_DATA:"LastName"::VARCHAR AS LAST_NAME,
    RAW_DATA:"NameStyle"::BOOLEAN AS NAME_STYLE,
    RAW_DATA:"BirthDate"::DATE AS BIRTH_DATE,
    RAW_DATA:"MaritalStatus"::VARCHAR AS MARITAL_STATUS,
    RAW_DATA:"Suffix"::VARCHAR AS SUFFIX,
    RAW_DATA:"Gender"::VARCHAR AS GENDER,
    RAW_DATA:"EmailAddress"::VARCHAR AS EMAIL_ADDRESS,
    RAW_DATA:"YearlyIncome"::NUMBER(19,4) AS YEARLY_INCOME,
    RAW_DATA:"TotalChildren"::NUMBER AS TOTAL_CHILDREN,
    RAW_DATA:"NumberChildrenAtHome"::NUMBER AS NUMBER_CHILDREN_AT_HOME,
    RAW_DATA:"EnglishEducation"::VARCHAR AS ENGLISH_EDUCATION,
    RAW_DATA:"SpanishEducation"::VARCHAR AS SPANISH_EDUCATION,
    RAW_DATA:"FrenchEducation"::VARCHAR AS FRENCH_EDUCATION,
    RAW_DATA:"EnglishOccupation"::VARCHAR AS ENGLISH_OCCUPATION,
    RAW_DATA:"SpanishOccupation"::VARCHAR AS SPANISH_OCCUPATION,
    RAW_DATA:"FrenchOccupation"::VARCHAR AS FRENCH_OCCUPATION,
    RAW_DATA:"HouseOwnerFlag"::BOOLEAN AS HOUSE_OWNER_FLAG,
    RAW_DATA:"NumberCarsOwned"::NUMBER AS NUMBER_CARS_OWNED,
    RAW_DATA:"AddressLine1"::VARCHAR AS ADDRESS_LINE_1,
    RAW_DATA:"AddressLine2"::VARCHAR AS ADDRESS_LINE_2,
    RAW_DATA:"Phone"::VARCHAR AS PHONE,
    RAW_DATA:"DateFirstPurchase"::DATE AS DATE_FIRST_PURCHASE,
    RAW_DATA:"CommuteDistance"::VARCHAR AS COMMUTE_DISTANCE,

    SOURCE_FILE,
    LOAD_TIMESTAMP

FROM {{ source('snowflake_landing', 'DIM_CUSTOMER') }}