{{ config(
    materialized='view',
    schema='PREPARE'
) }}

SELECT
    RAW_DATA:"ProductKey"::NUMBER AS PRODUCT_KEY,
    RAW_DATA:"ProductAlternateKey"::VARCHAR AS PRODUCT_ALTERNATE_KEY,
    RAW_DATA:"ProductSubcategoryKey"::NUMBER AS PRODUCT_SUBCATEGORY_KEY,
    RAW_DATA:"WeightUnitMeasureCode"::VARCHAR AS WEIGHT_UNIT_MEASURE_CODE,
    RAW_DATA:"SizeUnitMeasureCode"::VARCHAR AS SIZE_UNIT_MEASURE_CODE,
    RAW_DATA:"EnglishProductName"::VARCHAR AS ENGLISH_PRODUCT_NAME,
    RAW_DATA:"SpanishProductName"::VARCHAR AS SPANISH_PRODUCT_NAME,
    RAW_DATA:"FrenchProductName"::VARCHAR AS FRENCH_PRODUCT_NAME,
    RAW_DATA:"StandardCost"::NUMBER(19,4) AS STANDARD_COST,
    RAW_DATA:"FinishedGoodsFlag"::BOOLEAN AS FINISHED_GOODS_FLAG,
    RAW_DATA:"Color"::VARCHAR AS COLOR,
    RAW_DATA:"SafetyStockLevel"::NUMBER AS SAFETY_STOCK_LEVEL,
    RAW_DATA:"ReorderPoint"::NUMBER AS REORDER_POINT,
    RAW_DATA:"ListPrice"::NUMBER(19,4) AS LIST_PRICE,
    RAW_DATA:"Size"::VARCHAR AS SIZE,
    RAW_DATA:"SizeRange"::VARCHAR AS SIZE_RANGE,
    RAW_DATA:"Weight"::NUMBER(19,4) AS WEIGHT,
    RAW_DATA:"DaysToManufacture"::NUMBER AS DAYS_TO_MANUFACTURE,
    RAW_DATA:"ProductLine"::VARCHAR AS PRODUCT_LINE,
    RAW_DATA:"DealerPrice"::NUMBER(19,4) AS DEALER_PRICE,
    RAW_DATA:"Class"::VARCHAR AS CLASS,
    RAW_DATA:"Style"::VARCHAR AS STYLE,
    RAW_DATA:"ModelName"::VARCHAR AS MODEL_NAME,
    RAW_DATA:"EnglishDescription"::VARCHAR AS ENGLISH_DESCRIPTION,
    RAW_DATA:"FrenchDescription"::VARCHAR AS FRENCH_DESCRIPTION,
    RAW_DATA:"ChineseDescription"::VARCHAR AS CHINESE_DESCRIPTION,
    RAW_DATA:"ArabicDescription"::VARCHAR AS ARABIC_DESCRIPTION,
    RAW_DATA:"HebrewDescription"::VARCHAR AS HEBREW_DESCRIPTION,
    RAW_DATA:"ThaiDescription"::VARCHAR AS THAI_DESCRIPTION,
    RAW_DATA:"GermanDescription"::VARCHAR AS GERMAN_DESCRIPTION,
    RAW_DATA:"JapaneseDescription"::VARCHAR AS JAPANESE_DESCRIPTION,
    RAW_DATA:"TurkishDescription"::VARCHAR AS TURKISH_DESCRIPTION,
    RAW_DATA:"StartDate"::DATE AS START_DATE,
    RAW_DATA:"EndDate"::DATE AS END_DATE,
    RAW_DATA:"Status"::VARCHAR AS STATUS,

    SOURCE_FILE,
    LOAD_TIMESTAMP

FROM {{ source('snowflake_landing', 'DIM_PRODUCT') }}