{{ config(
    materialized='view',
    schema='PREPARE'
) }}

SELECT
    PRODUCTKEY AS PRODUCT_KEY,
    ORDERDATEKEY AS ORDER_DATE_KEY,
    DUEDATEKEY AS DUE_DATE_KEY,
    SHIPDATEKEY AS SHIP_DATE_KEY,
    CUSTOMERKEY AS CUSTOMER_KEY,
    PROMOTIONKEY AS PROMOTION_KEY,
    CURRENCYKEY AS CURRENCY_KEY,
    SALESTERRITORYKEY AS SALES_TERRITORY_KEY,

    SALESORDERNUMBER AS SALES_ORDER_NUMBER,
    SALESORDERLINENUMBER AS SALES_ORDER_LINE_NUMBER,
    REVISIONNUMBER AS REVISION_NUMBER,
    ORDERQUANTITY AS ORDER_QUANTITY,

    UNITPRICE AS UNIT_PRICE,
    EXTENDEDAMOUNT AS EXTENDED_AMOUNT,
    UNITPRICEDISCOUNTPCT AS UNIT_PRICE_DISCOUNT_PCT,
    DISCOUNTAMOUNT AS DISCOUNT_AMOUNT,
    PRODUCTSTANDARDCOST AS PRODUCT_STANDARD_COST,
    TOTALPRODUCTCOST AS TOTAL_PRODUCT_COST,
    SALESAMOUNT AS SALES_AMOUNT,
    TAXAMT AS TAX_AMT,
    FREIGHT,

    CARRIERTRACKINGNUMBER AS CARRIER_TRACKING_NUMBER,
    CUSTOMERPONUMBER AS CUSTOMER_PO_NUMBER,

    ORDERDATE AS ORDER_DATE,
    DUEDATE AS DUE_DATE,
    SHIPDATE AS SHIP_DATE

FROM {{ source('snowflake_landing', 'FACT_INTERNET_SALES') }}