{{
  config(
    materialized = "view",
    alias = "rdm",
    schema="REFERENCE_DATA"
  )
}}

SELECT
    A.BUSINESS_APPLICATION_CODE,
    A.BUSINESS_APPLICATION_DOMAIN_CODE,
    A.BUSINESS_APPLICATION_VALUE,
    A.STANDARD_APPLICATION_CODE,
    A.STANDARD_DOMAIN_APPLICATION_CODE,
    A.STANDARD_APPLICATION_VALUE,
    B.NAME AS STANDARD_APPLICATION_VALUE_NAME_FR,
    C.NAME AS STANDARD_APPLICATION_VALUE_NAME_EN
FROM {{ref('norm_standard_code_mapping')}} A
LEFT JOIN {{ref('norm_descriptions')}} B
    ON A.STANDARD_APPLICATION_CODE = B.APPLICATIONCODE
    AND A.STANDARD_DOMAIN_APPLICATION_CODE = B.DOMAINCODE
    AND A.STANDARD_APPLICATION_VALUE = B.VALUE
    AND B.LANGUAGE = 'FR'
LEFT JOIN {{ref('norm_descriptions')}} C
    ON A.STANDARD_APPLICATION_CODE = C.APPLICATIONCODE
    AND A.STANDARD_DOMAIN_APPLICATION_CODE = C.DOMAINCODE
    AND A.STANDARD_APPLICATION_VALUE = C.VALUE
    AND C.LANGUAGE = 'EN'