{{
  config(
    materialized = "view",
    alias = "wip_accounting_classes",
    schema='EBS'
  )
}}

SELECT 
 DATA:GLOBAL_ATTRIBUTE19 AS GLOBAL_ATTRIBUTE19
,DATA:GLOBAL_ATTRIBUTE18 AS GLOBAL_ATTRIBUTE18
,DATA:GLOBAL_ATTRIBUTE16 AS GLOBAL_ATTRIBUTE16
,DATA:GLOBAL_ATTRIBUTE15 AS GLOBAL_ATTRIBUTE15
,DATA:GLOBAL_ATTRIBUTE14 AS GLOBAL_ATTRIBUTE14
,DATA:GLOBAL_ATTRIBUTE13 AS GLOBAL_ATTRIBUTE13
,DATA:GLOBAL_ATTRIBUTE12 AS GLOBAL_ATTRIBUTE12
,DATA:GLOBAL_ATTRIBUTE11 AS GLOBAL_ATTRIBUTE11
,DATA:GLOBAL_ATTRIBUTE10 AS GLOBAL_ATTRIBUTE10
,DATA:GLOBAL_ATTRIBUTE8 AS GLOBAL_ATTRIBUTE8
,DATA:GLOBAL_ATTRIBUTE7 AS GLOBAL_ATTRIBUTE7
,DATA:GLOBAL_ATTRIBUTE6 AS GLOBAL_ATTRIBUTE6
,DATA:GLOBAL_ATTRIBUTE5 AS GLOBAL_ATTRIBUTE5
,DATA:GLOBAL_ATTRIBUTE4 AS GLOBAL_ATTRIBUTE4
,DATA:GLOBAL_ATTRIBUTE3 AS GLOBAL_ATTRIBUTE3
,DATA:GLOBAL_ATTRIBUTE2 AS GLOBAL_ATTRIBUTE2
,DATA:GLOBAL_ATTRIBUTE_CATEGORY AS GLOBAL_ATTRIBUTE_CATEGORY
,DATA:ATTRIBUTE15 AS ATTRIBUTE15
,DATA:ATTRIBUTE14 AS ATTRIBUTE14
,DATA:ATTRIBUTE13 AS ATTRIBUTE13
,DATA:ATTRIBUTE11 AS ATTRIBUTE11
,DATA:ATTRIBUTE10 AS ATTRIBUTE10
,DATA:ATTRIBUTE9 AS ATTRIBUTE9
,DATA:ATTRIBUTE8 AS ATTRIBUTE8
,DATA:ATTRIBUTE7 AS ATTRIBUTE7
,DATA:ATTRIBUTE6 AS ATTRIBUTE6
,DATA:ATTRIBUTE5 AS ATTRIBUTE5
,DATA:ATTRIBUTE4 AS ATTRIBUTE4
,DATA:ATTRIBUTE2 AS ATTRIBUTE2
,DATA:ATTRIBUTE1 AS ATTRIBUTE1
,DATA:ATTRIBUTE_CATEGORY AS ATTRIBUTE_CATEGORY
,DATA:STD_COST_ADJUSTMENT_ACCOUNT AS STD_COST_ADJUSTMENT_ACCOUNT
,DATA:OVERHEAD_VARIANCE_ACCOUNT AS OVERHEAD_VARIANCE_ACCOUNT
,DATA:OVERHEAD_ACCOUNT AS OVERHEAD_ACCOUNT
,DATA:OUTSIDE_PROC_VARIANCE_ACCOUNT AS OUTSIDE_PROC_VARIANCE_ACCOUNT
,DATA:OUTSIDE_PROCESSING_ACCOUNT AS OUTSIDE_PROCESSING_ACCOUNT
,DATA:RESOURCE_VARIANCE_ACCOUNT AS RESOURCE_VARIANCE_ACCOUNT
,DATA:RESOURCE_ACCOUNT AS RESOURCE_ACCOUNT
,DATA:MATERIAL_OVERHEAD_ACCOUNT AS MATERIAL_OVERHEAD_ACCOUNT
,DATA:MATERIAL_VARIANCE_ACCOUNT AS MATERIAL_VARIANCE_ACCOUNT
,DATA:MATERIAL_ACCOUNT AS MATERIAL_ACCOUNT
,DATA:DISABLE_DATE AS DISABLE_DATE
,DATA:DESCRIPTION AS DESCRIPTION
,DATA:CLASS_TYPE AS CLASS_TYPE
,DATA:LAST_UPDATE_LOGIN AS LAST_UPDATE_LOGIN
,DATA:CREATED_BY AS CREATED_BY
,DATA:CREATION_DATE AS CREATION_DATE
,DATA:LAST_UPDATED_BY AS LAST_UPDATED_BY
,DATA:LAST_UPDATE_DATE AS LAST_UPDATE_DATE
,DATA:ORGANIZATION_ID AS ORGANIZATION_ID
,DATA:CLASS_CODE AS CLASS_CODE
,DATA:COST_TYPE_ID AS COST_TYPE_ID
,DATA:COMPLETION_COST_SOURCE AS COMPLETION_COST_SOURCE
,DATA:GLOBAL_ATTRIBUTE20 AS GLOBAL_ATTRIBUTE20
,DATA:GLOBAL_ATTRIBUTE17 AS GLOBAL_ATTRIBUTE17
,DATA:GLOBAL_ATTRIBUTE1 AS GLOBAL_ATTRIBUTE1
,DATA:ATTRIBUTE3 AS ATTRIBUTE3
,DATA:GLOBAL_ATTRIBUTE9 AS GLOBAL_ATTRIBUTE9
,DATA:ATTRIBUTE12 AS ATTRIBUTE12
,DATA:EXPENSE_ACCOUNT AS EXPENSE_ACCOUNT
,DATA:SYSTEM_OPTION_ID AS SYSTEM_OPTION_ID
,DATA:BRIDGING_ACCOUNT AS BRIDGING_ACCOUNT
,DATA:EST_SCRAP_VAR_ACCOUNT AS EST_SCRAP_VAR_ACCOUNT
,DATA:EST_SCRAP_ACCOUNT AS EST_SCRAP_ACCOUNT
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM {{ source("landing_ebs", "WIP_ACCOUNTING_CLASSES") }}
-- to only take the files after the last fullLoad
  WHERE 
  split(FILENAME, '_')[array_size(split(FILENAME, '_')) - 2] >=
    (SELECT min_timestamp
  FROM
      (SELECT split(FILENAME, '_')[array_size(split(FILENAME, '_')) - 2] AS min_timestamp, split(FILENAME, '/')[3] AS type_file
      FROM {{ source("landing_ebs", "WIP_ACCOUNTING_CLASSES") }}
      WHERE type_file LIKE 'fullload%'
      QUALIFY ROW_NUMBER() OVER (ORDER BY min_timestamp DESC) = 1)
    )