
{{
  config(
    materialized = "view",
    alias = "cst_distribution",
    schema='ebs'
  )
}}

SELECT
DATA:TRANSACTION_ID AS TRANSACTION_ID
,DATA:ORGANIZATION_ID AS ORGANIZATION_ID
,DATA:WIP_ENTITY_ID AS WIP_ENTITY_ID
,DATA:WIP_ENTITY_NAME AS WIP_ENTITY_NAME
,DATA:PRIMARY_ITEM_ID AS PRIMARY_ITEM_ID
,DATA:LINE_ID AS LINE_ID
,DATA:LINE_CODE AS LINE_CODE
,DATA:ACCT_PERIOD_ID AS ACCT_PERIOD_ID
,DATA:TRANSACTION_TYPE_NAME AS TRANSACTION_TYPE_NAME
,DATA:TRANSACTION_DATE AS TRANSACTION_DATE
,DATA:TRANSACTION_QUANTITY AS TRANSACTION_QUANTITY
,DATA:TRANSACTION_UOM AS TRANSACTION_UOM
,DATA:PRIMARY_QUANTITY AS PRIMARY_QUANTITY
,DATA:PRIMARY_UOM AS PRIMARY_UOM
,DATA:OPERATION_SEQ_NUM AS OPERATION_SEQ_NUM
,DATA:CURRENCY_CODE AS CURRENCY_CODE
,DATA:CURRENCY_CONVERSION_DATE AS CURRENCY_CONVERSION_DATE
,DATA:CURRENCY_CONVERSION_TYPE AS CURRENCY_CONVERSION_TYPE
,DATA:CURRENCY_CONVERSION_RATE AS CURRENCY_CONVERSION_RATE
,DATA:DEPARTMENT_CODE AS DEPARTMENT_CODE
,DATA:DEPARTMENT_DESCRIPTION AS DEPARTMENT_DESCRIPTION
,DATA:REASON_NAME AS REASON_NAME
,DATA:REFERENCE AS REFERENCE
,DATA:INVENTORY_ITEM_ID AS INVENTORY_ITEM_ID
,DATA:REVISION AS REVISION
,DATA:SUBINVENTORY_CODE AS SUBINVENTORY_CODE
,DATA:RESOURCE_SEQ_NUM AS RESOURCE_SEQ_NUM
,DATA:REFERENCE_ACCOUNT AS REFERENCE_ACCOUNT
,DATA:RESOURCE_CODE AS RESOURCE_CODE
,DATA:REPETITIVE_SCHEDULE_ID AS REPETITIVE_SCHEDULE_ID
,DATA:LINE_TYPE_NAME AS LINE_TYPE_NAME
,DATA:TRANSACTION_VALUE AS TRANSACTION_VALUE
,DATA:BASE_TRANSACTION_VALUE AS BASE_TRANSACTION_VALUE
,DATA:CONTRA_SET_ID AS CONTRA_SET_ID
,DATA:BASIS AS BASIS
,DATA:COST_ELEMENT AS COST_ELEMENT
,DATA:ACTIVITY AS ACTIVITY
,DATA:RATE_OR_AMOUNT AS RATE_OR_AMOUNT
,DATA:GL_BATCH_ID AS GL_BATCH_ID
,DATA:OVERHEAD_BASIS_FACTOR AS OVERHEAD_BASIS_FACTOR
,DATA:BASIS_RESOURCE_ID AS BASIS_RESOURCE_ID
,DATA:TRANSACTION_SOURCE AS TRANSACTION_SOURCE
,DATA:UNIT_COST AS UNIT_COST
,DATA:ROW_ID AS ROW_ID
,DATA:LAST_UPDATE_DATE AS LAST_UPDATE_DATE
,DATA:LAST_UPDATED_BY AS LAST_UPDATED_BY
,DATA:CREATION_DATE AS CREATION_DATE
,DATA:CREATED_BY AS CREATED_BY
,DATA:LAST_UPDATE_LOGIN AS LAST_UPDATE_LOGIN
,DATA:REQUEST_ID AS REQUEST_ID
,DATA:PROGRAM_APPLICATION_ID AS PROGRAM_APPLICATION_ID
,DATA:PROGRAM_ID AS PROGRAM_ID
,DATA:PROGRAM_UPDATE_DATE AS PROGRAM_UPDATE_DATE
,DATA:ASSET_NUMBER AS ASSET_NUMBER
,DATA:ASSET_GROUP_ID AS ASSET_GROUP_ID
,DATA:REBUILD_ITEM_ID AS REBUILD_ITEM_ID
,DATA:REBUILD_SERIAL_NUMBER AS REBUILD_SERIAL_NUMBER
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM 
 {{ source("landing_ebs", "CST_DISTRIBUTION")}}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM 
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM 
                  {{ source("landing_ebs", "CST_DISTRIBUTION")}}
                    
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )