{{
  config(
    materialized = "view",
    alias = "hz_locations",
    schema='ebs'
  )
}}

SELECT DATA:"LOCATION_ID" AS LOCATION_ID
,DATA:"LAST_UPDATE_DATE" AS LAST_UPDATE_DATE
,DATA:"LAST_UPDATED_BY" AS LAST_UPDATED_BY
,DATA:"CREATION_DATE" AS CREATION_DATE
,DATA:"CREATED_BY" AS CREATED_BY
,DATA:"LAST_UPDATE_LOGIN" AS LAST_UPDATE_LOGIN
,DATA:"REQUEST_ID" AS REQUEST_ID
,DATA:"PROGRAM_APPLICATION_ID" AS PROGRAM_APPLICATION_ID
,DATA:"PROGRAM_ID" AS PROGRAM_ID
,DATA:"PROGRAM_UPDATE_DATE" AS PROGRAM_UPDATE_DATE
,DATA:"WH_UPDATE_DATE" AS WH_UPDATE_DATE
,DATA:"ATTRIBUTE_CATEGORY" AS ATTRIBUTE_CATEGORY
,DATA:"ATTRIBUTE1" AS ATTRIBUTE1
,DATA:"ATTRIBUTE2" AS ATTRIBUTE2
,DATA:"ATTRIBUTE3" AS ATTRIBUTE3
,DATA:"ATTRIBUTE4" AS ATTRIBUTE4
,DATA:"ATTRIBUTE5" AS ATTRIBUTE5
,DATA:"ATTRIBUTE6" AS ATTRIBUTE6
,DATA:"ATTRIBUTE7" AS ATTRIBUTE7
,DATA:"ATTRIBUTE8" AS ATTRIBUTE8
,DATA:"ATTRIBUTE9" AS ATTRIBUTE9
,DATA:"ATTRIBUTE10" AS ATTRIBUTE10
,DATA:"ATTRIBUTE11" AS ATTRIBUTE11
,DATA:"ATTRIBUTE12" AS ATTRIBUTE12
,DATA:"ATTRIBUTE13" AS ATTRIBUTE13
,DATA:"ATTRIBUTE14" AS ATTRIBUTE14
,DATA:"ATTRIBUTE15" AS ATTRIBUTE15
,DATA:"ATTRIBUTE16" AS ATTRIBUTE16
,DATA:"ATTRIBUTE17" AS ATTRIBUTE17
,DATA:"ATTRIBUTE18" AS ATTRIBUTE18
,DATA:"ATTRIBUTE19" AS ATTRIBUTE19
,DATA:"ATTRIBUTE20" AS ATTRIBUTE20
,DATA:"GLOBAL_ATTRIBUTE_CATEGORY" AS GLOBAL_ATTRIBUTE_CATEGORY
,DATA:"GLOBAL_ATTRIBUTE1" AS GLOBAL_ATTRIBUTE1
,DATA:"GLOBAL_ATTRIBUTE2" AS GLOBAL_ATTRIBUTE2
,DATA:"GLOBAL_ATTRIBUTE3" AS GLOBAL_ATTRIBUTE3
,DATA:"GLOBAL_ATTRIBUTE4" AS GLOBAL_ATTRIBUTE4
,DATA:"GLOBAL_ATTRIBUTE5" AS GLOBAL_ATTRIBUTE5
,DATA:"GLOBAL_ATTRIBUTE6" AS GLOBAL_ATTRIBUTE6
,DATA:"GLOBAL_ATTRIBUTE7" AS GLOBAL_ATTRIBUTE7
,DATA:"GLOBAL_ATTRIBUTE8" AS GLOBAL_ATTRIBUTE8
,DATA:"GLOBAL_ATTRIBUTE9" AS GLOBAL_ATTRIBUTE9
,DATA:"GLOBAL_ATTRIBUTE10" AS GLOBAL_ATTRIBUTE10
,DATA:"GLOBAL_ATTRIBUTE11" AS GLOBAL_ATTRIBUTE11
,DATA:"GLOBAL_ATTRIBUTE12" AS GLOBAL_ATTRIBUTE12
,DATA:"GLOBAL_ATTRIBUTE13" AS GLOBAL_ATTRIBUTE13
,DATA:"GLOBAL_ATTRIBUTE14" AS GLOBAL_ATTRIBUTE14
,DATA:"GLOBAL_ATTRIBUTE15" AS GLOBAL_ATTRIBUTE15
,DATA:"GLOBAL_ATTRIBUTE16" AS GLOBAL_ATTRIBUTE16
,DATA:"GLOBAL_ATTRIBUTE17" AS GLOBAL_ATTRIBUTE17
,DATA:"GLOBAL_ATTRIBUTE18" AS GLOBAL_ATTRIBUTE18
,DATA:"GLOBAL_ATTRIBUTE19" AS GLOBAL_ATTRIBUTE19
,DATA:"GLOBAL_ATTRIBUTE20" AS GLOBAL_ATTRIBUTE20
,DATA:"ORIG_SYSTEM_REFERENCE" AS ORIG_SYSTEM_REFERENCE
,DATA:"COUNTRY" AS COUNTRY
,DATA:"ADDRESS1" AS ADDRESS1
,DATA:"ADDRESS2" AS ADDRESS2
,DATA:"ADDRESS3" AS ADDRESS3
,DATA:"ADDRESS4" AS ADDRESS4
,DATA:"CITY" AS CITY
,DATA:"POSTAL_CODE" AS POSTAL_CODE
,DATA:"STATE" AS STATE
,DATA:"PROVINCE" AS PROVINCE
,DATA:"COUNTY" AS COUNTY
,DATA:"ADDRESS_KEY" AS ADDRESS_KEY
,DATA:"ADDRESS_STYLE" AS ADDRESS_STYLE
,DATA:"VALIDATED_FLAG" AS VALIDATED_FLAG
,DATA:"ADDRESS_LINES_PHONETIC" AS ADDRESS_LINES_PHONETIC
,DATA:"APARTMENT_FLAG" AS APARTMENT_FLAG
,DATA:"PO_BOX_NUMBER" AS PO_BOX_NUMBER
,DATA:"HOUSE_NUMBER" AS HOUSE_NUMBER
,DATA:"STREET_SUFFIX" AS STREET_SUFFIX
,DATA:"APARTMENT_NUMBER" AS APARTMENT_NUMBER
,DATA:"SECONDARY_SUFFIX_ELEMENT" AS SECONDARY_SUFFIX_ELEMENT
,DATA:"STREET" AS STREET
,DATA:"RURAL_ROUTE_TYPE" AS RURAL_ROUTE_TYPE
,DATA:"RURAL_ROUTE_NUMBER" AS RURAL_ROUTE_NUMBER
,DATA:"STREET_NUMBER" AS STREET_NUMBER
,DATA:"BUILDING" AS BUILDING
,DATA:"FLOOR" AS FLOOR
,DATA:"SUITE" AS SUITE
,DATA:"ROOM" AS ROOM
,DATA:"POSTAL_PLUS4_CODE" AS POSTAL_PLUS4_CODE
,DATA:"TIME_ZONE" AS TIME_ZONE
,DATA:"OVERSEAS_ADDRESS_FLAG" AS OVERSEAS_ADDRESS_FLAG
,DATA:"POST_OFFICE" AS POST_OFFICE
,DATA:"POSITION" AS POSITION
,DATA:"DELIVERY_POINT_CODE" AS DELIVERY_POINT_CODE
,DATA:"LOCATION_DIRECTIONS" AS LOCATION_DIRECTIONS
,DATA:"ADDRESS_EFFECTIVE_DATE" AS ADDRESS_EFFECTIVE_DATE
,DATA:"ADDRESS_EXPIRATION_DATE" AS ADDRESS_EXPIRATION_DATE
,DATA:"ADDRESS_ERROR_CODE" AS ADDRESS_ERROR_CODE
,DATA:"CLLI_CODE" AS CLLI_CODE
,DATA:"DODAAC" AS DODAAC
,DATA:"TRAILING_DIRECTORY_CODE" AS TRAILING_DIRECTORY_CODE
,DATA:"LANGUAGE" AS LANGUAGE
,DATA:"LIFE_CYCLE_STATUS" AS LIFE_CYCLE_STATUS
,DATA:"SHORT_DESCRIPTION" AS SHORT_DESCRIPTION
,DATA:"DESCRIPTION" AS DESCRIPTION
,DATA:"CONTENT_SOURCE_TYPE" AS CONTENT_SOURCE_TYPE
,DATA:"LOC_HIERARCHY_ID" AS LOC_HIERARCHY_ID
,DATA:"SALES_TAX_GEOCODE" AS SALES_TAX_GEOCODE
,DATA:"SALES_TAX_INSIDE_CITY_LIMITS" AS SALES_TAX_INSIDE_CITY_LIMITS
,DATA:"FA_LOCATION_ID" AS FA_LOCATION_ID
,DATA:"OBJECT_VERSION_NUMBER" AS OBJECT_VERSION_NUMBER
,DATA:"CREATED_BY_MODULE" AS CREATED_BY_MODULE
,DATA:"APPLICATION_ID" AS APPLICATION_ID
,DATA:"TIMEZONE_ID" AS TIMEZONE_ID
,DATA:"GEOMETRY_STATUS_CODE" AS GEOMETRY_STATUS_CODE
,DATA:"ACTUAL_CONTENT_SOURCE" AS ACTUAL_CONTENT_SOURCE
,DATA:"VALIDATION_STATUS_CODE" AS VALIDATION_STATUS_CODE
,DATA:"DATE_VALIDATED" AS DATE_VALIDATED
,DATA:"DO_NOT_VALIDATE_FLAG" AS DO_NOT_VALIDATE_FLAG
,DATA:"GEOMETRY" AS GEOMETRY
,FILENAME AS METADATA_FILENAME
,FILE_ROW_NUMBER AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME AS METADATA_START_SCAN_TIME
 FROM 
 {{ source("landing_ebs", "HZ_LOCATIONS")}}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM 
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM 
                  {{ source("landing_ebs", "HZ_LOCATIONS")}}
                    
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )
