{{
  config(
    materialized = "view",
    alias = "hz_customer_profiles",
    schema='ebs'
  )
}}

SELECT DATA:"PARTY_ID" AS PARTY_ID
,DATA:"LAST_CREDIT_REVIEW_DATE" AS LAST_CREDIT_REVIEW_DATE
,DATA:"REVIEW_CYCLE" AS REVIEW_CYCLE
,DATA:"CREDIT_CLASSIFICATION" AS CREDIT_CLASSIFICATION
,DATA:"GLOBAL_ATTRIBUTE11" AS GLOBAL_ATTRIBUTE11
,DATA:"GLOBAL_ATTRIBUTE10" AS GLOBAL_ATTRIBUTE10
,DATA:"GLOBAL_ATTRIBUTE9" AS GLOBAL_ATTRIBUTE9
,DATA:"GLOBAL_ATTRIBUTE8" AS GLOBAL_ATTRIBUTE8
,DATA:"GLOBAL_ATTRIBUTE7" AS GLOBAL_ATTRIBUTE7
,DATA:"GLOBAL_ATTRIBUTE6" AS GLOBAL_ATTRIBUTE6
,DATA:"GLOBAL_ATTRIBUTE5" AS GLOBAL_ATTRIBUTE5
,DATA:"GLOBAL_ATTRIBUTE4" AS GLOBAL_ATTRIBUTE4
,DATA:"GLOBAL_ATTRIBUTE3" AS GLOBAL_ATTRIBUTE3
,DATA:"GLOBAL_ATTRIBUTE2" AS GLOBAL_ATTRIBUTE2
,DATA:"GLOBAL_ATTRIBUTE1" AS GLOBAL_ATTRIBUTE1
,DATA:"JGZZ_ATTRIBUTE15" AS JGZZ_ATTRIBUTE15
,DATA:"JGZZ_ATTRIBUTE14" AS JGZZ_ATTRIBUTE14
,DATA:"JGZZ_ATTRIBUTE13" AS JGZZ_ATTRIBUTE13
,DATA:"JGZZ_ATTRIBUTE12" AS JGZZ_ATTRIBUTE12
,DATA:"JGZZ_ATTRIBUTE11" AS JGZZ_ATTRIBUTE11
,DATA:"JGZZ_ATTRIBUTE10" AS JGZZ_ATTRIBUTE10
,DATA:"JGZZ_ATTRIBUTE9" AS JGZZ_ATTRIBUTE9
,DATA:"JGZZ_ATTRIBUTE8" AS JGZZ_ATTRIBUTE8
,DATA:"JGZZ_ATTRIBUTE7" AS JGZZ_ATTRIBUTE7
,DATA:"JGZZ_ATTRIBUTE6" AS JGZZ_ATTRIBUTE6
,DATA:"JGZZ_ATTRIBUTE5" AS JGZZ_ATTRIBUTE5
,DATA:"JGZZ_ATTRIBUTE4" AS JGZZ_ATTRIBUTE4
,DATA:"JGZZ_ATTRIBUTE3" AS JGZZ_ATTRIBUTE3
,DATA:"JGZZ_ATTRIBUTE2" AS JGZZ_ATTRIBUTE2
,DATA:"JGZZ_ATTRIBUTE1" AS JGZZ_ATTRIBUTE1
,DATA:"JGZZ_ATTRIBUTE_CATEGORY" AS JGZZ_ATTRIBUTE_CATEGORY
,DATA:"CLEARING_DAYS" AS CLEARING_DAYS
,DATA:"GROUPING_RULE_ID" AS GROUPING_RULE_ID
,DATA:"CHARGE_ON_FINANCE_CHARGE_FLAG" AS CHARGE_ON_FINANCE_CHARGE_FLAG
,DATA:"TAX_PRINTING_OPTION" AS TAX_PRINTING_OPTION
,DATA:"AUTO_REC_INCL_DISPUTED_FLAG" AS AUTO_REC_INCL_DISPUTED_FLAG
,DATA:"ATTRIBUTE15" AS ATTRIBUTE15
,DATA:"ATTRIBUTE14" AS ATTRIBUTE14
,DATA:"ATTRIBUTE13" AS ATTRIBUTE13
,DATA:"ATTRIBUTE12" AS ATTRIBUTE12
,DATA:"ATTRIBUTE11" AS ATTRIBUTE11
,DATA:"WH_UPDATE_DATE" AS WH_UPDATE_DATE
,DATA:"REQUEST_ID" AS REQUEST_ID
,DATA:"PROGRAM_UPDATE_DATE" AS PROGRAM_UPDATE_DATE
,DATA:"PROGRAM_ID" AS PROGRAM_ID
,DATA:"PROGRAM_APPLICATION_ID" AS PROGRAM_APPLICATION_ID
,DATA:"ATTRIBUTE10" AS ATTRIBUTE10
,DATA:"ATTRIBUTE9" AS ATTRIBUTE9
,DATA:"ATTRIBUTE8" AS ATTRIBUTE8
,DATA:"ATTRIBUTE7" AS ATTRIBUTE7
,DATA:"ATTRIBUTE6" AS ATTRIBUTE6
,DATA:"ATTRIBUTE5" AS ATTRIBUTE5
,DATA:"ATTRIBUTE4" AS ATTRIBUTE4
,DATA:"ATTRIBUTE3" AS ATTRIBUTE3
,DATA:"ATTRIBUTE2" AS ATTRIBUTE2
,DATA:"ATTRIBUTE1" AS ATTRIBUTE1
,DATA:"ATTRIBUTE_CATEGORY" AS ATTRIBUTE_CATEGORY
,DATA:"AUTOCASH_HIERARCHY_ID" AS AUTOCASH_HIERARCHY_ID
,DATA:"PERCENT_COLLECTABLE" AS PERCENT_COLLECTABLE
,DATA:"ACCOUNT_STATUS" AS ACCOUNT_STATUS
,DATA:"STATEMENT_CYCLE_ID" AS STATEMENT_CYCLE_ID
,DATA:"DISCOUNT_GRACE_DAYS" AS DISCOUNT_GRACE_DAYS
,DATA:"PAYMENT_GRACE_DAYS" AS PAYMENT_GRACE_DAYS
,DATA:"INTEREST_PERIOD_DAYS" AS INTEREST_PERIOD_DAYS
,DATA:"DUNNING_LETTER_SET_ID" AS DUNNING_LETTER_SET_ID
,DATA:"OVERRIDE_TERMS" AS OVERRIDE_TERMS
,DATA:"STANDARD_TERMS" AS STANDARD_TERMS
,DATA:"RISK_CODE" AS RISK_CODE
,DATA:"CREDIT_RATING" AS CREDIT_RATING
,DATA:"SITE_USE_ID" AS SITE_USE_ID
,DATA:"PROFILE_CLASS_ID" AS PROFILE_CLASS_ID
,DATA:"CREDIT_HOLD" AS CREDIT_HOLD
,DATA:"CREDIT_BALANCE_STATEMENTS" AS CREDIT_BALANCE_STATEMENTS
,DATA:"SEND_STATEMENTS" AS SEND_STATEMENTS
,DATA:"PREF_FUNCTIONAL_CURRENCY" AS PREF_FUNCTIONAL_CURRENCY
,DATA:"INTEREST_CHARGES" AS INTEREST_CHARGES
,DATA:"DUNNING_LETTERS" AS DUNNING_LETTERS
,DATA:"DISCOUNT_TERMS" AS DISCOUNT_TERMS
,DATA:"TOLERANCE" AS TOLERANCE
,DATA:"NEXT_CREDIT_REVIEW_DATE" AS NEXT_CREDIT_REVIEW_DATE
,DATA:"CREDIT_CHECKING" AS CREDIT_CHECKING
,DATA:"CREDIT_ANALYST_ID" AS CREDIT_ANALYST_ID
,DATA:"COLLECTOR_ID" AS COLLECTOR_ID
,DATA:"STATUS" AS STATUS
,DATA:"CUST_ACCOUNT_ID" AS CUST_ACCOUNT_ID
,DATA:"CREATION_DATE" AS CREATION_DATE
,DATA:"CREATED_BY" AS CREATED_BY
,DATA:"LAST_UPDATE_LOGIN" AS LAST_UPDATE_LOGIN
,DATA:"LAST_UPDATE_DATE" AS LAST_UPDATE_DATE
,DATA:"LAST_UPDATED_BY" AS LAST_UPDATED_BY
,DATA:"CUST_ACCOUNT_PROFILE_ID" AS CUST_ACCOUNT_PROFILE_ID
,DATA:"LOCKBOX_MATCHING_OPTION" AS LOCKBOX_MATCHING_OPTION
,DATA:"AUTOCASH_HIERARCHY_ID_FOR_ADR" AS AUTOCASH_HIERARCHY_ID_FOR_ADR
,DATA:"CONS_INV_TYPE" AS CONS_INV_TYPE
,DATA:"CONS_INV_FLAG" AS CONS_INV_FLAG
,DATA:"GLOBAL_ATTRIBUTE_CATEGORY" AS GLOBAL_ATTRIBUTE_CATEGORY
,DATA:"GLOBAL_ATTRIBUTE20" AS GLOBAL_ATTRIBUTE20
,DATA:"GLOBAL_ATTRIBUTE19" AS GLOBAL_ATTRIBUTE19
,DATA:"GLOBAL_ATTRIBUTE18" AS GLOBAL_ATTRIBUTE18
,DATA:"GLOBAL_ATTRIBUTE17" AS GLOBAL_ATTRIBUTE17
,DATA:"GLOBAL_ATTRIBUTE16" AS GLOBAL_ATTRIBUTE16
,DATA:"GLOBAL_ATTRIBUTE15" AS GLOBAL_ATTRIBUTE15
,DATA:"GLOBAL_ATTRIBUTE14" AS GLOBAL_ATTRIBUTE14
,DATA:"GLOBAL_ATTRIBUTE13" AS GLOBAL_ATTRIBUTE13
,DATA:"GLOBAL_ATTRIBUTE12" AS GLOBAL_ATTRIBUTE12
,DATA:"APPLICATION_ID" AS APPLICATION_ID
,DATA:"CREATED_BY_MODULE" AS CREATED_BY_MODULE
,DATA:"OBJECT_VERSION_NUMBER" AS OBJECT_VERSION_NUMBER
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
 FROM 
 {{ source("landing_ebs", "HZ_CUSTOMER_PROFILES")}}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM 
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM 
                  {{ source("landing_ebs", "HZ_CUSTOMER_PROFILES")}}
                    
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )