{{
  config(
    materialized = "view",
    alias = "per_org_structure_elements_v",
    schema='EBS'
  )
}}

SELECT 
DATA:"LAST_UPDATE_DATE" AS LAST_UPDATE_DATE
,DATA:"PROGRAM_UPDATE_DATE" AS PROGRAM_UPDATE_DATE
,DATA:"PROGRAM_ID" AS PROGRAM_ID
,DATA:"PROGRAM_APPLICATION_ID" AS PROGRAM_APPLICATION_ID
,DATA:"REQUEST_ID" AS REQUEST_ID
,DATA:"D_CHILD_NAME" AS D_CHILD_NAME
,DATA:"ORGANIZATION_ID_CHILD" AS ORGANIZATION_ID_CHILD
,DATA:"ORG_STRUCTURE_VERSION_ID" AS ORG_STRUCTURE_VERSION_ID
,DATA:"D_PARENT_NAME" AS D_PARENT_NAME
,DATA:"ORGANIZATION_ID_PARENT" AS ORGANIZATION_ID_PARENT
,DATA:"BUSINESS_GROUP_ID" AS BUSINESS_GROUP_ID
,DATA:"ORG_STRUCTURE_ELEMENT_ID" AS ORG_STRUCTURE_ELEMENT_ID
,DATA:"ROW_ID" AS ROW_ID
,DATA:"POSITION_CONTROL_ENABLED_FLAG" AS POSITION_CONTROL_ENABLED_FLAG
,DATA:"CREATION_DATE" AS CREATION_DATE
,DATA:"CREATED_BY" AS CREATED_BY
,DATA:"LAST_UPDATE_LOGIN" AS LAST_UPDATE_LOGIN
,DATA:"LAST_UPDATED_BY" AS LAST_UPDATED_BY
,DATA:"src_system_operation" AS SRC_SYSTEM_OPERATION
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM {{ source("landing_ebs", "PER_ORG_STRUCTURE_ELEMENTS_V") }}
-- to only take the files after the last fullLoad
  WHERE 
  split(FILENAME, '_')[array_size(split(FILENAME, '_')) - 2] >=
    (SELECT min_timestamp
  FROM
      (SELECT split(FILENAME, '_')[array_size(split(FILENAME, '_')) - 2] AS min_timestamp, split(FILENAME, '/')[3] AS type_file
      FROM {{ source("landing_ebs", "PER_ORG_STRUCTURE_ELEMENTS_V") }}
      WHERE type_file LIKE 'fullload%'
      QUALIFY ROW_NUMBER() OVER (ORDER BY min_timestamp DESC) = 1)
    )