{{
  config(
    materialized = "view",
    alias = "hz_cust_site_uses_all",
    schema='ebs'
  )
}}

SELECT 
DATA:"SITE_USE_ID" AS SITE_USE_ID
,DATA:"CUST_ACCT_SITE_ID" AS CUST_ACCT_SITE_ID
,DATA:"LAST_UPDATE_DATE" AS LAST_UPDATE_DATE
,DATA:"LAST_UPDATED_BY" AS LAST_UPDATED_BY
,DATA:"CREATION_DATE" AS CREATION_DATE
,DATA:"CREATED_BY" AS CREATED_BY
,DATA:"SITE_USE_CODE" AS SITE_USE_CODE
,DATA:"PRIMARY_FLAG" AS PRIMARY_FLAG
,DATA:"STATUS" AS STATUS
,DATA:"LOCATION" AS LOCATION
,DATA:"LAST_UPDATE_LOGIN" AS LAST_UPDATE_LOGIN
,DATA:"CONTACT_ID" AS CONTACT_ID
,DATA:"BILL_TO_SITE_USE_ID" AS BILL_TO_SITE_USE_ID
,DATA:"ORIG_SYSTEM_REFERENCE" AS ORIG_SYSTEM_REFERENCE
,DATA:"SIC_CODE" AS SIC_CODE
,DATA:"PAYMENT_TERM_ID" AS PAYMENT_TERM_ID
,DATA:"GSA_INDICATOR" AS GSA_INDICATOR
,DATA:"SHIP_PARTIAL" AS SHIP_PARTIAL
,DATA:"SHIP_VIA" AS SHIP_VIA
,DATA:"FOB_POINT" AS FOB_POINT
,DATA:"ORDER_TYPE_ID" AS ORDER_TYPE_ID
,DATA:"PRICE_LIST_ID" AS PRICE_LIST_ID
,DATA:"FREIGHT_TERM" AS FREIGHT_TERM
,DATA:"WAREHOUSE_ID" AS WAREHOUSE_ID
,DATA:"TERRITORY_ID" AS TERRITORY_ID
,DATA:"ATTRIBUTE_CATEGORY" AS ATTRIBUTE_CATEGORY
,DATA:"ATTRIBUTE1" AS ATTRIBUTE1
,DATA:"ATTRIBUTE2" AS ATTRIBUTE2
,DATA:"ATTRIBUTE3" AS ATTRIBUTE3
,DATA:"ATTRIBUTE4" AS ATTRIBUTE4
,DATA:"ATTRIBUTE5" AS ATTRIBUTE5
,DATA:"ATTRIBUTE6" AS ATTRIBUTE6
,DATA:"ATTRIBUTE7" AS ATTRIBUTE7
,DATA:"ATTRIBUTE8" AS ATTRIBUTE8
,DATA:"ATTRIBUTE9" AS ATTRIBUTE9
,DATA:"ATTRIBUTE10" AS ATTRIBUTE10
,DATA:"REQUEST_ID" AS REQUEST_ID
,DATA:"PROGRAM_APPLICATION_ID" AS PROGRAM_APPLICATION_ID
,DATA:"PROGRAM_ID" AS PROGRAM_ID
,DATA:"PROGRAM_UPDATE_DATE" AS PROGRAM_UPDATE_DATE
,DATA:"TAX_REFERENCE" AS TAX_REFERENCE
,DATA:"SORT_PRIORITY" AS SORT_PRIORITY
,DATA:"TAX_CODE" AS TAX_CODE
,DATA:"ATTRIBUTE11" AS ATTRIBUTE11
,DATA:"ATTRIBUTE12" AS ATTRIBUTE12
,DATA:"ATTRIBUTE13" AS ATTRIBUTE13
,DATA:"ATTRIBUTE14" AS ATTRIBUTE14
,DATA:"ATTRIBUTE15" AS ATTRIBUTE15
,DATA:"ATTRIBUTE16" AS ATTRIBUTE16
,DATA:"ATTRIBUTE17" AS ATTRIBUTE17
,DATA:"ATTRIBUTE18" AS ATTRIBUTE18
,DATA:"ATTRIBUTE19" AS ATTRIBUTE19
,DATA:"ATTRIBUTE20" AS ATTRIBUTE20
,DATA:"ATTRIBUTE21" AS ATTRIBUTE21
,DATA:"ATTRIBUTE22" AS ATTRIBUTE22
,DATA:"ATTRIBUTE23" AS ATTRIBUTE23
,DATA:"ATTRIBUTE24" AS ATTRIBUTE24
,DATA:"ATTRIBUTE25" AS ATTRIBUTE25
,DATA:"LAST_ACCRUE_CHARGE_DATE" AS LAST_ACCRUE_CHARGE_DATE
,DATA:"SECOND_LAST_ACCRUE_CHARGE_DATE" AS SECOND_LAST_ACCRUE_CHARGE_DATE
,DATA:"LAST_UNACCRUE_CHARGE_DATE" AS LAST_UNACCRUE_CHARGE_DATE
,DATA:"SECOND_LAST_UNACCRUE_CHRG_DATE" AS SECOND_LAST_UNACCRUE_CHRG_DATE
,DATA:"DEMAND_CLASS_CODE" AS DEMAND_CLASS_CODE
,DATA:"ORG_ID" AS ORG_ID
,DATA:"TAX_HEADER_LEVEL_FLAG" AS TAX_HEADER_LEVEL_FLAG
,DATA:"TAX_ROUNDING_RULE" AS TAX_ROUNDING_RULE
,DATA:"WH_UPDATE_DATE" AS WH_UPDATE_DATE
,DATA:"GLOBAL_ATTRIBUTE1" AS GLOBAL_ATTRIBUTE1
,DATA:"GLOBAL_ATTRIBUTE2" AS GLOBAL_ATTRIBUTE2
,DATA:"GLOBAL_ATTRIBUTE3" AS GLOBAL_ATTRIBUTE3
,DATA:"GLOBAL_ATTRIBUTE4" AS GLOBAL_ATTRIBUTE4
,DATA:"GLOBAL_ATTRIBUTE5" AS GLOBAL_ATTRIBUTE5
,DATA:"GLOBAL_ATTRIBUTE6" AS GLOBAL_ATTRIBUTE6
,DATA:"GLOBAL_ATTRIBUTE7" AS GLOBAL_ATTRIBUTE7
,DATA:"GLOBAL_ATTRIBUTE8" AS GLOBAL_ATTRIBUTE8
,DATA:"GLOBAL_ATTRIBUTE9" AS GLOBAL_ATTRIBUTE9
,DATA:"GLOBAL_ATTRIBUTE10" AS GLOBAL_ATTRIBUTE10
,DATA:"GLOBAL_ATTRIBUTE11" AS GLOBAL_ATTRIBUTE11
,DATA:"GLOBAL_ATTRIBUTE12" AS GLOBAL_ATTRIBUTE12
,DATA:"GLOBAL_ATTRIBUTE13" AS GLOBAL_ATTRIBUTE13
,DATA:"GLOBAL_ATTRIBUTE14" AS GLOBAL_ATTRIBUTE14
,DATA:"GLOBAL_ATTRIBUTE15" AS GLOBAL_ATTRIBUTE15
,DATA:"GLOBAL_ATTRIBUTE16" AS GLOBAL_ATTRIBUTE16
,DATA:"GLOBAL_ATTRIBUTE17" AS GLOBAL_ATTRIBUTE17
,DATA:"GLOBAL_ATTRIBUTE18" AS GLOBAL_ATTRIBUTE18
,DATA:"GLOBAL_ATTRIBUTE19" AS GLOBAL_ATTRIBUTE19
,DATA:"GLOBAL_ATTRIBUTE20" AS GLOBAL_ATTRIBUTE20
,DATA:"GLOBAL_ATTRIBUTE_CATEGORY" AS GLOBAL_ATTRIBUTE_CATEGORY
,DATA:"PRIMARY_SALESREP_ID" AS PRIMARY_SALESREP_ID
,DATA:"FINCHRG_RECEIVABLES_TRX_ID" AS FINCHRG_RECEIVABLES_TRX_ID
,DATA:"DATES_NEGATIVE_TOLERANCE" AS DATES_NEGATIVE_TOLERANCE
,DATA:"DATES_POSITIVE_TOLERANCE" AS DATES_POSITIVE_TOLERANCE
,DATA:"DATE_TYPE_PREFERENCE" AS DATE_TYPE_PREFERENCE
,DATA:"OVER_SHIPMENT_TOLERANCE" AS OVER_SHIPMENT_TOLERANCE
,DATA:"UNDER_SHIPMENT_TOLERANCE" AS UNDER_SHIPMENT_TOLERANCE
,DATA:"ITEM_CROSS_REF_PREF" AS ITEM_CROSS_REF_PREF
,DATA:"OVER_RETURN_TOLERANCE" AS OVER_RETURN_TOLERANCE
,DATA:"UNDER_RETURN_TOLERANCE" AS UNDER_RETURN_TOLERANCE
,DATA:"SHIP_SETS_INCLUDE_LINES_FLAG" AS SHIP_SETS_INCLUDE_LINES_FLAG
,DATA:"ARRIVALSETS_INCLUDE_LINES_FLAG" AS ARRIVALSETS_INCLUDE_LINES_FLAG
,DATA:"SCHED_DATE_PUSH_FLAG" AS SCHED_DATE_PUSH_FLAG
,DATA:"INVOICE_QUANTITY_RULE" AS INVOICE_QUANTITY_RULE
,DATA:"PRICING_EVENT" AS PRICING_EVENT
,DATA:"GL_ID_REC" AS GL_ID_REC
,DATA:"GL_ID_REV" AS GL_ID_REV
,DATA:"GL_ID_TAX" AS GL_ID_TAX
,DATA:"GL_ID_FREIGHT" AS GL_ID_FREIGHT
,DATA:"GL_ID_CLEARING" AS GL_ID_CLEARING
,DATA:"GL_ID_UNBILLED" AS GL_ID_UNBILLED
,DATA:"GL_ID_UNEARNED" AS GL_ID_UNEARNED
,DATA:"GL_ID_UNPAID_REC" AS GL_ID_UNPAID_REC
,DATA:"GL_ID_REMITTANCE" AS GL_ID_REMITTANCE
,DATA:"GL_ID_FACTOR" AS GL_ID_FACTOR
,DATA:"TAX_CLASSIFICATION" AS TAX_CLASSIFICATION
,DATA:"OBJECT_VERSION_NUMBER" AS OBJECT_VERSION_NUMBER
,DATA:"CREATED_BY_MODULE" AS CREATED_BY_MODULE
,DATA:"APPLICATION_ID" AS APPLICATION_ID
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM 
 {{ source("landing_ebs", "HZ_CUST_SITE_USES_ALL")}}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM 
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM 
                  {{ source("landing_ebs", "HZ_CUST_SITE_USES_ALL")}}
                    
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )