{{
  config(
    materialized = "view",
    alias = "wip_discrete_jobs",
    schema='EBS'
  )
}}

SELECT 
 DATA:WIP_ENTITY_ID AS WIP_ENTITY_ID
,DATA:ORGANIZATION_ID AS ORGANIZATION_ID
,DATA:LAST_UPDATE_DATE AS LAST_UPDATE_DATE
,DATA:LAST_UPDATED_BY AS LAST_UPDATED_BY
,DATA:CREATION_DATE AS CREATION_DATE
,DATA:CREATED_BY AS CREATED_BY
,DATA:LAST_UPDATE_LOGIN AS LAST_UPDATE_LOGIN
,DATA:REQUEST_ID AS REQUEST_ID
,DATA:PROGRAM_APPLICATION_ID AS PROGRAM_APPLICATION_ID
,DATA:PROGRAM_ID AS PROGRAM_ID
,DATA:PROGRAM_UPDATE_DATE AS PROGRAM_UPDATE_DATE
,DATA:SOURCE_LINE_ID AS SOURCE_LINE_ID
,DATA:SOURCE_CODE AS SOURCE_CODE
,DATA:DESCRIPTION AS DESCRIPTION
,DATA:STATUS_TYPE AS STATUS_TYPE
,DATA:PRIMARY_ITEM_ID AS PRIMARY_ITEM_ID
,DATA:FIRM_PLANNED_FLAG AS FIRM_PLANNED_FLAG
,DATA:JOB_TYPE AS JOB_TYPE
,DATA:WIP_SUPPLY_TYPE AS WIP_SUPPLY_TYPE
,DATA:CLASS_CODE AS CLASS_CODE
,DATA:MATERIAL_ACCOUNT AS MATERIAL_ACCOUNT
,DATA:MATERIAL_OVERHEAD_ACCOUNT AS MATERIAL_OVERHEAD_ACCOUNT
,DATA:RESOURCE_ACCOUNT AS RESOURCE_ACCOUNT
,DATA:OUTSIDE_PROCESSING_ACCOUNT AS OUTSIDE_PROCESSING_ACCOUNT
,DATA:MATERIAL_VARIANCE_ACCOUNT AS MATERIAL_VARIANCE_ACCOUNT
,DATA:RESOURCE_VARIANCE_ACCOUNT AS RESOURCE_VARIANCE_ACCOUNT
,DATA:OUTSIDE_PROC_VARIANCE_ACCOUNT AS OUTSIDE_PROC_VARIANCE_ACCOUNT
,DATA:STD_COST_ADJUSTMENT_ACCOUNT AS STD_COST_ADJUSTMENT_ACCOUNT
,DATA:OVERHEAD_ACCOUNT AS OVERHEAD_ACCOUNT
,DATA:OVERHEAD_VARIANCE_ACCOUNT AS OVERHEAD_VARIANCE_ACCOUNT
,DATA:SCHEDULED_START_DATE AS SCHEDULED_START_DATE
,DATA:DATE_RELEASED AS DATE_RELEASED
,DATA:SCHEDULED_COMPLETION_DATE AS SCHEDULED_COMPLETION_DATE
,DATA:DATE_COMPLETED AS DATE_COMPLETED
,DATA:DATE_CLOSED AS DATE_CLOSED
,DATA:START_QUANTITY AS START_QUANTITY
,DATA:QUANTITY_COMPLETED AS QUANTITY_COMPLETED
,DATA:QUANTITY_SCRAPPED AS QUANTITY_SCRAPPED
,DATA:NET_QUANTITY AS NET_QUANTITY
,DATA:BOM_REFERENCE_ID AS BOM_REFERENCE_ID
,DATA:ROUTING_REFERENCE_ID AS ROUTING_REFERENCE_ID
,DATA:COMMON_BOM_SEQUENCE_ID AS COMMON_BOM_SEQUENCE_ID
,DATA:COMMON_ROUTING_SEQUENCE_ID AS COMMON_ROUTING_SEQUENCE_ID
,DATA:BOM_REVISION AS BOM_REVISION
,DATA:ROUTING_REVISION AS ROUTING_REVISION
,DATA:BOM_REVISION_DATE AS BOM_REVISION_DATE
,DATA:ROUTING_REVISION_DATE AS ROUTING_REVISION_DATE
,DATA:LOT_NUMBER AS LOT_NUMBER
,DATA:ALTERNATE_BOM_DESIGNATOR AS ALTERNATE_BOM_DESIGNATOR
,DATA:ALTERNATE_ROUTING_DESIGNATOR AS ALTERNATE_ROUTING_DESIGNATOR
,DATA:COMPLETION_SUBINVENTORY AS COMPLETION_SUBINVENTORY
,DATA:COMPLETION_LOCATOR_ID AS COMPLETION_LOCATOR_ID
,DATA:MPS_SCHEDULED_COMPLETION_DATE AS MPS_SCHEDULED_COMPLETION_DATE
,DATA:MPS_NET_QUANTITY AS MPS_NET_QUANTITY
,DATA:DEMAND_CLASS AS DEMAND_CLASS
,DATA:SCHEDULE_GROUP_ID AS SCHEDULE_GROUP_ID
,DATA:BUILD_SEQUENCE AS BUILD_SEQUENCE
,DATA:LINE_ID AS LINE_ID
,DATA:PROJECT_ID AS PROJECT_ID
,DATA:TASK_ID AS TASK_ID
,DATA:ATTRIBUTE_CATEGORY AS ATTRIBUTE_CATEGORY
,DATA:ATTRIBUTE1 AS ATTRIBUTE1
,DATA:ATTRIBUTE2 AS ATTRIBUTE2
,DATA:ATTRIBUTE3 AS ATTRIBUTE3
,DATA:ATTRIBUTE4 AS ATTRIBUTE4
,DATA:ATTRIBUTE5 AS ATTRIBUTE5
,DATA:ATTRIBUTE6 AS ATTRIBUTE6
,DATA:ATTRIBUTE7 AS ATTRIBUTE7
,DATA:ATTRIBUTE8 AS ATTRIBUTE8
,DATA:ATTRIBUTE9 AS ATTRIBUTE9
,DATA:ATTRIBUTE10 AS ATTRIBUTE10
,DATA:ATTRIBUTE11 AS ATTRIBUTE11
,DATA:ATTRIBUTE12 AS ATTRIBUTE12
,DATA:ATTRIBUTE13 AS ATTRIBUTE13
,DATA:ATTRIBUTE14 AS ATTRIBUTE14
,DATA:ATTRIBUTE15 AS ATTRIBUTE15
,DATA:KANBAN_CARD_ID AS KANBAN_CARD_ID
,DATA:OVERCOMPLETION_TOLERANCE_TYPE AS OVERCOMPLETION_TOLERANCE_TYPE
,DATA:OVERCOMPLETION_TOLERANCE_VALUE AS OVERCOMPLETION_TOLERANCE_VALUE
,DATA:END_ITEM_UNIT_NUMBER AS END_ITEM_UNIT_NUMBER
,DATA:PO_CREATION_TIME AS PO_CREATION_TIME
,DATA:PRIORITY AS PRIORITY
,DATA:DUE_DATE AS DUE_DATE
,DATA:ISSUE_ZERO_COST_FLAG AS ISSUE_ZERO_COST_FLAG
,DATA:EST_SCRAP_ACCOUNT AS EST_SCRAP_ACCOUNT
,DATA:EST_SCRAP_VAR_ACCOUNT AS EST_SCRAP_VAR_ACCOUNT
,DATA:EST_SCRAP_PRIOR_QTY AS EST_SCRAP_PRIOR_QTY
,DATA:DUE_DATE_PENALTY AS DUE_DATE_PENALTY
,DATA:DUE_DATE_TOLERANCE AS DUE_DATE_TOLERANCE
,DATA:COPRODUCTS_SUPPLY AS COPRODUCTS_SUPPLY
,DATA:PARENT_WIP_ENTITY_ID AS PARENT_WIP_ENTITY_ID
,DATA:ASSET_NUMBER AS ASSET_NUMBER
,DATA:ASSET_GROUP_ID AS ASSET_GROUP_ID
,DATA:REBUILD_ITEM_ID AS REBUILD_ITEM_ID
,DATA:REBUILD_SERIAL_NUMBER AS REBUILD_SERIAL_NUMBER
,DATA:MANUAL_REBUILD_FLAG AS MANUAL_REBUILD_FLAG
,DATA:SHUTDOWN_TYPE AS SHUTDOWN_TYPE
,DATA:ESTIMATION_STATUS AS ESTIMATION_STATUS
,DATA:REQUESTED_START_DATE AS REQUESTED_START_DATE
,DATA:NOTIFICATION_REQUIRED AS NOTIFICATION_REQUIRED
,DATA:WORK_ORDER_TYPE AS WORK_ORDER_TYPE
,DATA:OWNING_DEPARTMENT AS OWNING_DEPARTMENT
,DATA:ACTIVITY_TYPE AS ACTIVITY_TYPE
,DATA:ACTIVITY_CAUSE AS ACTIVITY_CAUSE
,DATA:ACTIVITY_SOURCE AS ACTIVITY_SOURCE
,DATA:TAGOUT_REQUIRED AS TAGOUT_REQUIRED
,DATA:PLAN_MAINTENANCE AS PLAN_MAINTENANCE
,DATA:PM_SCHEDULE_ID AS PM_SCHEDULE_ID
,DATA:LAST_ESTIMATION_DATE AS LAST_ESTIMATION_DATE
,DATA:LAST_ESTIMATION_REQ_ID AS LAST_ESTIMATION_REQ_ID
,DATA:SERIALIZATION_START_OP AS SERIALIZATION_START_OP
,DATA:MAINTENANCE_OBJECT_ID AS MAINTENANCE_OBJECT_ID
,DATA:MAINTENANCE_OBJECT_TYPE AS MAINTENANCE_OBJECT_TYPE
,DATA:MAINTENANCE_OBJECT_SOURCE AS MAINTENANCE_OBJECT_SOURCE
,DATA:MATERIAL_ISSUE_BY_MO AS MATERIAL_ISSUE_BY_MO
,DATA:SCHEDULING_REQUEST_ID AS SCHEDULING_REQUEST_ID
,DATA:EAM_LINEAR_LOCATION_ID AS EAM_LINEAR_LOCATION_ID
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM {{ source("landing_ebs", "WIP_DISCRETE_JOBS") }}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM 
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM 
                  {{ source("landing_ebs", "WIP_DISCRETE_JOBS")}}
                    
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )