{{
  config(
    materialized = "view",
    alias = "bom_resources",
    schema='EBS'
  )
}}

SELECT DATA:ATTRIBUTE9 AS ATTRIBUTE9
,DATA:PROGRAM_UPDATE_DATE AS PROGRAM_UPDATE_DATE
,DATA:PROGRAM_ID AS PROGRAM_ID
,DATA:PROGRAM_APPLICATION_ID AS PROGRAM_APPLICATION_ID
,DATA:REQUEST_ID AS REQUEST_ID
,DATA:ATTRIBUTE15 AS ATTRIBUTE15
,DATA:ATTRIBUTE14 AS ATTRIBUTE14
,DATA:ATTRIBUTE13 AS ATTRIBUTE13
,DATA:ATTRIBUTE12 AS ATTRIBUTE12
,DATA:ATTRIBUTE11 AS ATTRIBUTE11
,DATA:ATTRIBUTE10 AS ATTRIBUTE10
,DATA:ATTRIBUTE8 AS ATTRIBUTE8
,DATA:ATTRIBUTE7 AS ATTRIBUTE7
,DATA:ATTRIBUTE6 AS ATTRIBUTE6
,DATA:ATTRIBUTE5 AS ATTRIBUTE5
,DATA:ATTRIBUTE4 AS ATTRIBUTE4
,DATA:ATTRIBUTE3 AS ATTRIBUTE3
,DATA:ATTRIBUTE2 AS ATTRIBUTE2
,DATA:ATTRIBUTE1 AS ATTRIBUTE1
,DATA:ATTRIBUTE_CATEGORY AS ATTRIBUTE_CATEGORY
,DATA:EXPENDITURE_TYPE AS EXPENDITURE_TYPE
,DATA:RATE_VARIANCE_ACCOUNT AS RATE_VARIANCE_ACCOUNT
,DATA:ALLOW_COSTS_FLAG AS ALLOW_COSTS_FLAG
,DATA:ABSORPTION_ACCOUNT AS ABSORPTION_ACCOUNT
,DATA:DEFAULT_BASIS_TYPE AS DEFAULT_BASIS_TYPE
,DATA:STANDARD_RATE_FLAG AS STANDARD_RATE_FLAG
,DATA:AUTOCHARGE_TYPE AS AUTOCHARGE_TYPE
,DATA:RESOURCE_TYPE AS RESOURCE_TYPE
,DATA:DEFAULT_ACTIVITY_ID AS DEFAULT_ACTIVITY_ID
,DATA:UNIT_OF_MEASURE AS UNIT_OF_MEASURE
,DATA:FUNCTIONAL_CURRENCY_FLAG AS FUNCTIONAL_CURRENCY_FLAG
,DATA:COST_CODE_TYPE AS COST_CODE_TYPE
,DATA:PURCHASE_ITEM_ID AS PURCHASE_ITEM_ID
,DATA:COST_ELEMENT_ID AS COST_ELEMENT_ID
,DATA:DISABLE_DATE AS DISABLE_DATE
,DATA:DESCRIPTION AS DESCRIPTION
,DATA:LAST_UPDATE_LOGIN AS LAST_UPDATE_LOGIN
,DATA:CREATED_BY AS CREATED_BY
,DATA:CREATION_DATE AS CREATION_DATE
,DATA:LAST_UPDATED_BY AS LAST_UPDATED_BY
,DATA:LAST_UPDATE_DATE AS LAST_UPDATE_DATE
,DATA:ORGANIZATION_ID AS ORGANIZATION_ID
,DATA:RESOURCE_CODE AS RESOURCE_CODE
,DATA:RESOURCE_ID AS RESOURCE_ID
,DATA:COMPETENCE_ID AS COMPETENCE_ID
,DATA:BATCH_WINDOW_UOM AS BATCH_WINDOW_UOM
,DATA:BATCH_WINDOW AS BATCH_WINDOW
,DATA:BATCH_CAPACITY_UOM AS BATCH_CAPACITY_UOM
,DATA:MIN_BATCH_CAPACITY AS MIN_BATCH_CAPACITY
,DATA:MAX_BATCH_CAPACITY AS MAX_BATCH_CAPACITY
,DATA:BATCHABLE AS BATCHABLE
,DATA:QUALIFICATION_TYPE_ID AS QUALIFICATION_TYPE_ID
,DATA:RATING_LEVEL_ID AS RATING_LEVEL_ID
,DATA:SUPPLY_LOCATOR_ID AS SUPPLY_LOCATOR_ID
,DATA:SUPPLY_SUBINVENTORY AS SUPPLY_SUBINVENTORY
,DATA:BILLABLE_ITEM_ID AS BILLABLE_ITEM_ID
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM {{ source("landing_ebs", "bom_resources") }}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM 
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM 
                  {{ source("landing_ebs", "bom_resources")}}
                    
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )