{{
  config(
    materialized = "view",
    alias = "cm50_po_line_locations",
    schema='EBS',
    tags=["cm50_po_line_locations"]
  )
}}

SELECT
DATA:PLL_LINE_LOCATION_ID AS PLL_LINE_LOCATION_ID
,DATA:PLL_LAST_UPDATE_DATE AS PLL_LAST_UPDATE_DATE
,DATA:PLL_LAST_UPDATED_BY AS PLL_LAST_UPDATED_BY
,DATA:PLL_PO_HEADER_ID AS PLL_PO_HEADER_ID
,DATA:PLL_PO_LINE_ID AS PLL_PO_LINE_ID
,DATA:PLL_LAST_UPDATE_LOGIN AS PLL_LAST_UPDATE_LOGIN
,DATA:PLL_CREATION_DATE AS PLL_CREATION_DATE
,DATA:PLL_CREATED_BY AS PLL_CREATED_BY
,DATA:PLL_QUANTITY AS PLL_QUANTITY
,DATA:PLL_QUANTITY_ACCEPTED AS PLL_QUANTITY_ACCEPTED
,DATA:PLL_QUANTITY_RECEIVED AS PLL_QUANTITY_RECEIVED
,DATA:PLL_QUANTITY_REJECTED AS PLL_QUANTITY_REJECTED
,DATA:PLL_QUANTITY_BILLED AS PLL_QUANTITY_BILLED
,DATA:PLL_QUANTITY_CANCELLED AS PLL_QUANTITY_CANCELLED
,DATA:PLL_UNIT_MEAS_LOOKUP_CODE AS PLL_UNIT_MEAS_LOOKUP_CODE
,DATA:PLL_PO_RELEASE_ID AS PLL_PO_RELEASE_ID
,DATA:PLL_SHIP_TO_LOCATION_ID AS PLL_SHIP_TO_LOCATION_ID
,DATA:PLL_SHIP_VIA_LOOKUP_CODE AS PLL_SHIP_VIA_LOOKUP_CODE
,DATA:PLL_NEED_BY_DATE AS PLL_NEED_BY_DATE
,DATA:PLL_PROMISED_DATE AS PLL_PROMISED_DATE
,DATA:PLL_LAST_ACCEPT_DATE AS PLL_LAST_ACCEPT_DATE
,DATA:PLL_PRICE_OVERRIDE AS PLL_PRICE_OVERRIDE
,DATA:PLL_ENCUMBERED_FLAG AS PLL_ENCUMBERED_FLAG
,DATA:PLL_FOB_LOOKUP_CODE AS PLL_FOB_LOOKUP_CODE
,DATA:PLL_FREIGHT_TERMS_LOOKUP_CODE AS PLL_FREIGHT_TERMS_LOOKUP_CODE
,DATA:PLL_TAXABLE_FLAG AS PLL_TAXABLE_FLAG
,DATA:PLL_TAX_NAME AS PLL_TAX_NAME
,DATA:PLL_FROM_HEADER_ID AS PLL_FROM_HEADER_ID
,DATA:PLL_FROM_LINE_ID AS PLL_FROM_LINE_ID
,DATA:PLL_START_DATE AS PLL_START_DATE
,DATA:PLL_END_DATE AS PLL_END_DATE
,DATA:PLL_PRICE_DISCOUNT AS PLL_PRICE_DISCOUNT
,DATA:PLL_TERMS_ID AS PLL_TERMS_ID
,DATA:PLL_APPROVED_FLAG AS PLL_APPROVED_FLAG
,DATA:PLL_APPROVED_DATE AS PLL_APPROVED_DATE
,DATA:PLL_CANCEL_FLAG AS PLL_CANCEL_FLAG
,DATA:PLL_CANCELLED_BY AS PLL_CANCELLED_BY
,DATA:PLL_CANCEL_DATE AS PLL_CANCEL_DATE
,DATA:PLL_CANCEL_REASON AS PLL_CANCEL_REASON
,DATA:PLL_FIRM_STATUS_LOOKUP_CODE AS PLL_FIRM_STATUS_LOOKUP_CODE
,DATA:PLL_INSPECTION_REQUIRED_FLAG AS PLL_INSPECTION_REQUIRED_FLAG
,DATA:PLL_RECEIPT_REQUIRED_FLAG AS PLL_RECEIPT_REQUIRED_FLAG
,DATA:PLL_QTY_RCV_TOLERANCE AS PLL_QTY_RCV_TOLERANCE
,DATA:PLL_QTY_RCV_EXCEPTION_CODE AS PLL_QTY_RCV_EXCEPTION_CODE
,DATA:PLL_ENFOR_SHIP_TO_LOC_CODE AS PLL_ENFOR_SHIP_TO_LOC_CODE
,DATA:PLL_ALLOW_SUTE_RECTS_FLAG AS PLL_ALLOW_SUTE_RECTS_FLAG
,DATA:PLL_DAYS_EARLY_RECEIPT_ALLOWED AS PLL_DAYS_EARLY_RECEIPT_ALLOWED
,DATA:PLL_DAYS_LATE_RECEIPT_ALLOWED AS PLL_DAYS_LATE_RECEIPT_ALLOWED
,DATA:PLL_RECEIPT_DAYS_EXC_CODE AS PLL_RECEIPT_DAYS_EXC_CODE
,DATA:PLL_INVOICE_CLOSE_TOLERANCE AS PLL_INVOICE_CLOSE_TOLERANCE
,DATA:PLL_RECEIVE_CLOSE_TOLERANCE AS PLL_RECEIVE_CLOSE_TOLERANCE
,DATA:PLL_SHIP_TO_ORGANIZATION_ID AS PLL_SHIP_TO_ORGANIZATION_ID
,DATA:PLL_SHIPMENT_NUM AS PLL_SHIPMENT_NUM
,DATA:PLL_SHIPMENT_TYPE AS PLL_SHIPMENT_TYPE
,DATA:PLL_CLOSED_CODE AS PLL_CLOSED_CODE
,DATA:PLL_REQUEST_ID AS PLL_REQUEST_ID
,DATA:PLL_PROGRAM_APPLICATION_ID AS PLL_PROGRAM_APPLICATION_ID
,DATA:PLL_PROGRAM_ID AS PLL_PROGRAM_ID
,DATA:PLL_PROGRAM_UPDATE_DATE AS PLL_PROGRAM_UPDATE_DATE
,DATA:PLL_RECEIVING_ROUTING_ID AS PLL_RECEIVING_ROUTING_ID
,DATA:PLL_ACCRUE_ON_RECEIPT_FLAG AS PLL_ACCRUE_ON_RECEIPT_FLAG
,DATA:PLL_CLOSED_REASON AS PLL_CLOSED_REASON
,DATA:PLL_CLOSED_DATE AS PLL_CLOSED_DATE
,DATA:PLL_CLOSED_BY AS PLL_CLOSED_BY
,DATA:PLL_ORG_ID AS PLL_ORG_ID
,DATA:PLL_QUANTITY_SHIPPED AS PLL_QUANTITY_SHIPPED
,DATA:PLL_COUNTRY_OF_ORIGIN_CODE AS PLL_COUNTRY_OF_ORIGIN_CODE
,DATA:PLL_TAX_USER_OVERRIDE_FLAG AS PLL_TAX_USER_OVERRIDE_FLAG
,DATA:PLL_MATCH_OPTION AS PLL_MATCH_OPTION
,DATA:PLL_TAX_CODE_ID AS PLL_TAX_CODE_ID
,DATA:PLL_CALCULATE_TAX_FLAG AS PLL_CALCULATE_TAX_FLAG
,DATA:PLL_NOTE_TO_RECEIVER AS PLL_NOTE_TO_RECEIVER
,DATA:PLL_SECONDARY_QTY_RECEIVED AS PLL_SECONDARY_QTY_RECEIVED
,DATA:PLL_SECONDARY_QTY_ACCEPTED AS PLL_SECONDARY_QTY_ACCEPTED
,DATA:PLL_SECONDARY_QTY_REJECTED AS PLL_SECONDARY_QTY_REJECTED
,DATA:PLL_SECONDARY_QTY_CANCELLED AS PLL_SECONDARY_QTY_CANCELLED
,DATA:PLL_CONSIGNED_FLAG AS PLL_CONSIGNED_FLAG
,DATA:PLL_RETROACTIVE_DATE AS PLL_RETROACTIVE_DATE
,DATA:PLL_AMOUNT_RECEIVED AS PLL_AMOUNT_RECEIVED
,DATA:PLL_AMOUNT_BILLED AS PLL_AMOUNT_BILLED
,DATA:PLL_AMOUNT_CANCELLED AS PLL_AMOUNT_CANCELLED
,DATA:PLL_AMOUNT_REJECTED AS PLL_AMOUNT_REJECTED
,DATA:PLL_AMOUNT_ACCEPTED AS PLL_AMOUNT_ACCEPTED
,DATA:PLL_DROP_SHIP_FLAG AS PLL_DROP_SHIP_FLAG
,DATA:PLL_MANUAL_PRICE_CHANGE_FLAG AS PLL_MANUAL_PRICE_CHANGE_FLAG
,DATA:PLL_SHIPMENT_CLOSED_DATE AS PLL_SHIPMENT_CLOSED_DATE
,DATA:PLL_CLOSED_FOR_RECEIVING_DATE AS PLL_CLOSED_FOR_RECEIVING_DATE
,DATA:PLL_CLOSED_FOR_INVOICE_DATE AS PLL_CLOSED_FOR_INVOICE_DATE
,FILENAME                           as METADATA_FILENAME 
,FILE_ROW_NUMBER                    as METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                 as METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                    as METADATA_START_SCAN_TIME
from {{ source("landing_ebs", "CM50_PO_LINE_LOCATIONS") }}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM
                    {{ source("landing_ebs", "CM50_PO_LINE_LOCATIONS") }}
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )