{{
  config(
    materialized = "view",
    alias = "eam_work_orders",
    schema='EBS'
  )
}}

SELECT
 DATA:ATTRIBUTE7 AS ATTRIBUTE7
,DATA:ATTRIBUTE6 AS ATTRIBUTE6
,DATA:ATTRIBUTE5 AS ATTRIBUTE5
,DATA:ATTRIBUTE4 AS ATTRIBUTE4
,DATA:ATTRIBUTE3 AS ATTRIBUTE3
,DATA:ATTRIBUTE2 AS ATTRIBUTE2
,DATA:ATTRIBUTE1 AS ATTRIBUTE1
,DATA:ATTRIBUTE_CATEGORY AS ATTRIBUTE_CATEGORY
,DATA:DEMAND_CLASS AS DEMAND_CLASS
,DATA:LOT_NUMBER AS LOT_NUMBER
,DATA:COMPLETION_LOCATOR_ID AS COMPLETION_LOCATOR_ID
,DATA:COMPLETION_SUBINVENTORY AS COMPLETION_SUBINVENTORY
,DATA:ROUTING_REVISION_DATE AS ROUTING_REVISION_DATE
,DATA:ROUTING_REVISION AS ROUTING_REVISION
,DATA:ALTERNATE_ROUTING_DESIGNATOR AS ALTERNATE_ROUTING_DESIGNATOR
,DATA:BOM_REVISION_DATE AS BOM_REVISION_DATE
,DATA:BOM_REVISION AS BOM_REVISION
,DATA:ALTERNATE_BOM_DESIGNATOR AS ALTERNATE_BOM_DESIGNATOR
,DATA:COMMON_ROUTING_SEQUENCE_ID AS COMMON_ROUTING_SEQUENCE_ID
,DATA:COMMON_BOM_SEQUENCE_ID AS COMMON_BOM_SEQUENCE_ID
,DATA:ROUTING_REFERENCE_ID AS ROUTING_REFERENCE_ID
,DATA:BOM_REFERENCE_ID AS BOM_REFERENCE_ID
,DATA:REBUILD_SERIAL_NUMBER AS REBUILD_SERIAL_NUMBER
,DATA:REBUILD_ITEM_ID AS REBUILD_ITEM_ID
,DATA:PARENT_WIP_ENTITY_NAME AS PARENT_WIP_ENTITY_NAME
,DATA:PARENT_WIP_ENTITY_ID AS PARENT_WIP_ENTITY_ID
,DATA:TASK_ID AS TASK_ID
,DATA:TASK_NAME AS TASK_NAME
,DATA:TASK_NUMBER AS TASK_NUMBER
,DATA:PROJECT_ID AS PROJECT_ID
,DATA:PROJECT_NAME AS PROJECT_NAME
,DATA:PROJECT_NUMBER AS PROJECT_NUMBER
,DATA:SCHEDULE_GROUP_NAME AS SCHEDULE_GROUP_NAME
,DATA:SCHEDULE_GROUP_ID AS SCHEDULE_GROUP_ID
,DATA:FIRM_PLANNED_FLAG AS FIRM_PLANNED_FLAG
,DATA:PLAN_MAINTENANCE AS PLAN_MAINTENANCE
,DATA:TAGOUT_REQUIRED AS TAGOUT_REQUIRED
,DATA:SHUTDOWN_TYPE_DISP AS SHUTDOWN_TYPE_DISP
,DATA:SHUTDOWN_TYPE AS SHUTDOWN_TYPE
,DATA:NOTIFICATION_REQUIRED AS NOTIFICATION_REQUIRED
,DATA:ESTIMATION_STATUS AS ESTIMATION_STATUS
,DATA:REQUESTED_DUE_DATE AS REQUESTED_DUE_DATE
,DATA:REQUESTED_START_DATE AS REQUESTED_START_DATE
,DATA:PRIORITY_DISP AS PRIORITY_DISP
,DATA:PRIORITY AS PRIORITY
,DATA:ACTIVITY_CAUSE_DISP AS ACTIVITY_CAUSE_DISP
,DATA:ACTIVITY_CAUSE AS ACTIVITY_CAUSE
,DATA:ACTIVITY_TYPE_DISP AS ACTIVITY_TYPE_DISP
,DATA:ACTIVITY_TYPE AS ACTIVITY_TYPE
,DATA:OWNING_DEPARTMENT_CODE AS OWNING_DEPARTMENT_CODE
,DATA:OWNING_DEPARTMENT AS OWNING_DEPARTMENT
,DATA:DATE_CLOSED AS DATE_CLOSED
,DATA:DATE_COMPLETED AS DATE_COMPLETED
,DATA:DATE_RELEASED AS DATE_RELEASED
,DATA:SCHEDULED_COMPLETION_DATE AS SCHEDULED_COMPLETION_DATE
,DATA:SCHEDULED_START_DATE AS SCHEDULED_START_DATE
,DATA:OVERHEAD_VARIANCE_ACCOUNT AS OVERHEAD_VARIANCE_ACCOUNT
,DATA:OVERHEAD_ACCOUNT AS OVERHEAD_ACCOUNT
,DATA:STD_COST_ADJUSTMENT_ACCOUNT AS STD_COST_ADJUSTMENT_ACCOUNT
,DATA:OUTSIDE_PROC_VARIANCE_ACCOUNT AS OUTSIDE_PROC_VARIANCE_ACCOUNT
,DATA:RESOURCE_VARIANCE_ACCOUNT AS RESOURCE_VARIANCE_ACCOUNT
,DATA:MATERIAL_VARIANCE_ACCOUNT AS MATERIAL_VARIANCE_ACCOUNT
,DATA:OUTSIDE_PROCESSING_ACCOUNT AS OUTSIDE_PROCESSING_ACCOUNT
,DATA:RESOURCE_ACCOUNT AS RESOURCE_ACCOUNT
,DATA:MATERIAL_OVERHEAD_ACCOUNT AS MATERIAL_OVERHEAD_ACCOUNT
,DATA:MATERIAL_ACCOUNT AS MATERIAL_ACCOUNT
,DATA:WORK_ORDER_TYPE_DISP AS WORK_ORDER_TYPE_DISP
,DATA:WORK_ORDER_TYPE AS WORK_ORDER_TYPE
,DATA:MANUAL_REBUILD_FLAG AS MANUAL_REBUILD_FLAG
,DATA:PM_SCHEDULE_ID AS PM_SCHEDULE_ID
,DATA:STATUS_TYPE_DISP AS STATUS_TYPE_DISP
,DATA:STATUS_TYPE AS STATUS_TYPE
,DATA:CLASS_CODE AS CLASS_CODE
,DATA:ASSET_DESCRIPTION AS ASSET_DESCRIPTION
,DATA:ASSET_NUMBER AS ASSET_NUMBER
,DATA:ASSET_GROUP_ID AS ASSET_GROUP_ID
,DATA:PRIMARY_ITEM_ID AS PRIMARY_ITEM_ID
,DATA:DESCRIPTION AS DESCRIPTION
,DATA:LAST_UPDATE_LOGIN AS LAST_UPDATE_LOGIN
,DATA:CREATED_BY AS CREATED_BY
,DATA:CREATION_DATE AS CREATION_DATE
,DATA:LAST_UPDATED_BY AS LAST_UPDATED_BY
,DATA:LAST_UPDATE_DATE AS LAST_UPDATE_DATE
,DATA:ORGANIZATION_ID AS ORGANIZATION_ID
,DATA:ENTITY_TYPE AS ENTITY_TYPE
,DATA:WE_ROW_ID AS WE_ROW_ID
,DATA:WIP_ENTITY_NAME AS WIP_ENTITY_NAME
,DATA:WIP_ENTITY_ID AS WIP_ENTITY_ID
,DATA:ACTUAL_START_DATE AS ACTUAL_START_DATE
,DATA:SCHED_PARENT_WIP_ENTITY_NAME AS SCHED_PARENT_WIP_ENTITY_NAME
,DATA:ROW_ID AS ROW_ID
,DATA:RESOLUTION_CODE AS RESOLUTION_CODE
,DATA:CAUSE_CODE AS CAUSE_CODE
,DATA:FAILURE_CODE AS FAILURE_CODE
,DATA:FAILURE_ENTRY_ID AS FAILURE_ENTRY_ID
,DATA:FAILURE_ID AS FAILURE_ID
,DATA:EAM_LINEAR_LOCATION_ID AS EAM_LINEAR_LOCATION_ID
,DATA:ACTIVITY_SOURCE_MEANING AS ACTIVITY_SOURCE_MEANING
,DATA:ACTIVITY_SOURCE AS ACTIVITY_SOURCE
,DATA:MATERIAL_ISSUE_BY_MO AS MATERIAL_ISSUE_BY_MO
,DATA:SERVICE_REQUEST AS SERVICE_REQUEST
,DATA:SERVICE_REQUEST_ID AS SERVICE_REQUEST_ID
,DATA:MAINTENANCE_OBJECT_ID AS MAINTENANCE_OBJECT_ID
,DATA:SOURCE AS SOURCE
,DATA:MAINTENANCE_OBJECT_TYPE AS MAINTENANCE_OBJECT_TYPE
,DATA:MAINTENANCE_OBJECT_SOURCE AS MAINTENANCE_OBJECT_SOURCE
,DATA:INSTANCE_NUMBER AS INSTANCE_NUMBER
,DATA:INSTANCE_ID AS INSTANCE_ID
,DATA:ATTRIBUTE15 AS ATTRIBUTE15
,DATA:ATTRIBUTE14 AS ATTRIBUTE14
,DATA:ATTRIBUTE13 AS ATTRIBUTE13
,DATA:ATTRIBUTE12 AS ATTRIBUTE12
,DATA:ATTRIBUTE11 AS ATTRIBUTE11
,DATA:ATTRIBUTE10 AS ATTRIBUTE10
,DATA:ATTRIBUTE9 AS ATTRIBUTE9
,DATA:ATTRIBUTE8 AS ATTRIBUTE8
,DATA:COMMENTS AS COMMENTS
,DATA:FAILURE_DATE AS FAILURE_DATE
,DATA:FAILURE_CODE_REQUIRED AS FAILURE_CODE_REQUIRED
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM {{ source("landing_ebs", "EAM_WORK_ORDERS") }}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM 
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM 
                  {{ source("landing_ebs", "EAM_WORK_ORDERS")}}
                    
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )