{{
  config(
    materialized = "view",
    alias = "hz_parties",
    schema='ebs'
  )
}}

SELECT DATA:"PARTY_ID" AS PARTY_ID
,DATA:"PARTY_NUMBER" AS PARTY_NUMBER
,DATA:"PARTY_NAME" AS PARTY_NAME
,DATA:"PARTY_TYPE" AS PARTY_TYPE
,DATA:"VALIDATED_FLAG" AS VALIDATED_FLAG
,DATA:"LAST_UPDATED_BY" AS LAST_UPDATED_BY
,DATA:"CREATION_DATE" AS CREATION_DATE
,DATA:"LAST_UPDATE_LOGIN" AS LAST_UPDATE_LOGIN
,DATA:"REQUEST_ID" AS REQUEST_ID
,DATA:"PROGRAM_APPLICATION_ID" AS PROGRAM_APPLICATION_ID
,DATA:"CREATED_BY" AS CREATED_BY
,DATA:"LAST_UPDATE_DATE" AS LAST_UPDATE_DATE
,DATA:"PROGRAM_ID" AS PROGRAM_ID
,DATA:"PROGRAM_UPDATE_DATE" AS PROGRAM_UPDATE_DATE
,DATA:"WH_UPDATE_DATE" AS WH_UPDATE_DATE
,DATA:"ATTRIBUTE_CATEGORY" AS ATTRIBUTE_CATEGORY
,DATA:"ATTRIBUTE1" AS ATTRIBUTE1
,DATA:"ATTRIBUTE2" AS ATTRIBUTE2
,DATA:"ATTRIBUTE3" AS ATTRIBUTE3
,DATA:"ATTRIBUTE4" AS ATTRIBUTE4
,DATA:"ATTRIBUTE5" AS ATTRIBUTE5
,DATA:"ATTRIBUTE6" AS ATTRIBUTE6
,DATA:"ATTRIBUTE7" AS ATTRIBUTE7
,DATA:"ATTRIBUTE8" AS ATTRIBUTE8
,DATA:"ATTRIBUTE9" AS ATTRIBUTE9
,DATA:"ATTRIBUTE10" AS ATTRIBUTE10
,DATA:"ATTRIBUTE11" AS ATTRIBUTE11
,DATA:"ATTRIBUTE12" AS ATTRIBUTE12
,DATA:"ATTRIBUTE13" AS ATTRIBUTE13
,DATA:"ATTRIBUTE14" AS ATTRIBUTE14
,DATA:"ATTRIBUTE15" AS ATTRIBUTE15
,DATA:"ATTRIBUTE16" AS ATTRIBUTE16
,DATA:"ATTRIBUTE17" AS ATTRIBUTE17
,DATA:"ATTRIBUTE18" AS ATTRIBUTE18
,DATA:"ATTRIBUTE19" AS ATTRIBUTE19
,DATA:"ATTRIBUTE20" AS ATTRIBUTE20
,DATA:"ATTRIBUTE21" AS ATTRIBUTE21
,DATA:"ATTRIBUTE22" AS ATTRIBUTE22
,DATA:"ATTRIBUTE23" AS ATTRIBUTE23
,DATA:"ATTRIBUTE24" AS ATTRIBUTE24
,DATA:"GLOBAL_ATTRIBUTE_CATEGORY" AS GLOBAL_ATTRIBUTE_CATEGORY
,DATA:"GLOBAL_ATTRIBUTE1" AS GLOBAL_ATTRIBUTE1
,DATA:"GLOBAL_ATTRIBUTE2" AS GLOBAL_ATTRIBUTE2
,DATA:"GLOBAL_ATTRIBUTE4" AS GLOBAL_ATTRIBUTE4
,DATA:"GLOBAL_ATTRIBUTE3" AS GLOBAL_ATTRIBUTE3
,DATA:"GLOBAL_ATTRIBUTE5" AS GLOBAL_ATTRIBUTE5
,DATA:"GLOBAL_ATTRIBUTE6" AS GLOBAL_ATTRIBUTE6
,DATA:"GLOBAL_ATTRIBUTE7" AS GLOBAL_ATTRIBUTE7
,DATA:"GLOBAL_ATTRIBUTE8" AS GLOBAL_ATTRIBUTE8
,DATA:"GLOBAL_ATTRIBUTE9" AS GLOBAL_ATTRIBUTE9
,DATA:"GLOBAL_ATTRIBUTE10" AS GLOBAL_ATTRIBUTE10
,DATA:"GLOBAL_ATTRIBUTE11" AS GLOBAL_ATTRIBUTE11
,DATA:"GLOBAL_ATTRIBUTE12" AS GLOBAL_ATTRIBUTE12
,DATA:"GLOBAL_ATTRIBUTE13" AS GLOBAL_ATTRIBUTE13
,DATA:"GLOBAL_ATTRIBUTE14" AS GLOBAL_ATTRIBUTE14
,DATA:"GLOBAL_ATTRIBUTE15" AS GLOBAL_ATTRIBUTE15
,DATA:"GLOBAL_ATTRIBUTE16" AS GLOBAL_ATTRIBUTE16
,DATA:"GLOBAL_ATTRIBUTE17" AS GLOBAL_ATTRIBUTE17
,DATA:"GLOBAL_ATTRIBUTE18" AS GLOBAL_ATTRIBUTE18
,DATA:"GLOBAL_ATTRIBUTE19" AS GLOBAL_ATTRIBUTE19
,DATA:"GLOBAL_ATTRIBUTE20" AS GLOBAL_ATTRIBUTE20
,DATA:"ORIG_SYSTEM_REFERENCE" AS ORIG_SYSTEM_REFERENCE
,DATA:"SIC_CODE" AS SIC_CODE
,DATA:"HQ_BRANCH_IND" AS HQ_BRANCH_IND
,DATA:"CUSTOMER_KEY" AS CUSTOMER_KEY
,DATA:"TAX_REFERENCE" AS TAX_REFERENCE
,DATA:"JGZZ_FISCAL_CODE" AS JGZZ_FISCAL_CODE
,DATA:"DUNS_NUMBER" AS DUNS_NUMBER
,DATA:"TAX_NAME" AS TAX_NAME
,DATA:"PERSON_PRE_NAME_ADJUNCT" AS PERSON_PRE_NAME_ADJUNCT
,DATA:"PERSON_FIRST_NAME" AS PERSON_FIRST_NAME
,DATA:"PERSON_MIDDLE_NAME" AS PERSON_MIDDLE_NAME
,DATA:"PERSON_LAST_NAME" AS PERSON_LAST_NAME
,DATA:"PERSON_NAME_SUFFIX" AS PERSON_NAME_SUFFIX
,DATA:"PERSON_TITLE" AS PERSON_TITLE
,DATA:"PERSON_ACADEMIC_TITLE" AS PERSON_ACADEMIC_TITLE
,DATA:"PERSON_PREVIOUS_LAST_NAME" AS PERSON_PREVIOUS_LAST_NAME
,DATA:"KNOWN_AS" AS KNOWN_AS
,DATA:"PERSON_IDEN_TYPE" AS PERSON_IDEN_TYPE
,DATA:"PERSON_IDENTIFIER" AS PERSON_IDENTIFIER
,DATA:"GROUP_TYPE" AS GROUP_TYPE
,DATA:"COUNTRY" AS COUNTRY
,DATA:"ADDRESS1" AS ADDRESS1
,DATA:"ADDRESS2" AS ADDRESS2
,DATA:"ADDRESS3" AS ADDRESS3
,DATA:"ADDRESS4" AS ADDRESS4
,DATA:"CITY" AS CITY
,DATA:"POSTAL_CODE" AS POSTAL_CODE
,DATA:"STATE" AS STATE
,DATA:"PROVINCE" AS PROVINCE
,DATA:"STATUS" AS STATUS
,DATA:"COUNTY" AS COUNTY
,DATA:"SIC_CODE_TYPE" AS SIC_CODE_TYPE
,DATA:"TOTAL_NUM_OF_ORDERS" AS TOTAL_NUM_OF_ORDERS
,DATA:"TOTAL_ORDERED_AMOUNT" AS TOTAL_ORDERED_AMOUNT
,DATA:"LAST_ORDERED_DATE" AS LAST_ORDERED_DATE
,DATA:"URL" AS URL
,DATA:"EMAIL_ADDRESS" AS EMAIL_ADDRESS
,DATA:"DO_NOT_MAIL_FLAG" AS DO_NOT_MAIL_FLAG
,DATA:"ANALYSIS_FY" AS ANALYSIS_FY
,DATA:"FISCAL_YEAREND_MONTH" AS FISCAL_YEAREND_MONTH
,DATA:"EMPLOYEES_TOTAL" AS EMPLOYEES_TOTAL
,DATA:"CURR_FY_POTENTIAL_REVENUE" AS CURR_FY_POTENTIAL_REVENUE
,DATA:"NEXT_FY_POTENTIAL_REVENUE" AS NEXT_FY_POTENTIAL_REVENUE
,DATA:"YEAR_ESTABLISHED" AS YEAR_ESTABLISHED
,DATA:"GSA_INDICATOR_FLAG" AS GSA_INDICATOR_FLAG
,DATA:"MISSION_STATEMENT" AS MISSION_STATEMENT
,DATA:"ORGANIZATION_NAME_PHONETIC" AS ORGANIZATION_NAME_PHONETIC
,DATA:"PERSON_FIRST_NAME_PHONETIC" AS PERSON_FIRST_NAME_PHONETIC
,DATA:"PERSON_LAST_NAME_PHONETIC" AS PERSON_LAST_NAME_PHONETIC
,DATA:"LANGUAGE_NAME" AS LANGUAGE_NAME
,DATA:"CATEGORY_CODE" AS CATEGORY_CODE
,DATA:"REFERENCE_USE_FLAG" AS REFERENCE_USE_FLAG
,DATA:"THIRD_PARTY_FLAG" AS THIRD_PARTY_FLAG
,DATA:"COMPETITOR_FLAG" AS COMPETITOR_FLAG
,DATA:"SALUTATION" AS SALUTATION
,DATA:"KNOWN_AS2" AS KNOWN_AS2
,DATA:"KNOWN_AS3" AS KNOWN_AS3
,DATA:"KNOWN_AS4" AS KNOWN_AS4
,DATA:"KNOWN_AS5" AS KNOWN_AS5
,DATA:"DUNS_NUMBER_C" AS DUNS_NUMBER_C
,DATA:"OBJECT_VERSION_NUMBER" AS OBJECT_VERSION_NUMBER
,DATA:"CREATED_BY_MODULE" AS CREATED_BY_MODULE
,DATA:"APPLICATION_ID" AS APPLICATION_ID
,DATA:"PRIMARY_PHONE_CONTACT_PT_ID" AS PRIMARY_PHONE_CONTACT_PT_ID
,DATA:"PRIMARY_PHONE_PURPOSE" AS PRIMARY_PHONE_PURPOSE
,DATA:"PRIMARY_PHONE_LINE_TYPE" AS PRIMARY_PHONE_LINE_TYPE
,DATA:"PRIMARY_PHONE_COUNTRY_CODE" AS PRIMARY_PHONE_COUNTRY_CODE
,DATA:"PRIMARY_PHONE_AREA_CODE" AS PRIMARY_PHONE_AREA_CODE
,DATA:"PRIMARY_PHONE_NUMBER" AS PRIMARY_PHONE_NUMBER
,DATA:"PRIMARY_PHONE_EXTENSION" AS PRIMARY_PHONE_EXTENSION
,DATA:"CERTIFICATION_LEVEL" AS CERTIFICATION_LEVEL
,DATA:"CERT_REASON_CODE" AS CERT_REASON_CODE
,DATA:"PREFERRED_CONTACT_METHOD" AS PREFERRED_CONTACT_METHOD
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM 
 {{ source("landing_ebs", "HZ_PARTIES")}}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM 
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM 
                  {{ source("landing_ebs", "HZ_PARTIES")}}
                    
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )