{{
  config(
    materialized = "view",
    alias = "cm50_po_supplier",
    schema='EBS'
  )
}}


SELECT 
DATA:POV_ALLOW_AWT_FLAG               AS POV_ALLOW_AWT_FLAG
,DATA:POV_ALLOW_SUB_RECEIPTS_FLAG     AS POV_ALLOW_SUB_RECEIPTS_FLAG
,DATA:POV_ALLOW_UNORDERED_REC_FLAG    AS POV_ALLOW_UNORDERED_REC_FLAG
,DATA:POV_ALWAYS_TAKE_DISC_FLAG       AS POV_ALWAYS_TAKE_DISC_FLAG
,DATA:POV_AMOUNT_INCLUDES_TAX_FLAG    AS POV_AMOUNT_INCLUDES_TAX_FLAG
,DATA:POV_AP_TAX_ROUNDING_RULE        AS POV_AP_TAX_ROUNDING_RULE
,DATA:POV_ATTRIBUTE1                  AS POV_ATTRIBUTE1
,DATA:POV_AUTO_CALCULATE_INT_FLAG     AS POV_AUTO_CALCULATE_INT_FLAG
,DATA:POV_AUTO_TAX_CALC_FLAG          AS POV_AUTO_TAX_CALC_FLAG
,DATA:POV_AUTO_TAX_CALC_OVERRIDE      AS POV_AUTO_TAX_CALC_OVERRIDE
,DATA:POV_BANK_ACCOUNT_NAME           AS POV_BANK_ACCOUNT_NAME
,DATA:POV_BANK_ACCOUNT_NUM            AS POV_BANK_ACCOUNT_NUM
,DATA:POV_BANK_ACCOUNT_TYPE           AS POV_BANK_ACCOUNT_TYPE
,DATA:POV_BANK_CHARGE_BEARER          AS POV_BANK_CHARGE_BEARER
,DATA:POV_BANK_NUM                    AS POV_BANK_NUM
,DATA:POV_BANK_NUMBER                 AS POV_BANK_NUMBER
,DATA:POV_BILL_TO_LOCATION_ID         AS POV_BILL_TO_LOCATION_ID
,DATA:POV_CREATED_BY                  AS POV_CREATED_BY
,DATA:POV_CREATE_DEBIT_MEMO_FLAG      AS POV_CREATE_DEBIT_MEMO_FLAG
,DATA:POV_CREATION_DATE               AS POV_CREATION_DATE
,DATA:POV_DAYS_EARLY_RECEIPT_ALLOWED  AS POV_DAYS_EARLY_RECEIPT_ALLOWED
,DATA:POV_DAYS_LATE_RECEIPT_ALLOWED   AS POV_DAYS_LATE_RECEIPT_ALLOWED
,DATA:POV_EMPLOYEE_ID                 AS POV_EMPLOYEE_ID
,DATA:POV_ENABLED_FLAG                AS POV_ENABLED_FLAG
,DATA:POV_END_DATE_ACTIVE             AS POV_END_DATE_ACTIVE
,DATA:POV_ENFORCE_SHIP_TO_LOC_CODE    AS POV_ENFORCE_SHIP_TO_LOC_CODE
,DATA:POV_EXCLUSIVE_PAYMENT_FLAG      AS POV_EXCLUSIVE_PAYMENT_FLAG
,DATA:POV_EXCLU_FREIGHT_FR_DISCOUNT   AS POV_EXCLU_FREIGHT_FR_DISCOUNT
,DATA:POV_FEDERAL_REPORTABLE_FLAG     AS POV_FEDERAL_REPORTABLE_FLAG
,DATA:POV_HOLD_ALL_PAYMENTS_FLAG      AS POV_HOLD_ALL_PAYMENTS_FLAG
,DATA:POV_HOLD_FLAG                   AS POV_HOLD_FLAG
,DATA:POV_HOLD_FUTURE_PAYMENTS_FLAG   AS POV_HOLD_FUTURE_PAYMENTS_FLAG
,DATA:POV_HOLD_REASON                 AS POV_HOLD_REASON
,DATA:POV_HOLD_UNMATCHED_INV_FLAG     AS POV_HOLD_UNMATCHED_INV_FLAG
,DATA:POV_INDIVIDUAL_1099             AS POV_INDIVIDUAL_1099
,DATA:POV_INSPECTION_REQUIRED_FLAG    AS POV_INSPECTION_REQUIRED_FLAG
,DATA:POV_INVOICE_CURRENCY_CODE       AS POV_INVOICE_CURRENCY_CODE
,DATA:POV_LAST_UPDATED_BY             AS POV_LAST_UPDATED_BY
,DATA:POV_LAST_UPDATE_DATE            AS POV_LAST_UPDATE_DATE
,DATA:POV_LAST_UPDATE_LOGIN           AS POV_LAST_UPDATE_LOGIN
,DATA:POV_MATCH_OPTION                AS POV_MATCH_OPTION
,DATA:POV_NATURE_OF_SUPPLIER          AS POV_NATURE_OF_SUPPLIER
,DATA:POV_NUM_1099                    AS POV_NUM_1099
,DATA:POV_OFFSET_TAX_FLAG             AS POV_OFFSET_TAX_FLAG
,DATA:POV_ONE_TIME_FLAG               AS POV_ONE_TIME_FLAG
,DATA:POV_ORG_TYPE_LOOKUP_CODE        AS POV_ORG_TYPE_LOOKUP_CODE
,DATA:POV_PARENT_VENDOR_ID            AS POV_PARENT_VENDOR_ID
,DATA:POV_PAYMENT_CURRENCY_CODE       AS POV_PAYMENT_CURRENCY_CODE
,DATA:POV_PAYMENT_METHOD_LOOKUP_CODE  AS POV_PAYMENT_METHOD_LOOKUP_CODE
,DATA:POV_PAYMENT_PRIORITY            AS POV_PAYMENT_PRIORITY
,DATA:POV_PAY_DATE_BASIS_LOOKUP_CODE  AS POV_PAY_DATE_BASIS_LOOKUP_CODE
,DATA:POV_PAY_GROUP_LOOKUP_CODE       AS POV_PAY_GROUP_LOOKUP_CODE
,DATA:POV_QTY_RCV_EXCEPTION_CODE      AS POV_QTY_RCV_EXCEPTION_CODE
,DATA:POV_QTY_RCV_TOLERANCE           AS POV_QTY_RCV_TOLERANCE
,DATA:POV_RECEIPT_DAYS_EX_CODE        AS POV_RECEIPT_DAYS_EX_CODE
,DATA:POV_RECEIPT_REQUIRED_FLAG       AS POV_RECEIPT_REQUIRED_FLAG
,DATA:POV_RECEIVING_ROUTING_ID        AS POV_RECEIVING_ROUTING_ID
,DATA:POV_SET_OF_BOOKS_ID             AS POV_SET_OF_BOOKS_ID
,DATA:POV_SMALL_BUSINESS_FLAG         AS POV_SMALL_BUSINESS_FLAG
,DATA:POV_START_DATE_ACTIVE           AS POV_START_DATE_ACTIVE
,DATA:POV_STATE_REPORTABLE_FLAG       AS POV_STATE_REPORTABLE_FLAG
,DATA:POV_SUMMARY_FLAG                AS POV_SUMMARY_FLAG
,DATA:POV_TAX_REPORTING_NAME          AS POV_TAX_REPORTING_NAME
,DATA:POV_TAX_VERIFICATION_DATE       AS POV_TAX_VERIFICATION_DATE
,DATA:POV_TERMS_DATE_BASIS            AS POV_TERMS_DATE_BASIS
,DATA:POV_TERMS_ID                    AS POV_TERMS_ID
,DATA:POV_TYPE_1099                   AS POV_TYPE_1099
,DATA:POV_VAT_REGISTRATION_NUM        AS POV_VAT_REGISTRATION_NUM
,DATA:POV_VENDOR_ID                   AS POV_VENDOR_ID
,DATA:POV_VENDOR_NAME                 AS POV_VENDOR_NAME
,DATA:POV_VENDOR_NAME_ALT             AS POV_VENDOR_NAME_ALT
,DATA:POV_VENDOR_NUMBER               AS POV_VENDOR_NUMBER
,DATA:POV_VENDOR_TYPE_LOOKUP_CODE     AS POV_VENDOR_TYPE_LOOKUP_CODE
,DATA:POV_WOMEN_OWNED_FLAG            AS POV_WOMEN_OWNED_FLAG
,DATA:src_system_operation            AS src_system_operation
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
from {{ source("landing_ebs", "CM50_PO_SUPPLIER") }}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM
                    {{ source("landing_ebs", "CM50_PO_SUPPLIER") }}
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )