{{
  config(
    materialized = "view",
    alias = "bom_resource_employees",
    schema='EBS'
  )
}}

SELECT 
    DATA:RESOURCE_ID AS RESOURCE_ID
   ,DATA:ORGANIZATION_ID AS ORGANIZATION_ID
   ,DATA:PERSON_ID AS PERSON_ID
   ,DATA:EFFECTIVE_START_DATE AS EFFECTIVE_START_DATE
   ,DATA:EFFECTIVE_END_DATE AS EFFECTIVE_END_DATE
   ,DATA:INTERLEAVE AS INTERLEAVE
   ,DATA:LAST_UPDATE_DATE AS LAST_UPDATE_DATE
   ,DATA:LAST_UPDATED_BY AS LAST_UPDATED_BY
   ,DATA:CREATION_DATE AS CREATION_DATE
   ,DATA:CREATED_BY AS CREATED_BY
   ,DATA:LAST_UPDATE_LOGIN AS LAST_UPDATE_LOGIN
   ,DATA:ATTRIBUTE_CATEGORY AS ATTRIBUTE_CATEGORY
   ,DATA:ATTRIBUTE1 AS ATTRIBUTE1
   ,DATA:ATTRIBUTE2 AS ATTRIBUTE2
   ,DATA:ATTRIBUTE3 AS ATTRIBUTE3
   ,DATA:ATTRIBUTE4 AS ATTRIBUTE4
   ,DATA:ATTRIBUTE5 AS ATTRIBUTE5
   ,DATA:ATTRIBUTE6 AS ATTRIBUTE6
   ,DATA:ATTRIBUTE7 AS ATTRIBUTE7
   ,DATA:ATTRIBUTE8 AS ATTRIBUTE8
   ,DATA:ATTRIBUTE9 AS ATTRIBUTE9
   ,DATA:ATTRIBUTE10 AS ATTRIBUTE10
   ,DATA:ATTRIBUTE11 AS ATTRIBUTE11
   ,DATA:ATTRIBUTE12 AS ATTRIBUTE12
   ,DATA:ATTRIBUTE13 AS ATTRIBUTE13
   ,DATA:ATTRIBUTE14 AS ATTRIBUTE14
   ,DATA:ATTRIBUTE15 AS ATTRIBUTE15
   ,DATA:REQUEST_ID AS REQUEST_ID
   ,DATA:PROGRAM_APPLICATION_ID AS PROGRAM_APPLICATION_ID
   ,DATA:PROGRAM_ID AS PROGRAM_ID
   ,DATA:PROGRAM_UPDATE_DATE AS PROGRAM_UPDATE_DATE
   ,DATA:INSTANCE_ID AS INSTANCE_ID
   ,FILENAME                             AS METADATA_FILENAME 
   ,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
   ,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
   ,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME

FROM {{ source("landing_ebs", "BOM_RESOURCE_EMPLOYEES") }}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM 
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM 
                  {{ source("landing_ebs", "BOM_RESOURCE_EMPLOYEES")}}
                    
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )
         