{{
  config(
    materialized = "view",
    alias = "cmg_pa_shipped_quantities",
    schema='ebs'
  )
}}

SELECT
DATA:CREATED_BY AS CREATED_BY
,DATA:CREATION_DATE AS CREATION_DATE
,DATA:LAST_UPDATED_BY AS LAST_UPDATED_BY
,DATA:LAST_UPDATE_DATE AS LAST_UPDATE_DATE
,DATA:LAST_UPDATE_LOGIN AS LAST_UPDATE_LOGIN
,DATA:PROJECT_ID AS PROJECT_ID
,DATA:TASK_ID AS TASK_ID
,DATA:ORG_ID AS ORG_ID
,DATA:ORGANIZATION_ID AS ORGANIZATION_ID
,DATA:TASK_FAMILY AS TASK_FAMILY
,DATA:TRANSACTION_DATE AS TRANSACTION_DATE
,DATA:SHIPPED_QUANTITY AS SHIPPED_QUANTITY
,DATA:SHIPPED_UNITS AS SHIPPED_UNITS
,DATA:SHIPPED_UOM AS SHIPPED_UOM
,DATA:BILL_OF_LADING_NUMBER AS BILL_OF_LADING_NUMBER
,DATA:BILL_OF_LADING_DATE AS BILL_OF_LADING_DATE
,DATA:FOB AS FOB
,DATA:FOB_DESCRIPTION AS FOB_DESCRIPTION
,DATA:SHIP_VIA AS SHIP_VIA
,DATA:SHIP_VIA_DESCRIPTION AS SHIP_VIA_DESCRIPTION
,DATA:SHIPPED_QUANTITY_NOT_NAFTA AS SHIPPED_QUANTITY_NOT_NAFTA
,DATA:EVENT_FLAG AS EVENT_FLAG
,DATA:NON_NAFTA_ORIGIN AS NON_NAFTA_ORIGIN
,DATA:DESCRIPTION AS DESCRIPTION
,DATA:BACKORDER_QUANTITY AS BACKORDER_QUANTITY
,DATA:ORDERED_QUANTITY AS ORDERED_QUANTITY
,DATA:COMMENTS AS COMMENTS
,DATA:COMMENT_BOTTOM AS COMMENT_BOTTOM
,DATA:ADDRESS1 AS ADDRESS1
,DATA:ADDRESS2 AS ADDRESS2
,DATA:CITY AS CITY
,DATA:STATE_PROVINCE AS STATE_PROVINCE
,DATA:POSTAL_CODE AS POSTAL_CODE
,DATA:INVOICE_AMOUNT AS INVOICE_AMOUNT
,DATA:QUANTITY_TYPE AS QUANTITY_TYPE
,DATA:SHOP_BOLT_SHIP_QTY AS SHOP_BOLT_SHIP_QTY
,DATA:SHOP_BOLT_SHIP_UNITS AS SHOP_BOLT_SHIP_UNITS
,DATA:SHOP_BOLT_SHIP_QTY_NOT_NAFTA AS SHOP_BOLT_SHIP_QTY_NOT_NAFTA
,DATA:STRUMIS_DELIVERY_NOTE AS STRUMIS_DELIVERY_NOTE
,DATA:ORIGINAL_TASK_NUMBER AS ORIGINAL_TASK_NUMBER
,DATA:CUSTOMS_DESCRIPTION AS CUSTOMS_DESCRIPTION
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM 
 {{ source("landing_ebs", "CMG_PA_SHIPPED_QUANTITIES")}}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM 
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM 
                  {{ source("landing_ebs", "CMG_PA_SHIPPED_QUANTITIES")}}
                    
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )