{{
  config(
    materialized = "view",
    alias = "pa_expenditure_types",
    schema='EBS'
  )
}}

SELECT 
 DATA:EXPENDITURE_TYPE AS EXPENDITURE_TYPE
,DATA:LAST_UPDATE_DATE AS LAST_UPDATE_DATE
,DATA:LAST_UPDATED_BY AS LAST_UPDATED_BY
,DATA:CREATION_DATE AS CREATION_DATE
,DATA:CREATED_BY AS CREATED_BY
,DATA:LAST_UPDATE_LOGIN AS LAST_UPDATE_LOGIN
,DATA:EXPENDITURE_CATEGORY AS EXPENDITURE_CATEGORY
,DATA:REVENUE_CATEGORY_CODE AS REVENUE_CATEGORY_CODE
,DATA:SYSTEM_LINKAGE_FUNCTION AS SYSTEM_LINKAGE_FUNCTION
,DATA:UNIT_OF_MEASURE AS UNIT_OF_MEASURE
,DATA:START_DATE_ACTIVE AS START_DATE_ACTIVE
,DATA:COST_RATE_FLAG AS COST_RATE_FLAG
,DATA:END_DATE_ACTIVE AS END_DATE_ACTIVE
,DATA:DESCRIPTION AS DESCRIPTION
,DATA:ATTRIBUTE_CATEGORY AS ATTRIBUTE_CATEGORY
,DATA:ATTRIBUTE1 AS ATTRIBUTE1
,DATA:ATTRIBUTE2 AS ATTRIBUTE2
,DATA:ATTRIBUTE3 AS ATTRIBUTE3
,DATA:ATTRIBUTE4 AS ATTRIBUTE4
,DATA:ATTRIBUTE5 AS ATTRIBUTE5
,DATA:ATTRIBUTE6 AS ATTRIBUTE6
,DATA:ATTRIBUTE7 AS ATTRIBUTE7
,DATA:ATTRIBUTE8 AS ATTRIBUTE8
,DATA:ATTRIBUTE9 AS ATTRIBUTE9
,DATA:ATTRIBUTE10 AS ATTRIBUTE10
,DATA:ATTRIBUTE11 AS ATTRIBUTE11
,DATA:ATTRIBUTE12 AS ATTRIBUTE12
,DATA:ATTRIBUTE13 AS ATTRIBUTE13
,DATA:ATTRIBUTE14 AS ATTRIBUTE14
,DATA:ATTRIBUTE15 AS ATTRIBUTE15
,DATA:ADW_NOTIFY_FLAG AS ADW_NOTIFY_FLAG
,DATA:EXPENDITURE_TYPE_ID AS EXPENDITURE_TYPE_ID
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
    from 
    {{ source("landing_ebs", "PA_EXPENDITURE_TYPES") }}
    WHERE
        split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
            SELECT
                min_timestamp
            FROM
                (
                    SELECT
                        split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                        split(FILENAME, '/') [3] AS type_file
                    FROM
                        {{ source("landing_ebs", "PA_EXPENDITURE_TYPES") }}
                    WHERE
                        type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                            ORDER BY
                                min_timestamp DESC
                        ) = 1
                )
            )