{{
  config(
    materialized = "view",
    alias = "po_vendors",
    schema='EBS'
  )
}}

SELECT
 DATA:LAST_UPDATE_DATE AS LAST_UPDATE_DATE
,DATA:VENDOR_ID AS VENDOR_ID
,DATA:GLOBAL_ATTRIBUTE5 AS GLOBAL_ATTRIBUTE5
,DATA:GLOBAL_ATTRIBUTE4 AS GLOBAL_ATTRIBUTE4
,DATA:GLOBAL_ATTRIBUTE3 AS GLOBAL_ATTRIBUTE3
,DATA:GLOBAL_ATTRIBUTE2 AS GLOBAL_ATTRIBUTE2
,DATA:GLOBAL_ATTRIBUTE1 AS GLOBAL_ATTRIBUTE1
,DATA:AWT_GROUP_ID AS AWT_GROUP_ID
,DATA:ALLOW_AWT_FLAG AS ALLOW_AWT_FLAG
,DATA:CHECK_DIGITS AS CHECK_DIGITS
,DATA:TAX_REPORTING_NAME AS TAX_REPORTING_NAME
,DATA:EXCLUDE_FREIGHT_FROM_DISCOUNT AS EXCLUDE_FREIGHT_FROM_DISCOUNT
,DATA:AUTO_CALCULATE_INTEREST_FLAG AS AUTO_CALCULATE_INTEREST_FLAG
,DATA:OFFSET_VAT_CODE AS OFFSET_VAT_CODE
,DATA:PROGRAM_UPDATE_DATE AS PROGRAM_UPDATE_DATE
,DATA:PROGRAM_ID AS PROGRAM_ID
,DATA:PROGRAM_APPLICATION_ID AS PROGRAM_APPLICATION_ID
,DATA:REQUEST_ID AS REQUEST_ID
,DATA:ATTRIBUTE15 AS ATTRIBUTE15
,DATA:ATTRIBUTE14 AS ATTRIBUTE14
,DATA:ATTRIBUTE13 AS ATTRIBUTE13
,DATA:ATTRIBUTE12 AS ATTRIBUTE12
,DATA:ATTRIBUTE11 AS ATTRIBUTE11
,DATA:ATTRIBUTE10 AS ATTRIBUTE10
,DATA:ATTRIBUTE9 AS ATTRIBUTE9
,DATA:ATTRIBUTE8 AS ATTRIBUTE8
,DATA:ATTRIBUTE7 AS ATTRIBUTE7
,DATA:ATTRIBUTE6 AS ATTRIBUTE6
,DATA:ATTRIBUTE5 AS ATTRIBUTE5
,DATA:ATTRIBUTE3 AS ATTRIBUTE3
,DATA:ATTRIBUTE2 AS ATTRIBUTE2
,DATA:ATTRIBUTE1 AS ATTRIBUTE1
,DATA:ATTRIBUTE_CATEGORY AS ATTRIBUTE_CATEGORY
,DATA:FEDERAL_REPORTABLE_FLAG AS FEDERAL_REPORTABLE_FLAG
,DATA:STATE_REPORTABLE_FLAG AS STATE_REPORTABLE_FLAG
,DATA:NAME_CONTROL AS NAME_CONTROL
,DATA:TAX_VERIFICATION_DATE AS TAX_VERIFICATION_DATE
,DATA:AMOUNT_INCLUDES_TAX_FLAG AS AMOUNT_INCLUDES_TAX_FLAG
,DATA:AUTO_TAX_CALC_OVERRIDE AS AUTO_TAX_CALC_OVERRIDE
,DATA:AUTO_TAX_CALC_FLAG AS AUTO_TAX_CALC_FLAG
,DATA:AP_TAX_ROUNDING_RULE AS AP_TAX_ROUNDING_RULE
,DATA:EXCLUSIVE_PAYMENT_FLAG AS EXCLUSIVE_PAYMENT_FLAG
,DATA:HOLD_UNMATCHED_INVOICES_FLAG AS HOLD_UNMATCHED_INVOICES_FLAG
,DATA:ALLOW_UNORDERED_RECEIPTS_FLAG AS ALLOW_UNORDERED_RECEIPTS_FLAG
,DATA:ALLOW_SUBSTITUTE_RECEIPTS_FLAG AS ALLOW_SUBSTITUTE_RECEIPTS_FLAG
,DATA:RECEIVING_ROUTING_ID AS RECEIVING_ROUTING_ID
,DATA:RECEIPT_DAYS_EXCEPTION_CODE AS RECEIPT_DAYS_EXCEPTION_CODE
,DATA:DAYS_LATE_RECEIPT_ALLOWED AS DAYS_LATE_RECEIPT_ALLOWED
,DATA:DAYS_EARLY_RECEIPT_ALLOWED AS DAYS_EARLY_RECEIPT_ALLOWED
,DATA:ENFORCE_SHIP_TO_LOCATION_CODE AS ENFORCE_SHIP_TO_LOCATION_CODE
,DATA:QTY_RCV_EXCEPTION_CODE AS QTY_RCV_EXCEPTION_CODE
,DATA:QTY_RCV_TOLERANCE AS QTY_RCV_TOLERANCE
,DATA:RECEIPT_REQUIRED_FLAG AS RECEIPT_REQUIRED_FLAG
,DATA:PRICE_TOLERANCE AS PRICE_TOLERANCE
,DATA:TERMS_DATE_BASIS AS TERMS_DATE_BASIS
,DATA:HOLD_DATE AS HOLD_DATE
,DATA:HOLD_BY AS HOLD_BY
,DATA:PURCHASING_HOLD_REASON AS PURCHASING_HOLD_REASON
,DATA:HOLD_FLAG AS HOLD_FLAG
,DATA:STANDARD_INDUSTRY_CLASS AS STANDARD_INDUSTRY_CLASS
,DATA:SMALL_BUSINESS_FLAG AS SMALL_BUSINESS_FLAG
,DATA:WOMEN_OWNED_FLAG AS WOMEN_OWNED_FLAG
,DATA:BANK_ACCOUNT_TYPE AS BANK_ACCOUNT_TYPE
,DATA:BANK_NUM AS BANK_NUM
,DATA:BANK_ACCOUNT_NUM AS BANK_ACCOUNT_NUM
,DATA:BANK_ACCOUNT_NAME AS BANK_ACCOUNT_NAME
,DATA:PAYMENT_METHOD_LOOKUP_CODE AS PAYMENT_METHOD_LOOKUP_CODE
,DATA:MINORITY_GROUP_LOOKUP_CODE AS MINORITY_GROUP_LOOKUP_CODE
,DATA:END_DATE_ACTIVE AS END_DATE_ACTIVE
,DATA:START_DATE_ACTIVE AS START_DATE_ACTIVE
,DATA:VAT_CODE AS VAT_CODE
,DATA:ORGANIZATION_TYPE_LOOKUP_CODE AS ORGANIZATION_TYPE_LOOKUP_CODE
,DATA:WITHHOLDING_START_DATE AS WITHHOLDING_START_DATE
,DATA:WITHHOLDING_STATUS_LOOKUP_CODE AS WITHHOLDING_STATUS_LOOKUP_CODE
,DATA:TYPE_1099 AS TYPE_1099
,DATA:NUM_1099 AS NUM_1099
,DATA:PREPAY_CODE_COMBINATION_ID AS PREPAY_CODE_COMBINATION_ID
,DATA:EXPENSE_CODE_COMBINATION_ID AS EXPENSE_CODE_COMBINATION_ID
,DATA:DISC_TAKEN_CODE_COMBINATION_ID AS DISC_TAKEN_CODE_COMBINATION_ID
,DATA:DISC_LOST_CODE_COMBINATION_ID AS DISC_LOST_CODE_COMBINATION_ID
,DATA:ACCTS_PAY_CODE_COMBINATION_ID AS ACCTS_PAY_CODE_COMBINATION_ID
,DATA:DISTRIBUTION_SET_ID AS DISTRIBUTION_SET_ID
,DATA:HOLD_REASON AS HOLD_REASON
,DATA:HOLD_FUTURE_PAYMENTS_FLAG AS HOLD_FUTURE_PAYMENTS_FLAG
,DATA:EXCHANGE_DATE_LOOKUP_CODE AS EXCHANGE_DATE_LOOKUP_CODE
,DATA:INVOICE_AMOUNT_LIMIT AS INVOICE_AMOUNT_LIMIT
,DATA:PAYMENT_CURRENCY_CODE AS PAYMENT_CURRENCY_CODE
,DATA:INVOICE_CURRENCY_CODE AS INVOICE_CURRENCY_CODE
,DATA:PAYMENT_PRIORITY AS PAYMENT_PRIORITY
,DATA:PAY_GROUP_LOOKUP_CODE AS PAY_GROUP_LOOKUP_CODE
,DATA:PAY_DATE_BASIS_LOOKUP_CODE AS PAY_DATE_BASIS_LOOKUP_CODE
,DATA:ALWAYS_TAKE_DISC_FLAG AS ALWAYS_TAKE_DISC_FLAG
,DATA:CREDIT_STATUS_LOOKUP_CODE AS CREDIT_STATUS_LOOKUP_CODE
,DATA:SET_OF_BOOKS_ID AS SET_OF_BOOKS_ID
,DATA:TERMS_ID AS TERMS_ID
,DATA:FOB_LOOKUP_CODE AS FOB_LOOKUP_CODE
,DATA:FREIGHT_TERMS_LOOKUP_CODE AS FREIGHT_TERMS_LOOKUP_CODE
,DATA:SHIP_VIA_LOOKUP_CODE AS SHIP_VIA_LOOKUP_CODE
,DATA:BILL_TO_LOCATION_ID AS BILL_TO_LOCATION_ID
,DATA:SHIP_TO_LOCATION_ID AS SHIP_TO_LOCATION_ID
,DATA:MIN_ORDER_AMOUNT AS MIN_ORDER_AMOUNT
,DATA:PARENT_VENDOR_ID AS PARENT_VENDOR_ID
,DATA:ONE_TIME_FLAG AS ONE_TIME_FLAG
,DATA:CUSTOMER_NUM AS CUSTOMER_NUM
,DATA:VENDOR_TYPE_LOOKUP_CODE AS VENDOR_TYPE_LOOKUP_CODE
,DATA:EMPLOYEE_ID AS EMPLOYEE_ID
,DATA:CREATED_BY AS CREATED_BY
,DATA:CREATION_DATE AS CREATION_DATE
,DATA:LAST_UPDATE_LOGIN AS LAST_UPDATE_LOGIN
,DATA:SEGMENT5 AS SEGMENT5
,DATA:SEGMENT4 AS SEGMENT4
,DATA:SEGMENT2 AS SEGMENT2
,DATA:ENABLED_FLAG AS ENABLED_FLAG
,DATA:SUMMARY_FLAG AS SUMMARY_FLAG
,DATA:SEGMENT1 AS SEGMENT1
,DATA:VENDOR_NAME_ALT AS VENDOR_NAME_ALT
,DATA:VENDOR_NAME AS VENDOR_NAME
,DATA:LAST_UPDATED_BY AS LAST_UPDATED_BY
,DATA:BANK_BRANCH_TYPE AS BANK_BRANCH_TYPE
,DATA:BANK_CHARGE_BEARER AS BANK_CHARGE_BEARER
,DATA:EDI_REMITTANCE_INSTRUCTION AS EDI_REMITTANCE_INSTRUCTION
,DATA:EDI_REMITTANCE_METHOD AS EDI_REMITTANCE_METHOD
,DATA:EDI_PAYMENT_FORMAT AS EDI_PAYMENT_FORMAT
,DATA:EDI_PAYMENT_METHOD AS EDI_PAYMENT_METHOD
,DATA:EDI_TRANSACTION_HANDLING AS EDI_TRANSACTION_HANDLING
,DATA:GLOBAL_ATTRIBUTE_CATEGORY AS GLOBAL_ATTRIBUTE_CATEGORY
,DATA:GLOBAL_ATTRIBUTE20 AS GLOBAL_ATTRIBUTE20
,DATA:GLOBAL_ATTRIBUTE18 AS GLOBAL_ATTRIBUTE18
,DATA:GLOBAL_ATTRIBUTE17 AS GLOBAL_ATTRIBUTE17
,DATA:GLOBAL_ATTRIBUTE16 AS GLOBAL_ATTRIBUTE16
,DATA:GLOBAL_ATTRIBUTE15 AS GLOBAL_ATTRIBUTE15
,DATA:GLOBAL_ATTRIBUTE14 AS GLOBAL_ATTRIBUTE14
,DATA:GLOBAL_ATTRIBUTE13 AS GLOBAL_ATTRIBUTE13
,DATA:GLOBAL_ATTRIBUTE12 AS GLOBAL_ATTRIBUTE12
,DATA:GLOBAL_ATTRIBUTE11 AS GLOBAL_ATTRIBUTE11
,DATA:GLOBAL_ATTRIBUTE10 AS GLOBAL_ATTRIBUTE10
,DATA:GLOBAL_ATTRIBUTE9 AS GLOBAL_ATTRIBUTE9
,DATA:GLOBAL_ATTRIBUTE8 AS GLOBAL_ATTRIBUTE8
,DATA:GLOBAL_ATTRIBUTE7 AS GLOBAL_ATTRIBUTE7
,DATA:GLOBAL_ATTRIBUTE6 AS GLOBAL_ATTRIBUTE6
,DATA:GLOBAL_ATTRIBUTE19 AS GLOBAL_ATTRIBUTE19
,DATA:VAT_REGISTRATION_NUM AS VAT_REGISTRATION_NUM
,DATA:ATTRIBUTE4 AS ATTRIBUTE4
,DATA:INSPECTION_REQUIRED_FLAG AS INSPECTION_REQUIRED_FLAG
,DATA:HOLD_ALL_PAYMENTS_FLAG AS HOLD_ALL_PAYMENTS_FLAG
,DATA:SEGMENT3 AS SEGMENT3
,DATA:BANK_NUMBER AS BANK_NUMBER
,DATA:OFFSET_TAX_FLAG AS OFFSET_TAX_FLAG
,DATA:CREATE_DEBIT_MEMO_FLAG AS CREATE_DEBIT_MEMO_FLAG
,DATA:FUTURE_DATED_PAYMENT_CCID AS FUTURE_DATED_PAYMENT_CCID
,DATA:MATCH_OPTION AS MATCH_OPTION
,DATA:BUS_CLASS_LAST_CERTIFIED_BY AS BUS_CLASS_LAST_CERTIFIED_BY
,DATA:BUS_CLASS_LAST_CERTIFIED_DATE AS BUS_CLASS_LAST_CERTIFIED_DATE
,DATA:CIS_PARENT_VENDOR_ID AS CIS_PARENT_VENDOR_ID
,DATA:VALIDATION_NUMBER AS VALIDATION_NUMBER
,DATA:CREDIT_LIMIT AS CREDIT_LIMIT
,DATA:INDIVIDUAL_1099 AS INDIVIDUAL_1099
,DATA:CIS_VERIFICATION_DATE AS CIS_VERIFICATION_DATE
,DATA:MATCH_STATUS_FLAG AS MATCH_STATUS_FLAG
,DATA:VERIFICATION_REQUEST_ID AS VERIFICATION_REQUEST_ID
,DATA:VERIFICATION_NUMBER AS VERIFICATION_NUMBER
,DATA:NATIONAL_INSURANCE_NUMBER AS NATIONAL_INSURANCE_NUMBER
,DATA:COMPANY_REGISTRATION_NUMBER AS COMPANY_REGISTRATION_NUMBER
,DATA:WORK_REFERENCE AS WORK_REFERENCE
,DATA:TRADING_NAME AS TRADING_NAME
,DATA:SALUTATION AS SALUTATION
,DATA:LAST_NAME AS LAST_NAME
,DATA:SECOND_NAME AS SECOND_NAME
,DATA:FIRST_NAME AS FIRST_NAME
,DATA:CIS_ENABLED_FLAG AS CIS_ENABLED_FLAG
,DATA:PARTNERSHIP_NAME AS PARTNERSHIP_NAME
,DATA:PARTNERSHIP_UTR AS PARTNERSHIP_UTR
,DATA:UNIQUE_TAX_REFERENCE_NUM AS UNIQUE_TAX_REFERENCE_NUM
,FILENAME AS METADATA_FILENAME
,FILE_ROW_NUMBER AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME AS METADATA_START_SCAN_TIME
 FROM 
 {{ source("landing_ebs", "PO_VENDORS")}}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM 
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM 
                  {{ source("landing_ebs", "PO_VENDORS")}}
                    
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )
