{{
  config(
    materialized = "view",
    alias = "cm50_po_distributions",
    schema='EBS'
  )
}}

SELECT 
    DATA:"PDA_PO_DISTRIBUTION_ID" AS PDA_PO_DISTRIBUTION_ID
    ,DATA:"PDA_LAST_UPDATE_DATE" AS PDA_LAST_UPDATE_DATE
    ,DATA:"PDA_LAST_UPDATED_BY" AS PDA_LAST_UPDATED_BY
    ,DATA:"PDA_PO_HEADER_ID" AS PDA_PO_HEADER_ID
    ,DATA:"PDA_PO_LINE_ID" AS PDA_PO_LINE_ID
    ,DATA:"PDA_LINE_LOCATION_ID" AS PDA_LINE_LOCATION_ID
    ,DATA:"PDA_SET_OF_BOOKS_ID" AS PDA_SET_OF_BOOKS_ID
    ,DATA:"PDA_CODE_COMBINATION_ID" AS PDA_CODE_COMBINATION_ID
    ,DATA:"PDA_QUANTITY_ORDERED" AS PDA_QUANTITY_ORDERED
    ,DATA:"PDA_LAST_UPDATE_LOGIN" AS PDA_LAST_UPDATE_LOGIN
    ,DATA:"PDA_CREATION_DATE" AS PDA_CREATION_DATE
    ,DATA:"PDA_CREATED_BY" AS PDA_CREATED_BY
    ,DATA:"PDA_PO_RELEASE_ID" AS PDA_PO_RELEASE_ID
    ,DATA:"PDA_QUANTITY_DELIVERED" AS PDA_QUANTITY_DELIVERED
    ,DATA:"PDA_QUANTITY_BILLED" AS PDA_QUANTITY_BILLED
    ,DATA:"PDA_QUANTITY_CANCELLED" AS PDA_QUANTITY_CANCELLED
    ,DATA:"PDA_REQ_HEADER_REFERENCE_NUM" AS PDA_REQ_HEADER_REFERENCE_NUM
    ,DATA:"PDA_REQ_LINE_REFERENCE_NUM" AS PDA_REQ_LINE_REFERENCE_NUM
    ,DATA:"PDA_REQ_DISTRIBUTION_ID" AS PDA_REQ_DISTRIBUTION_ID
    ,DATA:"PDA_DELIVER_TO_LOCATION_ID" AS PDA_DELIVER_TO_LOCATION_ID
    ,DATA:"PDA_DELIVER_TO_PERSON_ID" AS PDA_DELIVER_TO_PERSON_ID
    ,DATA:"PDA_RATE_DATE" AS PDA_RATE_DATE
    ,DATA:"PDA_RATE" AS PDA_RATE
    ,DATA:"PDA_AMOUNT_BILLED" AS PDA_AMOUNT_BILLED
    ,DATA:"PDA_ACCRUED_FLAG" AS PDA_ACCRUED_FLAG
    ,DATA:"PDA_ENCUMBERED_FLAG" AS PDA_ENCUMBERED_FLAG
    ,DATA:"PDA_GL_ENCUMBERED_DATE" AS PDA_GL_ENCUMBERED_DATE
    ,DATA:"PDA_GL_ENCUMBERED_PERIOD_NAME" AS PDA_GL_ENCUMBERED_PERIOD_NAME
    ,DATA:"PDA_GL_CANCELLED_DATE" AS PDA_GL_CANCELLED_DATE
    ,DATA:"PDA_DESTINATION_TYPE_CODE" AS PDA_DESTINATION_TYPE_CODE
    ,DATA:"PDA_DESTINATION_ORG_ID" AS PDA_DESTINATION_ORG_ID
    ,DATA:"PDA_DESTINATION_SUBINVENTORY" AS PDA_DESTINATION_SUBINVENTORY
    ,DATA:"PDA_ATTRIBUTE_CATEGORY" AS PDA_ATTRIBUTE_CATEGORY
    ,DATA:"PDA_ATTRIBUTE1" AS PDA_ATTRIBUTE1
    ,DATA:"PDA_ATTRIBUTE2" AS PDA_ATTRIBUTE2
    ,DATA:"PDA_ATTRIBUTE3" AS PDA_ATTRIBUTE3
    ,DATA:"PDA_ATTRIBUTE4" AS PDA_ATTRIBUTE4
    ,DATA:"PDA_ATTRIBUTE5" AS PDA_ATTRIBUTE5
    ,DATA:"PDA_ATTRIBUTE6" AS PDA_ATTRIBUTE6
    ,DATA:"PDA_ATTRIBUTE7" AS PDA_ATTRIBUTE7
    ,DATA:"PDA_ATTRIBUTE8" AS PDA_ATTRIBUTE8
    ,DATA:"PDA_ATTRIBUTE9" AS PDA_ATTRIBUTE9
    ,DATA:"PDA_ATTRIBUTE10" AS PDA_ATTRIBUTE10
    ,DATA:"PDA_ATTRIBUTE11" AS PDA_ATTRIBUTE11
    ,DATA:"PDA_ATTRIBUTE13" AS PDA_ATTRIBUTE13
    ,DATA:"PDA_WIP_ENTITY_ID" AS PDA_WIP_ENTITY_ID
    ,DATA:"PDA_WIP_OPERATION_SEQ_NUM" AS PDA_WIP_OPERATION_SEQ_NUM
    ,DATA:"PDA_WIP_RESOURCE_SEQ_NUM" AS PDA_WIP_RESOURCE_SEQ_NUM
    ,DATA:"PDA_BUDGET_ACCOUNT_ID" AS PDA_BUDGET_ACCOUNT_ID
    ,DATA:"PDA_ACCRUAL_ACCOUNT_ID" AS PDA_ACCRUAL_ACCOUNT_ID
    ,DATA:"PDA_VARIANCE_ACCOUNT_ID" AS PDA_VARIANCE_ACCOUNT_ID
    ,DATA:"PDA_PREVENT_ENCUMBRANCE_FLAG" AS PDA_PREVENT_ENCUMBRANCE_FLAG
    ,DATA:"PDA_DESTINATION_CONTEXT" AS PDA_DESTINATION_CONTEXT
    ,DATA:"PDA_DISTRIBUTION_NUM" AS PDA_DISTRIBUTION_NUM
    ,DATA:"PDA_REQUEST_ID" AS PDA_REQUEST_ID
    ,DATA:"PDA_PROGRAM_APPLICATION_ID" AS PDA_PROGRAM_APPLICATION_ID
    ,DATA:"PDA_PROGRAM_ID" AS PDA_PROGRAM_ID
    ,DATA:"PDA_PROGRAM_UPDATE_DATE" AS PDA_PROGRAM_UPDATE_DATE
    ,DATA:"PDA_PROJECT_ID" AS PDA_PROJECT_ID
    ,DATA:"PDA_TASK_ID" AS PDA_TASK_ID
    ,DATA:"PDA_EXPENDITURE_TYPE" AS PDA_EXPENDITURE_TYPE
    ,DATA:"PDA_PROJECT_ACCOUNTING_CONTEXT" AS PDA_PROJECT_ACCOUNTING_CONTEXT
    ,DATA:"PDA_EXPENDITURE_ORG_ID" AS PDA_EXPENDITURE_ORG_ID
    ,DATA:"PDA_ACCRUE_ON_RECEIPT_FLAG" AS PDA_ACCRUE_ON_RECEIPT_FLAG
    ,DATA:"PDA_EXPENDITURE_ITEM_DATE" AS PDA_EXPENDITURE_ITEM_DATE
    ,DATA:"PDA_ORG_ID" AS PDA_ORG_ID
    ,DATA:"PDA_TAX_RECOVERY_OVERRIDE_FLAG" AS PDA_TAX_RECOVERY_OVERRIDE_FLAG
    ,DATA:"PDA_RECOVERABLE_TAX" AS PDA_RECOVERABLE_TAX
    ,DATA:"PDA_NONRECOVERABLE_TAX" AS PDA_NONRECOVERABLE_TAX
    ,DATA:"PDA_RECOVERY_RATE" AS PDA_RECOVERY_RATE
    ,DATA:"PDA_AMOUNT_DELIVERED" AS PDA_AMOUNT_DELIVERED
    ,DATA:"PDA_AMOUNT_CANCELLED" AS PDA_AMOUNT_CANCELLED
    ,DATA:"PDA_DISTRIBUTION_TYPE" AS PDA_DISTRIBUTION_TYPE
    ,DATA:"PDA_INVOICE_ADJUSTMENT_FLAG" AS PDA_INVOICE_ADJUSTMENT_FLAG
    ,FILENAME                             AS METADATA_FILENAME 
    ,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
    ,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
    ,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
    from 
    {{ source("landing_ebs", "CM50_PO_DISTRIBUTIONS") }}
    WHERE
        split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
            SELECT
                min_timestamp
            FROM
                (
                    SELECT
                        split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                        split(FILENAME, '/') [3] AS type_file
                    FROM
                        {{ source("landing_ebs", "CM50_PO_DISTRIBUTIONS") }}
                    WHERE
                        type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                            ORDER BY
                                min_timestamp DESC
                        ) = 1
                )
            )