{{
  config(
    materialized = "view",
    alias = "cm50_po_headers_all",
    schema='EBS'
  )
}}

SELECT 
     DATA:"PHA_PO_HEADER_ID" AS PHA_PO_HEADER_ID
    ,DATA:"PHA_AGENT_ID" AS PHA_AGENT_ID
    ,DATA:"PHA_TYPE_LOOKUP_CODE" AS PHA_TYPE_LOOKUP_CODE
    ,DATA:"PHA_LAST_UPDATE_DATE" AS PHA_LAST_UPDATE_DATE
    ,DATA:"PHA_LAST_UPDATED_BY" AS PHA_LAST_UPDATED_BY
    ,DATA:"PHA_SEGMENT1" AS PHA_SEGMENT1
    ,DATA:"PHA_SUMMARY_FLAG" AS PHA_SUMMARY_FLAG
    ,DATA:"PHA_ENABLED_FLAG" AS PHA_ENABLED_FLAG
    ,DATA:"PHA_LAST_UPDATE_LOGIN" AS PHA_LAST_UPDATE_LOGIN
    ,DATA:"PHA_CREATION_DATE" AS PHA_CREATION_DATE
    ,DATA:"PHA_CREATED_BY" AS PHA_CREATED_BY
    ,DATA:"PHA_VENDOR_ID" AS PHA_VENDOR_ID
    ,DATA:"PHA_VENDOR_SITE_ID" AS PHA_VENDOR_SITE_ID
    ,DATA:"PHA_VENDOR_CONTACT_ID" AS PHA_VENDOR_CONTACT_ID
    ,DATA:"PHA_SHIP_TO_LOCATION_ID" AS PHA_SHIP_TO_LOCATION_ID
    ,DATA:"PHA_BILL_TO_LOCATION_ID" AS PHA_BILL_TO_LOCATION_ID
    ,DATA:"PHA_TERMS_ID" AS PHA_TERMS_ID
    ,DATA:"PHA_SHIP_VIA_LOOKUP_CODE" AS PHA_SHIP_VIA_LOOKUP_CODE
    ,DATA:"PHA_FOB_LOOKUP_CODE" AS PHA_FOB_LOOKUP_CODE
    ,DATA:"PHA_FREIGHT_TERMS_LOOKUP_CODE" AS PHA_FREIGHT_TERMS_LOOKUP_CODE
    ,DATA:"PHA_STATUS_LOOKUP_CODE" AS PHA_STATUS_LOOKUP_CODE
    ,DATA:"PHA_CURRENCY_CODE" AS PHA_CURRENCY_CODE
    ,DATA:"PHA_RATE_TYPE" AS PHA_RATE_TYPE
    ,DATA:"PHA_RATE_DATE" AS PHA_RATE_DATE
    ,DATA:"PHA_RATE" AS PHA_RATE
    ,DATA:"PHA_FROM_HEADER_ID" AS PHA_FROM_HEADER_ID
    ,DATA:"PHA_FROM_TYPE_LOOKUP_CODE" AS PHA_FROM_TYPE_LOOKUP_CODE
    ,DATA:"PHA_START_DATE" AS PHA_START_DATE
    ,DATA:"PHA_END_DATE" AS PHA_END_DATE
    ,DATA:"PHA_BLANKET_TOTAL_AMOUNT" AS PHA_BLANKET_TOTAL_AMOUNT
    ,DATA:"PHA_AUTHORIZATION_STATUS" AS PHA_AUTHORIZATION_STATUS
    ,DATA:"PHA_REVISION_NUM" AS PHA_REVISION_NUM
    ,DATA:"PHA_REVISED_DATE" AS PHA_REVISED_DATE
    ,DATA:"PHA_APPROVED_FLAG" AS PHA_APPROVED_FLAG
    ,DATA:"PHA_APPROVED_DATE" AS PHA_APPROVED_DATE
    ,DATA:"PHA_AMOUNT_LIMIT" AS PHA_AMOUNT_LIMIT
    ,DATA:"PHA_MIN_RELEASE_AMOUNT" AS PHA_MIN_RELEASE_AMOUNT
    ,DATA:"PHA_NOTE_TO_VENDOR" AS PHA_NOTE_TO_VENDOR
    ,DATA:"PHA_NOTE_TO_RECEIVER" AS PHA_NOTE_TO_RECEIVER
    ,DATA:"PHA_PRINT_COUNT" AS PHA_PRINT_COUNT
    ,DATA:"PHA_PRINTED_DATE" AS PHA_PRINTED_DATE
    ,DATA:"PHA_CONFIRMING_ORDER_FLAG" AS PHA_CONFIRMING_ORDER_FLAG
    ,DATA:"PHA_COMMENTS" AS PHA_COMMENTS
    ,DATA:"PHA_REPLY_DATE" AS PHA_REPLY_DATE
    ,DATA:"PHA_RFQ_CLOSE_DATE" AS PHA_RFQ_CLOSE_DATE
    ,DATA:"PHA_QUOTE_TYPE_LOOKUP_CODE" AS PHA_QUOTE_TYPE_LOOKUP_CODE
    ,DATA:"PHA_QUOTATION_CLASS_CODE" AS PHA_QUOTATION_CLASS_CODE
    ,DATA:"PHA_QUOTE_WARNING_DELAY" AS PHA_QUOTE_WARNING_DELAY
    ,DATA:"PHA_ACCEPTANCE_REQUIRED_FLAG" AS PHA_ACCEPTANCE_REQUIRED_FLAG
    ,DATA:"PHA_CLOSED_DATE" AS PHA_CLOSED_DATE
    ,DATA:"PHA_USER_HOLD_FLAG" AS PHA_USER_HOLD_FLAG
    ,DATA:"PHA_APPROVAL_REQUIRED_FLAG" AS PHA_APPROVAL_REQUIRED_FLAG
    ,DATA:"PHA_CANCEL_FLAG" AS PHA_CANCEL_FLAG
    ,DATA:"PHA_FIRM_STATUS_LOOKUP_CODE" AS PHA_FIRM_STATUS_LOOKUP_CODE
    ,DATA:"PHA_FROZEN_FLAG" AS PHA_FROZEN_FLAG
    ,DATA:"PHA_SUPPLY_AGREEMENT_FLAG" AS PHA_SUPPLY_AGREEMENT_FLAG
    ,DATA:"PHA_CMG_GL_LOCATION" AS PHA_CMG_GL_LOCATION
    ,DATA:"PHA_CMG_GL_DETAIL_ACTIVITY" AS PHA_CMG_GL_DETAIL_ACTIVITY
    ,DATA:"PHA_CMG_PO_TAG_NUMBER" AS PHA_CMG_PO_TAG_NUMBER
    ,DATA:"PHA_CMG_PO_MANUF_NAME" AS PHA_CMG_PO_MANUF_NAME
    ,DATA:"PHA_CMG_PO_PHSE1A_PROJECT" AS PHA_CMG_PO_PHSE1A_PROJECT
    ,DATA:"PHA_CMG_PO_PHSE1A_TRANS_TYPE" AS PHA_CMG_PO_PHSE1A_TRANS_TYPE
    ,DATA:"PHA_CMG_PO_LOGO" AS PHA_CMG_PO_LOGO
    ,DATA:"PHA_CMG_PO_FLEET_WRK_ORDER" AS PHA_CMG_PO_FLEET_WRK_ORDER
    ,DATA:"PHA_CLOSED_CODE" AS PHA_CLOSED_CODE
    ,DATA:"PHA_REQUEST_ID" AS PHA_REQUEST_ID
    ,DATA:"PHA_PROGRAM_APPLICATION_ID" AS PHA_PROGRAM_APPLICATION_ID
    ,DATA:"PHA_PROGRAM_ID" AS PHA_PROGRAM_ID
    ,DATA:"PHA_PROGRAM_UPDATE_DATE" AS PHA_PROGRAM_UPDATE_DATE
    ,DATA:"PHA_ORG_ID" AS PHA_ORG_ID
    ,DATA:"PHA_INTERFACE_SOURCE_CODE" AS PHA_INTERFACE_SOURCE_CODE
    ,DATA:"PHA_WF_ITEM_TYPE" AS PHA_WF_ITEM_TYPE
    ,DATA:"PHA_WF_ITEM_KEY" AS PHA_WF_ITEM_KEY
    ,DATA:"PHA_XML_FLAG" AS PHA_XML_FLAG
    ,DATA:"PHA_ENABLE_ALL_SITES" AS PHA_ENABLE_ALL_SITES
    ,DATA:"PHA_CONTERMS_EXIST_FLAG" AS PHA_CONTERMS_EXIST_FLAG
    ,DATA:"PHA_ENCUMBRANCE_REQUIRED_FLAG" AS PHA_ENCUMBRANCE_REQUIRED_FLAG
    ,DATA:"PHA_PENDING_SIGNATURE_FLAG" AS PHA_PENDING_SIGNATURE_FLAG
    ,DATA:"PHA_CHANGE_SUMMARY" AS PHA_CHANGE_SUMMARY
    ,DATA:"PHA_DOCUMENT_CREATION_METHOD" AS PHA_DOCUMENT_CREATION_METHOD
    ,DATA:"PHA_SUBMIT_DATE" AS PHA_SUBMIT_DATE
    ,FILENAME                             AS METADATA_FILENAME 
    ,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
    ,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
    ,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
    from 
    {{ source("landing_ebs", "CM50_PO_HEADERS_ALL") }}
    WHERE
        split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
            SELECT
                min_timestamp
            FROM
                (
                    SELECT
                        split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                        split(FILENAME, '/') [3] AS type_file
                    FROM
                        {{ source("landing_ebs", "CM50_PO_HEADERS_ALL") }}
                    WHERE
                        type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                            ORDER BY
                                min_timestamp DESC
                        ) = 1
                )
            )