{{
  config(
    materialized = "view",
    alias = "hz_cust_accounts",
    schema='ebs'
  )
}}

SELECT DATA:"CUST_ACCOUNT_ID" AS CUST_ACCOUNT_ID
,DATA:"PARTY_ID" AS PARTY_ID
,DATA:"LAST_UPDATE_DATE" AS LAST_UPDATE_DATE
,DATA:"ACCOUNT_NUMBER" AS ACCOUNT_NUMBER
,DATA:"LAST_UPDATED_BY" AS LAST_UPDATED_BY
,DATA:"CREATION_DATE" AS CREATION_DATE
,DATA:"CREATED_BY" AS CREATED_BY
,DATA:"LAST_UPDATE_LOGIN" AS LAST_UPDATE_LOGIN
,DATA:"REQUEST_ID" AS REQUEST_ID
,DATA:"PROGRAM_APPLICATION_ID" AS PROGRAM_APPLICATION_ID
,DATA:"PROGRAM_ID" AS PROGRAM_ID
,DATA:"PROGRAM_UPDATE_DATE" AS PROGRAM_UPDATE_DATE
,DATA:"WH_UPDATE_DATE" AS WH_UPDATE_DATE
,DATA:"ATTRIBUTE_CATEGORY" AS ATTRIBUTE_CATEGORY
,DATA:"ATTRIBUTE1" AS ATTRIBUTE1
,DATA:"ATTRIBUTE2" AS ATTRIBUTE2
,DATA:"ATTRIBUTE3" AS ATTRIBUTE3
,DATA:"ATTRIBUTE4" AS ATTRIBUTE4
,DATA:"ATTRIBUTE5" AS ATTRIBUTE5
,DATA:"ATTRIBUTE6" AS ATTRIBUTE6
,DATA:"ATTRIBUTE7" AS ATTRIBUTE7
,DATA:"ATTRIBUTE8" AS ATTRIBUTE8
,DATA:"ATTRIBUTE9" AS ATTRIBUTE9
,DATA:"ATTRIBUTE10" AS ATTRIBUTE10
,DATA:"ATTRIBUTE11" AS ATTRIBUTE11
,DATA:"ATTRIBUTE12" AS ATTRIBUTE12
,DATA:"ATTRIBUTE13" AS ATTRIBUTE13
,DATA:"ATTRIBUTE14" AS ATTRIBUTE14
,DATA:"ATTRIBUTE15" AS ATTRIBUTE15
,DATA:"ATTRIBUTE16" AS ATTRIBUTE16
,DATA:"ATTRIBUTE17" AS ATTRIBUTE17
,DATA:"ATTRIBUTE18" AS ATTRIBUTE18
,DATA:"ATTRIBUTE19" AS ATTRIBUTE19
,DATA:"ATTRIBUTE20" AS ATTRIBUTE20
,DATA:"GLOBAL_ATTRIBUTE_CATEGORY" AS GLOBAL_ATTRIBUTE_CATEGORY
,DATA:"GLOBAL_ATTRIBUTE1" AS GLOBAL_ATTRIBUTE1
,DATA:"GLOBAL_ATTRIBUTE2" AS GLOBAL_ATTRIBUTE2
,DATA:"GLOBAL_ATTRIBUTE3" AS GLOBAL_ATTRIBUTE3
,DATA:"GLOBAL_ATTRIBUTE4" AS GLOBAL_ATTRIBUTE4
,DATA:"GLOBAL_ATTRIBUTE5" AS GLOBAL_ATTRIBUTE5
,DATA:"GLOBAL_ATTRIBUTE6" AS GLOBAL_ATTRIBUTE6
,DATA:"GLOBAL_ATTRIBUTE7" AS GLOBAL_ATTRIBUTE7
,DATA:"GLOBAL_ATTRIBUTE8" AS GLOBAL_ATTRIBUTE8
,DATA:"GLOBAL_ATTRIBUTE9" AS GLOBAL_ATTRIBUTE9
,DATA:"GLOBAL_ATTRIBUTE10" AS GLOBAL_ATTRIBUTE10
,DATA:"GLOBAL_ATTRIBUTE11" AS GLOBAL_ATTRIBUTE11
,DATA:"GLOBAL_ATTRIBUTE12" AS GLOBAL_ATTRIBUTE12
,DATA:"GLOBAL_ATTRIBUTE13" AS GLOBAL_ATTRIBUTE13
,DATA:"GLOBAL_ATTRIBUTE14" AS GLOBAL_ATTRIBUTE14
,DATA:"GLOBAL_ATTRIBUTE15" AS GLOBAL_ATTRIBUTE15
,DATA:"GLOBAL_ATTRIBUTE16" AS GLOBAL_ATTRIBUTE16
,DATA:"GLOBAL_ATTRIBUTE17" AS GLOBAL_ATTRIBUTE17
,DATA:"GLOBAL_ATTRIBUTE18" AS GLOBAL_ATTRIBUTE18
,DATA:"GLOBAL_ATTRIBUTE19" AS GLOBAL_ATTRIBUTE19
,DATA:"GLOBAL_ATTRIBUTE20" AS GLOBAL_ATTRIBUTE20
,DATA:"ORIG_SYSTEM_REFERENCE" AS ORIG_SYSTEM_REFERENCE
,DATA:"STATUS" AS STATUS
,DATA:"CUSTOMER_TYPE" AS CUSTOMER_TYPE
,DATA:"CUSTOMER_CLASS_CODE" AS CUSTOMER_CLASS_CODE
,DATA:"PRIMARY_SALESREP_ID" AS PRIMARY_SALESREP_ID
,DATA:"SALES_CHANNEL_CODE" AS SALES_CHANNEL_CODE
,DATA:"ORDER_TYPE_ID" AS ORDER_TYPE_ID
,DATA:"PRICE_LIST_ID" AS PRICE_LIST_ID
,DATA:"SUBCATEGORY_CODE" AS SUBCATEGORY_CODE
,DATA:"TAX_CODE" AS TAX_CODE
,DATA:"FOB_POINT" AS FOB_POINT
,DATA:"FREIGHT_TERM" AS FREIGHT_TERM
,DATA:"SHIP_PARTIAL" AS SHIP_PARTIAL
,DATA:"SHIP_VIA" AS SHIP_VIA
,DATA:"WAREHOUSE_ID" AS WAREHOUSE_ID
,DATA:"PAYMENT_TERM_ID" AS PAYMENT_TERM_ID
,DATA:"TAX_HEADER_LEVEL_FLAG" AS TAX_HEADER_LEVEL_FLAG
,DATA:"TAX_ROUNDING_RULE" AS TAX_ROUNDING_RULE
,DATA:"COTERMINATE_DAY_MONTH" AS COTERMINATE_DAY_MONTH
,DATA:"PRIMARY_SPECIALIST_ID" AS PRIMARY_SPECIALIST_ID
,DATA:"SECONDARY_SPECIALIST_ID" AS SECONDARY_SPECIALIST_ID
,DATA:"ACCOUNT_LIABLE_FLAG" AS ACCOUNT_LIABLE_FLAG
,DATA:"RESTRICTION_LIMIT_AMOUNT" AS RESTRICTION_LIMIT_AMOUNT
,DATA:"CURRENT_BALANCE" AS CURRENT_BALANCE
,DATA:"PASSWORD_TEXT" AS PASSWORD_TEXT
,DATA:"HIGH_PRIORITY_INDICATOR" AS HIGH_PRIORITY_INDICATOR
,DATA:"ACCOUNT_ESTABLISHED_DATE" AS ACCOUNT_ESTABLISHED_DATE
,DATA:"ACCOUNT_TERMINATION_DATE" AS ACCOUNT_TERMINATION_DATE
,DATA:"ACCOUNT_ACTIVATION_DATE" AS ACCOUNT_ACTIVATION_DATE
,DATA:"CREDIT_CLASSIFICATION_CODE" AS CREDIT_CLASSIFICATION_CODE
,DATA:"DEPARTMENT" AS DEPARTMENT
,DATA:"MAJOR_ACCOUNT_NUMBER" AS MAJOR_ACCOUNT_NUMBER
,DATA:"HOTWATCH_SERVICE_FLAG" AS HOTWATCH_SERVICE_FLAG
,DATA:"HOTWATCH_SVC_BAL_IND" AS HOTWATCH_SVC_BAL_IND
,DATA:"HELD_BILL_EXPIRATION_DATE" AS HELD_BILL_EXPIRATION_DATE
,DATA:"HOLD_BILL_FLAG" AS HOLD_BILL_FLAG
,DATA:"HIGH_PRIORITY_REMARKS" AS HIGH_PRIORITY_REMARKS
,DATA:"PO_EFFECTIVE_DATE" AS PO_EFFECTIVE_DATE
,DATA:"PO_EXPIRATION_DATE" AS PO_EXPIRATION_DATE
,DATA:"REALTIME_RATE_FLAG" AS REALTIME_RATE_FLAG
,DATA:"SINGLE_USER_FLAG" AS SINGLE_USER_FLAG
,DATA:"WATCH_ACCOUNT_FLAG" AS WATCH_ACCOUNT_FLAG
,DATA:"WATCH_BALANCE_INDICATOR" AS WATCH_BALANCE_INDICATOR
,DATA:"GEO_CODE" AS GEO_CODE
,DATA:"ACCT_LIFE_CYCLE_STATUS" AS ACCT_LIFE_CYCLE_STATUS
,DATA:"ACCOUNT_NAME" AS ACCOUNT_NAME
,DATA:"DEPOSIT_REFUND_METHOD" AS DEPOSIT_REFUND_METHOD
,DATA:"DORMANT_ACCOUNT_FLAG" AS DORMANT_ACCOUNT_FLAG
,DATA:"NPA_NUMBER" AS NPA_NUMBER
,DATA:"PIN_NUMBER" AS PIN_NUMBER
,DATA:"SUSPENSION_DATE" AS SUSPENSION_DATE
,DATA:"WRITE_OFF_ADJUSTMENT_AMOUNT" AS WRITE_OFF_ADJUSTMENT_AMOUNT
,DATA:"WRITE_OFF_PAYMENT_AMOUNT" AS WRITE_OFF_PAYMENT_AMOUNT
,DATA:"WRITE_OFF_AMOUNT" AS WRITE_OFF_AMOUNT
,DATA:"SOURCE_CODE" AS SOURCE_CODE
,DATA:"COMPETITOR_TYPE" AS COMPETITOR_TYPE
,DATA:"COMMENTS" AS COMMENTS
,DATA:"DATES_NEGATIVE_TOLERANCE" AS DATES_NEGATIVE_TOLERANCE
,DATA:"DATES_POSITIVE_TOLERANCE" AS DATES_POSITIVE_TOLERANCE
,DATA:"DATE_TYPE_PREFERENCE" AS DATE_TYPE_PREFERENCE
,DATA:"OVER_SHIPMENT_TOLERANCE" AS OVER_SHIPMENT_TOLERANCE
,DATA:"UNDER_SHIPMENT_TOLERANCE" AS UNDER_SHIPMENT_TOLERANCE
,DATA:"OVER_RETURN_TOLERANCE" AS OVER_RETURN_TOLERANCE
,DATA:"UNDER_RETURN_TOLERANCE" AS UNDER_RETURN_TOLERANCE
,DATA:"ITEM_CROSS_REF_PREF" AS ITEM_CROSS_REF_PREF
,DATA:"SHIP_SETS_INCLUDE_LINES_FLAG" AS SHIP_SETS_INCLUDE_LINES_FLAG
,DATA:"ARRIVALSETS_INCLUDE_LINES_FLAG" AS ARRIVALSETS_INCLUDE_LINES_FLAG
,DATA:"SCHED_DATE_PUSH_FLAG" AS SCHED_DATE_PUSH_FLAG
,DATA:"INVOICE_QUANTITY_RULE" AS INVOICE_QUANTITY_RULE
,DATA:"PRICING_EVENT" AS PRICING_EVENT
,DATA:"ACCOUNT_REPLICATION_KEY" AS ACCOUNT_REPLICATION_KEY
,DATA:"STATUS_UPDATE_DATE" AS STATUS_UPDATE_DATE
,DATA:"AUTOPAY_FLAG" AS AUTOPAY_FLAG
,DATA:"NOTIFY_FLAG" AS NOTIFY_FLAG
,DATA:"LAST_BATCH_ID" AS LAST_BATCH_ID
,DATA:"OBJECT_VERSION_NUMBER" AS OBJECT_VERSION_NUMBER
,DATA:"CREATED_BY_MODULE" AS CREATED_BY_MODULE
,DATA:"APPLICATION_ID" AS APPLICATION_ID
,DATA:"SELLING_PARTY_ID" AS SELLING_PARTY_ID
,DATA:"ORG_ID" AS ORG_ID
,FILENAME AS METADATA_FILENAME
,FILE_ROW_NUMBER AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME AS METADATA_START_SCAN_TIME
 FROM 
 {{ source("landing_ebs", "HZ_CUST_ACCOUNTS")}}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM 
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM 
                  {{ source("landing_ebs", "HZ_CUST_ACCOUNTS")}}
                    
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )
