{{
  config(
    materialized = "view",
    alias = "cm50_ap_invoice_distribution",
    schema='EBS'
  )
}}

select  
DATA:AID_ACCOUNTING_DATE              as AID_ACCOUNTING_DATE
,DATA:AID_ACCOUNTING_EVENT_ID         as AID_ACCOUNTING_EVENT_ID
,DATA:AID_ACCRUAL_POSTED_FLAG         as AID_ACCRUAL_POSTED_FLAG
,DATA:AID_AMOUNT                      as AID_AMOUNT
,DATA:AID_AMOUNT_INCLUDES_TAX_FLAG    as AID_AMOUNT_INCLUDES_TAX_FLAG
,DATA:AID_AP_INTERFACED               as AID_AP_INTERFACED
,DATA:AID_AP_MODEL_NO                 as AID_AP_MODEL_NO
,DATA:AID_ASSETS_ADDITION_FLAG        as AID_ASSETS_ADDITION_FLAG
,DATA:AID_ASSETS_TRACKING_FLAG        as AID_ASSETS_TRACKING_FLAG
,DATA:AID_ATTRIBUTE8                  as AID_ATTRIBUTE8
,DATA:AID_ATTRIBUTE9                  as AID_ATTRIBUTE9
,DATA:AID_ATTRIBUTE_CATEGORY          as AID_ATTRIBUTE_CATEGORY
,DATA:AID_BASE_AMOUNT                 as AID_BASE_AMOUNT
,DATA:AID_BASE_INVE_PRCE_VARIANCE     as AID_BASE_INVE_PRCE_VARIANCE
,DATA:AID_BASE_QUANTITY_VARIANCE      as AID_BASE_QUANTITY_VARIANCE
,DATA:AID_BATCH_ID                    as AID_BATCH_ID
,DATA:AID_CANCELLATION_FLAG           as AID_CANCELLATION_FLAG
,DATA:AID_CASH_POSTED_FLAG            as AID_CASH_POSTED_FLAG
,DATA:AID_CM_PA_CC_AR_INV_ID          as AID_CM_PA_CC_AR_INV_ID
,DATA:AID_CREATED_BY                  as AID_CREATED_BY
,DATA:AID_CREATION_DATE               as AID_CREATION_DATE
,DATA:AID_DESCRIPTION                 as AID_DESCRIPTION
,DATA:AID_DISTRIBUTION_LINE_NUMBER    as AID_DISTRIBUTION_LINE_NUMBER
,DATA:AID_DIST_CODE_COMBINATION_ID    as AID_DIST_CODE_COMBINATION_ID
,DATA:AID_DIST_MATCH_TYPE             as AID_DIST_MATCH_TYPE
,DATA:AID_ENCUMBERED_FLAG             as AID_ENCUMBERED_FLAG
,DATA:AID_EXCHANGE_DATE               as AID_EXCHANGE_DATE
,DATA:AID_EXCHANGE_RATE               as AID_EXCHANGE_RATE
,DATA:AID_EXCHANGE_RATE_TYPE          as AID_EXCHANGE_RATE_TYPE
,DATA:AID_EXCHANGE_RATE_VARIANCE      as AID_EXCHANGE_RATE_VARIANCE
,DATA:AID_EXPENDITURE_ITEM_DATE       as AID_EXPENDITURE_ITEM_DATE
,DATA:AID_EXPENDITURE_ORG_ID          as AID_EXPENDITURE_ORG_ID
,DATA:AID_EXPENDITURE_TYPE            as AID_EXPENDITURE_TYPE
,DATA:AID_FINAL_MATCH_FLAG            as AID_FINAL_MATCH_FLAG
,DATA:AID_GL_DETAIL_ACTIVITY          as AID_GL_DETAIL_ACTIVITY
,DATA:AID_GL_LOCATION                 as AID_GL_LOCATION
,DATA:AID_INCOME_TAX_REGION           as AID_INCOME_TAX_REGION
,DATA:AID_INVENTORY_TRANSFER_STATUS   as AID_INVENTORY_TRANSFER_STATUS
,DATA:AID_INVOICE_DISTRIBUTION_ID     as AID_INVOICE_DISTRIBUTION_ID
,DATA:AID_INVOICE_ID                  as AID_INVOICE_ID
,DATA:AID_INVOICE_INCL_PRPAY_FLAG     as AID_INVOICE_INCL_PRPAY_FLAG
,DATA:AID_INVOICE_PRICE_VARIANCE      as AID_INVOICE_PRICE_VARIANCE
,DATA:AID_LAST_UPDATED_BY             as AID_LAST_UPDATED_BY
,DATA:AID_LAST_UPDATE_DATE            as AID_LAST_UPDATE_DATE
,DATA:AID_LAST_UPDATE_LOGIN           as AID_LAST_UPDATE_LOGIN
,DATA:AID_LINE_TYPE_LOOKUP_CODE       as AID_LINE_TYPE_LOOKUP_CODE
,DATA:AID_MATCHED_UOM_LOOKUP_CODE     as AID_MATCHED_UOM_LOOKUP_CODE
,DATA:AID_MATCH_STATUS_FLAG           as AID_MATCH_STATUS_FLAG
,DATA:AID_ORG_ID                      as AID_ORG_ID
,DATA:AID_PARENT_INVOICE_ID           as AID_PARENT_INVOICE_ID
,DATA:AID_PARENT_REVERSAL_ID          as AID_PARENT_REVERSAL_ID
,DATA:AID_PA_ADDITION_FLAG            as AID_PA_ADDITION_FLAG
,DATA:AID_PA_CC_AR_INVOICE_ID         as AID_PA_CC_AR_INVOICE_ID
,DATA:AID_PA_CC_AR_INVOICE_LINE_NUM   as AID_PA_CC_AR_INVOICE_LINE_NUM
,DATA:AID_PA_QUANTITY                 as AID_PA_QUANTITY
,DATA:AID_PERIOD_NAME                 as AID_PERIOD_NAME
,DATA:AID_POSTED_FLAG                 as AID_POSTED_FLAG
,DATA:AID_PO_DISTRIBUTION_ID          as AID_PO_DISTRIBUTION_ID
,DATA:AID_PO_FLEET_WORK_ORDER         as AID_PO_FLEET_WORK_ORDER
,DATA:AID_PO_TAG_NUMBER               as AID_PO_TAG_NUMBER
,DATA:AID_PREPAY_AMOUNT_REMAINING     as AID_PREPAY_AMOUNT_REMAINING
,DATA:AID_PREPAY_DISTRIBUTION_ID      as AID_PREPAY_DISTRIBUTION_ID
,DATA:AID_PREPAY_TAX_PARENT_ID        as AID_PREPAY_TAX_PARENT_ID
,DATA:AID_PRICE_ADJUSTMENT_FLAG       as AID_PRICE_ADJUSTMENT_FLAG
,DATA:AID_PRICE_CORRECT_INV_ID        as AID_PRICE_CORRECT_INV_ID
,DATA:AID_PRICE_CORRECT_QTY           as AID_PRICE_CORRECT_QTY
,DATA:AID_PRICE_VAR_CODE_COM_ID       as AID_PRICE_VAR_CODE_COM_ID
,DATA:AID_PROGRAM_APPLICATION_ID      as AID_PROGRAM_APPLICATION_ID
,DATA:AID_PROGRAM_ID                  as AID_PROGRAM_ID
,DATA:AID_PROGRAM_UPDATE_DATE         as AID_PROGRAM_UPDATE_DATE
,DATA:AID_PROJECT_ACCOUNTING_CONTEXT  as AID_PROJECT_ACCOUNTING_CONTEXT
,DATA:AID_PROJECT_ID                  as AID_PROJECT_ID
,DATA:AID_QUANTITY_INVOICED           as AID_QUANTITY_INVOICED
,DATA:AID_QUANTITY_VARIANCE           as AID_QUANTITY_VARIANCE
,DATA:AID_RATE_VAR_CDE_COMB_ID        as AID_RATE_VAR_CDE_COMB_ID
,DATA:AID_REQUEST_ID                  as AID_REQUEST_ID
,DATA:AID_REVERSAL_FLAG               as AID_REVERSAL_FLAG
,DATA:AID_SET_OF_BOOKS_ID             as AID_SET_OF_BOOKS_ID
,DATA:AID_TASK_ID                     as AID_TASK_ID
,DATA:AID_TAX_CALCULATED_FLAG         as AID_TAX_CALCULATED_FLAG
,DATA:AID_TAX_CODE_ID                 as AID_TAX_CODE_ID
,DATA:AID_TAX_CODE_OVERRIDE_FLAG      as AID_TAX_CODE_OVERRIDE_FLAG
,DATA:AID_TAX_RECOVERABLE_FLAG        as AID_TAX_RECOVERABLE_FLAG
,DATA:AID_TAX_RECOVERY_OVERRIDE_FLAG  as AID_TAX_RECOVERY_OVERRIDE_FLAG
,DATA:AID_TAX_RECOVERY_RATE           as AID_TAX_RECOVERY_RATE
,DATA:AID_TYPE_1099                   as AID_TYPE_1099
,DATA:AID_UNIT_PRICE                  as AID_UNIT_PRICE
,FILENAME                             as METADATA_FILENAME 
,FILE_ROW_NUMBER                      as METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   as METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      as METADATA_START_SCAN_TIME
from {{ source("landing_ebs", "CM50_AP_INVOICE_DISTRIBUTION") }}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM
                    {{ source("landing_ebs", "CM50_AP_INVOICE_DISTRIBUTION") }}
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )