{{
  config(
    materialized = "view",
    alias = "hr_organization_units_v",
    schema='EBS'
  )
}}

SELECT DATA:"LOC_INFORMATION15" AS LOC_INFORMATION15
,DATA:"LOC_INFORMATION14" AS LOC_INFORMATION14
,DATA:"LOC_INFORMATION13" AS LOC_INFORMATION13
,DATA:"TOWN_OR_CITY" AS TOWN_OR_CITY
,DATA:"POSTAL_CODE" AS POSTAL_CODE
,DATA:"TELEPHONE_NUMBER_3" AS TELEPHONE_NUMBER_3
,DATA:"TELEPHONE_NUMBER_2" AS TELEPHONE_NUMBER_2
,DATA:"TELEPHONE_NUMBER_1" AS TELEPHONE_NUMBER_1
,DATA:"REGION_3" AS REGION_3
,DATA:"REGION_2" AS REGION_2
,DATA:"REGION_1" AS REGION_1
,DATA:"ADDRESS_LINE_3" AS ADDRESS_LINE_3
,DATA:"ADDRESS_LINE_2" AS ADDRESS_LINE_2
,DATA:"ADDRESS_LINE_1" AS ADDRESS_LINE_1
,DATA:"COUNTRY" AS COUNTRY
,DATA:"STYLE" AS STYLE
,DATA:"LOCATION_CODE" AS LOCATION_CODE
,DATA:"LOCATION_ID" AS LOCATION_ID
,DATA:"COST_ALLOCATION_KEYFLEX_ID" AS COST_ALLOCATION_KEYFLEX_ID
,DATA:"BUSINESS_GROUP_ID" AS BUSINESS_GROUP_ID
,DATA:"ROW_ID" AS ROW_ID
,DATA:"ORGANIZATION_ID" AS ORGANIZATION_ID
,DATA:"OBJECT_VERSION_NUMBER" AS OBJECT_VERSION_NUMBER
,DATA:"CREATION_DATE" AS CREATION_DATE
,DATA:"CREATED_BY" AS CREATED_BY
,DATA:"LAST_UPDATE_LOGIN" AS LAST_UPDATE_LOGIN
,DATA:"LAST_UPDATED_BY" AS LAST_UPDATED_BY
,DATA:"LAST_UPDATE_DATE" AS LAST_UPDATE_DATE
,DATA:"ATTRIBUTE20" AS ATTRIBUTE20
,DATA:"ATTRIBUTE19" AS ATTRIBUTE19
,DATA:"ATTRIBUTE18" AS ATTRIBUTE18
,DATA:"ATTRIBUTE17" AS ATTRIBUTE17
,DATA:"ATTRIBUTE16" AS ATTRIBUTE16
,DATA:"ATTRIBUTE15" AS ATTRIBUTE15
,DATA:"ATTRIBUTE14" AS ATTRIBUTE14
,DATA:"ATTRIBUTE13" AS ATTRIBUTE13
,DATA:"ATTRIBUTE12" AS ATTRIBUTE12
,DATA:"ATTRIBUTE11" AS ATTRIBUTE11
,DATA:"ATTRIBUTE10" AS ATTRIBUTE10
,DATA:"ATTRIBUTE9" AS ATTRIBUTE9
,DATA:"ATTRIBUTE8" AS ATTRIBUTE8
,DATA:"ATTRIBUTE7" AS ATTRIBUTE7
,DATA:"ATTRIBUTE6" AS ATTRIBUTE6
,DATA:"ATTRIBUTE5" AS ATTRIBUTE5
,DATA:"ATTRIBUTE4" AS ATTRIBUTE4
,DATA:"ATTRIBUTE3" AS ATTRIBUTE3
,DATA:"ATTRIBUTE2" AS ATTRIBUTE2
,DATA:"ATTRIBUTE1" AS ATTRIBUTE1
,DATA:"ATTRIBUTE_CATEGORY" AS ATTRIBUTE_CATEGORY
,DATA:"PROGRAM_UPDATE_DATE" AS PROGRAM_UPDATE_DATE
,DATA:"PROGRAM_ID" AS PROGRAM_ID
,DATA:"PROGRAM_APPLICATION_ID" AS PROGRAM_APPLICATION_ID
,DATA:"REQUEST_ID" AS REQUEST_ID
,DATA:"ORGANIZATION_TYPE" AS ORGANIZATION_TYPE
,DATA:"TYPE" AS TYPE
,DATA:"INTERNAL_ADDRESS_LINE" AS INTERNAL_ADDRESS_LINE
,DATA:"INTERNAL_EXTERNAL_MEANING" AS INTERNAL_EXTERNAL_MEANING
,DATA:"INTERNAL_EXTERNAL_FLAG" AS INTERNAL_EXTERNAL_FLAG
,DATA:"DATE_TO" AS DATE_TO
,DATA:"COMMENTS" AS COMMENTS
,DATA:"NAME" AS NAME
,DATA:"DATE_FROM" AS DATE_FROM
,DATA:"SOFT_CODING_KEYFLEX_ID" AS SOFT_CODING_KEYFLEX_ID
,DATA:"LOC_INFORMATION20" AS LOC_INFORMATION20
,DATA:"LOC_INFORMATION19" AS LOC_INFORMATION19
,DATA:"LOC_INFORMATION18" AS LOC_INFORMATION18
,DATA:"LOC_INFORMATION17" AS LOC_INFORMATION17
,DATA:"LOC_INFORMATION16" AS LOC_INFORMATION16
,FILENAME AS METADATA_FILENAME
,FILE_ROW_NUMBER AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME AS METADATA_START_SCAN_TIME
FROM 
 {{ source("landing_ebs", "HR_ORGANIZATION_UNITS_V")}}
 
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM 
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM 
                  {{ source("landing_ebs", "HR_ORGANIZATION_UNITS_V")}}
                    
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )