{{
  config(
    materialized = "view",
    alias = "mtl_eam_asset_attr_values",
    schema='EBS'
  )
}}

SELECT
DATA:N_ATTRIBUTE8 AS N_ATTRIBUTE8
,DATA:N_ATTRIBUTE7 AS N_ATTRIBUTE7
,DATA:N_ATTRIBUTE6 AS N_ATTRIBUTE6
,DATA:N_ATTRIBUTE5 AS N_ATTRIBUTE5
,DATA:N_ATTRIBUTE4 AS N_ATTRIBUTE4
,DATA:N_ATTRIBUTE3 AS N_ATTRIBUTE3
,DATA:N_ATTRIBUTE2 AS N_ATTRIBUTE2
,DATA:N_ATTRIBUTE1 AS N_ATTRIBUTE1
,DATA:D_ATTRIBUTE10 AS D_ATTRIBUTE10
,DATA:D_ATTRIBUTE9 AS D_ATTRIBUTE9
,DATA:D_ATTRIBUTE8 AS D_ATTRIBUTE8
,DATA:D_ATTRIBUTE7 AS D_ATTRIBUTE7
,DATA:D_ATTRIBUTE6 AS D_ATTRIBUTE6
,DATA:D_ATTRIBUTE5 AS D_ATTRIBUTE5
,DATA:D_ATTRIBUTE4 AS D_ATTRIBUTE4
,DATA:D_ATTRIBUTE3 AS D_ATTRIBUTE3
,DATA:D_ATTRIBUTE2 AS D_ATTRIBUTE2
,DATA:D_ATTRIBUTE1 AS D_ATTRIBUTE1
,DATA:C_ATTRIBUTE20 AS C_ATTRIBUTE20
,DATA:C_ATTRIBUTE19 AS C_ATTRIBUTE19
,DATA:C_ATTRIBUTE18 AS C_ATTRIBUTE18
,DATA:C_ATTRIBUTE17 AS C_ATTRIBUTE17
,DATA:C_ATTRIBUTE16 AS C_ATTRIBUTE16
,DATA:C_ATTRIBUTE15 AS C_ATTRIBUTE15
,DATA:C_ATTRIBUTE14 AS C_ATTRIBUTE14
,DATA:C_ATTRIBUTE13 AS C_ATTRIBUTE13
,DATA:C_ATTRIBUTE12 AS C_ATTRIBUTE12
,DATA:C_ATTRIBUTE11 AS C_ATTRIBUTE11
,DATA:C_ATTRIBUTE10 AS C_ATTRIBUTE10
,DATA:C_ATTRIBUTE9 AS C_ATTRIBUTE9
,DATA:C_ATTRIBUTE8 AS C_ATTRIBUTE8
,DATA:C_ATTRIBUTE7 AS C_ATTRIBUTE7
,DATA:C_ATTRIBUTE6 AS C_ATTRIBUTE6
,DATA:C_ATTRIBUTE5 AS C_ATTRIBUTE5
,DATA:C_ATTRIBUTE4 AS C_ATTRIBUTE4
,DATA:C_ATTRIBUTE3 AS C_ATTRIBUTE3
,DATA:C_ATTRIBUTE2 AS C_ATTRIBUTE2
,DATA:C_ATTRIBUTE1 AS C_ATTRIBUTE1
,DATA:ORGANIZATION_ID AS ORGANIZATION_ID
,DATA:SERIAL_NUMBER AS SERIAL_NUMBER
,DATA:INVENTORY_ITEM_ID AS INVENTORY_ITEM_ID
,DATA:DESCRIPTIVE_FLEXFIELD_NAME AS DESCRIPTIVE_FLEXFIELD_NAME
,DATA:APPLICATION_ID AS APPLICATION_ID
,DATA:ATTRIBUTE_GROUP AS ATTRIBUTE_GROUP
,DATA:ATTRIBUTE_CATEGORY AS ATTRIBUTE_CATEGORY
,DATA:ASSOCIATION_ID AS ASSOCIATION_ID
,DATA:ROW_ID AS ROW_ID
,DATA:PROGRAM_UPDATE_DATE AS PROGRAM_UPDATE_DATE
,DATA:PROGRAM_ID AS PROGRAM_ID
,DATA:PROGRAM_APPLICATION_ID AS PROGRAM_APPLICATION_ID
,DATA:REQUEST_ID AS REQUEST_ID
,DATA:LAST_UPDATE_LOGIN AS LAST_UPDATE_LOGIN
,DATA:CREATED_BY AS CREATED_BY
,DATA:CREATION_DATE AS CREATION_DATE
,DATA:LAST_UPDATED_BY AS LAST_UPDATED_BY
,DATA:LAST_UPDATE_DATE AS LAST_UPDATE_DATE
,DATA:N_ATTRIBUTE10 AS N_ATTRIBUTE10
,DATA:N_ATTRIBUTE9 AS N_ATTRIBUTE9
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM {{ source("landing_ebs", "MTL_EAM_ASSET_ATTR_VALUES") }}
-- to only take the files after the last fullLoad
  WHERE 
  split(FILENAME, '_')[array_size(split(FILENAME, '_')) - 2] >=
    (SELECT min_timestamp
  FROM
      (SELECT split(FILENAME, '_')[array_size(split(FILENAME, '_')) - 2] AS min_timestamp, split(FILENAME, '/')[3] AS type_file
      FROM {{ source("landing_ebs", "MTL_EAM_ASSET_ATTR_VALUES") }}
      WHERE type_file LIKE 'fullload%'
      QUALIFY ROW_NUMBER() OVER (ORDER BY min_timestamp DESC) = 1)
    )