{{
  config(
    materialized = "view",
    alias = "mtl_object_genealogy",
    schema='EBS'
  )
}}

select
DATA:OBJECT_ID AS OBJECT_ID
,DATA:OBJECT_TYPE AS OBJECT_TYPE
,DATA:PARENT_OBJECT_TYPE AS PARENT_OBJECT_TYPE
,DATA:PARENT_OBJECT_ID AS PARENT_OBJECT_ID
,DATA:LAST_UPDATE_DATE AS LAST_UPDATE_DATE
,DATA:LAST_UPDATED_BY AS LAST_UPDATED_BY
,DATA:CREATION_DATE AS CREATION_DATE
,DATA:CREATED_BY AS CREATED_BY
,DATA:START_DATE_ACTIVE AS START_DATE_ACTIVE
,DATA:END_DATE_ACTIVE AS END_DATE_ACTIVE
,DATA:GENEALOGY_ORIGIN AS GENEALOGY_ORIGIN
,DATA:ORIGIN_TXN_ID AS ORIGIN_TXN_ID
,DATA:GENEALOGY_TYPE AS GENEALOGY_TYPE
,DATA:LAST_UPDATE_LOGIN AS LAST_UPDATE_LOGIN
,DATA:ATTRIBUTE_CATEGORY AS ATTRIBUTE_CATEGORY
,DATA:ATTRIBUTE1 AS ATTRIBUTE1
,DATA:ATTRIBUTE2 AS ATTRIBUTE2
,DATA:ATTRIBUTE3 AS ATTRIBUTE3
,DATA:ATTRIBUTE4 AS ATTRIBUTE4
,DATA:ATTRIBUTE5 AS ATTRIBUTE5
,DATA:ATTRIBUTE6 AS ATTRIBUTE6
,DATA:ATTRIBUTE7 AS ATTRIBUTE7
,DATA:ATTRIBUTE8 AS ATTRIBUTE8
,DATA:ATTRIBUTE9 AS ATTRIBUTE9
,DATA:ATTRIBUTE10 AS ATTRIBUTE10
,DATA:ATTRIBUTE11 AS ATTRIBUTE11
,DATA:ATTRIBUTE12 AS ATTRIBUTE12
,DATA:ATTRIBUTE13 AS ATTRIBUTE13
,DATA:ATTRIBUTE14 AS ATTRIBUTE14
,DATA:ATTRIBUTE15 AS ATTRIBUTE15
,DATA:REQUEST_ID AS REQUEST_ID
,DATA:PROGRAM_APPLICATION_ID AS PROGRAM_APPLICATION_ID
,DATA:PROGRAM_ID AS PROGRAM_ID
,DATA:PROGRAM_UPDATE_DATE AS PROGRAM_UPDATE_DATE
,DATA:UPDATE_TXN_ID AS UPDATE_TXN_ID
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM {{ source("landing_ebs", "MTL_OBJECT_GENEALOGY") }}
-- to only take the files after the last fullLoad
  WHERE 
  split(FILENAME, '_')[array_size(split(FILENAME, '_')) - 2] >=
    (SELECT min_timestamp
  FROM
      (SELECT split(FILENAME, '_')[array_size(split(FILENAME, '_')) - 2] AS min_timestamp, split(FILENAME, '/')[3] AS type_file
      FROM {{ source("landing_ebs", "MTL_OBJECT_GENEALOGY") }}
      WHERE type_file LIKE 'fullload%'
      QUALIFY ROW_NUMBER() OVER (ORDER BY min_timestamp DESC) = 1)
    )