{{
  config(
    materialized = "view",
    alias = "cm50_ap_invoices_all",
    schema='EBS'
  )
}}


select  
DATA:AIA_ACCTS_PAY_CC_ID             as AIA_ACCTS_PAY_CC_ID
,DATA:AIA_AMOUNT_APP_TO_DISCOUNT     as AIA_AMOUNT_APP_TO_DISCOUNT
,DATA:AIA_AMOUNT_PAID                as AIA_AMOUNT_PAID
,DATA:AIA_APPROVAL_DESCRIPTION       as AIA_APPROVAL_DESCRIPTION
,DATA:AIA_APPROVAL_ITERATION         as AIA_APPROVAL_ITERATION
,DATA:AIA_APPROVAL_READY_FLAG        as AIA_APPROVAL_READY_FLAG
,DATA:AIA_APPROVED_AMOUNT            as AIA_APPROVED_AMOUNT
,DATA:AIA_ATTRIBUTE_CATEGORY         as AIA_ATTRIBUTE_CATEGORY
,DATA:AIA_AUTO_TAX_CALC_FLAG         as AIA_AUTO_TAX_CALC_FLAG
,DATA:AIA_AWT_FLAG                   as AIA_AWT_FLAG
,DATA:AIA_BASE_AMOUNT                as AIA_BASE_AMOUNT
,DATA:AIA_BATCH_ID                   as AIA_BATCH_ID
,DATA:AIA_CANCELLED_AMOUNT           as AIA_CANCELLED_AMOUNT
,DATA:AIA_CANCELLED_BY               as AIA_CANCELLED_BY
,DATA:AIA_CANCELLED_DATE             as AIA_CANCELLED_DATE
,DATA:AIA_CMG_AP_APPROVER            as AIA_CMG_AP_APPROVER
,DATA:AIA_CMG_AP_FAPPROVER           as AIA_CMG_AP_FAPPROVER
,DATA:AIA_CMG_AP_MODEL_NO            as AIA_CMG_AP_MODEL_NO
,DATA:AIA_CMG_AP_REMIT_TO            as AIA_CMG_AP_REMIT_TO
,DATA:AIA_CMG_AP_SERIAL_NO           as AIA_CMG_AP_SERIAL_NO
,DATA:AIA_CMG_FA_PRODN_LINE          as AIA_CMG_FA_PRODN_LINE
,DATA:AIA_CMG_GL_DETAIL_ACTIVITY     as AIA_CMG_GL_DETAIL_ACTIVITY
,DATA:AIA_CMG_GL_LOCATION            as AIA_CMG_GL_LOCATION
,DATA:AIA_CMG_PO_FLEET_WK_ORDER      as AIA_CMG_PO_FLEET_WK_ORDER
,DATA:AIA_CMG_PO_MANUF_NAME          as AIA_CMG_PO_MANUF_NAME
,DATA:AIA_CMG_PO_PHSE1A_PROJECT      as AIA_CMG_PO_PHSE1A_PROJECT
,DATA:AIA_CMG_PO_PHSE1A_TR_TYPE      as AIA_CMG_PO_PHSE1A_TR_TYPE
,DATA:AIA_CMG_PO_TAG_NUMBER          as AIA_CMG_PO_TAG_NUMBER
,DATA:AIA_CREATED_BY                 as AIA_CREATED_BY
,DATA:AIA_CREATION_DATE              as AIA_CREATION_DATE
,DATA:AIA_DESCRIPTION                as AIA_DESCRIPTION
,DATA:AIA_DISCOUNT_AMOUNT_TAKEN      as AIA_DISCOUNT_AMOUNT_TAKEN
,DATA:AIA_EARLIEST_SETTLEMENT_DATE   as AIA_EARLIEST_SETTLEMENT_DATE
,DATA:AIA_EXCHANGE_DATE              as AIA_EXCHANGE_DATE
,DATA:AIA_EXCHANGE_RATE              as AIA_EXCHANGE_RATE
,DATA:AIA_EXCHANGE_RATE_TYPE         as AIA_EXCHANGE_RATE_TYPE
,DATA:AIA_EXCLUSIVE_PAYMENT_FLAG     as AIA_EXCLUSIVE_PAYMENT_FLAG
,DATA:AIA_EXPENDITURE_ITEM_DATE      as AIA_EXPENDITURE_ITEM_DATE
,DATA:AIA_EXPENDITURE_ORG_ID         as AIA_EXPENDITURE_ORG_ID
,DATA:AIA_EXPENDITURE_TYPE           as AIA_EXPENDITURE_TYPE
,DATA:AIA_FREIGHT_AMOUNT             as AIA_FREIGHT_AMOUNT
,DATA:AIA_GL_DATE                    as AIA_GL_DATE
,DATA:AIA_INVOICE_AMOUNT             as AIA_INVOICE_AMOUNT
,DATA:AIA_INVOICE_CURRENCY_CODE      as AIA_INVOICE_CURRENCY_CODE
,DATA:AIA_INVOICE_DATE               as AIA_INVOICE_DATE
,DATA:AIA_INVOICE_ID                 as AIA_INVOICE_ID
,DATA:AIA_INVOICE_NUM                as AIA_INVOICE_NUM
,DATA:AIA_INVOICE_RECEIVED_DATE      as AIA_INVOICE_RECEIVED_DATE
,DATA:AIA_INVOICE_TYPE_LOOKUP_CODE   as AIA_INVOICE_TYPE_LOOKUP_CODE
,DATA:AIA_LAST_UPDATED_BY            as AIA_LAST_UPDATED_BY
,DATA:AIA_LAST_UPDATE_DATE           as AIA_LAST_UPDATE_DATE
,DATA:AIA_LAST_UPDATE_LOGIN          as AIA_LAST_UPDATE_LOGIN
,DATA:AIA_ORG_ID                     as AIA_ORG_ID
,DATA:AIA_ORIGINAL_PREPAYMENT_AMOUNT as AIA_ORIGINAL_PREPAYMENT_AMOUNT
,DATA:AIA_PAYMENT_CROSS_RATE         as AIA_PAYMENT_CROSS_RATE
,DATA:AIA_PAYMENT_CROSS_RATE_DATE    as AIA_PAYMENT_CROSS_RATE_DATE
,DATA:AIA_PAYMENT_CURRENCY_CODE      as AIA_PAYMENT_CURRENCY_CODE
,DATA:AIA_PAYMENT_METHOD_LOOKUP_CODE as AIA_PAYMENT_METHOD_LOOKUP_CODE
,DATA:AIA_PAYMENT_STATUS_FLAG        as AIA_PAYMENT_STATUS_FLAG
,DATA:AIA_PAY_CURR_INVOICE_AMOUNT    as AIA_PAY_CURR_INVOICE_AMOUNT
,DATA:AIA_PAY_GROUP_LOOKUP_CODE      as AIA_PAY_GROUP_LOOKUP_CODE
,DATA:AIA_PA_DEFAULT_DIST_CCID       as AIA_PA_DEFAULT_DIST_CCID
,DATA:AIA_POSTING_STATUS             as AIA_POSTING_STATUS
,DATA:AIA_PO_HEADER_ID               as AIA_PO_HEADER_ID
,DATA:AIA_PREPAY_FLAG                as AIA_PREPAY_FLAG
,DATA:AIA_PROJECT_ID                 as AIA_PROJECT_ID
,DATA:AIA_RECURRING_PAYMENT_ID       as AIA_RECURRING_PAYMENT_ID
,DATA:AIA_SET_OF_BOOKS_ID            as AIA_SET_OF_BOOKS_ID
,DATA:AIA_SOURCE                     as AIA_SOURCE
,DATA:AIA_TASK_ID                    as AIA_TASK_ID
,DATA:AIA_TEMP_CANCELLED_AMOUNT      as AIA_TEMP_CANCELLED_AMOUNT
,DATA:AIA_TERMS_DATE                 as AIA_TERMS_DATE
,DATA:AIA_TERMS_ID                   as AIA_TERMS_ID
,DATA:AIA_VALIDATED_TAX_AMOUNT       as AIA_VALIDATED_TAX_AMOUNT
,DATA:AIA_VAT_CODE                   as AIA_VAT_CODE
,DATA:AIA_VENDOR_ID                  as AIA_VENDOR_ID
,DATA:AIA_VENDOR_PREPAY_AMOUNT       as AIA_VENDOR_PREPAY_AMOUNT
,DATA:AIA_VENDOR_SITE_ID             as AIA_VENDOR_SITE_ID
,DATA:AIA_WFAPPROVAL_STATUS          as AIA_WFAPPROVAL_STATUS
,FILENAME                            AS METADATA_FILENAME 
,FILE_ROW_NUMBER                     AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                  AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                     AS METADATA_START_SCAN_TIME
from {{ source("landing_ebs", "CM50_AP_INVOICES_ALL") }}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM
                    {{ source("landing_ebs", "CM50_AP_INVOICES_ALL") }}
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )