{{
  config(
    materialized = "view",
    alias = "cm50_po_lines_all",
    schema='EBS'
  )
}}

SELECT 
 DATA:"POL_PO_LINE_ID" AS POL_PO_LINE_ID
,DATA:"POL_LAST_UPDATE_DATE" AS POL_LAST_UPDATE_DATE
,DATA:"POL_LAST_UPDATED_BY" AS POL_LAST_UPDATED_BY
,DATA:"POL_PO_HEADER_ID" AS POL_PO_HEADER_ID
,DATA:"POL_LINE_TYPE_ID" AS POL_LINE_TYPE_ID
,DATA:"POL_LINE_NUM" AS POL_LINE_NUM
,DATA:"POL_LAST_UPDATE_LOGIN" AS POL_LAST_UPDATE_LOGIN
,DATA:"POL_CREATION_DATE" AS POL_CREATION_DATE
,DATA:"POL_CREATED_BY" AS POL_CREATED_BY
,DATA:"POL_ITEM_ID" AS POL_ITEM_ID
,DATA:"POL_ITEM_REVISION" AS POL_ITEM_REVISION
,DATA:"POL_CATEGORY_ID" AS POL_CATEGORY_ID
,DATA:"POL_ITEM_DESCRIPTION" AS POL_ITEM_DESCRIPTION
,DATA:"POL_UNIT_MEAS_LOOKUP_CODE" AS POL_UNIT_MEAS_LOOKUP_CODE
,DATA:"POL_QUANTITY_COMMITTED" AS POL_QUANTITY_COMMITTED
,DATA:"POL_ALLOW_PRICE_OVERRIDE_FLAG" AS POL_ALLOW_PRICE_OVERRIDE_FLAG
,DATA:"POL_LIST_PRICE_PER_UNIT" AS POL_LIST_PRICE_PER_UNIT
,DATA:"POL_UNIT_PRICE" AS POL_UNIT_PRICE
,DATA:"POL_QUANTITY" AS POL_QUANTITY
,DATA:"POL_NOTE_TO_VENDOR" AS POL_NOTE_TO_VENDOR
,DATA:"POL_FROM_HEADER_ID" AS POL_FROM_HEADER_ID
,DATA:"POL_FROM_LINE_ID" AS POL_FROM_LINE_ID
,DATA:"POL_QTY_RCV_TOLERANCE" AS POL_QTY_RCV_TOLERANCE
,DATA:"POL_OVER_TOLERANCE_ERROR_FLAG" AS POL_OVER_TOLERANCE_ERROR_FLAG
,DATA:"POL_MARKET_PRICE" AS POL_MARKET_PRICE
,DATA:"POL_UNORDERED_FLAG" AS POL_UNORDERED_FLAG
,DATA:"POL_CLOSED_FLAG" AS POL_CLOSED_FLAG
,DATA:"POL_USER_HOLD_FLAG" AS POL_USER_HOLD_FLAG
,DATA:"POL_CANCEL_FLAG" AS POL_CANCEL_FLAG
,DATA:"POL_CANCELLED_BY" AS POL_CANCELLED_BY
,DATA:"POL_CANCEL_DATE" AS POL_CANCEL_DATE
,DATA:"POL_CANCEL_REASON" AS POL_CANCEL_REASON
,DATA:"POL_FIRM_STATUS_LOOKUP_CODE" AS POL_FIRM_STATUS_LOOKUP_CODE
,DATA:"POL_VENDOR_PRODUCT_NUM" AS POL_VENDOR_PRODUCT_NUM
,DATA:"POL_TAXABLE_FLAG" AS POL_TAXABLE_FLAG
,DATA:"POL_TAX_NAME" AS POL_TAX_NAME
,DATA:"POL_TYPE_1099" AS POL_TYPE_1099
,DATA:"POL_CAPITAL_EXPENSE_FLAG" AS POL_CAPITAL_EXPENSE_FLAG
,DATA:"POL_NEGOTIATED_FLAG" AS POL_NEGOTIATED_FLAG
,DATA:"POL_ATTRIBUTE1" AS POL_ATTRIBUTE1
,DATA:"POL_ATTRIBUTE2" AS POL_ATTRIBUTE2
,DATA:"POL_ATTRIBUTE3" AS POL_ATTRIBUTE3
,DATA:"POL_ATTRIBUTE4" AS POL_ATTRIBUTE4
,DATA:"POL_ATTRIBUTE5" AS POL_ATTRIBUTE5
,DATA:"POL_ATTRIBUTE6" AS POL_ATTRIBUTE6
,DATA:"POL_ATTRIBUTE7" AS POL_ATTRIBUTE7
,DATA:"POL_PRICE_TYPE_LOOKUP_CODE" AS POL_PRICE_TYPE_LOOKUP_CODE
,DATA:"POL_CLOSED_CODE" AS POL_CLOSED_CODE
,DATA:"POL_PRICE_BREAK_LOOKUP_CODE" AS POL_PRICE_BREAK_LOOKUP_CODE
,DATA:"POL_REQUEST_ID" AS POL_REQUEST_ID
,DATA:"POL_PROGRAM_APPLICATION_ID" AS POL_PROGRAM_APPLICATION_ID
,DATA:"POL_PROGRAM_ID" AS POL_PROGRAM_ID
,DATA:"POL_PROGRAM_UPDATE_DATE" AS POL_PROGRAM_UPDATE_DATE
,DATA:"POL_CLOSED_DATE" AS POL_CLOSED_DATE
,DATA:"POL_CLOSED_REASON" AS POL_CLOSED_REASON
,DATA:"POL_CLOSED_BY" AS POL_CLOSED_BY
,DATA:"POL_ORG_ID" AS POL_ORG_ID
,DATA:"POL_EXPIRATION_DATE" AS POL_EXPIRATION_DATE
,DATA:"POL_TAX_CODE_ID" AS POL_TAX_CODE_ID
,DATA:"POL_RETROACTIVE_DATE" AS POL_RETROACTIVE_DATE
,DATA:"POL_CONTRACT_ID" AS POL_CONTRACT_ID
,DATA:"POL_ORDER_TYPE_LOOKUP_CODE" AS POL_ORDER_TYPE_LOOKUP_CODE
,DATA:"POL_PURCHASE_BASIS" AS POL_PURCHASE_BASIS
,DATA:"POL_MATCHING_BASIS" AS POL_MATCHING_BASIS
,DATA:"POL_BASE_UNIT_PRICE" AS POL_BASE_UNIT_PRICE
,DATA:"POL_MANUAL_PRICE_CHANGE_FLAG" AS POL_MANUAL_PRICE_CHANGE_FLAG
    ,FILENAME                             AS METADATA_FILENAME 
    ,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
    ,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
    ,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
    from 
    {{ source("landing_ebs", "CM50_PO_LINES_ALL") }}
    WHERE
        split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
            SELECT
                min_timestamp
            FROM
                (
                    SELECT
                        split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                        split(FILENAME, '/') [3] AS type_file
                    FROM
                        {{ source("landing_ebs", "CM50_PO_LINES_ALL") }}
                    WHERE
                        type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                            ORDER BY
                                min_timestamp DESC
                        ) = 1
                )
            )