{{
  config(
    materialized = "view",
    alias = "pa_tasks",
    schema='EBS'
  )
}}

SELECT 
DATA:"CINT_STOP_DATE" AS CINT_STOP_DATE
,DATA:"CINT_ELIGIBLE_FLAG" AS CINT_ELIGIBLE_FLAG
,DATA:"RETIREMENT_COST_FLAG" AS RETIREMENT_COST_FLAG
,DATA:"LONG_TASK_NAME" AS LONG_TASK_NAME
,DATA:"NON_LABOR_DISC_REASON_CODE" AS NON_LABOR_DISC_REASON_CODE
,DATA:"LABOR_DISC_REASON_CODE" AS LABOR_DISC_REASON_CODE
,DATA:"NON_LAB_STD_BILL_RT_SCH_ID" AS NON_LAB_STD_BILL_RT_SCH_ID
,DATA:"TASKFUNC_COST_RATE_DATE" AS TASKFUNC_COST_RATE_DATE
,DATA:"TASKFUNC_COST_RATE_TYPE" AS TASKFUNC_COST_RATE_TYPE
,DATA:"EMP_BILL_RATE_SCHEDULE_ID" AS EMP_BILL_RATE_SCHEDULE_ID
,DATA:"JOB_BILL_RATE_SCHEDULE_ID" AS JOB_BILL_RATE_SCHEDULE_ID
,DATA:"RECORD_VERSION_NUMBER" AS RECORD_VERSION_NUMBER
,DATA:"WORK_TYPE_ID" AS WORK_TYPE_ID
,DATA:"OVR_REV_IND_RATE_SCH_ID" AS OVR_REV_IND_RATE_SCH_ID
,DATA:"OVR_INV_IND_RATE_SCH_ID" AS OVR_INV_IND_RATE_SCH_ID
,DATA:"OVR_COST_IND_RATE_SCH_ID" AS OVR_COST_IND_RATE_SCH_ID
,DATA:"NON_LABOR_SCH_TYPE" AS NON_LABOR_SCH_TYPE
,DATA:"LABOR_SCH_TYPE" AS LABOR_SCH_TYPE
,DATA:"INV_IND_SCH_FIXED_DATE" AS INV_IND_SCH_FIXED_DATE
,DATA:"COST_IND_SCH_FIXED_DATE" AS COST_IND_SCH_FIXED_DATE
,DATA:"INV_IND_RATE_SCH_ID" AS INV_IND_RATE_SCH_ID
,DATA:"REV_IND_RATE_SCH_ID" AS REV_IND_RATE_SCH_ID
,DATA:"COST_IND_RATE_SCH_ID" AS COST_IND_RATE_SCH_ID
,DATA:"ATTRIBUTE10" AS ATTRIBUTE10
,DATA:"ATTRIBUTE9" AS ATTRIBUTE9
,DATA:"ATTRIBUTE8" AS ATTRIBUTE8
,DATA:"ATTRIBUTE7" AS ATTRIBUTE7
,DATA:"ATTRIBUTE6" AS ATTRIBUTE6
,DATA:"ATTRIBUTE5" AS ATTRIBUTE5
,DATA:"ATTRIBUTE4" AS ATTRIBUTE4
,DATA:"ATTRIBUTE2" AS ATTRIBUTE2
,DATA:"ATTRIBUTE_CATEGORY" AS ATTRIBUTE_CATEGORY
,DATA:"PROGRAM_UPDATE_DATE" AS PROGRAM_UPDATE_DATE
,DATA:"PROGRAM_ID" AS PROGRAM_ID
,DATA:"REQUEST_ID" AS REQUEST_ID
,DATA:"LABOR_COST_MULTIPLIER_NAME" AS LABOR_COST_MULTIPLIER_NAME
,DATA:"NON_LABOR_SCHEDULE_DISCOUNT" AS NON_LABOR_SCHEDULE_DISCOUNT
,DATA:"NON_LABOR_SCHEDULE_FIXED_DATE" AS NON_LABOR_SCHEDULE_FIXED_DATE
,DATA:"NON_LABOR_STD_BILL_RATE_SCHDL" AS NON_LABOR_STD_BILL_RATE_SCHDL
,DATA:"NON_LABOR_BILL_RATE_ORG_ID" AS NON_LABOR_BILL_RATE_ORG_ID
,DATA:"LABOR_SCHEDULE_DISCOUNT" AS LABOR_SCHEDULE_DISCOUNT
,DATA:"LABOR_SCHEDULE_FIXED_DATE" AS LABOR_SCHEDULE_FIXED_DATE
,DATA:"LABOR_BILL_RATE_ORG_ID" AS LABOR_BILL_RATE_ORG_ID
,DATA:"ADDRESS_ID" AS ADDRESS_ID
,DATA:"COMPLETION_DATE" AS COMPLETION_DATE
,DATA:"START_DATE" AS START_DATE
,DATA:"LIMIT_TO_TXN_CONTROLS_FLAG" AS LIMIT_TO_TXN_CONTROLS_FLAG
,DATA:"BILLABLE_FLAG" AS BILLABLE_FLAG
,DATA:"CHARGEABLE_FLAG" AS CHARGEABLE_FLAG
,DATA:"TASK_MANAGER_PERSON_ID" AS TASK_MANAGER_PERSON_ID
,DATA:"SERVICE_TYPE_CODE" AS SERVICE_TYPE_CODE
,DATA:"CARRYING_OUT_ORGANIZATION_ID" AS CARRYING_OUT_ORGANIZATION_ID
,DATA:"DESCRIPTION" AS DESCRIPTION
,DATA:"PARENT_TASK_ID" AS PARENT_TASK_ID
,DATA:"READY_TO_DISTRIBUTE_FLAG" AS READY_TO_DISTRIBUTE_FLAG
,DATA:"WBS_LEVEL" AS WBS_LEVEL
,DATA:"TOP_TASK_ID" AS TOP_TASK_ID
,DATA:"TASK_NAME" AS TASK_NAME
,DATA:"LAST_UPDATE_LOGIN" AS LAST_UPDATE_LOGIN
,DATA:"LAST_UPDATED_BY" AS LAST_UPDATED_BY
,DATA:"LAST_UPDATE_DATE" AS LAST_UPDATE_DATE
,DATA:"CREATED_BY" AS CREATED_BY
,DATA:"CREATION_DATE" AS CREATION_DATE
,DATA:"TASK_NUMBER" AS TASK_NUMBER
,DATA:"PROJECT_ID" AS PROJECT_ID
,DATA:"TASK_ID" AS TASK_ID
,DATA:"ADW_NOTIFY_FLAG" AS ADW_NOTIFY_FLAG
,DATA:"ALLOW_CROSS_CHARGE_FLAG" AS ALLOW_CROSS_CHARGE_FLAG
,DATA:"GEN_ETC_SOURCE_CODE" AS GEN_ETC_SOURCE_CODE
,DATA:"EARLY_FINISH_DATE" AS EARLY_FINISH_DATE
,DATA:"EARLY_START_DATE" AS EARLY_START_DATE
,DATA:"ACTUAL_FINISH_DATE" AS ACTUAL_FINISH_DATE
,DATA:"ACTUAL_START_DATE" AS ACTUAL_START_DATE
,DATA:"PM_TASK_REFERENCE" AS PM_TASK_REFERENCE
,DATA:"PM_PRODUCT_CODE" AS PM_PRODUCT_CODE
,DATA:"CUSTOMER_ID" AS CUSTOMER_ID
,DATA:"PROGRAM_APPLICATION_ID" AS PROGRAM_APPLICATION_ID
,DATA:"BILL_SCHE_OVRD_FLAG" AS BILL_SCHE_OVRD_FLAG
,DATA:"INVOICE_METHOD" AS INVOICE_METHOD
,DATA:"REVENUE_ACCRUAL_METHOD" AS REVENUE_ACCRUAL_METHOD
,DATA:"RECEIVE_PROJECT_INVOICE_FLAG" AS RECEIVE_PROJECT_INVOICE_FLAG
,DATA:"NL_TP_FIXED_DATE" AS NL_TP_FIXED_DATE
,DATA:"NL_TP_SCHEDULE_ID" AS NL_TP_SCHEDULE_ID
,DATA:"CC_PROCESS_NL_FLAG" AS CC_PROCESS_NL_FLAG
,DATA:"LABOR_TP_FIXED_DATE" AS LABOR_TP_FIXED_DATE
,DATA:"LABOR_TP_SCHEDULE_ID" AS LABOR_TP_SCHEDULE_ID
,DATA:"CC_PROCESS_LABOR_FLAG" AS CC_PROCESS_LABOR_FLAG
,DATA:"PROJECT_RATE_TYPE" AS PROJECT_RATE_TYPE
,DATA:"PROJECT_RATE_DATE" AS PROJECT_RATE_DATE
,DATA:"SCHEDULED_FINISH_DATE" AS SCHEDULED_FINISH_DATE
,DATA:"SCHEDULED_START_DATE" AS SCHEDULED_START_DATE
,DATA:"LATE_FINISH_DATE" AS LATE_FINISH_DATE
,DATA:"LATE_START_DATE" AS LATE_START_DATE
,DATA:"ATTRIBUTE1" AS ATTRIBUTE1
,DATA:"REV_IND_SCH_FIXED_DATE" AS REV_IND_SCH_FIXED_DATE
,DATA:"ATTRIBUTE3" AS ATTRIBUTE3
,DATA:"LABOR_STD_BILL_RATE_SCHDL" AS LABOR_STD_BILL_RATE_SCHDL
,DATA:"READY_TO_BILL_FLAG" AS READY_TO_BILL_FLAG
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM {{ source("landing_ebs", "PA_TASKS") }}
-- -- to only take the files after the last fullLoad
--   WHERE 
--   split(FILENAME, '_')[array_size(split(FILENAME, '_')) - 2] >=
--     (SELECT min_timestamp
--   FROM
--       (SELECT split(FILENAME, '_')[array_size(split(FILENAME, '_')) - 2] AS min_timestamp, split(FILENAME, '/')[3] AS type_file
--       FROM {{ source("landing_ebs", "PER_ORG_STRUCTURE_ELEMENTS_V") }}
--       WHERE type_file LIKE 'fullload%'
--       QUALIFY ROW_NUMBER() OVER (ORDER BY min_timestamp DESC) = 1)
--     )