{{
  config(
    materialized = "view",
    alias = "cm50_po_supplier_site",
    schema='EBS'
  )
}}

SELECT
DATA:ATE_DESCRIPTION                as ATE_DESCRIPTION
,DATA:ATE_ENABLED_FLAG              as ATE_ENABLED_FLAG
,DATA:ATE_NAME                      as ATE_NAME
,DATA:ATE_START_DATE_ACTIVE         as ATE_START_DATE_ACTIVE
,DATA:ATE_TERM_ID                   as ATE_TERM_ID
,DATA:ATE_TYPE                      as ATE_TYPE
,DATA:FNT_CREATED_BY                as FNT_CREATED_BY
,DATA:FNT_CREATION_DATE             as FNT_CREATION_DATE
,DATA:FNT_EU_CODE                   as FNT_EU_CODE
,DATA:FNT_ISO_NUMERIC_CODE          as FNT_ISO_NUMERIC_CODE
,DATA:FNT_ISO_TERRITORY_CODE        as FNT_ISO_TERRITORY_CODE
,DATA:FNT_LAST_UPDATED_BY           as FNT_LAST_UPDATED_BY
,DATA:FNT_LAST_UPDATE_DATE          as FNT_LAST_UPDATE_DATE
,DATA:FNT_LAST_UPDATE_LOGIN         as FNT_LAST_UPDATE_LOGIN
,DATA:FNT_NLS_TERRITORY             as FNT_NLS_TERRITORY
,DATA:FNT_OBSOLETE_FLAG             as FNT_OBSOLETE_FLAG
,DATA:FNT_TERRITORY_CODE            as FNT_TERRITORY_CODE
,DATA:PVS_ACCTS_PAY_CODE_COMB_ID    as PVS_ACCTS_PAY_CODE_COMB_ID
,DATA:PVS_ADDRESS_LINE1             as PVS_ADDRESS_LINE1
,DATA:PVS_ADDRESS_LINE2             as PVS_ADDRESS_LINE2
,DATA:PVS_ADDRESS_LINE3             as PVS_ADDRESS_LINE3
,DATA:PVS_ADDRESS_LINE4             as PVS_ADDRESS_LINE4
,DATA:PVS_ADDRESS_LINES_ALT         as PVS_ADDRESS_LINES_ALT
,DATA:PVS_ALLOW_AWT_FLAG            as PVS_ALLOW_AWT_FLAG
,DATA:PVS_ALWAYS_TAKE_DISC_FLAG     as PVS_ALWAYS_TAKE_DISC_FLAG
,DATA:PVS_AMOUNT_INCLUDES_TAX_FLAG  as PVS_AMOUNT_INCLUDES_TAX_FLAG
,DATA:PVS_AP_TAX_ROUNDING_RULE      as PVS_AP_TAX_ROUNDING_RULE
,DATA:PVS_AREA_CODE                 as PVS_AREA_CODE
,DATA:PVS_ATTENTION_AR_FLAG         as PVS_ATTENTION_AR_FLAG
,DATA:PVS_AUTO_TAX_CALC_FLAG        as PVS_AUTO_TAX_CALC_FLAG
,DATA:PVS_AUTO_TAX_CALC_OVERRIDE    as PVS_AUTO_TAX_CALC_OVERRIDE
,DATA:PVS_BANK_ACCOUNT_NAME         as PVS_BANK_ACCOUNT_NAME
,DATA:PVS_BANK_ACCOUNT_NUM          as PVS_BANK_ACCOUNT_NUM
,DATA:PVS_BANK_CHARGE_BEARER        as PVS_BANK_CHARGE_BEARER
,DATA:PVS_BANK_NUM                  as PVS_BANK_NUM
,DATA:PVS_BANK_NUMBER               as PVS_BANK_NUMBER
,DATA:PVS_BILL_TO_LOCATION_ID       as PVS_BILL_TO_LOCATION_ID
,DATA:PVS_CAN_SPM_VENDOR_NUMBER     as PVS_CAN_SPM_VENDOR_NUMBER
,DATA:PVS_CITY                      as PVS_CITY
,DATA:PVS_COUNTRY                   as PVS_COUNTRY
,DATA:PVS_COUNTY                    as PVS_COUNTY
,DATA:PVS_CREATED_BY                as PVS_CREATED_BY
,DATA:PVS_CREATE_DEBIT_MEMO_FLAG    as PVS_CREATE_DEBIT_MEMO_FLAG
,DATA:PVS_CREATION_DATE             as PVS_CREATION_DATE
,DATA:PVS_CUSTOMER_NUM              as PVS_CUSTOMER_NUM
,DATA:PVS_DISTRIBUTION_SET_ID       as PVS_DISTRIBUTION_SET_ID
,DATA:PVS_EDI_TRANSACTION_HANDLING  as PVS_EDI_TRANSACTION_HANDLING
,DATA:PVS_EMAIL                     as PVS_EMAIL
,DATA:PVS_EMAIL_ADDRESS             as PVS_EMAIL_ADDRESS
,DATA:PVS_EXCLUSIVE_PAYMENT_FLAG    as PVS_EXCLUSIVE_PAYMENT_FLAG
,DATA:PVS_EXCLU_FREIGHT_FR_DISCOUNT as PVS_EXCLU_FREIGHT_FR_DISCOUNT
,DATA:PVS_EXCLU_TAXES_FR_DISCOUNT   as PVS_EXCLU_TAXES_FR_DISCOUNT
,DATA:PVS_FAX                       as PVS_FAX
,DATA:PVS_FAX_AREA_CODE             as PVS_FAX_AREA_CODE
,DATA:PVS_FREIGHT_TERMS_LOOKUP_CODE as PVS_FREIGHT_TERMS_LOOKUP_CODE
,DATA:PVS_GST_HST_NUMBER            as PVS_GST_HST_NUMBER
,DATA:PVS_HOLD_ALL_PAYMENTS_FLAG    as PVS_HOLD_ALL_PAYMENTS_FLAG
,DATA:PVS_HOLD_FUTURE_PAYMENTS_FLAG as PVS_HOLD_FUTURE_PAYMENTS_FLAG
,DATA:PVS_HOLD_REASON               as PVS_HOLD_REASON
,DATA:PVS_HOLD_UNMATCHED_INV_FLAG   as PVS_HOLD_UNMATCHED_INV_FLAG
,DATA:PVS_INACTIVE_DATE             as PVS_INACTIVE_DATE
,DATA:PVS_INVOICE_CURRENCY_CODE     as PVS_INVOICE_CURRENCY_CODE
,DATA:PVS_LANGUAGE                  as PVS_LANGUAGE
,DATA:PVS_LAST_UPDATED_BY           as PVS_LAST_UPDATED_BY
,DATA:PVS_LAST_UPDATE_DATE          as PVS_LAST_UPDATE_DATE
,DATA:PVS_LAST_UPDATE_LOGIN         as PVS_LAST_UPDATE_LOGIN
,DATA:PVS_MATCH_OPTION              as PVS_MATCH_OPTION
,DATA:PVS_OFFSET_TAX_FLAG           as PVS_OFFSET_TAX_FLAG
,DATA:PVS_ORG_ID                    as PVS_ORG_ID
,DATA:PVS_PAYMENT_CURRENCY_CODE     as PVS_PAYMENT_CURRENCY_CODE
,DATA:PVS_PAYMENT_METHOD            as PVS_PAYMENT_METHOD
,DATA:PVS_PAYMENT_METHOD_LOOKUP_CODE as PVS_PAYMENT_METHOD_LOOKUP_CODE
,DATA:PVS_PAYMENT_PRIORITY          as PVS_PAYMENT_PRIORITY
,DATA:PVS_PAY_DATE_BASIS_LOOKUP_CODE as PVS_PAY_DATE_BASIS_LOOKUP_CODE
,DATA:PVS_PAY_GROUP_LOOKUP_CODE     as PVS_PAY_GROUP_LOOKUP_CODE
,DATA:PVS_PAY_SITE_FLAG             as PVS_PAY_SITE_FLAG
,DATA:PVS_PCARD_SITE_FLAG           as PVS_PCARD_SITE_FLAG
,DATA:PVS_PHONE                     as PVS_PHONE
,DATA:PVS_PREPAY_CODE_COMBINATION_ID as PVS_PREPAY_CODE_COMBINATION_ID
,DATA:PVS_PRIMARY_PAY_SITE_FLAG     as PVS_PRIMARY_PAY_SITE_FLAG
,DATA:PVS_PROVINCE                  as PVS_PROVINCE
,DATA:PVS_PURCHASING_SITE_FLAG      as PVS_PURCHASING_SITE_FLAG
,DATA:PVS_PURCHASING_SPN            as PVS_PURCHASING_SPN
,DATA:PVS_QST_NUMBER                as PVS_QST_NUMBER
,DATA:PVS_RFQ_ONLY_SITE_FLAG        as PVS_RFQ_ONLY_SITE_FLAG
,DATA:PVS_SHIP_VIA_LOOKUP_CODE      as PVS_SHIP_VIA_LOOKUP_CODE
,DATA:PVS_STATE                     as PVS_STATE
,DATA:PVS_TAX_REPORTING_SITE_FLAG   as PVS_TAX_REPORTING_SITE_FLAG
,DATA:PVS_TELEX                     as PVS_TELEX
,DATA:PVS_TERMS_DATE_BASIS          as PVS_TERMS_DATE_BASIS
,DATA:PVS_TERMS_ID                  as PVS_TERMS_ID
,DATA:PVS_TOLERANCE_ID              as PVS_TOLERANCE_ID
,DATA:PVS_USA_SPM_VENDOR_NUMBER     as PVS_USA_SPM_VENDOR_NUMBER
,DATA:PVS_VALIDATION_NUMBER         as PVS_VALIDATION_NUMBER
,DATA:PVS_VAT_CODE                  as PVS_VAT_CODE
,DATA:PVS_VAT_REGISTRATION_NUM      as PVS_VAT_REGISTRATION_NUM
,DATA:PVS_VENDOR_ID                 as PVS_VENDOR_ID
,DATA:PVS_VENDOR_SITE_CODE          as PVS_VENDOR_SITE_CODE
,DATA:PVS_VENDOR_SITE_CODE_ALT      as PVS_VENDOR_SITE_CODE_ALT
,DATA:PVS_VENDOR_SITE_ID            as PVS_VENDOR_SITE_ID
,DATA:PVS_ZIP                       as PVS_ZIP
,DATA:src_system_operation          as src_system_operation
,FILENAME                           as METADATA_FILENAME 
,FILE_ROW_NUMBER                    as METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                 as METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                    as METADATA_START_SCAN_TIME
from {{ source("landing_ebs", "CM50_PO_SUPPLIER_SITE") }}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM
                    {{ source("landing_ebs", "CM50_PO_SUPPLIER_SITE") }}
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )