{{
  config(
    materialized = "view",
    alias = "cmg_dw_projects_etl",
    schema='EBS'
  )
}}

SELECT DATA:"PROJECT_CODE" AS PROJECT_CODE
    ,DATA:"PROJECT_NAME" AS PROJECT_NAME
    ,DATA:"PROJECT_SALESREP" AS PROJECT_SALESREP
    ,DATA:"PROJECT_MANAGER" AS PROJECT_MANAGER
    ,DATA:"COORDINATOR_NAME" AS COORDINATOR_NAME
    ,DATA:"PROJECT_MANAGER_EMAIL" AS PROJECT_MANAGER_EMAIL
    ,DATA:"PROJECT_SALESREP_GLCIE" AS PROJECT_SALESREP_GLCIE
    ,DATA:"PROJECT_SALESREP_REGION" AS PROJECT_SALESREP_REGION
    ,DATA:"PROJECT_SALESREP_SUBREGION" AS PROJECT_SALESREP_SUBREGION
    ,DATA:"PROJECT_CURRENCY" AS PROJECT_CURRENCY
    ,DATA:"PROJECT_STATUS_CODE" AS PROJECT_STATUS_CODE
    ,DATA:"PROJECT_TYPE" AS PROJECT_TYPE
    ,DATA:"PROJECT_START_DATE" AS PROJECT_START_DATE
    ,DATA:"PROJECT_CLOSE_DATE" AS PROJECT_CLOSE_DATE
    ,DATA:"PROJECT_COMPLETION_DATE" AS PROJECT_COMPLETION_DATE
    ,DATA:"PROJECT_CREATION_DATE" AS PROJECT_CREATION_DATE
    ,DATA:"CLASS_CATEGORY" AS CLASS_CATEGORY
    ,DATA:"CLASS_CODE" AS CLASS_CODE
    ,DATA:"CLASS_DESCRIPTION" AS CLASS_DESCRIPTION
    ,DATA:"BILL_TO_NUMBER" AS BILL_TO_NUMBER
    ,DATA:"BILL_TO_ORG_ID" AS BILL_TO_ORG_ID
    ,DATA:"SHIP_ADDRESS1" AS SHIP_ADDRESS1
    ,DATA:"SHIP_ADDRESS2" AS SHIP_ADDRESS2
    ,DATA:"SHIP_ADDRESS3" AS SHIP_ADDRESS3
    ,DATA:"SHIP_POSTAL_CODE" AS SHIP_POSTAL_CODE
    ,DATA:"SHIP_CITY" AS SHIP_CITY
    ,DATA:"SHIP_STATE_PROV" AS SHIP_STATE_PROV
    ,DATA:"SHIP_COUNTY" AS SHIP_COUNTY
    ,DATA:"SHIP_COUNTRY" AS SHIP_COUNTRY
    ,DATA:"RELATED_PROJECT_CODE" AS RELATED_PROJECT_CODE
    ,DATA:"CARRYING_OUT_ORGANIZATION_ID" AS CARRYING_OUT_ORGANIZATION_ID
    ,DATA:"BUSINESS_UNITS_CODE" AS BUSINESS_UNITS_CODE
    ,DATA:"PROJECT_CURRENCY_RATE" AS PROJECT_CURRENCY_RATE
    ,DATA:"LAST_UPDATE_DATE" AS LAST_UPDATE_DATE
    ,FILENAME AS METADATA_FILENAME 
    ,FILE_ROW_NUMBER AS METADATA_FILE_ROW_NUMBER
    ,FILE_LAST_MODIFIED AS METADATA_FILE_LAST_MODIFIED
    ,START_SCAN_TIME AS METADATA_START_SCAN_TIME
FROM
    {{ source("landing_ebs", "CMG_DW_PROJECTS_ETL")}}
    -- to only take the files after the last fullLoad
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM
                    {{ source("landing_ebs", "CMG_DW_PROJECTS_ETL")}}
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
    )