{{
  config(
    materialized = "view",
    alias = "fnd_flex_value_sets",
    schema='EBS'
  )
}}

SELECT DATA:"FORMAT_TYPE" AS FORMAT_TYPE
,DATA:"LONGLIST_FLAG" AS LONGLIST_FLAG
,DATA:"SECURITY_ENABLED_FLAG" AS SECURITY_ENABLED_FLAG
,DATA:"PROTECTED_FLAG" AS PROTECTED_FLAG
,DATA:"VALIDATION_TYPE" AS VALIDATION_TYPE
,DATA:"LAST_UPDATE_LOGIN" AS LAST_UPDATE_LOGIN
,DATA:"CREATED_BY" AS CREATED_BY
,DATA:"CREATION_DATE" AS CREATION_DATE
,DATA:"LAST_UPDATED_BY" AS LAST_UPDATED_BY
,DATA:"LAST_UPDATE_DATE" AS LAST_UPDATE_DATE
,DATA:"FLEX_VALUE_SET_NAME" AS FLEX_VALUE_SET_NAME
,DATA:"NUMBER_PRECISION" AS NUMBER_PRECISION
,DATA:"MAXIMUM_VALUE" AS MAXIMUM_VALUE
,DATA:"MINIMUM_VALUE" AS MINIMUM_VALUE
,DATA:"PARENT_FLEX_VALUE_SET_ID" AS PARENT_FLEX_VALUE_SET_ID
,DATA:"DEPENDANT_DEFAULT_MEANING" AS DEPENDANT_DEFAULT_MEANING
,DATA:"DEPENDANT_DEFAULT_VALUE" AS DEPENDANT_DEFAULT_VALUE
,DATA:"DESCRIPTION" AS DESCRIPTION
,DATA:"NUMERIC_MODE_ENABLED_FLAG" AS NUMERIC_MODE_ENABLED_FLAG
,DATA:"UPPERCASE_ONLY_FLAG" AS UPPERCASE_ONLY_FLAG
,DATA:"ALPHANUMERIC_ALLOWED_FLAG" AS ALPHANUMERIC_ALLOWED_FLAG
,DATA:"MAXIMUM_SIZE" AS MAXIMUM_SIZE
,DATA:"FLEX_VALUE_SET_ID" AS FLEX_VALUE_SET_ID
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM
    {{ source("landing_ebs", "FND_FLEX_VALUE_SETS")}}
    -- to only take the files after the last fullLoad
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM
                    {{ source("landing_ebs", "FND_FLEX_VALUE_SETS")}}
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )