{{
  config(
    materialized = "view",
    alias = "fnd_flex_values",
    schema='EBS',
    tags=["fnd_flex_values"]
  )
}}

SELECT DATA:"FLEX_VALUE_SET_ID" AS FLEX_VALUE_SET_ID
,DATA:"FLEX_VALUE_ID" AS FLEX_VALUE_ID
,DATA:"FLEX_VALUE" AS FLEX_VALUE
,DATA:"LAST_UPDATE_DATE" AS LAST_UPDATE_DATE
,DATA:"LAST_UPDATED_BY" AS LAST_UPDATED_BY
,DATA:"CREATION_DATE" AS CREATION_DATE
,DATA:"CREATED_BY" AS CREATED_BY
,DATA:"LAST_UPDATE_LOGIN" AS LAST_UPDATE_LOGIN
,DATA:"ENABLED_FLAG" AS ENABLED_FLAG
,DATA:"SUMMARY_FLAG" AS SUMMARY_FLAG
,DATA:"START_DATE_ACTIVE" AS START_DATE_ACTIVE
,DATA:"END_DATE_ACTIVE" AS END_DATE_ACTIVE
,DATA:"PARENT_FLEX_VALUE_LOW" AS PARENT_FLEX_VALUE_LOW
,DATA:"PARENT_FLEX_VALUE_HIGH" AS PARENT_FLEX_VALUE_HIGH
,DATA:"STRUCTURED_HIERARCHY_LEVEL" AS STRUCTURED_HIERARCHY_LEVEL
,DATA:"HIERARCHY_LEVEL" AS HIERARCHY_LEVEL
,DATA:"COMPILED_VALUE_ATTRIBUTES" AS COMPILED_VALUE_ATTRIBUTES
,DATA:"VALUE_CATEGORY" AS VALUE_CATEGORY
,DATA:"ATTRIBUTE1" AS ATTRIBUTE1
,DATA:"ATTRIBUTE2" AS ATTRIBUTE2
,DATA:"ATTRIBUTE3" AS ATTRIBUTE3
,DATA:"ATTRIBUTE4" AS ATTRIBUTE4
,DATA:"ATTRIBUTE5" AS ATTRIBUTE5
,DATA:"ATTRIBUTE6" AS ATTRIBUTE6
,DATA:"ATTRIBUTE7" AS ATTRIBUTE7
,DATA:"ATTRIBUTE8" AS ATTRIBUTE8
,DATA:"ATTRIBUTE9" AS ATTRIBUTE9
,DATA:"ATTRIBUTE10" AS ATTRIBUTE10
,DATA:"ATTRIBUTE11" AS ATTRIBUTE11
,DATA:"ATTRIBUTE12" AS ATTRIBUTE12
,DATA:"ATTRIBUTE13" AS ATTRIBUTE13
,DATA:"ATTRIBUTE14" AS ATTRIBUTE14
,DATA:"ATTRIBUTE15" AS ATTRIBUTE15
,DATA:"ATTRIBUTE16" AS ATTRIBUTE16
,DATA:"ATTRIBUTE17" AS ATTRIBUTE17
,DATA:"ATTRIBUTE18" AS ATTRIBUTE18
,DATA:"ATTRIBUTE19" AS ATTRIBUTE19
,DATA:"ATTRIBUTE20" AS ATTRIBUTE20
,DATA:"ATTRIBUTE21" AS ATTRIBUTE21
,DATA:"ATTRIBUTE22" AS ATTRIBUTE22
,DATA:"ATTRIBUTE23" AS ATTRIBUTE23
,DATA:"ATTRIBUTE24" AS ATTRIBUTE24
,DATA:"ATTRIBUTE25" AS ATTRIBUTE25
,DATA:"ATTRIBUTE26" AS ATTRIBUTE26
,DATA:"ATTRIBUTE27" AS ATTRIBUTE27
,DATA:"ATTRIBUTE28" AS ATTRIBUTE28
,DATA:"ATTRIBUTE29" AS ATTRIBUTE29
,DATA:"ATTRIBUTE30" AS ATTRIBUTE30
,DATA:"ATTRIBUTE31" AS ATTRIBUTE31
,DATA:"ATTRIBUTE32" AS ATTRIBUTE32
,DATA:"ATTRIBUTE33" AS ATTRIBUTE33
,DATA:"ATTRIBUTE34" AS ATTRIBUTE34
,DATA:"ATTRIBUTE35" AS ATTRIBUTE35
,DATA:"ATTRIBUTE36" AS ATTRIBUTE36
,DATA:"ATTRIBUTE37" AS ATTRIBUTE37
,DATA:"ATTRIBUTE38" AS ATTRIBUTE38
,DATA:"ATTRIBUTE39" AS ATTRIBUTE39
,DATA:"ATTRIBUTE40" AS ATTRIBUTE40
,DATA:"ATTRIBUTE41" AS ATTRIBUTE41
,DATA:"ATTRIBUTE42" AS ATTRIBUTE42
,DATA:"ATTRIBUTE43" AS ATTRIBUTE43
,DATA:"ATTRIBUTE44" AS ATTRIBUTE44
,DATA:"ATTRIBUTE45" AS ATTRIBUTE45
,DATA:"ATTRIBUTE46" AS ATTRIBUTE46
,DATA:"ATTRIBUTE47" AS ATTRIBUTE47
,DATA:"ATTRIBUTE48" AS ATTRIBUTE48
,DATA:"ATTRIBUTE49" AS ATTRIBUTE49
,DATA:"ATTRIBUTE50" AS ATTRIBUTE50
,DATA:"ATTRIBUTE_SORT_ORDER" AS ATTRIBUTE_SORT_ORDER
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM
    {{ source("landing_ebs", "FND_FLEX_VALUES")}}
    -- to only take the files after the last fullLoad
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM
                    {{ source("landing_ebs", "FND_FLEX_VALUES")}}
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )