{{
  config(
    materialized = "view",
    alias = "hz_party_sites",
    schema='EBS'
  )
}}

SELECT DATA:"PARTY_SITE_ID" AS PARTY_SITE_ID
,DATA:"PARTY_ID" AS PARTY_ID
,DATA:"LOCATION_ID" AS LOCATION_ID
,DATA:"LAST_UPDATE_DATE" AS LAST_UPDATE_DATE
,DATA:"PARTY_SITE_NUMBER" AS PARTY_SITE_NUMBER
,DATA:"LAST_UPDATED_BY" AS LAST_UPDATED_BY
,DATA:"CREATION_DATE" AS CREATION_DATE
,DATA:"CREATED_BY" AS CREATED_BY
,DATA:"LAST_UPDATE_LOGIN" AS LAST_UPDATE_LOGIN
,DATA:"REQUEST_ID" AS REQUEST_ID
,DATA:"PROGRAM_APPLICATION_ID" AS PROGRAM_APPLICATION_ID
,DATA:"PROGRAM_ID" AS PROGRAM_ID
,DATA:"PROGRAM_UPDATE_DATE" AS PROGRAM_UPDATE_DATE
,DATA:"WH_UPDATE_DATE" AS WH_UPDATE_DATE
,DATA:"ATTRIBUTE_CATEGORY" AS ATTRIBUTE_CATEGORY
,DATA:"ATTRIBUTE1" AS ATTRIBUTE1
,DATA:"ATTRIBUTE2" AS ATTRIBUTE2
,DATA:"ATTRIBUTE3" AS ATTRIBUTE3
,DATA:"ATTRIBUTE4" AS ATTRIBUTE4
,DATA:"ATTRIBUTE5" AS ATTRIBUTE5
,DATA:"ATTRIBUTE6" AS ATTRIBUTE6
,DATA:"ATTRIBUTE7" AS ATTRIBUTE7
,DATA:"ATTRIBUTE8" AS ATTRIBUTE8
,DATA:"ATTRIBUTE9" AS ATTRIBUTE9
,DATA:"ATTRIBUTE10" AS ATTRIBUTE10
,DATA:"ATTRIBUTE11" AS ATTRIBUTE11
,DATA:"ATTRIBUTE12" AS ATTRIBUTE12
,DATA:"ATTRIBUTE13" AS ATTRIBUTE13
,DATA:"ATTRIBUTE14" AS ATTRIBUTE14
,DATA:"ATTRIBUTE15" AS ATTRIBUTE15
,DATA:"ATTRIBUTE16" AS ATTRIBUTE16
,DATA:"ATTRIBUTE17" AS ATTRIBUTE17
,DATA:"ATTRIBUTE18" AS ATTRIBUTE18
,DATA:"ATTRIBUTE19" AS ATTRIBUTE19
,DATA:"ATTRIBUTE20" AS ATTRIBUTE20
,DATA:"GLOBAL_ATTRIBUTE_CATEGORY" AS GLOBAL_ATTRIBUTE_CATEGORY
,DATA:"GLOBAL_ATTRIBUTE1" AS GLOBAL_ATTRIBUTE1
,DATA:"GLOBAL_ATTRIBUTE2" AS GLOBAL_ATTRIBUTE2
,DATA:"GLOBAL_ATTRIBUTE3" AS GLOBAL_ATTRIBUTE3
,DATA:"GLOBAL_ATTRIBUTE4" AS GLOBAL_ATTRIBUTE4
,DATA:"GLOBAL_ATTRIBUTE5" AS GLOBAL_ATTRIBUTE5
,DATA:"GLOBAL_ATTRIBUTE6" AS GLOBAL_ATTRIBUTE6
,DATA:"GLOBAL_ATTRIBUTE7" AS GLOBAL_ATTRIBUTE7
,DATA:"GLOBAL_ATTRIBUTE8" AS GLOBAL_ATTRIBUTE8
,DATA:"GLOBAL_ATTRIBUTE9" AS GLOBAL_ATTRIBUTE9
,DATA:"GLOBAL_ATTRIBUTE10" AS GLOBAL_ATTRIBUTE10
,DATA:"GLOBAL_ATTRIBUTE11" AS GLOBAL_ATTRIBUTE11
,DATA:"GLOBAL_ATTRIBUTE12" AS GLOBAL_ATTRIBUTE12
,DATA:"GLOBAL_ATTRIBUTE13" AS GLOBAL_ATTRIBUTE13
,DATA:"GLOBAL_ATTRIBUTE14" AS GLOBAL_ATTRIBUTE14
,DATA:"GLOBAL_ATTRIBUTE15" AS GLOBAL_ATTRIBUTE15
,DATA:"GLOBAL_ATTRIBUTE16" AS GLOBAL_ATTRIBUTE16
,DATA:"GLOBAL_ATTRIBUTE17" AS GLOBAL_ATTRIBUTE17
,DATA:"GLOBAL_ATTRIBUTE18" AS GLOBAL_ATTRIBUTE18
,DATA:"GLOBAL_ATTRIBUTE19" AS GLOBAL_ATTRIBUTE19
,DATA:"GLOBAL_ATTRIBUTE20" AS GLOBAL_ATTRIBUTE20
,DATA:"ORIG_SYSTEM_REFERENCE" AS ORIG_SYSTEM_REFERENCE
,DATA:"START_DATE_ACTIVE" AS START_DATE_ACTIVE
,DATA:"END_DATE_ACTIVE" AS END_DATE_ACTIVE
,DATA:"REGION" AS REGION
,DATA:"MAILSTOP" AS MAILSTOP
,DATA:"CUSTOMER_KEY_OSM" AS CUSTOMER_KEY_OSM
,DATA:"PHONE_KEY_OSM" AS PHONE_KEY_OSM
,DATA:"CONTACT_KEY_OSM" AS CONTACT_KEY_OSM
,DATA:"IDENTIFYING_ADDRESS_FLAG" AS IDENTIFYING_ADDRESS_FLAG
,DATA:"LANGUAGE" AS LANGUAGE
,DATA:"STATUS" AS STATUS
,DATA:"PARTY_SITE_NAME" AS PARTY_SITE_NAME
,DATA:"ADDRESSEE" AS ADDRESSEE
,DATA:"OBJECT_VERSION_NUMBER" AS OBJECT_VERSION_NUMBER
,DATA:"CREATED_BY_MODULE" AS CREATED_BY_MODULE
,DATA:"APPLICATION_ID" AS APPLICATION_ID
,DATA:"ACTUAL_CONTENT_SOURCE" AS ACTUAL_CONTENT_SOURCE
,DATA:"GLOBAL_LOCATION_NUMBER" AS GLOBAL_LOCATION_NUMBER
,FILENAME                             AS METADATA_FILENAME 
,FILE_ROW_NUMBER                      AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                   AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                      AS METADATA_START_SCAN_TIME
FROM {{ source("landing_ebs", "HZ_PARTY_SITES") }}
-- to only take the files after the last fullLoad
  WHERE 
  split(FILENAME, '_')[array_size(split(FILENAME, '_')) - 2] >=
    (SELECT min_timestamp
  FROM
      (SELECT split(FILENAME, '_')[array_size(split(FILENAME, '_')) - 2] AS min_timestamp, split(FILENAME, '/')[3] AS type_file
      FROM {{ source("landing_ebs", "HZ_PARTY_SITES") }}
      WHERE type_file LIKE 'fullload%'
      QUALIFY ROW_NUMBER() OVER (ORDER BY min_timestamp DESC) = 1)
    )