{{
  config(
    materialized = "view",
    alias = "mtl_serial_numbers",
    schema='EBS'
  )
}}


SELECT
 DATA:"INVENTORY_ITEM_ID" AS INVENTORY_ITEM_ID
,DATA:"SERIAL_NUMBER" AS SERIAL_NUMBER
,DATA:"LAST_UPDATE_DATE" AS LAST_UPDATE_DATE
,DATA:"LAST_UPDATED_BY" AS LAST_UPDATED_BY
,DATA:"CREATION_DATE" AS CREATION_DATE
,DATA:"CREATED_BY" AS CREATED_BY
,DATA:"LAST_UPDATE_LOGIN" AS LAST_UPDATE_LOGIN
,DATA:"REQUEST_ID" AS REQUEST_ID
,DATA:"PROGRAM_APPLICATION_ID" AS PROGRAM_APPLICATION_ID
,DATA:"PROGRAM_ID" AS PROGRAM_ID
,DATA:"PROGRAM_UPDATE_DATE" AS PROGRAM_UPDATE_DATE
,DATA:"INITIALIZATION_DATE" AS INITIALIZATION_DATE
,DATA:"COMPLETION_DATE" AS COMPLETION_DATE
,DATA:"SHIP_DATE" AS SHIP_DATE
,DATA:"CURRENT_STATUS" AS CURRENT_STATUS
,DATA:"REVISION" AS REVISION
,DATA:"LOT_NUMBER" AS LOT_NUMBER
,DATA:"FIXED_ASSET_TAG" AS FIXED_ASSET_TAG
,DATA:"RESERVED_ORDER_ID" AS RESERVED_ORDER_ID
,DATA:"PARENT_ITEM_ID" AS PARENT_ITEM_ID
,DATA:"PARENT_SERIAL_NUMBER" AS PARENT_SERIAL_NUMBER
,DATA:"ORIGINAL_WIP_ENTITY_ID" AS ORIGINAL_WIP_ENTITY_ID
,DATA:"ORIGINAL_UNIT_VENDOR_ID" AS ORIGINAL_UNIT_VENDOR_ID
,DATA:"VENDOR_SERIAL_NUMBER" AS VENDOR_SERIAL_NUMBER
,DATA:"VENDOR_LOT_NUMBER" AS VENDOR_LOT_NUMBER
,DATA:"LAST_TXN_SOURCE_TYPE_ID" AS LAST_TXN_SOURCE_TYPE_ID
,DATA:"LAST_TRANSACTION_ID" AS LAST_TRANSACTION_ID
,DATA:"LAST_RECEIPT_ISSUE_TYPE" AS LAST_RECEIPT_ISSUE_TYPE
,DATA:"LAST_TXN_SOURCE_NAME" AS LAST_TXN_SOURCE_NAME
,DATA:"LAST_TXN_SOURCE_ID" AS LAST_TXN_SOURCE_ID
,DATA:"DESCRIPTIVE_TEXT" AS DESCRIPTIVE_TEXT
,DATA:"CURRENT_SUBINVENTORY_CODE" AS CURRENT_SUBINVENTORY_CODE
,DATA:"CURRENT_LOCATOR_ID" AS CURRENT_LOCATOR_ID
,DATA:"CURRENT_ORGANIZATION_ID" AS CURRENT_ORGANIZATION_ID
,DATA:"ATTRIBUTE_CATEGORY" AS ATTRIBUTE_CATEGORY
,DATA:"ATTRIBUTE1" AS ATTRIBUTE1
,DATA:"ATTRIBUTE2" AS ATTRIBUTE2
,DATA:"ATTRIBUTE3" AS ATTRIBUTE3
,DATA:"ATTRIBUTE4" AS ATTRIBUTE4
,DATA:"ATTRIBUTE5" AS ATTRIBUTE5
,DATA:"ATTRIBUTE6" AS ATTRIBUTE6
,DATA:"ATTRIBUTE7" AS ATTRIBUTE7
,DATA:"ATTRIBUTE8" AS ATTRIBUTE8
,DATA:"ATTRIBUTE9" AS ATTRIBUTE9
,DATA:"ATTRIBUTE10" AS ATTRIBUTE10
,DATA:"ATTRIBUTE11" AS ATTRIBUTE11
,DATA:"ATTRIBUTE12" AS ATTRIBUTE12
,DATA:"ATTRIBUTE13" AS ATTRIBUTE13
,DATA:"ATTRIBUTE14" AS ATTRIBUTE14
,DATA:"ATTRIBUTE15" AS ATTRIBUTE15
,DATA:"GROUP_MARK_ID" AS GROUP_MARK_ID
,DATA:"LINE_MARK_ID" AS LINE_MARK_ID
,DATA:"LOT_LINE_MARK_ID" AS LOT_LINE_MARK_ID
,DATA:"END_ITEM_UNIT_NUMBER" AS END_ITEM_UNIT_NUMBER
,DATA:"GEN_OBJECT_ID" AS GEN_OBJECT_ID
,DATA:"SERIAL_ATTRIBUTE_CATEGORY" AS SERIAL_ATTRIBUTE_CATEGORY
,DATA:"TERRITORY_CODE" AS TERRITORY_CODE
,DATA:"ORIGINATION_DATE" AS ORIGINATION_DATE
,DATA:"C_ATTRIBUTE1" AS C_ATTRIBUTE1
,DATA:"C_ATTRIBUTE2" AS C_ATTRIBUTE2
,DATA:"C_ATTRIBUTE3" AS C_ATTRIBUTE3
,DATA:"C_ATTRIBUTE4" AS C_ATTRIBUTE4
,DATA:"C_ATTRIBUTE5" AS C_ATTRIBUTE5
,DATA:"C_ATTRIBUTE6" AS C_ATTRIBUTE6
,DATA:"C_ATTRIBUTE7" AS C_ATTRIBUTE7
,DATA:"C_ATTRIBUTE8" AS C_ATTRIBUTE8
,DATA:"C_ATTRIBUTE9" AS C_ATTRIBUTE9
,DATA:"C_ATTRIBUTE10" AS C_ATTRIBUTE10
,DATA:"C_ATTRIBUTE11" AS C_ATTRIBUTE11
,DATA:"C_ATTRIBUTE12" AS C_ATTRIBUTE12
,DATA:"C_ATTRIBUTE13" AS C_ATTRIBUTE13
,DATA:"C_ATTRIBUTE14" AS C_ATTRIBUTE14
,DATA:"C_ATTRIBUTE15" AS C_ATTRIBUTE15
,DATA:"C_ATTRIBUTE16" AS C_ATTRIBUTE16
,DATA:"C_ATTRIBUTE17" AS C_ATTRIBUTE17
,DATA:"C_ATTRIBUTE18" AS C_ATTRIBUTE18
,DATA:"C_ATTRIBUTE19" AS C_ATTRIBUTE19
,DATA:"C_ATTRIBUTE20" AS C_ATTRIBUTE20
,DATA:"D_ATTRIBUTE1" AS D_ATTRIBUTE1
,DATA:"D_ATTRIBUTE2" AS D_ATTRIBUTE2
,DATA:"D_ATTRIBUTE3" AS D_ATTRIBUTE3
,DATA:"D_ATTRIBUTE4" AS D_ATTRIBUTE4
,DATA:"D_ATTRIBUTE5" AS D_ATTRIBUTE5
,DATA:"D_ATTRIBUTE6" AS D_ATTRIBUTE6
,DATA:"D_ATTRIBUTE7" AS D_ATTRIBUTE7
,DATA:"D_ATTRIBUTE8" AS D_ATTRIBUTE8
,DATA:"D_ATTRIBUTE9" AS D_ATTRIBUTE9
,DATA:"D_ATTRIBUTE10" AS D_ATTRIBUTE10
,DATA:"N_ATTRIBUTE1" AS N_ATTRIBUTE1
,DATA:"N_ATTRIBUTE2" AS N_ATTRIBUTE2
,DATA:"N_ATTRIBUTE3" AS N_ATTRIBUTE3
,DATA:"N_ATTRIBUTE4" AS N_ATTRIBUTE4
,DATA:"N_ATTRIBUTE5" AS N_ATTRIBUTE5
,DATA:"N_ATTRIBUTE6" AS N_ATTRIBUTE6
,DATA:"N_ATTRIBUTE7" AS N_ATTRIBUTE7
,DATA:"N_ATTRIBUTE8" AS N_ATTRIBUTE8
,DATA:"N_ATTRIBUTE9" AS N_ATTRIBUTE9
,DATA:"N_ATTRIBUTE10" AS N_ATTRIBUTE10
,DATA:"STATUS_ID" AS STATUS_ID
,DATA:"COST_GROUP_ID" AS COST_GROUP_ID
,DATA:"TIME_SINCE_NEW" AS TIME_SINCE_NEW
,DATA:"CYCLES_SINCE_NEW" AS CYCLES_SINCE_NEW
,DATA:"TIME_SINCE_OVERHAUL" AS TIME_SINCE_OVERHAUL
,DATA:"CYCLES_SINCE_OVERHAUL" AS CYCLES_SINCE_OVERHAUL
,DATA:"TIME_SINCE_REPAIR" AS TIME_SINCE_REPAIR
,DATA:"CYCLES_SINCE_REPAIR" AS CYCLES_SINCE_REPAIR
,DATA:"TIME_SINCE_VISIT" AS TIME_SINCE_VISIT
,DATA:"CYCLES_SINCE_VISIT" AS CYCLES_SINCE_VISIT
,DATA:"TIME_SINCE_MARK" AS TIME_SINCE_MARK
,DATA:"CYCLES_SINCE_MARK" AS CYCLES_SINCE_MARK
,DATA:"NUMBER_OF_REPAIRS" AS NUMBER_OF_REPAIRS
,DATA:"LPN_ID" AS LPN_ID
,DATA:"INSPECTION_STATUS" AS INSPECTION_STATUS
,DATA:"PREVIOUS_STATUS" AS PREVIOUS_STATUS
,DATA:"LPN_TXN_ERROR_FLAG" AS LPN_TXN_ERROR_FLAG
,DATA:"WIP_ACCOUNTING_CLASS_CODE" AS WIP_ACCOUNTING_CLASS_CODE
,DATA:"MAINTAINABLE_FLAG" AS MAINTAINABLE_FLAG
,DATA:"OWNING_DEPARTMENT_ID" AS OWNING_DEPARTMENT_ID
,DATA:"NETWORK_ASSET_FLAG" AS NETWORK_ASSET_FLAG
,DATA:"FA_ASSET_ID" AS FA_ASSET_ID
,DATA:"PN_LOCATION_ID" AS PN_LOCATION_ID
,DATA:"EAM_LOCATION_ID" AS EAM_LOCATION_ID
,DATA:"ASSET_CRITICALITY_CODE" AS ASSET_CRITICALITY_CODE
,DATA:"CATEGORY_ID" AS CATEGORY_ID
,DATA:"PROD_ORGANIZATION_ID" AS PROD_ORGANIZATION_ID
,DATA:"EQUIPMENT_ITEM_ID" AS EQUIPMENT_ITEM_ID
,DATA:"EQP_SERIAL_NUMBER" AS EQP_SERIAL_NUMBER
,DATA:"ORGANIZATION_TYPE" AS ORGANIZATION_TYPE
,DATA:"OWNING_ORGANIZATION_ID" AS OWNING_ORGANIZATION_ID
,DATA:"OWNING_TP_TYPE" AS OWNING_TP_TYPE
,DATA:"PLANNING_ORGANIZATION_ID" AS PLANNING_ORGANIZATION_ID
,DATA:"PLANNING_TP_TYPE" AS PLANNING_TP_TYPE
,DATA:"ONHAND_QUANTITIES_ID" AS ONHAND_QUANTITIES_ID
,DATA:"WIP_ENTITY_ID" AS WIP_ENTITY_ID
,DATA:"OPERATION_SEQ_NUM" AS OPERATION_SEQ_NUM
,DATA:"INTRAOPERATION_STEP_TYPE" AS INTRAOPERATION_STEP_TYPE
,DATA:"EAM_INSTANTIATION_FLAG" AS EAM_INSTANTIATION_FLAG
,DATA:"EAM_LINEAR_LOCATION_ID" AS EAM_LINEAR_LOCATION_ID
,FILENAME                               AS METADATA_FILENAME 
,FILE_ROW_NUMBER                        AS METADATA_FILE_ROW_NUMBER
,FILE_LAST_MODIFIED                     AS METADATA_FILE_LAST_MODIFIED
,START_SCAN_TIME                        AS METADATA_START_SCAN_TIME
from {{ source("landing_ebs", "MTL_SERIAL_NUMBERS") }}
WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM
                    {{ source("landing_ebs", "MTL_SERIAL_NUMBERS") }}
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )