{{
  config(
    materialized = "view",
    alias = "hr_all_organization_units",
    schema='EBS'
  )
}}

SELECT
DATA:"CREATION_DATE" AS CREATION_DATE,
DATA:"LAST_UPDATE_LOGIN" AS LAST_UPDATE_LOGIN,
DATA:"LAST_UPDATED_BY" AS LAST_UPDATED_BY,
DATA:"LAST_UPDATE_DATE" AS LAST_UPDATE_DATE,
DATA:"ATTRIBUTE20" AS ATTRIBUTE20,
DATA:"ATTRIBUTE19" AS ATTRIBUTE19,
DATA:"ATTRIBUTE18" AS ATTRIBUTE18,
DATA:"ATTRIBUTE17" AS ATTRIBUTE17,
DATA:"ATTRIBUTE16" AS ATTRIBUTE16,
DATA:"ATTRIBUTE15" AS ATTRIBUTE15,
DATA:"ATTRIBUTE14" AS ATTRIBUTE14,
DATA:"ATTRIBUTE13" AS ATTRIBUTE13,
DATA:"ATTRIBUTE11" AS ATTRIBUTE11,
DATA:"ATTRIBUTE9" AS ATTRIBUTE9,
DATA:"ATTRIBUTE8" AS ATTRIBUTE8,
DATA:"ATTRIBUTE7" AS ATTRIBUTE7,
DATA:"ATTRIBUTE6" AS ATTRIBUTE6,
DATA:"ATTRIBUTE5" AS ATTRIBUTE5,
DATA:"ATTRIBUTE4" AS ATTRIBUTE4,
DATA:"ATTRIBUTE3" AS ATTRIBUTE3,
DATA:"ATTRIBUTE2" AS ATTRIBUTE2,
DATA:"ATTRIBUTE1" AS ATTRIBUTE1,
DATA:"ATTRIBUTE_CATEGORY" AS ATTRIBUTE_CATEGORY,
DATA:"PROGRAM_UPDATE_DATE" AS PROGRAM_UPDATE_DATE,
DATA:"PROGRAM_ID" AS PROGRAM_ID,
DATA:"PROGRAM_APPLICATION_ID" AS PROGRAM_APPLICATION_ID,
DATA:"REQUEST_ID" AS REQUEST_ID,
DATA:"INTERNAL_ADDRESS_LINE" AS INTERNAL_ADDRESS_LINE,
DATA:"INTERNAL_EXTERNAL_FLAG" AS INTERNAL_EXTERNAL_FLAG,
DATA:"NAME" AS NAME,
DATA:"DATE_FROM" AS DATE_FROM,
DATA:"SOFT_CODING_KEYFLEX_ID" AS SOFT_CODING_KEYFLEX_ID,
DATA:"LOCATION_ID" AS LOCATION_ID,
DATA:"COST_ALLOCATION_KEYFLEX_ID" AS COST_ALLOCATION_KEYFLEX_ID,
DATA:"BUSINESS_GROUP_ID" AS BUSINESS_GROUP_ID,
DATA:"ORGANIZATION_ID" AS ORGANIZATION_ID,
DATA:"CREATED_BY" AS CREATED_BY,
DATA:"ATTRIBUTE12" AS ATTRIBUTE12,
DATA:"ATTRIBUTE10" AS ATTRIBUTE10,
DATA:"TYPE" AS TYPE,
DATA:"COMMENTS" AS COMMENTS,
DATA:"DATE_TO" AS DATE_TO,
DATA:"PARTY_ID" AS PARTY_ID,
DATA:"OBJECT_VERSION_NUMBER" AS OBJECT_VERSION_NUMBER,
FILENAME AS METADATA_FILENAME,
    FILE_ROW_NUMBER AS METADATA_FILE_ROW_NUMBER,
    FILE_LAST_MODIFIED AS METADATA_FILE_LAST_MODIFIED,
    START_SCAN_TIME AS METADATA_START_SCAN_TIME
FROM
    {{ source("landing_ebs", "HR_ALL_ORGANIZATION_UNITS") }}
    -- to only take the files after the last fullLoad

WHERE
    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] >= (
        SELECT
            min_timestamp
        FROM
            (
                SELECT
                    split(FILENAME, '_') [array_size(split(FILENAME, '_')) - 2] AS min_timestamp,
                    split(FILENAME, '/') [3] AS type_file
                FROM
                    {{ source("landing_ebs", "HR_ALL_ORGANIZATION_UNITS") }}
                WHERE
                    type_file LIKE 'fullload%' QUALIFY ROW_NUMBER() OVER (
                        ORDER BY
                            min_timestamp DESC
                    ) = 1
            )
         )

