{{ config(
    materialized='table',
    schema='MARKETPLACE'
) }}

SELECT

    PRODUCT_KEY,
    ENGLISH_PRODUCT_NAME,
    COLOR,
    SIZE,

    COUNT(DISTINCT SALES_ORDER_NUMBER) AS TOTAL_ORDERS,

    SUM(ORDER_QUANTITY) AS TOTAL_QUANTITY,

    SUM(SALES_AMOUNT) AS TOTAL_SALES,

    SUM(TOTAL_PRODUCT_COST) AS TOTAL_PRODUCT_COST,

    SUM(SALES_AMOUNT) - SUM(TOTAL_PRODUCT_COST)
        AS GROSS_PROFIT

FROM {{ ref('dp_internet_sales_silver') }}

GROUP BY
    PRODUCT_KEY,
    ENGLISH_PRODUCT_NAME,
    COLOR,
    SIZE