{{ config(
    materialized='table',
    schema='MARKETPLACE'
) }}

SELECT

    ORDER_DATE,

    YEAR,
    QUARTER,
    MONTH,
    MONTH_NAME,

    COUNT(DISTINCT SALES_ORDER_NUMBER) AS TOTAL_ORDERS,

    SUM(ORDER_QUANTITY) AS TOTAL_QUANTITY,

    SUM(SALES_AMOUNT) AS TOTAL_SALES,

    SUM(TOTAL_PRODUCT_COST) AS TOTAL_PRODUCT_COST,

    SUM(DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT,

    SUM(TAX_AMT) AS TOTAL_TAX,

    SUM(FREIGHT) AS TOTAL_FREIGHT,

    SUM(SALES_AMOUNT) - SUM(TOTAL_PRODUCT_COST)
        AS GROSS_PROFIT

FROM {{ ref('dp_internet_sales_silver') }}

GROUP BY
    ORDER_DATE,
    YEAR,
    QUARTER,
    MONTH,
    MONTH_NAME