{{
  config(
    materialized = "view",
    alias = "rdm",
    schema="BIGQUERY"
  )
}}


with 

raw_data_deduplicated as (

    SELECT *
    from {{ref('prep_bigquery_rdm')}}
    QUALIFY TO_TIMESTAMP_NTZ(exported_datetime_utc) = MAX(TO_TIMESTAMP_NTZ(exported_datetime_utc)) OVER()
)

SELECT
BUSINESSAPPLICATION_DOMAINCODE::STRING as BUSINESSAPPLICATION_DOMAINCODE
, BUSINESSAPPLICATION_VALUE::STRING as BUSINESSAPPLICATION_VALUE
, BUSINESSAPPLICATIONCODE::STRING as BUSINESSAPPLICATIONCODE
, EFFECTIVEON::DATE as EFFECTIVEON
, STANDARDAPPLICATION_DOMAINCODE::STRING as STANDARDAPPLICATION_DOMAINCODE
, STANDARDAPPLICATION_VALUE::STRING as STANDARDAPPLICATION_VALUE
, EXPORTED_DATETIME_UTC::DATETIME as EXPORTED_DATETIME_UTC
from raw_data_deduplicated
