{{
  config(
    materialized = "view",
    alias = "production_transactions_hist",
    schema='roll_former'
  )
}}

SELECT
 NULLIF(UPPER(TRIM(TRANSACTION_ID::STRING)),'') AS TRANSACTION_ID
,NULLIF(UPPER(TRIM(ENTITY_CODE::STRING)),'') AS ENTITY_CODE
,NULLIF(UPPER(TRIM(EQUIPMENT_NAME::STRING)),'') AS EQUIPMENT_NAME
,TO_TIMESTAMP_NTZ(START_TIME::STRING) AS START_TIME
,TO_TIMESTAMP_NTZ(END_TIME::STRING) AS END_TIME
,NULLIF(TRIM(REQUIRED_GLOBAL_ITEM_UUID::STRING),'') AS REQUIRED_GLOBAL_ITEM_UUID
,NULLIF(TRIM(REQUIRED_STEEL_GRADE_UUID::STRING),'') AS REQUIRED_STEEL_GRADE_UUID
,NULLIF(UPPER(TRIM(REQUIRED_SORT_ITEM_CODE::STRING)),'') AS REQUIRED_SORT_ITEM_CODE
,NULLIF(UPPER(TRIM(USED_SORT_ITEM_CODE::STRING)),'') AS USED_SORT_ITEM_CODE
,USED_SLITTED_COIL_NUMBER::double AS USED_SLITTED_COIL_NUMBER
,QUANTITY_DONE::double AS QUANTITY_DONE
,REQUEST_LENGTH::double AS REQUEST_LENGTH
,USED_LENGTH::double AS USED_LENGTH
,NULLIF(UPPER(TRIM(SUBSTITUTION_REASON_CODE::STRING)),'') AS SUBSTITUTION_REASON_CODE
,NULLIF(UPPER(TRIM(REQUIRED_ITEM_CODE::STRING)),'') AS REQUIRED_ITEM_CODE
,NULLIF(TRIM(SUBSTITUTION_REASON_DESCRIPTION_FRENCH::STRING),'') AS SUBSTITUTION_REASON_DESCRIPTION_FRENCH
,NULLIF(TRIM(SUBSTITUTION_REASON_DESCRIPTION_ENGLISH::STRING),'') AS SUBSTITUTION_REASON_DESCRIPTION_ENGLISH
,REQUISITION_NUMBER::INTEGER AS REQUISITION_NUMBER
,NULLIF(UPPER(TRIM(PRODUCT_NO::STRING)),'') AS PRODUCT_NO
,NULLIF(UPPER(TRIM(MARK::STRING)),'') AS MARK
,NULLIF(UPPER(TRIM(COMPONENT_TYPE::STRING)),'') AS COMPONENT_TYPE
,NULLIF(UPPER(TRIM(OPERATOR_NAME::STRING)),'') AS OPERATOR_NAME
,NULLIF(UPPER(TRIM(EVENT_BY::STRING)),'') AS EVENT_BY
,TO_TIMESTAMP_NTZ(EVENT_DATE::STRING) AS EVENT_DATE
,NULLIF(UPPER(TRIM(EVENT_TYPE::STRING)),'') AS EVENT_TYPE
,SRC_SYSTEM_OPERATION::STRING AS SRC_SYSTEM_OPERATION
,TO_TIMESTAMP_NTZ(IPAAS_UPDATED_DATE::STRING) AS IPAAS_UPDATED_DATE
FROM {{ref('prep_production_transactions')}}
WHERE NULLIF(UPPER(TRIM(EVENT_TYPE::STRING)),'') = 'CREATE'
AND USED_SLITTED_COIL_NUMBER = 0
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TRANSACTION_ID ORDER BY 
    IFNULL(TO_TIMESTAMP_NTZ(EVENT_DATE),'0000-01-01T00:00:01.000Z'::DATE) DESC) = 1 
