{{
  config(
    full_refresh = true,
    materialized="dynamic_table",
    target_lag="downstream",
    snowflake_warehouse= var('task_warehouse'),
    alias = "working_shift_calendar",
    schema= "bronze",
    post_hook = "ALTER DYNAMIC TABLE {{ this }} SET LOG_LEVEL = ERROR"
  )
}}

SELECT
	WS.WORKING_SHIFT_UUID																AS WORKING_SHIFT_UUID,
	WSD.WORKING_SHIFT_DETAIL_UUID														AS WORKING_SHIFT_DETAIL_UUID,
	DC.FULL_DATE 																		AS WORKING_SHIFT_DATE,
    ACTIVE_FROM_DATE                                                                    AS WORKING_SHIFT_ACTIVE_FROM_DATE,
    ACTIVE_TO_DATE                                                                      AS WORKING_SHIFT_ACTIVE_TO_DATE,
	TRIM(WS.ENTITY_CODE) 																AS WORKING_SHIFT_ENTITY_CODE,
	ENT.TIMEZONE																		AS WORKING_SHIFT_ENTITY_TIMEZONE,
	TO_TIMESTAMP_NTZ(DATEADD(SECOND, WSD.SHIFT_START_TIME, DC.FULL_DATE))				AS WORKING_SHIFT_START_DATETIME_NTZ,
    TO_TIMESTAMP_NTZ(DATEADD(SECOND, IFF(WSD.SHIFT_END_TIME < WSD.SHIFT_START_TIME, 
    	WSD.SHIFT_END_TIME + 86400, WSD.SHIFT_END_TIME), DC.FULL_DATE))					AS WORKING_SHIFT_END_DATETIME_NTZ,
    CONVERT_TIMEZONE(ENT.TIMEZONE, 'UTC',WORKING_SHIFT_START_DATETIME_NTZ)				AS WORKING_SHIFT_START_DATETIME_UTC,
    CONVERT_TIMEZONE(ENT.TIMEZONE, 'UTC',WORKING_SHIFT_END_DATETIME_NTZ)				AS WORKING_SHIFT_END_DATETIME_UTC,
    WSD.WEEK_DAY																		AS WORKING_SHIFT_DAY_OF_WEEK,	
	UPPER(WS.WORKING_SHIFT_CODE)														AS WORKING_SHIFT_CODE,
	UPPER(DN.NAME)																		AS WORKING_SHIFT_NAME,	
	WSD.WORKING_SHIFT_TYPE																AS WORKING_SHIFT_TYPE,
	CASE WHEN WSD.WORKING_SHIFT_TYPE = 1 THEN WSD.SHOP_NO ELSE NULL END					AS WORKING_SHIFT_SHOP_NO,
	CASE WHEN WSD.WORKING_SHIFT_TYPE = 2 THEN WSD.MACHN_NO ELSE NULL END				AS WORKING_SHIFT_MACHN_NO,
	WS.ACTIVE 																			AS WORKING_SHIFT_IS_ACTIVE
FROM 
    {{ref('norm_working_shift')}} WS
LEFT JOIN 
    {{ref('norm_working_shift_detail')}} WSD 
ON 
    UPPER(TRIM(WS.WORKING_SHIFT_UUID)) = UPPER(TRIM(WSD.WORKING_SHIFT_UUID))
LEFT JOIN 
    {{ref('norm_manual_entity_descriptions')}}  ENT 
ON 
    UPPER(ENT.ENTITY_CODE) = UPPER(WS.ENTITY_CODE)
LEFT JOIN 
    {{ref('norm_data_name')}} DN 
ON 
    UPPER(WS.WORKING_SHIFT_NAME_ID) = UPPER(DN.NAME_ID) AND DN.LANGUAGE_CODE = 1
LEFT JOIN 
    {{ref('sche_dim_Date')}} DC 
ON 
    WSD.WEEK_DAY = DC.CALENDAR_WEEK_DAY_NUMBER AND (DC.FULL_DATE BETWEEN WSD.ACTIVE_FROM_DATE AND COALESCE(WSD.ACTIVE_TO_DATE,DATE(DATEADD(year,1,CURRENT_DATE()))))
WHERE 
    WSD.NONWORKING_TIME <> TRUE AND DC.FULL_DATE IS NOT NULL
QUALIFY 
    ROW_NUMBER() OVER (PARTITION BY DC.FULL_DATE,WSD.WORKING_SHIFT_UUID,WSD.SHOP_NO,WSD.MACHN_NO,WSD.WEEK_DAY ORDER BY WSD.ACTIVE_FROM_DATE DESC) = 1
ORDER BY 
    WORKING_SHIFT_UUID, SHOP_NO, MACHN_NO, WORKING_SHIFT_DAY_OF_WEEK, WORKING_SHIFT_DATE