{{
  config(
    full_refresh = true,
    materialized="dynamic_table",
    target_lag="24 hour",
    snowflake_warehouse= var('task_warehouse'),
    alias = "Calendar",
    schema= "dataproducts_gold",
    post_hook = "ALTER DYNAMIC TABLE {{ this }} SET LOG_LEVEL = ERROR"
  
  )
}}

with Calendar AS (
    SELECT 
      FULL_DATE::DATE AS FULL_DATE,
      CALENDAR_YEAR::INTEGER AS CALENDAR_YEAR,
      CALENDAR_MONTH_NUMBER::INTEGER AS CALENDAR_MONTH_NUMBER,
      CALENDAR_MONTH_DAY_NUMBER::INTEGER AS CALENDAR_MONTH_DAY_NUMBER,
      CALENDAR_QUARTER_NUMBER::INTEGER AS CALENDAR_QUARTER_NUMBER,
      CALENDAR_SEMESTER_NUMBER::INTEGER AS CALENDAR_SEMESTER_NUMBER,
      CALENDAR_WEEK_DAY_NUMBER::INTEGER AS CALENDAR_WEEK_DAY_NUMBER,
      CALENDAR_WEEK_NUMBER::INTEGER AS CALENDAR_WEEK_NUMBER,
      CALENDAR_WEEK_START_DATE::DATE AS CALENDAR_WEEK_START_DATE,
      CALENDAR_MONTH_NAME_FR::STRING AS CALENDAR_MONTH_NAME_FR,
      CALENDAR_MONTH_NAME_EN::STRING AS CALENDAR_MONTH_NAME_EN,
      CALENDAR_DAY_NAME_FR::STRING AS CALENDAR_DAY_NAME_FR,
      CALENDAR_DAY_NAME_EN::STRING AS CALENDAR_DAY_NAME_EN,
      FISCAL_YEAR::INTEGER AS FISCAL_YEAR,
      FISCAL_PERIOD_NUMBER::INTEGER AS FISCAL_PERIOD_NUMBER,
      FISCAL_PERIOD_NAME::STRING AS FISCAL_PERIOD_NAME,
      FISCAL_PERIOD_START_DATE::DATE AS FISCAL_PERIOD_START_DATE,
      FISCAL_PERIOD_END_DATE::DATE AS FISCAL_PERIOD_END_DATE,
      CANAM_WEEK_NUMBER::INTEGER AS CANAM_WEEK_NUMBER,
      CANAM_WEEK_DAY_NUMBER::INTEGER AS CANAM_WEEK_DAY_NUMBER,
      CANAM_WEEK_START_DATE::DATE AS CANAM_WEEK_START_DATE 
    FROM {{ref('sche_dim_Date') }}
)

SELECT * FROM Calendar