{{
  config(
    materialized = "view",
    alias = "item_category",
    schema='spm_gdm'
  )
}}

SELECT
 ITEM_CATEGORY_UUID::string AS ITEM_CATEGORY_UUID
,UPPER(ITEM_CATEGORY_CODE::string) AS ITEM_CATEGORY_CODE
,ITEM_CATEGORY_NAME_ID::integer AS ITEM_CATEGORY_NAME_ID
,TO_BOOLEAN(ORIGIN_REQUIRED::string) AS ORIGIN_REQUIRED
,TO_BOOLEAN(ACTIVE::string) AS ACTIVE
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string),'')  AS MODIFIED_BY
,NULLIF(TRIM(CREATED_BY::string),'')  AS CREATED_BY
FROM {{ref('prep_item_category')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'