{{
  config(
    materialized = "view",
    alias = "steel_grade",
    schema='spm_gdm'
  )
}}

SELECT
 NULLIF(TRIM(STEEL_GRADE_UUID::string), '') AS STEEL_GRADE_UUID
,NULLIF(TRIM(STEEL_GRADE_CODE::string), '') AS STEEL_GRADE_CODE
,NULLIF(TRIM(DESCRIPTION::string), '') AS DESCRIPTION
,KSI::INTEGER AS KSI
,NULLIF(TRIM(CREATEDBY::string), '') AS CREATED_BY
,TO_BOOLEAN(ACTIVE::string) AS ACTIVE
,TO_TIMESTAMP_NTZ(MODIFIEDDATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIEDBY::string), '') AS MODIFIED_BY
,TO_TIMESTAMP_NTZ(CREATEDDATE::string) AS CREATED_DATE
FROM {{ref('prep_steel_grade')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'