{{
  config(
    materialized = "view",
    alias = "customer_type",
    schema='spm_gdm'
  )
}}
  SELECT
 TRIM(CUSTOMER_TYPE_UUID)::string AS CUSTOMER_TYPE_UUID
    ,NULLIF(CUST_TYPE, '')::INTEGER AS CUST_TYPE
    ,NULLIF(CUSTOMER_TYPE_NAME_ID, '')::INTEGER AS CUSTOMER_TYPE_NAME_ID
    ,TO_BOOLEAN(NULLIF(ACTIVE, '')::string) AS ACTIVE
    ,TO_BOOLEAN(NULLIF(NATIONAL_ACCOUNT, '')::string) AS NATIONAL_ACCOUNT
    ,TO_BOOLEAN(NULLIF(AVAILABLE_FOR_PROJECT_EVENTS, '')::string) AS AVAILABLE_FOR_PROJECT_EVENTS
    --,ROW_ID::string AS  ROW_ID
    ,NULLIF(TRIM(SRC_SYSTEM_OPERATION::string),'')::string AS  SRC_SYSTEM_OPERATION
    --,IPAAS_UPDATED_DATE::string AS IPAAS_UPDATED_DATE
    ,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
    ,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
    ,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
    ,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
from {{ref('prep_customer_type')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'