{{
  config(
    materialized = "view",
    alias = "data_name",
    schema='spm_gdm'
  )
}}
  SELECT
  TRIM(DATA_NAME_UUID)::string AS DATA_NAME_UUID
    ,UPPER(TABLE_NAME)::string AS TABLE_NAME
    ,UPPER(FIELD_NAME)::string AS FIELD_NAME
    ,NULLIF(NAME_ID, '')::INTEGER AS NAME_ID
    ,NULLIF(LANGUAGE_CODE, '')::INTEGER AS LANGUAGE_CODE
    ,NULLIF(NAME, '')::string AS NAME
    ,NULLIF(MAX_LENGTH_NAME, '')::INTEGER AS MAX_LENGTH_NAME
    ,TO_BOOLEAN(NULLIF(IS_SETUP, '')::string) AS IS_SETUP
    --,ROW_ID::string AS  ROW_ID
    ,NULLIF(TRIM(SRC_SYSTEM_OPERATION::string),'')::string AS  SRC_SYSTEM_OPERATION
    --,IPAAS_UPDATED_DATE::string AS IPAAS_UPDATED_DATE
    ,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
    ,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
    ,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
    ,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
from {{ref('prep_data_name')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'