{{
  config(
    materialized = "view",
    alias = "global_item",
    schema='spm_gdm'
  )
}}

SELECT
 GLOBAL_ITEM_UUID::string AS GLOBAL_ITEM_UUID
,UPPER(GLOBAL_ITEM_CODE::string) AS GLOBAL_ITEM_CODE
,GLOBAL_ITEM_NAME_ID::string AS GLOBAL_ITEM_NAME_ID
,UPPER(GLOBAL_ITEM_SHORT_CODE::string) AS GLOBAL_ITEM_SHORT_CODE
,MEASURE::INTEGER AS MEASURE
,NULLIF(EQUIVALENT_ITEM_UUID::string, '') AS EQUIVALENT_ITEM_UUID
,UPPER(UOM_CODE::string) AS UOM_CODE
,UPPER(ALTERNATIVE_UOM_CODE::string) AS ALTERNATIVE_UOM_CODE
,ITEM_SUBCATEGORY_UUID::string AS ITEM_SUBCATEGORY_UUID
,WEIGHT::DOUBLE AS WEIGHT
,NULLIF(SHAPE_AISC_UUID::string, '') AS SHAPE_AISC_UUID
,NULLIF(SHAPE_CISC_UUID::string, '') AS SHAPE_CISC_UUID
,UPPER(NULLIF(SDS_CODE::string, '')) AS SDS_CODE
,NULLIF(TECKLA_STRUCTURES_CODE::string, '') AS TECKLA_STRUCTURES_CODE
,NULLIF(ESTIMATING_SOFTWARE_CODE::string, '') AS ESTIMATING_SOFTWARE_CODE
,NULLIF(BIM_CODE::string, '') AS BIM_CODE
,NULLIF(DEFAULT_R_MARQUE::string, '') AS DEFAULT_R_MARQUE
,TO_BOOLEAN(ACTIVE::string) AS ACTIVE
,TO_BOOLEAN(TECHNICAL_INFORMATION_AVAILABLE::string) AS TECHNICAL_INFORMATION_AVAILABLE
,NULLIF(ITEM_GAGE_UUID::string, '') AS ITEM_GAGE_UUID
,NULLIF(TECHNICAL_CATEGORY_UUID::string, '') AS TECHNICAL_CATEGORY_UUID
,NULLIF(CREATEDBY::string, '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(CREATEDDATE::string) AS CREATED_DATE
,TO_TIMESTAMP_NTZ(MODIFIEDDATE::string) AS MODIFIED_DATE
,MODIFIEDBY::string AS MODIFIED_BY
FROM {{ref('prep_global_item')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'