{{
  config(
    materialized = "view",
    alias = "salesman",
    schema='spm_gdm'
  )
}}
SELECT 
NULLIF(TRIM(SALESMAN_UUID::string),'') AS SALESMAN_UUID
,UPPER(NULLIF(TRIM(SLSMN_CODE::string),'')) AS SLSMN_CODE
,INITCAP(NULLIF(TRIM(SLSMN_NAME::string),'')) AS SLSMN_NAME
,NULLIF(PEOPLE_ID::INTEGER,0) AS PEOPLE_ID
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
  from {{ref('prep_salesman')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'