{{
  config(
    materialized = "view",
    alias = "people",
    schema='spm_gdm'
  )
}}
  SELECT
TRIM(PEOPLE_UUID::string) AS PEOPLE_UUID
,PEOPLE_ID::INTEGER AS PEOPLE_ID
,TRIM(CODE::string) AS CODE
,INITCAP(NULLIF(TRIM(NAME::string),'')) AS NAME
,TO_BOOLEAN(ACTIVE::string) AS ACTIVE
,CASE WHEN LENGTH(NULLIF(TRIM(EMAIL::string),'')) < 5 THEN NULL ELSE LOWER(NULLIF(TRIM(EMAIL::string),'')) END AS EMAIL
,CASE WHEN LENGTH(NULLIF(TRIM(EMAIL2::string),'')) < 5 THEN NULL ELSE LOWER(NULLIF(TRIM(EMAIL2::string),'')) END AS EMAIL2
,TO_BOOLEAN(DRAWING_FOLLOW_UP_EMAIL::string) AS DRAWING_FOLLOW_UP_EMAIL
,TO_BOOLEAN(DELIVERY_DATE_MODIFICATION_EMAIL::string) AS DELIVERY_DATE_MODIFICATION_EMAIL
,TO_BOOLEAN(DELIVERY_DATE_REQ_REC_DATE_EMAIL::string) AS DELIVERY_DATE_REQ_REC_DATE_EMAIL
,NULLIF(UPPER(TRIM(OFFICE_CODE::string)),'') AS OFFICE_CODE
,NULLIF(UPPER(TRIM(BRANCH_OFFICE_CODE::string)),'') AS BRANCH_OFFICE_CODE
,NULLIF(REPLACE(TRIM(DEFAULT_ROLE_UUID::string),'?'),'') AS DEFAULT_ROLE_UUID
,NULLIF(TRIM(TRUCK_LOADING_PASSWORD::string),'') AS TRUCK_LOADING_PASSWORD
,NULLIF(TRIM(DEFAULT_LOADING_TEAM::string),'')::INTEGER AS DEFAULT_LOADING_TEAM
,TO_BOOLEAN(EVENTS_FOLLOW_UP_EMAIL::string) AS EVENTS_FOLLOW_UP_EMAIL
,TO_BOOLEAN(VEHICLE_MODIFICATION_EMAIL::string) AS VEHICLE_MODIFICATION_EMAIL
,TO_BOOLEAN(DELIVERY_DATE_MODIF_DAILY_EMAIL::string) AS DELIVERY_DATE_MODIF_DAILY_EMAIL
,TO_BOOLEAN(NEW_PROJECTS_DAILY_EMAIL::string) AS NEW_PROJECTS_DAILY_EMAIL
,FAX_SERVICE_UUID::string AS FAX_SERVICE_UUID
,SUPERVISOR_PEOPLE_ID::INTEGER AS SUPERVISOR_PEOPLE_ID
,TO_BOOLEAN(CREDIT_STATUS_MODIFICATION_EMAIL::string) AS CREDIT_STATUS_MODIFICATION_EMAIL
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
  from {{ref('prep_people')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'