{{
  config(
    materialized = "view",
    alias = "customer_market",
    schema='spm_gdm'
  )
}}
  SELECT
NULLIF(TRIM(CUSTOMER_MARKET_UUID::string),'') AS CUSTOMER_MARKET_UUID
,NULLIF(TRIM(CUSTOMER_UUID::string),'') AS CUSTOMER_UUID
,UPPER(NULLIF(TRIM(AR_ENTITY::string),'')) AS AR_ENTITY
,CREDIT_LIMIT::INTEGER AS CREDIT_LIMIT
,TO_BOOLEAN(CREDIT_CONDITIONAL_APPROVAL::string) AS CREDIT_CONDITIONAL_APPROVAL
,UPPER(NULLIF(TRIM(TERM_CODE::string),'')) AS TERM_CODE
,LOWER(NULLIF(TRIM(NO_COORD::string),'')) AS NO_COORD
,UPPER(NULLIF(TRIM(CMG_INVOICE_STYLE::string),'')) AS CMG_INVOICE_STYLE
,UPPER(NULLIF(TRIM(CURRENCY_COD::string),'')) AS CURRENCY_COD
,UPPER(NULLIF(TRIM(SLSMN_CODE::string),'')) AS SLSMN_CODE
,UPPER(NULLIF(TRIM(TERR_CODE::string),'')) AS TERR_CODE
,TO_TIMESTAMP_NTZ(BILL_TO_TRANSFER_DATETIME::string) AS BILL_TO_TRANSFER_DATETIME
,TO_BOOLEAN(ACTIVE_FOR_PROJECT::string) AS ACTIVE_FOR_PROJECT
,TO_TIMESTAMP_NTZ(CREATION_DATETIME::string) AS CREATION_DATETIME
,LOWER(NULLIF(TRIM(CREATION_BY::string),'')) AS CREATION_BY
,TO_TIMESTAMP_NTZ(LAST_UPDATED_DATETIME::string) AS LAST_UPDATED_DATETIME
,LOWER(NULLIF(TRIM(LAST_UPDATED_BY::string),'')) AS LAST_UPDATED_BY
,TYPE_APPR::INTEGER AS TYPE_APPR
,UPPER(NULLIF(TRIM(NO_AGENT_CT::string),'')) AS NO_AGENT_CT
,TO_BOOLEAN(FINANCIAL_APPL_TRANSFER::string) AS FINANCIAL_APPL_TRANSFER
,UPPER(NULLIF(TRIM(FINANCIAL_APPL_CUSTOMER_NUMBER::string),'')) AS FINANCIAL_APPL_CUSTOMER_NUMBER
,NULLIF(TRIM(ACCOUNTING_TRANSMISSION_MODE::string),'')::INTEGER AS ACCOUNTING_TRANSMISSION_MODE
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
  from {{ref('prep_customer_market')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'