{{
  config(
    materialized = "view",
    alias = "uom",
    schema='spm_gdm',
    meta = {
        'table_key': 'UOM_NAME_ID',
        'tests': {
            'null_values':{
                'columns':[
                    'RDM_UOM_CODE',
                    'RDM_UOM_TYPE_CODE',
                    'RDM_UOM_SYSTEM_CODE'
                ]
            }
        }
    }
  )
}}
with raw_uom as(
SELECT *
from {{ref('prep_uom')}} UOM
QUALIFY ROW_NUMBER() OVER (PARTITION BY UOM_CODE ORDER BY IFNULL(TO_TIMESTAMP_NTZ(IPAAS_UPDATED_DATE),'0000-01-01'::DATE) DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION)) <> 'DELETE'
)
select
UPPER(NULLIF(TRIM(UOM_CODE::string),'')) AS UOM_CODE
,UOM_NAME_ID::INTEGER AS UOM_NAME_ID
,UNIT::INTEGER AS UNIT
,EXP_DECIMAL::INTEGER AS EXP_DECIMAL
,MAX_VALUE::INTEGER AS MAX_VALUE
,MASK::string AS MASK
,TYPE::INTEGER AS TYPE
,UPPER(BASE_UOM::string) AS BASE_UOM
,NULLIF(TRIM(CANSIS_UOM::string),'') AS CANSIS_UOM
,TO_BOOLEAN(MEASURE_SYSTEM::string) AS MEASURE_SYSTEM
,UPPER(NULLIF(TRIM(SRC_SYSTEM_OPERATION::string),'')) AS SRC_SYSTEM_OPERATION
,TO_TIMESTAMP_LTZ(IPAAS_UPDATED_DATE::string) AS IPAAS_UPDATED_DATE 
,IFNULL(RDM.STANDARD_APPLICATION_VALUE, 'Not Found') as RDM_UOM_CODE
,CASE WHEN NULLIF(TRIM(UOM.TYPE::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM1.STANDARD_APPLICATION_VALUE,'Not Found') END as RDM_UOM_TYPE_CODE
,CASE WHEN NULLIF(TRIM(UOM.MEASURE_SYSTEM::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM2.STANDARD_APPLICATION_VALUE,'Not Found') END as RDM_UOM_SYSTEM_CODE
,IFNULL(RDM.STANDARD_APPLICATION_VALUE_NAME_FR, 'Not Found') AS RDM_UOM_NAME_FR
,IFNULL(RDM.STANDARD_APPLICATION_VALUE_NAME_EN, 'Not Found') AS RDM_UOM_NAME_EN
,CASE WHEN NULLIF(TRIM(UOM.TYPE::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM1.STANDARD_APPLICATION_VALUE_NAME_FR,'Not Found') 
END                                                          AS RDM_UOM_TYPE_NAME_FR
,CASE WHEN NULLIF(TRIM(UOM.TYPE::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM1.STANDARD_APPLICATION_VALUE_NAME_EN,'Not Found') 
END                                                          AS RDM_UOM_TYPE_NAME_EN
,CASE WHEN NULLIF(TRIM(UOM.MEASURE_SYSTEM::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM2.STANDARD_APPLICATION_VALUE_NAME_FR,'Not Found') 
END                                                          AS RDM_UOM_SYSTEM_NAME_FR
,CASE WHEN NULLIF(TRIM(UOM.MEASURE_SYSTEM::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM2.STANDARD_APPLICATION_VALUE_NAME_EN,'Not Found') 
END                                                          AS RDM_UOM_SYSTEM_NAME_EN
from raw_uom UOM
LEFT join {{ref('gov_referencedata_rdm')}} RDM 
  ON UPPER(UOM.UOM_CODE) = UPPER(RDM.BUSINESS_APPLICATION_VALUE)
    AND UPPER(RDM.BUSINESS_APPLICATION_DOMAIN_CODE) = 'UNITOFMEASURE'
    AND UPPER(RDM.STANDARD_DOMAIN_APPLICATION_CODE) = 'UNITOFMEASURE'
    AND UPPER(RDM.BUSINESS_APPLICATION_CODE) = 'SPM'
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM1
  ON UPPER(UOM.TYPE) = UPPER(RDM1.BUSINESS_APPLICATION_VALUE) 
    AND UPPER(RDM1.BUSINESS_APPLICATION_DOMAIN_CODE) = 'UNITOFMEASURE'
    AND UPPER(RDM1.STANDARD_DOMAIN_APPLICATION_CODE) = 'UNITOFMEASURETYPE'
    AND UPPER(RDM1.BUSINESS_APPLICATION_CODE) = 'SPM'
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM2
  ON UPPER(UOM.MEASURE_SYSTEM) = UPPER(RDM2.BUSINESS_APPLICATION_VALUE) 
    AND UPPER(RDM2.BUSINESS_APPLICATION_DOMAIN_CODE) = 'UNITOFMEASURESYSTEM'
    AND UPPER(RDM2.STANDARD_DOMAIN_APPLICATION_CODE) = 'UNITOFMEASURESYSTEM'
    AND UPPER(RDM2.BUSINESS_APPLICATION_CODE) = 'SPM'
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'
