{{
  config(
    materialized = "view",
    alias = "technical_category",
    schema='spm_gdm'
  )
}}

SELECT
 TECHNICAL_CATEGORY_UUID::string AS TECHNICAL_CATEGORY_UUID
,UPPER(TECHNICAL_CATEGORY_CODE::string) AS TECHNICAL_CATEGORY_CODE
,TECHNICAL_CATEGORY_NAME_ID::INTEGER AS TECHNICAL_CATEGORY_NAME_ID
,UPPER(ITEM_PREFIX::string) AS ITEM_PREFIX
,TO_BOOLEAN(PERFORATION_COST_INPUT_ALLOWED::string) AS PERFORATION_COST_INPUT_ALLOWED
,TO_BOOLEAN(ALLOW_DUPLICATE_ABM_ITEM_NO::string) AS ALLOW_DUPLICATE_ABM_ITEM_NO
,TO_BOOLEAN(ACTIVE::string) AS ACTIVE
FROM {{ref('prep_technical_category')}}
