{{
  config(
    materialized = "view",
    alias = "cmg_task",
    schema='spm_gdm'
  )
}}
  SELECT
UPPER(TRIM(TASK_NUMBER::string)) AS TASK_NUMBER
,NULLIF(TASK_NAME_1::string,'') AS TASK_NAME_1
,NULLIF(TASK_NAME_2::string,'') AS TASK_NAME_2
,TO_BOOLEAN(ACTIVE::string) AS ACTIVE
,NULLIF(TASK_FAMILY_1::string,'') AS TASK_FAMILY_1
,NULLIF(TASK_FAMILY_2::string,'') AS TASK_FAMILY_2
,SALES_GROUP_CODE::INTEGER AS SALES_GROUP_CODE
,CASE WHEN CT.ACTIVE IS NULL 
  THEN NULL 
  ELSE IFNULL(RDM_AS.STANDARD_APPLICATION_VALUE,'Not Found') 
  END                                                           AS RDM_ACTIVE_STATUS_CODE
 ,CASE WHEN CT.ACTIVE IS NULL THEN NULL ELSE IFNULL(RDM_AS.STANDARD_APPLICATION_VALUE_NAME_FR,'Not Found') END    AS RDM_ACTIVE_STATUS_NAME_FR
 ,CASE WHEN CT.ACTIVE IS NULL THEN NULL ELSE IFNULL(RDM_AS.STANDARD_APPLICATION_VALUE_NAME_EN ,'Not Found') END   AS RDM_ACTIVE_STATUS_NAME_EN
  FROM {{ref('prep_cmg_task')}} CT
   LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM_AS
    ON CAST(CT.ACTIVE AS INT) = CAST(RDM_AS.BUSINESS_APPLICATION_VALUE AS INT)
    AND UPPER(RDM_AS.BUSINESS_APPLICATION_DOMAIN_CODE) = 'ACTIVESTATUS'
    AND UPPER(RDM_AS.STANDARD_DOMAIN_APPLICATION_CODE) = 'ACTIVESTATUS' 
    AND UPPER(RDM_AS.BUSINESS_APPLICATION_CODE) = 'SPM'
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'