{{
  config(
    materialized = "view",
    alias = "qc_office",
    schema='spm_gdm',
    meta = {
        'table_key': 'OFFICE_CODE',
        'tests': {
            'null_values':{
                'columns':[
                    'RDM_SALES_OFFICE_DEPARTMENT_CODE',
                    'RDM_ACTIVE_STATUS_CODE'
                ]
            }
        }
    }
  )
}}

WITH raw_qc_office as
(
  select * from {{ref('prep_qc_office')}}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'
)

SELECT
NULLIF(UPPER(TRIM(OFFICE_CODE::string)),'') AS  OFFICE_CODE
, NEXT_JOB_NO::integer AS  NEXT_JOB_NO
, TRIM(PREFIX::string) AS  PREFIX
, TO_BOOLEAN(BILL_SHIP::string) AS  BILL_SHIP
, NULLIF(TRIM(ADDRSS1::string), '') AS  ADDRSS1
, NULLIF(TRIM(ADDRSS2::string), '') AS  ADDRSS2
, INITCAP(NULLIF(TRIM(CITY::string), '')) AS  CITY
, NULLIF(TRIM(ST::string), '') AS  ST
, NULLIF(TRIM(COUNTRY::string), '') AS  COUNTRY
, NULLIF(TRIM(ZIP_CODE::string), '') AS  ZIP_CODE
, NULLIF(REGEXP_REPLACE(PHONE,'[^\\d]*'), '')::string AS  PHONE
, FAX::string AS  FAX  -- column entirely NULL
, OPENING_FEE::integer AS  OPENING_FEE
, ROUNDING_FACTOR::integer AS  ROUNDING_FACTOR
, TO_BOOLEAN(MESURE::string) AS  MESURE
, LOGO_FILE_3::string AS  LOGO_FILE_3
, LOGO_FILE_1::string AS  LOGO_FILE_1
, LOGO_FILE_2::string AS  LOGO_FILE_2
, NULLIF(TRIM(NAME::string), '') AS  NAME
, NULLIF(TRIM(CURRENCY_COD::string), '') AS  CURRENCY_COD
, CALC_SOFT::integer AS  CALC_SOFT
, SEQ_YEAR::integer AS  SEQ_YEAR
, TO_BOOLEAN(ACTIVE::string) AS  ACTIVE
, NULLIF(TRIM(DEFAULT_CONTRC_NOTE_3::string), '') AS  DEFAULT_CONTRC_NOTE_3
, NULLIF(TRIM(DEFAULT_CONTRC_NOTE_1::string), '') AS  DEFAULT_CONTRC_NOTE_1
, NULLIF(TRIM(DEFAULT_CONTRC_NOTE_2::string), '') AS  DEFAULT_CONTRC_NOTE_2
, TRIM(DATE_FORMAT::string) AS  DATE_FORMAT
, TOLERANCE_FACTOR::double AS  TOLERANCE_FACTOR
, TO_BOOLEAN(SIGNATURE::string) AS  SIGNATURE
, NULLIF(TRIM(PHONE_FORMAT::string), '') AS  PHONE_FORMAT
, PRICE_EXPIRATION_DELAY::integer AS  PRICE_EXPIRATION_DELAY
, TO_BOOLEAN(DETAIL_EDIT_ALLOWED::string) AS  DETAIL_EDIT_ALLOWED
, TO_BOOLEAN(USE_OFFICE_LOGO::string) AS  USE_OFFICE_LOGO
, TO_BOOLEAN(ENG_SOLUTION_COMPLETED_MANDATORY::string) AS  ENG_SOLUTION_COMPLETED_MANDATORY
, NULLIF(TRIM(AR_ENTITY::string), '')  AS AR_ENTITY
, TO_BOOLEAN(SHOW_ADDRESSES_ON_FPS::string) AS  SHOW_ADDRESSES_ON_FPS
, NULLIF(REGEXP_REPLACE(TOLL_FREE,'[^\\d]*'), '')::string AS  TOLL_FREE
, NULLIF(TRIM(OFFICE_ADDRESS_FORMAT_ON_DOC), '')::string AS  OFFICE_ADDRESS_FORMAT_ON_DOC
, TO_BOOLEAN(SHOW_CURRENCY_ON_FPS::string) AS  SHOW_CURRENCY_ON_FPS
, DOCUMENTS_DUE_IN_DELAY::integer AS  DOCUMENTS_DUE_IN_DELAY
, SALESMANAGERPEOPLEID::integer AS  SALESMANAGERPEOPLEID
, ESTIMATIONTARGETDATEDELAY::integer AS  ESTIMATIONTARGETDATEDELAY
--, ROW_ID::string AS  ROW_ID  -- we shouldn't use it except for debug
, NULLIF(TRIM(SRC_SYSTEM_OPERATION::string),'') AS  SRC_SYSTEM_OPERATION
--, IPAAS_UPDATED_DATE::string AS  IPAAS_UPDATED_DATE  -- we shouldn't use it except for debug

--RDM data for Sales Office Department
,IFNULL(RDM_SALES.STANDARD_APPLICATION_VALUE, 'Not Found') AS RDM_SALES_OFFICE_DEPARTMENT_CODE

--RDM data for Active Status
,IFNULL(RDM_ACT.STANDARD_APPLICATION_VALUE, 'Not Found') AS RDM_ACTIVE_STATUS_CODE

--RDM data for Country Code
,CASE WHEN NULLIF(TRIM(QO.COUNTRY::STRING),'') IS NULL 
THEN NULL 
ELSE IFNULL(RDM_C.STANDARD_APPLICATION_VALUE,'Not Found') 
END                                                                 AS RDM_COUNTRY_CODE

, TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS  CREATED_DATE
, TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS  MODIFIED_DATE
, NULLIF(TRIM(CREATED_BY::string),'') AS  CREATED_BY
, NULLIF(TRIM(MODIFIED_BY::string),'') AS  MODIFIED_BY
, CASE WHEN NULLIF(TRIM(QO.COUNTRY::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM_C.STANDARD_APPLICATION_VALUE_NAME_FR ,'Not Found') 
END                                   AS RDM_COUNTRY_NAME_FR
, CASE WHEN NULLIF(TRIM(QO.COUNTRY::STRING),'') 
IS NULL THEN NULL ELSE IFNULL(RDM_C.STANDARD_APPLICATION_VALUE_NAME_EN ,'Not Found') 
END                                   AS RDM_COUNTRY_NAME_EN
, IFNULL(RDM_SALES.STANDARD_APPLICATION_VALUE_NAME_FR, 'Not Found')  AS RDM_SALES_OFFICE_DEPARTMENT_NAME_FR
, IFNULL(RDM_SALES.STANDARD_APPLICATION_VALUE_NAME_EN, 'Not Found')  AS RDM_SALES_OFFICE_DEPARTMENT_NAME_EN
  from raw_qc_office QO

--join for RDM_SALES_OFFICE_DEPARTMENT_CODE
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM_SALES
    ON UPPER(TRIM(QO.OFFICE_CODE)) = UPPER(TRIM(RDM_SALES.BUSINESS_APPLICATION_VALUE))
    AND UPPER(RDM_SALES.BUSINESS_APPLICATION_DOMAIN_CODE) = 'SALESOFFICEDEPARTMENT'
    AND UPPER(RDM_SALES.STANDARD_DOMAIN_APPLICATION_CODE) = 'SALESOFFICEDEPARTMENT' 
    AND UPPER(RDM_SALES.BUSINESS_APPLICATION_CODE) = 'SPM'

--join for RDM_ACTIVE_STATUS_CODE
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM_ACT
  ON CAST(QO.ACTIVE AS INT) = CAST(RDM_ACT.BUSINESS_APPLICATION_VALUE AS INT)
    AND UPPER(RDM_ACT.BUSINESS_APPLICATION_DOMAIN_CODE) = 'ACTIVESTATUS'
    AND UPPER(RDM_ACT.STANDARD_DOMAIN_APPLICATION_CODE) = 'ACTIVESTATUS' 
    AND UPPER(RDM_ACT.BUSINESS_APPLICATION_CODE) = 'SPM'

--join form RDM Country Code
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM_C 
    ON UPPER(NULLIF(TRIM(QO.COUNTRY::STRING),'')) = UPPER(RDM_C.BUSINESS_APPLICATION_VALUE)
    AND UPPER(RDM_C.BUSINESS_APPLICATION_DOMAIN_CODE) = 'COUNTRY'
    AND UPPER(RDM_C.STANDARD_DOMAIN_APPLICATION_CODE) = 'COUNTRY' 
    AND UPPER(RDM_C.BUSINESS_APPLICATION_CODE) = 'SPM'    
