{{
  config(
    materialized = "view",
    alias = "country",
    schema='spm_gdm'
  )
}}

SELECT
 UPPER(COUNTRY_UUID::string) AS COUNTRY_UUID
,UPPER(COUNTRY_CODE::string) AS COUNTRY_CODE
,INITCAP(LOWER(NAME::string)) AS NAME
,TO_BOOLEAN(NAFTA::string) AS NAFTA
,NULLIF(CREATED_BY::string, '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(MODIFIED_BY::string, '') AS MODIFIED_BY
FROM {{ref('prep_country')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'