{{
  config(
    materialized = "view",
    alias = "item_subcategory",
    schema='spm_gdm'
  )
}}

SELECT
 ITEM_SUBCATEGORY_UUID::string AS ITEM_SUBCATEGORY_UUID
,ITEM_CATEGORY_UUID::string AS ITEM_CATEGORY_UUID
,UPPER(ITEM_SUBCATEGORY_CODE::string) AS ITEM_SUBCATEGORY_CODE
,ITEM_SUBCATEGORY_NAME_ID::integer AS ITEM_SUBCATEGORY_NAME_ID
,NULLIF(TRIM(ITEM_PREFIX::string),'') AS ITEM_PREFIX
,TO_BOOLEAN(STANDARD_CONNECTION::string) AS STANDARD_CONNECTION
,TO_BOOLEAN(CISC_AISC_CODE_MANDATORY::string) AS CISC_AISC_CODE_MANDATORY
,TO_BOOLEAN(ACTIVE::string) AS ACTIVE
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string),'')  AS MODIFIED_BY
,NULLIF(TRIM(CREATED_BY::string),'')  AS CREATED_BY
FROM {{ref('prep_item_subcategory')}}
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'