{{
  config(
    materialized = "view",
    alias = "business_unit",
    schema='spm_gdm',
    meta = {
        'table_key': 'BUSINESS_UNIT_ID',
        'tests': {
            'null_values':{
                'columns':[
                    'RDM_ACTIVE_STATUS_CODE'
                ]
            }
        }
    }
  )
}}

SELECT
BUSINESS_UNIT_ID::INTEGER AS BUSINESS_UNIT_ID
,UPPER(TRIM(BUSINESS_UNIT_CODE::string)) AS BUSINESS_UNIT_CODE
,BUSINESS_UNIT_NAME_ID::INTEGER AS BUSINESS_UNIT_NAME_ID
,TO_BOOLEAN(IS_ACTIVE::string) AS IS_ACTIVE
,COMPANY_REFERENCE_NAME_ID::INTEGER AS COMPANY_REFERENCE_NAME_ID
,LOGO_FILE_NAME_ID::INTEGER AS LOGO_FILE_NAME_ID
,BUSINESS_UNIT_SHORT_NAME_ID::INTEGER AS BUSINESS_UNIT_SHORT_NAME_ID
,REQ_SENT_OUT_TARGET_DELAY::INTEGER AS REQ_SENT_OUT_TARGET_DELAY
,TO_BOOLEAN(ALLOW_DSMS_TRANSFER::string) AS ALLOW_DSMS_TRANSFER
,BUSINESS_UNIT_TAG_NAME_ID::INTEGER AS BUSINESS_UNIT_TAG_NAME_ID
,BOL_DESCRIPTION_NAME_ID::INTEGER AS BOL_DESCRIPTION_NAME_ID
,INITCAP(TRIM(REVENUE_QUANTITY_TYPE_UUID::string)) AS REVENUE_QUANTITY_TYPE_UUID
,TO_BOOLEAN(PROJECT_EVENT_MANAGE_BY_PROJCOOR::string) AS PROJECT_EVENT_MANAGE_BY_PROJCOOR
,TO_BOOLEAN(PERFORMANCE_IND_CALCULATION::string) AS PERFORMANCE_IND_CALCULATION
,PCX_LOGO_FILE_NAME_ID::INTEGER AS PCX_LOGO_FILE_NAME_ID
,TO_BOOLEAN(ALLOW_LINK_TO_CMS::string) AS ALLOW_LINK_TO_CMS
,TO_BOOLEAN(CMS_GLOBAL_APPROVAL::string) AS CMS_GLOBAL_APPROVAL
,RDM.STANDARD_APPLICATION_VALUE AS RDM_ACTIVE_STATUS_CODE
,IFNULL(RDM_LOB.STANDARD_APPLICATION_VALUE,'Not Found') AS RDM_LINE_OF_BUSINESS_CODE
,IFNULL(RDM_LOB.STANDARD_APPLICATION_VALUE_NAME_FR,'Not Found') AS RDM_LINE_OF_BUSINESS_NAME_FR
,IFNULL(RDM_LOB.STANDARD_APPLICATION_VALUE_NAME_EN ,'Not Found') AS RDM_LINE_OF_BUSINESS_NAME_EN
FROM {{ref('prep_business_unit')}} BU
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM
  ON CAST(BU.IS_ACTIVE AS INT) = CAST(RDM.BUSINESS_APPLICATION_VALUE AS INT)
    AND UPPER(RDM.BUSINESS_APPLICATION_DOMAIN_CODE) = 'ACTIVESTATUS'
    AND UPPER(RDM.STANDARD_DOMAIN_APPLICATION_CODE) = 'ACTIVESTATUS' 
    AND UPPER(RDM.BUSINESS_APPLICATION_CODE) = 'SPM'
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM_LOB
  ON UPPER(TRIM(BU.BUSINESS_UNIT_CODE)) = UPPER(RDM_LOB.BUSINESS_APPLICATION_VALUE)
    AND UPPER(RDM_LOB.BUSINESS_APPLICATION_DOMAIN_CODE) = 'LINESOFBUSINESS'
    AND UPPER(RDM_LOB.STANDARD_DOMAIN_APPLICATION_CODE) = 'LINESOFBUSINESS' 
    AND UPPER(RDM_LOB.BUSINESS_APPLICATION_CODE) = 'SPM'    
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1