{{
  config(
    materialized = "view",
    alias = "project",
    schema='spm_gdm',
    meta = {
        'table_key': 'PROJECT_ID',
        'tests': {
            'null_values':{
                'columns':[
                    'PROJECT_CURRENCY_CODE'
                ]
            }
        }
    }
  )
}}
SELECT
PROJECT_ID::INTEGER AS PROJECT_ID
,PROJECT_NAME::string AS PROJECT_NAME
,PROJECT_SHORT_NAME::string AS PROJECT_SHORT_NAME
,UPPER(PROJECT_CODE::string) AS PROJECT_CODE
,UPPER(QUOTATION_CODE::string) AS QUOTATION_CODE
,QUOTATION_DATE::DATE AS QUOTATION_DATE
,UPPER(NULLIF(TRIM(CONTRACT_CODE::string), '')) AS CONTRACT_CODE
,CONTRACT_DATE::DATE AS CONTRACT_DATE
,UPPER(NULLIF(TRIM(CUSTOMER_PROJECT_CODE::string),'')) AS CUSTOMER_PROJECT_CODE
,PROJECT_STATUS_CODE::INTEGER AS PROJECT_STATUS_CODE
--,CREATED_BY::string AS CREATED_BY            -- column entirely NULL
,LOWER(NULLIF(TRIM(LAST_UPDATED_BY::string), '')) AS LAST_UPDATED_BY
,UPPER(NULLIF(TRIM(CUSTOMER_PO::string), '')) AS CUSTOMER_PO
,CURRENCY_CODE::string AS CURRENCY_CODE_SOURCE
,IFNULL(Standard_Application_Value,'Not Found') AS PROJECT_CURRENCY_CODE
,REPORT_TEMPLATE_ID::INTEGER AS REPORT_TEMPLATE_ID
,BUSINESS_UNIT_ID::INTEGER AS BUSINESS_UNIT_ID
,ESTIMATED_SHIPPING_DATE::DATE AS ESTIMATED_SHIPPING_DATE
,UPPER(NULLIF(TRIM(EXTRA_PREFIX::string), '')) AS EXTRA_PREFIX
,MASTER_PROJECT_ID::INTEGER AS MASTER_PROJECT_ID
,LINK_DB_ALIAS::string AS LINK_DB_ALIAS
,UPPER(NULLIF(TRIM(PROJECT_SOURCE_CODE::string), '')) AS PROJECT_SOURCE_CODE
,ERECTION_ADVANCEMENT_PERCENTAGE::INTEGER AS ERECTION_ADVANCEMENT_PERCENTAGE
,UPPER(NULLIF(TRIM(BILL_TO_CUSTOMER_UUID::string), '')) AS BILL_TO_CUSTOMER_UUID
,ERECTOR_PRIVILEGE_PARENT_PROJ_ID::INTEGER AS ERECTOR_PRIVILEGE_PARENT_PROJ_ID
--,UPPER(NULLIF(TRIM(JOB_SITE_IMAGE_PATH::string), ''))::string AS JOB_SITE_IMAGE_PATH          -- column entirely NULL
--,ERECTION_TARGET_END_DATE::DATE AS ERECTION_TARGET_END_DATE          -- column entirely NULL
--,ERECTION_REVISED_END_DATE::DATE AS ERECTION_REVISED_END_DATE          -- column entirely NULL
,TO_BOOLEAN(NULLIF(ERECTOR_PRIVILEGE_INCLUDED, '')::string) AS ERECTOR_PRIVILEGE_INCLUDED
,UPPER(NULLIF(TRIM(MARKET_UUID::string), '')) AS MARKET_UUID
,UPPER(NO_PROJET)::string AS NO_PROJET
,NULLIF(UPPER(JOB_NO)::string,'') AS JOB_NO
,UPPER(NULLIF(TRIM(QUOTATION_ENTITY_CODE::string), '')) AS QUOTATION_ENTITY_CODE
,PRICE_EXPIRATION_DATE::DATE AS PRICE_EXPIRATION_DATE
--,QUOTATION_SENT_DATE::DATE AS QUOTATION_SENT_DATE            -- column entirely NULL
,D_CONTRAT::DATE AS D_CONTRAT
,NULLIF(INITCAP(NOM_CONTACT::string),'') AS NOM_CONTACT
,NULLIF(REGEXP_REPLACE(SITE_PHONE,'[^\\d]*'), '')::string AS SITE_PHONE
--,SITE_FAX::string AS SITE_FAX -- column entirely NULL
--,CONTACT_EMAIL::string AS CONTACT_EMAIL -- column entirely NULL
,INITCAP(NULLIF(TRIM(FINANCIAL_COMMENTS::string), '')) AS FINANCIAL_COMMENTS
,EXCHGN_RATE::DOUBLE AS EXCHGN_RATE
,CMG_INVOICE_STYLE::string AS CMG_INVOICE_STYLE
,TERM_CODE::string AS TERM_CODE
,NO_AGENT_CT::string AS NO_AGENT_CT
,TYPE_APPR::INTEGER AS TYPE_APPR
,D_APP_CREDIT::DATE AS D_APP_CREDIT
,lower(NULLIF(TRIM(CREDIT_APPROVED_BY::string), '')) AS CREDIT_APPROVED_BY
,NO_APPR_CRE::INTEGER AS NO_APPR_CRE
,CMG_CHECK_AMT::DOUBLE AS CMG_CHECK_AMT
,UPPER(NULLIF(TRIM(CMG_CREDIT_COMM::string), '')) AS CMG_CREDIT_COMM
,TO_BOOLEAN(NULLIF(MAN_AUTO_CRED, '')::string) AS MAN_AUTO_CRED
,TO_BOOLEAN(NULLIF(DENONCIATION, '')::string) AS DENONCIATION
,UPPER(NULLIF(TRIM(SET_OFF_INFORMATION::string), '')) AS SET_OFF_INFORMATION
,UPPER(NULLIF(TRIM(ENTITY_CODE::string), '')) AS ENTITY_CODE
,UPPER(NULLIF(TRIM(FORM_ENTITY::string), '')) AS FORM_ENTITY
,TO_BOOLEAN(NULLIF(IS_LAYOUT_JOB, '')::string) AS IS_LAYOUT_JOB
,TO_BOOLEAN(NULLIF(DOUANE_PROJ, '')::string) AS DOUANE_PROJ
,TO_BOOLEAN(NULLIF(TYPE_PROJET, '')::string) AS TYPE_PROJET
,TAXATION_ADDRESS::string AS TAXATION_ADDRESS
,UPPER(NULLIF(TRIM(TERR_CODE::string), '')) AS TERR_CODE
,UPPER(NULLIF(TRIM(PST_LICENSE::string), ''))  AS PST_LICENSE
,UPPER(NULLIF(TRIM(FST_LICENSE::string), '')) AS FST_LICENSE
,SLSMN_CODE::string AS SLSMN_CODE
,NULLIF(UPPER(TRIM(OFFICE_CODE::string)), '') AS OFFICE_CODE
,NULLIF(UPPER(TRIM(BRANCH_OFFICE_CODE::string)), '') AS BRANCH_OFFICE_CODE
,MAX_DECK_BUNDL_WEIGHT::INTEGER AS MAX_DECK_BUNDL_WEIGHT
,MAX_DECK_BUNDL_PIECES::INTEGER AS MAX_DECK_BUNDL_PIECES
,DECK_BUNDL_PIECES_TOLERANCE::INTEGER AS DECK_BUNDL_PIECES_TOLERANCE
,TO_BOOLEAN(NULLIF(STATUT_PROJ, '')::string) AS STATUT_PROJ
,NULLIF(TRIM(PROJECT_STATUS_COMMENT::string),'') AS PROJECT_STATUS_COMMENT
,Lower(NULLIF(TRIM(PROJECT_STATUS_UPDATED_BY::string), '')) AS PROJECT_STATUS_UPDATED_BY
,TO_TIMESTAMP_NTZ(PROJECT_STATUS_UPDATED_DATETIME::string) AS PROJECT_STATUS_UPDATED_DATETIME
,ESTIMATED_SHIPMENT_NUMBER::double AS ESTIMATED_SHIPMENT_NUMBER
,ESTIMATED_ESCORT_NUMBER::INTEGER AS ESTIMATED_ESCORT_NUMBER
,TO_BOOLEAN(NULLIF(SEQUENCING, '')::string) AS SEQUENCING
,TO_BOOLEAN(NULLIF(FOLLOW_DIV, '')::string) AS FOLLOW_DIV
,TO_BOOLEAN(NULLIF(FOLLOW_MARK, '')::string) AS FOLLOW_MARK
,MARK_TYPE::INTEGER AS MARK_TYPE
,ESTIMATED_SHIPPING_WEEK::INTEGER AS ESTIMATED_SHIPPING_WEEK
,ESTIMATED_FABRICATION_DATE::DATE AS ESTIMATED_FABRICATION_DATE
,ESTIMATED_ENGINEERING_DATE::DATE AS ESTIMATED_ENGINEERING_DATE
,ESTIMATED_FABRICATION_WEEK::INTEGER AS ESTIMATED_FABRICATION_WEEK
,ESTIMATED_ENGINEERING_WEEK::INTEGER AS ESTIMATED_ENGINEERING_WEEK
,TO_BOOLEAN(NULLIF(PO_NO_TRANS_ORACLE, '')::string) AS PO_NO_TRANS_ORACLE
,TO_BOOLEAN(NULLIF(LST_BCKLOG, '')::string) AS LST_BCKLOG
,NULLIF(TRIM(WEIGHT_INCREASE_COMMENT::string),'') AS WEIGHT_INCREASE_COMMENT
,TO_BOOLEAN(NULLIF(cmg_transfer, '')::string) AS CMG_TRANSFER
,TO_BOOLEAN(NULLIF(DSG_TRANSFER, '')::string) AS DSG_TRANSFER
,TO_BOOLEAN(NULLIF(DSMS_TRANSFER, '')::string) AS DSMS_TRANSFER
,PRIORITY_CODE::INTEGER AS PRIORITY_CODE
,TO_BOOLEAN(NULLIF(SPECIAL_ELEMENTS, '')::string) AS SPECIAL_ELEMENTS
,NULLIF(TRIM(SPECIAL_ELEMENTS_COMMENTS::string),'') AS SPECIAL_ELEMENTS_COMMENTS
--,DRAWING_DUE_IN::DATE AS DRAWING_DUE_IN  --all null
,NULLIF(TRIM(LAYOUT_PROCESS_CODE::string),'') AS LAYOUT_PROCESS_CODE
,UPPER(NULLIF(TRIM(CMG_SOURCE_TEMPLATE::string),'')) AS CMG_SOURCE_TEMPLATE
,TO_BOOLEAN(NULLIF(MESURE, '')::string) AS MESURE
,NULLIF(NO_PEINTURE::string,'') AS NO_PEINTURE
,NULLIF(FINISHING_CODE::string,'') AS FINISHING_CODE
,TO_TIMESTAMP_NTZ(CREATION_DATETIME::string) AS CREATION_DATETIME
,TO_TIMESTAMP_NTZ(LAST_UPDATED_DATETIME::string) AS LAST_UPDATED_DATETIME
,GLOBAL_PROJECT_UUID::string AS GLOBAL_PROJECT_UUID
,TO_BOOLEAN(NULLIF(PREPARATION_FOLLOW_UP, '')::string) AS PREPARATION_FOLLOW_UP
,UPPER(NULLIF(TRIM(PREP_FOLLOW_UP_MARKS_FILTER::string),'')) AS PREP_FOLLOW_UP_MARKS_FILTER
,ESTIMATED_LAST_SHIPPING_DATE::DATE AS ESTIMATED_LAST_SHIPPING_DATE
,ESTIMATED_LAST_SHIPPING_WEEK::INTEGER AS ESTIMATED_LAST_SHIPPING_WEEK
,TO_BOOLEAN(NULLIF(OFFICIAL_BUDGET, '')::string) AS OFFICIAL_BUDGET
,TO_BOOLEAN(NULLIF(enterpriseTASKMANAGEMENTEXPORT, '')::string) AS enterpriseTASKMANAGEMENTEXPORT
,TO_BOOLEAN(NULLIF(PACKAGE, '')::string) AS PACKAGE
,JOBSITERESPONSIBLEID::INTEGER AS JOBSITERESPONSIBLEID
,INITCAP(NULLIF(TRIM(JOBSITERESPONSIBLETEXT::string),'')) AS JOBSITERESPONSIBLETEXT
,TO_BOOLEAN(NULLIF(SAPTRANSFER, '')::string) AS SAPTRANSFER
FROM 
  {{ref('prep_project')}} 
LEFT JOIN
  {{ref('gov_referencedata_rdm')}}
  ON UPPER(currency_code::string) = UPPER(Business_Application_Value)
  AND Business_Application_Code = 'spm'
  AND Business_Application_Domain_Code = 'Currency'
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'