{{
  config(
    materialized = "view",
    alias = "qc_branch_office",
    schema='spm_gdm',
    meta = {
        'table_key': 'QC_BRANCH_OFFICE_UUID',
        'tests': {
            'null_values':{
                'columns':[
                    'RDM_SALES_OFFICE_DEPARTMENT_CODE',
                    'RDM_SALES_BRANCH_OFFICE_DEPARTMENT_CODE'
                ]
            }
        }
    }
  )
}}
SELECT
NULLIF(UPPER(TRIM(OFFICE_CODE::string)), '') AS OFFICE_CODE
,NULLIF(UPPER(TRIM(BRANCH_OFFICE_CODE::string)), '') AS BRANCH_OFFICE_CODE
,NULLIF(TRIM(ADDRSS1::string), '') AS ADDRSS1
,NULLIF(TRIM(ADDRSS2::string), '') AS ADDRSS2
,INITCAP(NULLIF(TRIM(CITY::string), '')) AS CITY
,UPPER(NULLIF(TRIM(ST::string), '')) AS ST
,INITCAP(NULLIF(TRIM(COUNTRY::string), '')) AS COUNTRY
,UPPER(NULLIF(TRIM(ZIP_CODE::string), '')) AS ZIP_CODE
,INITCAP(NULLIF(TRIM(NAME::string), '')) AS NAME
,NULLIF(REGEXP_REPLACE(PHONE,'[^\\d]*'), '')::string AS PHONE
--,FAX::string AS FAX --all null
--,ACTIVE::string AS ACTIVE --single value
--,TAX::string AS TAX --single value
,NULLIF(TRIM(TOLL_FREE::string), '') AS TOLL_FREE
--,DECK_CALC_SOFT::string AS DECK_CALC_SOFT -- single value
,UPPER(NULLIF(TRIM(QC_BRANCH_OFFICEUUID::string), '')) AS QC_BRANCH_OFFICE_UUID
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,LOWER(NULLIF(TRIM(CREATED_BY::string),'')) AS CREATED_BY
,LOWER(NULLIF(TRIM(MODIFIED_BY::string),'')) AS MODIFIED_BY
,IFNULL(RDM.STANDARD_APPLICATION_VALUE, 'Not Found') AS RDM_SALES_OFFICE_DEPARTMENT_CODE
,IFNULL(RDM1.STANDARD_APPLICATION_VALUE, 'Not Found') AS RDM_SALES_BRANCH_OFFICE_DEPARTMENT_CODE
,IFNULL(RDM.STANDARD_APPLICATION_VALUE_NAME_FR, 'Not Found') AS RDM_SALES_OFFICE_DEPARTMENT_NAME_FR
,IFNULL(RDM.STANDARD_APPLICATION_VALUE_NAME_EN , 'Not Found') AS RDM_SALES_OFFICE_DEPARTMENT_NAME_EN
,IFNULL(RDM1.STANDARD_APPLICATION_VALUE_NAME_FR, 'Not Found') AS RDM_SALES_BRANCH_OFFICE_DEPARTMENT_NAME_FR
,IFNULL(RDM1.STANDARD_APPLICATION_VALUE_NAME_EN , 'Not Found') AS RDM_SALES_BRANCH_OFFICE_DEPARTMENT_NAME_EN
from {{ref('prep_qc_branch_office')}} QBO
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM_SBODG 
    ON CONCAT(UPPER(TRIM(QBO.OFFICE_CODE)),UPPER(TRIM(QBO.BRANCH_OFFICE_CODE)))  = UPPER(RDM_SBODG.BUSINESS_APPLICATION_VALUE)
    AND UPPER(RDM_SBODG.BUSINESS_APPLICATION_DOMAIN_CODE) = 'SALESBRANCHOFFICEDEPARTMENTGROUP'
    AND UPPER(RDM_SBODG.STANDARD_DOMAIN_APPLICATION_CODE) = 'SALESBRANCHOFFICEDEPARTMENTGROUP' 
    AND UPPER(RDM_SBODG.BUSINESS_APPLICATION_CODE) = 'SPM'
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM
    ON UPPER(TRIM(QBO.OFFICE_CODE)) = UPPER(TRIM(RDM.BUSINESS_APPLICATION_VALUE)) 
    AND UPPER(RDM.BUSINESS_APPLICATION_DOMAIN_CODE) = 'SALESOFFICEDEPARTMENT'
    AND UPPER(RDM.STANDARD_DOMAIN_APPLICATION_CODE) = 'SALESOFFICEDEPARTMENT' 
    AND UPPER(RDM.BUSINESS_APPLICATION_CODE) = 'SPM'
LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM1
    ON UPPER(TRIM(QBO.BRANCH_OFFICE_CODE)) = UPPER(TRIM(RDM1.BUSINESS_APPLICATION_VALUE)) 
    AND UPPER(RDM1.BUSINESS_APPLICATION_DOMAIN_CODE) = 'SALESBRANCHOFFICEDEPARTMENT'
    AND UPPER(RDM1.STANDARD_DOMAIN_APPLICATION_CODE) = 'SALESBRANCHOFFICEDEPARTMENT' 
    AND UPPER(RDM1.BUSINESS_APPLICATION_CODE) = 'SPM'
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'