{{
  config(
    materialized = "view",
    alias = "item_technical_property",
    schema='spm_gdm'
  )
}}

SELECT
 ITEM_TECHNICAL_PROPERTY_UUID::string AS ITEM_TECHNICAL_PROPERTY_UUID
,GLOBAL_ITEM_UUID::string AS GLOBAL_ITEM_UUID
,TECHNICAL_DESCRIPTION_NAME_ID::INTEGER AS TECHNICAL_DESCRIPTION_NAME_ID
,NOMINAL_HEIGHT::DOUBLE AS NOMINAL_HEIGHT
,NOMINAL_WIDTH::DOUBLE AS NOMINAL_WIDTH
,NOMINAL_THICKNESS::DOUBLE AS NOMINAL_THICKNESS
,NOMINAL_SURFACE::DOUBLE AS NOMINAL_SURFACE
,UNFOLDED_LENGTH::DOUBLE AS UNFOLDED_LENGTH
,PAINTING_SURFACE::DOUBLE AS PAINTING_SURFACE
,MASTER_ITEM_UUID::string AS MASTER_ITEM_UUID
,ITEM_FINISHING_UUID::string AS ITEM_FINISHING_UUID
,WIDTH_TOLERANCE::DOUBLE AS WIDTH_TOLERANCE
,THICKNESS_TOLERANCE_MIN::DOUBLE AS THICKNESS_TOLERANCE_MIN
,THICKNESS_TOLERANCE_MAX::DOUBLE AS THICKNESS_TOLERANCE_MAX
,FABRICATION_CODE::string AS FABRICATION_CODE
FROM {{ref('prep_item_technical_property')}}