{{
  config(
    materialized = "view",
    alias = "customer",
    schema='spm_gdm'
  )
}}
  SELECT
 TRIM(CUSTOMER_UUID::string) AS CUSTOMER_UUID
,UPPER(TRIM(CUST_NO::string)) AS CUST_NO
,UPPER(TRIM(NAME::string)) AS NAME
,UPPER(NULLIF(TRIM(SORT_NAME::string), '')) AS SORT_NAME
,CUST_TYPE::INTEGER AS CUST_TYPE
,TO_BOOLEAN(PROSPECT::string) AS PROSPECT
,NULLIF(TRIM(ADDRESS1::string), '') AS ADDRESS1
,NULLIF(TRIM(ADDRESS2::string), '') AS ADDRESS2
,INITCAP(NULLIF(TRIM(CITY::string), '')) AS CITY
,UPPER(NULLIF(TRIM(COUNTY::string), '')) AS COUNTY
,UPPER(NULLIF(TRIM(ST::string), '')) AS ST
,UPPER(NULLIF(TRIM(COUNTRY::string), '')) AS COUNTRY
,NULLIF(TRIM(UPPER(REGEXP_REPLACE(ZIP_CODE::string,'[-\\s.*]',''))), '') AS ZIP_CODE
,NULLIF(REGEXP_REPLACE(TELEPHONE,'[^\\d]*'), '') AS TELEPHONE
--,TELEX_TWX::string AS TELEX_TWX -- column entirely NULL
,LANGUAGE_CODE::INTEGER AS LANGUAGE_CODE
,UPPER(NULLIF(TRIM(ORIG_CUST_NO::string), '')) AS ORIG_CUST_NO
,TO_BOOLEAN(AFFILIATED::string) AS AFFILIATED
,UPPER(NULLIF(TRIM(AFFILIATION_CODE::string), '')) AS AFFILIATION_CODE
,INITCAP(NULLIF(TRIM(CONTACT::string),'')) AS CONTACT
,LOWER(NULLIF(TRIM(INVOICING_TYPE::string), '')) AS INVOICING_TYPE
,NULLIF(TRIM(MEMO::string),'') AS MEMO
,NULLIF(TRIM(FST_LICENSE::string),'') AS FST_LICENSE
,NULLIF(TRIM(PST_LICENSE::string),'') AS PST_LICENSE
,TO_BOOLEAN(FST_EXEMPT::string) AS FST_EXEMPT
,TO_BOOLEAN(PST_EXEMPT::string) AS PST_EXEMPT
,INITCAP(NULLIF(TRIM(BUYER_NAME::string),'')) AS BUYER_NAME
,TO_BOOLEAN(ROYALTY::string) AS ROYALTY
,TO_BOOLEAN(ON_HOLD::string) AS ON_HOLD
,NULLIF(TRIM(ORIG_BILL_TO::string),'') AS ORIG_BILL_TO
,MAX_DECK_BUNDL_WEIGHT::INTEGER AS MAX_DECK_BUNDL_WEIGHT
,MAX_DECK_BUNDL_PIECES::INTEGER AS MAX_DECK_BUNDL_PIECES
,DECK_BUNDL_PIECES_TOLERANCE::INTEGER AS DECK_BUNDL_PIECES_TOLERANCE
,INITCAP(NULLIF(TRIM(SHOP_CITY::string),'')) AS SHOP_CITY
,UPPER(NULLIF(TRIM(SHOP_ST::string),'')) AS SHOP_ST
,UPPER(NULLIF(REPLACE(TRIM(SHOP_COUNTRY::string),'?',''),'')) AS SHOP_COUNTRY
,NULLIF(TRIM(UPPER(REGEXP_REPLACE(SHOP_ZIP_CODE::string,'[-\\s.*]',''))), '') AS SHOP_ZIP_CODE
,NULLIF(REGEXP_REPLACE(SHOP_PHONE::string,'[^\\d]*(0{9,})?(1{9,})?(2{9,})?(3{9,})?(4{9,})?(5{9,})?(6{9,})?(7{9,})?(8{9,})?(9{9,})?'), '') AS SHOP_PHONE
--,NULLIF(REGEXP_REPLACE(SHOP_FAX::string, '[^\\d]*(0{9,})?'),'') AS SHOP_FAX -- column entirely NULL
,TO_BOOLEAN(SPN_MEMBER::string) AS SPN_MEMBER
,NULLIF(TRIM(SHOP_ADDRESS1::string),'') AS SHOP_ADDRESS1
,NULLIF(TRIM(SHOP_ADDRESS2::string),'') AS SHOP_ADDRESS2
,TO_BOOLEAN(SUN_BUILDER_AUTHORIZED::string) AS SUN_BUILDER_AUTHORIZED
,NULLIF(TRIM(WEB_ADDRESS::string),'') AS WEB_ADDRESS
,TO_BOOLEAN(SHOP_LIKE_OFFICE::string) AS SHOP_LIKE_OFFICE
--,NULLIF(REPLACE(TRIM(EMAIL_ADDRESS::string),'?',''),'') AS EMAIL_ADDRESS -- column entirely NULL
,NULLIF(TRIM(QUOTATION_TRANSMISSION_MODE::STRING),'')::INTEGER AS QUOTATION_TRANSMISSION_MODE
,TO_BOOLEAN(LUMP_SUM::string) AS LUMP_SUM
--,NULLIF(REPLACE(TRIM(SALES_FAX::string),'0000000000',''),'') AS SALES_FAX -- column entirely NULL
--,NULLIF(REPLACE(TRIM(SALES_EMAIL_ADDRESS::string::string),'?',''),'') AS SALES_EMAIL_ADDRESS --column entirely NULL
,UPPER(NULLIF(TRIM(SHOP_COUNTY_CODE::string),'')) AS SHOP_COUNTY_CODE
,TO_BOOLEAN(ACTIVE::string) AS ACTIVE
,TO_BOOLEAN(ERECTOR_PRIVILEGE::string) AS ERECTOR_PRIVILEGE
,TO_BOOLEAN(COUNTERSALECUSTOMER::string) AS COUNTERSALECUSTOMER
,TO_BOOLEAN(SAPTRANSFER::string) AS SAPTRANSFER
,TO_TIMESTAMP_NTZ(LAST_UPDATED_DATETIME::string) AS LAST_UPDATED_DATETIME
,NULLIF(TRIM(ODS_ID::string),'') AS ODS_ID
--,ROW_ID::string AS ROW_ID -- we shouldn't use it except for debug
--,TO_TIMESTAMP_LTZ(IPAAS_UPDATED_DATE::string) AS IPAAS_UPDATED_DATE -- we shouldn't use it except for debug
,TO_TIMESTAMP_NTZ(CREATED_DATE::string) AS CREATED_DATE
,NULLIF(TRIM(CREATED_BY::string), '') AS CREATED_BY
,TO_TIMESTAMP_NTZ(MODIFIED_DATE::string) AS MODIFIED_DATE
,NULLIF(TRIM(MODIFIED_BY::string), '') AS MODIFIED_BY
,IFNULL(RDM_CC.STANDARD_APPLICATION_VALUE,'Not Found')                  AS RDM_CUSTOMER_CLASS_CODE
,IFNULL(RDM_CC.STANDARD_APPLICATION_VALUE_NAME_FR, 'Not Found')         AS RDM_CUSTOMER_CLASS_NAME_FR
,IFNULL(RDM_CC.STANDARD_APPLICATION_VALUE_NAME_EN, 'Not Found')         AS RDM_CUSTOMER_CLASS_NAME_EN
        FROM {{ref('prep_customer')}} C
            LEFT JOIN {{ref('gov_referencedata_rdm')}} RDM_CC
            ON UPPER(TRIM(C.AFFILIATION_CODE)) = UPPER(RDM_CC.BUSINESS_APPLICATION_VALUE)
                AND UPPER(RDM_CC.BUSINESS_APPLICATION_DOMAIN_CODE) = 'CUSTOMERCLASS'
                AND UPPER(RDM_CC.STANDARD_DOMAIN_APPLICATION_CODE) = 'CUSTOMERCLASS' 
                AND UPPER(RDM_CC.BUSINESS_APPLICATION_CODE) = 'SPM'     
QUALIFY ROW_NUMBER() OVER (PARTITION BY TABLE_SK ORDER BY QUALIFY_TIMESTAMP DESC) = 1 AND UPPER(TRIM(SRC_SYSTEM_OPERATION::STRING)) <> 'DELETE'